### ISSUE TITLE
Improperly Tagged TV Episodes

### ISSUE THREAD

**Issue by thedarkassassin101** [croneter/PlexKodiConnect#10]
My TV Episodes are linked to Movies not their appropriate TV Episode. I tested a multitude of my  Movies and they all seemed to be tagged properly, but the TV Episodes are a mess. When I try to play them I get movies not the TV Show. I have tried resetting the database files and the entire settings of the program with no success yet.

**Comment by croneter** [comment]
Are you playing episodes directly? Or are you first in the Kodi episode information screen and then start playback from there? 

Without a log file, I can't help you. Thanks if you reset your library, let PKC scan again, then start a "wrong" episode and capture [everything in the Kodi log file as described here](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug)

**Comment by thedarkassassin101** [comment]
I have it set to use the default method not the direct. I got the log file I think hopefully it is correct for you. http://xbmclogs.com/pcja6ozjw

**Comment by croneter** [comment]
Hmmm, can't find anything suspicious in your logs

* Upgrade to the newest PKC version 1.1.4. You were using 1.1.2. Do a library reset as suggested once you have updated!

If that still does not work:

* How do you start episode playback? Do you first go into the episode information screen (`i-Key`) where you see a lot of details for this one particular episode? Or do you start the episode instantly, e.g. from the "On Deck" view for episodes?

**Comment by thedarkassassin101** [comment]
Alright I will update and reset and hopefully that fixes it. I start the episode though through the normal way by surfing to TV Shows -> "Show Name" -> "Season" -> "Episode" -> Play. I am curious though if you plan to add the add on to a respository relatively soon as well if you don't mind me asking. I'm trying to figure out if it would be worth me writing a script to keep pulling the add on from the git every so often so it will never be out of date.

**Comment by croneter** [comment]
Don't - repo is on the way ;-)

**Comment by thedarkassassin101** [comment]
Updating fixed it.
