### ISSUE TITLE
Cant Playback with Force Transcode

### ISSUE THREAD

**Issue by KingGodzilla** [croneter/PlexKodiConnect#100]
Hey Guys i have following issue i cant Playback movies with Force Transcode maybe someone can me help out.
Running Kodi 16.1 and PlexKodiConnect 1.3.0

My Log File
10:58:15 T:1108  NOTICE: PLEX.playbackutils -> Play called.
10:58:15 T:1108  NOTICE: PLEX.playutils -> User chose to not direct play
10:58:15 T:1108  NOTICE: PLEX.playutils -> User chose to transcode
10:58:15 T:1108  NOTICE: PLEX.playutils -> File is transcoding.
10:58:15 T:1108  NOTICE: PLEX.playutils -> The playurl is: https://192.168.178.56:32400/video/:/transcode/universal/start.m3u8?X-Plex-Platform=Windows&X-Plex-Client-Platform=Windows&Connection=keep-alive&X-Plex-Device-Name=Kodi+%28DESKTOP-TSBE28C%29&X-Plex-Provides=player&X-Plex-Token=zh6Bf7UwsPzVm1gGzppz&X-Plex-Client-Identifier=b0bff778-624e-4203-b931-62ed38c61016&Accept=%2A%2F%2A&X-Plex-Device=Plex+Home+Theater&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=1.0.2&maxVideoBitrate=2000&videoQuality=100&protocol=hls&directPlay=0&fastSeek=1&partIndex=0&session=b0bff778-624e-4203-b931-62ed38c61016&path=%2Flibrary%2Fmetadata%2F3629&mediaIndex=0&videoResolution=1024x768&directStream=0
10:58:15 T:1108  NOTICE: PLEX.playbackutils -> Playlist start position: 0
10:58:15 T:1108  NOTICE: PLEX.playbackutils -> Playlist plugin position: 0
10:58:15 T:1108  NOTICE: PLEX.playbackutils -> Playlist size: 1
10:58:15 T:1108  NOTICE: PLEX.playbackutils -> Setting up properties in playlist.
10:58:15 T:1108  NOTICE: PLEX.playbackutils -> Processed as a playlist. First item is skipped.
10:58:15 T:7264   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.plexkodiconnect.movies/?dbid=141&mode=play&id=3629&filename=%2Flibrary%2Fmetadata%2F3629]
10:58:16 T:7220  NOTICE: PLEX.artwork -> Using Image Cache Thread Count: 25
10:58:16 T:7220  NOTICE: PLEX.downloadutils -> Request session does not exist: start one
10:58:16 T:7220  NOTICE: PLEX.downloadutils -> Requests session started on: https://192.168.178.56:32400
10:58:16 T:7220  NOTICE: PLEX.artwork -> Using Image Cache Thread Count: 25
10:58:16 T:7220  NOTICE: PLEX.playlist -> Initiated video playlist
10:58:16 T:7220  NOTICE: PLEX.playbackutils -> Play called.
10:58:16 T:7220  NOTICE: PLEX.playutils -> User chose to not direct play
10:58:16 T:7220  NOTICE: PLEX.playutils -> User chose to transcode
10:58:16 T:7220  NOTICE: PLEX.playutils -> File is transcoding.
10:58:16 T:7220  NOTICE: PLEX.playutils -> The playurl is: https://192.168.178.56:32400/video/:/transcode/universal/start.m3u8?X-Plex-Platform=Windows&X-Plex-Client-Platform=Windows&Connection=keep-alive&X-Plex-Device-Name=Kodi+%28DESKTOP-TSBE28C%29&X-Plex-Provides=player&X-Plex-Token=zh6Bf7UwsPzVm1gGzppz&X-Plex-Client-Identifier=b0bff778-624e-4203-b931-62ed38c61016&Accept=%2A%2F%2A&X-Plex-Device=Plex+Home+Theater&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=1.0.2&maxVideoBitrate=2000&videoQuality=100&protocol=hls&directPlay=0&fastSeek=1&partIndex=0&session=b0bff778-624e-4203-b931-62ed38c61016&path=%2Flibrary%2Fmetadata%2F3629&mediaIndex=0&videoResolution=1024x768&directStream=0
10:58:16 T:7220  NOTICE: PLEX.playbackutils -> Playlist start position: 1
10:58:16 T:7220  NOTICE: PLEX.playbackutils -> Playlist plugin position: 1
10:58:16 T:7220  NOTICE: PLEX.playbackutils -> Playlist size: 2
10:58:19 T:7220  NOTICE: PLEX.PlexAPI -> Plex did not provide ID for IMDB or TVDB. Start lookup process
10:58:19 T:7220  NOTICE: PLEX.PlexAPI -> No themoviedb match found using year 2016
10:58:19 T:7220  NOTICE: PLEX.PlexAPI -> Found themoviedb match for The Hateful 8: {u'poster_path': u'/uGAZgetAXpQhn1kAO09qroq55W0.jpg', u'title': u'The Hateful 8', u'overview': u'Irgendwo im verschneiten Wyoming, einige Jahre nach dem B\xfcrgerkrieg: Eine Postkutsche k\xe4mpft sich auf dem Weg zum St\xe4dtchen Red Rock durch die Landschaft. An Bord sind der Kopfgeldj\xe4ger John Ruth, seine Gefangene Daisy Domergue und zwei erst auf dem Weg zugestiegene Passagiere: der Ex-Soldat und nun ebenfalls als Kopfgeldj\xe4ger t\xe4tige Marquis Warren sowie Chris Mannix, der angibt, der neue Sheriff von Red Rock zu sein. Aufgrund eines heftigen Schneesturms sind sie jedoch dazu gezwungen, in einer H\xfctte Zuflucht zu suchen. Dort verstecken sich bereits der Mexikaner Bob, der undurchsichtige Oswaldo Mobray, der Cowboy Joe Gage und der in die Jahre gekommene S\xfcdstaaten-General Sanford Smithers vor dem Wetter. Schnell nehmen die Spannungen in der Gruppe von misstrauischen Raubeinen zu, nachdem man sich anfangs noch bestens unterhalten hat. Und bald wird klar, dass l\xe4ngst nicht jeder von ihnen die H\xfctte lebend verlassen wird.', u'release_date': u'2015-12-25', u'popularity': 6.72468, u'original_title': u'The Hateful Eight', u'backdrop_path': u'/sSvgNBeBNzAuKl8U8sP50ETJPgx.jpg', u'vote_count': 2012, u'video': False, u'adult': False, u'vote_average': 7.31, u'original_language': u'en', u'id': 273248, u'genre_ids': [80, 18, 9648, 37]}
10:58:20 T:7220  NOTICE: PLEX.playbackutils -> Play as a regular item.
10:58:21 T:1868  NOTICE: PLEX.artwork -> Using Image Cache Thread Count: 25
10:58:22 T:7264  NOTICE: Previous line repeats 1 times.
10:58:22 T:7264  NOTICE: DVDPlayer: Opening: https://192.168.178.56:32400/video/:/transcode/universal/start.m3u8?X-Plex-Platform=Windows&X-Plex-Client-Platform=Windows&Connection=keep-alive&X-Plex-Device-Name=Kodi+%28DESKTOP-TSBE28C%29&X-Plex-Provides=player&X-Plex-Token=zh6Bf7UwsPzVm1gGzppz&X-Plex-Client-Identifier=b0bff778-624e-4203-b931-62ed38c61016&Accept=%2A%2F%2A&X-Plex-Device=Plex+Home+Theater&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=1.0.2&maxVideoBitrate=2000&videoQuality=100&protocol=hls&directPlay=0&fastSeek=1&partIndex=0&session=b0bff778-624e-4203-b931-62ed38c61016&path=%2Flibrary%2Fmetadata%2F3629&mediaIndex=0&videoResolution=1024x768&directStream=0&audioStreamID=9123&audioBoost=0&skipSubtitles=1
10:58:22 T:7264 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
10:58:22 T:5912  NOTICE: Creating InputStream
10:58:22 T:5912  NOTICE: Creating Demuxer
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.kodi.tv	TRUE	/	FALSE	1494054653	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.thetvdb.com	TRUE	/	FALSE	1504733356	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.thetvdb.com	TRUE	/	FALSE	1504733356	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.thetvdb.com	TRUE	/	FALSE	1504733356	__cfdui	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.thetvdb.com	TRUE	/	FALSE	1504733356	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.thetvdb.com	TRUE	/	FALSE	1504733356	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.thetvdb.com	TRUE	/	FALSE	1504733356	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.ly_.kodi.tv	TRUE	/	FALSE	1494054653	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.pOnly_.thetvdb.com	TRUE	/	FALSE	1504733356	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.ly_.kodi.tv	TRUE	/	FALSE	1494054653	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.tmdb.org	TRUE	/	FALSE	1504733351	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.pOnly_.thetvdb.com	TRUE	/	FALSE	1504733356	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	__cfdui	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.thetvdb.com	TRUE	/	FALSE	1504733356	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.kodi.tv	TRUE	/	FALSE	1494054653	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.kodi.tv	TRUE	/	FALSE	1494054653	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.ly_.kodi.tv	TRUE	/	FALSE	1494054653	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.ly_.kodi.tv	TRUE	/	FALSE	1494054653	__cfdui	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.fanart.tv	TRUE	/	FALSE	1504733359	__cfdui	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.etvdb.com	TRUE	/	FALSE	1504733356	__cfdui	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.ly_.kodi.tv	TRUE	/	FALSE	1494054653	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.etvdb.com	TRUE	/	FALSE	1504733356	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.fanart.tv	TRUE	/	FALSE	1504733359	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.fanart.tv	TRUE	/	FALSE	1504733353	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.ly_.kodi.tv	TRUE	/	FALSE	1494054653	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'RUE	FALSE	/	FALSE	1494054653	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'E	FALSE	/	FALSE	1504733356	__cfdui	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.fanart.tv	TRUE	/	FALSE	1504733353	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.fanart.tv	TRUE	/	FALSE	1504733359	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tvdb.com	TRUE	/	FALSE	1504733356	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.ly_.kodi.tv	TRUE	/	FALSE	1494054653	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'E	FALSE	/	FALSE	1504733356	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.kodi.tv	TRUE	/	FALSE	1494054653	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.etvdb.com	TRUE	/	FALSE	1504733356	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'RUE	FALSE	/	FALSE	1494054653	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.etvdb.com	TRUE	/	FALSE	1504733356	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tvdb.com	TRUE	/	FALSE	1504733356	__cfdui	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'TRUE	FALSE	/	FALSE	1494054653	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tvdb.com	TRUE	/	FALSE	1504733356	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.fanart.tv	TRUE	/	FALSE	1504733353	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'TRUE	FALSE	/	FALSE	1494054653	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.etvdb.com	TRUE	/	FALSE	1504733356	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'E	FALSE	/	FALSE	1504733356	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tvdb.com	TRUE	/	FALSE	1504733356	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.etvdb.com	TRUE	/	FALSE	1504733356	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'E	FALSE	/	FALSE	1504733353	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tvdb.com	TRUE	/	FALSE	1504733356	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.v	TRUE	/	FALSE	1504733353	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'TRUE	FALSE	/	FALSE	1494054653	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.etvdb.com	TRUE	/	FALSE	1504733356	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.fanart.tv	TRUE	/	FALSE	1504733353	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'E	FALSE	/	FALSE	1504733356	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'TRUE	FALSE	/	FALSE	1494054653	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'TRUE	FALSE	/	FALSE	1494054653	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'TRUE	FALSE	/	FALSE	1504733356	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'E	FALSE	/	FALSE	1504733356	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.vdb.com	TRUE	/	FALSE	1504733356	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'E	FALSE	/	FALSE	1504733356	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tvdb.com	TRUE	/	FALSE	1504733356	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'LSE	FALSE	/	FALSE	1494054653	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.kodi.tv	TRUE	/	FALSE	1494054653	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'RUE	FALSE	/	FALSE	1494054653	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tvdb.com	TRUE	/	FALSE	1504733356	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'RUE	FALSE	/	FALSE	1504733356	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.vdb.com	TRUE	/	FALSE	1504733356	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.vdb.com	TRUE	/	FALSE	1504733356	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'RUE	FALSE	/	FALSE	1494054653	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.v	TRUE	/	FALSE	1504733353	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.v	TRUE	/	FALSE	1504733353	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.v	TRUE	/	FALSE	1504733353	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'LSE	FALSE	/	FALSE	1494054653	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'LSE	FALSE	/	FALSE	1494054653	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'LSE	FALSE	/	FALSE	1494054653	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.vdb.com	TRUE	/	FALSE	1504733356	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.v	TRUE	/	FALSE	1504733353	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'UE	FALSE	/	FALSE	1504733356	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'FALSE	FALSE	/	FALSE	1494054653	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.Only_.kodi.tv	TRUE	/	FALSE	1494054653	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.db.com	TRUE	/	FALSE	1504733356	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.db.com	TRUE	/	FALSE	1504733356	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'FALSE	FALSE	/	FALSE	1494054653	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.db.com	TRUE	/	FALSE	1504733356	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'TRUE	FALSE	/	FALSE	1494054653	__cfduid	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.com	TRUE	/	FALSE	1504733356	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tpOnly_.tmdb.org	TRUE	/	FALSE	1504733367	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.Only_.kodi.tv	TRUE	/	FALSE	1494054653	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.Only_.kodi.tv	TRUE	/	FALSE	1494054653	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.Only_.kodi.tv	TRUE	/	FALSE	1494054653	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'FALSE	FALSE	/	FALSE	1494054653	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.Only_.kodi.tv	TRUE	/	FALSE	1494054653	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.db.com	TRUE	/	FALSE	1504733356	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.om	TRUE	/	FALSE	1504733356	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.Only_.kodi.tv	TRUE	/	FALSE	1494054653	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.om	TRUE	/	FALSE	1504733356	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.di.tv	TRUE	/	FALSE	1494054653	__cfdu	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.om	TRUE	/	FALSE	1504733356	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tv	TRUE	/	FALSE	1494054653	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'UE	FALSE	/	FALSE	1504733356	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'TRUE	FALSE	/	FALSE	1494054653	__cfdui	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'LSE	FALSE	/	FALSE	1494054653	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.di.tv	TRUE	/	FALSE	1494054653	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.om	TRUE	/	FALSE	1504733356	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.di.tv	TRUE	/	FALSE	1494054653	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'FALSE	FALSE	/	FALSE	1494054653	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tv	TRUE	/	FALSE	1494054653	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.di.tv	TRUE	/	FALSE	1494054653	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.com	TRUE	/	FALSE	1504733356	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'FALSE	FALSE	/	FALSE	1494054653	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.om	TRUE	/	FALSE	1504733356	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.di.tv	TRUE	/	FALSE	1494054653	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.di.tv	TRUE	/	FALSE	1494054653	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '#HttpOnly_.kodi.tv	TRUE	/	FALSE	1494054653	__cfdui	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.com	TRUE	/	FALSE	1504733356	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.db.com	TRUE	/	FALSE	1504733356	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'LSE	FALSE	/	FALSE	1494054653	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.tv	TRUE	/	FALSE	1494054653	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'SE	FALSE	/	FALSE	1504733356	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'SE	FALSE	/	FALSE	1494054653	__	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'SE	FALSE	/	FALSE	1504733356	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'SE	FALSE	/	FALSE	1504733356	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.HttpOnly_.kodi.tv	TRUE	/	FALSE	1494054653	__cf	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: 'FALSE	FALSE	/	FALSE	1494054653	__cfd	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.HttpOnly_.kodi.tv	TRUE	/	FALSE	1494054653	_	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.db.com	TRUE	/	FALSE	1504733356	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '.com	TRUE	/	FALSE	1504733356	__c	'
10:58:22 T:5912   ERROR: CCurlFile::GetCookies - invalid cookie: '192.168.178.56	FALSE	/	FALSE	1597363199	SESSION	'
10:58:25 T:1868  NOTICE: PLEX.artwork -> Using Image Cache Thread Count: 25
10:58:26 T:1868  NOTICE: Previous line repeats 3 times.
10:58:26 T:1868  NOTICE: PLEX.librarysync -> TVShows sync is finished.
10:58:26 T:1868  NOTICE: PLEX.artwork -> Using Image Cache Thread Count: 25
10:58:26 T:1868  NOTICE: PLEX.librarysync -> Path hack successful
10:58:26 T:1868  NOTICE: PLEX.librarysync -> Initial start-up full sync successful
10:58:26 T:8552  NOTICE: VideoInfoScanner: Starting scan ..
10:58:26 T:8552  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
10:58:52 T:5912   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
10:58:52 T:5912  NOTICE: CDVDPlayer::OnExit()
10:58:52 T:7264   ERROR: Playlist Player: skipping unplayable item: 1, path [plugin://plugin.video.plexkodiconnect.movies/?dbid=141&mode=play&id=3629&filename=%2Flibrary%2Fmetadata%2F3629]
10:58:52 T:7264  NOTICE: CDVDPlayer::CloseFile()
10:58:52 T:7264  NOTICE: DVDPlayer: waiting for threads to exit
10:58:52 T:7264  NOTICE: DVDPlayer: finished waiting
10:58:52 T:7264  NOTICE: CDVDPlayer::CloseFile()
10:58:52 T:7264  NOTICE: DVDPlayer: waiting for threads to exit
10:58:52 T:7264  NOTICE: DVDPlayer: finished waiting
10:58:52 T:5884  NOTICE: PLEX.player -> ONPLAYBACK_STOPPED

My Settings
![kodi settings](https://cloud.githubusercontent.com/assets/18376824/18307252/e5a41726-74ef-11e6-963d-1f03b3a032dc.jpg)

**Comment by croneter** [comment]
Is this related to https://github.com/croneter/PlexKodiConnect/issues/66?

In other words: does it work if you deactivate subtitles?

**Comment by KingGodzilla** [comment]
Nope same issue with activated/deactivated subtitles.

**Comment by croneter** [comment]
Could you try again using the latest BETA PKC 1.3.2?

**Comment by KingGodzilla** [comment]
Oh man thank you it works :+1:

**Comment by croneter** [comment]
Very good, thanks for getting back here and telling us ;-)
