### ISSUE TITLE
problems with larges libraries

### ISSUE THREAD

**Issue by rafasilv** [croneter/PlexKodiConnect#1000]
I got a large library. I noticed some difficulties even after full sync, sometimes plexkodiconnect crashes. My solution was to cast from my plex android app. Any advice?

**Comment by croneter** [comment]
PKC should deal well with large libraries. Your issue is very unspecific. At least I need the Kodi DEBUG log files after pkc crashes, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
@rafasilv no log file no help possible. Please share your debug log file according to https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
No log, no advice possible
