### ISSUE TITLE
Play Count Reported Back Incorrectly to PMS

### ISSUE THREAD

**Issue by louderthanconcorde** [croneter/PlexKodiConnect#1003]
When a movie or TV is played through PKC, the play count is recorded twice on the PMS Dashboards in the Web App. The cause seems to be PMS marking the video as played when it reaches the default 90% watch point (as it would in any Plex app) but then marking it as played again when the video finishes playing in Kodi. As a result, play counts for all videos are inflated.

**Comment by croneter** [comment]
Good catch! Should be solved in BETA version 2.9.10

**Comment by louderthanconcorde** [comment]
Confirmed fixed in 2.9.10. Thank you!
