### ISSUE TITLE
OSMC PlexForKodi doesn’t honor RESUME

### ISSUE THREAD

**Issue by vogelap** [croneter/PlexKodiConnect#1007]
If I watch part of a movie/show on my Plex server on my Windows 10 64-bit PC or on my OSMC RasPlex and then try to resume it from PlexForKodi in OSMC on my Raspberry Pi 3b+, the show resumes at the correct time BUT the timebar (horizontal bar that runs along the bottom of the screen showing how far I am into the show) flashes the correct timestamp briefly and when the show begins to play it resets to 00:00. If I fast-forward or reverse, it does it relative to the incorrect timestamp.

I would like the timestamp to be correctly reflected in the horizontal timebar and stored correctly when I stop watching the show.

https://forums.plex.tv/t/osmc-plexforkodi-doesnt-honor-resume/456423

Here's a sanitized kodi.log... https://pastebin.com/hTgjpLNx

**Comment by croneter** [comment]
Ouh sorry, this concerns Plex for Kodi and not PlexKodiConnect :see_no_evil:. You can try posting on Plex' github: https://github.com/plexinc/plex-for-kodi/issues

I cannot help you
