### ISSUE TITLE
Random items suddenly marked as played

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#101]
I've had a look through the issues, but I can't see anything similar - is anyone else experiencing random items showing up as being watched in their library?

Setup:
LibreElec 7.90.004 (Kodi Alpha 3)
PlexKodiConnect 1.3 (from repo)
Plex home user account (called 'Home'), which has access to all libraries on the PMS.

Every now and then a random episode from a random will show as having been watched, so a new show will appear in the 'In Progress' TV shows. Normally it's a show that the 'home' user is unlikely to have watched on purpose - eg. a random episode in the middle of a series. The episode status changes in the PMS for that user too. If I look in plexpy I can see that the home user has never watched that show (or any other user for that matter).
Hard to tell if it's a plex bug randomly marking an episode as watched, or a PKC bug updating the wrong entry from the DB somewhere...

**Comment by croneter** [comment]
Have you entered your PMS IP manually? Try toggling the [PKC Connection Setting](https://github.com/croneter/PlexKodiConnect/wiki/PKC-settings#connection)  `I own this Plex Media Server`

I'll have to think of a way to do this automatically, rather annoying how Plex handles PMS messages of who is playing what.

**Comment by croneter** [comment]
Anyone having this issue?!? Logs would be much appreciated

**Comment by hstamas** [comment]
Im seeing this too in movies but it took so long to notice I don't think logs are going to help. Movies that have long since been watched are now showing as unwatched. It's pretty random what is marked u watched. 
I've also been playing around with other clients and using Trakt to sync so I wonder if that has something to do with it?

**Comment by croneter** [comment]
Hmm, not good. Will be almost impossible to pin down without logs. 

If your Kodi is running 24/7, the "event" might still be captured. Just note down the plex id of the movie/episode that is affected. The log can than be search for that id. To do that, simply navigate to that element in Plex web. Copy the last digits of the URL, so e.g. 
```
https://192.168.0.2:32400/web/index.html?_escaped_fragment_=/dashboard#!/server/<STRING>/details/%2Flibrary%2Fmetadata%2F146846
```
Just get the `146846`

**Comment by croneter** [comment]
By the way - are these items marked as played on the PMS? Or on kodi only?

**Comment by hstamas** [comment]
Mine are on PMS as well. Its still happening as of last night but again, since I have been messing around with Trakt I cant tell if its PKC or Trakt messing things up? Did my log I sent you via the Plex forums show anything?

**Comment by croneter** [comment]
Got it, yes. But I cannot tell you anything without you giving me some Plex ids on the way for the items that changed ;-). Or you can simply search for them yourself. See my post above

**Comment by hstamas** [comment]
OK here is one. Gravity. 4595. I watched that movie ages ago yet it is now listed as unwatched on my PMS.

**Comment by croneter** [comment]
Nothing suspicious in the log, only normal updates because the item changed on the PMS side.

I checked my library and I don't see anything suspicious, i.e. the wrong items as marked played/unplayed. Your issues might really stem from Trakt :-/

**Comment by hstamas** [comment]
I what way did the item change? Does the log indicate that? It was watched over a year ago and has just sat in my library ever since.

**Comment by croneter** [comment]
Don't know - the PMS does not tell you how it changed :-(

**Comment by croneter** [comment]
This still an issue? Has never happened to me as far as I can tell

**Comment by hstamas** [comment]
This has stopped for me. My thinking is that Trakt was the problem not PKC. Will keep any eye open but I think this is now a non issue.
