### ISSUE TITLE
Song takes 15 seconds to start playing

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#1020]
> I noticed that when listening to music there is a pause of about 15 seconds between each track. Is there a way to switch these pauses off or at least reduce them?

**Comment by croneter** [comment]
How do you play sour songs - where do you start your songs from?

**Comment by croneter** [comment]
@Squippy61 thanks but I meant Kodi-wise :laughing:. How exactly do you navigate within Kodi to start playing your songs?

**Comment by Squippy61** [comment]
Oops, sorry, I got you wrong 😉. KODi runs without interruption every day. When I open the virtual desktop, the 'Music' category is open. On the right are the albums. I click on an album and then on the first track to listen to the whole album or on a track in the middle to listen to it. I hope I've answered your question correctly now. I can also do screenshots if necessary.

**Comment by croneter** [comment]
You have tons of there error messages in the log:
```
ERROR: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for https://192-168-178-24.c5c48ff0435f454ab84d2e22cc148bda.plex.direct:32400/library/parts/1/1568462868/
```
as well as 
```
ERROR: CCurlFile::Exists - Failed: Couldn't connect to server(7) for https://217-94-251-124.c5c48ff0435f454ab84d2e22cc148bda.plex.direct:32400/photo/:/transcode?width=1920&height=1920&minSize=1&upscale=0&url=/library/metadata/57797/thumb/1571367258&X-Plex-Token=abc
```
Seems like a network issue to me. I also could not replicate the issue with my setup. 

Try the following:
1. Reconnect to your PMS by going to the PKC settings, `Connection`, then `List PMS in a list`. Pick your PMS again. 
2. Reset the Kodi database (to get rid of old, invalid URLs like the ones above) by going to `Advanced`, then `Reset the Kodi database ...` (in red). Hit Yes, then No

**Comment by croneter** [comment]
That should solve your issue. Please let me know here if this is not the case.
