### ISSUE TITLE
Lag on Raspberry Pi with 10-bit videos: activate force transcode for H265 as a fix

### ISSUE THREAD

**Issue by KiokiN** [croneter/PlexKodiConnect#1044]
On the Raspberry Pi, trying to playback 10-bit video causes intense lag, however, if you enable the option to force H265 on video 1080p and higher, it completely fixes this issue. I think it would be helpful for new users if you made this option the default for Raspberry Pi's.

**Comment by croneter** [comment]
Thanks for the hint. My Raspberry Pi can't deal with ANY H265 media, whether or not 10-bit video...

Nope, I currently don't want to change default setups depending on both the player as well as the media. That would increase complexity immensly.

**Comment by KiokiN** [comment]
Understandable. I'd imagine adding a check would be tedious. Thanks for responding.

**Comment by thisfro** [comment]
Hi @KiokiN 
Do you have a raspberry pi 3? I have the problem that transcoding does barely work. It has to cache every 30s or so and then audio gets out of sync or fails to play at all and so,etimes the video just starts over. Does this work fine on your raspi?
