### ISSUE TITLE
Quality Settings

### ISSUE THREAD

**Issue by Darg1** [croneter/PlexKodiConnect#105]
Forgive me if I'm imagining this but I could have sworn that, when I first set up PKC, there was a settings menu within PKC for adjusting the video quality for Local, Remote and something else (online maybe?).   If it was indeed there, I cannot for the life of me find it now.   Am I imagining it or am I just not navigating to the right place?    Thanks

**Comment by croneter** [comment]
Not that I remember :-). 

There's only 1 quality setting you can choose: in the [PKC settings under Playback](https://github.com/croneter/PlexKodiConnect/wiki/PKC-settings#playback), `Video quality`

**Comment by Darg1** [comment]
Thanks!  I must have still been thinking of plexbmc.
