### ISSUE TITLE
Photos not showing

### ISSUE THREAD

**Issue by chernyshaw** [croneter/PlexKodiConnect#1053]
I have a problem with photos in PKC.
I'm trying to view photos through Add-ons → Picture add-ons → PlexKodiConnect → Photos → All Photos → here I have folders with photos.

I see all the folders and all the photos in them, I see a preview on the left and in the background for each photo, but I can not see the photos themselves. When I try to open them, Kodi waits a second and shows nothing.

Those photos that I tried to view, I can see their properties. Other photos have no such option.
I can add any photo to my favorites. In my favorites, I can even view those photos that I tried to view through PKC. Other photos in favorites do not open.

I tried PKC on lastest OSMC and LibreELEC on Raspberry Pi 3B +. I tried the lastest stable and beta version of PKC. And I tried Plex server on Windows 10 and Debian. I am using Add-on path.

Here is the part of the log file where I tried to open some photos: https://pastebin.com/tasvHNAH

**Comment by chernyshaw** [comment]
Perhaps this is a [Kodi problem](https://forum.kodi.tv/showthread.php?tid=325083) that has existed since at least [2015](https://forum.kodi.tv/showthread.php?tid=236988).

**Comment by croneter** [comment]
Solved with PKC version 2.12.10 or 3.0.5. Let me know here should this not be the case...
