### ISSUE TITLE
External subtitles idx/sub not working

### ISSUE THREAD

**Issue by JoshBeer** [croneter/PlexKodiConnect#1055]
Hi,

similar to the problem that existed a few weeks ago it now seems that external subtitles are not working when in sub/idx format. They even don't show up so there is no way to activate them.
External srt is working and "internal" (merged in the mkv) subtitles are also working.

Can someone confirm? I'm on the stable branch.

Best regards

**Comment by JoshBeer** [comment]
I just double checked. Opening a few examples without PKC (directly from a local NAS) does indeed load the subtitles normally and also displays them if activated.

I also tried via Plex App and they are also displayed.
I'm pretty sure it's an PKC related issue.
Hopefully croneter can, once again, do some magic to get it working again. :)

**Comment by JoshBeer** [comment]
Sorry update again: Plex Addon in Kodi does offer the subtitles but does not display them.
Plex App on Fire TV Stick 4k does show the subtitles but only because they are transcoded/burned in.
So it could be a Plex Server (version 1.18.1.1973) issue after all.

Would be great if somebody could test.

**Comment by JoshBeer** [comment]
Downgraded to some random PMS version from a few months ago (1.16.6.1592) and the problem still persists, so not sure if the PMS is the problem.
@croneter If there is any log or something like that that I could provide then pls give me a shout.
I'm happy to provide anything that helps.

**Comment by croneter** [comment]
There is no reason why sub/idx should not work. However - did they ever work with PKC?

**Comment by JoshBeer** [comment]
Well to be honest I'm not entirely sure. Most of my library was with SRT and PGS subtitles. So it could be that I always displayed the srt versions.
But recently my library grew with PGS only content and thats when I noticed.
Could you check on your side if it works?
If it never worked do you think you could implement it?

**Comment by JoshBeer** [comment]
@croneter I just had the chance to check. I muxed the idx/sub into an mkv and it plays fine.
So it's definitely a problem with external idx/sub only.
Do you think you could have a look at this?
Also: Is there a way to downgrade PKC to a certain version? So I could check if it ever worked and maybe jsut broke with an update a few versions ago.

**Comment by croneter** [comment]
idx/sub subtitles should work in principle. However, in some cases they don't work on the Plex side, apparently: https://forums.plex.tv/t/subtitles-sub-idx-not-showing-anymore/473588

# Workaround
Use [PKC Direct Paths](https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths) and make sure the subtitle files are named correctly, lying in the same folder as the video. See here: https://kodi.wiki/view/Subtitles

**Comment by JoshBeer** [comment]
Hey croneter, I would be happy to try the workaround but I'm not sure it would work with my setup.
My media is on gdrive only. Does it even work that way?

**Comment by croneter** [comment]
As far as I know, gdrive does not work with PKC direct paths

**Comment by Quentin-M** [comment]
Seems that burn-in subs, or PGS subs, do not work in plex kodi connect. While the prompt asks for which subtitle to pick, they are not rendered in Kodi, nor are they available in the subs menu while the file is playing. The Plex backend does state that subtitles are playing.

**Comment by croneter** [comment]
Does PKC **beta** version 2.11.0 help?
