### ISSUE TITLE
Play wrong file...

### ISSUE THREAD

**Issue by direk** [croneter/PlexKodiConnect#106]
Hi,

I found this plugin very recently, installed it and it is almost perfect. One thing thou... While I want to play something from my PLEX library it almost always opens not selected file, but the first one on the list. After trying again it plays correct one.

**Comment by croneter** [comment]
Logs!! 

See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Sorry, but no log file, no issue...

I bet you did deactivate the trailers in the PKC settings? ;-)
