### ISSUE TITLE
Play 3d movies as 2d

### ISSUE THREAD

**Issue by sinterlkaas** [croneter/PlexKodiConnect#107]
Is there a possibility to play 3d movies as 2d using this addon?

**Comment by croneter** [comment]
That is technically impossible

**Comment by sinterlkaas** [comment]
Ok this is limited by plex I assume? Because I can play those 3d movies in 2d when I use kodi. 

I have to say when I use plex to play this same movie I am not able to force it as 2d

ps: talked about an sbs 3d movie

**Comment by hstamas** [comment]
I'm not at my media player ATM but wouldn't selecting the option to play 3D as 2D in Kodi work as usual? PKC has nothing to do with the actual displaying of the video.

**Comment by sinterlkaas** [comment]
this kept failing here and changed back

**Comment by croneter** [comment]
As mentioned, PKC has nothing to do with the actual playing of the video
