### ISSUE TITLE
python3: Not working with Kodi 19

### ISSUE THREAD

**Issue by tiagogaspar8** [croneter/PlexKodiConnect#1070]
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)
I have searched and found nothing close this if wrong.

## Describe the bug
I believe this happens because the PKC is not compatible with python3 and kodi has made the switch from python 2 to 3.

## To Reproduce
Install the plugin and try doing anything with it

## Expected behavior
It should just Work

## You need to attach a KODI LOG FILE!
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3889520/kodi.log)

**Comment by croneter** [comment]
As explained in the readme, Kodi 19 Matrix is not yet supported by PKC due to Python 3.

Pull requests are welcome. No need to open this issue though

**Comment by tiagogaspar8** [comment]
I'd help do the transition but I have no python skills.
Are there any plans to migrate?
