### ISSUE TITLE
Subtitle Issue with transcoding Hi10P files

### ISSUE THREAD

**Issue by Shadowkillerdragon** [croneter/PlexKodiConnect#1077]
I usually have the force transcode option for Hi10P files since my Odroid C2 isn't fast enough to direct play those files, works fine via hardware decoding with everything else luckily.

On the latest versions of PlexKodiConnect whenever I start playing a Hi10P file, I get the subtitle prompt and proceed to select the subtitle I want for the transcode. It begins the playback after some time but it doesn't not display the subtitles. Looking on the dashboard of the plex webclient, I can see it transcoding the video along with passing the subtitles from the server.

I tried multiple previous versions because I faintly remember not having this issue before. I testing different versions of PKC. I reverted to the Stable Release chain version 2.9.5 to get subtitles when transcoding. It doesn't seem like any of the newer versions work.

**Comment by redplanks** [comment]
I have the same issue: debug log attached.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3954152/kodi.log)

**Comment by croneter** [comment]
This is hard to troubleshoot.
* Is 2.9.5 the last PKC version where Hi10P subtitles worked? Beta or stable PKC?
* Is this an issue only for Hi10P videos? All others work?
* What kind of subtitles don't work, what does Plex Web tell you about the respective subtitle not working? (or working!)

**Comment by Shadowkillerdragon** [comment]
- 2.9.5 Stable is the last one where Hi10P subtitles worked. I tried all the newer versions, but it does not work in those versions. It only occurs when transcoding is required. 
I tried playback with my computer for testing since it is much snappier with making changes. With the force transcode option off and it was able to read it, since my main pc can direct play everything. Once force transcode of Hi10P is checked, it does not carry over the subtitles on transcode. That applies for all the versions past 2.9.5 Stable.

- As far as I know, I have only seen it occur with Hi10P videos, but that is only because those are the only video files that I transcode. I use a Odroid-C2 as my kodi client primarily, so it can direct play everything except the Hi10P files. It may occur on other files if I would need to transcode them, but I am unsure of how to force that when the C2 has hardware decoding for those files x264, x265/HEVC etc in order to try alternative formats with transcoding

- A snippet of the a few files are the following.

1. 
1080p (H.264 High 10) - 1080p (H.264) Transcode
DTS 5.1 - AAC Transcode
Unknown (ASS)

2.
1080p (H.264 High 10) - 1080p (H.264) Transcode
FLAC Stereo - AAC Transcode
English (ASS)

The only subtitle file I saw was ASS. The only main difference is the varying audio formats gets transcoded. On 2.9.5 Stable, all subtitles displayed when transcoding. On 2.10.4 Stable, none of the subtitles are displayed when transcoding. The same info is on Plex Web (#1 and #2) when playback for both versions of PKC. I tried about 10 or so random Hi10P files I had.

**Comment by croneter** [comment]
What if you force transcode a non-Hi10p video using the Kodi context menu?

**Comment by Shadowkillerdragon** [comment]
Just tried it with a few non Hi10P videos and it does not display subtitles when transcoding when using 2.10.4 Stable, but is fine on 2.9.5 Stable. Another thing I noticed was that it seems to have problems transcoding as well. It would have to transcode 1080p High 10 to 720p or SD quality on 2.10.4 vs 1080p High 10 to 1080p on 2.9.5 respectively to maintain smooth playback.

**Comment by croneter** [comment]
It works with `srt` subtitles. Could you please share an example subtitle file here that does not work - just upload it please. 

PKC now tries to avoid "burning in" a subtitle. Is the `ass` subtitle not a choice using the Kodi playback menu when selecting a subtitle?

**Comment by Shadowkillerdragon** [comment]
The srt subtitles you mentioned that it was working for. Are those external subtitles? I should be able to check I get home. 

The files I had tried had subtitles internal to the video. When I select a file with Hi10P force transcode enabled it does prompt the subtitle selection. I believe it is the same with doing so from the Kodi playback menu.

**Comment by croneter** [comment]
The `srt` are external, yes.

When you are able to select the `ass` subtitle from the Kodi playback menu as an active sub - problem solved 😆

**Comment by Shadowkillerdragon** [comment]
Yea they should be selectable but they don't display during playback. It typically goes as follows.

I select the video for transcode. It prompts selection of subtitles or none per available options. I select the desired subtitle playback occurs but no subtitles display. I am presuming this may only occur on videos with internal subtitles seeing as your test with external subs worked.

**Comment by croneter** [comment]
I am talking about you using the KODI playback dialog that you'll also get without Kodi - where you can select audio as well as subtitle streams during playback. I am NOT talking about the PKC dialog that pops up before you start playing a movie. 

Is the `ass` subtitle selectable and working in the Kodi playback dialog?

I'd still need a test `ass` file...

**Comment by Shadowkillerdragon** [comment]
Oh okay I understand what menu context you mean now. I should be able to try when I get home and get that test .ass file. I've just been replying on mobile since I'm in the office for another 6 hours

**Comment by Shadowkillerdragon** [comment]
Okay. I did more testing with the files that I had. 

- Transcode with srt subtitles works fine. 
- Direct Play with srt subtitles work fine.
- Direct Play with .ass subtitle works fine
- Transcode with .ass subs fail whether internal or external

For the question regarding the Kodi Context Menu for subtitles. They all show a selected subtitle file except when I transcode with .ass subtitle file. The subtitle option is grayed out and display none in that situation. Direct play with the same set of files the subtitle display the corresponding subtitle.

The following was the files I was testing with.
https://www.dropbox.com/sh/3qwngnasw75ggjw/AACySJGa4zkGk13BSYxKL7B3a?dl=0

**Comment by croneter** [comment]
OK thanks a lot! Please also share the movie metadata XML of the respektive movie with a non-working ass subtitle, See here: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/

**Comment by Shadowkillerdragon** [comment]
`<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="1" librarySectionTitle="Anime" librarySectionUUID="0875b27e-81ba-4637-9943-9b6199c3a0d9" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1574418295">
<Video ratingKey="7193" key="/library/metadata/7193" guid="com.plexapp.agents.none://f8a065ffdcb881b75cd2ef50d2943de7242fde8e?lang=xn" type="movie" title="Saint Seiya Episode 001" librarySectionTitle="Anime" librarySectionID="1" librarySectionKey="/library/sections/1" summary="" viewOffset="552098" lastViewedAt="1576642180" year="1970" thumb="/library/metadata/7193/thumb/1575363035" art="/library/metadata/7193/art/1575363035" duration="1461420" originallyAvailableAt="1970-01-01" addedAt="1409471350" updatedAt="1575363035" chapterSource="media" createdAtAccuracy="epoch,local" createdAtTZOffset="149640">
<Media id="7192" duration="1461420" bitrate="967" width="720" height="544" aspectRatio="1.33" audioChannels="2" audioCodec="aac" videoCodec="h264" videoResolution="480" container="mkv" videoFrameRate="24p" audioProfile="he-aac" videoProfile="high">
<Part accessible="1" exists="1" id="7192" key="/library/parts/7192/1409471350/file.mkv" duration="1461420" file="/media/Anime/Saint Seiya Anime/Saint Seiya/Saint Seiya Episode 001.mkv" size="176564236" audioProfile="he-aac" container="mkv" deepAnalysisVersion="4" requiredBandwidths="1335,1335,1335,1335,1335,1335,1335,1335" videoProfile="high">
<Stream id="24857" streamType="1" default="1" codec="h264" index="0" bitrate="967" language="日本語" languageCode="jpn" bitDepth="8" chromaLocation="left" chromaSubsampling="4:2:0" frameRate="23.976" hasScalingMatrix="0" headerCompression="1" height="544" level="51" profile="high" refFrames="16" requiredBandwidths="1274,1274,1274,1274,1274,1274,1274,1274" scanType="progressive" width="720" displayTitle="480p (H.264)"/>
<Stream id="24858" streamType="2" selected="1" default="1" codec="aac" index="1" channels="2" language="日本語" languageCode="jpn" profile="he-aac" requiredBandwidths="64,64,64,64,64,64,64,64" samplingRate="48000" displayTitle="日本語 (HE-AAC Stereo)"/>
<Stream id="24859" streamType="3" selected="1" default="1" codec="ass" index="2" language="English" languageCode="eng" requiredBandwidths="2,2,2,2,2,2,2,2" displayTitle="English (ASS)"/>
</Part>
</Media>
<Extras size="0"> </Extras>
</Video>
</MediaContainer>`

Sorry mess of the XML copy. I'm not sure how to do the formatting.
https://imgur.com/a/D1zZgiq

**Comment by jcphilips** [comment]
I had the same issue as @Shadowkillerdragon where Hi10P files do not display burned in subtitles even though the plex dashboard shows I have selected a subtitle file. As suggested above I tried it on some HEVC files with srt subs to confirm if the issue was limited to ass files but unfortunately that does not seem to be the case as other formats too did not display subtitles. So in my case it just seems like force transcoding breaks subtitles.

Direct play with ass subtitles (and srt) does work fine (tested with HEVC and Hi10P video).
All tests were using internal subs.

XML for test files -
[SRT HEVC](https://pastebin.com/PjCBvv31)
[SRT H264](https://pastebin.com/FxeaGSEb)
[ASS Hi10p](https://pastebin.com/CQcQbcZF)
[ASS HEVC](https://pastebin.com/mzEpxyiL)

**Comment by sca2511** [comment]
I'm also having the same issue with Hi10p files and .ASS subtitles. Would reverting back to 2.9.5 be a good workaround?

**Comment by jcphilips** [comment]
@sca2511 Yes. Subtitles work fine when force-transcoding with version 2.9.5 but not (stable) versions after.

**Comment by croneter** [comment]
Does PKC **beta** version 2.11.0 help?

**Comment by jcphilips** [comment]
Subs do now work on 2.11.0 but video quality is a lot worse compared to 2.9.5.

![image](https://user-images.githubusercontent.com/4137235/75116324-305cff80-568d-11ea-8f3c-b3dda4dbef1e.png)
2.11.0 seems to transcode audio as well for some reason.

![image](https://user-images.githubusercontent.com/4137235/75116201-da3b8c80-568b-11ea-93e2-fb8aa26f69e1.png)

**Comment by croneter** [comment]
@jcphilips video quality is due to your settings. Please change them in the PKC settings under Playback

**Comment by jcphilips** [comment]
Disabling auto-adjust transcode quality fixed it (I had video quality set to 1080p 40Mbps on both versions) although audio does still transcode to OPUS instead of direct streaming.

Ignoring these, the transcoding does renders subs perfectly fine now for other files too (tested HEVC with SRT subs).
