### ISSUE TITLE
Filter sync with existing kodi library 

### ISSUE THREAD

**Issue by darknessgp** [croneter/PlexKodiConnect#109]
In my setup, I've got an existing kodi library and then have a remote plex that houses random other media. These two are probably never going to be in sync. So I'll have some items only on kodi, some only on plex, but quite a few that will exist on both mostly  with plex having a SD version and local having an HD version. 

Because of this, I think the ideal situation would be to have an option in plexkodiconnect to not sync items that already exist in the kodi library. I know this will make the sync slower, but it would prevent cases where I have the same movie showing up twice, with no indication on where it's coming from. As well as, I'll always want to play my local copy anyways. Direct play could work, except when filenames don't line up between SD and HD. As well as the items that aren't on plex anyways.

**Comment by croneter** [comment]
This feature request was changed. 

NOT synching items that are already in the Kodi library is not going to be implemented. There is no way of telling with certainty which Plex item corresponds to which Kodi item
