### ISSUE TITLE
PKC showing the wrong info for some movie collections

### ISSUE THREAD

**Issue by spindle1** [croneter/PlexKodiConnect#1094]
On some of my movie collections it shows the right movie collection name, but for some reason on the right it will show the information and title for another movie collection. Once you go into the movie collection it does have the right movies in it though.

I have tried resetting everything etc, and the most it does is change the random movie that shows up on that right side info. It doesn't do this for every movie collection, just a few.

![PKC issue](https://user-images.githubusercontent.com/59537966/71783780-37cb2b00-2fb1-11ea-82d5-fa962e2243b2.png)

**Comment by croneter** [comment]
Does this issue persist if you change to another skin?

**Comment by croneter** [comment]
Could you give me a reply here please? What happens if you change to e.g. the standard Kodi skin Estuary?

**Comment by croneter** [comment]
No reply, no help possible
