### ISSUE TITLE
PKC Stops Syncing At 2000 Albums

### ISSUE THREAD

**Issue by quixote23** [croneter/PlexKodiConnect#1095]
I have a fairly large music collection (about 8850 albums in total) and I'm using PKC as a music library backend instead of Kodi's native music library. I have Direct Paths enabled.

I noticed a few months ago that while new albums are getting updated in Kodi during syncs, a lot of albums that exist in my Plex library are not showing up in Kodi. To rectify this, I've attempted  "Repair Kodi Database (Force Update)". While running, TV and Movies sync with no problem other than a brief pause at 2000 and 4000 episodes, but when Albums start to sync, it stops at 2000 albums and doesn't proceed any further no matter how long I leave it. 

I have not performed a full Kodi database reset because I'd like to avoid doing so if possible. However, I did delete and recreate my Plex music library from scratch and it didn't fix the problem. 

- Navigate to Add-Ons > PlexKodiConnect > Settings > Advanced
- Select 'Repair The Kodi Database (force update all content)'
- Sync starts (shows status in top right corner)
- Hangs at 2000th album

kodi.log: http://p.ip.fi/HFgK

**Comment by croneter** [comment]
What does "hang" mean? Will the sync indicator get stuck at 2000?

**Comment by quixote23** [comment]
Yes, that's correct. I can still use Kodi, but the sync indicator in the top right corner will stop at the 2000th album and display there indefinitely.

**Comment by croneter** [comment]
The log is huge, I can't really see it except the very beginning :see_no_evil: . But
* I'd highly suggest you move to Kodi 18. You're still using Kodi 17. 
* Could you please try the latest PlexKodiConnect BETA version? Simply install the second beta PKC repository, then install PKC again from there

**Comment by quixote23** [comment]
I'm using Kodi 17 because I rely on a branch of it called DSPlayer which allows madVR and external filter integration. 

However, I tried installing the PKC beta and it seems like this problem is now resolved! Thank you!
