### ISSUE TITLE
PlexKodiConnect cannot choose libraries or sync

### ISSUE THREAD

**Issue by ThyNameIsP** [croneter/PlexKodiConnect#1098]
I'm having an issue where whenever I load PKC, it will not actually bring in my libraries whether I do a manual sync, click to choose libraries to sync, etc. Will just give in the top right of Kodi a message that an unknown error occurred and to check log for details. As per instructions, I turned on debug logs and here is said log. I am using the latest version of Kodi, brand new install, and in this log I am using PKC 10.2 I believe (second newest in repository), but got the same error in the newest before uninstalling and reinstalling Kodi itself. Also, it logs into Plex just fine and if I go into, say, recently played on the video addon settings, I can play the videos. I just can't do anything with adding the libraries which is, well, a major problem. Here's the LOG ((hopefully with all tokens deleted, did a ctrl+f for the word token and removed what was thought as the relevant parts to be nixxed):
[[[log removed, no longer relevant]]]

**Comment by ThyNameIsP** [comment]
OK TO CLOSE:
Error was an issue on Plex's end. While my libraries were readable, they inadvertently got corrupt at one point when I transferred my database from an HDD to my new SSD. Rolled back to a month old backup and it now works.

**Comment by croneter** [comment]
Thanks for reporting back! :laughing:
