### ISSUE TITLE
Duplicate Movies & Unstable Message after Sync

### ISSUE THREAD

**Issue by tknice** [croneter/PlexKodiConnect#110]
Using Kodi 17 Krypton beta 2 and KodiPlexConnect 1.3.6 beta, a message appears saying there was a problem syncing and it may be unstable.  After this occurs, a number of movies have duplicate entries.

[kodi_092016.zip](https://github.com/croneter/PlexKodiConnect/files/482970/kodi_092016.zip)

If that link didn't work, here's another:

https://dl.dropboxusercontent.com/u/2416987/Misc%20Links/kodi_092016.zip

**Comment by croneter** [comment]
Darn, could you please enable debug logging in the PKC options, advanced and try again?

**Comment by croneter** [comment]
Have you switched users using PKC (so not just switching Kodi profiles)?

**Comment by tknice** [comment]
Oh no!   I didn't have debug logging enabled.   Okay, I'll delete the log
and try again.

No, I don't switch profiles on either.

**Comment by tknice** [comment]
I'm not sure if you mean PKC debug logging or Kodi debug logging in the
system screens but I have both enabled now.   When the Kodi debug is on, I
get data overlayed on the screen.  I don't think I'll be able to keep that
on while the family watches things.

The log could be pretty big!

Tom

**Comment by tknice** [comment]
No, when I tried to browse a movie with the web interface and change out the 10602 number at the end, it says media not found.

**Comment by tknice** [comment]
Looking through the logs, i think user in the error msgs (cookiekitty) is one of my friends accessing my server.  Would you expect profile changes/access to happen when its a remote user?   I wonder why that is generated so many errors.  Also, the server we are accessing here is not on the shield--its a dedicated server, so its strange that she is showing up in these kodi client logs.

**Comment by croneter** [comment]
Then above error messages have nothing to do with a profile or user switch. Is the user you use the Plex home master user of the PMS you are accessing?

**Comment by tknice** [comment]
Yes, I believe so, I think they are both tknice.  I'm confident my user on the server is tknice.  For the other, do you mean what shows up in PKC or Kodi or both?  I think they are all tknice.

**Comment by croneter** [comment]
OK! Thanks. Please try to get the debug log ;-)

**Comment by tknice** [comment]
Here's a new one croneter.  Again, overnight so sorry for the size.   It has duplicates and the instable error.

[kodi_092116.zip](https://github.com/croneter/PlexKodiConnect/files/485800/kodi_092116.zip)
https://dl.dropboxusercontent.com/u/2416987/Misc%20Links/kodi_092116.zip

**Comment by croneter** [comment]
Thank you very much! Try the new beta version and reset your Kodi db in the PKC settings, Advanced. Might help already

**Comment by tknice** [comment]
Will do, thanks!   Bouncing between work and this but I should be able to tell you something shortly.   Also, please mention if anything glaring jumps out from my logs that I can fix.  I'm just starting to get familiar with looking at them.   Is there any kind of parser for the kodi logs or are you just paging through?

**Comment by tknice** [comment]
I've got 1.3.7 loaded and logging.  :)

**Comment by tknice** [comment]
A few duplicates showed up but I haven't seen the unstable crash yet.  Looking at the folders of the movies that have duplicates, I thought maybe some of the extra files (like subs or jpgs) may be causing it so I deleted all but the mkv.  After PKC synced again, the dups are still there.   I can't find any reason why some have duplicates and others do not.

**Comment by tknice** [comment]
Hi croneter!   I haven't had an instable msg crash with 1.3.7 loaded so that's great!  I'm pretty sure I would have seen it by now.

**Comment by croneter** [comment]
Hmmm, these duplicates are a bit wierd. Can you choose "Reset videonodes and playlists" if you navigate to Video -> Video Addons -> PlexKodiConnect? Then reset the database again in the PKC settings, Advanced?

I see that another Kodi addon (Skinhelper) has some errors caused by a PKC video node. Maybe that leads to duplicates

**Comment by croneter** [comment]
You got many errors that I still don't understand. After the steps above, make **sure to enable PKC debug logging in the PKC settings** ;-) (because your last log wasn't a debug log ;-)). 

Then if you could just send me the log again, I would be very happy indeed! Thanks for you help, by the way, much appreciated

**Comment by tknice** [comment]
Sure thing, I'd like to get to the bottom of this as well!   I'm not seeing "Reset videonodes and playlists" anywhere.  Is this in PKC settings where the advanced > reset is?  I don't have a Video > Video Addons anywhere in the Kodi settings.

Also, regarding the debug, are you saying I need to have debug logging on at the Kodi level, or just under PKC settings?

**Comment by tknice** [comment]
I found it now--had to switch to the Estuary skin.  I reset that, then reset the database and set up PKC again with debug logging enabled (in the addon).   I don't have it enabled in the Kodi settings.

**Comment by tknice** [comment]
Something else I noticed--there were 2 entries for PLEX under Settings > Media Library > Videos so I removed the second one.  I don't know how that got there.

Will run for a bit with debug on in PKC settings and capture another log.

**Comment by tknice** [comment]
Lots of debug stuff showing in the logs.  Haven't seen duplicates yet.

**Comment by tknice** [comment]
We have duplicates, and this time the shield was never turned off (that was another theory I had).

[kodi_092216.zip](https://github.com/croneter/PlexKodiConnect/files/488570/kodi_092216.zip)

**Comment by croneter** [comment]
Could you figure out the Plex ids of some of these duplicates? I can then search for these ids in the log. 

To do that, use Plex web to navigate to a duplicate. Note the last digits in the URL. Many thanks for your patience :-)

**Comment by tknice** [comment]
Here you go.  These are all the duplicates from my Action/Adventure section which has a total count of 114.   Looks like 33 total dups or roughly 30% of the movies.   Each of my sections looks like this.

I don't know if all of these will be represented in the log file you have.   I can send you the latest log if that helps.   Thanks!

535 - Title: Battleship
1327 - Title: The Beastmaster
729 - Title: The Bourne Legacy
899 - Title: Cliffhanger
572 - Title: Con Air
1794 - Title: Die Hard with a Vengeance
625 - Title: The Expendables 2
962 - Title: Face/Off
835 - Title: The Fast and the Furious: Tokyo Drift
576 - Title: First Blood
963 - Title: Gone in Sixty Seconds
1008 - Title: A Good Day to Die Hard
1323 - Title: The Grandmasters
4219 - Title: Hercules
577 - Title: The Italian Job
573 - Title: Jurassic Park
11 - Title: Lockout
1553 - Title: Lone Survivor
8135 - Title: Jurassic World
12 - Title: Man on a Ledge
2593 - Title: Need for Speed
1066 - Title: Olympus Has Fallen
4236 - Title: The Purge: Anarchy
902 - Title: The Raid
2469 - Title: The Raid 2
1534 - Title: RED
2470 - Title: RoboCop
797 - Title: The Rock
578 - Title: Ronin
917 - Title: Safe
14 - Title: Sherlock Holmes: A Game of Shadows
586 - Title: Taken
1065 - Title: Tombstone

**Comment by croneter** [comment]
Wow, thanks for the work! Should suffice for now

**Comment by croneter** [comment]
Silly question - changing the Kodi skin doesn't fix it?

**Comment by tknice** [comment]
Let me check with the default Estuary skin.  I don't tend to use that one because I don't think you can create shortcuts and all of the movies are in one place.

**Comment by tknice** [comment]
Switching to Estuary and they are all still there under movies.   Should I go ahead and clear things again by resetting PKC and run with Estuary for a few days?

**Comment by croneter** [comment]
No, that would not help. It's a PKC and not skin issue then ;-)

**Comment by croneter** [comment]
Is there a second PMS in your network?

**Comment by tknice** [comment]
I think there is one in the Shield (as of 3.2 update) but it's turned off.   I can confirm.

**Comment by croneter** [comment]
So there is a second PMS? What does that one's web interface tell you about the id `1327`?

**Comment by tknice** [comment]
Okay, so the PMS on the Nvidia shield is definitely stopped (and it doesn't need PKC anyway).  I can get to it with a web interface when it's stopped.  The only one my web interface shows is my main server (called HTServer).

No, I don't use the Plex DVR.

**Comment by croneter** [comment]
Might not matter whether that second Plex Media Server (!!, not a Plex Client!) is shut off now, but was on at some point in the past. Do turn it on and see which item has number `1327`

**Comment by tknice** [comment]
Where do I see 1327?

**Comment by tknice** [comment]
Oh you mean movie 1327?   The ShieldServer does not have any media on it at all.

**Comment by tknice** [comment]
I turned the ShieldServer back off.  

Also did a clean library in Kodi settings and everything disappeared, then ran the force database update in PKC to reload the database.  Everything looks now with no duplicates. 

I'll see what happens on the next few PKC refreshes.

Incidentally, I wasn't running the latest Kodi beta back then, but this problem didn't appear until (I want to say) PKC 1.3.3.   I was on 1.3.2 for quite a while and saw no duplicates.

**Comment by tknice** [comment]
heya cron, dupes again.  I think just some time needs to pass for it to occur

**Comment by croneter** [comment]
Darn. For the entire time since your last database reset, was there only ONE Plex Media Server turned on?

I'll push an update tonite, maybe that one will help

**Comment by tknice** [comment]
Yep, only one server going on my network. Watching football today with
friends but I will look for the update later. Thanks!

Oh, one other side note that I dont think affects anything but there ARE
other Plex servers that I can connect to through my friends. None of them
are on my network though and Id have to actually select them to see their
movies (which I never do).

**Comment by wersus1** [comment]
Hi,

I just want to say that I have kind of a same problem. My PKC adds a few duplicates almost every time it syncs with Plex. Also it didn't sync playback progress when I watched half of duplicated movie from my library. TV shows work flawlessly.

I'm using PMS on my shield TV.

After reading this thread, I enabled debug logging and updated to latest beta and did full library resync. So far it's working but let's see in few days.

**Comment by tknice** [comment]
Thanks versus1.   Glad to know I'm not the only one!  :)

I'm using the 1.3.8 beta and still getting duplicates.  I did a clean library and force refresh, but maybe i need to clean library and do the "reset all" option in PKC.  I'll try that tomorrow and report.

I wonder if you and I have any other settings that are different.

**Comment by croneter** [comment]
Guys, I need a log where I can see when the items were added (several times, apparently).

To achieve this, do a database reset in the PKC settings. Kodi will then restart. Try to NOT restart until duplicates show up and get the log ;-)

**Comment by tknice** [comment]
will do, I'll get it for you asap.   Prob around 10am EST.

**Comment by croneter** [comment]
Thanks. No hurry, I'll be busy as cracy for the next 3 weeks :-(. 

I will also need ~5 Plex IDs of duplicates, see above. (the duplicates might change)

**Comment by tknice** [comment]
Here's a log with IDs:

5376 - Title: Housebound
1145 - Title: The Croods
5465 - Title: Night at the Museum 3
373 - Title: Serenity
374 - Title: Skyline
5375 - Title: The Infinite Man

[kodi_092716.zip](https://github.com/croneter/PlexKodiConnect/files/496233/kodi_092716.zip)

**Comment by riffy13** [comment]
Wiped & waited... "The Thing" got duplicated. Note there are 2 movies named that too. Only one was duplicated.

[KodiLogDuplicate.zip](https://github.com/croneter/PlexKodiConnect/files/518571/KodiLogDuplicate.zip)

**Comment by wersus1** [comment]
I can't find my logs, I guess I messed something up when I reinstalled things. 

Here's my situation if it helps:
My movies got duplicated over time but I also got new problem: My TV show episodes started disappearing one by one.
Plex forum is suggesting that duplicates are caused by Plex PVR beta server which I'm using.

However I found a "fix" or workaround to my problems:
I disabled "constant background sync" and I change "do a full library sync every x minutes" to 30 and everything works well enough for me. No duplicates or disappearing episodes anymore.

**Comment by riffy13** [comment]
EWWW! That'd be more annoying. LOL 

I'm on the DRV Beta 2. The Beta 3 is way to unstable. I opened a ticket about that too. But, as for this... I've just been resetting the whole damn database every couple of days when I know I won't be watching anything for a couple of hours. I have my phone tell me when something is ready & to have to wait for Plex & then Kodi to get it... screw that mess! I like instant!! :-)

**Comment by wersus1** [comment]
You can also disable "show syncing progress" and you won't even notice it :). Syncing takes about 30sec - 1min on Nvidia Shield.

**Comment by riffy13** [comment]
Oh it takes longer on my library. I also have music enabled too. That's not helping I'm sure. I don't like to wait tho. I like it to do most of the updates in the background while I'm watching something.
