### ISSUE TITLE
Direct-Path sync not working nicely with tv shows

### ISSUE THREAD

**Issue by ghbeta** [croneter/PlexKodiConnect#1100]
Hi,
i have this strange issues. when using the direct path with tv shows.
i saved all the tvshows files insided the video/tvshows without any subfolder.
if i use the addon-path the play and sync functions works like a charm. 
but if i changed the addon-path to the direct-path (set the direct-path also under the sync settings), the tvshows will be played at first normally, however if added a new episode to the folder this will triggered a sync at the plexconnect side, then i can not find the newly added episode at kodi anymore.
strangely the movies always work either with addon-path or direct-path. can this be related to the kodi tv database can not processed tvseries without subfolder?

thanks for the helps

**Comment by croneter** [comment]
Ouch, yes, Kodi expects episodes to be in a dedicated folder per TV-Show! https://kodi.wiki/view/Naming_video_files/TV_shows

Please fix that on your end.
