### ISSUE TITLE
Synched Plex music playlist fails to play for Add-on Paths

### ISSUE THREAD

**Issue by williamkray** [croneter/PlexKodiConnect#1102]
System info: 
  + PMS running in a docker container
  + PKC configured for Addon paths and "Try Direct Play"
  + PKC running on Kodi 17 in libreelec on raspberry pi
  + official Plex for Kodi plugin plays playlists just fine

I'm unable to play anything in playlists that have been synced from my PMS. I've got a snippet of the log data here:

    kodi-livingroom:~/.kodi/temp # tail -f kodi.log |grep Neither
    16:54:31.134 T:1086321568   ERROR: PLEX.utils: Error encountered:  - u"Neither Plex nor Kodi id found for {u'title': u'', u'type': None, u'id': None, u'file': u'plugin://plugin.video.plexkodiconnect/?plex_id=8245&plex_type=track&mode=play&filename=02 Lord Echo feat. Mara TK - Life on Earth.mp3', u'label': u'Life on Earth'}"
    16:54:31.147 T:1086321568   ERROR: PLEX.utils:         raise KeyError('Neither Plex nor Kodi id found for %s' % kodi_item)
    16:54:31.147 T:1086321568   ERROR: PLEX.utils:     KeyError: u"Neither Plex nor Kodi id found for {u'title': u'', u'type': None, u'id': None, u'file': u'plugin://plugin.video.plexkodiconnect/?plex_id=8245&plex_type=track&mode=play&filename=02 Lord Echo feat. Mara TK - Life on Earth.mp3', u'label': u'Life on Earth'}"
    16:54:44.791 T:1132458912   ERROR: PLEX.utils: Error encountered:  - u"Neither Plex nor Kodi id found for {u'title': u'', u'type': None, u'id': None, u'file': u'plugin://plugin.video.plexkodiconnect/?plex_id=8246&plex_type=track&mode=play&filename=03 Lord Echo feat. Mara TK - The Sweetest Meditation.mp3', u'label': u'The Sweetest Meditation'}"
    16:54:44.804 T:1132458912   ERROR: PLEX.utils:         raise KeyError('Neither Plex nor Kodi id found for %s' % kodi_item)
    16:54:44.805 T:1132458912   ERROR: PLEX.utils:     KeyError: u"Neither Plex nor Kodi id found for {u'title': u'', u'type': None, u'id': None, u'file': u'plugin://plugin.video.plexkodiconnect/?plex_id=8246&plex_type=track&mode=play&filename=03 Lord Echo feat. Mara TK - The
    Sweetest Meditation.mp3', u'label': u'The Sweetest Meditation'}"

This is what the structure looks like in the playlist that it's trying to play:

    kodi-livingroom:~/.kodi/temp # head ../userdata/playlists/music/Chill\ Vibes.m3u
    #EXTCPlayListM3U::M3U
    #EXTINF:331,Woah! There’s No Limit
    plugin://plugin.video.plexkodiconnect/?plex_id=8244&plex_type=track&mode=play&filename=01 Lord Echo feat. Mara TK - Woah! There’s No Limit.mp3
    #EXTINF:153,Life on Earth
    plugin://plugin.video.plexkodiconnect/?plex_id=8245&plex_type=track&mode=play&filename=02 Lord Echo feat. Mara TK - Life on Earth.mp3
    #EXTINF:354,The Sweetest Meditation
    plugin://plugin.video.plexkodiconnect/?plex_id=8246&plex_type=track&mode=play&filename=03 Lord Echo feat. Mara TK - The Sweetest Meditation.mp3
    #EXTINF:241,Makossa No.3
    plugin://plugin.video.plexkodiconnect/?plex_id=8247&plex_type=track&mode=play&filename=04 Lord Echo - Makossa No.3.mp3
    #EXTINF:309,Low to the Street

Meanwhile, here is a playlist that was created from the Kodi side of things, you can see that the structure is completely different. This format works just fine:

    [~] ▶ head /tmp/test\ kodi\ playlist.m3u
    #EXTCPlayListM3U::M3U
    #EXTINF:331,Lord Echo - Woah! There’s No Limit
    https://plex.kray.pw:32400/library/parts/10073/1506992447/file.mp3?X-Plex-Token=REDACTED$
    #EXTINF:153,Lord Echo - Life on Earth
    https://plex.kray.pw:32400/library/parts/10074/1506992447/file.mp3?X-Plex-Token=REDACTED$
    #EXTINF:354,Lord Echo - The Sweetest Meditation
    https://plex.kray.pw:32400/library/parts/10075/1506992447/file.mp3?X-Plex-Token=REDACTED$
    #EXTINF:241,Lord Echo - Makossa No.3
    https://plex.kray.pw:32400/library/parts/10076/1506992447/file.mp3?X-Plex-Token=REDACTED$
    #EXTINF:309,Lord Echo - Low to the Street

**Comment by croneter** [comment]
Entire Debug log please

**Comment by williamkray** [comment]
[kodi.debug.log](https://github.com/croneter/PlexKodiConnect/files/4081212/kodi.debug.log)

**Comment by williamkray** [comment]
sorry, here's another version... seems like now SOME music is playing, but perhaps music with special characters in the name gets screwed up? I am having trouble replicating despite the behavior being consistent all day yesterday after multiple reboots and database resets.

https://gist.github.com/williamkray/ab741cd59530ee10121ee22fddec1dd1

**Comment by williamkray** [comment]
one more update: seems that the reason i wasn't able to replicate the original issue was because i was using Chorus to load the playlists above... this is when I would see the unicode decode issue in those logs.

here's another debug log where I see the original behavior when trying to play a playlist by navigating to it in the Kodi interface:

https://gist.github.com/williamkray/521c22a65a8477b4c4b07fd00aaef74d

**Comment by williamkray** [comment]
I've also discovered that Kodi will appropriately load album art and track information if I navigate to the PKC Playlists directory (rather than the Music > Playlists directory), but when I try to play anything, I see examples of BOTH of the above errors (unicode decode error AND the "Neither Plex nor Kodi id found" error).

**Comment by croneter** [comment]
Sorry it took so long 😞 . This is caused by your old version of Kodi, as far as I can tell. 

Please update to Kodi 18; Kodi 18.5 being the latest.

**Comment by williamkray** [comment]
I just spent all morning installing the latest LibreELEC on a fresh microSD card, configuring it, and installing and configuring PKC... and it'd demonstrating the same error. When navigating from Home -> Music -> Playlists -> a playlist, it says it can find neither kodi nor plex ID.

**Comment by croneter** [comment]
Could you please share your debug log again?

**Comment by williamkray** [comment]
https://gist.github.com/williamkray/7c54f5a22876304ba4f2e12868b22b8f

**Comment by croneter** [comment]
Ah, finally spottet the issue. You're using Add-on Paths, not [Direct Paths](https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths) and we're talking about music playlists here. I'm sorry to tell you that it's currently not possible to use Add-on Paths and playlists synched from the PMS. 

Playlists should work fine if you create them within Kodi. 

If you can get Direct Paths to work, music playlists should be synched correctly.

**Comment by williamkray** [comment]
oh, so the very second thing that I said in my very first message about this issue:

> System info:
> 
>     * PMS running in a docker container
> 
>     * PKC configured for Addon paths and "Try Direct Play"
> 
>     * PKC running on Kodi 17 in libreelec on raspberry pi
> 
>     * official Plex for Kodi plugin plays playlists just fine
> 
> 

Cool. Consider this a feature-request I suppose, and I'll use the official Plex addon if I want to play any playlists.

Considering the fact that music itself plays just fine, and playlists created in Kodi play just fine, my assumption is that it's strictly how the playlist is being created during the synch process and therefore should be fixable. Addon paths are recommended in most of your documentation, and the whole point of Plex is to eliminate complicated sharing and network configuration, so it only makes sense that this be supported.

**Comment by croneter** [comment]
This is solved/implemented from PKC **beta** version 2.11.2 onwards.

**Comment by williamkray** [comment]
wow, thank you! i'll test it out as soon as i can.

**Comment by williamkray** [comment]
working very well... if i navigate to the playlist from the PKC Music addon category, all metadata loads appropriately and the playlists play without issue in my brief testing. I've got this added to my favorites so i don't navigate to the playlist from the Kodi Music library, which only shows "file.mp3" playing with no metadata, but this feels like a Kodi limitation.

Thank you for your quick work on this fix!

**Comment by croneter** [comment]
> Kodi Music library, which only shows "file.mp3" playing with no metadata
PKC has to point to a PMS url that unfortunately all end with `file.mp3`. I like your workaround though :smile:
