### ISSUE TITLE
Movies do not play if they are in a identically-named subfolder and path replacement is on

### ISSUE THREAD

**Issue by AlbinoDrought** [croneter/PlexKodiConnect#1104]
My environment:

- PKC Version: 2.10.4
- Movies are available to Plex from `/data/movies`
- That same folder is available over the network as `smb://foo/media/movies`
- Path replacement is on and replaces `/data` with `smb://foo/media`. [Picture](https://imgur.com/65EF4xf)
- Movies in the root folder or differently-named subfolders appear to play perfectly. Only movies in identically-named subfolders have trouble
- Other software I am using occasionally stores files in this identically-named subfolder format

Steps to reproduce:

1. Find some sample movie. I used Big Buck Bunny from [here](https://peach.blender.org/download/), renamed to `Big.Buck.Bunny.Sunflower.2008.1080p.WEB-DL.x264-BLENDER.mp4`
2. Create a folder in your movie store with the same name as the file: `/data/movies/Big.Buck.Bunny.Sunflower.2008.1080p.WEB-DL.x264-BLENDER.mp4/`
3. Put the movie in that folder: `/data/movies/Big.Buck.Bunny.Sunflower.2008.1080p.WEB-DL.x264-BLENDER.mp4/Big.Buck.Bunny.Sunflower.2008.1080p.WEB-DL.x264-BLENDER.mp4`
4. Rescan so both Plex and PKC pick it up

[Debug kodi.log pastebin link here](https://pastebin.com/wZWXLiVy)

What I see:

- Everything plays fine in the Plex WebUI
- Plex WebUI shows the full path as being `/data/movies/Big.Buck.Bunny.Sunflower.2008.1080p.WEB-DL.x264-BLENDER.mp4/Big.Buck.Bunny.Sunflower.2008.1080p.WEB-DL.x264-BLENDER.mp4 `
- PKC shows the full path as being `smb://foo/movies//Big.Buck.Bunny.Sunflower.2008.1080p.WEB-DL.x264-BLENDER.mp4`. [Picture](https://imgur.com/iO0IZ00)

Is there a quick fix to this, besides just renaming the folder? Even stripping the file extension off of the folder name fixes things: [Picture](https://imgur.com/UqcYBYH)

**Comment by AlbinoDrought** [comment]
Replacing `path = playurl.replace(filename, "")` with `path = playurl.rpartition(filename)[0]` in [resources/lib/itemtypes/movies.py](https://github.com/croneter/PlexKodiConnect/blob/45cd1aa0fcbd47e2a714f324c629735633549e85/resources/lib/itemtypes/movies.py#L57) fixes this issue on my machine. 

This should help convert paths like `smb://foo/movies/Big.Buck.Bunny.Sunflower.2008.1080p.WEB-DL.x264-BLENDER.mp4/Big.Buck.Bunny.Sunflower.2008.1080p.WEB-DL.x264-BLENDER.mp4` to `smb://foo/movies/Big.Buck.Bunny.Sunflower.2008.1080p.WEB-DL.x264-BLENDER.mp4/` instead of `smb://foo/movies//`

I am not sure what unintended consequences this change could have. On my machine, other movies continue to play as expected after this change.

This same `path = playurl.replace(filename, "")` line also appears in `tvshows.py` and `music.py`: https://github.com/croneter/PlexKodiConnect/search?q=%22path+%3D+playurl.replace%28filename%2C+%22%22%29%22&unscoped_q=%22path+%3D+playurl.replace%28filename%2C+%22%22%29%22

**Comment by croneter** [comment]
Thanks for the report. No I guess I need to dig into the code to fix this

**Comment by croneter** [comment]
Does beta version 2.10.8 help?

**Comment by croneter** [comment]
This should be fixed. Let me know here if this is not the case.

**Comment by AlbinoDrought** [comment]
Sorry, I missed the comment mentioning the beta version.

I can confirm this is fixed for me, running 2.10.12 and it's working great! Thanks!

**Comment by croneter** [comment]
Hah, thanks for the coffee @AlbinoDrought ❤🙏
