### ISSUE TITLE
Kodi 18 and Estuary / Other Skins

### ISSUE THREAD

**Issue by obsidiangroup** [croneter/PlexKodiConnect#1106]
I have PlexKodiConnect installed on multiple installations of Kodi (All installations are running Leia).  Two are running on Windows, while the third is running on Ubuntu.  Upon installing the first instance of PKC on the Ubuntu box, initially with the Estuary Skin, the 'Movies' and 'TV Shows' showed 'Your library is currently empty.  In order to populate with your personal media ...'.  It even displayed this after PKC scanned and completed syncing.  After restarting Kodi multiple times however, the categories displayed content.  

However, on both of the Kodi implementations running on Windows, regardless of what I do, these categories do not display any information.  And as documented, you cannot do much customizing of Estuary.  I would like to know if there are any pre-defined XML files for any of the skins (specifically Estuary and Titan) that has PKC fully implemented?  Or, can someone point out what exact steps need to be taken to get PKC to work correctly with Estuary?  I have not included any logs, but if needed I can submit them.

I just thought that if there were any skin configuration files that have PKC fully implemented, that including them as "examples" would be a great addition.

**Comment by croneter** [comment]
Are you 100% sure you did sync your libraries to these 2 Windows instances? You could still navigate Plex without having synced them - obviously, the Kodi libraries would remain empty. Check e.g. by navigating to the PKC settings, then `Sync Options`, then `Select Plex libraries to sync`. They need to be selected :wink:
    
You don't need to mess with any skin XMLs to get PKC working!
