### ISSUE TITLE
Sync Stalls in SPMC

### ISSUE THREAD

**Issue by soljarag** [croneter/PlexKodiConnect#111]
I've been using this plugin for many months flawlessly on 2 minix boxes.... on the older box I'm running regular Kodi. but on the newer box, I have to run SPMC

All of the sudden a few days ago, the SPMC box keeps stalling after it starts to do the startup Sync. It will get to like 8 items, then stops. I can't play any videos either..... the Kodi Box still works fine.

I just installed Minix XBMC on the new box, and PlexKodiConnect works great.... So it may be a SPMC issue.....

here is the spmc log

[spmc.txt](https://github.com/croneter/PlexKodiConnect/files/486316/spmc.txt)

**Comment by croneter** [comment]
Hmm, I can't see anything in the logs. 

With SPMC, could you try the BETA version? Sync changed rather drastically, maybe that will work for you ;-)

**Comment by soljarag** [comment]
I went ahead and completely uninstalled and re installed SPMC and the addon.  When it started to sync  the library it said:

library sync thread crashed

then I restarted SPMC and its syncing just fine...... So I'm not sure what caused the thread crash the first time

**Comment by croneter** [comment]
OK, let me know if you run into issues again ;-)
