### ISSUE TITLE
Feature Request: Select which Libraries to sync

### ISSUE THREAD

**Issue by ProGEEK** [croneter/PlexKodiConnect#112]
My Plex account has several libraries accessible to it from a single server, (Home Videos, Kids Movies etc), It would be really cool if in the configuration (Or at setup) I could specify/select which libraries to sync to different kodi boxes rather than having to have multiple accounts /users for specific libraries.

**Comment by rokkhan** [comment]
Yes please!

**Comment by breezytm** [comment]
I create another feature request for this. I am just noticing it has already been asked. Perhaps it can be consolidated. Or mine can be labeled duplicate.

**Comment by croneter** [comment]
Now on feathub.com: http://feathub.com/croneter/PlexKodiConnect/+13
