### ISSUE TITLE
Just crashing

### ISSUE THREAD

**Issue by ShiiroSan** [croneter/PlexKodiConnect#1128]
I don't really know why it's not working. I just have a notifications telling me PKC crashed.
debug file (post install): http://paste.kodi.tv/yedamizohu
debug file (after restarting): http://paste.kodi.tv/giricexedo

Plex is installed on a Windows 10 computer. No SSL.
Kodi 18.5 installed on Xbox One

**Comment by ShiiroSan** [comment]
I'm dumb, here is debug log: http://paste.kodi.tv/kutudexube

**Comment by croneter** [comment]
Seems to be your RAM:
'''
MemoryError
'''

**Comment by croneter** [comment]
Nothing PlexKodiConnect can do...

**Comment by croneter** [comment]
Haven't seen that error. If you're lucky, this will work: try to deactivate Synching of playlists on the PKC settings under Sync

**Comment by ShiiroSan** [comment]
> Haven't seen that error. If you're lucky, this will work: try to deactivate Synching of playlists on the PKC settings under Sync

I'll try it asap. I guess Xbox One S can't handle it.

**Comment by croneter** [comment]
Guess this is solved. Let me know here if that is not the case
