### ISSUE TITLE
Opening Stream Dialog Not Closing

### ISSUE THREAD

**Issue by chaoticmaster** [croneter/PlexKodiConnect#113]
When playing movies or TV shows from widgets the opening stream dialog box is not closing when the video starts. I am able to cancel it after a few seconds and continue watching the movie. Playing the same movie from the library does not have the issue.  Changing skins does not solve the problem

[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/488693/kodi.txt)

[https://15254b2dcaab7f5478ab-24461f391e20b7336331d5789078af53.ssl.cf1.rackcdn.com/plex.vanillacommunity.com/editor/xg/7id1y04v174q.png](url)

**Comment by meestark** [comment]
Not sure if necessary, but attached my logs too of the same issue.


[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/490689/kodi.txt)
