### ISSUE TITLE
PKC Tv Shows On Deck widget

### ISSUE THREAD

**Issue by MagicSG1** [croneter/PlexKodiConnect#1130]
Hi, has the PKC Tv Shows On Deck(faster) widget been removed? Noticed it wouldn’t load earlier and when I went to add it again it’s missing. Only the standard On deck which is ridiculously slow. I’m on Kodi 18.5. NVIDIA Shield TV 2017(latest) and PMS(linuxserver/latest). Love the plugin mate. Keep up the good work.

**Comment by croneter** [comment]
There is only one TV shows on deck widget. I don't even remember whether there ever was another one. From a technical perspective, Kodi would need to implement a fast one - it's impossible from the PKC side of things
