### ISSUE TITLE
Direct Play is receiving a DirectStream link, and doesn't receive the direct path

### ISSUE THREAD

**Issue by Inervo** [croneter/PlexKodiConnect#1133]
Hi,

I'm using PKC since some times, at first with "Direct Path", and now with "addon" Sync Options.
I'm fairly confident that my settings is currently playing my videos through direct stream and not direct play (some delay when starting the movie playback, no information on the movie full filename and path when trying to download a subtitle, etc.).

Here is exactly what i tried:
First, configure everything with directPath, and defined the path substitution. Works perfectly, i can read all the videos without any issue.
Log : [kodilog - DirectPath.txt](https://github.com/croneter/PlexKodiConnect/files/4256313/kodilog.-.DirectPath.txt)

Then, switched Sync Options to "addon", and switched Prefered playback method to "Direct Play".
Performed a "Partial or full reset of Database and PKC" --> options yes, then no.
Restarted and resynched the videos. And tried to play the exact same video file.
But now, there's a delay in the launch of the playback, there's no information of the movie filename in the "download subtitle" menu, and in the log, every line related to playback just contains reference to the URL, but not to the path.
Log : [kodilog - DirectPlay.txt](https://github.com/croneter/PlexKodiConnect/files/4256312/kodilog.-.DirectPlay.txt)

Am i doing something wrong ? Or maybe I am wrong and this is Direct Play ?
Thanks a lot for your help :)

**Comment by croneter** [comment]
Looking at your last log:
```
2020-02-26 15:14:24.277 T:8976  NOTICE: PLEX.service: PKC Direct Paths: False
```
In the PKC settings under `Advanced`, choose `Direct Paths`:
![image](https://user-images.githubusercontent.com/4637940/75361970-5c0ffd80-58b8-11ea-8a8a-de1f6f5de671.png)

You only changed the `Prefered Playback Method` in the section `Playback`. `Try Direct Path` there means that PKC *add-on paths* will still try to find a direct path to the media BUT: initiating playback etc. is still done like with add-on paths

**Comment by Inervo** [comment]
I'm not sure to understand you (or that i made myself clear - sorry for that):
I **want** to be in `Addon` mode, with `Direct Play`, i don't want to be in `Direct Path` mode. So i did everything that's described in the `How to set everything up`from your wiki [https://github.com/croneter/PlexKodiConnect/wiki/Direct-Play](url)

The settings is as follow : 
![Sync options](https://user-images.githubusercontent.com/2921547/75365119-07bb4c80-58bd-11ea-83e1-0da9d1348a65.png)
![Playback](https://user-images.githubusercontent.com/2921547/75365121-0853e300-58bd-11ea-9676-15f2eb7f19a6.png)

But i find it strange that the debug log tells me that the link is `PLEX.playback_decision: The playurl for DirectPlay is: https://192-168-13-42.520d3fcf72374e079012cdf4fcaa8ae2.plex.direct:32400/library/parts/72029/1581616769/file.mkv`, which seems like Direct streaming.
Shouldn't it be something like `nfs://192.168.13.42/volume1/Videos/..../RealFileName.mkv` ?

(Again, i'm using the knowledge from `What is Direct Play` from the wiki [https://github.com/croneter/PlexKodiConnect/wiki/Direct-Play](url). I may have misunderstood something)

Thanks a lot :)

**Comment by croneter** [comment]
Nope. You're perfectly fine like this, you're using Direct Play. The PMS
does not serve the "real" filename.

Inervo <notifications@github.com> schrieb am Mi., 26. Feb. 2020, 17:36:
