### ISSUE TITLE
Receiving error, ’none type’ object has no attribute ‘getitem’ when adding a PKC Music widget to homescreen

### ISSUE THREAD

**Issue by kpmelvin** [croneter/PlexKodiConnect#1136]
When adding a PKC Music widget to the home screen I get the following error,

’none type’ object has no attribute ‘getitem’

It’s only happening with the Music widgets.

Log attached.

Thanks,
Ken

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/4270522/kodi.log)

**Comment by croneter** [comment]
Fixed with BETA 2.11.3
