### ISSUE TITLE
Integration with tautulli

### ISSUE THREAD

**Issue by spamies1** [croneter/PlexKodiConnect#1139]
The PKC stream shows up as generic and tautulli can't terminate the stream. I attached two screenshots, one shows the PKC stream showing as generic and the other as a identified stream that can be terminated. 

![generic](https://user-images.githubusercontent.com/45741111/75692084-e14d3680-5c59-11ea-89d4-36d3557386ce.png)

![terminate](https://user-images.githubusercontent.com/45741111/75692098-e4482700-5c59-11ea-8c46-1c08a1d58417.png)

**Comment by croneter** [comment]
That's not a bug but a feature request. Please open a new feature request here: https://feathub.com/croneter/PlexKodiConnect

Thanks!
