### ISSUE TITLE
Unable to manually connect to Plex server on LAN

### ISSUE THREAD

**Issue by LinuxChristian** [croneter/PlexKodiConnect#114]
Hi,

When I attempt to manually connect to my Plex server I get the following error message from kodi,

```
17:43:10 940.587219 T:1648358384  NOTICE: PLEX.default -> Full sys.argv received: ['plugin://plugin.video.plexkodiconnect/', '-1', '?mode=enterPMS']
17:43:41 971.070190 T:1648358384   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: not all arguments converted during string formatting
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 178, in <module>
                                                Main()
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 146, in __init__
                                                modes[mode]()
                                              File "/home/osmc/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 1367, in enterPMS
                                                % (https, ip, port, machineIdentifier))
                                            TypeError: not all arguments converted during string formatting
                                            -->End of Python script error report<--
```
My setup:
I am running PlexKodiConnect v1.3.3 installed per the guide and OSMC 2016-08.1 (Just did a system update) on a Raspberry PI 3. The plex server is running on a separate machine in a Docker container (i.e. the external server IP 192.168.1.100 does not match the internal plex IP 172.17.0.3 since this is a virtual network). The web interface works without any problems and can be accessed via the server IP. The android app is also able to connect to the server using manual server discovery by typing the servers IP (i.e. not the docker IP).
Automatic discovery does of course not work since GDM reports the docker IP to PlexKodiConnect and not the server IP. This should however not be a problem for the manual server discovery since the port mapping works fine on other devices.

When does the error happen:
* In the settings panel I select manual connection to plex
* I enter my local server IP 192.168.1.100
* Use the standard port
* The above message is reported

**Comment by croneter** [comment]
Thanks for your detailed report! I will look into it
