### ISSUE TITLE
Estuary skin and Library Node Editor

### ISSUE THREAD

**Issue by rajil** [croneter/PlexKodiConnect#1142]
Hello,
The [documentation](https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins#customize-your-homescreen) mentions it is possible to create a Video Node for the Estuary skin. I have installed Library Node Editor and created a Video Node called 'Other'. How can i link it to the my Plex Library called "HomeVideo"?

Thanks

**Comment by croneter** [comment]
I don't know how that works for Estuary. Other skins let you customize so called widgets for the home screen. When selecting one, navigate like described here: https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins
