### ISSUE TITLE
Sync on Startup Crash

### ISSUE THREAD

**Issue by amitgir** [croneter/PlexKodiConnect#1145]
I'm running the newest update (2.11.5).

Upon start up the PKC will start the sync with PMS which then locks up towards the last +95% mark and stalls KODI. In the log below the lock happens at the moment the movie "LOU" (Plex_id: 177828) comes up. 

I've attached my logs here.
[01_KODI.log](https://github.com/croneter/PlexKodiConnect/files/4333652/01_KODI.log)

Thanks! Help make Kodi useable again!

**Comment by croneter** [comment]
Can you please share the metadata xml of "Lou", see here: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/

**Comment by croneter** [comment]
What happens if you reboot Kodi? Does the sync get stuck at the same element?

**Comment by croneter** [comment]
Did you try to reset the Kodi database by navigating to the PlexKodiConnect settings, Advanced, then Reset the Kodi database, then Yes, then No?

**Comment by amitgir** [comment]
I’ll send over the XML shortly. 

Sort of. The sync stops at just about any part of the process. Sometimes the same movie. Sometimes a different one. 

I’ve reset the database before but will try again.

**Comment by amitgir** [comment]
Here's the XML for "Lou"

https://pastebin.com/rQzRnRhR

**Comment by amitgir** [comment]
Seems if I soft reboot a few times PKC is able to eventually complete a full sync and all’s well.

**Comment by croneter** [comment]
Still an issue?  How often did this happen?

**Comment by amitgir** [comment]
Oddly enough PKC hasn’t done it these past few days. A few reboots and resetting the database have seem to have done the trick. I’m going to update to 2.11.6 today

**Comment by amitgir** [comment]
Sorry @croneter. The issue is back. I haven't tried the newest version with the XBOX fixes. Was there anything on my logs that could explain? I though the fix sync with full queue would fix it, but no...

**Comment by croneter** [comment]
Darn. Could you please share your log file again?

**Comment by amitgir** [comment]
It's at the top of this post. But let me know if you need a new one.

**Comment by croneter** [comment]
New one please, debug logging enabled

**Comment by croneter** [comment]
@amitgir could you please share a new debug log?

**Comment by amitgir** [comment]
You can close this. I haven't gotten the error since I updated to Kodi 18.6 (via CoreELEC 9.2.2). Thanks though.
