### ISSUE TITLE
Development for Kodi 19

### ISSUE THREAD

**Issue by xinseo** [croneter/PlexKodiConnect#1147]
Any update on how the development for Kodi 19 is going? Any betas that we can try?

Asking because there's a bunch of new features that I would love to use along with PKC.

**Comment by croneter** [comment]
No. There is not even an official, "stable" Kodi 19 Alpha version out yet. 

PKC heavily uses Python and some "fringe" features. There is still a lot of development going on on the Kodi Python side. I'd need Kodi Python to be more a more or less stable basis...

**Comment by xinseo** [comment]
> No. There is not even an official, "stable" Kodi 19 Alpha version out yet.
> 
> PKC heavily uses Python and some "fringe" features. There is still a lot of development going on on the Kodi Python side. I'd need Kodi Python to be more a more or less stable basis...

Thanks for the update!
