### ISSUE TITLE
My recently added tv shows widgets not syncing unless I play an episode...

### ISSUE THREAD

**Issue by Cynwrig** [croneter/PlexKodiConnect#1151]
Dear Croneter,

I am pretty sure it has something to do with the way PKC works. Do you have a work arround for this widget? I would be fine if it was possible to make a start script in Kodi where it would start an episode for a short time or triggers the open / update button for the widget as that seems to sync the tv shows aswell, only I don't have enough experience with Kodi to do this.

Thanks in advance

**Comment by croneter** [comment]
Sorry, no. This is very probably an issue with the skin you're using. The widget you're referring to is "standard" Kodi and should load pretty much instantly. I'd get back to the skin developer if I were you

**Comment by Cynwrig** [comment]
No problem, I try with Mikesilvo
