### ISSUE TITLE
Video remains in menue state, only audio playing

### ISSUE THREAD

**Issue by MrDownstream** [croneter/PlexKodiConnect#1152]
Hi,

I just recently discovered that some of my movies/series won´t play correctly anymore.
Behavior is as follows:
Movie loads nicely, sound starts, yet video remains in menue view (can only see the timebar and the background image for said movies/series).
I already watched those movies with the same hardware setup, so my only conclussion is that it must be an issue with a software update.
Right now im using Kodi 18.6 and the newest update from PKC. I already tried using older versions of PKC without any success. the PMS Version is also the current version available.

Yesterday i checked the logs (Kodi Log Viewer Addon), relating to one Error with "skipping unplayable item".
I also uploaded the current log here (Kodi Log Uploader Addon): http://paste.kodi.tv/tobiqemoju
Strangely enough the Uploaded Addon does not show the Error!?

**Comment by MrDownstream** [comment]
Here is a second logfile (Kodi Log Viewer Addon) with said error: http://paste.kodi.tv/ofiwemakow

**Comment by croneter** [comment]
I'm very sorry, but this is not the fault of PlexKodiConnect. PKC correctly hands over the file for playback to Kodi. Then it's all up to Kodi what to do with it. You might want to consider downgrading your Kodi and try again - I had some issues with Kodi 18.6 for Android as well.
