### ISSUE TITLE
Multi-Folder Libraries

### ISSUE THREAD

**Issue by aerogems** [croneter/PlexKodiConnect#1153]
I have a growing Anime collection which I would like to be mixed in with my other TV shows, but I am running out of space on the drive that hosts all these files, so I would like to be able to split them across to drives/volumes.

It is a simple enough process to add another folder to a library in Plex and it will play the files in the secondary folders without issue. PlexKodiConnect, however, will not. The files are found and added to the Kodi library, but when attempting to play any of them an error message that the file cannot be found is displayed and the user is asked if they wish to remove the file from the library.

I have made sure that the secondary library folder is added as a mount point in Kodi and that files play back correctly when accessed directly, and the path info shown within Kodi is correct. I'm running PMS 1.18.8.2468 on a Synology NAS, PKC is 2.11.6, Kodi is 18.6 on a Nvidia Shield, and I am using Direct Paths configured using Option 2 from the FAQ. Everything works correctly _except_ any files added to secondary or later folders on a Plex library.

**Comment by croneter** [comment]
Use add-on paths: https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths-Explained 

Or re-visit your direct paths setup and opt for Option 2: https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths

**Comment by aerogems** [comment]
I tried that, just for a lark, and now even after reverting my settings back to direct paths, PKC won't actually sync my TV shows into the Kodi database. So I've gone from a mostly workable state to one that doesn't work at all. Hurray! Now I will likely have to completely wipe out all my PKC settings and start over. 

Would it not be possible to add a few extra entries for each section (TV/Movie/Music/Photo) and loop over them when syncing to handle this sort of scenario? Symlinks just break the scraper, and create other issues. I don't currently have another drive to create a RAID setup so that more space appears available under the same volume. I just don't understand how it is that Kodi can show the correct path for the file, and can access the file just fine if I mount it in Kodi, but won't play via the library. The only thing that makes sense is that PKC is somehow involved.

**Comment by croneter** [comment]
> Would it not be possible to add a few extra entries for each section (TV/Movie/Music/Photo) and loop over them when syncing to handle this sort of scenario?

No. And sorry, but yes you do need to resync your entire Plex library if you switch from Add-on Paths to Direct Paths or vice-versa. 

Fastest fix: reset PKC completely (PKC settings - Advanced - Reset the Kodi DB - YES - YES) and choose Add-on Paths.

**Comment by croneter** [comment]
> The only thing that makes sense is that PKC is somehow involved.

Correct. But it's your configuration for Direct Paths that is incorrect / not apt for your complicated setup. Do stick to Add-on Paths

**Comment by aerogems** [comment]
> 
> 
> > Would it not be possible to add a few extra entries for each section (TV/Movie/Music/Photo) and loop over them when syncing to handle this sort of scenario?
> 
> No. And sorry, but yes you do need to resync your entire Plex library if you switch from Add-on Paths to Direct Paths or vice-versa.
> 
> Fastest fix: reset PKC completely (PKC settings - Advanced - Reset the Kodi DB - YES - YES) and choose Add-on Paths.

I did all that. The only way I could get it to start working again was to delete everything in the Database folder for Kodi. Otherwise, it would appear to sync everything, but then when I would try to go to the TV Shows section of Kodi it was just an empty list. Maybe I'm just "lucky" but I run into malformed disk image errors a lot with PKC and every time the only fix is to delete someething in the Database folder for Kodi. Usually the plex.db file is enough, but this time it wasn't.

In any event, I will have to agree to disagree that this is a complicated setup. It is a native feature of both Kodi and Plex, but it's your project so I will simply seek out alternatives such as MrMC to see if they will fit my needs.

**Comment by croneter** [comment]
> malformed disk image errors
PKC is taxing on your SD card, this is probably your root cause for pkc not behaving like it should. You should definitely NOT have any of these errors!! Please get a better SD card...
