### ISSUE TITLE
Crashing on XBOX one S Kodi 18.6 Leia

### ISSUE THREAD

**Issue by thatsmesaurav** [croneter/PlexKodiConnect#1155]
Crashing on XBOX one S during sync. Disabled playlist sync manually and restarted kodi multiple times still happening. 

Log file:
http://paste.kodi.tv/tozuvusosu

**Comment by croneter** [comment]
Hmm, weird, Python or Kodi does not detect that you're running Kodi on an Xbox.

Solution: in the PKC settings under Sync, manually deactivate synching of playlists. Then restart Kodi

**Comment by thatsmesaurav** [comment]
Disabling sync did not work.

**Comment by croneter** [comment]
Make sure the syncing of **playlists** is disabled in the PKC settings. Reboot Kodi again to be sure. Then share another DEBUG log file if the issue still occurs

**Comment by thatsmesaurav** [comment]
I just started kodi. the setting was disabled since I disabled it yesterday. Attaching image and logs.
Logs: [http://paste.kodi.tv/ikuduviqew](url)

Image:
![Kodi](https://user-images.githubusercontent.com/7416229/77546629-85ee1d00-6e82-11ea-8481-69caf382f19b.jpg)

**Comment by croneter** [comment]
Argh, that was a pretty serious bug, thanks for being insistent! Try PKC version 2.11.7, should be online in a few minutes.

**Comment by thatsmesaurav** [comment]
thanks bud will check out new version.
