### ISSUE TITLE
no movies found

### ISSUE THREAD

**Issue by droopified** [croneter/PlexKodiConnect#1159]
im new to this plugin. im using unraid with a docker of plex which this plugin is able to see. when i set it up it scanned for movies and did show on the top right movie titles but when i go into the addon i dont see any movies. i tried both direct and simple paths after reinstalling the plugin. on my unraid and kodi i have a source as nfs://server/mnt/user/Movies. im not to familiar with plex since i mainly use kodi but wanted to use the plex server for managing the watched status. am i doing something wrong or do i have to configure this addon in a special way?

**Comment by croneter** [comment]
Everything shows up in your normal Kodi library, movies included. There is no need to navigate to the add-on once the sync is done.

BUT: if you do navigate to the PlexKodiConnect add-on by clicking "Music", then "Music addons“, only music libraries will be shown (Kodi limitation). So be sure to navigate via e.g. Videos. - Video Add-ons - PlexKodiConnect.

You probably did not select a single Plex library to sync when that was promoted. By default, ALL Plex libraries are selected to be synched so there is nothing you need to do. You can check that in the PKC settings under Sync, "Select Plex libraries to sync"

**Comment by droopified** [comment]
when using this plugin, am i supposed to see a movie being played in the plex activity?

**Comment by croneter** [comment]
Yes

**Comment by droopified** [comment]
ok. well im not sure what the problem is. when i first installed the plugin, i saw it find my server which i selected, i then did the addon paths, i think thats the most important parts, but when i restarted kodi after selecting no on the extra settings at the end, it booted and tried to sync my movies. everything looked the same so i tried to play a movie from the recently added, it played but i didnt see it on plex activity so thought i had to go in the addon and browse that way, nothing was the library. not sure what is wrong at this point. i went back to my sql database and came back to this post and tried again. library seems broken. i dont see anything in Movies or TV Shows. not even the recently added text or the resume playing text. i have a backup of the sql database but i am not sure what went wrong. i deployed another sql server and used a windows fresh install of kodi but the same results. i dont know what to do.

**Comment by croneter** [comment]
Try resetting Kodi completely, that should help in extreme cases. Also, I'd like to have a look at your DEBUG log file, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by droopified** [comment]
how do i reset kodi completely? i used kodi on windows which is the first time i installed it and only added my advancedsettings.xml and it showed the same results. its the stock kodi install. the database showed same results. i also tried kodi 17 which used an older version of the kodi database and same results. here is a link of the debug i tried to ask on kodi forum but they dont know... https://pastebin.com/c0ZXQGhV

https://forum.kodi.tv/showthread.php?tid=352857&pid=2934708

**Comment by croneter** [comment]
To reset Kodi, shut it down and delete the entire [Kodi userdata folder](https://kodi.wiki/view/Userdata)

**Comment by croneter** [comment]
Hah, no wonder you've got issues! Pkc is KOT compatible with a Kodi MySQL solution. There is no need for it with PKC anyway. Please get rid of it completely by resetting Kodi as described above.
```
NOTICE: Contents of special://profile/advancedsettings.xml are...
                                            <advancedsettings>
                                              <loglevel hide="false">3</loglevel>
                                              <videodatabase>
                                                <name>KodiVideos</name>
                                                <host>*****.*****.*****.*****</host>
                                                <user>**********</user>
                                                <pass>**********</pass>
                                                <type>mysql</type>
                                                <port>3306</port>
                                              </videodatabase>
                                              <musicdatabase>
                                                <name>KodiMusic</name>
                                                <host>*****.*****.*****.*****</host>
                                                <user>**********</user>
                                                <pass>**********</pass>
                                                <type>mysql</type>
                                                <port>3306</port>
                                              </musicdatabase>
                                            </advancedsettings>
```

**Comment by droopified** [comment]
seems to be a missunderstanding. my first post here is infact from me trying to use mysql and even tho it said it wasnt used, the wording made me assume that it was going to alter my database to scrape from plex and make it look like its from kodi. 

when trying to undo everything, i installed kodi on a brand new system that had never had kodi and used a backup of my database. so given that the kodi is freshly installed, and my database is restored to before attempting pkc, im not sure why its not loading the database. as mentioned before, i also tried an earlier version of kodi and it used an older database, but it had the same results. so i dont think its pkc related but i am not an expert. just my guess.

**Comment by croneter** [comment]
Please start with an empty database and you should be fine

**Comment by croneter** [comment]
Actually, be sure to reset Kodi completely like described above

**Comment by droopified** [comment]
question, if i have multiple kodi devices, i used the advanced settings xml to share the databases. if i install pkc on multiple devices, will it sync the watched status across all kodi devices?

**Comment by croneter** [comment]
Yes. That's the point of pkc. Please be sure to reset all Kodi devices
