### ISSUE TITLE
[Feature Request] Ability to Disable MKV Subtitles

### ISSUE THREAD

**Issue by medoix** [croneter/PlexKodiConnect#116]
Currently the MKV subtitles are displayed automatically and when you go to subtitles there is no options, just a box saying there are no subtitles services installed.

**Comment by croneter** [comment]
Does this helP? http://kodi.wiki/view/subtitles#Changing_subtitle_settings_during_playback

to deactivate subtitles on the **KODI** side by default. This is not PKC's mistake ;-)

**Comment by medoix** [comment]
Sure does, the simple fact i needed to go into the "Audio" menu instead of the "Subtitle" menu now allows me to turn them off when needed. Makes complete sense... not haha thanks for the help!

**Comment by medoix** [comment]
This can be closed.

**Comment by medoix** [comment]
This can be closed.
