### ISSUE TITLE
Watched state of all users was imported instead of only the correct profile

### ISSUE THREAD

**Issue by SlovakianCanon** [croneter/PlexKodiConnect#1160]
I'm trying to set up PlexKodiConnect and I have an annoying problem with the watched state of movies and TV shows.

I have a Plex server with 2 home users (the main admin account and another one) and like 10 friends with whom I share some libraries. When I log into PlexKodiConnect I use the admin account as it's mine, but it seems that the watched state is not scoped to my profile but all the users all at once. So if a friend watched anything, it's going to show up as watched.

Is there a way to fix this? Even not importing the watched state at all would actually work since I use Trakt for that already. I just don't know how.

Thank you!

**Comment by croneter** [comment]
PKC updates playstate if a **friend** watches something?! Not good at all and I don't see that issue. 

Please share your DEBUG log file of you and your friend replicating the issue according to https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
No log no help possible, sorry
