### ISSUE TITLE
Resume playback not working. Arctic: Zephyr kodi 17.6 

### ISSUE THREAD

**Issue by thecat18** [croneter/PlexKodiConnect#1163]
I have this same issue, is there a way to get this too work on this Arctic: Zephyr skin, I really like the extra info for metadata in it & I can't use the new kodi leia for certain & most video  files because fast forward & rewind is horrible with speed compared to version 17.6.  Files just don't resume they start over.

**Comment by croneter** [comment]
Please use Kodi 18.6!
