### ISSUE TITLE
Unwatched status reverting back to in-progress

### ISSUE THREAD

**Issue by VooPoc** [croneter/PlexKodiConnect#1166]
Hi Guys,

Sorry about the title, it's a little hard to explain, in one line.  I've also done a quick search and don't find anything within issues, so sorry if this is known.

When I have content that has in-progress of over 1 minute, it syncs and reports to/from plex without issues.  However, I have a habit of watching content for a couple of seconds to revert the status on Kodi to unwatched.  When I do this with PlexKodiConnect it updates on Kodi as unwatched, but on plex, it's still listed as the original in-progress status and time.  Therefore when it syncs it reverts back to in-progress on Kodi.

I'm on the stable branch.

Thanks,

**Comment by croneter** [comment]
Does this happen if you start a movie, watch only a few seconds (less than a minute), then stop again? What if you watch for e.g. 3 minutes?

**Comment by VooPoc** [comment]
I've just double checked this to validate it.  Yes to both, the above scenario is when watching an in-progress movie (of more than 1 minute) from the beginning for less than 1 minute (Kodi goes to unwatched and plex reverts to the original timestamp until sync occurs).  If I watch for over 1 minute plex and Kodi in-progress timestamps are the same as well as watched status.

I assume the fix would be to set content to unwatched on Plex if content is watched for less than 1 minute on Kodi?

**Comment by croneter** [comment]
So to summarize: you don't experience this issue if you watch for longer than a minute.

Thing is, Kodi should NOT mark a movie as partially played if you watch for less than a minute. This is a bug that I'm also experience. 

Minor inconvenience if you ask me. Hopefully to be fixed on the Kodi side at some point

**Comment by VooPoc** [comment]
To be clear based on my communication.  It's not marking it as partially played if you watch it for less than a minute, it's marking it as unwatched.  This is different than Plex, where it reverts to the original timestamp if watched for less than a minute.  Hence the subsequent sync pushing the timestamp from plex to Kodi and changing content from unwatched to in-progress.

It's just different logic on either side, I don't think its a Kodi issue or Plex issue, they just do things differently.

I am just understanding how PKC integrated with Plex.  I am also just starting to code for addon's myself and have seen logic for monitor actions based on media player states, I assume you can pull the timestamp also and then do a change on the watch status.  But you will definitely know better than me :)
