### ISSUE TITLE
Preferred subtitles aren't defaulted when embedded in MKV

### ISSUE THREAD

**Issue by beffy** [croneter/PlexKodiConnect#1167]
## Describe the bug
For .mkv's with embedded .srt subtitles, my preferred subtitle language (as per my Plex settings) isn't defaulted. This is, however, not an issue when there is external .srt subtitles.

## To Reproduce
1. Play an .mkv with an embedded subtitle track of your preferred language.
2. Notice how the preferred subtitle language isn't defaulted.

## Expected behavior
I expect the same behavior as with external subtitles, that is, my preferred language is defaulted.

## Logs
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/4553071/kodi.log)

**Comment by croneter** [comment]
Opened a new feature request: https://feathub.com/croneter/PlexKodiConnect/+64

**Comment by king8084** [comment]
jesus christ i wish i searched for this issue beforehand, wasted hours trying to figure this out

any updates on when this might be fixed
