### ISSUE TITLE
Replace path using regex

### ISSUE THREAD

**Issue by JayXon** [croneter/PlexKodiConnect#1170]
Right now it's doing a simple string replace, this won't work if I have movies in different drives, even though Substitute Paths on the PMS exists, that's a way more complicated setup, I would prefer not do that. Can we support regex for replace pattern?
For example replace `([A-Z]):\\movies` with `smb://myNas/\1/movies` will map
`C:\movies` to `smb://myNas/C/movies`
`D:\movies` to `smb://myNas/D/movies`

Just change
```py
            path = path.replace(getattr(app.SYNC, 'remapSMB%sOrg' % typus),
                                getattr(app.SYNC, 'remapSMB%sNew' % typus),
                                1)
```
to
```py
            path = re.sub(getattr(app.SYNC, 'remapSMB%sOrg' % typus),
                          getattr(app.SYNC, 'remapSMB%sNew' % typus),
                          path,
                          1)
```

This might break some existing config, maybe add a new option for this?

**Comment by croneter** [comment]
Feature request is here, vote for it: https://feathub.com/croneter/PlexKodiConnect/+28
