### ISSUE TITLE
„Show sync progress“ and „Sync when screensaver is deactivated“ do not corelate

### ISSUE THREAD

**Issue by drt1** [croneter/PlexKodiConnect#1171]
Hi,

when you have setting „show syncing progress“ DISabled, but have „sync when screensaver is deactivated“ ENabled, it still shows the syncing progress when returning from screensaver.

I would assume that the second setting should respect the first one, do you mind to chang that behaviour?

thanks, BR

**Comment by croneter** [comment]
Fixed in PKC **beta** version 2.12.1
