### ISSUE TITLE
Re-downloading covers all the time.

### ISSUE THREAD

**Issue by netleader** [croneter/PlexKodiConnect#1172]
I'm using this addon for quite a while but there is one thing that drives me nuts. 
Each time i reboot my HTPC and start Kodi it downloads all the covers again and this takes ages with 2000+ movies. With a default Kodi library and other Plex clients I don't have this problem.

My HTPC is very high-end due to MadVR usage 9900k RTX 2080ti PCiE SSD, latest Kodi for Windows etc...

**Comment by croneter** [comment]
What do you mean with "downloads all covers again"? That is definitely not necessary.

Please enable DEBUG logging in Kodi, reboot Kodi and gather logs of this happening. See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by netleader** [comment]
I found the problem, the addon was always connecting via the external address instead of the local ip... could you change that behaviour?

**Comment by croneter** [comment]
That is incorrect - I have the same setup and an external IP works fine. Please share your log!

**Comment by croneter** [comment]
No log file (see e.g. https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug), no further help possible
