### ISSUE TITLE
Allow spaces in Plex device name

### ISSUE THREAD

**Issue by maforshaw** [croneter/PlexKodiConnect#1178]
What was the reason behind commit 2e5249ca4fbf22a831c9b3a84d1a969d6c5751db?

All my other native Plex clients allow spaces in the device name so for example I see "Lounge Shield Plex" in the list of devices in the Plex app. Note this name is entered inside the Plex client app, I'm not talking about the host name.

However, PlexKodiConnect is the odd one out and removes spaces. As a test, I commented out that line from the commit, rebooted and now the PlexKodiConnect client appears in Plex client lists with a space in the device name.

Everything still seems to work OK. Please would you consider reversing the above commit?

**Comment by croneter** [comment]
Fixed in PKC **beta** version 2.12.1
