### ISSUE TITLE
Add single movie to kodi library even if PKC is not synced with kodi library

### ISSUE THREAD

**Issue by fatshotty** [croneter/PlexKodiConnect#1179]
Hello,
first of all thank for great work. PKC works very well and I'm very happy to use it :)

my needs are a little bit different, now. I'd like to keep my kodi libraries clean so I disabled PKC library sync.
I wonder: is there a way to "add to kodi movie library" one specific movie? I mean can I add to kodi library only one selected movie from Plex library? So, I search for a movie in my Plex library (joker 2019, for example). "Context menu" to the item and the select "add to kodi library". PKC could create a .strm file linkining the PKC section in order to start the stream?

If it is not possible, could PKC "add to playlist" the "Joker 2019" in order to keep sync my choosed playlist with kodi only?

Thanks in advance

**Comment by croneter** [comment]
No there is not and this is not a use case many user are looking for, sorry

Pull requests are always welcome, of course 😝
