### ISSUE TITLE
[Feature Request] Appearance Tweek

### ISSUE THREAD

**Issue by starmanrf** [croneter/PlexKodiConnect#1181]
Hiya,

I don't sync TV content anymore as library was just getting too big, so I just use the add-on as a browser for my TV content and create widgets from the Nodes (Brilliant Feature btw!).

Just wondering if I could request an option to hide the 'all episodes' and 'specials' that appear within shows when using the video add-on as a browser for non-synched TV shows.

**Comment by croneter** [comment]
Sorry, no, that would make the entire logic really cumbersome (just a few lines of code now)
