### ISSUE TITLE
Add Plex's "Skip Intro"

### ISSUE THREAD

**Issue by requiem240sx** [croneter/PlexKodiConnect#1182]
Plex server now has a cool new feature to "Skip Intros" on tv shows.  It doesn't appear to have the "Skip Intro" pop up in Kodi though after the latest Plex [Update](https://support.plex.tv/articles/skip-content/). 

I use an Odroid N2 running CorELEC with Kodi v18 "Leia", with the plexkodiconnect add on.  My mobile app and browser both have "Skip Intro" popping up fine, so I know its setup corrctly server side, however I'm not seeing it on my Kodi devices.  Just wondering if I can submit a feature request for this, and/or if someone knows a way to get this working... maybe i'm doing something wrong.

Huge shoutout to everyone pushing changes on this! I love and use it faithfully every day!

**Comment by rati0nal** [comment]
+1. Interested to know if this is possible before getting my hopes up. I assume it will require some sort of UI element within Kodi also?

**Comment by CorentinB** [comment]
Hey!
FWIW, Composite added it, it's definitely do-able, if anyone want to take on the work I am pretty sure some inspiration can be found there: https://github.com/anxdpanic/plugin.video.composite_for_plex

**Comment by Hunk4TH** [comment]
Definitely interested in this as well!

**Comment by yekul** [comment]
Yeah for sure this was a pretty nice feature add by Plex and somewhat unexpected. Was waiting for an update about it, but figure there's no way for the Author to know if there's interest unless commenting so just popping in to say very interested please. 

Tried composite, was miles slower on my Firestick 4K than PKC was. Great work Croneter so far, really appreciated. The native Plex app is still so garbage and falls over on so many codecs/minor issues that the device itself can handle resulting in transcodes.

**Comment by Ares4570** [comment]
Would love to see this feature as well.

**Comment by simonk83** [comment]
Would also love this (I guess that's redundant as I assume pretty much everybody wants this, it's super super useful). Just commenting to show support :)

**Comment by freakshock88** [comment]
I would love this feature as well. I know other Kodi/Plex addons have it, but the preformance of PKC can't be beat for me. 
@croneter , wouldn't it be easier to implement this as a configuration option in PKC settings? (Like: "Always skip intro's")
This way no UI changes to the Kodi player are required.

**Comment by nilleiz** [comment]
I'd really like to see this feature too

**Comment by Cookie-Monster-Coder** [comment]
+1 for this feature!

**Comment by Alenael** [comment]
I want to see this too!

**Comment by Eggroley** [comment]
Would love to see this happen and it wouldn't require any UI changes either. It can be implemented in the same way Composite's skip intro function is. A simple next up esque pop up will suffice. Unfortunate that this feature has been ignored for so long.

**Comment by croneter** [comment]
Implemented with PKC versions 3.0.9 and (BETA) 2.12.14
