### ISSUE TITLE
Resume starts from the beginning

### ISSUE THREAD

**Issue by alexsmith2709** [croneter/PlexKodiConnect#1183]
When i need to pause a video file and then want to resume later, whether kodi has been restarted or not and i choose "resume from x time" it starts playback from the beginning again. I have not tried music files, only video files.

## Describe the bug
Video playback starts from the beginning after select to resume from the time it was paused.

## To Reproduce
Start video playback and pause playback at any time.
Exit from plexkodiconnect
Enter plexkodiconnect and find the video file. (I normally go to on deck but this happens however you wish to find the same file).
Press play and when the options come up to resume from x time or start from beginning, choose to resume from x time.

## Expected behavior
To resume from the time it was paused

## You need to attach a KODI LOG FILE!
https://filebin.net/w3bi7pdpp5ur6p35/kodi.log?t=5djf5ouq

**Comment by croneter** [comment]
That is due to the PMS becoming unreachable: 
```
WARNING: PLEX.download: HTTPConnectionPool(host='192.168.1.2', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xec042ad0>: Failed to establish a new connection: [Errno 113] No route to host',))
WARNING: PLEX.download: Server unreachable at: http://192.168.1.2:32400
...
ERROR: PLEX.sync.websocket: Could not retrieve Plex db info for 2066
```
Get your connectivity issues in order on the Kodi (or the Kodi host) and you should be able to resume a video without an issue.

**Comment by alexsmith2709** [comment]
There are no connectivity issues with anything else and it instantly plays back from the beginning, like its not even trying to connect.
Oddly i changed skin from the OSMC default skin to Amber and then it worked perfectly so i will check with the OSMC developers about this, but i dont know why i skin would cause this. This has never worked for me and i have never noticed a connectivity issue with anything else.

**Comment by croneter** [comment]
For posterity's sake: https://discourse.osmc.tv/t/resume-playback-from-pause-point-not-working/86004

Can you please try to reset the Kodi database in the PKC settings under Advanced (hit YES, then NO). 

If that does not work, try this:
1. Enable Kodi debug logging, restart Kodi.
2. Start playback of a new movie (one without a resume point), leave playback on for at least 2 minutes. 
3. Stop playback. Wait a couple of seconds! 
4. Then try to resume the same movie again
5. Share your Kodi log file

**Comment by alexsmith2709** [comment]
Resetting the database seems to have sorted this issue. I played both a film and a tv show, paused and rebooted before playing back from resume point and both worked as expected.

Thanks
