### ISSUE TITLE
In Kodi Krypton, cannot update IMDb Top 250 information

### ISSUE THREAD

**Issue by bartolomesoriano** [croneter/PlexKodiConnect#119]
PMS does not keep IMDb Top 250 ranking info for movies, yet it is in the Kodi video db for movies.  Generally, the only way, if you use PKC, to have this information updated, is by using an addon, such as "Rating Update" (http://forum.kodi.tv/showthread.php?tid=107331).  In Kodi Krypton, unfortunately when using PKC this addon no longer works, giving the error that the query to the Kodi video db failed.  if I revert to a local (non PKC) Kodi video db, the addon works correctly.

**Comment by rokkhan** [comment]
Samme issue here

**Comment by croneter** [comment]
Is this issue fixed?

**Comment by bartolomesoriano** [comment]
I will have to test again and will let you know.

**Comment by bartolomesoriano** [comment]
The script works, but not well.  For example, I have multiple movies in the IMDb Top 250 in one of my Plex libraries that are not updated with the correct Top 250 number and thus do not show up in my Top 250 playlist.

**Comment by croneter** [comment]
Thanks for checking.

Well, it's not a PKC issue anymore then. It's either up to Plex to provide
the correct imdb ID or to the imdb plugin to better scrape the info from
imdb.

Am 24.01.2017 14:02 schrieb "bartolomesoriano" <notifications@github.com>:
