### ISSUE TITLE
PKC changes Plex default subtitles

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#1191]
Reported in the Plex forums by user @Randomacts

I’m running the stable version and one thing I’ve noticed is that when I watch something with subs it changes the setting on my plex account to NONE on the subtitles so if I watch it on another client the subtitles won’t be selected anymore.

Is there a way to prevent kodi from touching plex’s setting on the subs? It works fine during playback but clearing the subtitle setting on the account itself is not a desired change. I’m not sure if it does this on audio as well but I don’t have much dual audio stuff to test on.

I’m on a shield pro btw if that matters.

**Comment by midusch** [comment]
Got the same issue.
Also for me I have some additional issues.

When I selected English subtitles in Plex, Kodi mostly has subtitles disabled when I watch en Episode.
And on files with multiple subtitles, it sometimes randomly chooses any of them.

I guess all in all it would be nice if the subtitle settings would just be read but not changed or anything.

**Comment by Chalanxe** [comment]
Happening with mine as well.This is after playing the video file on a pkc client and switching back to the plex app on the same file for me

**Comment by king8084** [comment]
i have tried literally everything possible within kodi and PCK to fix this...no slice

this is ruining my experience, every single video i play on pck will make that file sub default NONE for good unless i manually change it...this is not ok

**Comment by croneter** [comment]
Fixed with 3.4.2 and 2.14.0

**Comment by lvpro** [comment]
This issue has returned in recent builds.  
  
I've verified it occurs on Kodi 20 & 21 with both the latest STABLE & BETA of PKC.  

Specifically if I configure an external SRT in Plex for a file, the first time I play the file through PKC, it's set back to NONE on the Plex Server (which in effect means you can only use the external SRT on playback exactly 1 time and will need to download it again via Plex).

**Comment by croneter** [comment]
Kindly open a new issue @lvpro
