### ISSUE TITLE
plex companion port - docker pms

### ISSUE THREAD

**Issue by thejck** [croneter/PlexKodiConnect#1197]
I just switched my plex server to run in docker in linux
i have the following ports open
ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

when using the plex app on my phone I can see my various plexkodiconnect devices that I can fling too. However when using the plex app on windows or the web browsers I cannot see the plexkodiconnect as options to fling too.  Any thoughts on what to look for?

**Comment by thejck** [comment]
interestingly enough i switched docker to use host networking and this started working.
I would really like to know the port I missed to prevent pkc from showing up in the plex web ui if possible.

**Comment by croneter** [comment]
See here: https://github.com/croneter/PlexKodiConnect/blob/master/resources/settings.xml

3005 and 32412. Websocket connections need to be allowed, at least for one of these ports
