### ISSUE TITLE
Kodi library not containing Trailer info

### ISSUE THREAD

**Issue by fatshotty** [croneter/PlexKodiConnect#1198]
hello
first of all thanks for great addon

## Describe the bug
I'm using PlayTrailer addon. It works fine with movie that I have on my hd e synced with kodi videolibrary.
It is not working on movie that has been synced with PKC. I think the problem could be caused by "trailer_id" info missing in the database.
Is it possibile to sync the trailer id as per kodi videolabrary?

thank in advance

## To Reproduce
1. Sync Movies library with PKC
2. sync personal HD folder with movie
3. install Play Trailer addon from ufficial kodi repo
4. Context menu on Kodi videolibrary Movie and then click on Play Trailer
5. context menu on PKC movie
6. NO player trailer entry found

## Expected behavior
PlayTrailer should appear on context menu for each movie item

**Comment by ThomasKat** [comment]
If there IS indeed a trailer in Plex, PKC will sync this info to Kodi. Then `Play Trailer` will be available. If not, not.

I'm looking into faulty IMDB IDs, that might be the cause of this...

**Comment by croneter** [comment]
Seems like there is no easy way to manually call the Kodi scraper on library items stemming from Plex that do NOT yet have a trailer. This needs some hacking...

**Comment by fatshotty** [comment]
thanks for reply.
I think this could be a very good feature

Fat

**Comment by croneter** [comment]
Implemented with PKC version 3.0.4

**Comment by xenophobentx** [comment]
Is there any way to have an option to override plex trailers with imdbs trailers? As plex trailers has issues with skin autoplay trailer integration. See this issue i reported: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/issues/724
