### ISSUE TITLE
Not appearing on PMS dashboard when playing media with PKC (revisited)

### ISSUE THREAD

**Issue by renzzla** [croneter/PlexKodiConnect#1199]
Last year I raised issue #961 where basically, if I played a file on an SMB share from my Kodi box running PKC, and then played something from Plex, there would be no indication on the PMS dashboard that I was playing anything, and Tautulli would not show anything connected. This was fixed in PKC and all was good. However....

I've just started using a remote server that serves files via an https:// link, and I'm finding that after playing a file on that server, if I then play something on Plex using PKC, I have the same issue as before - nothing appears on the PMS dashboard or in Tautulli.

I assume that maybe the original fix was only for SMB shares and not for anything else? Is there any way this could be fixed for https:// links as well?

I've put a full debug log at https://we.tl/t-KcTsJDUjxW

Thanks

**Comment by croneter** [comment]
Thanks for this log. Something is definitely off, you got a lot of these log entries:
```
DEBUG: PLEX.subscribers: PKC playqueue is still initializing - skip update
```
I will look into it

**Comment by croneter** [comment]
Darn, your log upload was deleted. @renzzla could you please be so kind and upload your Kodi debug log again, preferably directly here on GitHub? Just drop the file here into this dialog when you're replying to my message; you might need to rename the log to end with `.txt`

**Comment by renzzla** [comment]
Here you go.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/4995888/kodi.log)

**Comment by croneter** [comment]
Sorry that I did not get back in touch with you. The problem is that the file you're playing (the direct path) is not stored in the Kodi video database:
```
NOTICE: VideoPlayer::OpenFile: https://USERNAME:PASSWORD@username.lw905.usbx.me:443/files/Laurie/Test-file-on-https-server.ts
...
PLEX.kodimonitor: Need to initialize Plex and PKC playqueue
...
PLEX.kodi_db.video: Did not find a video DB match
PLEX.kodi_db: No kodi video db element found for path https://username:password@username.lw905.usbx.me:443/files/Laurie/ file Test-file-on-https-server.ts
PLEX.kodimonitor: No Plex id obtained - aborting playback report
```
Workaround: make sure that you chose `Direct Paths` in the PKC settings under `Sync Options`, `Playback Mode` and subsequently reset the Kodi database (under `Advanced`). It should work then
