### ISSUE TITLE
movie not marked as watched 

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#120]
tried letting the move finish on its own and also stopping at the end credits and it consistently returns to the main menu as "in progress". PMS says it's watched but Kodi does not. 

Logs on Pastbin:
http://pastebin.com/CV2u6F5S

**Comment by croneter** [comment]
Looks like this is caused by Kodi Krypton :-(. Could you downgrade without a lot of hassle and try again?

**Comment by hstamas** [comment]
I don't have a Jarvis 16 install anymore but let me set one up and test it out. Might be a week or two before I can get it up and running and have time to watch a movie all the way through.

**Comment by MartinAyla** [comment]
There are some fixes in Krypton that I need for my setup, so I can't downgrade to Jarvis;

Wouldn't it be a good idea to ensure that PKC is Krypton compatible, before the general release?

I know that we're only at Beta 5 or 6, but the RC is probably not too far away and then suddenly there will be a lot of PKC/Krypton users.

Thanks for all you work on PKC! :)
