### ISSUE TITLE
_delete_kodi_db_items: variable 'types' undefined in some cases

### ISSUE THREAD

**Issue by gyre** [croneter/PlexKodiConnect#1204]
When starting kodi, I get an error about "local variable 'types' referenced before assignment'.

Looking at the kodi log file, I see that it's in _delete_kodi_db_items in sections.py.

Looking at the python code I see the following:

```def _delete_kodi_db_items(section):
    if section.section_type == v.PLEX_TYPE_MOVIE:
        kodi_context = kodi_db.KodiVideoDB
        types = ((v.PLEX_TYPE_MOVIE, itemtypes.Movie), )
    elif section.section_type == v.PLEX_TYPE_SHOW:
        kodi_context = kodi_db.KodiVideoDB
        types = ((v.PLEX_TYPE_SHOW, itemtypes.Show),
                 (v.PLEX_TYPE_SEASON, itemtypes.Season),
                 (v.PLEX_TYPE_EPISODE, itemtypes.Episode))
    elif section.section_type == v.PLEX_TYPE_ARTIST:
        kodi_context = kodi_db.KodiMusicDB
        types = ((v.PLEX_TYPE_ARTIST, itemtypes.Artist),
                 (v.PLEX_TYPE_ALBUM, itemtypes.Album),
                 (v.PLEX_TYPE_SONG, itemtypes.Song))
    for plex_type, context in types:
```

So I can see that for some reason `section_type` isn't one of the 3 values.  I temporarily got around the problem by setting `types` to `()` above the if statement and avoided that particular error.

![43438437-B1FA-490D-874B-CFAC4D66E044](https://user-images.githubusercontent.com/434906/88485335-04f87c80-cf6d-11ea-952c-ee9140fc7bd7.jpeg)

**Comment by croneter** [comment]
Please upload the entire log here, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by gyre** [comment]
Yup, I wish I'd saved it at the time.  After performing the simple workaround, pkc was able to continue, so I was able to re-initialize the database.  I'm unable to get the error to happen now, so I'm guessing whatever deletion / migration that pkc did once it got past the error has righted itself.

As I've now got easier access to the shield tv's internal filesystem from my debian box, I'll be in a better position to grab the log if/when this happens again.

**Comment by ThomasKat** [comment]
I'd really love to have a look at the log file. I can fix the immediate issue easily, but I'm afraid that something "further up the chain" could cause issues in the long run

**Comment by croneter** [comment]
I'd really love to have a look at the log file. I can fix the immediate issue easily, but I'm afraid that something "further up the chain" could cause issues in the long run

**Comment by gyre** [comment]
I'll keep an eye on my log file now you've done a patch to spit out the section type.

**Comment by croneter** [comment]
Thanks a lot for reporting this! PKC version 2.12.3 should fix this issue. Please let me know here if this is not the case.
