### ISSUE TITLE
Addon path, kodi crashes when i try to launch a movie

### ISSUE THREAD

**Issue by Noustaa** [croneter/PlexKodiConnect#1207]
Hi i know this issue has been solved normally in previous version but i still get it...

The media files are on a server in another place. I do not have access to direct path for security purpose so i am obliged to use addon path.

here is the log https://pastebin.com/sMQTNmty

I have tried disable Plex companion, no change.
I have uninstall completely kodi and reinstall cleanly and still the same issue.

Thanks for your help
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/5009289/kodi.log)

**Comment by croneter** [comment]
What does crashing mean, exactly?

Try disable image caching in the PKC settings under artwork

**Comment by Noustaa** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/5009980/kodi.log)

Hi Thanks for your answer!
Crash means that when i launch a movie, it loads while few seconds and then kodi closes itself suddenly without any errors showing.
Please find the new log as attached with the image caching disabled. Still not working unfortunately.

Thanks

**Comment by Noustaa** [comment]
hey problem is solved, i had to completely reset my PC to get it to work. I don't know what was the issue tho.
