### ISSUE TITLE
Option "Also show already watched movies" doesn't work

### ISSUE THREAD

**Issue by rmellid** [croneter/PlexKodiConnect#1208]
In Apperances Tweaks, Movies, the option: "Recently Added: also show already watched movies" doesn't work anymore. It's like always off.
In older version, it worked. (I don't remember which version)

Using now last 2.12.2
Thanks

**Comment by ThomasKat** [comment]
Are you sure that you're using the **PlexKodiConnect" widget? There's a TON of other Kodi widgets around - PKC won't change them, obviously...
To check, navigate to Videos, Video Add-ons, PlexKodiConnect, then any Movie library, then "Recently Added"

**Comment by rmellid** [comment]
just check the image....

![kodioption](https://user-images.githubusercontent.com/53934742/89715738-21061000-d9a8-11ea-8834-c7426fc1a3ea.png)

**Comment by croneter** [comment]
That is completely irrelevant to the advise above. If your using another widget than PKC, then PKC won't be able to do anything. 

Could you please check as explained?

**Comment by rmellid** [comment]
![plexoption2](https://user-images.githubusercontent.com/53934742/89762913-ae08b080-daf1-11ea-8a2b-2ea0aef22ea4.png)
 Just checked now, I don't use another widget. I did a fresh install of kodi and only pkc add-on.
I navigate to video/..../recently added --> all is fine.
You can see in the in the new "print screen". The list on the the right is ok, but not in the left. 
With older version of pkc, the watched movie was also added in recently added.

**Comment by croneter** [comment]
This has nothing to do with PlexKodiConnect but is up to the Kodi skin "Estuary". Estuary does NOT display already watched movies under "Recently added movies" and there is, unfortunately, nothing that PKC can do about that. 
    
You have different options to solve this issue you're having:
* Use another Kodi skin that let's you select the homescreen widgets (you can't do that in Estuary). When selecting widgets, choose the PKC ones navigating like this: Videos -> Video Add-ons -> PlexKodiConnect -> name of your Plex movie library -> "Recently added". 
* Hack the Estuary xml files to also show watched movies if you feel comfortable doing that. To get you started: https://forum.kodi.tv/showthread.php?tid=307231
