### ISSUE TITLE
Feature request: several path substitution patterns

### ISSUE THREAD

**Issue by marc-spinozza** [croneter/PlexKodiConnect#121]
It would be nice to expand current path substitution feature to have list of substitution patterns per plex library.

My Plex libraries uses to have several paths to, potentially, several disks. With the current feature I am forced to set up links behind a common folder to all the sources in a library. This has a performance hit when the sources are hosted in different machines.

**Comment by DivinityCycle** [comment]
Seconded, having to symblink everything to a single folder isn't ideal.

**Comment by croneter** [comment]
Now on feathub.com: http://feathub.com/croneter/PlexKodiConnect/+12
