### ISSUE TITLE
Install from URL

### ISSUE THREAD

**Issue by appark** [croneter/PlexKodiConnect#1211]
Is there a way for me to install plexkodiconnect by url since AppleTV doesnt have usb c port

**Comment by ThomasKat** [comment]
As far as I know, it's currently not yet possible to load PlexKodiConnect by an URL, unfortunately 😞

**Comment by croneter** [comment]
As far as I know, it's currently not yet possible to load PlexKodiConnect by an URL, unfortunately 😞

**Comment by appark** [comment]
So any idea how I can install plexkodiconnect on a APPLETV 4k since it doesnt use USB C?  I have tried the google drive method but it didnt work?

**Comment by croneter** [comment]
Thanks for reporting this, I wasn't aware that this was an issue 🙈 . It's now possible to quickly install PKC without uploading a ZIP file.     

See here: https://github.com/croneter/PlexKodiConnect/wiki/Installation
