### ISSUE TITLE
Direct Stream with selective audio-track

### ISSUE THREAD

**Issue by krendll** [croneter/PlexKodiConnect#1213]
Hello. Is it possible to add Direct Stream with selective audio-track? This function is very useful when you need to play high-bitrate mkv with multiple audiotracks, and total bandwidth higher then your network could achive. I have this function in tizen plex client (just have to disable direct play in settings), and when i start video on tv, plex repacks single video and single audio track to a single container on the fly.
Thank you.

**Comment by croneter** [comment]
I have to tell you that this feature request of yours is not high priority.

Please open a feature request here to see if others also want this feature: http://feathub.com/croneter/PlexKodiConnect
