### ISSUE TITLE
PKC : impossible to hide Photos or Music Library from Plex

### ISSUE THREAD

**Issue by Boggyb01** [croneter/PlexKodiConnect#1219]
Hello Croneter,

My setup : Plex Media Server running on NAS, Kodi 18 and PKC installed on Vero4k+. PKC is set as Direct Path. Everything runs smoothly on the video side.

I have recently added a music library and a photos library on my Plex server. These 2 libraries are being displayed automatically on Kodi main screen. I am trying to hide those 2 libraries but the PKC Setting in the Sync Option menu "Select Plex librairies to Sync" does not display the photo or music library. So I cannot un-check them

Probably a node functionality here?

![Plexlibrairies](https://user-images.githubusercontent.com/54419966/93748169-1a4df800-fbf8-11ea-8941-000fc47c1c81.jpg)

**Comment by croneter** [comment]
Hmm, showing elements on your Kodi home screen is entirely up to the Kodi skin and NOT PKC. Could you try another skin?

**Comment by Boggyb01** [comment]
Yes indeed, some others skin let me add shortcuts I wants, the one I was using displays all librairies and I cannot adapt them

Sorry and thanks
