### ISSUE TITLE
PKC stuck at 99% while syncing libraries (movies)

### ISSUE THREAD

**Issue by grbatrain** [croneter/PlexKodiConnect#1222]
## Describe the bug
After installing PKC libraries wont sync. Always gets stuck at 99%. Ive waited over an hour a couple of times. When deleting/removing the movie it is stuck at it just stucks at an other one at 99%. Doenst matter which one.

Ive tried running older versions of Kodi Leia as well as the beta version for PKC. I also did a factory reset on the shield but the result is the same. 

If i search by folders within the PKC Addon i can see the movies/folders there and they are accessible. Im connected via 1Gbit wired connection. Normal Plex runs without an issue

##Log
https://pastebin.com/yJR4Vfdg

## To Reproduce
1. Install PKC stable or beta. both newest versions
2. select (setup PKC); 1. Add Path, 2. Disable music library, 3. no additional artwork, 4. no to how many versions of a file, 5. no fine-tuning,
3. Restart Kodi
4. PKC/Plex opens --> select user --> showing libraries --> select 
5. done

Thank you

**Comment by Soulplayer** [comment]
I have the exact same bug. Also using an nvidia shield (2017)

**Comment by Rob-122** [comment]
I keep running into this as well I believe it has to do with sets because the movie it gets stuck on, I open plex remove the tag>collection then save - restart kodi and wait for the scan to reach the next one and do the same until I find all the problem movie sets keeping the list of movies in notepad. Once I have got them all and the scan completes I can then add the tag back in plex and it updates kodi almost immediately. I thought it had something to do with old data in kodi but just had to do the same on brand knew setup on the new google Chromecast after just doing it yesterday on windows. good news is once you fix it it seems to work as it should from then on hope this helps

**Comment by Rob-122** [comment]
Just finished this one on Android Google Chromecast and the list of movies that got stuck was only 3. On windows it was about 7

**Comment by Soulplayer** [comment]
This morning it suddenly worked without a problem. I changed nothing.

**Comment by grbatrain** [comment]
> This morning it suddenly worked without a problem. I changed nothing.

Hello. Thanks for your information ill try it out this Weekend and get back to U. Did U do a fresh Install etc? Or just opened PKC and started to sync?

**Comment by Rob-122** [comment]
yes my clients were fresh installs but have had my plex server for many years

**Comment by grbatrain** [comment]
> I keep running into this as well I believe it has to do with sets because the movie it gets stuck on, I open plex remove the tag>collection then save - restart kodi and wait for the scan to reach the next one and do the same until I find all the problem movie sets keeping the list of movies in notepad. Once I have got them all and the scan completes I can then add the tag back in plex and it updates kodi almost immediately. I thought it had something to do with old data in kodi but just had to do the same on brand new setup on the new google Chromecast after just doing it yesterday on windows. good news is once you fix it it seems to work as it should from then on hope this helps

That actually worked. I finally can use the shield as Client.

Ive deleted all collections and after that it just worked. Thank you

**Comment by croneter** [comment]
Does BETA version 2.12.4 fix this annoying problem? *fingerscrossed*

**Comment by croneter** [comment]
Any news here whether the patch worked? @grbatrain, @Soulplayer, @Rob-122

**Comment by croneter** [comment]
Darn 😢 . Thanks for testing, @Soulplayer !

**Comment by grbatrain** [comment]
@croneter sorry totally forgot to post again. PKC works perfectly on all my devices now. Thank you:) really like the addon

**Comment by croneter** [comment]
Sure this is still an issue, @Soulplayer ? Unfortunately, I don't manage to replicate this but...

**Comment by croneter** [comment]
Anyone else having this issue still?

**Comment by Soulplayer** [comment]
You can resolve this ticket. It is fixed for me!
