### ISSUE TITLE
"Recently Released Movies" Widget

### ISSUE THREAD

**Issue by rajil** [croneter/PlexKodiConnect#1223]
Hello,

PlexKodiConnect is working quite well for me. However, I miss the "Recently Released Movies" widget which appears in native Plex under "Movies>Recommended". 

Is there any skin/addon which can show the "Recently Released Movies" similar to Plex?

Thanks

**Comment by croneter** [comment]
Just point your widget to Videos - Video Add-ons - PlexKodiConnect - More... - Recently released
