### ISSUE TITLE
PKC Incorrectly Matching Certain Titles for extra Fanart

### ISSUE THREAD

**Issue by nightwingxwally** [croneter/PlexKodiConnect#1224]
## Describe the bug
PKC seems to be incorrectly matching certain titles on fanart.tv. I noticed some of my titles weren't downloading logo art (despite fanart.tv having plenty for the titles.) It seems to be happening with movies that have multiple entries on Fanart.tv's search, with PKC pulling data from the first result rather than the one that actually has art.  

Not sure if this is a bug or if there is a way to fix this on my end so that it pulls from the right entry? I've looked through the various settings on PKC and Kodi and haven't come up with anything - but there are a ton of customization options so I apologize if I did overlook it. Thanks for your help and thanks for all the hard work that goes into this -- it's made my Plex experience 100x better and more beautiful! <3

## To Reproduce
Adding a film such as 'X-Men: First Class' (2011) to Plex. Plex matches and pulls the metadata properly on Plex's side and grabs the right posters, background images, etc.  Loading PKC and refreshing the library does not download extra fanart for this title onto Kodi. Searching for the title on Fanart.Tv brings up four results, with only one containing images: https://fanart.tv/?sect=all&s=X-Men+First+Class The right result is not the first one, but is the only result to actually have images.

Some other titles that are also not pulling in extra fanart and seem to also have weird fanart.tv search results with the top result having 0 images: Hereditary: https://fanart.tv/?sect=all&s=Hereditary  Fantasy Island: https://fanart.tv/?sect=all&s=Fantasy+Island 

Also - For what it's worth: I was able to fix one title that Plex matched correctly but was not pulling extra data on PKC (Oculus). For this one, the year needed changed: Fanart.TV had two entries for this film: One in 2013 and one 2014. Changing it to the year that had images on Fanart.tv in Plex and refreshing PKC grabbed the right data. The problem though still seems to be that for the titles like X-Men, Hereditary, etc. the entries are all the same year so it's not a simple fix of changing something in Plex for it to match - at least that I can see.

If there is any other data or info you need from me, please let me know. :)

**Comment by croneter** [comment]
Nice catch - thanks for the report!

**Comment by croneter** [comment]
Hopefully fixed in [PKC **beta** version 2.12.5](https://github.com/croneter/PlexKodiConnect/releases/tag/2.12.5). Let me know here if this is not the case
