### ISSUE TITLE
nfs direct play?

### ISSUE THREAD

**Issue by droopified** [croneter/PlexKodiConnect#1225]
i want to dive into this but i was watching some youtube videos and they use smb paths. my server has nfs paths so all the movie folders are in the root of nfs://server/mnt/user/Movies/ and i only use direct play within my network. if i have a movie that requires transcoding i usually switch to plex but 99% of the time i am on kodi.

will there be any difference if i change it to nfs. if possible? and what would be the proper way to make these changes?

**Comment by croneter** [comment]
Nfs paths are supported by pkc.just make sure that Kodi can access your shares before you start on the pkc side - see the how to here on the wiki

**Comment by croneter** [comment]
There is no downside, by the way
