### ISSUE TITLE
stuttering & freezing

### ISSUE THREAD

**Issue by Soulplayer** [croneter/PlexKodiConnect#1226]
I have some problems with PKC on my nvidia shield. When playing files sometimes the frames start to drop and after a while it completely freezes kodi. It takes a long time to respond to a command (like stopping). I attached a log. I'm not sure if it is really PKC related but I don't know kodi that well to understand the logs.

It started after a while when playing Doom Patrol S01e02

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/5404323/kodi.log)

**Comment by croneter** [comment]
This is not pkc related at all. Pkc hands over the video for playback to Kodi. It's then up to Kodi. I guess your hardware is not strong enough, e.g. you have an older raspberry pi, and you might be trying to play HEVC video. Pkc can help you with this if you choose Force Transcoding from the PKC context menu

**Comment by Soulplayer** [comment]
Just want to let you know that the plex app does not stutter nor freezes while playing the same file without transcoding on the same device?

**Comment by croneter** [comment]
Sorry, but again this is not a PKC issue. PKC successfully passes the original (!!) filename of the video to Kodi, so your direct paths are working correctly:
```
VideoPlayer::OpenFile: smb://10.0.1.8/video/Media/TV Series/TV Series/Doom Patrol (2019)/Season 01/Doom.Patrol.2019.S01E02.WEBDL-2160p.h265-NIXON.mkv
```
Then it's entirely up to Kodi. The Kodi forum people might be able to help you. 

I don't know why the Plex app works, sorry.

**Comment by Soulplayer** [comment]
Okay thank you! I will post the log on the Kodi forums.

**Comment by croneter** [comment]
Could you please link to your forum post here on GitHub? Makes it easier for others with similar problems to follow along :wink:
