### ISSUE TITLE
https direct play does not work due to credential failure

### ISSUE THREAD

**Issue by hacktek** [croneter/PlexKodiConnect#1227]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
I exposed content via HTTP/S using nginx and added basic authentication to it. 
I validated that it's working using the browser and curl.
I added that as a source in Kodi with credentials and can browse and play content.

The above should allow me to use direct play paths by replacing /mnt/ with https://files.hostname.com/ but it does not. When PKC tries to sync I see the following error in nginx:

`172.18.0.6 - - [20/Oct/2020:15:22:50 +0000] "HEAD /Media/TV/TV/Show/Season%2009/Show%20(1994)...-bmf.mkv HTTP/1.1" 401 0 "-" "Kodi/18.8 (Linux; Android 9.0; SHIELD Android TV Build/PPR1.180610.011) Android/9.0.0 Sys_CPU/aarch64 App_Bitness/64 Version/18.8-(18.8.0)-Git:20200727-45686bddb1" "186.32.164.155, 162.158.123.24"`

Note the 401 response code. So it looks like PKC is not sending credentials properly.

As a test, I disabled authentication and created an nginx acl to only allow my requests and that fixed the problem so it's definitely an auth issue.

## To Reproduce
1. Add an https source to Kodi protected by basic authentication
2. Configure PKC and use the builtin tool to define credentials. I tried both http and https as protocol and I'm 100% sure the username and password are correct.
3. Replace path so mount style base path (/mnt/) has an https://files.hostname.com/ substitution path.
4. PKC will complain about not being able to sync items and ask if you want to stop syncing.

## Expected behavior
Direct play to work properly as path exists and should be accessible with added credentials.

All of this was done on a shield, I'll try to reproduce on my laptop to get a log file more easily.

**Comment by hacktek** [comment]
Log says:

```
2020-10-20 10:12:27.923 T:123145452584960   ERROR: CCurlFile::Exists - Failed: HTTP returned error 401 for https://files.hostname.com/...oR.mkv
2020-10-20 10:12:27.934 T:123145452584960 WARNING: PLEX.api: Cannot access file: https://files.hostname.com/...oR.mkv
2020-10-20 10:12:27.941 T:4478586304   DEBUG: ------ Window Init (/Users/xxx/Library/Application Support/Kodi/addons/plugin.video.plexkodiconnect/resources/skins/Main/1080i/script-plex-options_dialog.xml) ------
2020-10-20 10:12:27.941 T:4478586304    INFO: Loading skin file: /Users/xxx/Library/Application Support/Kodi/addons/plugin.video.plexkodiconnect/resources/skins/Main/1080i/script-plex-options_dialog.xml, load type: LOAD_ON_GUI_INIT
2020-10-20 10:12:27.946 T:4478586304   ERROR: Control 1001 in window 13000 has been asked to focus, but it can't
```

This is what passwords.xml looks like. This look right?

```
<passwords>
  <path>
    <from pathversion="1">https://files.hostname.com/</from>
    <to pathversion="1">https://user:pass@files.hostname.com/</to>
  </path>
</passwords>
```

**Comment by croneter** [comment]
Entire Kodi debug log please!

**Comment by hacktek** [comment]
https://pastebin.com/TwACWj5A

**Comment by croneter** [comment]
Great to hear! PKC/Kodi *should* use the passwords.xml you provided automatically. It do not know why that did not work. I haven't seen anyone using https credentials like you though
