### ISSUE TITLE
Clarify: use Kodi Music Videos alongside PKC

### ISSUE THREAD

**Issue by kmshort** [croneter/PlexKodiConnect#1228]
Kodi does it better - Plex's implementation of music video handling is a joke/is ridiculous.
I have about 500 music videos, each with local information.
Can I keep Kodi handling music videos, but use PKC to grab metadata from plex for everything else?
thanks.

**Comment by croneter** [comment]
Unfortunately, PKC won't leave your Music Videos alone as they are part of the Kodi video database. If you first install PKC or if you later reset the Kodi database manually from the PKC settings, you will delete the entire database including your Music videos.

BUT: if you get PKC up an running first, then add your Music Videos automatically e.g. from nfo files you should be fine. Just do NOT mess around with your music video metadata manually as you are likely to somehow loose these changes.

That good for you?

**Comment by kmshort** [comment]
> Unfortunately, PKC won't leave your Music Videos alone as they are part of the Kodi video database. If you first install PKC or if you later reset the Kodi database manually from the PKC settings, you will delete the entire database including your Music videos.
> 
> BUT: if you get PKC up an running first, then add your Music Videos automatically e.g. from nfo files you should be fine. Just do NOT mess around with your music video metadata manually as you are likely to somehow loose these changes.
> 
> That good for you?

Thanks for the reply.
Unfortunately I don't think that will work. Unless I'm mistaken, I can't add new music videos in kodi and add them to the database. Which is something I si regularly do.
It's a shame because I love the idea of PKC because my plex information is just so accurate.
I've spent ages on my local music video nfos and have a lot of them. I use Kodi party mode a lot for my music videos. Plex treats music videos like an afterthought, it's terrible.

Thanks for your response though.

**Comment by croneter** [comment]
> Unless I'm mistaken, I can't add new music videos in kodi and add them to the database. Which is something I regularly 

I don't understand. Why should that not work? Just add source, then let Kodi scan the .nfos, no? This AFTER you set-up PKC

**Comment by kmshort** [comment]
> If you add new videos later, rescan the source

So when PKC syncs the Plex meta data (and it will routinely), it doesn't touch the kodi database (which the music videos are stored in, with metadata scraped from local source)?

**Comment by croneter** [comment]
> So when PKC syncs the Plex meta data (and it will routinely), it doesn't touch the kodi database (which the music videos are stored in, with metadata scraped from local source)?

Correct, PKC should leave your music videos untouched.
