### ISSUE TITLE
"Cannot connect" - tried everything

### ISSUE THREAD

**Issue by TooUnCool** [croneter/PlexKodiConnect#1229]
For some reason I am getting a "PlexKodiConnect error - please check the logs". I have made sure the repository is updated, tried the release version and the beta all to no avail. I am using Coreelec on an OdroidC2, v 9.2.4.2 although I also tried downloading to 9.2.3 with the same effect. I can get into Settings, but if I try to change anything or do a complete reset, it errors out.

This was working and I cannot for the life of me work out why it now isn't. It's working fine on a couple of FireTVSticks around the place. Can anyone enlighten me?

**Comment by croneter** [comment]
I need your debug logs, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
No log no help possible

**Comment by TooUnCool** [comment]
Apologies, I have a day job and am not always in front of my device. Don’t worry, I will work it out.
