### ISSUE TITLE
Suggestion: "choose library" isn't determined by colour

### ISSUE THREAD

**Issue by jt196** [croneter/PlexKodiConnect#1231]
This isn't a bug, sorry just a suggestion. Think it's a simple fix and hopefully would have saved me a bit of head scratching. 

In the config, you're able to choose which library to sync: TV, films etc, it brings you out of the config (slightly odd behaviour but I'm sure there's a reason for that like calling to the server), then you have to choose which library to sync. Currently the behaviour in my version of Kodi (Embuary skin) is that it changes colour - it's white or yellow for yes or no. 

I'm not sure if this is skin based or it's plugin related, but if the latter, some checkboxes or whatever design you wished to go with would be super helpful as it's currently difficult to understand whether something is checked or not. 

Cheers.

**Comment by croneter** [comment]
The color is decided by the skin, sorry. I know it's not optimal right now 😞

**Comment by jt196** [comment]
A radio button or check box would be super useful! The colour is just not enough to indicate which one is on and which is off!

**Comment by croneter** [comment]
Sorry, but that's entirely up to the skin and not PlexKodiConnect. The one you're using seems to be a bit silly regarding user friendliness and seeing whether something is active/selected or not 😉 . Below is my skin "Aura", no issue at all. 
Workaround: switch skin...

![image](https://user-images.githubusercontent.com/4637940/98379008-14489500-2047-11eb-8b1f-cc655fb887ea.png)

**Comment by jt196** [comment]
Looks like something to take up with the author of the skin then!
