### ISSUE TITLE
On Deck: Continue episode in progress

### ISSUE THREAD

**Issue by drt1** [croneter/PlexKodiConnect#1232]
Hi croneter,

is it possible to have the same „in progress“-widget (if it is called that way, that stuff on kodi home screen) for single TV show episode than for movies?

There already is a „in progress tv shows“ widget in kodi, but this shows only seasons.
What I mean is on episode basis, so i can continue a half-watched episode directly from kodi home screen?

Thanks, BR

**Comment by croneter** [comment]
All the PlexKodiConnect "widgets" can be found by navigating to Add-Ons -> Video Add-Ons -> PlexKodiConnect -> (name of the Plex library) -> [whatever]. You might want to check "On Deck" there or "More..."

You can try to use Kodi's widget magic to get what you want. Please check the Kodi forum. I won't implement a new widget like you described, sorry...
