### ISSUE TITLE
seasons being showed as just S

### ISSUE THREAD

**Issue by DirtyNightmare** [croneter/PlexKodiConnect#124]
there is a issue where it just show the S out for all the seasons instead of showing season 1 season 2 and so on

**Comment by croneter** [comment]
Could you please share a Screenshot?

**Comment by DirtyNightmare** [comment]
![20161016_182328](https://cloud.githubusercontent.com/assets/13226293/19418953/c9e10afa-93ce-11e6-979e-555cd102f542.jpg)
and thats how it is shown on all the tv shows

**Comment by croneter** [comment]
Does the issue persist with other skins? Especially the Kodi standard one?

**Comment by DirtyNightmare** [comment]
yes on aeon nox estouchy and estouary
my folder structure is Season 2\S02E03E04E05\Show Name - S02E03E04E05 - Ep Name Show.Name.S02E03E04E05.HDTV.XviD-RLSGROUP.ext

**Comment by croneter** [comment]
This strongly smells like a Kodi Krypton Beta-issue :-(. 

Have you tried resetting PKC? Go to the PKC settings, Advanced, then the red "Reset database". Kodi will ask 3 questions, hit YES, YES, NO

**Comment by bartolomesoriano** [comment]
@croneter, maybe this has something to do with the fact that the user has each episode in a separate folder, which I don't think is standard naming either for Kodi or Plex.

**Comment by DirtyNightmare** [comment]
that didn't worked but the strange thing is that the specials is showing right

**Comment by DirtyNightmare** [comment]
i dont have any trouble with it if i just add them directly to kodi or plex so i dont think thats the issue

**Comment by croneter** [comment]
Is this still an issue?

Can you try to go to Add-On -> Video Add-On -> PlexKodiConnect -> "Reset playlists and video nodes", then reboot Kodi?

**Comment by DirtyNightmare** [comment]
i just took a look today and now they are all shown right i think it might had been fixed in krypton beta 5 or 6
