### ISSUE TITLE
Watched status between plex app and pkc bug (re-producable)

### ISSUE THREAD

**Issue by king8084** [croneter/PlexKodiConnect#1240]
When you watch something on plex and dont finish it, then finish it on pkc...it wont tell plex the updated status. The status will always remain based on the original plex paused moment

**Comment by croneter** [comment]
I cannot reproduce your bug. Please share your DEBUG Kodi log files according to https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by king8084** [comment]
> I cannot reproduce your bug. Please share your DEBUG Kodi log files according to https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Hmm

Quick testing and seems it works for movies. But if i tried to do it in series it wont work. Weird

Will produce a log

**Comment by croneter** [comment]
No log, no help possible.
