### ISSUE TITLE
Is this a bug or intended feature? Video Transcoding if Transcoding necessary

### ISSUE THREAD

**Issue by mason1171** [croneter/PlexKodiConnect#1242]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
- Video Transcoding if Transcoding necessary differs between Kodi 18.8 clients. On my iPhone 8 Plus, I can set the quality at **4K, 50Mbps** while my Win 10 laptop is restricted to **1920x1080p, 40Mbps**

## To Reproduce
1. PKC Settings > Playback > Video Transcoding if Transcoding necessary
2. Try to set the option as 4K on different clients

## Expected behavior
- I expected the "Video Transcoding if Transcoding necessary" to be unlocked but it is not. Can this feature be unlocked if possible? It is the only method I know to transcode 4K HDR to 4K SDR. 

## You need to attach a KODI LOG FILE!
Windows - https://paste.ubuntu.com/p/tW7482NxXQ/
iOS - https://paste.ubuntu.com/p/9GSQyydrxm/
    
I am aware that I can delete Plex tokens that I accidentially posted by following the [instructions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server)

**Comment by croneter** [comment]
Hopefully fixed in [PKC **beta** version 2.12.5](https://github.com/croneter/PlexKodiConnect/releases/tag/2.12.5). Let me know here if this is not the case

**Comment by mason1171** [comment]
Thank you.

**Comment by mason1171** [comment]
> Hopefully fixed in [PKC **beta** version 2.12.5](https://github.com/croneter/PlexKodiConnect/releases/tag/2.12.5). Let me know here if this is not the case

Thanks. Ill let you know
