### ISSUE TITLE
PKC and Kodi 19/ python 3 - now available!

### ISSUE THREAD

**Issue by artzox** [croneter/PlexKodiConnect#1243]
Hi, I see that this issue has been brought up before, so apologies for resurfacing it. Is this still being actively worked on? 
I have a plasma tv and need to use transparent subtitles to avoid permanent burn-in, already have some. Kodi 18 does not provide this option, so kodi 19 (using beta 19)is a must but pkc does not work with python 3 and I am no programmer to get this working. 
Is it possible to get pkc working under kodi 19 or solve subtitles issue under kodi 18?
Thanks

**Comment by croneter** [comment]
Work in progess, yes. No estimated time of arrival though, sorry...

**Comment by artzox** [comment]
Thanks!

**Comment by drt1** [comment]
Is there any news on how long it will take _approximately_?
I setted up a fresh machine, and Kodi <19 has been removed from distribution package repository, so currently I am stuck.
If you say it will be _days_, then i will wait.
If it is _weeks_ or _months_ i have to find another solution in between.

Thanks for your great work!

**Comment by amitgir** [comment]
+1 Thanks @croneter

**Comment by croneter** [comment]
# Want to use PlexKodiConnect with Kodi 19 Matrix and you know what you're doing?
Then manually install PKC and the 2 helper add-ons from ZIP using these branches:
* PKC itself: https://github.com/croneter/PlexKodiConnect/tree/python3
* Helper for movies (required): https://github.com/croneter/plugin.video.plexkodiconnect.movies/tree/python3
* Helper for TV shows (required): https://github.com/croneter/plugin.video.plexkodiconnect.tvshows/tree/python3

No support whatsoever, still in development. Music needs some more love, for example

**Comment by Hunk4TH** [comment]
> 
> # Want to use PlexKodiConnect with Kodi 19 Matrix and you know what you're doing?
> 
> Then manually install PKC and the 2 helper add-ons from ZIP using these branches:
> 
>     * PKC itself: https://github.com/croneter/PlexKodiConnect/tree/python3
> 
>     * Helper for movies (required): https://github.com/croneter/plugin.video.plexkodiconnect.movies/tree/python3
> 
>     * Helper for TV shows (required): https://github.com/croneter/plugin.video.plexkodiconnect.tvshows/tree/python3
> 
> 
> No support whatsoever, still in development. Music needs some more love, for example

Thanks so much for letting us try a py3 build!

**Comment by porkchop999** [comment]
Working fine for Movies. Getting AttributeError: 'str' object has no attribute 'decode' for TV Shows

**Comment by croneter** [comment]
@porkchop999 
Working fine here. Could you share some logs please?

**Comment by artzox** [comment]
hmm, I am getting an error message - xbmc.python ver.2.1.0 could not be satisfied, using the latest version for Android TV.
Any help with that?

**Comment by porkchop999** [comment]
Debug Log https://pastebin.com/Gtmc9dpf

**Comment by ioncewasacat** [comment]
> @porkchop999
> Working fine here. Could you share some logs please?

If you need another:
https://paste.kodi.tv/kiqesixopu

**Comment by drt1** [comment]
Works great, thank you. As soon as I find out how to buy bitcoins I will donate u.
Thanks for the great, quick job

**Comment by artzox** [comment]
Working for me as well, thanks.
Just one issue - I started getting an error message on kodi start - "If web server authentication is enabled, a password must be entered as well".
I haven't changed anything installing PKC.

**Comment by drt1** [comment]
I got the same popup message, even if webserver was disabled. I enabled webserver and set a password, then the message went away.

**Comment by croneter** [comment]
New code online, please update @drt1 , @artzox , @ioncewasacat , @porkchop999 
* "If web server authentication is enabled, a password must be entered as well" has been taken care of
* AttributeError: 'str' object has no attribute 'decode'  should be fixed

**Comment by ioncewasacat** [comment]
> New code online, please update @drt1 , @artzox , @ioncewasacat , @porkchop999
> 
> * "If web server authentication is enabled, a password must be entered as well" has been taken care of
> * AttributeError: 'str' object has no attribute 'decode'  should be fixed

Works well for me! Thanks for all the work and help.

**Comment by porkchop999** [comment]
Yes fixed the error thank you so much

**Comment by artzox** [comment]
Thanks!

**Comment by jools5000** [comment]
Excellent news! Thanks for the hard work @croneter

**Comment by artzox** [comment]
Hi, I am assuming Music is not yet integrated or available as separate zip, is this correct.

Thanks
