### ISSUE TITLE
Prerolls

### ISSUE THREAD

**Issue by n4tur3502** [croneter/PlexKodiConnect#1245]
Is it possible to get prerolls to play before movies in kodi 18.9? I haven enabled the option to play extras but nothing happens before movies.

**Comment by croneter** [comment]
You're probably using direct paths. If so, you need to start the movie by using the Kodi context menu, then Plex Settings, then Play via PMS

Does that work?

**Comment by n4tur3502** [comment]
I am indeed using direct paths. When i go to the context menu and select the plex options and play via pms it still doesnt play the prerolls.

**Comment by croneter** [comment]
Do you have a Plex Pass? You need one for trailers...

**Comment by n4tur3502** [comment]
I do not have plex pass, although the prerolls play fine in plex web player and the plex media player for windows. Guess it might be time for a lifetime pass.

**Comment by croneter** [comment]
Plex Pass is needed
