### ISSUE TITLE
Problem scraping content

### ISSUE THREAD

**Issue by pacomaral** [croneter/PlexKodiConnect#125]
Hello, i just installed the plugin in libreelec 7.0.2 and when it is scraping the tvshows (the movies are scrapped well after some tries), wich has 2100 items, my raspberry always restart when it has 650~ items. I don't know what it could be, i already changed the recommended configuration for raspberry to 1 and still having the problem. What could be the problem?

**Comment by croneter** [comment]
Post your log as described here - https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
I would be interested in failed "tries" of scraping movies too! Scraping should happen in one single go

**Comment by croneter** [comment]
Is this still an issue?

I personally use a raspberry pi with LibreElec. No issue with scraping. At all. Please share your logs if you do have issues.

**Comment by marc-spinozza** [comment]
I had the same problem after updating to 1.4.0 but now running 1.4.1 the sync is working fine again.
I tried to reduce the number of threads to 1 (as recommended in the wiki) but kodi continues rebooting at the same point of the library syncronization.

Sorry, I deleted the logs so can't provide more clues to track the problem down

**Comment by croneter** [comment]
I am stuck without logs :-(

If Kodi rebooted, the Kodi crashlogs would be perfect

**Comment by croneter** [comment]
@pacomaral 
PKC 1.4.1 should ideally solve your issue. If not, please share your crashlogs!

**Comment by pacomaral** [comment]
Sorry, i hadn't much time this days. I will try to update to that version and if not I will upload the logs tomorrow or so. Thanks

**Comment by croneter** [comment]
Should be solved with 1.4.1 and 1.4.2. Let me know if that is not the case
