### ISSUE TITLE
pkc 3.0.1 'resources.lib.utils' has no attribute 'try_decode'

### ISSUE THREAD

**Issue by xing0r** [croneter/PlexKodiConnect#1262]
PlexKodiConnect 3.0.1
Kodi 19.0-BETA2 (18.9.821)

with every pkc-sync I get this error:

[https://pastebin.com/raw/hTe8RQmr](https://pastebin.com/raw/hTe8RQmr)

best regards

**Comment by croneter** [comment]
Thanks for the report! Fixed with PKC version 3.0.2
