### ISSUE TITLE
Sync is stuck at 100% and kodi is unresponsive

### ISSUE THREAD

**Issue by Cyriltra** [croneter/PlexKodiConnect#1267]
Hello,

PKC v2.12.6

Everything was running flawlessly for a long while. Then today i noticed kodi became unresponsive (stuck on whatever the current screen is) with the top banner from PKC indicating a sync at 100% on my latest added TV show episode.
I reboot several time, but as soon as PKC is syncing that particular episode, kodi get stuck.
The thing is this happen only few seconds after booting, so i can't even go to PKC's setting to rebuild database (which I would like to avoid if possible).

in the log, i see "NOTICE: PLEX.default: plugin.video.plexkodiconnect stopped". 

Thank you
[01_KODI.log](https://github.com/croneter/PlexKodiConnect/files/5791233/01_KODI.log)

**Comment by croneter** [comment]
Please share a DEBUG log file, see here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Did you try to delete the PlexKodiConnect userdata folder when Kodi is not running?
* Navigate to the Kodi userdata folder, see https://kodi.wiki/view/Userdata
* Delete the entire folder `plugin.video.plexkodiconnect` within the directory called `addon_data`

**Comment by Cyriltra** [comment]
Hi, 

i fixed the issue by renaming "_plugin.video.plexkodiconnect_" under **Addons** folder (not **Userdata -> addon_data**) and rebooting. 
Not sure what was the issue though, but this way I keep all my settings and database as is (did few checks, all good).
If the issue come back again, I will submit proper logs
