### ISSUE TITLE
Genre Syncing

### ISSUE THREAD

**Issue by rjcogin** [croneter/PlexKodiConnect#128]
I've been editing the genres of my media a lot lately but to get it to sync to KODI I have to do a database reset. Any chance genres can be synced with a normal sync?

**Comment by croneter** [comment]
If you changed the genre on the PMS and they don't get synced within at most 2 minutes, then unfortunately no.

This is an issue on the Plex side - the PMS doesn't mark an element as "changed" in some circumstances :-(
