### ISSUE TITLE
Problems Playing Pictures

### ISSUE THREAD

**Issue by viking2** [croneter/PlexKodiConnect#1287]
I have a small picture folder with jpg images that I can play fine in Plex (using OpenPHT). 

In Kodi (v18.9.0), with the current PKC, the same picture folder shows up when I use the Night skin, but not when I use the default skin (Estauray).

If I try to play the images in the folder, using the Night skin, it goes to the the 2nd image which takes 1 sec to load and is displayed for a fraction of a second and then repeats.  I have to click on Stop/Pause multiple times to get it to stop. 

Here is what it looks like:
https://i.gyazo.com/8f398bae6c7260a8fe844100004c84d2.gif

Note: Before I installed PKC, I tested to play the same pictures and it worked fine (using either skin). I deleted the picture folder path in Kodi before I installed PKC.

**Comment by viking2** [comment]
The new issue (https://github.com/croneter/PlexKodiConnect/issues/1297) may be relevant to this problem

**Comment by croneter** [comment]
How are you playing the pictures, exactly? How do you navigate within Kodi? Please also share a DEBUG log file, we. Here https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by viking2** [comment]
As I mentioned originally, I only see my Plex "photo" folder if I use the Night Skin. You mention in the other issue that there may be a problem with the Night Skin, so forget about playing the pictures for the moment.

**With the default skin (Estauray):** 
In Plex, I have a "photo" folder with photos (jpg pictures).
In Kodi, I don't have a "photo" folder. I have a "picture" folder, but it is empty.

What do I need to do to get PKC to import my Plex "photo" folder to Kodi'?

**Comment by croneter** [comment]
Using Estuary, navigate to Addons - Picture Addons - PlexKodiConnect - name of your library.

When you set a Kodi widget for any skin, also navigate like that! ("picture addons"!)

**Comment by viking2** [comment]
1. I created a new blank **Profile w/o PKC**: 
a. Using Estuary, I navigated to Pictures => Add Pictures and added the path to a "picture folder" with a few pictures.
b.  I navigated to Pictures => My new "picture folder". I can see the images listed.
c. I click on the first image, and **it is shown in full screen**. If I use the left/right arrow keys (in full screen mode) I can view the next image.
d. I move the mouse to the left part of the screen and start "View slideshow". The **images are automatically viewed one after another**.  
Everything works as expected.


2. I next switch to my **Profile with PKC**:
a-b. Using Estuary, I navigated to Addons => Picture Addons => PlexKodiConnect => My "picture folder".
c.  I click on the first image, I see the "double circle" for fraction of a second and then nothing.  **The picture is not shown full screen**. If I use the left/right arrow keys it now just moves between the images.
d. I move the mouse to the left part of the screen and start "View slideshow". **It fails as described in my original post:** It goes to the the 2nd image which takes 1 sec to load and is displayed for a fraction of a second and then repeats. I have to click on Stop/Pause multiple times to get it to stop.
Here is what it looks like:_
https://i.gyazo.com/8f398bae6c7260a8fe844100004c84d2.gif

Could you please try to add a picture folder with a few images and try what I described above?

Thanks in advance.

**Comment by croneter** [comment]
Solved with PKC version 2.12.10 or 3.0.5. Let me know here should this not be the case...

**Comment by viking2** [comment]
Works now with version 2.12.10. I didn't realize that there is a version 3.0.5.
Is that also for Leia? What is the difference? How do I get it?

**Comment by croneter** [comment]
It's for Kodi Matrix only
