### ISSUE TITLE
Trying to browse for subtitles hangs Kodi (four copies of "PlexKodiConnect Masterlock Hack")

### ISSUE THREAD

**Issue by viking2** [croneter/PlexKodiConnect#1288]
I wanted to browse for subtitles, but the only paths I see are four copies of "PlexKodiConnect Masterlock Hack":

![](https://i.gyazo.com/8ab004acbfaa54523601f534d821985d.png)
If I click on one of those, Kodi hangs.

Kodi v18.9.0 (default skin) & current PKC 

Note that I have also seen these four copies of "PlexKodiConnect Masterlock Hack" in other menus, but I cannot recall where.

**Comment by viking2** [comment]
Here is a menu I get after selecting "Videos". It also has the four copies of "PlexKodiConnect Masterlock Hack"
![](https://i.gyazo.com/88a44b46762b9260360f5eb889ff10ff.png)

**Comment by croneter** [comment]
These copies of a "Hack" are by design

**Comment by viking2** [comment]
> 
> 
> These copies of a "Hack" are by design

I had expected to see paths to my local hard drives in the "Browse for subtitles" window.  Is that not correct?
What do you see?
If you see the same thing as me, what happens when you click on one of "PlexKodiConnect Masterlock Hack" links?

**Comment by croneter** [comment]
These hacks are only needed for PKC to function correctly. Not for you to click on, unfortunately. So no subtitles there, sorry. Subtitles are automatically "added" to a playing video if this is possible

**Comment by viking2** [comment]
I actually had questions about subtitles (which I need).  In Plex, I have installed subzero which is hard to use manually now that the UI is no longer exposed. In Plex, I also have the option to manually demand subtitle download from OpenSubtitles.

In Kodi, I believe that there are two options:
1. As a Service  
2. By using an Addon
I don't have either installed (Services are empty).

I am not sure that I understand:  "Subtitles are **automatically** "added""? Maybe you meant that they are added if a Service is available? 
If so, I though that I would still need to manually request a subtitle from a configured Service?

That brings me to my next question, which I think that you have indirectly answered: Would adding subtitles from the Kodi side mess up the database in any way? Strictly speaking, by doing so, we are not exclusively using Plex to manage our media....
