### ISSUE TITLE
Adding Subtitles from the Kodi side?

### ISSUE THREAD

**Issue by viking2** [croneter/PlexKodiConnect#1289]
In Plex, I have installed subzero which is hard to use manually now that the UI is no longer exposed. In Plex, I also have the option to manually demand subtitle download from OpenSubtitles.

In Kodi, I believe that there are two options:
1. As a Service  
2. By using an Addon
I don't have either installed (Services are empty).

In another issue (now closed: https://github.com/croneter/PlexKodiConnect/issues/1288), you stated:  "Subtitles are **automatically** "added""? Maybe you meant that they are added if a Service is available? 
If so, I though that I would still need to manually request a subtitle from a configured Service?

That brings me to my next question, which I think that you have indirectly answered: Would adding subtitles from the Kodi side mess up the database in any way? Strictly speaking, by doing so, we are not exclusively using Plex to manage our media....

**Comment by croneter** [comment]
PlexKodiConnect automatically "exposes" the **PLEX**-subtitles if you start playing a video. Using the Kodi facilities like a subtitle add-on (try e.g. [Opensubtitles](https://kodi.wiki/view/Add-on:OpenSubtitles.org)), you can download **additional** subtitles within Kodi while watching a certain video. Adding subtitles does not mess up anything. If Kodi can access the original video file (you've set-up direct paths and they are working), the subtitle is even saved right next to the video file. 

Some subtitles CANNOT be accessed by Kodi/PKC and there is nothing I can do about that. So don't wonder why a certain subtitle is missing from the Kodi side of things even though you can see the subtitle using Plex directly. If you still want to use that subtitle, use the Kodi context Menu for PlexKodiConnect and select "Force Transcode" - you'll then be prompted to select a sub, if any exist
