### ISSUE TITLE
Unable to finish sync with recent versions of pkc

### ISSUE THREAD

**Issue by joswart** [croneter/PlexKodiConnect#1295]
I was having issues with RottenTomatoes not showing up on my movies. Hoping a resync would fix the problem, I went into the settings of PKC, chose the red option (start allover again) and restarted Kodi.

Two observations: the sync on my large (>2500) movie collection was extremely slow. It takes around 0.7 seconds for a single movie to load. I remember past versions were way quicker, they would do a complete resync of everything in a couple of minutes.

Second observation: the sync never finishes. Funny thing is that it always stops 10-11 movies before the counter reaches the maximum, reaching to movie 2748 in a collection holding 2758 movies.

I have tested this multiple times on multiple devices: 2 NUCs und some H96 devices. They are all running the latest stable version of Libreelec (NUCs) or CoreElec (H96). They all show the same symptoms. Looking at the logs, the sync just freezes. No error messages, or anything, it just stops.

Reverting to a 2.11 or 2.10 version didn't fix the problem. Reverting to 2.9.11 fixed it: sync is very quick as well and finishes. If I then upgrade again to the latest version, everything works fine as well.

Rottentomatoes are still not there, probably not related.

**Comment by croneter** [comment]
Nothing I can do without a debug log file: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Hmm, PKC has been optimized for fast syncs. What you're describing suggests that another process or add-on accesses the database at the same time as PKC. Kindly share a log file, I might spot something. 

Other than that I'd suggest to completely reset Kodi and start from scratch

**Comment by croneter** [comment]
In other words: it might be purely accidental that old PKC versions worked fine...

**Comment by croneter** [comment]
"recent versions" is a problem: you MUST use the latest stable version of pkc. Otherwise there is indeed a bug that prevents the sync from completing!

When you used the latest version: was only the sync speed a problem?

**Comment by joswart** [comment]
I have reproduced this on multiple installations and it is very consistent. I am wondering whether it has to do with my Plex library.

I have multiple movie libraries in Plex. Two are small and one is very large. The sync speed on the small ones is good, with all tested versions of PKC (see above). The sync speed on the large one is extremely slow and never finishes with PKC > 2.9.11. I have tested the downgrade on multiple installations now and it always works.

My huge series library syncs quickly as well. It is just the major movie library that has issues. It would be nice if I don't have to recreate my library since it will remove all the view states for the different Plex users I have. Since everything works with PKC < 2.10 I am wondering what could have caused the change in behaviour.

As to the "recent versions": I have been playing with this issues for a couple of months now, I am not sure on what version I started seeing this, hence the recent versions. All my plugins update automatically to the latest stable on all my installations.

**Comment by joswart** [comment]
I appreciate you need a debug log. Is there a secure way to send that to you? I am not going to publish it here for everybody to see.

**Comment by joswart** [comment]
Missed your last sentence: with the latest (stable) version, the sync did not complete. It stopped 10 movies before completion. After a restart it had to resync 438 titles (the other 2000 or so where apparently there). But it halted again after 428. Ten seems to be a little bit of a magic number here, although I have seen 11 as well.

Multiple restarts gave the same result.

**Comment by croneter** [comment]
Let's turn this around - any chance you could give me, croneter, access to your Plex Media Server?

**Comment by joswart** [comment]
Turned around. Gave you the library with issues.

**Comment by croneter** [comment]
Thanks! Sync seems WAY too slow. Does the PMS log say anything?

**Comment by croneter** [comment]
If you want to send me some logs, you may use croneter@gmail.com

**Comment by joswart** [comment]
I will send you the log in a couple of hours. Running some tests myself.

Just "repaired" the plex database by following this: https://support.plex.tv/articles/201100678-repair-a-corrupt-database/. Seems to have the same result. All libraries are quick, but the main movie one.

I stopped kodi, removed the database (My* and plex*) from the .kodi/userdata/Database directory to get a relatively clean start.

Reverting to 2.9.11 gives me full speed.

**Comment by joswart** [comment]
Mail sent.

**Comment by croneter** [comment]
Any news?

**Comment by croneter** [comment]
Never mind - got your mail 🙈

**Comment by croneter** [comment]
This is the issue (excerpt from your PMS log):
```
WARN - QueryParser: Invalid field 'checkFiles' found, ignoring.
WARN - QueryParser: Invalid field 'skipRefresh' found, ignoring.
WARN - QueryParser: Invalid field 'checkFiles' found, ignoring.
WARN - QueryParser: Invalid field 'skipRefresh' found, ignoring.
WARN - QueryParser: Invalid field 'checkFiles' found, ignoring.
WARN - QueryParser: Invalid field 'skipRefresh' found, ignoring.
WARN - QueryParser: Invalid field 'checkFiles' found, ignoring.
WARN - QueryParser: Invalid field 'skipRefresh' found, ignoring.
WARN - QueryParser: Invalid field 'checkFiles' found, ignoring.
WARN - QueryParser: Invalid field 'skipRefresh' found, ignoring.
```
It is absolutely vital that `skipRefresh` and `checkFiles` are "understood" by the PMS when PKC syncs. Otherwise, it'll refresh the item and check whether a file exists. This takes forever... Could you kindly send an entire DEBUG or even "verbose" PMS log please? I can then see that the queries looked like - queries that work with every other possible PMS 🙄

**Comment by joswart** [comment]
Thanks for your support. I noticed that my library had language set to "none", which is funny, the other libraries didn't have that. I was unable to pick a language from the dropdown, so I bit the bullet and recreated my library.

The new library, naturally is quick and runs nicely. Question remains: what changed between 2.9 and 2.10 that coud have made it slow? Not that it is really important anymore, but still...

Thanks for your support! Really highly appreciated!

**Comment by croneter** [comment]
Nice!! That seems like a really weird Plex but!

> Question remains: what changed between 2.9 and 2.10 that coud have made it slow? Not that it is really important anymore, but still...
Yupp, but not worth investigating at this point, sorry
