### ISSUE TITLE
Can I turn off/on PKC?

### ISSUE THREAD

**Issue by viking2** [croneter/PlexKodiConnect#1296]
I sometimes don't know know if a problem is due to KODI/Addon or PKC . 

Is there some way to turn off PKC and use the KODI "native" database and later turn on PKC again (which uses a KODI database created from Plex)? I understand that I may have to switch between the two databases for this to work (where is it located?)?

For example, I tried a KODI Addon (https://forum.kodi.tv/showthread.php?tid=316342) to get TV-show IMDb ratings but it didn't work (The ratings were supposedly added but they are not shown) . I would like to "turn off" PKC temporarily to see if it works then.
(Note that Plex cannot get IMDb rating for TV-shows).

**Comment by croneter** [comment]
Yes, just disable the Kodi addon PlexKodiConnect - that shuts PKC down
