### ISSUE TITLE
PKC with Night Skin shows KODI and PLEX sections!?

### ISSUE THREAD

**Issue by viking2** [croneter/PlexKodiConnect#1297]
When I use PKC and the default skin (Estuary) the library looks "normal":
https://i.gyazo.com/2c3c2177b37b20b390f3adaa36444c0e.png

However, when I use PKC and the Night skin, the library has two sections
KODI: https://i.gyazo.com/be7d1a387cee61e2b50aca502c9bbc6c.png
and
PLEX: https://i.gyazo.com/b5fde75475c27b93fe11781046b53532.png

Is that by design? It is very confusing.

Note that "TV-shows" and "Movies" are both shown in KODI and in PLEX.
However, "Pictures" is only shows in PLEX with the Path: "Photos_TEST_PLEX". The KODI "Pictures" is empty.
As I posted in another issue (https://github.com/croneter/PlexKodiConnect/issues/1287), I am not able to play the images in "Photos_TEST_PLEX".

**Comment by croneter** [comment]
This is a skin "issue" - please take it up with the skin author in the Kodi forums. 

My guess is that the night skin detects the additional PKC libraries and adds video nodes automatically - something you don't want, apparently. When customizing the skin, you should be able to delete unwanted entries that show up on your home screen. But again: no skin support here!
