### ISSUE TITLE
[FeatureRequest] Automatically create customized shortcuts for different plex libraries

### ISSUE THREAD

**Issue by lews-therin** [croneter/PlexKodiConnect#1305]
Hello, 

Thanks for the great software, it's something I cannot do without for my home system. 

With regards to my request, having read https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins and getting a basic understanding of the home menu shortcuts; I would appreciate it if PKC could also generate at least a default set of split video items (maybe also could be part of the setup wizard, where it asks whether we'd like to get custom home menus per Plex library managed).

I hope it's a reasonable request which we could get to enjoy in the newer versions. Please let me know if you need me to elaborate on anything. 

Thanks!

**Comment by croneter** [comment]
That's impossible as it's unfortunately up to the Kodi skin. PlexKodiConnect already automates what's possible by providing a set of nodes per Plex library - the "shortcuts" you mentioned. Pkc cannot set them up for your skin automatically though: you need to select shortcuts manually when adjusting your skin
