### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '124349-163875600'

### ISSUE THREAD

**Issue by Claw256** [croneter/PlexKodiConnect#1307]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
When syncing from the Plex server, during the TV shows syncing, the error `ValueError: invalid literal for int() with base 10: '124349-163875600'` occurs. Here is the link to the sanitized kodi.log file with Debug logging enabled: https://www.mediafire.com/file/nqs57wgetzzzlfg/kodi.log/file

## To Reproduce
1. Perform a mnual library sync by going into PKC addon settings
2. Wait a minute or so
3. The syncing will stop with the Error message described above

## Expected behavior
No error should occur, it should perform the full library sync.

**Comment by Claw256** [comment]
How would I get the XML file of the episode `Madeira, My Dear`? I'm not the owner of the Plex server.

**Comment by croneter** [comment]
Thx! You need to be the owner, otherwise you can't get the xml (easily)

**Comment by Claw256** [comment]
> Thx! You need to be the owner, otherwise you can't get the xml (easily)

No bothers, I can talk to my friend and ask him to send me the XML file. What would he need to get?

**Comment by Claw256** [comment]
Any update to this? What should I request from my friend?

**Comment by croneter** [comment]
Should be fixed with 3.0.7 and 2.12.12

**Comment by Claw256** [comment]
Nice one, is this live in the beta version now?

**Comment by Claw256** [comment]
@croneter I tried installing the new version from the beta repo, but it won't install and it throws an error: 
```
DEBUG: CAddonInstallJob[script.module.requests]: requires script.module.idna version 2.6 which is not available
ERROR: CAddonInstallJob[plugin.video.plexkodiconnect]: The dependency on script.module.idna version 2.6 could not be satisfied.
```
Maybe something to do with the `script.module.requests` version?

**Comment by Claw256** [comment]
Sorry it is a Kodi problem with their mirrors, see here: https://www.reddit.com/r/jellyfin/comments/l8iool/android_tv_cannot_install_jellyfin_for_kodi_after
https://github.com/nixgates/plugin.video.seren/issues/492
