### ISSUE TITLE
Kodi 18.9 with PKC. Hanging when turn off

### ISSUE THREAD

**Issue by Massaguana** [croneter/PlexKodiConnect#1316]
Hello,

having same issues with Kodi an PKC with all my systems.. (MacOS, Ubuntu 18.04)

When i say Kodi "Leave" to close Kodi, the App Kodi Freez... nothing happens... same with OSX and Ubuntu

I log i fin this many times:

WARNING: Process directory 'http://XXXX:5324/library/parts/2797615/1418753956/' does not exist - skipping scan.

Here are an debug.log
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/5890523/kodi.log)

**Comment by croneter** [comment]
That's because you're using PkC add-on paths in combination with a Plex music library. There's nothing I can do, unfortunately. See here for more info: https://github.com/croneter/PlexKodiConnect/issues/14
