### ISSUE TITLE
Question about ?mode=search in Kodi Command

### ISSUE THREAD

**Issue by Claw256** [croneter/PlexKodiConnect#1323]
Hi,
Great job by the way with my previous issue, I was successfully able to sync the Plex server with everything synced up after :).

Anyway, I'm trying to get TheMovieDB Helper to work with PlexKodiConnect, but it takes a good 2 minutes for the movie to load once it is pressed. I know that this isn't your problem, but I just need a bit of information so I can figure it our. When I launch a move from the PKC library, it loads up instantly in 3 seconds. TheMovieDB Helper (GitHub repo: [https://github.com/jurialmunkey/plugin.video.themoviedb.helper](https://github.com/jurialmunkey/plugin.video.themoviedb.helper)) uses "players" to launch Movies/TV shows once they are clicked from, for example, a widget. Nobody has written a full player for it since an issue was made in February of last year.

The closest thing to a player we have at the moment is something that @jurialmunkey wrote in this issue of the repo: [https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/50#issuecomment-581176831](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/50#issuecomment-581176831). It was also said by him in another issue that this JSON file was never meant to be used as a player, but instead used a base that other people can create a player from it: [https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/224#issuecomment-629270618](https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/224#issuecomment-629270618) Just wondering, about calling the plugin plexkodiconnect, is this a valid URL to put in the `filename=` section of the call?: 
```
plugin://plugin.video.plexkodiconnect.movies/?mode=play&plex_id=1136413&plex_type=movie&filename=News of the World (2020) [tt6878306] [WEBDL-1080p DIVX MP3 2.0]-EVO.avi
```

See how there's spaces and dashes. Is that a valid filename to use when calling the plugin with `?mode=play`? That is an exact log line from my log file when playing media from TheMovieDB Helper. I should also point out that I am using jurialmunkey's base plexkodiconnect player linked above, even though it is not meant to be used long term.

I know that TheMovieDB Helper is not your repo, so I will probably ask in jurialmunkey's repo anyway about helping me out with this, but I just need to know what type of format should the `filename=` be when calling the plugin in a Kodi Command (i.e a player for TheMovieDB Helper).

Here's my debug enabled kodi.log for this issue, if you think that would be of use: https://www.mediafire.com/file/18a3uwebu5x00tr/kodi.log/file

**Comment by croneter** [comment]
You need to `urlencode` the filename (and everything else, really). This should do it:
```
try:
    # Python 3
    from urllib.parse import urlencode
except ImportError:
    # Python 2
    from urllib import urlencode
url = 'plugin://plugin.video.plexkodiconnect.movies'
args = {
    'mode': 'play',
    'plex_id': 1136413,
    'plex_type': 'movie',
    'filename': 'News of the World (2020) [tt6878306] [WEBDL-1080p DIVX MP3 2.0]-EVO.avi'
}
url = '%s?%s' % (url, urlencode(args))

```

**Comment by croneter** [comment]
Or you know what? Simply drop `filename` entirely, it should NOT be needed. `mode=play` and `plex_id=1136413` should suffice

**Comment by croneter** [comment]
Is this working out, @Claw256 ?

**Comment by croneter** [comment]
Any update here, @Claw256 ?

**Comment by Claw256** [comment]
> Any update here, @Claw256 ?

Sorry about the delay, I'm been busy with college during the week. I'm afraid that I'm not that good with Python, so I'm not sure if I would be able to make the required changes for this to work. I also switch over from Plex to Jellyfin recently for various reasons, so I can't test this change I'm afraid. Sorry about this.

**Comment by jurialmunkey** [comment]
FYI -- TMDbH already provides various types of urlencoded values which can be added as string format {keys} to the url, so there shouldn't be any need for python to construct a player:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/wiki/Player-Function#special-suffixes

I have no idea why someone would try to search by filename though as I'm sure there would be a lot of differences due to encodings etc. It makes way more sense to search by title via plugin directories.
