### ISSUE TITLE
Feature Request: Configuration option for updating watched status

### ISSUE THREAD

**Issue by fnwc** [croneter/PlexKodiConnect#134]
Hi,

I'd like to request that the update of watched status from Kodi to Plex be togglable.

I'm using a couple of Kodi plugins, such as Trakt and PseudoTV Live, and the automatic pushing of watched status from the PlexKodiConnect plugin is messing with my watched statuses, since I don't want them to be updated when watching PseudoTV Live.

Edit: Prefer to rather have it just ignore PseudoTV plays and keep the syncing intact.

**Comment by croneter** [comment]
I don't understand. How is PKC messing with your watched status when you're watching PseudoTV?

**Comment by fnwc** [comment]
Long story short, I use Trakt to track my watched status of my libraries, since it remembers whenever I install a new version of Kodi (for example).

Since I sometimes use Plex on my iPad to stream things, and Kodi at home, I use the Trakt plugins for each platform to record my watched status.

However, PseudoTV Live is just a kind of background "browsing" plugin I use, so I **don't** want to update my Trakt status while watching things, because of the nature of the plugin -- it acts as a kind of "live TV" browsing, so you might switch a channel to the middle of an episode.

PseudoTV Live has a setting to disable the Trakt plugin tracking, which is fine... that's what I want. However, due to PlexKodiConnect marking the episode as watched and then passing it to my Plex server, the Plex Trakt plugin then updates the watched status, which is wrong.

Maybe I'm thinking about this wrong? Can I disable the Plex Trakt plugin and still have my watched statuses sync for both platforms?

**Comment by croneter** [comment]
> Since I sometimes use Plex on my iPad to stream things, and Kodi at home, I use the Trakt plugins for each platform to record my watched status.

PKC does this for you! (core functionality actually) It will sync the watched state of Plex to Kodi in real-time. I would deactivate this in Trakt if possible - you don't want 2 plugins messing with watched states simultaneously. 

> However, due to PlexKodiConnect marking the episode as watched and then passing it to my Plex server, the Plex Trakt plugin then updates the watched status, which is wrong.

I think PseudoTV names the content it serves up in a specific way. PKC detects this and thinks it's a Kodi library element. Could you enable debug logging for both Kodi and PKC and then share the part of the Kodi log file where you start watching something on PseudoTV that is also in your library?

**Comment by fnwc** [comment]
Here you go. I think I scrubbed any personal information from the log (hopefully). Full log is available on request.

[pseudotvkodi-trimmed.txt](https://github.com/croneter/PlexKodiConnect/files/554646/pseudotvkodi-trimmed.txt)

**Comment by croneter** [comment]
Is this file actually on your server?  `smb://REDACTED/TV/Death Note (2006)/Season 01/Arigatou.Death.Note.S01E33.x264.AAC.mkv`

**Comment by fnwc** [comment]
Yes. I just removed the server name.

**Comment by KarlDag** [comment]
I stumbled on this discussion because I'm having the same problem. I also wish there was a way to stream PKC with PseudoTV live without having my server update the watched status.  Thanks for looking into it.

**Comment by hstamas** [comment]
I don't understand the point of using PKC if you don't want the watched status synced? Why not just use a local Kodi database install in this case and be 100% compatible?

**Comment by KarlDag** [comment]
Because my library is on my server and kodi is on my ShieldTV... Also, I would like to use kodi for my regular plex watching (with watched status) but use pseudotv for random background playback. 

Guess I could mount SMB shares to load the library in kodi, but pkc is much easier.

**Comment by fnwc** [comment]
@hstamas Actually, I would really prefer that it just ignore PseudoTV feeds for syncing, if that were possible, and keep the regular syncing.

**Comment by croneter** [comment]
I don't see how automatically ignoring PseudoTV is possible. PseudoTV starts movies/shows just like the user would. You'd have to manually toggle a `Don't update Plex watched status` manually

**Comment by croneter** [comment]
Now on feathub.com: http://feathub.com/croneter/PlexKodiConnect/+11

**Comment by poprokx** [comment]
I would like a way to turn off the watched tags/on deck progress tracking.... has anyone found a way for this?

To the people who keep saying "i don't understand why...." its simple, PsuedoTv takes your content and mimics live channels. I use it to watch random stuff or leave things in the background. Flicking through channels creates a mess on the on deck feature and loses track of your progress on shows, so when I go back to my plex its a mess and not where i left off. 

why don't i just use kodi native library? simple the scrappers for tv isn't working right for me right now (never had this issue before) and none of my shows pop up. So I decided to try this plugin to manage my library easier as im a plex user anyways and enjoy the server concept.

**Comment by poprokx** [comment]
QUICK FIX/WORKAROUND: Sign up a new user on plex.tv, share your sever library with the new user (no need to make a new sever), login to PlexKodiConnect with your new user. Setup channels in PsuedoTv, it will no longer change your watch list/on deck on your main sever and have its own separate database for that. 

Now this wont work if you want to still track show progress in kodi obviously, the only workaround for that is use the official plex app and drop using the native tv/movie library and PKC to access. This will allow you login to a different account (you main account). so that PlexKodiConnect is used to connect to your second account (syncing your main library to kodi and make available to psuedo tv with separate ondeck/watched) and plex official will be used to access your main plex server with proper ondeck info.


This is what I came up with using a little brain power, hope this comes useful for anyone else who might be trying to do the same thing... now to big question is what happends when my internet connection is down if lol if i have trouble accessing my content

Edit: they really need a way so i can edit/del my post on the feathub page to fix formatting
