### ISSUE TITLE
trouble connecting.

### ISSUE THREAD

**Issue by thecat18** [croneter/PlexKodiConnect#1345]
I am having trouble connecting to plexkodiconnect on my shield after getting a new router but still can get into plex. Any ideas.

**Comment by croneter** [comment]
No DEBUG log no help possible, see here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Closing until you share a log file, @thecat18

**Comment by thecat18** [comment]
I fixed it, I got a new netgear router & having the Armour security on preventing it from running.
