### ISSUE TITLE
Question: library management

### ISSUE THREAD

**Issue by christianlupus** [croneter/PlexKodiConnect#1346]
Hello,

I have a quick question regarding the usage of PKC. I installed it as described in the wiki and it worked straight. Now I tried to play a video on the Plex server and I have to go through a lot of steps in order to get the video running. I have to go to Add-ons / Plex / Videos / All / All / Video file in order to play it. For series, it is even one or two menus deeper.

When looking at the screenshots it seems the media registered with the Plex server are registered in the regular kodi lists. When I am on the home page of kodi (just freshly started), I can navigate to e.g. series or videos but kodi tells me there is nothing and offers me to remove that top menu entry. This seems counterintuitive to me to have to dig deep into the app navigation in order to see the media (c.f. discussion regarding taking over kodi's internal data structure). 

So I am asking, is this correct that the media quick links in the kodi top menu are empty or am I missing something?

**Comment by croneter** [comment]
Hell yeah, you're not using PKC like it's intended 😉 . All your Plex media will show up like "normal" Kodi media. 

You probably disabled synching of every single Plex library. Go to the PKC Settings, then Sync, then "Choose Plex libaries to sync". Select them all.
