### ISSUE TITLE
Plex/Link TV Loop

### ISSUE THREAD

**Issue by dangoodfellow86** [croneter/PlexKodiConnect#1347]
Hi There, I am trying to install PKC on andriod, it has worked previously. I am currently getting a loop when trying to sign in were it will take me to the plex.tv/link page, sign in and enter pin. this then goes back to the beginning and is then trying to get me to enter the link over and over then not adding the server. account is fine seems the auth is not being accepted by PKC.

**Comment by croneter** [comment]
No chance to help you without a debug log: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by dangoodfellow86** [comment]
Here is the log from debugging
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6017689/kodi.log)

**Comment by croneter** [comment]
Useless since it's only an excerpt. Kindly share the entire debug log please

**Comment by croneter** [comment]
Please share the entire debug log file, @dangoodfellow86

**Comment by dangoodfellow86** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6051935/kodi.log)
Here is the full log file

**Comment by croneter** [comment]
Hmmm, looks like your Plex Media Server is NOT signed in to plex.tv, is that correct? 

Hence PKC only detects your PMS because it's in the same LAN. When later trying to connect, the PMS demands a token - that we cannot get through plex.tv (since the PMS is not listed)

**Comment by croneter** [comment]
Any updates here, @dangoodfellow86?

**Comment by springjools** [comment]
I also have this issue.
