### ISSUE TITLE
Plex Media Server "bug" leads to frequent and slow syncs

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#135]
## Plex Media Server "bug"

You are affected if you experience frequent PKC syncs and if the number of `downloaded` items is almost always the same number as `processed` items:

![unbenannt](https://cloud.githubusercontent.com/assets/4637940/19736379/4d138a14-9baf-11e6-942d-3d704a6d7b71.PNG)

Currently, the Plex Media Server has an issue that leads to PKC needing to sync the entire library frequently, daily in my case. If you're unlucky (like me), the sync will take longer because the PMS will scan every single Plex item anew (which seems quite unnecessary). Keep your fingers crossed...

For more info, see https://forums.plex.tv/discussion/comment/1287014#Comment_1287014

## Latest Update (January 12, 2018)

PKC has been rewired to work around this issue as much as possible. You should not feel an impact now, **except** you may experience a slow first sync after installing PKC. 

The issue remains unchanged/fixed on the PMS side.

**Comment by milnash** [comment]
For people without Plex Pass and no access to the forum link - what is the current status?

**Comment by croneter** [comment]
@milnash 
See my very first post above

**Comment by croneter** [comment]
Possible fix imminent after a hint from Plex: https://forums.plex.tv/t/plex-server-cache-over-310gb/274438
