### ISSUE TITLE
Plex titles dissapear from kodi and ends up empty

### ISSUE THREAD

**Issue by djmulder** [croneter/PlexKodiConnect#1350]
Sorry for not using the template as I feel it's more a setting somewhere that I just can't find.

Here's the problem: After a few days both my list of movies AND my list of tvshows is empty. Today for the first time it was only the TVShows, so it seems like it's because of some syncing.

If I do a full reset in the addon all return to normal. But then again after a few days everything gone. 

Is this some setting I'm overlooking? It looks a lot like: https://github.com/croneter/PlexKodiConnect/issues/586 but it's not this issue. I have those settings done and they are not even available to movies. 

My plex setup isn't at all special, it's pretty much setup standard with movies in separate folders and tv shows in separate folders with seasons in subfolders.

Subquestion, which might be related but I'm not sure: I'm using the Simple IPTV addon from kodi, sure it doesn't touch movies/tvshows but you do write to let the plexkodi addon to handle everything. If this could be the case is there a way to get IPTV to work with this? And I don't want it in some submenu from the addon, it has to be under the "TV" menu (so different from TV Shows).

**Comment by croneter** [comment]
Pretty much impossible to troubleshoot right now. Could you please try to capture some DEBUG logs of episodes/movies disappearing? See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Please triple check that you tried the workaround in issue #586

**Comment by djmulder** [comment]
Hmm I'll try my best but going to be hard, I normally find out "after the fact" ofc and I'm still trying to pinpoint in what timeframe it happens (also for debugging) added to that it's a nvidia shield so going to be interesting to get to the logfiles. 

And about 586: 
![2021-02-20 20_37_09-Plex](https://user-images.githubusercontent.com/10437793/108606643-6f668380-73bb-11eb-8192-f9af873cd34b.png)

**Comment by croneter** [comment]
Any news?

**Comment by djmulder** [comment]
Today it was empty again... it's not related to a theory I had... at first I thought it was related to either "reset watch position" (or whatever that option is called) or "Mark as watched" .. but I used that function 3 days ago.

I'll debug log kodi start soon.. but gf is hogging the tv (and I don't blame her: simpsons)

**Comment by djmulder** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6051726/kodi.log)
There that's the log.. it's near the end apparently... it's getting empty messages I guess?

Ps I think I removed all passwords/tokens from the file..if you find one please tell me :D

**Comment by croneter** [comment]
Something is really off with your movie `Alien`: These log lines are repeated over and over again. Seems like the PMS is stuck with scanning that movie. 
```
ERROR: PLEX.websocket_client: PMS_Websocket: Error decoding message from websocket
ERROR: PLEX.websocket_client: {"NotificationContainer":{"type":"progress","size":1,"ProgressNotification":[{"message":"Scanning Alien?"}]}}
ERROR: PLEX.websocket_client: PMS_Websocket: Error decoding message from websocket
ERROR: PLEX.websocket_client: {"NotificationContainer":{"type":"progress","size":1,"ProgressNotification":[{"message":"Scanning Alien?/extrathumbs"}]}}
ERROR: PLEX.websocket_client: PMS_Websocket: Error decoding message from websocket
ERROR: PLEX.websocket_client: {"NotificationContainer":{"type":"progress","size":1,"ProgressNotification":[{"message":"Scanning Alien?/extrafanart"}]}}
```
Try completely deleting that movie from the PMS. Then re-adding it again.

**Comment by croneter** [comment]
Other than that, I can't see why some items were deleted on the Kodi side. Could you kindly reset the Kodi database (in the PKC settings under Advanced, hitting YES, then NO) and try to capture another log file of items "getting lost"?

**Comment by croneter** [comment]
What's the status here?

**Comment by djmulder** [comment]
Removed alien3 (that was the "alien" movie it was stuck on, it had like the 3 euh forgot the english word, when it's floating higher like the "to the power")

Now trying.. but also having a server upgrade, went for an Epyc. But ordered wrong mem >.< so waiting on that

**Comment by croneter** [comment]
I would still need another debug log to investigate further

**Comment by djmulder** [comment]
Yeah no problem.. mem should arrive before wednesday.. then it's back to testing.

Tho I have to say... now the server been offline for a few days (think last online was wednesday) and all lists are still in tact. So it's indeed to do when it reindexes or something.

**Comment by croneter** [comment]
Any news here?

**Comment by djmulder** [comment]
Sorry .. still waiting on memory. The shop I ordered my server upgrade from apparently has a hard time getting memory for an Epyc :(

**Comment by djmulder** [comment]
Ok server upgrade done.. Running a day or 2 now with Alien3 removed... so far all movies/series still there. Looking up

**Comment by croneter** [comment]
Closing for now.come back if the issue returns

**Comment by djmulder** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6211956/kodi.log)
and it's back... even did a full clear. (again if you see tokens/passwords pls tell, I tried to remove them all

2 nights ago I thought I caught it at the moment. I saw the popup "cleaning database", but then I read the log and saw that alien3 was still there.. but now it's really not here.

**Comment by djmulder** [comment]
@croneter did you see the message? (I'm not sure, rarely use github;)

**Comment by djmulder** [comment]
I'm starting to think it's related to the backend adding new series/ movies. The last week it's almost happening daily and this week I had quite a few movies/series coming in.

**Comment by djmulder** [comment]
I haven't had a problem in ages.. fully forgot to mention (busy period)

I think I fixed it by not having kodi clean database and stuff (had it every night at 2)

**Comment by wormvortex** [comment]
My library isn't set to clean/update at all so don't think that's my issue

**Comment by croneter** [comment]
@wormvortex No log no help possible: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by wormvortex** [comment]
Noticed it again this morning. All tv shows are empty. Here's the latest log since I've noticed it.

https://paste.kodi.tv/ecedexotug.kodi

**Comment by croneter** [comment]
Really difficult to troubleshoot this issue. I'm guessing that not PKC but Kodi is deleting entries in the Kodi video database. I see this in the log:
```
INFO <general>: CleanDatabase: Starting videodatabase cleanup ..
INFO <general>: CleanDatabase: Cleaning videodatabase done. Operation took 00:11
```
11 seconds seems a bit long to do nothing - here, deletion might've taken place. But that's just a guess since debug logging was not enabled, unfortunately.

**Comment by croneter** [comment]
Try this: deactivate `Update library on startup` for both Video and Music libraries. You find this in the Kodi settings under `Media`, then `Library`. Make sure that `Expert` level is enabled (bottom left)

![image](https://user-images.githubusercontent.com/4637940/140643143-5c3066b2-e383-4842-bb53-e07912f06d30.png)

**Comment by wormvortex** [comment]
Just doubled checked and it's not enabled for either library.

**Comment by croneter** [comment]
Your log clearly states that your library got cleaned! Do you have any Kodi add-ons that could be causing Kodi database cleanups?

**Comment by wormvortex** [comment]
None that I can see. Nearly all are disabled except up next and the ones that come with the skin. 

I do sometimes delete files by using the context menu and going Plex options and remove from server to delete watched things. Could it be that??

**Comment by croneter** [comment]
No, that's not it.

**Comment by croneter** [comment]
Have you tried to completely reset Kodi? That might help, but is a hassle 😞

**Comment by croneter** [comment]
Any updates here, @wormvortex ?

**Comment by wormvortex** [comment]
Yes a full reset seems to have sorted it. I reformatted the SD card and just started all over and as of now it's been fine :)
