### ISSUE TITLE
Use Local Assets

### ISSUE THREAD

**Issue by Drubei** [croneter/PlexKodiConnect#1355]
Thanks for this great Kodi addon @croneter.  Been using this for years and it just keeps getting better.
I'm currently using your Matrix build and have a question in regards to using local assets.

It seems PKC only pulls local posters and fanart background.  Any addtional fanart like landscape, thumbs, clearart, logos, etc are downloaded automatically if I have "Download additional art from FanArtTV" enable in the settings.  It is possible to have PKC use the local assets first  if available instead of only downloading random ones from FanArtTV?  I have all additional artwork saved in each movie/tv show folder and name correctly according to kodi naming convention.  I have also try disabling the settings but same result.

I've tested this and it works with Emby and Jellyfin plugin.  They both use the local assets first before attempting to download from FanArtTV.  I know that Plex doesn't support additional fanart natively and was wondering if this is possible.  I'm not sure if this could be a skin specific thing as well but from all the different kodi skins I've tested I get the same result.

Any insight from you would be great.  Thanks for all the hard work and keep it up!

**Comment by croneter** [comment]
Moved to featurehub: https://feathub.com/croneter/PlexKodiConnect/+65

**Comment by simtaj** [comment]
I think that this still no work. Am I right @croneter ? There’s no option to mark in PKC to let know KODI that is artwork locally saved ?
For me KODI doesn’t see extra artwork. PKC passes only poster and fanart to kodi.

**Comment by OGTK423** [comment]
Also interested to see if this is currently possible or is planned to be. I have locally stored art assets like Logo, Clearlogo, and Clearart properly formatted to work with Kodi but not sure how to get them properly utilized when using PKC.

The 'feathub' link above appears to point somewhere unintentional, looks like.
