### ISSUE TITLE
Playback setting "Jump back on resume" not working

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#136]
Mentioned this on the forum without any input so thought I would officially list it as a possible issue. When stoping a video  mid-way, when resuming the expected action is for PKC to resume xx seconds back according to this setting.

What I'm experiencing is quite the opposite. When resuming a video, playback starts many seconds ahead of the stopped position making me rewind to get back to where I originally stopped.
[kodi.log.txt](https://github.com/croneter/PlexKodiConnect/files/554660/kodi.log.txt)

**Comment by croneter** [comment]
The jump back on resume is actually not even implemented. 

Do you have to rewind for every single item? How many seconds approximately?

**Comment by hstamas** [comment]
If I stop a video and then resume, it consistently starts about 5 seconds forward. This is with Kodi 16.1 and lastest stable PKC.

**Comment by croneter** [comment]
What happens if you resume on another device, e.g. Plex for Android? Still 5 seconds ahead?

**Comment by hstamas** [comment]
Start playing in Kodi/PKC - stop - resume play in Plex for IOS - resumes at the correct spot.
