### ISSUE TITLE
Unable to see/play external audio tracks

### ISSUE THREAD

**Issue by OGTK423** [croneter/PlexKodiConnect#1360]
Hello. Don't think a log file is necessary for this issue but can upload if required!

**Issue**: Unable to select external audio tracks for playback

**Explanation**: Kodi allows you to play a video file alongside an external audio track by placing the video file and external audio file in the same folder. (ex. MyMovie.mkv and MyMovie.flac).

When a video file and audio file are in the same folder, with the same file name, Kodi allows you to select the external audio track to play with the video just like any other audio track included in the container.

This feature is not currently working when using PlexKodiConnect. When going to select audio tracks, _only_ the tracks within the container are selectable. External tracks _are not_ selectable.

I encountered the issue by attempting to play a video file with an external audio track in Kodi, from my Plex library via PlexKodiConnect.

I tested, and confirmed, the issue is present only when using PlexKodiConnect by taking my external hard drive, plugging it directly into my Nvidia Shield 2019, and playing the MKV file via Kodi's File Manager. The external audio track is selectable and playable via this method.

>

**Comment by croneter** [comment]
Are you using direct paths? That's a requirement for external audio tracks. See https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths

**Comment by OGTK423** [comment]
> Are you using direct paths? That's a requirement for external audio tracks. See https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths

Thanks for the prompt reply. Turns out I had not set up direct paths.

In Step 2 of the Direct Paths guide it mentions usernames and passwords. Are these just your login credentials for the host computer? Not sure which username or password I'm supposed to be using or where they're set.

Relevant folders are shared via SMB on the host.
