### ISSUE TITLE
Add support for season names (new in Plex Web 4.52.1) 

### ISSUE THREAD

**Issue by jgilf** [croneter/PlexKodiConnect#1361]
As Plex Web 4.52.1 has officially added the option to manually set/change season names, would it be possible for this to be implemented into PKC? I know there is already inbuilt support for season names in Kodi. 

See below example of what it looks like in Plex:

![Screenshot from 2021-02-24 00-43-49](https://user-images.githubusercontent.com/5531002/108924308-8395d380-768e-11eb-8514-71f63d64f033.png)

TheTVDB has started allowing for season names which will be able to be scraped by [the new Plex TV Show scanner/agent](https://forums.plex.tv/t/new-plex-media-server-tv-show-series-scanner-and-agent-preview/665778). See for example [American Horror Story](https://thetvdb.com/series/american-horror-story) and [Survivor](https://thetvdb.com/series/survivor).

**Comment by croneter** [comment]
Thanks for the pointer! Implemented in PKC version 3.0.12 and 2.12.17
