### ISSUE TITLE
Need assistance to setup direct path on Matrix 19

### ISSUE THREAD

**Issue by Lyechee** [croneter/PlexKodiConnect#1368]
Hi Croneter, 

First of all, thanks for your work on PKC, it has been working like a charm for one year on my Shield TV, awesome ! 

My problems started recently, when Kodi updated itself to Matrix, and simply broke everything. My first error was to uninstall Kodi to make a fresh install. PKC worked on Kodi 18, and I just saw the #1359 entry, explaining how to update without loosing the settings. 

**So, my setup :** 
- My NAS is a W10 PC, with folders "Films, Series, Documentaires, Concerts" shared. I granted all permissions to these folders to anyone on the local network (I don't care about security for this data) and unchecked the password share in the advanced sharing options. 
- A shield TV 2020 with the latest Android TV update and fresh install of Kodi. At this point, I will just start again with what you advise me for settings.
- Plex Pass 
- Kodi 19 broke the smb share (not supporting smbV1 if I understood well), so I added smb://NAS as a source with the user and password of the NAS and I can browse through the shared folders.

**The expected behavior :**
- Libraries should be visible via PKC in Kodi
- I would like to play medias with the direct link on the network (ex: smb://NAS/Films/Mon_film.mkv)
- If possible, I would like to use a Netflixe-like skin like Bingie MOD. I assume it needs to play automatically trailers, but I'm not sure. If not possible with Direct Play/Path, it's not a big deal. 

**The actual behavior :**
- Plex libraries are visible in Kodi
- When I go in the informations of the movie, it tells me that the path is "D:/Films/Mon_film.mkv", the path on the NAS system.
- Of course, when I try to read the movie, it tells me that the file doesn't exist and asks if I want to remove it.

I read all the wiki and other topics, but couldn't find the correct way to set this up. It's even more frustrating considering that this used to work before the samba issue with Kodi 19. I tried the renaming option making D:/Films to smb://NAS/Films but no success. 

Thanks in advance for your help on that matter,

Nicolas

**Comment by croneter** [comment]
I usually do not give assistance to configure PKC - no time for that. 

However - Try this: (making sure that the case is correct!! e.g. `D:\` and not `d:\` and obviously doing the same for tv shows)
![image](https://user-images.githubusercontent.com/4637940/109114564-1d688980-773e-11eb-92e5-e5971f0bbdfd.png)

Then in the `Advanced` section, hit `Reset the Kodi database and optionally reset PlexKodiConnect`. Then YES, then NO

Just install/use Bingie MOD as usual, everything should be working. I'd do that AFTER direct paths started working though

**Comment by OGTK423** [comment]
I'm experiencing this issue as well.
