### ISSUE TITLE
Minor issue / feature request

### ISSUE THREAD

**Issue by bkury** [croneter/PlexKodiConnect#1378]
Thanks for your continuous work on this wonderful addon, here are just 2 minor things:

Skip intro:
---
I just added the skip intro xml file to my skin and noticed that you named it "skip_intro.xml". It would probably be better to rename it to e.g. "script-plex-skipintro.xml" like every other skin xml file.

Context menu:
---
It would be really nice to have "Go to show" and "Go to season" context menu entries if an episode is selected. This would be useful especially for widgets to quickly go to the library and start binge watching.

Thank you!

**Comment by croneter** [comment]
Renaming is implemented and will be in future PKC versions, thanks for the input. 


I won't implement your feature request for the new context menu items. There's a million ways how PKC could further improve Kodi, that's only 1 example. Since PKC let's you use the Kodi library "as is", this can be solved e.g. by Kodi core, by another Kodi add-on (I'm sure there is one somewhere) or the skin. PKC is just the wrong place for this, sorry...

**Comment by bkury** [comment]
> Renaming is implemented and will be in future PKC versions, thanks for the input.

thanks!

 
> I won't implement your feature request for the new context menu items. There's a million ways how PKC could further improve Kodi, that's only 1 example. Since PKC let's you use the Kodi library "as is", this can be solved e.g. by Kodi core, by another Kodi add-on (I'm sure there is one somewhere) or the skin. PKC is just the wrong place for this, sorry...

Fair enough, may I suggest an alternative idea which might work for both of us?

You already add the DBID infolabel [Listitem.DBID] to your widget items, if you could also add support for KODIs TvShowDBID infolabel [ListItem.TvShowDBID] skin developers would be able to create a working "Go to show" link :

_ActivateWindow(videos,videodb://tvshows/titles/$INFO[Listitem.TvShowDBID]... ,return)_

Thanks!

**Comment by bkury** [comment]
Sorry to bother you again but are there any updates on this issue?
(ListItem.TvShowDBID support for "In progress" widgets)

Thanks!

**Comment by croneter** [comment]
Nope sorry

**Comment by bkury** [comment]
No problem, I found a different solution. 

It seems like it's not possible to set Listitem.TvShowDBID via the python interface anyway.
(ListItem.DBID is in KODIs python documentation but ListIItem.TvShowDBID is not)

Anyway, this issue won't affect anybody else than me, so no need to bother with it.

Thanks!

**Comment by croneter** [comment]
Ok thanks a lot for your feedback
