### ISSUE TITLE
kodi 17 b5 crash during sync of movies from plex server

### ISSUE THREAD

**Issue by Goga777** [croneter/PlexKodiConnect#138]
during synch of movies from plex server I have kodi 17 b5 crash

crash log here is
http://slexy.org/view/s20UIQOshX

Also I have old error 

PLEX.websocket_client -> ERROR:: Unknown exception encountered in connecting: Handshake Status 401

**Comment by croneter** [comment]
Kodi Krypton is still heavily being developed and instable. It's very likely that Kodi is the problem, NOT PKC. 

This error is already registered as https://github.com/croneter/PlexKodiConnect/issues/97
```
ERROR:: Unknown exception encountered in connecting: Handshake Status 401
```
Thus closing this ticket

**Comment by Goga777** [comment]
than I have created the ticket on kodi tracker
