### ISSUE TITLE
kodi Matrix with plexkodiconnect 3.0.13 Video wouldn't resume last play position

### ISSUE THREAD

**Issue by koonfoon** [croneter/PlexKodiConnect#1380]
kodi did ask me whether I wouldn't like to resume last play position or play from start, but when I chose resume play, it just start the video from the beginning.
My device is Samsung table tab s5e.

**Comment by croneter** [comment]
I can't help you without a DEBUG log file, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
@koonfoon Could you kindly share a DEBUG log file as described in the link above? Otherwise I can't help you

**Comment by croneter** [comment]
No log no help possible. Kindly share a DEBUG log and I'll look into this
