### ISSUE TITLE
kodi 17 b15 hanged after disable of PKC 

### ISSUE THREAD

**Issue by Goga777** [croneter/PlexKodiConnect#140]
if I will try to disable PKC then kodi will hang up

http://slexy.org/view/s21Bcqf4Zb

19:53:52 T:2642408352  NOTICE: PLEX.downloadutils -> Request session stopped
19:53:52 T:2642408352  NOTICE: PLEX.service -> ======== STOP PlexKodiConnect ========
19:53:57 T:3035435008   ERROR: CPythonInvoker(1, /storage/.kodi/addons/plugin.video.plexkodiconnect/service.py): script didn't stop in 5 seconds - let's kill it
19:54:14 T:2774406048   DEBUG: Thread JobWorker 2774406048 terminating (autodelete)
19:54:14 T:2757628832   DEBUG: Thread JobWorker 2757628832 terminating (autodelete)
19:54:14 T:2947539872   DEBUG: Thread JobWorker 2947539872 terminating (autodelete)
19:54:14 T:2685158304   DEBUG: Thread JobWorker 2685158304 terminating (autodelete)

if it is kodi issue, then I will create the ticket on kodi trac

**Comment by croneter** [comment]
Yes please, do that ;-)

**Comment by Goga777** [comment]
done
http://trac.kodi.tv/ticket/17054
