### ISSUE TITLE
PKC with Kodi Matrix won't resume on last play position

### ISSUE THREAD

**Issue by desigi** [croneter/PlexKodiConnect#1408]
## Describe the bug
When attempting to resume a movie, the movie will always start from the beginning even if having selected "Resume from...". This only seems to happen with movies. TV shows seems to work fine when resuming.

## To Reproduce
1. Go to a movie that has already been started.
2. Click on it to play the movie.
3. Scroll down to "Resume from [whatever time it was at]"
4. See that movie starts from the beginning and not from where you had previously left it.

## Expected behavior
The movie should play from the timestamp mentioned in the "Resume from..." context menu.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6153592/kodi.log)
The error appears on line 2920.

**Comment by croneter** [comment]
Hopefully solved with 3.1.0. Let me know here if this should not be the case
