### ISSUE TITLE
PKC plays in local network but not remotely

### ISSUE THREAD

**Issue by andrewmasca** [croneter/PlexKodiConnect#141]
cant play a video remotely from my server at home , yet is ok when play it locally using plexkodiconnect from the same network. Tried resetting database and creating another plex user with permissions and no joy. Yet am able to play directly from the plex website and or app

[kodilog.txt](https://github.com/croneter/PlexKodiConnect/files/580674/kodilog.txt)

**Comment by croneter** [comment]
Thanks for the report! Could you be so kind and play something (successfully) when you are at home and share the log file? The difference will be most revealing ;-)

**Comment by andrewmasca** [comment]
log attached, just scanned through it and have a lot of handshake errors? though the video did play , which i then stopped after around 30 seconds of playback
[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/580906/kodi.txt)

**Comment by croneter** [comment]
Handshake errors are a known problem: https://github.com/croneter/PlexKodiConnect/issues/97

However, you seem to have a different issue

**Comment by croneter** [comment]
Ough, sorry to tell you, but you did not delete your Plex tokens in the log files :-(. Just added a section to the Wiki. 

Please follow the bottom part of this: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

It is not enough to delete the logs you posted here, unfortunately...

**Comment by andrewmasca** [comment]
My mistake I did the 1st log posted but not the 2nd time apologies

**Comment by croneter** [comment]
No worries. But I am glad that you care!! :-D

**Comment by croneter** [comment]
Is it possible that you'd have a crappy Internet connection? Or that something is interfering with your connection? The connection seems to drop repeatetly. 
```
Failed: Timeout was reached(28) for https://94-0-248-166.607761a724784e5b9ce724a500f3d518.plex.direct:32400/library/parts/12329/album.nfo
```
Other Kodi plugins also have issues ONLY if you're not at home: 
```
File "C:\Users\formnet\AppData\Roaming\Kodi\addons\plugin.video.cutthekord1.0.8\default.py", line 22, in CATEGORIES
                                                link = OPEN_URL('http://cutthekord.esy.es/pluginimages/wizard6.txt').replace('\n','').replace('\r','')
                                              File "C:\Users\formnet\AppData\Roaming\Kodi\addons\plugin.video.cutthekord1.0.8\default.py", line 32, in OPEN_URL
...
HTTPError: HTTP Error 401: Unauthorized
```
Have you tried from only 1 place outside home or several?

**Comment by croneter** [comment]
Are you still having this issue or can I close?

**Comment by andrewmasca** [comment]
I've removed the add on. As just using Plex through the app instead. I'll try again once I've got fibre installed. Thanks
