### ISSUE TITLE
Linux direct paths

### ISSUE THREAD

**Issue by n4tur3502** [croneter/PlexKodiConnect#1413]
I have recently switched plex from a windows 10 machine to one running ubuntu server 20.04. I must be missing something because no matter what I do I cannot get direct paths to work. On my nas i have my video setup like this on the drive nas:\Media\Video then inside video i have movies, tv shows and 4k that all have media directly inside them. Then inside the video folder i also have anime and kids, both have a tv and movie folder in them with the media. My understanding is now that the server is linux i have to set all types of media to the same root folder? So like add a kids folder to my movies folder and move the kids movies there? That way the structure would be Media/Video/Movies then inside movies kids, anime and like regular folders?

**Comment by croneter** [comment]
No support for configurations, sorry. Would take too much time

 Try to access your drives from Kodi directly as explained in the wiki here. Only THEN worry about paths

**Comment by croneter** [comment]
Stick to add-on paths if that does not work
