### ISSUE TITLE
Kodi 19 Error: NoneType Object is not Callable

### ISSUE THREAD

**Issue by louisefindlay23** [croneter/PlexKodiConnect#1425]
## Describe the bug
I tried to force update so Kodi reflected my new Plex artwork but nothing happened so I reset the Kodi database. 

After I restarted Kodi, Plex data wasn't syncing back (no Plex libraries) so I uninstalled and reinstalled PKC Matrix Stable using your instructions in #1359 but the prompt to Select libraries to sync didn't appear. Trying to force it in PKC Settings resulted in NoneType Object is not Callable error. 

I also get that error when Kodi starts and occassionally when synced data. Before I reset the database, playback and syncing was working but with the error message.

## Help yourself
Force updated library
Reset Kodi database
Uninstalled and reinstalled PKC Stable from scratch
Provided Debug Log

## To Reproduce
1. Install PKC on Kodi 19
2. Restart Kodi
3. Set up PKC
4. Restart Kodi and Error message appears
5. Reset database

## Expected behavior
The error message shouldn't appear and force updating the Kodi database should work. When the database is reset, the select libraries to sync prompt should appear so Plex data can sync. Also, select libraries to sync should work via PKC settings.

## You need to attach a KODI LOG FILE!
http://paste.kodi.tv/cizoxiwasi.kodi

**Comment by croneter** [comment]
```
File "C:\Users\Media\AppData\Roaming\Kodi\addons\script.games.rom.collection.browser\resources\lib\gamedatabase.py", line 19, in <lambda>
sqlite.register_adapter(str, lambda s: util.convertToUnicodeString(s))
TypeError: 'NoneType' object is not callable
```
Your Kodi add-on `script.games.rom.collection.browser` (usually standard Kodi!) literally **hijacked** either PlexKodiConnect or - even worse - the standard Kodi library `sqlite` (https://docs.python.org/3/library/sqlite3.html).

My guess is that a rogue Kodi add-on screwed your Kodi. Likely your add-on https://github.com/maloep/romcollectionbrowser

Clean your system. Don't use piracy add-ons.

**Comment by croneter** [comment]
Hmm, `Rom Collection Browser` seems legit. I'm wondering which add-on could have gone rogue

**Comment by louisefindlay23** [comment]
~~Think it was one of the Libertro addons I installed to try to get the native Kodi game system working.~~ My Plex libraries starting syncing again once they were gone though the error message still appears, PKC is working again. 

Turns out it's apparently a Matrix issue with RCB with its skins folder according to the forum. The fixed file link is dead so will try and get a copy. 

Thanks for all your help, croneter. Amazing addon, btw.

**Comment by croneter** [comment]
Could you point me to the thread discussing this? Might be really good to know what's going on, exactly. Thx!!

**Comment by louisefindlay23** [comment]
Sure, https://forum.kodi.tv/showthread.php?tid=70115&pid=3012272#pid3012272 is the message with the issue and a few messages down is a solution.

**Comment by louisefindlay23** [comment]
Just found out it breaks the Netflix plugin too and the dev there went into detail. https://github.com/CastagnaIT/plugin.video.netflix/issues/1061#issuecomment-774470523 
Seems like there's a PR with a potential fix. https://github.com/maloep/romcollectionbrowser/pull/432

**Comment by croneter** [comment]
No worries, thanks a lot for the valuable research!
