### ISSUE TITLE
The dependency on plugin.video.plexkodiconnect.movies version 3.0.0 could not be satisfied.

### ISSUE THREAD

**Issue by jake404** [croneter/PlexKodiConnect#1427]
I have followed your instructions to install PlexKodiConnect on Kodi Matrix but I'm receiving a dependency error.

The dependency on plugin.video.plexkodiconnect.movies version 3.0.0 could not be satisfied.

The log file: https://pastebin.com/7hspFSQJ

**Comment by croneter** [comment]
Kodi is sometimes really annoying with these dependencies 😞 . Did you try to restart Kodi and then to try again to install from the Repo? https://github.com/croneter/PlexKodiConnect/wiki/Install-PKC-from-PKC-Repo

**Comment by jake404** [comment]
Yes, I tried that. Is there a way to install the dependencies manually?

**Comment by croneter** [comment]
Yes, install these ZIP files manually:
* https://github.com/croneter/plugin.video.plexkodiconnect.tvshows/releases/tag/3.0.0
* https://github.com/croneter/plugin.video.plexkodiconnect.movies/releases/tag/3.0.0

**Comment by jake404** [comment]
Installing them manually worked, however now when going into PlexKodiConnect settings and selecting 'Choose Plex Server from a list' it just closes the dialog. If I try the 'Manually enter Plex Media Server address' the same thing happens, the dialog closes. The Plex Media Server is on the same PC.

Here is the log file from when I tried selecting the server: https://pastebin.com/N1290NiE

**Comment by jake404** [comment]
Did you manage to recreate the issue?

**Comment by jake404** [comment]
I resorted to removing the kodi directory and reinstalled PlexKodiConnect and now everything works.
