### ISSUE TITLE
Not yet connected to plex server error 

### ISSUE THREAD

**Issue by Dhop84** [croneter/PlexKodiConnect#143]
I keep getting an error saying I'm not yet connected to plex server

**Comment by croneter** [comment]
How about some log files?

https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by Dhop84** [comment]
Apologies but I'm a complete novice, how would I do that?

**Comment by croneter** [comment]
Follow the instructions in the link above.

Also, you have to provide more details - what did you do exactly? What is working, what is not working?

**Comment by Dhop84** [comment]
OK I'll do that, I don't really no what has happened obviously, on start up plex begins to sync but then stops and says plex sync has crashed and also when I then click on one of my films from the server it says that I'm not yet connected to the server. All my movies and shows are on my seagate personal cloud, which then run in plex, I use the Samsung plex app upstairs and then plexconnect with kodi downstairs, running off the same server

**Comment by croneter** [comment]
I definitely need the Kodi log for that. Please don't forget to enable Debug logging in the PKC settings...

Thanks for the report ;-)

**Comment by croneter** [comment]
To capture the correct log:
1) Enable debug logging in the PKC settings
2) Go to advanced -> Reset Kodi Database (in red), then YES, YES, NO
3) Let Kodi restart
4) Let PKC try to resync and crash
5) Get the log without restarting

**Comment by Dhop84** [comment]
It seams there was something in the build I was using that was interfering with it, as I deleted everything and started from basic and all is working fine now, thank you for your time
