### ISSUE TITLE
Playing any item crashes Kodi and locks up Nvidia Shield

### ISSUE THREAD

**Issue by ArturHartwig** [croneter/PlexKodiConnect#1435]
I am using PKC 3.1.0 with Kodi 19 Matrix on Nvidia Shield Pro. Everything worked fine on Kodi 18.
Whenever starting to play a file the loading animation is visible for approx. 15 seconds after which Kodi closes and a similar overlay to this one ([image](https://cdn.androidcommunity.com/wp-content/uploads/2020/05/Screenshot_20200520-104402-696x392.jpg)) is shown on my homescreen with the item I intended to play and Kodi as the source. I cannot navigate, open, close or return to Kodi or any app anymore at this point and I have to reset my Shield forcefully. I have uninstalled and reinstalled PKC before running this debug session but even with migrated settings from Kodi 18 I had the same results. For the logfile attached below I tried to play a file but the playback wouldnt start after the loading animation was shown twice (which I am used to since Kodi 18 tbh). Afterwards I klicked the file again which resulted in Kodi crashing. This behaviour is reproduceable with a different skin.
[Kodi.log](https://pastebin.com/tKuYS3YS)

**Comment by ArturHartwig** [comment]
Hello,
please find below the debug logs (split in 2 parts due to size) when trying to play a movie instead of a series episode.
([log part 1](https://pastebin.com/3v1Nh2jG))
([log part 2](https://pastebin.com/ejg0Myfm))
This is the image when kodi crashes and I am returned to the homescreen of androidtv ([image](https://imgur.com/a/CluMSFl))

**Comment by croneter** [comment]
PlexKodiConnect's job is to tell Kodi what video to play. Then it's entirely up to Kodi. This is NOT an issue with PKC but with Kodi, sorry. In my experience, Kodi 19 still has many bugs 😢

**Comment by croneter** [comment]
PKC did its job just fine:
```
PLEX.playback_decision: The playurl for DirectPlay is: http://192-168-0-20.XXXXXXXXXXXXXXXXXXXXXX.plex.direct:32400/library/parts/142712/1609170028/file.mp4?Accept=%2A%2F%2A&Connection=keep-alive&Content-Type=application%2Fx-www-form-urlencoded&Accept-Language=en&X-Plex-Device=Linux&X-Plex-Model=4.9.140-tegra-g7ad5124ecf88&X-Plex-Device-Name=Kodi+Shield&X-Plex-Platform=Generic&X-Plex-Platform-Version=1.0.0&X-Plex-Product=PlexKodiConnect&X-Plex-Version=3.1.0&X-Plex-Client-Identifier=b975b08c-8344-44f6-9176-3ddfc8245d03&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=XXXXXXXXXXXXXXXXXXXXXX
```
