### ISSUE TITLE
Kodi19: Stutter and smearing on SD Files

### ISSUE THREAD

**Issue by MrDownstream** [croneter/PlexKodiConnect#1436]
Hello,

i just recently had to reinstall Kodi on my Android TV-Box and therefor PKC as well.
I´ve been using the Box from Kodi 17.x onwards and never had a problem with playback of older SD Files, also i was always using PKC along the way.

Since the reinstall, those files only play with stuttering and smearing of the video.
Strangely enough, when an overlay comes into play (e.g. Menue of Kodi or the Debug Logger) the playback seems to smoothen a bit.
I already tested a bunch of configuration changes on Kodi as well as on Android itself. Nothing works.

I didn´t change anything of the hardware components whatsoever.

Here are two Logs to clarify the situation. In both Log Files there is always the same file played, while changing some of the Settings.

http://paste.kodi.tv/etumuxamez
http://paste.kodi.tv/yeripuyeda

Anyone got an Idea on this?

**Comment by croneter** [comment]
PlexKodiConnect's job is to tell Kodi what video to play. Then it's entirely up to Kodi. This is NOT an issue with PKC but with Kodi, sorry. In my experience, Kodi 19 still has many bugs 😢
