### ISSUE TITLE
Playback error with "Enable Plex trailers" on

### ISSUE THREAD

**Issue by Bergasha** [croneter/PlexKodiConnect#1438]
Hey mate,
When I have "Enable Plex trailers" on  the first movie will play "with intro trailer working" but if I try and play the same movie or even a different one I get playback error and nothing will play until I turn Plex trailers off. error log below and thanks for all your hard work.
https://pastebin.com/QjQ1ApZj

**Comment by croneter** [comment]
Please share a DEBUG log, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by Bergasha** [comment]
That was a lot of tokens lol. Thanks mate
https://pastebin.com/yeTHqq1s

**Comment by Bergasha** [comment]
@croneter  are you able to replicate this issue or is it just my system? Thanks

**Comment by croneter** [comment]
Is this still an issue with Kodi 19.1 and PKC beta 3.1.4?

**Comment by Bergasha** [comment]
Just checked it then and it's still an issue. both updated and same error.

**Comment by croneter** [comment]
Still an issue with PKC 3.3.0?

**Comment by Bergasha** [comment]
> Still an issue with PKC 3.3.0?

Still not working but it looks to be a different error, New  logs below
https://pastebin.com/07VNGHcJ

**Comment by croneter** [comment]
Is this still an issue? Works here...
