### ISSUE TITLE
TV Episodes will not start from beginning when in progress

### ISSUE THREAD

**Issue by blueblazer22x** [croneter/PlexKodiConnect#1439]
## Describe the bug
When a TV episode is in progress, choosing the "play from beginning" option resumes the episode instead.  The same feature seems to work flawlessly with movie titles.

## To Reproduce
1. Find a TV show marked "in progress"
2. Click the title and choose "Play from beginning"

## Expected behavior
Episode should start from beginning.

## You need to attach a KODI LOG FILE!
https://pastebin.com/t0NLnnjN
    
I am aware that I can delete Plex tokens that I accidentially posted by following the [instructions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server)

**Comment by croneter** [comment]
I can't access your log

**Comment by blueblazer22x** [comment]
https://controlc.com/bcf20812

uploaded again here

**Comment by croneter** [comment]
You are using the release candidate version of Kodi, even though the stable version has been out. Make sure you upgrade please!

No support from PKC side as this is probably caused by Kodi, not PKC

**Comment by croneter** [comment]
Excerpt from the log:
```
Starting Kodi (19.0-RC1 (18.9.910)
```

**Comment by blueblazer22x** [comment]
Upgraded to stable Kodi 19.0 and the issue persists.  Could be caused by Kodi like you said.  Thanks for looking.

**Comment by croneter** [comment]
Kindly share another DEBUG log file, I'll have another look

**Comment by blueblazer22x** [comment]
https://controlc.com/b81a7879

**Comment by croneter** [comment]
Kodi 19 is really annoying, many bugs left if you ask me. I cannot replicate your issue 😢 .

I'll rewire playback start-up completely, but that will take some time.

**Comment by Inkblot007** [comment]
I have this same issue on the Nvidia Shield with Kodi 18.  I’m trying to figure out how to get the logs off my device and then I’ll post them.

**Comment by croneter** [comment]
Is this still an issue with Kodi 19.1 and PKC version 3.3.0?

**Comment by Inkblot007** [comment]
I just went in and upgraded to Kodi 19 and the PlexKodiConnect Matrix
stable.  I tested multiple TV shows and movies and can confirm I no longer
have the issue.  Resume works and so does play from the beginning.

Thank you!!
