### ISSUE TITLE
Feature Request: Offline sync

### ISSUE THREAD

**Issue by Woutch** [croneter/PlexKodiConnect#144]
Dear,

Would it be possible to add the offline sync like the android clients? My use case would be that I sync all my favorite movies/series at home and then take my raspberry with me on Holliday and plug it in the TV in the hotel. Or when camping in my own tv. 

It would also be possible to sync over a slow Hotel wifi and play when the episode is synced. So no buffer problems. 

Don't know how hard it would be. But Rasplex does not support this. And a dedicated android tablet has not the storage needed. 

Let me know what you think!

Best regards,
Wouter

**Comment by croneter** [comment]
Now on feathub.com: http://feathub.com/croneter/PlexKodiConnect/+9
