### ISSUE TITLE
Show Collections with Regular Items

### ISSUE THREAD

**Issue by ElementalCrisis** [croneter/PlexKodiConnect#1444]
Hello,

I'm loving PKC so far and was wondering if there are any plans to show collections with regular items? I watch anime and while Plex shows related series in a collection, PKC shows each season separately. I know I can show just collections but I was hoping for an option to show both.

**Comment by croneter** [comment]
Glad you like pkc! What you're looking for is currently impossible from the Kodi side of things, unfortunately.

**Comment by ElementalCrisis** [comment]
Ah that's unfortunate.

However its a small price to pay because at least I can watch without issue unlike when using Plex's player.
