### ISSUE TITLE
New video node: unwatched items

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#145]
I have set up multiple Movie libraries in Plex set up that way for organization and sharing purposes. I can set them all up on the main menu the way I like. Which is great. What I did notice was that when I want to setup a Menu for my Family movies, and use a widget for unwatched movies, There is no option for that through the addon, If I use the one from the skin it jumbles up the different libraries.

**Comment by bartolomesoriano** [comment]
@croneter If the Family movies are in a different path, or all have the same genre, this can be accomplished by setting up a smart playlist and then using this playlist as a widget (depending on the skin).

**Comment by croneter** [comment]
Silly me :-D. Thanks for pointing this out @bartolomesoriano!

See e.g. here: https://www.youtube.com/watch?v=QjWea_PvIkE
