### ISSUE TITLE
Kodi 19 freeze and not responding

### ISSUE THREAD

**Issue by Acme908** [croneter/PlexKodiConnect#1455]
This is happening frequently.

https://pastebin.com/MtaSEr7g

**Comment by Acme908** [comment]
6 days and nothing.

take another log: https://controlc.com/d2d52417

P.S. pastebin size limit is sux

**Comment by croneter** [comment]
Kodi 19 is still unstable. An addon should never be able to crash Kodi. There is nothing suspicious in the Log regarding PlexKodiConnect

Sorry, nothing I can do AT the moment
