### ISSUE TITLE
Kodi freezes and becomes unresponsive

### ISSUE THREAD

**Issue by bokkoman** [croneter/PlexKodiConnect#1458]
Few days ago i freshly installed latest Kodi on my Shield Pro.

I then installed PKC (first time user), and it worked great after done finicking with the settings for direct paths (nfs).
Everything was working fine.

But today i got myself 2 new movies and when i started Kodo it starts syncing with PKC. It immediately freezes at 0%. Kodi still works though, just the syncing is not doing anything.

I tried the reset DB, does nothing.

Anyone else having this problem or knows a solution?

**Comment by croneter** [comment]
Log file?!? See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by bokkoman** [comment]
I'm on it! Gimme a few minutes.

**Comment by bokkoman** [comment]
@croneter 
here is the logfile:
https://paste.ubuntu.com/p/dw3wybs2GD/

Thank you for your patience.

**Comment by croneter** [comment]
Your log file has already been deleted 😢 . Sorry for that. Kindly upload it directly here onto GitHub - simply drag & drop the log file into the comment field.

**Comment by bokkoman** [comment]
It's ok now. I reinstalled from scratch (Kodi cleared data and cache). 
Since then it has been working fine. Thank you for trying to help. If i ever run into a new problem, I'll let ya know.

**Comment by bokkoman** [comment]
Well it started to happen again. This time completely freezing Kodi. Really annoying. I was really happy with this combo of Kodi and Plex, but i guess I'll wait till it works better.

I didn't change anything with my setup. It just randomly did this.

**Comment by croneter** [comment]
That implicates Kodi as the root cause, not PlexKodiConnect. An addon should never be able to crash Kodi. Are you using Kodi 19.1?

**Comment by bokkoman** [comment]
It happened on Kodi 19.0 stable. Then i updated Kodi on hopes it would be gone, but with no prevail.
It kinda is the same issue, it starts scanning and it shows a movie name and it just stops. 

When i looked at my videos sources, there were 4 things names something like Plex Database Hack or something, i removed those sources now and just started the old way. Is it normal that there are 4 of those, or should it be only 1?

**Comment by croneter** [comment]
That's normal.

So does Kodi crash completely or just get stuck? Kindly share a DEBUG log of this issue occuring: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by bokkoman** [comment]
Kodi just gets stuck, can't do anything. I have to force close it.
I don't have the addon installed at the moment. I deleted the addon because i couldn't do anything. Once i started Kodi it freezes in 5s. 
So I'm sorry, but i can't share a log atm. Maybe I'll try the addon again sometime in the near future, once it has been updated some more for Kodi 19.x.
Thanks anyway!

**Comment by croneter** [comment]
A Kodi issue then, if Kodi becomes completely unresponsive 😢

**Comment by croneter** [comment]
I'm still using Kodi 18.6, personally, by the way. Kodi 19 seems a bit unstable still

**Comment by bokkoman** [comment]
> A Kodi issue then, if Kodi becomes completely unresponsive 😢

Well, I'm not sure. Because nothing changed in Kodi, no new addons or updates. The only thing that changed was an update in my library (new episodes). It was updating it to Kodi, i saw the widget add the poster but it was an empty poster (though i already have the show in my library). 
For some reason i think it has something to do with that, the widget and PKC library. Next time I'll try to turn off the widget and see if Kodi stays working.

Is there a something in Kodi 19 that works better than Kodi 18.6? Maybe I'll just fall back as well.

**Comment by RickDB** [comment]
Kodi 19 especially has been pretty buggy for me with multiple addons like Youtube including my own.

Addons can make Kodi freeze / hang resulting in either some watchdog kicks in which restarts Kodi like in the case of CoreELEC or it just never becomes responsive.
Logs show nothing when this happens so it must be some internal API being called and entering a unstable state which it never recovers from, hard to debug this one but if I noticed it in PKC or my own addons again will post the crash dumps and any relevant logs.

**Comment by croneter** [comment]
@RickDB I'm starting to suspect that initializations of Python add-ons might be the cause of this, see e.g. https://github.com/xbmc/xbmc/issues/17311

I just added an additional Python dependency for `arrow` with the latest PKC beta version 3.2.1. Frequently, that init fails now for **script.skin.helper.widgets**! Problem is that for e.g. someone navigation through PKC, inits happen very frequently

**Comment by RickDB** [comment]
@croneter sure looks like the cause.
Wil give the new beta a try and report back 🙂

Noticed similar crashes of the Embuary helper as well which refuses to updated views on watched for instance unless I navigate back and forth.

**Comment by RickDB** [comment]
Smoothing sailing so far and plays nice with Embuary again showing 5-10s continue watching / next up widget updates after playback stopped or during (externally watched on phone).
Tried to stress Kodi out with manual syncing / item updates etc.. but could not make it freeze.

For reference:

**Hardware**: Odroid N2+
**OS**: CoreELEC 19.1
**Kodi**: 19.1
**PKC**: 3.2.1

Tried with existing database first and clean afterwards for comparison both with good results.

**Comment by croneter** [comment]
Beta 3.2.3 might help further. I ditched the Python module `arrow` 'cause Kodi couldn't import it in several Kodi add-ons simultaneously, apparently
