### ISSUE TITLE
Uninstalling?

### ISSUE THREAD

**Issue by njf1525** [croneter/PlexKodiConnect#146]
Hi

I have decided to give up on Plex and so want to uninstall PlexKodiConnect. You say that installing it messes with the Kodi databases so is there anything I need to do to 'repair' those databases when uninstalling?

Thanks.

Norm

**Comment by croneter** [comment]
Yes, uninstall PKC, then shut down Kodi. Then delete the entire kodi database folder in your user data folder (http://kodi.wiki/view/userdata)

**Comment by croneter** [comment]
Ouh and delete the thumbnail folder as well - it contains the cache for the Plex artwork
