### ISSUE TITLE
Is there a way to automatically select a stream?

### ISSUE THREAD

**Issue by Shasoosh** [croneter/PlexKodiConnect#1475]
When having more than one version of the same movie, trying to play it will display a popup in order to select a stream. 
Is there a way to automate this and auto select the high res version (4K instead of 1080p for example)

**Comment by croneter** [comment]
New setting in the upcoming BETA 3.3.1 version: `Pick the first video if several versions are present` in the PKC settings section `Playback`. PKC will pick the first version Plex offers

**Comment by Shasoosh** [comment]
That's great. Thanks!

**Comment by Shasoosh** [comment]
I'm getting this when trying to update to 3.3.2: "The dependency on plugin .video.plexkodiconnect.movies version 3.0.1 could not be satisfied " 

Also, I have two streams, one with HDR and one with DolbyVision - Is the auto pick should select the DV stream on a Dolby Vision device? Couldn't get this to work. HDR is always selected.

**Comment by croneter** [comment]
Update has been fixed

> Also, I have two streams, one with HDR and one with DolbyVision - Is the auto pick should select the DV stream on a Dolby Vision device? Couldn't get this to work. HDR is always selected.

PlexKodiConnect will simply select the "first" stream Plex servers - whatever that is. There's no other logic implemented (and never will be as it'll be way too complicated).
