### ISSUE TITLE
"Mark as watched" & "Mark as unwatched" are not registered by plex

### ISSUE THREAD

**Issue by Shasoosh** [croneter/PlexKodiConnect#1477]
Hey,

I'm experiencing three somewhat related issues, the first one, for some reason marking a movie as watched or unwatched from Kodi will not be triggered in PLEX instantly as opposed to other actions for example changing resume position for a movie. 
I've tried changing my skin to the default one and got the same results.
I've also tried creating a fresh install of Kodi and PKC and got the same results.

From my testing it seems that marking a movie as watched will be updated in PLEX only after another action will be done in Kodi. For example, 
Marking Movie A as watched = Not triggered in PLEX
Marking Movie A as watched and then playing Movie B and stopping it = Move A will be triggered as watched on PLEX and Movie B will be updated in PLEX with the correct resume position.

https://pastebin.com/XcX1bxn0

The second issue, when resume position is changed in plex or in another Kodi machine, the change will reflect only in plex.
so for example if I change movie position from 00:10 to 00:50 in Kodi A
Plex all instantly show position for that Movie at 00:50
Kodi B, inside the movie wall, will still show 00:10. The screen will not refresh it self but if I go out from the movies wall to the home screen and in again to the movies wall, the position will show 00:50. (So Kodi fetches the right position but doesn't display it)

Third issue is the "In progress" widget. It will not update (which I guess is related to issue#2) but even if I'll go out of the movie wall and in again, the movie inside the movie wall will show 00:50, going back to the home screen, the same movie "In progress" widget will still show 00:10.

I haven't supplied logs for the second and third issue as I'm not sure if this is a bug \ limitation or something I'm missing but I'll be happy to do so.

* All issues are reproducible on Windows 10 and Nvidia Shield machines.
* Changing a poster image from plex web will be updated on all Kodi machines instantly (which indicates that Kodi is updated frequently for some attributes) 

Thanks

**Comment by croneter** [comment]
Sorry it took so long...

Second and third issue are limitations. If you'd be watching on another device, Kodi would need to constantly re-render its widgets. 

I cannot replicate your first issue, just checked again. Is it still an issue for you or has a Kodi or PKC update resolved the situation?

**Comment by piejanssens** [comment]
Sorry to interupt here, but solving the second and third issue would be so awesome... 
If this update would only be done on pause/stop it covers 99.999999.. use cases.
This might be a source of inspiration: https://github.com/watchedsyncforkodi/service.watchedsync

**Comment by Shasoosh** [comment]
Hey @croneter, sorry for the late response.

I wasn't able to reproduce the first issue in last versions. 

Thanks.
