### ISSUE TITLE
Kodi crashes when trying to play any file now

### ISSUE THREAD

**Issue by LogiFun** [croneter/PlexKodiConnect#1478]
This is on Kodi 19.1 -- I am no longer able to play anything via plexkodiconnect as Kodi will crash to the Shield desktop. Log is attached. Any help would be greatly appreciated. [kodi.log](https://github.com/croneter/PlexKodiConnect/files/6504942/kodi.log)

Edit to note that I have reset/uninstalled/reinstalled both Kodi 19.1 and PKC and this issue persists.

**Comment by croneter** [comment]
What can I say - Kodi 19 😢

**Comment by croneter** [comment]
Nothing in the logs 😢  I am using 2 Android devices with Kodi 19.1 and they work with PKC just fine. Please also take this up with the Kodi devs!

**Comment by croneter** [comment]
Can you downgrade to Kodi 18? If so, do that please

**Comment by LogiFun** [comment]
Yeah I went ahead and downgraded to 18. All better. Appreciate the efforts with this addon. Thank you.
