### ISSUE TITLE
Nvidia shield 2019 - Cant get Kodi Matrix 19.1 to work with PlexKodiConnect, it used to work with Leia

### ISSUE THREAD

**Issue by user674574** [croneter/PlexKodiConnect#1479]
Sooo,

I used to run kodi Leia with the manual NONE-autoupdating plexkodiconnect for months, it worked great.
After a while kodi updated "to much" and plexkodiconnect got outdated, because i didnt know about the automatic update function.
I have now tried several times to get Kodi Matrix 19.1 (and 19.0) to work with both automatic update PKC and the manual install PKC.

The setup part works out fine, i get to select my server etc, get to select what to sync, and it all syncs.
But i cannot start anything, the loadingwheel keeps going for about 15-20sec and then i get thrown to Shield homescreen, with a "notification" that xxx video is running, but if i press "stop" it stops ofcourse and if i press "open" kodi opens up and then nothing. im running nvidia shield 2019.

- The problem does not exist on "kodi vanilla" with smb share, then it works to play
- Kodi logs says nothing, zero logging
- I tried debug log but nothing
- PLEX-server logs however, does say something
Im running the plex-server on my PC

```
May 21, 2021 16:03:22.989 [16860] ERROR - Error issuing curl_easy_perform(handle): 7
May 21, 2021 16:03:22.989 [16860] WARN - HTTP error requesting GET http://192.168.99.160:8080/MediaRenderer/desc.xml (7, Couldn't connect to server) (Failed to connect to 192.168.99.160 port 8080: Bad access)
May 21, 2021 16:03:22.989 [16860] ERROR - SSDP: Error parsing device schema for http://192.168.99.160:8080/MediaRenderer/desc.xml
May 21, 2021 16:03:52.086 [16860] ERROR - Error issuing curl_easy_perform(handle): 7
```

 `

The part which i dont get, at all, is that 192.168.99.160 is my AVR (sound amplifier) lol, has nothing to do with either plex or kodi, wtf? ^^

```
May 21, 2021 16:34:27.551 [20944] WARN - QueryParser: Invalid field 'checkFiles' found, ignoring.
May 21, 2021 16:34:27.551 [20944] WARN - QueryParser: Invalid field 'skipRefresh' found, ignoring.
May 21, 2021 16:34:27.551 [23968] WARN - QueryParser: Invalid field 'checkFiles' found, ignoring.
May 21, 2021 16:34:27.551 [23968] WARN - QueryParser: Invalid field 'skipRefresh' found, ignoring.
May 21, 2021 16:34:27.568 [23968] WARN - QueryParser: Invalid field 'checkFiles' found, ignoring.
May 21, 2021 16:34:27.568 [23968] WARN - QueryParser: Invalid field 'skipRefresh' found, ignoring.
May 21, 2021 16:34:27.585 [23968] WARN - QueryParser: Invalid field 'checkFiles' found, ignoring.
May 21, 2021 16:34:27.585 [23968] WARN - QueryParser: Invalid field 'skipRefresh' found, ignoring.
May 21, 2021 16:36:19.062 [3964] WARN - [Analytics] Attempting to send unrecognized metric (dlna:settings). Skipping.
May 21, 2021 16:36:19.062 [3964] ERROR - Unable to unlock named mutex 9334581e-7251-4ef7-a8ec-5bfe8e89ff68: 0x120
```

- Plex app for android works fine
- Kodi without PKC works fine (with smb share)
- I tried turning SSL off/on
- I tried enabling/disabling DNLA on plex server
- As far as i know, i didnt change anything in my network or windows firewalll or whatever after it worked with Leia a month ago or so

Im probably missing something thats right infront of me, but im falling short, please help :(

**Comment by croneter** [comment]
Entire debug log file please, see: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

And my advice: stick with Kodi Leia if you can 😞 . There are still many glitches with Kodi Matrix, unfortunately.

**Comment by user674574** [comment]
> 
> 
> Entire debug log file please, see: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug
> 
> And my advice: stick with Kodi Leia if you can 😞 . There are still many glitches with Kodi Matrix, unfortunately.

I will see if i get time to look at some more during weekend, regardless thanks alot for the best plugin hands down, and for quick reply

**Comment by croneter** [comment]
Closing until I'm getting a full DEBUG log...
