### ISSUE TITLE
Feature request: Allow Tv Tunes addon to work with PlexKodiConnect

### ISSUE THREAD

**Issue by Dhop84** [croneter/PlexKodiConnect#149]
I don't no where I need to put this as I have no idea about github so please forgive me if its wrong, I was wondering if there's anyway that you could add the ability to use the TV Tunes addon with this?

**Comment by croneter** [comment]
Have you tried using PKC with direct paths?

**Comment by Dhop84** [comment]
Sorry buddy could you explain what you mean by that (I'm a complete simpleton)

**Comment by Dhop84** [comment]
You mean this don't you? https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths

**Comment by croneter** [comment]
Yes. Switching to direct path should usually make every plugin work

**Comment by Dhop84** [comment]
OK, will that mess with my plex account at all? As I use this addon downstairs and then the same plex account upstairs, so I like them being linked so will changing to direct path affect that?

**Comment by croneter** [comment]
No it will not mess with your Plex account or view count or anything, of course!

**Comment by Dhop84** [comment]
OK I'll give that a try, thanks buddy! Ive only started using github recently so I don't really no how it works fully yet but is there a way so If I get any problems I can ask a question here or there without having to opening up a "issue"?

**Comment by croneter** [comment]
If you want to ask a question and not open an issue/new bug, then use the Plex forum here: https://forums.plex.tv/discussion/210023/plexkodiconnect-let-kodi-talk-to-your-plex#latest

I'm closing this ticket. Come back here to this issue and reopen it if you have Direct Paths enabled and working and the plugin still does not work.
