### ISSUE TITLE
nonstring object error. no atrrribute settimeout 

### ISSUE THREAD

**Issue by craZy-C** [croneter/PlexKodiConnect#1497]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6539858/kodi.log)
As per forum post system updated top 3.2.2 but will not update or resync.
Have tried changing to Estuary Skin from AEON Knox Silvo but same issue. Rebooted shield same issue. All working fine until update received.

**Comment by croneter** [comment]
Darn, it's a threading issue, this one: https://github.com/websocket-client/websocket-client/issues/591

Unfortunately, PKC uses `WebSocketApp()` - the solution ain't simple 😢 

See https://github.com/websocket-client/websocket-client/blob/master/docs/source/threading.rst and e.g. https://github.com/websocket-client/websocket-client/issues/591

**Comment by croneter** [comment]
This might have some clues: https://github.com/websocket-client/websocket-client/issues/580

**Comment by croneter** [comment]
For now: just reboot Kodi and try again, sorry...

**Comment by craZy-C** [comment]
Well that sucks, hopefully a resolution soon. I will try a few more times tonight and if it fails may go back to previous working version

**Comment by craZy-C** [comment]
Update of failure...Attempted multiple restarts both with my skin Aeon Nox and default Estuary and no go. Retstarted Kodi and the Shield each time. Will see if any potential update/fix when I get home. If none will look at trying to downgrade to v 3.2.1 which was working. (when I work out how to do that :) big day)

**Comment by croneter** [comment]
That's really weird. Maybe try to delete the Kodi database files, except addonsXX.db

**Comment by craZy-C** [comment]
Will give that a try tomorrow or Friday, unless you find a fix before hand. Have birthday dinners tonight and tomorrow. Cheers

**Comment by croneter** [comment]
Try beta 3.2.3 please

**Comment by craZy-C** [comment]
V3.2.3  appears to have worked. Converted to default Estuary Skin. Still had the socket error twice and it required about 3 reboots until error went away and is now syncing. Will repost if anything weird happens

**Comment by scotty-g** [comment]
I've upgraded to v3.2.3 yet the issue persists. I've rebooted a dozen times and continue to see the settimeout error

**Comment by craZy-C** [comment]
@scotty-g The processed I used was to make sure I reverted to Estuary, got the error two more times between reboots/ The update then appeared to work but had to restart two more times before everything behaved. No more errors and it is just resyncing fanart.  Have just turned off auto update in case something similar happens again

**Comment by croneter** [comment]
Kindly share a DEBUG log if you're still suffering of issues, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by scotty-g** [comment]
On a Nvidia shield so it's a bit more involved getting the logs. I'll set aside some time this weekend to figure out grabbing logs and post here. 

@croneter separately I'll mention I've enjoyed using the plugin so thanks for the hard work.

**Comment by craZy-C** [comment]
Hey @scotty-g,  I have a shield setup as well. If you have the shield as a network share you can find the log file here (insert drive letter):\Android\data\org.xbmc.kodi\files\.kodi\temp\
Hope this helps you

**Comment by cyberden** [comment]
No log because I reverted to 3.2.1 but I have the same issue on 3.2.3, Kodi M on an Nvidia shield.

Thanks for those who provide logs.

**Comment by croneter** [comment]
I really need another debug log file here, @scotty-g @cyberden @craZy-C . Works on my side, so I don't know yet what to fix...

**Comment by k-meeks** [comment]
[kodi.old.log](https://github.com/croneter/PlexKodiConnect/files/6563732/kodi.old.log)
Here's a debug log from my device. Kodi 19.0 armeabi running on a FireTV Cube Gen1.  Hopefully this helps you croneter.

**Comment by craZy-C** [comment]
Can provide a log file for you later tonight. As mentioned mine is working fine now since V3.2.3

**Comment by craZy-C** [comment]
Here is my current log, everything is working fine, I did find the following though
2021-05-29 17:16:34.114 T:9525    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'settimeout'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 8, in <module>
                                                       service_entry.start()
                                                     File 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/6564229/kodi.log)

**Comment by croneter** [comment]
Kindly try beta 3.2.4

**Comment by k-meeks** [comment]
3.2.4 worked for me. Upgraded without errors, closed Kodi relaunched and scanned my library again. Restarted again and no issues. Thanks croneter!

**Comment by craZy-C** [comment]
Confirmed also V3.21.3 and now v3.2.4 upgraded without errors. The warning in the log file has gone also

**Comment by croneter** [comment]
Great!

**Comment by scotty-g** [comment]
Confirmed as well with v3.2.4. Thanks!
