### ISSUE TITLE
DateAdded in music library is not correct

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#15]
albums seems to be added in revers alphabetic order wich is - if the crawler syncs alphabetically- indeed the same as DateAdded.

I remember this issue from XBMC were I posted the same issue.
They changed code so that at initial scan, the file/folder date is taken into account.
So when you do a first scan, the oldest are added first, the newest files last. In this way you could order by DateAdded (in the beginning, XBMC didn't had this field in their database schema)

This was okay for me. When building a new database, at least the order added was respected.

Maybe you can do also something like this?

I don't know the exact technical details, but maybe you can configure PKC to sync in the same order (oldest files first)
In that way, the KODI database will at least be in the same order

**Comment by badrabbit** [comment]
DateAdded also wont show up in any TV shows related section.

**Comment by croneter** [comment]
Please open a new issue - video and music databases work completely differently in Kodi. Thanks!
