### ISSUE TITLE
First try of playback fails, second try plays immediately

### ISSUE THREAD

**Issue by hanzoh** [croneter/PlexKodiConnect#150]
I have had this issue for a long time but never found the time to post it.

I am running PMS on a local Synology NAS and PKC v1.4.8 on an Intel HTPC with the latest LibreELEC build by Milhouse (Kodi 17 Beta 5).

After a fresh boot, PKC connects just fine to the PMS and reports no errors on screen. I then select any TV show episode or movie and I get the "waiting" spinner. After about 20-30 seconds, it tells me that playback failed. I can then immediately start playback of the same episode again, and it starts instantly.

Here is a normal Kodi log with PKC debugging enabled:
http://sprunge.us/IAXj

And my settings.xml:
http://sprunge.us/ifNL

**Comment by croneter** [comment]
You are using a beta/instable version of Kodi. Chances are high that your issue is caused by Kodi. 

Does this issue only happen once after a reboot? Or every time you want to play a new item?

**Comment by hanzoh** [comment]
Once after a reboot, every subsequent start of any item is working fine.

**Comment by croneter** [comment]
Sorry, but I can't do anything about this. Kodi Krypton issue. You might want to raise this here: http://trac.kodi.tv/
