### ISSUE TITLE
Artist missing

### ISSUE THREAD

**Issue by jeroenterheerdt** [croneter/PlexKodiConnect#1504]
I have been using PlexKodiConnect on OSMC for a while now, but just noticed today one artist is completely missing. They are not in the Artist screen and when I search for (part of) their name it does not show up. The artist name is 'Within Temptation', so nothing special. This happens for all their songs, although I can find the albums and songs by searching for _their_ name specifically. I am also able to play the songs once found. It's just the artist is not showing up, so I cannot play everything by this artist.
Is there anyway I can debug this somehow? Not sure where to start with regards to logs or whatever to see what is causing this.
I looked at the MP3 tags both on the file as well as in Plex and nothing jumps out to me as odd about the songs by this artist - they have the same tags as other MP3s....

**Comment by croneter** [comment]
Did you try to reset the Kodi database in the PKC settings under Advanced?

Is the same artist missing once PKC has resynced?

Then kindly share your Kodi database `MyMusic82.db` - simply upload it here. I might find something.

**Comment by jeroenterheerdt** [comment]
weird - I reset it twice before opening this ticket. This time I rebooted first, reset it then and suddenly the missing artist showed up. Not sure what happened, but it seems OK now. thanks!
