### ISSUE TITLE
Movies and TVShows items are duplicated under Videos

### ISSUE THREAD

**Issue by vores8** [croneter/PlexKodiConnect#151]
After installing PlexKodiConnect, I have 2 copies of Movies item and 2 copies of TVShows items under Videos menu, One pair contains "vanilla" Kodi items from medialibrary, the second pair is brought up by PlexKodiConnect. Although both Movies/TVShows have different menu structures, they both point to the same set of movies(tvshows) in Plex. Is there a way to leave only one subset of Movies/TVShows (I would prefer original ones from Kodi)?

**Comment by croneter** [comment]
Unfortunately no. And it honestly makes zero sense - use Plex only. 

Quote from the readme: 
```
This plugin assumes that you manage all your videos with Plex (and none with Kodi). 
```

**Comment by vores8** [comment]
Sorry, that's not what I mean. Let me explain. In a clean Kodi install top level menu item Videos has 2 chld videonodes: Movies and TVShows, so the top level menu looks like 

```
other top level menu items ... Videos ... other top level menu items
                                  Movies
                                  TVShows
                                   ...
                                  other nodes
```
After installing PKC you get extra pair of videonodes with the same names: Movies and TVShows, so you menu structure looks like
```
other top level menu items ... Videos ... other top level menu items
                                  Movies
                                  TVShows
                                  Movies
                                  TVShows
                                   ...
                                  other nodes
```
Both Movies refer to the same list of movies, provided by PKC, so the new structure looks a bit weird. As I undestand, extra nodes are added in videonodes.py. Do you think it would be good to have an ability to 'hide' these nodes, leaving Kodi menu structure intact? (medialibrary will still be managed solely by PKC)

**Comment by p0werfool** [comment]
This issue also breaks integration with common skins like Amber which uses default Movies, TV Shows nodes. I installed emby just to check if issue is seen there as well but I was unable to reproduce it with emby.

**Comment by croneter** [comment]
@vores8:
Are your Plex libraries named "Movies" and "TVShows"? Then that's the expected behavior. 

@p0werfool:
How would this break integration? Elaborate please

**Comment by croneter** [comment]
Is this solved then?
