### ISSUE TITLE
TV Season Poster Artwork Not Downloading

### ISSUE THREAD

**Issue by aerogems** [croneter/PlexKodiConnect#1511]
## Describe the bug
Poster artwork for TV show seasons not downloading. It has been several days now, and the artwork for panel views listing TV show seasons is still showing just a black box. Have attempted solution in FAQ, as well as rebuilding entire PKC database, and no change

## To Reproduce
Fresh install of Kodi 19.1 and PKC 3.1.x

## Expected behavior
That poster artwork for TV seasons download and display

**Comment by croneter** [comment]
Did you reset the Kodi database in the PKC settings under Advanced?

**Comment by aerogems** [comment]
Yes, I have. That is what I meant by rebuidling the PKC database, sorry if it was unclear.

**Comment by croneter** [comment]
Working just fine here, using Estuary. Please try another skin!

**Comment by aerogems** [comment]
It was indeed a skin issue. Skin author pushed an update and the issue's resolved.
