### ISSUE TITLE
Customize the PLATFORM variable

### ISSUE THREAD

**Issue by Shasoosh** [croneter/PlexKodiConnect#1512]
While using Tautulli & PKC, using different machines will always register them in Tautulli as one "Generic" machine.

https://i.ibb.co/hYQMQvm/11.png

Looks like this is the root cause: https://github.com/croneter/PlexKodiConnect/blob/27202d2ab2bfb7a32cd2d37eda869f0c6ebe2aac/resources/lib/variables.py#L465

Any chance this could be configurable in order to differentiate between machines?

**Comment by croneter** [comment]
Hmmm, look at the code in more detail:
```python
# Plex profile for transcoding and direct streaming
# Uses the empty Generic.xml at Plex Media Server/Resources/Profiles for any
# Playback decisions
PLATFORM = 'Generic'
# Version seems to be irrelevant for the generic platform
PLATFORM_VERSION = '1.0.0'
```
The `PLATFORM` is tied to transcoding (which is a real PITA). Thus I'm not going to make this user-editable, sorry... 😞
