### ISSUE TITLE
Changes to Plex Items Not Triggering PKC Updates

### ISSUE THREAD

**Issue by bradmann** [croneter/PlexKodiConnect#152]
If I change an item via the Plex web interface, for instance, edit a movie poster, I would expect this change to propagate to my Kodi instance running PKC. However, the change doesn't propagate unless I force a refresh or restart Kodi. The only logs I'm seeing look like this:

12:17:16.577 T:123145359237120 WARNING: Create - unsupported protocol(image) in image://https%3A%2F%2F192.168.0.101%3A32400%2Flibrary%2Fmetadata%2F257829%2Fart%2F1480662267%3FX-Plex-TokenXXXXXXXXXXXXXXX/
12:17:21.725 T:123145388756992  NOTICE: PLEX.PlexCompanion -> Client is no longer registered. Plex Companion still running on port 3005

**Comment by croneter** [comment]
Well, I would expect that, too! Unfortunately, the Plex Media Server remains silent for certain types of changes. There is nothing I can do about that. You need to wait until the next incremental sync takes place (defaults to every 60min).

Also see 'Known larger issues' in the readme, or here https://github.com/croneter/PlexKodiConnect

**Comment by croneter** [comment]
Maybe we could file a complaint with Plex ;-)

**Comment by croneter** [comment]
For an incremental sync, PKC downloads a list of all PMS elements. It then checks for certain changes. A full update is only triggered for changed items. It should not be too hard on either your kodi nor PMS resources

**Comment by croneter** [comment]
Ouh, rewind - the change you made does NOT propagate to Kodi at all UNTIL the item is changed again. I think a PMS "daily sync" counts as such
