### ISSUE TITLE
The current Kodi version is not supported by PKC. Please consult the plex forum

### ISSUE THREAD

**Issue by jokerigno** [croneter/PlexKodiConnect#1525]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug

"The current Kodi version is not supported by PKC. Please consult the plex forum" this is the message I see after the installation of the addon in kodi matrix 19.1 running on my nvidia shield.

## To Reproduce
1. Install

## Expected behavior
Be able to use it.

## You need to attach a KODI LOG FILE!

https://paste.ubuntu.com/p/GgQX5DP4dZ/

**Comment by croneter** [comment]
19.1 works just fine here on Windows and Android. Do you have some funky setup? A non-standard Kodi?

Try to shut Kodi down, then delete all the Kodi database files EXCEPT `MyAddons....db` in the [Kodi userdata folder](https://kodi.wiki/view/Userdata).

**Comment by jokerigno** [comment]
I found out. I used to use mariadb so erasing db in kodi folders wasn't enough. Now it works. 

Looking at the log I found this as errror message:

`PLEX.plexgdm: Unable to send registration message
`
Should I be worried?

**Comment by croneter** [comment]
Cool! Nope, nothing to worry
