### ISSUE TITLE
PlexKodiConnect does not connect / does not start to sync

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#1526]
Issue by dlpgraphics

> I just did a clean install LibreElec 9.2.6. I made it through the PKC install, signed in to Plex OK, picked my PMS. I stuck with default settings… nothing happens… doesn’t sync to PMS… just sits there telling me my library is empty. Isn’t it supposed to start a sync with my PMS? If I go into PlexKodiConnect and initiate a manual sync nothing happens. What am I missing?

> Yes I have restarted Kodi multiple times.
> If I go to the Sync Options in PKC Settings and choose Select Plex libraries to sync I get PlexKodiConnect unauthorized for PMS

> Log file: https://paste.kodi.tv/iyamizidey.kodi 2

> I don’t know anyone with another PMS to try. I did the complete reset. Didn’t help.

> I’m running PMS as a docker on an unRAID box. I have 2 Kodi boxes - our main one and a bedroom one. Bedroom one I haven’t looked at for a long time but I just tried it and its giving me PKC error “Plex.tv did not provide us with a valid list of Plex users.”

> The main one I was doing a drive change a few months ago. I backed up Kodi and restored to the new drive. Just the other day we wanted to watch a TV series and realized it was listing it as an older series with the same name. When I looked into it I discovered PCK wasn’t installed. I guess the restore didn’t restore PKC. So I did a new install and that is what I am having trouble with. I just put the original drive back in (which was working when I took it out) and now it is giving me “Plex.tv did not provide us with a valid list of Plex users.”

**Comment by croneter** [comment]
Are you using Plex Home - did you connect your pms to plex.tv? 
```
NOTICE: PLEX.service: No user received
```
Seems like PKC is not receiving any Plex home users, and then doesn't know what to do and shuts down.

**Comment by dlpgraphics** [comment]
I'm not sure what you mean by Plex Home. I just know it as Plex Media Server.
This is the unRaid docker I am using:
https://registry.hub.docker.com/r/binhex/arch-plex/

My PMS is signed in to my Plex.tv account. 
I have a single admin user "dlpgraphics". I have no PIN set,

I do not have a Plex Pass.
My PMS shows both of our Kodi boxes in its list of authorized devices as well as PlexMediaServer and Chrome browser on my PC.

PKC on my Kodi box shows connected to the correct PMS and it is logged in to plex.tv. It lists me as dlpgraphics as admin user.
On reboot it sometimes flashes "Remote communications Failed to start" in the upper right of the screen for a second, the shows  my log in image. I don't understand what else it wants.

**Comment by willmackey2nd** [comment]
Why was this closed without an answer?

If anyone else faces the issue, you need to go to PKC settings -> Plex -> Change logged in Plex home user and re-link the account. Dunno why it occasionally just decides to unlink clients.

**Comment by riverar** [comment]
For folks coming to this thread in 2025 (after resetting passwords due to Plex breach), and the above doesn't work, locate your settings.xml (e.g., `/.kodi/userdata/addon_data/plugin.video.plexkodiconnect/settings.xml`) and empty the `<setting id="plex_status">` element. 

Settings > Plex > Toggle plex.tv login (or Change logged in PLex home user) should now work.
