### ISSUE TITLE
Direct Paths broken if special characters are escaped

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#1529]
### Discussed in https://github.com/croneter/PlexKodiConnect/discussions/1527

<div type='discussions-op-text'>

<sup>Originally posted by **Bartyboy** July  4, 2021</sup>
Hi

Thanks for your great Plugin.
I've trouble in configurating Direct Paths in the Plugin.
I tested several hours and read your explanations carefully and many times.
But I'm failing with all my tests.

My configuration ist the following:
I've a Plexserver on a Synology NAS.
This are my Plex 

This are the nfs shares:
nfs://192.168.0.50/volume1/Movies
nfs://192.168.0.50/volume1/Kids movies
nfs://192.168.0.50/volume1/Series
nfs://192.168.0.50/volume1/Kids series
...

The Plex-librarys are:
/volume1/Movies
/volume1/Kids movies
/volume1/Series
/volume1/kids series
...

I'm not shure, If I should set-up option 1 or option 2.
I think it should be option 1, but I don't know how to share ...Movies and Kids movies as par example "nfs://myNAS/plex-movies/Movies". On my synology NAS I can't configure something on "volume1". The shares with nfs and smb rights are "Movies", "Kids Movies".

But if I test to replace following:
plex path: /volume1/Movies
with: nfs://192.168.0.50/volume1/Movies or nfs://192.168.0.50/volume1
Plexkodiconnect say's, that the files are no longer available.

If I should configure the option 2, I'm stucking on point 5:
"In our example, simply mount smb://myNas/ directly to e.g. /media/myNas and you're done"
How can I mount this in Plex? Or should I configure something on the nas first?

I hope you can help me, I would like the plugin in direct mode. With the plug-in mode it works, but on a firestick with only wlan is direct link the best thing.
</div>

**Comment by croneter** [comment]
> I found the problem now.
If I activate "Escape special characters in the path" (sorry, I don't know the real name, it's on german in my case), it put's a ' in front of the path and kodi means it's an unsupported protocol (/smb)
The path in the log is like this:
/smb://192.168.0.50/Movies
If "Escape special characters in the path" is disabled, I can play the files directly. Now, I have to reorganize my media because it only finds the media in the "smb://192.168.0.50/Movies" and "smb://192.168.0.50/Series" folder. "smb://192.168.0.50/Kids Movies" can't be found.
I will create a shared folder "smb://192.168.0.50/media" and will transfer all subfolders in this shared folder. I think, this should work.

**Comment by croneter** [comment]
I cannot replicate your issue, @Bartyboy, as described in https://github.com/croneter/PlexKodiConnect/discussions/1527#discussioncomment-969247 

Could you help me out? What were your exact settings to get an additional `/` in front of the path so you'll end up with `/smb://...` instead of `smb://`? Simply checking the `Escape special characters ...` doesn't lead to this bug in my case

**Comment by croneter** [comment]
Closing this as I would need more info from @Bartyboy

**Comment by dexterwick** [comment]
Hi, I have the same problem with "/smb://", any solution? I tried the beta version of PKC and don't solve, what you need @croneter ?

**Comment by ordo123** [comment]
@dextersnp did you find any solution to this? I am stuck with /smb:// unsupported protocol error. Even though there is no leading slash in my paths.

**Comment by dextersnp** [comment]
> [@dextersnp](https://github.com/dextersnp) did you find any solution to this? I am stuck with /smb:// unsupported protocol error. Even though there is no leading slash in my paths.

Sorry, I don't use kodi anymore.
