### ISSUE TITLE
Fresh install - Authentication failed

### ISSUE THREAD

**Issue by nerthazrim** [croneter/PlexKodiConnect#153]
Hi guys,

I use SPMC on a Nvidia Shield TV (192.168.0.40) to read content hosted on a NAS and shared by a PlexMediaServer installed in ubuntu (plexmediaserver_1.2.7.2987-1bef33a_amd64.deb 192.168.0.28)

After a fresh reinstallation of my Plex server and the Shield TV, impossible to log in with PKC on SPMC again... I don't know why.

Unfortunately, I don't have access to the PKC logs on the Shield TV (or I didn't find how yet) but here are my steps:
 - Install SPMC via Google Play Store
 - Start the app
 - Install PKC repo
 - Install PKC add-on from PKC repo / Video add-ons
 - Enter the password on plex.tv/pin (the device is properly displayed in my "Devices" section on my Plex account)
 - Select a Plex Server
 -> First fail here, PKC does see the server but cannot connect to it (Error : server does not repond, do you want to select another one?)
 - If I say no and manually configure the IP address of my Plex Server it prompts for the Plex PIN
 - I enter the PIN and it loops on the PIN prompt until Authentication Failed appears.

The Plex applications (Win10 UWP, Shield TV Android App, web browser) work fine so I don't think it's a Plex issue here.

Any help ? :(

Thanks!

**Comment by croneter** [comment]
Need the Kodi logs for this (there are no "PKC" logs). See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Do remember to enable PKC debug logging. Try to catch the steps above in the log, starting with "Select a Plex Server"

**Comment by nerthazrim** [comment]
@croneter I finally managed to access the logs!

http://pastebin.com/Kw4MnYdd

Apparently PKC fails to request http://192.168.0.28:32400/library/onDeck, no idea why :(

**Comment by croneter** [comment]
You got other problems:
```
ERROR: Error loading addon settings to special://profile/addon_data/plugin.video.plexkodiconnect/settings.xml
```
PKC heavily relies on accessing these "normal" Kodi plugin settings, e.g. while trying to connect. Do you use an SD card that's broken?

**Comment by nerthazrim** [comment]
Everything is stored on the Shield internal memory, it doesn't appear to have anything wrong.

I have some configuration content into the file and it seems to be consistent with my current settings.

I just retried and the logs are slightly different
http://pastebin.com/tmQxgFGY

**Comment by croneter** [comment]
You simply can't reach your PMS:
```
15:40:38 T:1400600880  NOTICE: PLEX.downloadutils -> Unknown error connecting to: https://192.168.0.28:32400/library/onDeck
15:40:38 T:1400600880  NOTICE: PLEX.downloadutils -> HTTPSConnectionPool(host='192.168.0.28', port=32400): Read timed out. (read timeout=4)
```
SSL/HTTPS works, otherwise you would not be able to sign in with plex.tv. You can still try and disable SSL on the PMS, see if that helps. 

Can you ping the PMS from your Kodi client? Firewall in the way?

**Comment by nerthazrim** [comment]
As I wrote in the EDITs, I already tried disabling SSL on the PMS. Didn't change anything.

The Plex client is working, on the Shield TV, so yes, it can ping the PMS. No firewall in the way, no.

**Comment by croneter** [comment]
Then please post the entire Kodi log, not only the PKC stuff. Might be something in there

**Comment by croneter** [comment]
Can you connect to your server if you go to video - > add source and then navigate to the servers ip? 

Also when capturing the log, please also include the attempt to use a user's pin

**Comment by nerthazrim** [comment]
Here you go:
http://pastebin.com/JHv8tZjS

This log is me, doing:
 - Starting SPMC
 - Logging to Plex with the pin on the website
 - Selecting plex(local) as autodetected server
 - Going into PKC config screen
 - Entering manually the IP of the server
 - Entering my Plex PIN multiple times until authentication failure (did you login to plex?)

Several questions here: (and yes, I'm sure I've taken the right log file)

1. why aren't all the steps after the fail autodetected-server connection attempts in the log file?!
Kodi seems to simply stop logging after that step...

2. why is PKC trying only in HTTPS?

I cannot add a video source from the PMS, my files are stored on my NAS on a different IP and I used to use the path rewriting to get a DIRECTPLAY. Again, it used to work perfectly. The problem is earlier, I cannot even connect PKC to my PMS here...

**Comment by croneter** [comment]
So HTTPS is deactivated on the PMS? Did you try to deactivate HTTPS in the PKC settings under connection, then reboot Kodi? Does the HTTPS stick after restart?

**Comment by nerthazrim** [comment]
HTTPS is disabled by default in the connection tab. That's what I don't get.

Here is the log file when I try to connect manually with the IP.
Please also note that for this try, I totally disabled remote access and my Plex.tv account from the PMS.

http://pastebin.com/GCXMNtAn

**Comment by croneter** [comment]
Plex.tv probably doesn't have anything to do with your issue! 

Please be more precise - did u try to disable https in the PKC Settings, then restarted kodi? Does the https setting stick?

**Comment by croneter** [comment]
And again - post the entire kodi log!

**Comment by nerthazrim** [comment]
HTTPS is disabled by default **in the PKC settings,** in the connection tab. So yes it is disabled.

I already posted the entire log! 28min ago
http://pastebin.com/JHv8tZjS

**Comment by croneter** [comment]
What if you enable HTTPS on the PMS, also the plex.tv sign-in. Then activate HTTPS in the PKC connection settings. Any luck?

**Comment by croneter** [comment]
Also disable HTTPS certificate check

**Comment by nerthazrim** [comment]
Exactly the same thing :(
http://pastebin.com/tEYxGymF

**Comment by croneter** [comment]
Make sure that https is enabled on the PMS, just in case. Reboot the PMS, best the entire server. 

Triple check that https is enabled, https certificate check is disabled. Reboot the Kodi client. Try again, capturing logs 

Sorry, but I spotted an ssl error in the first log

**Comment by nerthazrim** [comment]
I understand what you're saying, I saw the error too but
1. I don't care about SSL, when I force HTTP it doesn't work either
2. I did what you said the first time, above. I always restarted PMS to check that the config stayed, I first checked with my browser that https://192.168.0.28:32400 was working, I reset Kodi's installation by flushing the data and tried. The result is in the log of the previous link...

When I'll have some time, I'll check that a fresh build of PMS in a VM and a fresh build of Win10 + Kodi + PKC works.

**Comment by nerthazrim** [comment]
Just a thought.
Is it possible than Plex is blocking your plugin authentication on purpose because of this?
https://www.plex.tv/apps/computer/kodi/

I'll let you know as soon as I tested a fresh server/client installation.

**Comment by croneter** [comment]
No, that doesn't make any sense. PKC could easily mask as e.g. Plex Home Theater

**Comment by nerthazrim** [comment]
@croneter good news!

Update of the PMS to plexmediaserver_1.3.2.3112-1751929_amd64.deb and the problem is gone!
It was apparently an issue on Plex's side :)

Sorry about the time you gave and a big thanks for your awesome work :)
