### ISSUE TITLE
Feature Request: Widgets and submenus for Video Nodes.

### ISSUE THREAD

**Issue by rokkhan** [croneter/PlexKodiConnect#154]
I have configured my kodi following this [tutorial](https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins) to create different shortcust for every plex folder but I am unable to configure widgets or submenus for this Video Node. 
If I configure a Movie widget shows every video from my plex.

**Comment by croneter** [comment]
Use video nodes located within one your Plex libraries. So if one of your movie libraries is called "kids", point the widget to e.g. 'Video Library - Movies (with a Plex icon) - Kids - On Deck'

**Comment by rokkhan** [comment]
I already tried to do it but there is no option to point the widget to somewhere. 
Every option I choose from a widget shows full movie database.

**Comment by croneter** [comment]
Use another skin that supports this. I like this one: http://forum.kodi.tv/showthread.php?tid=257970

**Comment by rokkhan** [comment]
Ok, i will try it. I was using Aeon.
