### ISSUE TITLE
Depency on plugin.video.plexkodiconnect.movies version 3.0.1 could not be satisfied

### ISSUE THREAD

**Issue by Wicked0ne** [croneter/PlexKodiConnect#1542]
When I goto update(says to version 3.3.2) the PKC add-on I get the error 

`the depency on plugin.video.plexkodiconnect.movies version 3.0.1 could not be satisfied`

 I've tried restarting kodi and trying again, but I get the same error.

I'm running kodi 19.1 on a firetv stick 4k.

**Comment by xconverge** [comment]
Looks like you forgot to update croneter/binary_repo due to a dep update from last month

**Comment by fullerspectrum** [comment]
Just ran into this on a clean install. Yeah, 3.0.1 isn't on stable.

**Comment by croneter** [comment]
Sorry, forgot to add the two updates for `plugin.video.plexkodiconnect.movies` and `plugin.video.plexkodiconnect.tvshows` to the stable PKC repository. This has been fixed - the update should work now.
