### ISSUE TITLE
PKC constant crashing on adding episodes

### ISSUE THREAD

**Issue by popeye2468** [croneter/PlexKodiConnect#1543]
keeps crashing when adding episodes, i have a log but cant upload log as it says its too big

**Comment by croneter** [comment]
I do need the log. Try to zip the file and split it into several archives. Or does https://pastebin.com/ work?

Do mind the tokens, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by popeye2468** [comment]
https://drive.google.com/file/d/1-I9U9Iq0POLyCobzDrSLNLnk8cs9ow6p/view?usp=sharing

**Comment by croneter** [comment]
I don't have access to your link...

**Comment by popeye2468** [comment]
try now

**Comment by croneter** [comment]
Still a no. It prompts me to sign in

**Comment by popeye2468** [comment]
It's now public so should be viewable

**Comment by croneter** [comment]
You hit gold with that bug 😆 . Thanks for the log!
```
2021-07-21 00:17:20.483 T:560      INFO <general>: PLEX.tvshows: ADD episode plex_id: 826319 - Seconds from Death
2021-07-21 00:17:20.548 T:560     ERROR <general>: PLEX.timing: Received an illegal timestamp from Plex: 1626823040. Using 1970-01-01 12:00:00
                                                   Traceback (most recent call last):
                                                     File "C:\Users\Craig\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\timing.py", line 35, in unix_date_to_kodi
                                                       return strftime('%Y-%m-%d %H:%M:%S', localtime(float(unix_kodi_time)))
                                                   RecursionError: maximum recursion depth exceeded while calling a Python object
```
This bug should not even be supposed to be happening, as errors are getting caught: (extract from respective source code):
```python
def unix_date_to_kodi(unix_kodi_time):
    """
    converts a Unix time stamp (seconds passed sinceJanuary 1 1970) to a
    propper, human-readable time stamp used by Kodi

    Output: Y-m-d h:m:s = 2009-04-05 23:16:04
    """
    try:
        return strftime('%Y-%m-%d %H:%M:%S', localtime(float(unix_kodi_time)))
    except Exception:
        LOG.exception('Received an illegal timestamp from Plex: %s. '
                      'Using 1970-01-01 12:00:00',
                      unix_kodi_time)
        return '1970-01-01 12:00:00'
```
Looks like yet another Python fuck-up by Kodi 19: `RecursionError` is not a child class of `Exception` like it's supposed to. Please try PKC beta version 3.3.4 and see if it helps. 

BUT: the underlying issue is Plex. It delivers an "illegal" timestamp for your item `PLEX.tvshows: ADD episode plex_id: 826319 - Seconds from Death`. Try to re-scan that item within the PMS, see if that helps.

**Comment by croneter** [comment]
OK on second thought it might be an issue with logging and the `LOG.exception`. We will see whether 3.3.4 fixes your issue 😉

**Comment by popeye2468** [comment]
still crashing new log at same link

**Comment by popeye2468** [comment]
Any ideas on this one?

**Comment by croneter** [comment]
This looks really bad, to be honest 😞 . Python throws an exception - where it should not. Could you try 3.4.0 and share another log? Might shed some light on this...

**Comment by popeye2468** [comment]
it completed, did you still want a log?

**Comment by croneter** [comment]
Nice! :-D Nope, but thanks
