### ISSUE TITLE
Change subtitles when casting

### ISSUE THREAD

**Issue by jbonet** [croneter/PlexKodiConnect#155]
Hi, 

I don't know if this is a bug or it isn't supported. 

I use PKC to cast from Plex App to Kodi, but when media has subtitles I'm not able to change them from the Plex App. 

As play, pause etc works, I thought choosing subtitles and audio would too, but it doesn't. 

Is this the intended behavior or is it a bug? 

Thanks

**Comment by croneter** [comment]
That's not yet supported

**Comment by jbonet** [comment]
Okay, thanks for the quick answer!

**Comment by croneter** [comment]
Now on feathub.com: http://feathub.com/croneter/PlexKodiConnect/+8
