### ISSUE TITLE
Stopped connecting after several reboots and can't fix

### ISSUE THREAD

**Issue by wormvortex** [croneter/PlexKodiConnect#1561]
I'm using kodi matrix via LibreELEC. I've installed the newest Plexkodiconnect using the default skin and all works fine. However after some time/reboots Plexkodiconnect comes back with the error message check logs. 

I tried signing out, refreshing, full reset even followed the disable app delete database files and re-enable but it won't work again. As it was a fresh install of kodi I simply refreshing the SD card and started again but the same thing happened again.

I've attached the full log of when it happens if it points to my issue:

https://pastebin.com/2eFeFSRe

**Comment by croneter** [comment]
Thanks for that log! Please try the brand new BETA version 3.3.5

Looks like you screwed up the XML-syntax for one or more of Kodi's xml files. PKC should tell you more

**Comment by wormvortex** [comment]
Perfect. I edited one and must have done it wrong. All working perfectly now.
