### ISSUE TITLE
New issue resuming movies/shows - Kodi DS Player 17.7 

### ISSUE THREAD

**Issue by Deamaed** [croneter/PlexKodiConnect#1571]
Hi there. Long time user of PKC. I'm a particular usage case, as I am using Kodi DS Player 17.7 as I required the external audio filters for proper HDR, as well as to avoid Atmos dropouts. 

In any event, I have recently noticed that the "resume" playback feature no longer appears to work, whether using the Titan skin or the default skin.  This used to work in this version for some time, so I am not sure what has occurred, using the Leia builds from the repository.

I even tried a fresh install on another computer and the same issues arises.  Testing with the current Matrix doesn't seem to have this issue.

I did check the log file (which I've attached), and even though I select resume, for some reason the flags for Plex indicate no resume.

Perhaps there is something I am just missing or have inadvertently changed (or not changes).
I'm not sure what the error regarding unplayable item is about.

[kodi.old.log](https://github.com/croneter/PlexKodiConnect/files/6909165/kodi.old.log)

**Comment by croneter** [comment]
I'm very sorry, but I had to drop support for Kodi 17. Especially due to the fact how complicated playback-startup is and how it's changed over time 😞 . You're seeing the result of this...

You could try to use [PKC direct paths](https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths), that MIGHT work...

**Comment by Deamaed** [comment]
Thank you for replying.  I will and see if I can get direct paths working.

The confusing thing for me is that it was working perfectly for some time.  I have tried downgrading the PKC but it persists, in the event that an autoupdate did this.

Obviously, I haven't updated Kodi itself since its an older version. Perhaps they will eventually fix the Atmos issues and I can migrate to a version that isn't several years old...

**Comment by Deamaed** [comment]
Just an update - getting direct paths to work (by redirecting my local plex server to use network paths vs. drive paths) did seem to resolve this issue, so thank you for this!
