### ISSUE TITLE
     Kodi cannot locate the file /var/media/Leviathan/data/movies/etc... how to remove /data/ from path?

### ISSUE THREAD

**Issue by Suffice** [croneter/PlexKodiConnect#1575]
I'm running the Plex server as well as PlexKodiConnect on a Raspberry Pi running LIbreELEC OS.

I'm trying to get PlexKodiConnect to Direct Path from the drives connected to the Pi. One is mounted to "/var/media/Leviathan/"

I tried changing the path for "Replace Plex MOVIE" with "/var/media/Leviathan/" but it decides to add /data/ after that when trying to sync the database. What's going on here?

Unrelated concern: 
The specified port 443 in the instructions doesn't work for connecting to the repository. 
Unspecifying the port allowed access to the repository.

**Comment by croneter** [comment]
Share a screenshot of your settings please or list them here EXACTLY. Also share an exact path to a movie

**Comment by Suffice** [comment]
![screenshot005](https://user-images.githubusercontent.com/1063102/128064413-fedce106-55f4-448c-99a9-a146be9fbe90.png)
![screenshot004](https://user-images.githubusercontent.com/1063102/128064422-4cb601d1-2694-4588-95d4-535022f4ecd9.png)
![screenshot003](https://user-images.githubusercontent.com/1063102/128064428-5b8ee736-f1a2-42be-a46f-8ef76d431d3f.png)
![screenshot008](https://user-images.githubusercontent.com/1063102/128065973-8ba5d9a3-3d7d-4653-9992-cec81422e39e.png)
If I hit no, it looks like it syncs the rest of the videos in the library just fine, but if I try to play them it says that they don't exist. 

It just occurred to me what the problem may be:
![screenshot009](https://user-images.githubusercontent.com/1063102/128066381-58b98b29-d562-4178-800a-6f03bc3793b9.png)
These are the Plex Media Server container settings.
It looks like it's using the paths on the left column for some reason that I don't fully understand.
