### ISSUE TITLE
OSMC: PKC can't process section (sync error)

### ISSUE THREAD

**Issue by beffy** [croneter/PlexKodiConnect#1578]
I'm getting some sync errors all of a sudden. Specifically, every few seconds the Kodi interface throws a sync error and consequently my logs are filled up with this error message:

> ERROR <general>: PLEX.sync.full_sync: Could not entirely process section {'index': 7, 'name': 'TV Shows', 'section_id': 2, 'section_type': 'show', 'plex_type': 'episode', 'sync_to_kodi': True, 'last_sync': 1628429860}

I tried refreshing the database and even tried reinstalling the PKC plugin but the issue persisted. I've attached a debug log from a fresh restart until the first the error message appears: [DEBUG log](https://github.com/croneter/PlexKodiConnect/files/6951217/kodi_x.log)

**Comment by croneter** [comment]
Please make sure that DEBUG logging is enabled. Then reset the Kodi database again in the PKC settings under Advanced. Let PKC sync again from scratch. Share that log file again here...

**Comment by beffy** [comment]
@croneter: That's exactly the content of the log added in the OP. Do you still want me to re-do it?

**Comment by croneter** [comment]
You have many errors in your log that I can't do anything about:
```
ERROR <general>: Exception ignored in: 
ERROR <general>: <Finalize object, dead>
ERROR <general>: 
ERROR <general>: Traceback (most recent call last):
ERROR <general>:   File "/usr/lib/python3.7/multiprocessing/util.py", line 189, in __call__
ERROR <general>: res = self._callback(*self._args, **self._kwargs)
ERROR <general>: 
ERROR <general>:   File "/usr/lib/python3.7/multiprocessing/pool.py", line 581, in _terminate_pool
ERROR <general>: cls._help_stuff_finish(inqueue, task_handler, len(pool))
ERROR <general>: 
ERROR <general>:   File "/usr/lib/python3.7/multiprocessing/pool.py", line 815, in _help_stuff_finish
ERROR <general>: inqueue.get(block=False)
ERROR <general>: 
ERROR <general>: _queue
ERROR <general>: .
ERROR <general>: Empty
```
This is a vital part of Python that should just work. Have you somehow botched your Python installation? Can you try to re-install Kodi completely from scratch?

**Comment by beffy** [comment]
I tried reinstalling OSMC and I'm getting errors on a fresh install as well. It goes into a loop of constantly trying to sync and then getting 'ERROR in library sync'.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7139386/kodi.log)

**Comment by beffy** [comment]
Nevermind the previous log. Here's one after a database reset which has that 'maximum recursion depth exceeded while calling a Python object' error. You said that error is not something you can do anything about, so do I need to reach out to the OSMC maintainers?
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7145568/kodi.log)

**Comment by croneter** [comment]
Thanks for the logs. Do some of your episodes lie at the root of your file system's so at '/'?

**Comment by beffy** [comment]
Nope, all episodes are in /media/storage/TVSeries/ (or in a folder of that directory)

**Comment by croneter** [comment]
Try the brand new beta version 3.5.6, might help.

Otherwise: your logs show many weird errors. As explained above, I'm thinking of a sketchy Python installation/implementation for your OSMC. This errors really should not pop up and I can't do anything from the PKC side to fix them.

**Comment by beffy** [comment]
I'll try that. One thing though, newest version in the repository on my box is 3.4.6. Any thing I can do to make the newest release available? Or do I just need to be patient?

**Comment by croneter** [comment]
Sorry, typo, that is the latest you're seeing

**Comment by beffy** [comment]
That seems to have fixed the issue. Thanks a lot, croneter!
