### ISSUE TITLE
Home Movies in PKC

### ISSUE THREAD

**Issue by levander051** [croneter/PlexKodiConnect#158]
Is it possible to somehow separate home movies libraries from movie libraries in PKC? I don't want them showing up in movies.

**Comment by croneter** [comment]
https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins

**Comment by levander051** [comment]
Croneter, I'm familiar with that options in Kodi, obviously I wasn't clear: 
From Plex PKC imports seperately TV Shows, Music, Pictures (?), but Home Movies and Movies imports together. I use Plex Collections to organize everything which Kodi imports as Tags and it is very useful but it is unconvenient to have Tags from Home Movies mixed with Movies Tags. Is there a way PKC can separate it as two kinds of library? 
Thanks, I appreciate your work.

**Comment by croneter** [comment]
The video nodes/tages of "Movies" and "Home Movies" should NOT be mixed up. Have a read again of the link I posted above - link your homescreen widgets etc. to the correct PKC video node (so either "Movies" or "Home Movies")

**Comment by levander051** [comment]
Fair enough.
