### ISSUE TITLE
PKC cannot find Plex server anymore and starts setup dialogue

### ISSUE THREAD

**Issue by BerziOnline** [croneter/PlexKodiConnect#1580]
Hi!

all of a sudden PKC shows me the starting dialogue of questions to setup PKC the first time, I have to type in the Plex TV verification code and then PKC says there's no Plex-Server.
But the server is there and works fine. I can connect to it from the same network without any problems.

PKC runs on a NVIDIA Shield Pro and has full network connectivity without any network problems.
I can also connect via the normal plex app from the NVIDIA Shield Pro to the plex server, so the connection and the server cannot be the problem. Just PKC is saying there's no server.
When the PKC setup dialogue is over an empty settings field opens, what looks like a bug, because it's empty and the only useful thing you can do is to close it.

After a restart of Kodi the dialogue comes always again.
I once resetted everything: Deinstallation of PKC, completely data-refresh of Kodi (thanks for the re-setup of my skin :D ) and re-installed PKC new. After that it worked for two days again. But now the same behaviour: Each time I start Kodi the PKC comes up with the start-setup dialogue and after I answered everything it is not able to find the plex server.

At the first time I thought the reason was some broken plugin data, okay. But now I had this break for three times in a few days and I cannot say what leads to it or at least to fix it in a short way. :-/

Edit: 
Maybe one important fact (but I use it this way for years), the plex server is on another vlan than the NVIDIA Shield with the PKC on it. There are no restrictions between the vlans (like I said, the plex app on the same device can connect to the plex server), but maybe PKC needs some kind of broadcast/multicast pakets from the plex server to say it's alive?! (just wanted to give all the information to maybe find out the issue)

**Comment by croneter** [comment]
DEBUG Kodi Log File please, see: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by BerziOnline** [comment]
I'm sorry for letting you ask for the debug log!
https://paste.kodi.tv/ujonebacox
Plex-Server is on another device running with the name "Diskstation" and functional.
The log shows one process like the following:
1. Starting Kodi
2. Directly after start the plex link screen (4 didget code for https://plex.tv/link)
3. Linking is functional and plex screen disappears
4. PKC shows in the top of the screen the message "Plexkodiconnect - Search PMS"
5. Popup appears where I can choose the local server named "Diskstation" (what is correct)
6. Choosing the server starts the setup dialogue questions of PKC
7. After answering each question the buggy empty setting popup of PKC opens - I can just close

That's it. When I close Kodi and start again the whole part runs the same point along again.

**Comment by croneter** [comment]
Hmm, log looks normal to me. You need to answer the installation questions, then you opted to go to the PKC settings. After you're done there, you need to restart Kodi. 

Seems like PKC is not able to safe to its settings file. How does the file `settings.xml` under `userdata/addon_data/plugin.video.plexkodiconnect` (in the [Kodi userdata folder](https://kodi.wiki/view/Userdata)) look like? (mind to replace the tokens!)

**Comment by croneter** [comment]
This tells me that PKC can't safe it's settings:
```
PLEX.clientinfo: Generating a new deviceid
```
Any idea why? Read only file system maybe? Nothing I can do there from the PKC side of things

**Comment by croneter** [comment]
Any news here?

**Comment by BerziOnline** [comment]
> Any news here?

Thank you very much for your help and sorry for the delay. I am able to troubleshoot that further more in the next week. I will update this issue here then.

**Comment by bokkoman** [comment]
I have a similar problem @croneter . Suddenly i couldn't play any more media.
I didn't know why, because i can still access my Plex on localip:32400.

So i did a reset. Now it also can't find any server.
Here is my log.
https://paste.kodi.tv/sabiwinuvu

Hope this helps. I am using the beta channel btw (3.4..0).

**Comment by BerziOnline** [comment]
The issue can be closed, I have to apologize wasting your time.

The problem occured because of a non-compatability between an too old plex-server version of mine and the newest PKC.

My plex-server was not able to be updated anymore, because of an older DSM version on a Synology NAS. (I think because plex stopped supporting older 32 bit versions of plex the day of non-compatibility had to come) 
I invested the last few days to bring up a new server and the problems are gone. I didn't change anything on PKC, so the issue was never made by your plugin. I apologize. The reason why I just thought that PKC was the problem, was because of the buggy behavior of the plugin, which lead to these bugs like "not able to save settings" anymore and things like that. 

Thanks for your support and development here!

**Comment by croneter** [comment]
Glad everything works again! Thanks for reporting back
