### ISSUE TITLE
Videos with higher than ~6kbps bitrates crash kodi with direct play enabled.

### ISSUE THREAD

**Issue by quashtaki** [croneter/PlexKodiConnect#1581]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
Whenever I try to play a video file with over ~6kbps bitrate, Kodi/PlexKodiConnect crashes. This is not the case when playing a lower bitrate file. 

## To Reproduce
Try to play a high bitrate file.

## You need to attach a KODI LOG FILE!
[succesful.log](https://github.com/croneter/PlexKodiConnect/files/6984841/succesful.log)
[unsuccesful.log](https://github.com/croneter/PlexKodiConnect/files/6984842/unsuccesful.log)

**Comment by croneter** [comment]
Nothing to do with PlexKodiConnect, I'm afraid. PKC just tells Kodi which file to play, then it's up to Kodi to do whatever, including playback. Or crashing when it should not. Please take this up with the Kodi team.
