### ISSUE TITLE
willing to donate whatever to get embedded subs working

### ISSUE THREAD

**Issue by king8084** [croneter/PlexKodiConnect#1582]
can the creator state his email ? i wanna discuss this further

**Comment by croneter** [comment]
So what exactly is your issue? PlexKodiConnect tells Kodi what video to play - everything else is entirely up to Kodi, including probably anything around embedded subtitles

**Comment by king8084** [comment]
fix it and i will donate 50$ the same day, i swear, the issue been well established for over a year

https://github.com/croneter/PlexKodiConnect/issues/1191
https://github.com/croneter/PlexKodiConnect/issues/1167

basically, embedded subtitles in mkv wont default in pkc, it will go to NONE, or if you have an external sub of any lang it will go to that, even if its not picked by plex at all

for example, have an episode with embedded english sub, and an external chinese sub...PKC will always pick the chinese sub and change the default setting in plex for that episode to chinese 

pls fix it :(

**Comment by king8084** [comment]
Also,

if you play the video in kodi directly with pkc, it will play the embed subs...if you play it in plex directly, it will play the embed sub...only once PKC interact, it will default to NONE or ANY external sub, but never the embed

**Comment by croneter** [comment]
Should be solved with PKC 3.4.3

**Comment by alazabe** [comment]
Os there any chance to see .strm support?

**Comment by croneter** [comment]
@alazabe I don't think so, as PKC would need to be completely rewired. What exactly is your issue or what do you want to achieve?

**Comment by alazabe** [comment]
> @alazabe I don't think so, as PKC would need to be completely rewired. What exactly is your issue or what do you want to achieve?

I would like to see .strm files because it will not mess with netflix plugin and doing .strm files can be managed through media manger apps to add artwork and trailers and kodi will be stable since it see the files as local

i know it might need rewriting the plugin and if donations will help i am willing to donate 300$
