### ISSUE TITLE
Replace Paths for "Other Videos" Library

### ISSUE THREAD

**Issue by taylormia** [croneter/PlexKodiConnect#1583]
Hi, 
Thanks for this awesome add-on.
I'm on PKC 2.13.2 and Kodi 18.9 on Win 10. Plex is on Docker and my media is on a NFS NAS.
I have video files set up in an "Other Videos" library in Plex but I don't see a way to configure a custom path for this library similar to "Movies" and "TV Shows".
Is there a way to do this that I'm missing or is there a workaround?

https://imgur.com/jQjMNZG

**Comment by croneter** [comment]
You can try this: https://github.com/croneter/PlexKodiConnect/wiki/Option-2-Substitute-Paths-on-the-PMS
