### ISSUE TITLE
UpNext and OnDeck

### ISSUE THREAD

**Issue by eloo** [croneter/PlexKodiConnect#1589]
## Describe the bug
Hi, 

i'm not fully sure if the following behaviour is a bug or just an undocumented limitated but at least its unexpected to me so i would like to ask here. I'm also not sure if this belongs more to the PKC Addon or the Up Next addon.

I'm trying to get some kind of continuesly playback working from my widgets, or especially from the "On Deck" (in German: Aktuell) widget running.
I have disabled the automatic playback feature from kodi as described in the FAQ.
Installed the Up Next Addon and tested it.
So far my episode is near the end i see the expected from the Up Next plugin also with the correct episode as i expect.
But when the episode ends the new is not started automatically.

So i have also tested to start a episode from the season folder and then everything is working as expected. 
For me it so feels like there is something weird happening when i start a episode from the OnDeck widget. 

Maybe someother has also expierenced such a issue or maybe have also found a solution workaround?
Or is it a known limitation? 

## To Reproduce
1. Install PKC and configure it
2. Install Up Next plugin
3. Start any episode (with successor in place) from the OnDeck widget 
4. Watch the episode (or jump to end -1 minute)
5. See the Up Next dialog and wait till the episode is over
6. Expect the new episode to start
7. But it will not start automatically

## Expected behavior
I would expect that the UpNext plugins is working in the OnDeck widget as it is working in the Season folder

## You need to attach a KODI LOG FILE!
Can't see any interesting stuff in the logs. If still needed i can provide them tomorrow.

Thanks

**Comment by croneter** [comment]
This works for me using Kodi Matrix. Is it still an issue for you?

**Comment by croneter** [comment]
If so, please provide a DEBUG log: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by eloo** [comment]
Can confirm that it seems to work a bit better using Kodi Matrix. 
It seems not to be working every time but at i would around 50% of the time its working.

So for me we could close this. 
Maybe you can add a hint in the Readme that it seems to be broken on Leia.

Thanks
