### ISSUE TITLE
Stop playback from library

### ISSUE THREAD

**Issue by mufflon11** [croneter/PlexKodiConnect#1590]
The playback of all my videos randomly stops after a few secounds when im trying to play them from my library
It just display a 100% filled circle

I can play them with the normal plex plugin without issues, the plex web client also plays them so its not a Firewall / broken File issue, ALso tried it on my PC / Laptop / Libreelec raspi4 to ensure its not a PC Problem.

I got the same problem with Composite for kodi when adding them to the library with Osmosis

Heres a Debug log 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7009955/kodi.log)

**Comment by croneter** [comment]
Nothing to do with PlexKodiConnect. PKC just tells Kodi what file to play. I'm seeing this in the log, might help you troubleshoot:
```
2021-08-18 22:02:26.020 T:15448    INFO <general>: CVideoPlayerAudio::Process - stream stalled
2021-08-18 22:02:26.221 T:3380    DEBUG <general>: CDVDVideoCodecFFmpeg::GetPicture - eof hw accel
...
ERROR <general>: ffmpeg[0x21ae6d1e060X]: [matroska,webm] File ended prematurely
...
```
