### ISSUE TITLE
"Could not connect to repository" happens again

### ISSUE THREAD

**Issue by darouwan** [croneter/PlexKodiConnect#1591]
I have installed the latest PKC repository add-on, it show "Could not connect to repository". 

Then I do it again by following this [https://github.com/croneter/PlexKodiConnect/wiki/Update-PKC-Repository](https://github.com/croneter/PlexKodiConnect/wiki/Update-PKC-Repository) , but it still doesn't work. 

Any way to solve it now?

**Comment by croneter** [comment]
How about sharing a DEBUG log file? https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by darouwan** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7032343/kodi.log)

This is my debug log file. Thanks!

**Comment by darouwan** [comment]
I have tested it on Xbox, Android, Windows, and they all have the same message:  "Could not connect to repository". The log file I attached is from Windows Kodi.

**Comment by croneter** [comment]
Well, no idea! I just installed PKC myself this morning and everything worked just fine.

You can install from zip file file, see here: https://github.com/croneter/PlexKodiConnect/wiki/Installation

**Comment by darouwan** [comment]
That's really strange~ If I install pkc  in offline mode, can it update automatically in future?

**Comment by croneter** [comment]
As the wiki states: no
