### ISSUE TITLE
A watched movie or tv show does not get fully watched status in Kodi

### ISSUE THREAD

**Issue by PadelzZ** [croneter/PlexKodiConnect#160]
Im using titan skin in my kodi environment with like the video nodes setup but after i watched like a movie or a episode of a tv show on deck. The watched status gets put on like 7% but on plexpy i see the episode got fully watched, to fix this i always have to use the refresh list in the plexkodiconnect options. Im not sure were the problem is coming from. I recently have resetup up my kodi with the same settings as before and same skin and did not have this problem then.

Hope you can help me figure this out

**Comment by croneter** [comment]
* What Kodi version are you using?
* What does `i always have to use the refresh list in the plexkodiconnect options` mean exactly?
* Switch to the Kodi standard skin. Does your issue persist?

**Comment by PadelzZ** [comment]
What i mean by that is the "Refresh Plex playlists/nodes" option. Using the latest kodi version on nvidia shield android tv. I will try more later today

**Comment by croneter** [comment]
This is a Titan skin problem. Try another skin and see if the issue persists
