### ISSUE TITLE
subtitles

### ISSUE THREAD

**Issue by sarut0bi** [croneter/PlexKodiConnect#161]
Hi,
I think i ve got an issue with subtitles on TV show. Here is my problem:
I have the same TVshow video twice : one with english (original) audio with external local language srt and one with local language audio.
When i play video, local srt is attached to local video OR english video have no available srt :(

**Comment by croneter** [comment]
I don't quite understand, could you please elaborate? 
* Do you have 2 different files for a particular episode?
* Does Plex combine them into one Plex episode? Or do you have 2 Plex entries, one for each file?

You can always use a Kodi subtitle download manager to get more subtitles :-)

**Comment by sarut0bi** [comment]
- Do you have 2 different files for a particular episode?
- Yes

- Does Plex combine them into one Plex episode? 
- No I have 2 Plex entries : one for each file

Here is how dirs are:
SectionA
Tvshow1.mkv
Tvshow1.fr.srt
SectionB
Tvshow1-french.mkv

=> Tvshow1.fr.srt is available for Tvshow1-french.mkv instead of Tvshow1.mkv.

Should it be possible to make it available for both video files (fr & original)? (i know it should be quite difficult to find to which video file srt should be attached because both language are unknown if i remember)

**Comment by croneter** [comment]
So the 2 files are located in different folders on your HD? That makes Zero sense. Does this SRT subtitle work like you expect it to on another Plex client, e.g. Plex for Android?

If you use direct paths:
In principle, Kodi picks up subtitles that are located in the same folder and have the correct file name automatically. No PKC/Plex needed. See http://kodi.wiki/view/subtitles

**Comment by sarut0bi** [comment]
So the 2 files are located in different folders on your HD? 
=> Yes

That makes zero sense
=> Why zero sense? one section dedicated for original language and one for local... 

That makes Zero sense. Does this SRT subtitle work like you expect it to on another Plex client, e.g. Plex for Android?
=>Yes works fine in OpenPHT, plex for android and plex webapp... i don't even understand how subs are attached to another video given release name are different and Tvshow1.fr.srt is not matching Tvshow1-french.mkv name :(

=> I do not use direct path

**Comment by croneter** [comment]
You probably get an additional Kodi subtitle from some plugin - not the one you saved somewhere else.

Did you try a PKC/Kodi database reset? Go to PKC Settings, Advanced, Reset Kodi DB ... (in red). Hit YES, YES and NO. Reboot. 

If that did not help, please use the Plex web interface, navigate to an episode where you see the subtitle of ANOTHER episode that you would not expect to see. Hit the three dots (...) on the left, then Info, then "View XML". Copy paste everything in here.

**Comment by croneter** [comment]
This still an issue?

**Comment by sarut0bi** [comment]
Hi,
Some of my TV shows were wrongly parsed by Plex :)
So it is not a PKC issue :)
Thx for quick response
