### ISSUE TITLE
New version of PKC asks to relink plex, all settings are gone, being asked to setup everything in an endless loop

### ISSUE THREAD

**Issue by Shasoosh** [croneter/PlexKodiConnect#1621]
Opening Kodi showed the "Link your plex" screen, after that I was asked all the questions you get when you first install PKC..
Which is a big pain, resetting all the customize paths etc'.
After completing the process, restarting Kodi showed the same screen and the initial setup.
I had to uninstall PKC in order to stop that loop.

I'm seeing that PKC was auto updated to 2.14.2 so I'm guessing this is what triggered it. (Kodi 18.8)

**Comment by croneter** [comment]
Log? https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Kodi sometimes screws up certain settings. Try to completely remove PKC then start from scratch. See #1489

**Comment by Shasoosh** [comment]
Thanks. Reinstalling PKC solved it.
I didn't save the log. I'll see if I can reproduce it on the next update.

Thanks again for this great addon. I've been using it for months without a glitch.
