### ISSUE TITLE
Solution for Plex RAW photos/pictures that Kodi can't process?

### ISSUE THREAD

**Issue by bradmann** [croneter/PlexKodiConnect#164]
Kodi still seems to struggle with support for RAW photos, but Plex handles them nicely. It would be great if PlexKodiConnect could let me use "Direct Play" for my Movies/TV Shows, and "Direct Stream" for Photos, so Plex can feed them to Kodi.

**Comment by Memesa** [comment]
Just noticed this Feature Request, implemented this in Pull Request https://github.com/croneter/PlexKodiConnect/pull/165. Let's see what @croneter thinks of it.
