### ISSUE TITLE
can u add an option not to syn content

### ISSUE THREAD

**Issue by aniel300** [croneter/PlexKodiConnect#1646]
can u add an option not to sync content, i just want to on the fly access my libraries.

**Comment by croneter** [comment]
No. This would make a complete rewrite of the PKC backend necessary. 

You could choose to NOT sync anything by disabling sync for every single library when navigating to the PKC settings, Sync, `Choose which Plex library to sync`. Then you can still consume everything Plex by navigating to Add-ons -> Video Add-ons -> PlexKodiConnect -> <name of your library>

**Comment by aniel300** [comment]
yep i realized this after posting, thank you anyway and thank you for this amazing project,
