### ISSUE TITLE
Lots of Kodi error popups on clean install

### ISSUE THREAD

**Issue by dobbleg1000** [croneter/PlexKodiConnect#1656]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
A.Plex Kodi connect errors  on startup ( i think this is having issues with on deck)
B.Plex Kodi connect errors on playback start(using direct paths so it works but the error is annoying)
C. Kodi doesnt quit

## To Reproduce
A1. Add on deck as a widget
A2. go to home screen
B1. try to play any content 
C2. Try to quit/shutdown/reboot kodi

## Expected behavior
A:  On deck loads normally
B:  No error on playback
C:  Kodi exits appropriately

## You need to attach a KODI LOG FILE!
A Kodi debug log file is needed that you recorded while you reproduced the bug. **Do clean your log of all Plex tokens (="Plex passwords")!!!** .
1. Activate Kodi's debug logging by going to the Kodi `Settings` -> `System` -> `Logging`. Then toggle the `Enable debug logging` setting.
2. Restart Kodi to start with a "fresh" log file.
3. Reproduce the bug.
4. Follow the [Kodi instructions](http://kodi.wiki/view/Log
_file/Easy) to grab/share the Kodi log file. Usually only `kodi.log` is needed
    * You can [find the log file here](http://kodi.wiki/view/Log_file/Advanced#Location)
5. **Delete all references to any of your Plex tokens** by searching for `X-Plex-Token` and `accesstoken` and replacing the strings just after that!
    * It's easiest if you copy your token, then use Search&Replace for the entire log file
    * You don't want others to have access to your Plex installation....
6. Drop your log file here in this issue. Or use a free pasting-service like https://pastebin.com and include the link to it here
    
I am aware that I can delete Plex tokens that I accidentially posted by following the [instructions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server
)

**Comment by croneter** [comment]
Example error and traceback:
```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
	- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
   Error Type: <class '_queue.Empty'>
   Traceback (most recent call last):
	 File "/home/jake/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 203, in <module>
	   Main()
	 File "/home/jake/.kodi/addons/plugin.video.plexkodiconnect/default.py", line 44, in __init__
	   entrypoint.browse_plex(key=params.get('key'),
	 File "/home/jake/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 527, in browse_plex
	   show_listing(xml, plex_type, section_id, synched, key)
	 File "/home/jake/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/entrypoint.py", line 250, in show_listing
	   all_items = utils.process_method_on_list(widgets.generate_item, all_items)
	 File "/home/jake/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 880, in process_method_on_list
	   ERROR(notify=True)
	 File "/usr/lib/python3.9/multiprocessing/pool.py", line 736, in __exit__
	   self.terminate()
	 File "/usr/lib/python3.9/multiprocessing/pool.py", line 654, in terminate
	   self._terminate()
	 File "/usr/lib/python3.9/multiprocessing/util.py", line 224, in __call__
	   res = self._callback(*self._args, **self._kwargs)
	 File "/usr/lib/python3.9/multiprocessing/pool.py", line 692, in _terminate_pool
	   cls._help_stuff_finish(inqueue, task_handler, len(pool))
	 File "/usr/lib/python3.9/multiprocessing/pool.py", line 947, in _help_stuff_finish
	   inqueue.get(block=False)
   _queue.Empty
```
I'm afraid to tell you that this is a Kodi issue. Kodi 19 with Python 3 (where it was Python 2 before) is still struggling with Python issues, e.g. with the `multiprocessing` module. This causes bugs like you experience. I can't do anything from the PlexKodiConnect-side, unfortunately. 

I'd stick to Kodi 18.9 if I were you for now...

**Comment by dobbleg1000** [comment]
It is working now. Thanks. For the assistance. hopefully the python 3 issues get worked out
