### ISSUE TITLE
How to completely uninstall / remove from Kodi

### ISSUE THREAD

**Issue by gitguys** [croneter/PlexKodiConnect#166]
I've searched around and haven't found any uninstall directions.  If I've missed them, please direct me towards them.

I went through Kodi and found multiple PlexKodiConnect addons (I think 3 total?), deleted them, restarted Kodi and it seems to be removed for the most part.

However, there's music that still shows up.  Also, in TV SHOWS, it shows a dialog about 'Recently added episodes' when I select it on the main homepage that wasn't there before adding PKC.  I refreshed the library of videos, etc. and it seemed to at least clear those from VIDEOS , but refreshing the MUSIC library doesn't seem to work.

I don't want to reinstall Kodi because I really do NOT want to lose my current Kodi settings as it would take me a long time to reset them.  Is there some pieces of PKC I'm missing?  Really wish there was some instructions for this.

**Comment by croneter** [comment]
Good point. Here is the manual: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Uninstall-PlexKodiConnect

**Comment by gitguys** [comment]
I followed the instructions and deleted all the files, but it did cause some errors the next time I launched Kodi.

![screen shot 2016-12-22 at 10 49 06 am](https://cloud.githubusercontent.com/assets/11050768/21435051/bbdfd34c-c834-11e6-8d7a-259091ff7aa2.png)


I went ahead and reinstalled Kodi over top my old install while keeping my old setting intact to fix the problems but I now still get the same error.  Kodi seems broken now.

**Comment by gitguys** [comment]
I perhaps you should warn users on the main GitHub page that removal of your PKC may hose the entire Kodi install.  At this point, unless you revise the instructions or create your own uninstaller that doesn't cause these errors, it would appear I'm going to have to completely wipe out Kodi and all my settings to completely remove PKC without running a hobbled Kodi afterwards.

**Comment by croneter** [comment]
Ouh, not good. Thanks for letting me know. I'll test the uninstallation procedures further. I'm thinking that sources.xml might be causing issues.
