### ISSUE TITLE
SPMC Empty Source

### ISSUE THREAD

**Issue by darkcircuit** [croneter/PlexKodiConnect#168]
PlexKodiConnect appears to correctly connect to Plex, however when it has finished scanning and I navigate to any libraries in the menu (Movies, TV Shows, etc) they are blank. Did a bit more digging and I found that although the library sources are present ('Plex') when I edit the source I find that the smb path is just 'smb://' which I believe explains why the libraries are empty.

I tried multiple solutions (switching between Addon Paths &  Direct Paths, restarting the device, rebuilding database, resetting everything and starting again) and in all cases PlexKodiConnect seemed to find my media ok, but when it came to telling Kodi where to find them the result was the same (empty source path). I've attached my [SPMC.log](http://paste.ubuntu.com/23667919/) and I sincerely hope I am not wasting your time with a configuration issue.

**Comment by croneter** [comment]
Try restarting kodi. Try to navigate to video, add-ons, PlexKodiConnect, refresh Plex Playlist and nodes (or something along the lines). 

If that doesn't work, please share your sources.xml from the kodi user data folder.

**Comment by darkcircuit** [comment]
Thanks for the quick reply. I restarted kodi so many times last night with the same result, here is my [sources.xml](http://paste.ubuntu.com/23668018/)

**Comment by croneter** [comment]
I don't see anything in the logs nor the sources.xml, darn. Could you please reboot Kodi, then navigate to Videos -> Video addons -> PlexKodiConnect -> Movies. See anything there? How about in the "Watch later" section? 

Please share the log of you navigating there.

**Comment by darkcircuit** [comment]
Good news! I got to the bottom of the issue last night, my own fault entirely as I hadn't thought about the problem logically until then. Basically I still had in-place the AdvancedSettings.xml which would force Kodi to use a remote MySQL instance for it's DB; it seems PlexKodiConnect was successfully writing the required entries to the local DB, and Kodi was ignoring them.

**Comment by croneter** [comment]
Good to hear, many thanks for reporting back! One headache less ;-)
