### ISSUE TITLE
No longer compatible with python 3.6

### ISSUE THREAD

**Issue by KennyS** [croneter/PlexKodiConnect#1688]
## Help yourself
Tried first.

## Describe the bug

plexkodiconnect does not sync due to a startup crash, starting at release 3.5.8
Error Contents: cannot import name 'ThreadingHTTPServer'

I only took a quick look but its probably introduced in this commit:
https://github.com/croneter/PlexKodiConnect/pull/1686/commits/f3754fa2e323fc3b6582c839f1fa46da9fbb3939

## To Reproduce
Install on Ubuntu 18.04 with kodi matrix or any linux system where python3.6 is the system default for python3

## Expected behavior
No exception on startup

## You need to attach a KODI LOG FILE!
2021-10-31 16:59:05.246 T:145     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'ThreadingHTTPServer'
                                                   Traceback (most recent call last):
                                                     File "/cfgfs/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 4, in <module>
                                                       from resources.lib import service_entry
                                                     File "/cfgfs/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/service_entry.py", line 13, in <module>
                                                       from . import plex_companion
                                                     File "/cfgfs/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plex_companion.py", line 12, in <module>
                                                       from .plexbmchelper import listener, plexgdm, subscribers, httppersist
                                                     File "/cfgfs/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plexbmchelper/listener.py", line 8, in <module>
                                                       from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler
                                                   ImportError: cannot import name 'ThreadingHTTPServer'
                                                   -->End of Python script error report<--

**Comment by croneter** [comment]
Python 3.10 is currently out. Most people use Python 3.8 or larger. Why should I make sure that PKC remains compatible with Python 3.6?

**Comment by zumrazz** [comment]
I dont know anything about coding etc.
Im using Kodi on my QNAP NAS.
Worked without any Problems until yesterday as i was updating Kodi to 19.3 and got the exact same error like above.
PLEX itself runs without problems. 
If you need more Informations let me know.

**Comment by croneter** [comment]
Can you update your Python? 3.6 is rather old, indeed

**Comment by KennyS** [comment]
Personally I took this as the hint to upgrade to ubuntu 20.04 and now everything is fine. I figured you might want to know in case it wasn't intentional.

FYI, I already had a newer version of python installed, however kodi on ubuntu seems to embed the system version which for ubuntu 18.04 is python 3.6. Changing the python3 alias before installing kodi works but breaks some system utilities like apt.

**Comment by zumrazz** [comment]
I switched back to PKC 3.5.5 and it works again. Im not sure how to update the QNAPs Python to V 3.8+

**Comment by croneter** [comment]
Please try PKC beta version 3.5.9

**Comment by zumrazz** [comment]
Working like a charm. Thanks @croneter
