### ISSUE TITLE
PKC show error in kodi for xbox series x 

### ISSUE THREAD

**Issue by zhhuan** [croneter/PlexKodiConnect#1689]
1.I installed the PKC in xsx's kodi, after the installation is finished.  ( PKC addon is installed in kodi successfully)
2.addon->click PKC , show error
3.addon->PKC settings->click 'choose the Plex server list',  kodi shows the error. 
4.No matter what I do to choose Plex server, PKC always show errror.

PS: I installed the PKC in PC's kodi, it works well, the Plex server is easily found, the resource is also synced up .

xsx kodi's version: 19.3

sorry for that I can't post debug log here, because my log addon also occurs error when click run

**Comment by croneter** [comment]
I need a log file, otherwise I can't help you.

If even the Kodi log add-on is showing errors, there's something really wrong with your Kodi. And NOT PKC...

**Comment by zhhuan** [comment]
yes, you're right. I just found that kodi team reported the issue in 19.3 version, it's caused by the xbox kodi issue.
