### ISSUE TITLE
Users should be warned PKC may damage Kodi install at this point.

### ISSUE THREAD

**Issue by gitguys** [croneter/PlexKodiConnect#169]
Please see my comments here:

https://github.com/croneter/PlexKodiConnect/issues/166

Here's a rundown of problems after following the uninstall directions provided here:
https://github.com/croneter/PlexKodiConnect/wiki/How-to-Uninstall-PlexKodiConnect

I followed the Windows instructions and deleted all the files, but it did cause some errors the next time I launched Kodi.

![screen shot 2016-12-22 at 10 49 06 am](https://cloud.githubusercontent.com/assets/11050768/21435051/bbdfd34c-c834-11e6-8d7a-259091ff7aa2.png)

I went ahead and reinstalled Kodi over top my old install while keeping my old settings intact to fix the problems but I now still get the same error including other errors that say

"**:URL error: Unable to connect to server**"  and "**unable to connect to host**"

So.. I restored all the items from the trash bin and allowed the system to overwrite or merge contents of folders to put everything back.  **The errors are now gone.**

So, at least in Windows, it would seem the uninstall instructions are damaging something, somewhere and even installing Kodi over top the old install doesn't fix the issue.  So, I'm back to where I started where PKC isn't fully uninstalled.

I did go back and started to remove items section by section per your instructions.  I only got as far as your **Database** instructions before all the errors I mentioned above came back again.

------------------------------

Perhaps you should warn users on the main GitHub page that removal of your PKC may hose the entire Kodi install. At this point, unless you revise the instructions or create your own uninstaller that doesn't cause these errors, it would appear I'm going to have to completely wipe out Kodi and all my settings to completely remove PKC without running a hobbled Kodi afterwards.

Really wish I knew what I was getting into when I installed PKC in the first place.

**Comment by croneter** [comment]
Seems a bit excessive. Too bad you did not check back in when the uninstall instructions did not work. Have you tried deleting the sources.xml or is it too late for that?

**Comment by gitguys** [comment]
I'll try removing sources.xml and report back.  Unfortunately, I'm working on other things right now.
