### ISSUE TITLE
PKC not showing as a casting target after latest beta

### ISSUE THREAD

**Issue by MrDemous** [croneter/PlexKodiConnect#1693]
PKC is not showing as a casting target from the Android app on the latest 3.5.9 beta

**Comment by Wally73** [comment]
Neither from the windows 10 app

**Comment by croneter** [comment]
You guys using a Plex Media Server running within a Docker container, by any chance?

Looks like Plex' old way of doing Plex Companion is more robust 😢

**Comment by Wally73** [comment]
> You guys using a Plex Media Server running within a Docker container, by any chance?

No my pms (1.24.5.5173) runs normally on windows 10 (21H1,19043.1320)
PKC runs on CoreElec 19.3

**Comment by croneter** [comment]
Could you please enable Debug logging for your PMS, then turn on Kodi and PKC, then share your PMS log file?

**Comment by Wally73** [comment]
After rebooting both my windows box as my coreelec box, PKC is back in android app for casting, 

![androidapp](https://user-images.githubusercontent.com/2582289/140616555-1e595b2e-feb5-437e-b043-f5acbb7cd3ae.jpg)
its still missing though in PlexAMP 
![plexamp](https://user-images.githubusercontent.com/2582289/140616558-34998e9e-d2bd-41f8-9817-d25acae1f7b2.jpg)

**Comment by MrDemous** [comment]
It's still not working for me after rebooting my server and Libreelec.

Here are the logs

[Plex Media Server.log](https://github.com/croneter/PlexKodiConnect/files/7491275/Plex.Media.Server.log)

**Comment by croneter** [comment]
Thanks for the log, @MrDemous . Theoretically, PKC should be available as a casting target. Excerpt from your log file:
```
DEBUG - Request: [127.0.0.1:51520 (Loopback)] GET /servers (6 live) GZIP Signed-in Token (Demous) / Accept-Encoding => gzip / Connection => close / Host => 127.0.0.1:32400 / User-Agent => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.74.9 (KHTML, like Gecko) Version/7.0.2 Safari/537.74.9 / X-Plex-Token => xxxxxxxxxxxxxxxxxxxx438a-a84d-f0de1d891882
DEBUG - HTTP requesting GET https://plex.tv/api/v2/features?X-Plex-Token=xxxxxxxxxxxxxxxxxxxx
DEBUG - Request: [192.168.1.17:49828 (Subnet)] GET /player/proxy/poll?timeout=1&deviceClass=pc&protocolCapabilities=timeline%2Cplayback%2Cnavigation%2Cmirror%2Cplayqueues&protocolVersion=3 (6 live) TLS Signed-in Token (Demous) / Accept-Encoding => identity / Content-Type => text/xml;charset=utf-8 / Host => 192-168-1-202.95445814b4d44997ada6f358d7e3b78f.plex.direct:32400 / User-Agent => python-urllib3/1.26.4 / X-Plex-Client-Identifier => f41fe351-4fe8-4889-9d5f-59ae0366ab10 / X-Plex-Device-Name => Kodi LibreELEC / X-Plex-Platform => Kodi / X-Plex-Platform-Version => 19.3 (19.3.0) Git:19.3-Matrix / X-Plex-Product => PlexKodiConnect / X-Plex-Token => xxxxxxxxxxxxxxxxxxxx / X-Plex-Version => 3.5.10
DEBUG - Network change for advertiser.
DEBUG - NetworkService: Setting up multicast listener on 0.0.0.0:32410
DEBUG - Network change for advertiser.
DEBUG - NetworkService: Setting up multicast listener on 0.0.0.0:32412
DEBUG - NetworkService: Network change for browser (polled=0), closing 0 browse sockets.
DEBUG - NetworkService: Setting up multicast listener on 0.0.0.0:32413
DEBUG - NetworkService: Browsing on interface 192.168.1.202 on broadcast address 192.168.1.255 (index: 0)
DEBUG - NetworkService: Network change for browser (polled=1), closing 0 browse sockets.
DEBUG - NetworkService: Browsing on interface 192.168.1.202 on broadcast address 192.168.1.255 (index: 0)
DEBUG - NetworkService: Network change for browser (polled=0), closing 0 browse sockets.
DEBUG - NetworkService: Setting up multicast listener on 0.0.0.0:1901
DEBUG - NetworkService: Browsing on interface 192.168.1.202 on broadcast address 239.255.255.250 (index: 0)
DEBUG - [CompanionProxy] registered new player: f41fe351-4fe8-4889-9d5f-59ae0366ab10 (192.168.1.17)
```
I'm in contact with Plex, trying to fix this.

**Comment by MrDemous** [comment]
I can cast from the web app just fine, I just can't cast from the android app. PKC doesn't show up as a target device from the android app.

**Comment by croneter** [comment]
Plex Companion sucks...

Please try the brand new beta version 3.5.15

**Comment by MrDemous** [comment]
Working great on the latest beta. Thanks @croneter
