### ISSUE TITLE
Noticed it again this morning. All tv shows are empty. Here's the latest log since I've noticed it.

### ISSUE THREAD

**Issue by wormvortex** [croneter/PlexKodiConnect#1697]
Noticed it again this morning. All tv shows are empty. Here's the latest log since I've noticed it.

https://paste.kodi.tv/ecedexotug.kodi

_Originally posted by @wormvortex in https://github.com/croneter/PlexKodiConnect/issues/1350#issuecomment-955976035_

**Comment by croneter** [comment]
Completely unnecessary duplicate of #1350

**Comment by wormvortex** [comment]
Apologies! I didn't realise that reference in new issue meant it created a new post. Thought it was just marking that the issue is still present.

**Comment by croneter** [comment]
No worries 😉

**Comment by croneter** [comment]
Think I might've found something, see #1350
