### ISSUE TITLE
Works well, but every video starts with 3 trailers...

### ISSUE THREAD

**Issue by sebmaynard** [croneter/PlexKodiConnect#17]
Everytime I try and play something from my Plex, instead of playing what I've asked it to, it plays 3 random trailers first (from other items in my library)

I can't figure out how to disable this, and I don't have the Video Extras plugin installed...

Thanks, great plugin otherwise!

**Comment by croneter** [comment]
Disable trailers in the [PKC settings under playback](https://github.com/croneter/PlexKodiConnect/wiki/PKC-settings#playback)

**Comment by sebmaynard** [comment]
Ok, now I feel stupid. Thanks!
