### ISSUE TITLE
Tags updating...

### ISSUE THREAD

**Issue by levander051** [croneter/PlexKodiConnect#170]
If I add new tag or change existing tag PKC is still showing old tags that don't exist anymore. It also happens to genres. I tried cleaning bundles but they are still there after restarts and rescanning the library... anything I can do to fix this?

**Comment by croneter** [comment]
That's one of the things the PMS doesn't tell that it changed. Fix it by resetting the kodi db - go to the PKC Settings, advanced, Reset the Kodi database (in red)

**Comment by levander051** [comment]
That's what I was afraid of that you will tell me... I did that once and I lost all Super Favorites linked actors because actor IDs keep changing when PKC is reset. I know Super Favorites are not your issue but I would love to keep actors and directors organized and it is the only way I know.

**Comment by croneter** [comment]
By the way - it's not a good idea to rely on some "manual" settings like your super favorites on the kodi side. It's only a matter of time until you will have to reset the kodi database because of a PKC update...

**Comment by levander051** [comment]
> No idea what you mean with the second part

Plex Collections are recognized as Tags in PKC, but also PKC imports it as Sets, I actually don't need Sets but since its there and it is all mess (because one movie can belong to only one Set) I can select Set in Kodi and in context menu I can choose delete and delete it. The Set is not shown anymore and at the same time Tags are not affected by this. This way I can leave only Sets that are actually tagged as Set in Plax Collection. I also have an option to delete Tag the same way in context menu (I tried this to avoid resetting PKC) but nothing happens. As I said I don't care much about Sets but since its there I don't want it mixed up. 

> By the way - it's not a good idea to rely on some "manual" settings like your super favorites on the kodi side. It's only a matter of time until you will have to reset the kodi database because of a PKC update...

I totally agree.
