### ISSUE TITLE
Strip sensitive information from kodi logs

### ISSUE THREAD

**Issue by piejanssens** [croneter/PlexKodiConnect#1700]
How do I find the token (what's the surrounding format) to delete it from the logs?
If it's still required to strip it, wouldn't it be better to that PKC strips the token from being logged altogether?

**Comment by dobbleg1000** [comment]
I found its easiest to just open the file in the text editor of your choice CTRL+F "Token" and replace the accompanying token with REMOVED. Also if you open a New issue(at least in the web browser) and choose Bug Report there are some example formats to look for.
https://github.com/croneter/PlexKodiConnect/issues/new?assignees=&labels=&template=bug_report.md&title=
![image](https://user-images.githubusercontent.com/11370810/140859404-2e25c877-8cd2-4f1b-8d56-e05b0fdc49e7.png)

**Comment by piejanssens** [comment]
Then let this be a request to obfuscate the token from the logs:
- Protect PKC users from leaking their token by accident
- Easier for the end user to just submit the logs as-is (easier instructions = greater chance to receive good debug logs)
- Allows end users to use the official [Logfile Uploader](https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader) add-on or other built in solutions such as the [log uploader that is shipped with OSMC](https://osmc.tv/wiki/general/how-to-submit-a-useful-support-request/#:~:text=uploaded%20with%20ease%20via%20My%20OSMC)

**Comment by croneter** [comment]
Yes, it's still necessary to follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug when posting a Kodi log on the internet.

No, it's technically impossible for PKC to prevent all tokens from showing up in the log file: the token is attached to both video files and picture metadata in order to allow Kodi access to the PMS.
