### ISSUE TITLE
Cannot Skip intro

### ISSUE THREAD

**Issue by dobbleg1000** [croneter/PlexKodiConnect#1701]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did not try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
Skip intro shows but cannot accept or exit it. It intercepts most key presses. Only way out of playback is stop or use yatse to move out. remote cant get out.

## To Reproduce
1. Play a show until the intro starts
2. attempt to accept skip intro with remote/xbox controller/yatse

## Expected behavior
Video moves to after the intro or can close the prompt.

## You need to attach a KODI LOG FILE!
A Kodi debug log file is needed that you recorded while you reproduced the bug. **Do clean your log of all Plex tokens (="Plex passwords")!!!** .
1. Activate Kodi's debug logging by going to the Kodi `Settings` -> `System` -> `Logging`. Then toggle the `Enable debug logging` setting.
2. Restart Kodi to start with a "fresh" log file.
3. Reproduce the bug.
4. Follow the [Kodi instructions](http://kodi.wiki/view/Log_file/Easy) to grab/share the Kodi log file. Usually only `kodi.log` is needed
    * You can [find the log file here](http://kodi.wiki/view/Log_file/Advanced#Location)
5. **Delete all references to any of your Plex tokens** by searching for `X-Plex-Token` and `accesstoken` and replacing the strings just after that!
    * It's easiest if you copy your token, then use Search&Replace for the entire log file
    * You don't want others to have access to your Plex installation....
6. Drop your log file here in this issue. Or use a free pasting-service like https://pastebin.com and include the link to it here
   
I am aware that I can delete Plex tokens that I accidentially posted by following the [instructions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server)

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7501815/kodi.log)

**Comment by dobbleg1000** [comment]
I am on the latest version of Kodi (19.3) and using PKC Beta 3.5.11

**Comment by croneter** [comment]
You need to push the Select button or enter on the keyboard. Everyone else managed 😆

**Comment by dobbleg1000** [comment]
It worked until recently and the log indicated it was "Select" 2021-11-08 19:03:31.753 T:1651    DEBUG <general>: HandleKey: 11 (0x0b, obc244) pressed, action is Select

**Comment by dobbleg1000** [comment]
It can't be escaped with

**Comment by kesm** [comment]
Same problem here, works before last version

**Comment by croneter** [comment]
Try the brand-new beta version 3.5.12, should be fixed now.

**Comment by dobbleg1000** [comment]
Tested and  it does work

**Comment by dobbleg1000** [comment]
Thanks a bunch
