### ISSUE TITLE
Force transcode audio

### ISSUE THREAD

**Issue by wormvortex** [croneter/PlexKodiConnect#1707]
Is there a way to force transcode audio. For some reason any 4K film with true HD audio file will crash Kodi. Obviously this is not a plexkodiconnect issue but some files I have only have a true HD stream so I can't simply play something else.

Can I force Plex/plexkodiconnect to transcode any true HD audio file to AAC or another format? I'm not bothered about loss in quality etc...

**Comment by croneter** [comment]
No, you can only transcode both video and audio. Audio only is impossible. Simply use the Kodi context menu, then 'force transcode'
