### ISSUE TITLE
Context Menu[Req]

### ISSUE THREAD

**Issue by Kuro07** [croneter/PlexKodiConnect#172]
Hi there,

Thanks for the awesome plugin. I was able to make mx player work as an external player because of this plugin. It has been a great addition to my kodi setup however would it be possible for you to add an option to make plexkodiconnect as the default player and then it launches mx player(or any other player kinda like what the playercorefactory.xml does) as the default player? You may be wondering why I am using mx player.  That is because it plays my anime media better compared to running the in built player.

Happy New Year!

**Comment by croneter** [comment]
Happy new year!

This will be very low priority

**Comment by Kuro07** [comment]
Thank you! An alternative would be to add "Start Playback using PMS" on the other most Context Menu instead of me having to keep going to plex options to be able to launch it.

**Comment by croneter** [comment]
Now on feathub.com: http://feathub.com/croneter/PlexKodiConnect/+6
