### ISSUE TITLE
plex companion not showing up in any plex casting menu

### ISSUE THREAD

**Issue by itsj4y** [croneter/PlexKodiConnect#173]
here are the logs
[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/680052/kodi.txt)

**Comment by croneter** [comment]
Plex Companion seems to be running fine, using port 3005. Do you have a firewall blocking that?

Try changing the Plex companion port in the PKC Settings

**Comment by itsj4y** [comment]
that was the first thing i tried however port 3005 is just fine as i can see my plex media player but can't see pkc. i even just completely removed kodi from my system and reinstalled pkc to make sure it wasn't a plugin incompatibility

**Comment by croneter** [comment]
Have you tried renaming in the PKC Settings, Plex, Use alternate device name. Then reboot?

**Comment by croneter** [comment]
And I guess you did try rebooting the PMS as well, then Kodi afterwards? ;-)

**Comment by itsj4y** [comment]
yes i tried renaming the companion and restarting both koki and pms

**Comment by croneter** [comment]
PlexKodiConnect also does not show up when you fire up a browser and navigate to the Plex Media Server, then try casting there?

**Comment by itsj4y** [comment]
no it doesn't show up anywhere. but my plex iOS apps and plex media player do show up

**Comment by croneter** [comment]
Can you please enable debug logging on your PMS? Restart Kodi. Then share you PMS logs - they should show Plex companion trying to connect

**Comment by itsj4y** [comment]
which pms logs theres 77 of them

**Comment by croneter** [comment]
the last one, sorted by date ;-)

**Comment by itsj4y** [comment]
i guess you mean the latest Plex Media Server.log not any of the Plex Media Scanner.log, Plex Media Scanner Analysis.log, etc.

**Comment by itsj4y** [comment]
kodi was restarted between 2108 and 2114
[Plex Media Server.txt](https://github.com/croneter/PlexKodiConnect/files/681214/Plex.Media.Server.txt)

**Comment by croneter** [comment]
Yes, thanks.

Am 02.01.2017 19:19 schrieb "itsj4y" <notifications@github.com>:

**Comment by itsj4y** [comment]
looking through the pms logs in verbose mode i see this
under the iOS app it shows
X-Plex-Provides => client,controller,sync-target,player,server
under pkc it shows
X-Plex-Provides => player

should it show it as a client?

**Comment by croneter** [comment]
I think it should also say client, yes. 

Could you please share the log?

**Comment by itsj4y** [comment]
kodi restarted at 2126
[Plex Media Server.txt](https://github.com/croneter/PlexKodiConnect/files/681275/Plex.Media.Server.txt)

**Comment by itsj4y** [comment]
i just tried the official plex kodi plugin and it too does not show up

**Comment by croneter** [comment]
I hope it's the X-Plex-Provides as you suggested. Can't find anything else. Will be fixed in next version

**Comment by itsj4y** [comment]
ok cool thanks, just me wondering though. i haven't seen anyone else complain of this problem so it leads me to think its something with my setup?

**Comment by croneter** [comment]
That's what I'm wondering about, too. No idea... Keep your fingers crossed
;-)

2017-01-04 13:56 GMT+01:00 itsj4y <notifications@github.com>:

**Comment by itsj4y** [comment]
By next version did you mean 1.5.1 or the next one after that?

**Comment by croneter** [comment]
1.5.2 ;-)

**Comment by itsj4y** [comment]
still not showing as a cast option on the 1.5.2 beta. it does say it provides client, controller, and player.
i have attached the logs
[Plex Media Server.log.txt](https://github.com/croneter/PlexKodiConnect/files/696840/Plex.Media.Server.log.txt)
[kodi.log.txt](https://github.com/croneter/PlexKodiConnect/files/696841/kodi.log.txt)

**Comment by croneter** [comment]
Darn, thanks for the logs
