### ISSUE TITLE
PKC spams proxy server with `localhost` requests; proxy crashes;

### ISSUE THREAD

**Issue by gpacgpac** [croneter/PlexKodiConnect#1732]
## Describe the bug
Despite having set the no_proxy (or NO_PROXY) environment variable, PlexKodiConnect is not taking it into account and pass all requests to the proxy rather than directly to the plex server (located at same IP but different port).
Due to the type of request PlexKodiConnect is forging, proxy service finally crash blocking all http traffic for local clients.

## To Reproduce
either create/modify /storage/.profile with 
   export http_proxy="http://xxx.xxx.xxx.xxx:8080"
   export https_proxy="http://xxx.xxx.xxx.xxx:8080"
   export no_proxy="xxx.xxx.xxx.xxx"
or create/modify /storage/.config/system.d/kodi.service.d/override.conf with
   [Service]
   Environment="http_proxy=http://xxx.xxx.xxx.xxx:8080"
   Environment="https_proxy=http://xxx.xxx.xxx.xxx:8080"
   Environment="no_proxy=xxx.xxx.xxx.xxx"
   Environment="NO_PROXY=xxx.xxx.xxx.xxx"

then restart kodi. After few seconds / minutes proxy server crash due PlexKodiConnect requests

## Expected behavior
Normally requests to xxx.xxx.xxx.xxx:32400 or xxx.xxx.xxx.xxx:80 should not be passed to proxy sitting at port 8080.

## Traces in log files
No specific trace of proxy usage in kodi debug logfile, but proxy service log file shows many incoming requests from kodi client requesting this kind of url : _http://localhost:8080/image/image://http%253A%252F%252Fxxx.xxx.xxx.xxx%253A32400%252Fphoto%252F%253A%252Ftranscode%253Fwidth%253D1920%2526height%253D1920%2526minSize%253D1%2526upscale%253D0%2526url%253D%252Flibrary%252Fmetadata%252F11742%252Fart%252F1636765621_
After ~80 of such request the proxy service crash
and kodi log file then says PLEX.artwork: Were trying too hard to download art, server over-loaded. Sleep 1 seconds before trying again to download http://...

In my configuration this bug is somewhat blocking since it finally conduct the proxy server to crash (after a flow of ~80 repeated requests as above). If I remove http_proxy parameter from configuration, then the kodi client cannot go outside.

**Comment by croneter** [comment]
Seems to be a Python requests issue: https://github.com/psf/requests/issues/4871

I guess you're trying to whitelist IPs, not hostnames?

**Comment by gpacgpac** [comment]
Yes I'm trying to whitelist my plex/proxy IP (the exact IP, not a subdomain => I don't see the ).

I cannot proceed with hostname because plex does not accept connection with hostname (but accept without any problem with IP). That should be because I have no Plex Account nor ever connected my server to plex.tv in anyways (it's a local install to stream files locally).
When I proceed with hostname, the Plex server decline connection (despite my client IP adress is recognized as allowed network) :
ERROR: PLEX.initialsetup: Not yet authorized for http://plex.******.******:32400

And in plex server debug log file we find 
DEBUG - Request came in with unrecognized domain / IP 'plex.******.******' in header Host; treating as non-local
DEBUG - Request: [***.***.***.***:32968 (Allowed Network (WAN))] GET / (8 live) GZIP / Accept => */* / Accept-Encoding => gzip, deflate / Accept-Language => fr / Connection => keep-alive / Content-Type => application/x-www-form-urlencoded / Host => plex.*******.****:32400 / User-Agent => python-requests/2.22.0 / X-Plex-Client-Identifier => 943dbdac-a1a4-4dba-917b-30de4ee404bc / X-Plex-Device => Linux / X-Plex-Device-Name => Kodi LibreELEC / X-Plex-Model => 4.19.127 / X-Plex-Platform => Generic / X-Plex-Platform-Version => 1.0.0 / X-Plex-Product => PlexKodiConnect / X-Plex-Provides => client,controller,player,pubsub-player / X-Plex-Version => 2.15.0

**Comment by croneter** [comment]
Your use case is extremly peculiar / unlikely that others have similar requirements. I do not want to have to fix issues with underlying Python modules like requests, root cause of your issue (see my link above). 

Can you try this?
* Grab a Plex token, see https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
* Edit PKC's settings file `settings.xml`, that you can find in the folder `addon_data/plugin.video.plexkodiconnect` in the [Kodi userdata folder](https://kodi.wiki/view/Userdata):
  - plug-in your Plex token: `<setting id="accessToken">yourtokenhere</setting>`
  - plug-in your PMS connection:
    - `<setting id="https">true</setting>` or `false`
    - `<setting id="ipaddress">ip adress or hostname, e.g. 127.0.0.1</setting>` (so no `https://`!)
    - `<setting id="port">PMS port, e.g. 32400</setting>`
  - try this with your PMS' HOSTNAME, not IP (due to the "bug" mentioned in the Python requests library above)

**Comment by gpacgpac** [comment]
Thank you four your feedback,

Having checked the posts related to the underlying Python issue, I do understand your point.
I will retry what you suggest (may be only next week-end :-().


The issue I'm facing with Plexkodiconnect through my proxy is rather strange since access to my Plex server (with IP adress) from a desktop web brother directly or via proxy is working without hurting the proxy => I'm wondering if there is not a specific issue somewhere in your library explaining why it's creating these kind of strange requests (starting with http://localhost:8080/.... which sould initiate endlees loop in the proxy conducting to the crash).

Do you know if there is some ways to log each and every http requests Plexkodiconnect is sending to the Plex server ? (the proxy log is logging the request after having treated it but not at their arrival before treatment) ?

Nota : this problem is reproductible (each time I restart Kodi after few minutes it send such request and cause a proxy crash) ; but Plexkodiconnect achieved to load my library correctly (~5000 other "good" requests passed through the proxy without issues).

**Comment by croneter** [comment]
I could look into it - but I would need a Kodi DEBUG log, up till Kodi/your Proxy crashes.

**Comment by gpacgpac** [comment]
I've pent quite some time to analyze Kodi DEBUG logs with or without the no_proxy parameter set (but still with my server declared by it's IP). Findings are : 
1) when the no_proxy is NOT set-up, we see 
  + Curl::Debug lines showing curl is connected through the proxy (trying connections to port 8080 = proxy).
  + no line for requests to librelec.tv (these requests are sent each time kodi restarts and are properly traced in the proxy server log). It means that some requests are sent but not traced in Kodi DEBUG log file....

2) when the no_proxy is set-up with ip of the plex server, the Curl::Debug lines no longer show up connection via the proxy (and instead shows direct connections to port 32400 which is good), BUT 
   + just before Curl::Debug lines we such lines : 
              DEBUG: Using proxy *****.******.*****, type 0
              INFO: easy_acquire - Created session to http://***.***.***.***
         and some time later (after end of downloading several stuff from plex) : 
              INFO: CheckIdle - Closing session to http://***.***.***.*** (easy=0x6a2a84b0, multi=0x70ea52e8)
   + and finally just before crash of proxy we get the following in kodi DEBUG :
2021-12-06 22:07:46.948 T:1690878848   DEBUG: PLEX.kodimonitor: PKC settings change detected
2021-12-06 22:07:54.005 T:1936986688    INFO: CheckIdle - Closing session to http://***.***.***.*** (easy=0x6a06b660, multi=(nil))
2021-12-06 22:07:54.514 T:1936986688    INFO: CheckIdle - Closing session to http://***.***.***.*** (easy=0x7241b5a0, multi=0x72458750)
2021-12-06 22:07:54.514 T:1936986688    INFO: CheckIdle - Closing session to http://***.***.***.*** (easy=0x71869068, multi=0x5c1c9870)
2021-12-06 22:07:54.515 T:1936986688    INFO: CheckIdle - Closing session to http://***.***.***.*** (easy=0x6a0c4220, multi=0x70e220b0)
2021-12-06 22:07:54.515 T:1936986688    INFO: CheckIdle - Closing session to http://***.***.***.*** (easy=0x6a1c7a90, multi=0x72458bd0)
2021-12-06 22:07:54.580 T:1807721344   DEBUG: Thread JobWorker 1807721344 terminating (autodelete)
2021-12-06 22:07:54.582 T:1372291968   DEBUG: Thread JobWorker 1372291968 terminating (autodelete)
2021-12-06 22:07:54.597 T:1380684672   DEBUG: Thread JobWorker 1380684672 terminating (autodelete)
2021-12-06 22:07:54.703 T:1403310976   DEBUG: Thread JobWorker 1403310976 terminating (autodelete)
2021-12-06 22:08:06.499 T:1936986688  NOTICE: Samba is idle. Closing the remaining connections

And on the proxy server we have : 
2021.12.06 22:06:36 a trace of request for http://releases.libreelec.tv/releases.json
2021.12.06 22:06:37 a trace of request for https://update.libreelec.tv:443
then no other activity traced by proxy until
2021.12.06 22:08:22 with a bunch of lines similar to this one : http://localhost:8080/image/image://http%253A%252F%252Fxxx.xxx.xxx.xxx%253A32400%252Fphoto%252F%253A%252Ftranscode%253Fwidth%253D1920%2526height%253D1920%2526minSize%253D1%2526upscale%253D0%2526url%253D%252Flibrary%252Fmetadata%252F11742%252Fart%252F1636765621
... and finally the proxy server crashed !

=> it seems that some requests are not passing through Curl and are not traced in kodi DEBUG, and some of those might be the cause of the issue I'm facing.

**Comment by croneter** [comment]
Try deactivating the caching of artwork in the PKC settings, then restart Kodi

**Comment by croneter** [comment]
Any news here?

**Comment by gpacgpac** [comment]
With caching I do have crashes after 2 minutes from kodi startup (~ 30 sec after the "NOTICE: PLEX.artwork: ---===### Starting ImageCachingThread ###===---").

Without caching, no crash from the proxy (so far, after ~1 hour idle)... ...but now the covers / fan arts are not updated when an update is made on the Plex server (changing on Plex side is not implemented on the Kodi side even after kodi restart).

=> It seems there is something around the caching activity, and no caching is not the perfect answer (loss of update feature).

**Comment by gpacgpac** [comment]
Here is what I found when caching in enabled

When the script is working on artworks, it's going at some point of time through .kodi/addons/plugin.video.plexkodiconnect/resources/lib/artwork.py and more specifically though the "cache_url" sub starting at line 98.

the url at the beginning of the while loop (line 101) is OK, but when going through (line 104 to 107)
              url="http://%s:%s/image/image://%s"
                    % (app.CONN.webserver_host,
                       app.CONN.webserver_port,
                       url),
the url is changed to something claiming localhost:8080, then when this request is sent to proxy server, it crashes (endless loop).

A workaround seems to be to add "no_proxy=localhost" as environment variable. When this is done, these requests starting with localhost are not sent to proxy, but kept locally.

There is no gui to set-up the no_proxy environment variable in Kodi (and by the way, I think nobody would have the idea to include localhost in the no_proxy list of hosts) => my recommendation to fix this would be to append localhost to the no_proxy parameter when you initiate the request session (ie : if someone specified system-wide "no_proxy=direct.web.site", then python requests should be initiated with "no_proxy=direct.web.site,localhost").

I'm sorry, I cannot formulate code proposal since I have no experience in python :-(.

Nota : as a workaround I created the following systemctl override file for kodi service (with systemctl edit kodi) :
[Service]
Environment="http_proxy=http://myproxy:8080"
Environment="https_proxy=http://myproxy:8080"
Environment="no_proxy=localhost"

This workaround seems to work (despite systemctl is claiming for daemon-reload at each reboot even if this has been done !).

**Comment by croneter** [comment]
Glad we narrowed it down! I don't think PKC should be "hacking" your `no_proxy` environment variable, seems rather extreme. Could you please try this:
1. Shut down Kodi
2. Edit the file `addons/plugin.video.plexkodiconnect/resources/lib/app/connection.py` in your [Kodi userdata folder](https://kodi.wiki/view/Userdata)
3. Change `self.webserver_host = 'localhost'` to `self.webserver_host = '127.0.0.1'`

Does that help? Would be an easy fix on the PKC-side. Otherwise, other user would need to manually set their environment variable to `no_proxy=localhost` like you did.

Don't forget to change it back again 😉

**Comment by gpacgpac** [comment]
I will check as soon as I have hands on my kodi/plex install, but I'm rather pessimistic on the outcome.

I understand that it will throw to the proxy an http://12.0.0.1:8080/... request instead of http://localhost:8080/... I assume the result will unfortunately be the same.

To force direct connections, what about changing your line 110 of resources/lib/artwork.py for this :

proxies={ "http": None, "https": None }, timeout=TIMEOUT)

(https://www.w3schools.com/python/ref_requests_head.asp , https://www.w3schools.com/python/showpython.asp?filename=demo_requests_head_proxies & https://docs.python-requests.org/en/latest/user/advanced/#proxies).

I understand these 103 to 110 lines are only used for querying the local kodi webserver => overriding proxy parameters at that very specific point should not have side effects ?

**Comment by gpacgpac** [comment]
I've tested both proposals :
1) Changing localhost to 127.0.0.1 in addons/plugin.video.plexkodiconnect/resources/lib/app/connection.py has the same cosequences : proxy crashes again quickly after artwork update start (due to requests starting with http://127.0.0.1:8080/ passed to the proxy server) => this solution is NOK.

2) Updating line 110 of addons/plugin.video.plexkodiconnect/resources/lib/artwork.py by adding "proxies={ "http": None, "https": None },". This one seems to work : no more strange requests pushed to the proxy server.

If changing that line of artwork.py has no other consequences (ie : is used exclusively for localhost's webserver queries), this could (should) be the solution.

Have a nice Xmas.

**Comment by croneter** [comment]
Should be solved with version 2.6.2. 

Thanks a ton for your debugging and help solving this - much appreciated!

**Comment by gpacgpac** [comment]
Hum, proposed version in Kodi is already 2.15.0 => may be you mean 3.6.2 for Matrix.

Do you plan to release also the patch on Leia ? (For the one's like me using LibreElec on Raspberry Pi 3, Matrix is not yet available :-( ).
