### ISSUE TITLE
Only TV Shows in Collection don't sync with Plex

### ISSUE THREAD

**Issue by co-sine** [croneter/PlexKodiConnect#1733]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
After my test, PKC will sync everything (progress, status, etc.) while playing episodes in the library **only except** the TV Shows which are included in their Collections. On Plex side, the library is set "hide shows which are in collections"; PKC side, any playing method, add-on path, or direct path gave the same result.
The TV Shows in Collection is playable but won't have any sync happening with Plex, for example, no skip intro, no up-next, mark as watched/unwatched not working, no resume function.

## To Reproduce
1. Go to the homepage
2. Click on an episode (which is from a TV Show within its collection) on the deck
3. No skip intro, no up-next, mark as watched/unwatched not working, no resume function.
4. After stopping playback, then no update happens because there is no sync happened.

## Expected behavior
Sync everything normally.

## KODI LOG FILE!
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/7657026/kodi.log)

**Comment by croneter** [comment]
See here: https://github.com/croneter/PlexKodiConnect/issues/689
