### ISSUE TITLE
incorrect syncing when seasons are hidden for TV shows

### ISSUE THREAD

**Issue by kalle2000** [croneter/PlexKodiConnect#1735]
Hi there,

recently I started to hide the season in PLEX in case there is only one season for a show (via Edit --> Advanced --> Seasons --> Hide). After I changed that, the episodes are not accessible in Kodi anymore. I still have the entry of the show itself, but inside there are no entries anymore. I also excluded the entire library from sync, rebooted and included the library again for syncing.

**Comment by croneter** [comment]
Simply don't hide your seasons?

**Comment by croneter** [comment]
See here, exactly the same issue: https://github.com/croneter/PlexKodiConnect/issues/586
