### ISSUE TITLE
Add automatic "Skip Intro" option

### ISSUE THREAD

**Issue by kariudo** [croneter/PlexKodiConnect#1738]
The implementation of Skip Intro is great, but still requires the user pick up a remote and press skip at each episode. Ideally an the plugin could provide an optional settings boolean/toggle to automatically skip the detected intro instead of showing skip intro button.

**Comment by croneter** [comment]
Isn't there a PKC setting doing exactly that? https://github.com/croneter/PlexKodiConnect/pull/1680

**Comment by croneter** [comment]
Called Auto skip intro

**Comment by croneter** [comment]
Are you using Kodi 18? Haven't implemented that for Kodi 18 yet 😆

**Comment by kariudo** [comment]
Well, that's embarrassing, I searched issues and forgot to check for PRs or I would have seen that, sorry.

Turns out that despite me having auto-update on (shame on me for trusting that), I was still back on 3.5.8 of PKC. So yep, it is in fact now there in Matrix. Thanks for linking the PR for me so I would realize it just didn't update.
