### ISSUE TITLE
PlexKodiConnect crashes on startup, module utils missing

### ISSUE THREAD

**Issue by mpeterson** [croneter/PlexKodiConnect#174]
Whenever I start the add-on it crashes. Started a debug log and found that the culprit is that it cannot find the module utils. 

PlexKodiConnect version: 1.5.1

Here is the debug log: http://paste.ubuntu.com/23732592/

**Comment by croneter** [comment]
Try to uninstall PKC completely. Then try installing it again using the repo: [ ![Download](https://api.bintray.com/packages/croneter/PlexKodiConnect/PlexKodiConnect/images/download.svg) ](https://dl.bintray.com/croneter/PlexKodiConnect/bin/repository.plexkodiconnect/repository.plexkodiconnect-1.0.0.zip)

**Comment by mpeterson** [comment]
Worked. Don't know what the problem was before but at least it works now. Thanks.
