### ISSUE TITLE
Backend sync not working as it should

### ISSUE THREAD

**Issue by Osberg** [croneter/PlexKodiConnect#175]
I have 3 raspberry Pi running with OSMC and I can see the following issues.

1: When I start to play a movie on one of the rasp it dont sync data so I can see it on the others if I choose to move on from the first one. 
I saw this yesterday where I started a movie on the one in my livingroom, and then I went into my bedroom, where I have a Mi Box running Andriod, the movie I was watching did not show up here that I was watching it.
On the one I have in my kitchen a rasp pi3 it was the same. 

2: If I start a movie on my rasp, and I then go to my phone and start up my plex here and choose the movie I was watching, and the mark it as not seen, it will not sync this info to my rasp... I have tried with a full sync and this don´t help. 
I have to reboot the devices before it sometimes works. 

I have attach debug log file from one of my rasp from yesterday where I was playing around with this. 
[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/682315/kodi.txt)

**Comment by croneter** [comment]
1) If you watch a movie, will the play progress show up on your PMS (if you navigate to your Plex Media Server using a browser)?
2) Known issue. If you mark a video played/unplayed, this will sync to the PMS. However, the PMS will NOT tell anyone that this status changed. A full sync will update this info (on startup or by default every 60 minutes

**Comment by Osberg** [comment]
1: Yes I can see on my PMS that my device is playing the given movie. 

2: Strange that not a full sync fixed the issue then... I have set my full sync to 15 min instead. Is there a time frame on when this will be fixed?? :)

**Comment by Osberg** [comment]
I have seen serval times now that, sync info from devices etc is not working, and that is the biggest issue.... I mean background sync.... Since we often go from the livingroom to the bedroom or kitchen to keep watching the same movie, but I then have to start all over again... And that is not a WAF thing... hehe... :)

**Comment by croneter** [comment]
Full sync should definitely pick up the playstates. Please test again by going to Videos - Video Add ons - PlexKodiConnect - Manual sync. 
By the way, a full sync is not too heavy on your resources, you could lower the 15min to 1-2 min for now ;-).

**Comment by Osberg** [comment]
Ok have been testing it.... and the full sync every 2 min does it.... But I now stumble on a new ting here also.

On my rasp I have made my section on my home screen, for cartoon etc, and I have made a sub section for newly added, on deck etc... when I go into these sub section, and the full sync happens i will through me around in my menu and move me into the normal section of the my folder... So it will show all movies .... that is not very fancy.. :( 

I can make a small video if you would like to see??? :)

**Comment by Osberg** [comment]
Cronter, did you by any change test this your self or?? :)

**Comment by croneter** [comment]
Yes, short video please. 

The Plex user you're using - is it the Plex master user, or just some Plex home user?

**Comment by Osberg** [comment]
sure I will do this right away... This is the plex master (owner)

**Comment by croneter** [comment]
If you're using the master user, you definitely should have a working background sync.
* In the PKC Settings, Sync Options, is `Enable constant background sync` activated? If not, activate it and restart Kodi.
* If that does not help: 
    * You did not enable PKC debug logging in the PKC settings, Advanced. Please do so now, restart Kodi. 
    * Then play some Plex video on another client, see if PKC/Kodi picks up the view state. Then grab the log again and share it here.

**Comment by Osberg** [comment]
I just tested again, and the info from the other rasp pi3 dont come to the others rasp pi3 before they do a full sync :( 
![20170108_120847](https://cloud.githubusercontent.com/assets/23699885/21750244/28ce1112-d5af-11e6-8819-e7d58540844d.jpg)
![20170108_120859](https://cloud.githubusercontent.com/assets/23699885/21750243/28cd9994-d5af-11e6-81ad-362df257a244.jpg)
![20170108_135755](https://cloud.githubusercontent.com/assets/23699885/21750246/28ce6860-d5af-11e6-9d5f-56c909abbdf1.jpg)
![20170108_135817](https://cloud.githubusercontent.com/assets/23699885/21750245/28ce514a-d5af-11e6-93ec-360dd7a79cd1.jpg)

And the link to see the rec i made also : https://1drv.ms/v/s!ApflEzzfwkTsh_Jw7-kLfrR0vTUO7g

**Comment by croneter** [comment]
Logs please of you playing something somewhere else and the playstate not being synched to Kodi. Please enable PKC debug logging as explained above.

The fact that Kodi shows ALL movies instead of just your library might be a skin problem and is unrelated to the playstate not synching. Are you using Titan?

**Comment by Osberg** [comment]
I will fix some logs from one or two of my rasp to you... so you can see before a sync and after. :) 

About the changning of the info been showed, could be related to the skin.... I am using Arctic Zephyr on all 3. :) What I can see that when a sync start it changed how the movie are listed, from A-Y to Y-C and when the sync is done it change it again. 
But again the given movie been watched it not showen before it does a sync and not running in the background.... but can this be related to the skin also or?? :)

**Comment by croneter** [comment]
I also need the part WHILE you are playing on another device. Don't forget to enable debug logging. Let's focus on that issue for now

**Comment by Osberg** [comment]
From another device?? where can i find the logs here?? I am guessing you mean from a device where I am running plex correct?? 

I have just been testing it for 5 times on 5 different movies where I set the full sync to 10 min on both my raps pi3, and now they are sync in the background..... Grrr don´t you just hate it hehe... :) Let me keep testing this... :) 

Also regarding the change from A - Z when sync, I can see it changes the sorting from Last played to Title, so I am guessing that is a skin issue.... I will talk to the dev of the skin :)

**Comment by croneter** [comment]
So it's working now?

I mean I need the Kodi logs just after you've played something on another device and this change was NOT synched to Kodi, but showed up e.g. in the Plex web interface. The log will hopefully show something

**Comment by Osberg** [comment]
Well it worked yesterday on two of my rasp pi3 where I change the full sync to 10 min instead of 2 min... Let´s me test some more tonight. :) 

All test I have done so far, there has the movie come up in my plex... But let me dig a bit more in here :)

**Comment by croneter** [comment]
Still an issue?

**Comment by Osberg** [comment]
I will check up on this tonight to see if this is still a issue....

Regarding my other issue with the view changing on the under menu on-deck the dev of the skin replied:

Okay, I read through the GitHub issue for PKC and read what you said here. Now I don't use Plex (I tried it long ago when it was in its infancy and didn't like it and went back to WMC + MediaBrowser [now Emby]) but what I would need is someone knowledgeable in PlexKodiConnect to tell me if there is any additional logic that would need to be added to the skin for the "On Deck" folder to work as prescribed. From what I have read, it now is but you have an issue where the sorting is switching from Last Played to Title.

Can you provide a Kodi debug log when this happens?

The reason this is odd is because the sorting setting is actually a specific setting that is written to disk so its persistent. That means, to change the sort setting something actually has to tell Kodi what sort setting AZ:FA should use (whether that you using the sideblade or an addon). To me, at least for now, it seems like a PKC problem.

Can you comment on this??

**Comment by croneter** [comment]
Please provide a link to this discussion

**Comment by Osberg** [comment]
sure here we go : http://forum.kodi.tv/showthread.php?tid=257970&pid=2499122#pid2499122

**Comment by Osberg** [comment]
I also have a debug log here if you want: https://1drv.ms/t/s!ApflEzzfwkTsh_MAiXIyEbimGkEH5A

**Comment by Osberg** [comment]
I will check up on this tonight. :)

**Comment by Osberg** [comment]
Seems to be working again with background sync... I have set my full sync to 60 min again, and it seems to work better now. :)

**Comment by croneter** [comment]
Replied to Guardian Hope, dev of your skin `Arctic Zephyr: From Ashes`. Let's see what he thinks

http://forum.kodi.tv/showthread.php?tid=257970&pid=2507967#pid2507967

**Comment by Osberg** [comment]
Nice thanks for your help here. :)

**Comment by NorthernLights** [comment]
@croneter , I replied to you in the Arctic Zephyr: From Ashes discussion at http://forum.kodi.tv/showthread.php?tid=257970&pid=2510889#pid2510889.

One thing I want to note is that it appears @Osberg is using a version of `Arctic Zephyr: From Ashes Danvers (Preview)` that is modified. He has icons on the home screen which we disabled in that particular view in `Alpha 9` while the latest version is `Beta 10`.

If this issue has been resolved please let me know so I can mark this off of the list of known bugs with AZ:FA Danvers as it seems like the described behavior is functioning normally again.
