### ISSUE TITLE
Sync crash on reset of music DB due to non-existent table reference

### ISSUE THREAD

**Issue by davidheitman** [croneter/PlexKodiConnect#1765]
Kodi 19.3, built from source on Debian Sid
PlexKodiConnect 3.6.3

Upgraded to the latest PKC today.  It requested to reset the DB, so I did, but it failed.  I didn't save the log, unfortunately, but it shouldn't be necessary, details of the bug below, just depends how you want to fix it.  But basically, it was an error from the sync process complaining about a missing table "track" in the music DB.  The relevant code is here:

https://github.com/croneter/PlexKodiConnect/blob/ee1eb1447648069caa69b0266ac47595884d2a83/resources/lib/plex_db/music.py#L239

And the error is correct, there's no table "track" in the music DB.  I'm not sure if this is a recent schema change and it should be referencing the "song" table now, or what.  There are several other functions in that same file that reference the non-existent "track" table, but none of them appear to be called anywhere else in the code (actually looks like a lot of this file's functions are ripe for a purge).

As a workaround, I just temp changed this function to always return True, basically bypassing the check so it'll always wipe the music DB when it resets the database, regardless of whether there are any tracks synced. That works fine, the rest of the sync process proceeds normally.  So, the real fix is either updating this to reference whatever table supplanted "track" (possibly "song"?), or just remove the check entirely and always wipe the music db even when it's empty (https://github.com/croneter/PlexKodiConnect/blob/ee1eb1447648069caa69b0266ac47595884d2a83/resources/lib/utils.py#L580)

**Comment by croneter** [comment]
Debug log file?!? See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
I'm extremely interested in this part, that's why I'd love to see a debug log file 
> It requested to reset the DB, so I did, but it failed.

**Comment by davidheitman** [comment]
I didn't have time to recreate it, and won't have time anytime soon. I don't remember what version I was on before, but it was old, hadn't updated in a while.

Not really the upshot here, though. The headline is the "track" table doesn't exist.

**Comment by croneter** [comment]
No debug log no help possible
