### ISSUE TITLE
Sync had to skip some items....

### ISSUE THREAD

**Issue by chaoticmaster** [croneter/PlexKodiConnect#177]
I updated to the newest beta today and rebuilt the library as instructed.

Getting the error that sync had to skip some items because they could not be processed.
[pkc Could not process - unstable.txt](https://github.com/croneter/PlexKodiConnect/files/694993/pkc.Could.not.process.-.unstable.txt)

**Comment by croneter** [comment]
Darn! Thanks for the report!
