### ISSUE TITLE
PKC unresponsive after casting 

### ISSUE THREAD

**Issue by jackyaz** [croneter/PlexKodiConnect#1770]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
After casting an item to PKC, PKC can no longer play back any items either by casting or on Kodi

## To Reproduce
1. Cast item to PKC from Plex app
2. Stop playback 
3. Try playing something else

## Expected behavior
Other items can be played back either via casting or from Kodi PKC itself

I can upload a log file but it just shows PKC getting stuck on default.py when trying to start playback again. I'll upload it shortly

**Comment by croneter** [comment]
Debug log file?

**Comment by jackyaz** [comment]
Apologies, I seem to have got it working after a third Kodi database reset, disabling some other addons and turning off the device firewall. I'm going to keep testing it tonight, I'll report back if I see the issue again
