### ISSUE TITLE
Subtitles won't turn on by default because "PMS told us to not show any subtitles"

### ISSUE THREAD

**Issue by Shasoosh** [croneter/PlexKodiConnect#1771]
Hey,

I've suddenly started to get this issue where subtitles won't activate by default when starting a movie.
I keep seeing this in the log:
`PLEX.kodimonitor: Deactivating Kodi subtitles because the PMS told us to not show any subtitles`

Although PMS is configured to show subtitles.

Log: https://pastebin.com/ZRG7t701

Was anything changed in the recent versions?
Maybe a PMS update caused it?

Edit:

I've updated Kodi to 19.3 and the latest PKC, still no go. Although now the logs are different and only hint about this:

```
2022-01-13 00:49:38.807 T:9260  WARNING <general>: PLEX.subtitles: Unexpected missmatch of number of Kodi subtitles
2022-01-13 00:49:38.807 T:9260  WARNING <general>: PLEX.subtitles: Kodi subs: ['(External)']
2022-01-13 00:49:38.807 T:9260  WARNING <general>: PLEX.subtitles: Subs from the filesystem: []
```
Full log: https://pastebin.com/U000pHYS
I've tried playing two movies in the log session, both have external subtitles in Hebrew.

Thanks

**Comment by croneter** [comment]
Yes, something changed on the PKC side. PKC now by default tries to use the Plex settings for subtitles. This does not work 100% - your debug log for this video would be greatly appreciated! For now, simply go to the PKC settings -> Playback -> Switch `Who picks subtitles on playback start?` to `Kodi`. 

I need a DEBUG log file here, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Also for the video in question, please make a screenshot of the corresponding folder where the video lies. So I see what subtitle files are around

**Comment by croneter** [comment]
I need your help here, @Shasoosh

**Comment by Shasoosh** [comment]
Hey @croneter, sorry for the late replay. Since my initial post I had to reset my SHIELD due to the notorious SHIELD v19 update and wasn't able to reproduce this since. I'll reopen this thread once I'm able to reproduce this.
