### ISSUE TITLE
Open with ratingKey

### ISSUE THREAD

**Issue by spauldhaliwal** [croneter/PlexKodiConnect#1775]
Do the ratingKey's from plex mapped to videoId's inside the Kodi database when this plugin is used? I ask because I'm developing an app from which I would like to open kodi directly to a movie/tvshow's page, but the only id I have at runtime is plex's rating key.

**Comment by croneter** [comment]
You need to map the Plex `ratingKey` with the Kodi `movieId` (or whatever). Look into the `plex.db` that PKC creates, lies right next to all other databases. This is non-trivial, obviously, e.g. Plex has one unique ID for everything, Kodi one per media type (movie, show, season, episode, ...)

**Comment by croneter** [comment]
I myself did NOT succeed in opening a specific detailed e.g. movie information page on the Kodi side of things from within PKC (e.g. when you connect with Plex Companion and navigate to a movie's detail page using Plex for Android). Any pointers would be highly appreciated 😉

**Comment by spauldhaliwal** [comment]
Thanks! I'll look into it and let you know if I come up with anything.
