### ISSUE TITLE
Unique Constraint causing sync to crash

### ISSUE THREAD

**Issue by the-jeffski** [croneter/PlexKodiConnect#1777]
I've been getting an issue where the sync is crashing due to unique constraints failing.  Its been happening for the last 2-3 weeks and I can't see to narrow down why suddenly it is so. I don't see any update jobs happening to plex at this time - I use plex meta but this runs later in the morning so nothing I can see amending Plex data when the sync is happening.  

Yesterday I followed the full reset instruction to rebuild the database and the same happened overnight again. 

I'm aware you'd ideally want a full debug file but I am struggling to reproduce this on demand.  I have a log from this morning where it failed again where you can see it failing on the actors update. Any suggestions how I can force it to replicate to get a meaningful debug or to work out what data is causing this?

[plex_sync_crash_log.txt](https://github.com/croneter/PlexKodiConnect/files/7912575/plex_sync_crash_log.txt)

**Comment by the-jeffski** [comment]
I managed to dig into this a bit further and narrow down the movies causing this. Seems there is a known plex issue causing duplicate directors and actors in the db. The sync then falls fowl of that. By trial and error I can delete the affected movies, then the sync doesn't fail.  Might be good to have some try/catch around this update so if it hits a bad record it doesn't die.

**Comment by croneter** [comment]
> Might be good to have some try/catch around this update so if it hits a bad record it doesn't die.

No, it's not that easy, unfortunately...

**Comment by the-jeffski** [comment]
Shame.  There looks to be a fix in the latest plex beta to correct the dodgy data so hopefully that will nix this.  I've just removed the problematic films for now until I can prove that does.

**Comment by croneter** [comment]
You lucked out - found the bug. It's caused by a somehow "maleformed" Python environment that Kodi is using. 
This SHOULD work, but it did not:
```Python
from sqlite3 import IntegrityError
try:
    self.cursor.execute('INSERT INTO actor_link VALUES (?, ?, ?, ?, ?)',
                        (actor_id, kodi_id, kodi_type,
                         person[2], person[3]))
except IntegrityError:
    # With Kodi, an actor may have only one role, unlike Plex
    pass
```
Changed it to this and all is fine (there shouldn't be a difference!)
```Python
import sqlite3

try:
    self.cursor.execute('INSERT INTO actor_link VALUES (?, ?, ?, ?, ?)',
                        (actor_id, kodi_id, kodi_type,
                         person[2], person[3]))
except sqlite3.IntegrityError:
    # With Kodi, an actor may have only one role, unlike Plex
    pass
```
Did version 3.6.6 fix this for you?

**Comment by croneter** [comment]
Wierd, that did not fix it all the time, too eradic. Please try version 3.6.7

**Comment by the-jeffski** [comment]
Ah, was literally just about to test it as I moved one of the bad movies back to get added and it crashed on the directors constraint. Will revert it, update and try again.

**Comment by the-jeffski** [comment]
Yes, success. On the four movies I knew would cause it to crash, all imported and sync'd fine.  (which is great as it seems the PMS release didn't fix the raw data!)
