### ISSUE TITLE
PKC Incorrectly Reporting Playback for PVR Files

### ISSUE THREAD

**Issue by renzzla** [croneter/PlexKodiConnect#1778]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)

* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
I am hitting the same problem that was reported back in 2018, but looks like it was never fixed:

https://github.com/croneter/PlexKodiConnect/issues/557

Basically, I recently installed the Live TV Kodi addon to access my PVR (DVBViewer) which runs under Windows on a seperate box to Kodi (and has nothing to do with my Plex server which runs on a VPS remotely).

What I am seeing happen is that when I play back a recording from the PVR using kodi, PKC reports the playback to Plex, but incorrectly reports that it is the last thing I played from Plex. It shouldn't be reporting anything to Plex for PVR playback, let alone the incorrect file.

In the log, I played back 5 mins of an episode from Modern Family from my Plex server. PKC correctly reports this to Plex and Tautulli records it too. I then played back a recording from the PVR ("The Graham Norton Show"), and I can see in Plex and Tautulli that it's reporting the playback of Modern Family again, which is obviously wrong.

![image](https://user-images.githubusercontent.com/7829654/150638021-9ead52e1-343a-4dc2-a126-27437100e9d2.png)

Could PKC be made to ignore any PVR playback, ie anything that starts "PVR://"

## To Reproduce
Steps to reproduce the behaviour:
1. Make sure there is a working PVR addon installed in kodi
2.  Play episode from Plex server.
3. Stop playback, then play recorded show from the PVR addon
4. Check Plex/Tautulli

## Expected behavior
PKC should NOT be reporting playback status to Plex for PVR files.

## You need to attach a KODI LOG FILE!
A Kodi debug log file is needed that you recorded while you reproduced the bug. **Do clean your log of all Plex tokens (="Plex passwords")!!!** .
1. Activate Kodi's debug logging by going to the Kodi `Settings` -> `System` -> `Logging`. Then toggle the `Enable debug logging` setting.
2. Restart Kodi to start with a "fresh" log file.
3. Reproduce the bug.
4. Follow the [Kodi instructions](http://kodi.wiki/view/Log_file/Easy) to grab/share the Kodi log file. Usually only `kodi.log` is needed
    * 
5. **Delete all references to any of your Plex tokens** by searching for `X-Plex-Token` and `accesstoken` and replacing the strings just after that!
    * It's easiest if you copy your token, then use Search&Replace for the entire log file
    * You don't want others to have access to your Plex installation....
6. Drop your log file here in this issue. Or use a free pasting-service like https://pastebin.com and include the link to it here
    
I am aware that I can delete Plex tokens that I accidentially posted by following the [instructions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server)
[kodi.old.log.zip](https://github.com/croneter/PlexKodiConnect/files/7918270/kodi.old.log.zip)

**Comment by croneter** [comment]
Sorry, I don't use PVR at all. 

Could you kindly share a Kodi DEBUG log of you playing a PVR file? See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by renzzla** [comment]
Here you go
[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/8007841/kodi.zip)

**Comment by gregeeh** [comment]
This is exactly what I just reported [here.](https://github.com/croneter/PlexKodiConnect/issues/1772#issuecomment-1030694491)

The link contains the kodi debug file and the time it happens.

**Comment by renzzla** [comment]
No, you've misunderstood my problem (or gregeeh's problem is different from mine).

I have the issue while playing a recording using a Kodi PVR addon that accesses a remote DVBViewer server. It has nothing to do with Plex, and I am NOT playing the recording from Plex, I am playing it from the DVBViewer server. The issue is PKC tells Plex it's playing the PVR recording, when it shouldn't be telling Plex anything.

**Comment by croneter** [comment]
Kindly try the brand new BETA version 3.6.9

**Comment by gregeeh** [comment]
> No, you've misunderstood my problem (or gregeeh's problem is different from mine).
> 
> I have the issue while playing a recording using a Kodi PVR addon that accesses a remote DVBViewer server. It has nothing to do with Plex, and I am NOT playing the recording from Plex, I am playing it from the DVBViewer server. The issue is PKC tells Plex it's playing the PVR recording, when it shouldn't be telling Plex anything.

Mine problem is the same as yours, the only difference is you are playing a recording and I'm playing live FTA TV via TvH.  PKC thinks a movie or TV show is being played, usually whatever was played last in PKC, and then tells PMS its playing.

Will try latest BETA.

**Comment by renzzla** [comment]
3.6.9 seems to have fixed it for me. Playing back recordings using the Kodi PVR plugin is no longer reporting playback to Plex. I also tried Live TV, and that's not reporting to Plex either.

Thanks for fixing it.

**Comment by gregeeh** [comment]
@croneter - This issue is not fixed completely.  Last night I played a TV Show to the end, then went to bed.

This morning I played the trailers only of 2 different Movies.  Both Plex and Tautulli both have reported that I watched the same TV Show I watched last night twice this morning.  Which is not the case.

![2022-02-12_15-31-31](https://user-images.githubusercontent.com/46234729/153696572-2b6f6c40-c442-45d0-aa2a-37a418f42232.jpg)

**Comment by croneter** [comment]
I need debug logs for that, @gregeeh

**Comment by gregeeh** [comment]
> I need debug logs for that, @gregeeh

Will do tomorrow. 😎

**Comment by gregeeh** [comment]
> I need debug logs for that, @gregeeh

They are attached.

Played an episode of The Resident on Feb 13th 7:12AM  Then watched a trailer at 8:31AM.  History shows The Resident being played twice, which is not the case.

![2022-02-13_08-42-49](https://user-images.githubusercontent.com/46234729/153729510-7ba3cd79-157a-48b6-912b-3e459511ee21.jpg)

[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/8054582/kodi.zip)

**Comment by gregeeh** [comment]
Thanks @croneter , it does indeed seem to be fixed.
