### ISSUE TITLE
Kodi crashes after every video

### ISSUE THREAD

**Issue by djl0327** [croneter/PlexKodiConnect#1780]
Kodi crashes whenever the movie or episode finishes, or when marking a video as watched/unwatched
* Restarting has no effect, I've even uninstalled/reinstalled Kodi and started over
* I haven't found any solutions on here

**Comment by croneter** [comment]
Nothing suspicious in the log PKC-wise. Sorry, but there a thousands of reasons why Kodi could crash on video startup. PKC only tells Kodi what to play, then it's entirely up to Kodi. 

Check the Kodi forums for help; PKC can't help you here...

**Comment by djl0327** [comment]
I may have linked the wrong log file, posting the new one instead of the old one that crashed.  Here's a correct log file, in which I've enabled debug logging and component-specific logging.  There's definitely something happening after line 1219, but I can't figure out what's causing the problem.  I'll note that this crash happens after playing a video in full and also when an item is marked as watched or unwatched.  Can you help?
Kodi Log File: [https://paste.kodi.tv/diboquwevu.kodi](https://paste.kodi.tv/diboquwevu.kodi)
