### ISSUE TITLE
PKC overwrites advancedsettings.xml settings

### ISSUE THREAD

**Issue by taylormia** [croneter/PlexKodiConnect#1781]
My advancedsettings.xml looks like this:

```
<advancedsettings>
  <video>
    <ignorepercentatend>10</ignorepercentatend>
    <playcountminimumpercent>90</playcountminimumpercent>
    <ignoresecondsatstart>60</ignoresecondsatstart>
  </video>
  <musiclibrary>
    <backgroundupdate>true</backgroundupdate>
  </musiclibrary>
</advancedsettings>
```
When I change the video settings in the file to different numbers and restart Kodi, PKC overwrites the file with the previous settings. Any ideas how I can prevent the file being overwritten?
I'm on Kodi 19.3 on Ubuntu 20.04 and PKC 3.6.3.

**Comment by croneter** [comment]
There's no way to prevent that, because PKC enforces the same settings here that Plex uses. Otherwise you might end up with a different playback status (e.g. just started playing vs. completely unplayed)
