### ISSUE TITLE
Smart shortcuts don't work anymore

### ISSUE THREAD

**Issue by Daywalker442000** [croneter/PlexKodiConnect#179]
Running Kodi 17.0 (RC) and PKC 1.51. Testet with 1.54 also but same problem. Titan Skin is up to date

Not sure if its PKC or Titan related.

Last night i started Kodi up after quit some time, PKC had to be updatet and after basicly reinstalling the whole thing i saw the Homescreen. All my shortcuts and Widgets where there but nothing worked. I check skin settings and smart shortcuts for PKC was dissabled, couldn't turn it on because Titan doesn't know that PKC is installed, checked the supported addonss section and PKC was grey. So i deinstalled PKC and restarted KODI, after restart came a message that i have to install PKC to use certain features, so i did and after installing it again, Titan still does not know that its there. 

Strang but the widgets still work.

**Comment by croneter** [comment]
Sorry to tell you that this is skin related. PKC only provides e.g. Smart
playlists for the skin to use. Try removing the skin and wiping all its
settings (including its settings in the kodi userdata folder). Then
reinstall the skin

Am 12.01.2017 17:23 schrieb "Daywalker442000" <notifications@github.com>:

**Comment by Daywalker442000** [comment]
Thank you
