### ISSUE TITLE
error finding plex companion from windows phone plex

### ISSUE THREAD

**Issue by davidacarter1984** [croneter/PlexKodiConnect#18]
Been looking at the error logs and comparing responses from an android plex client to the plex companion in kodi connect and have found a possible solution in the code. The response  from an android box is in text/xml whereas your component sends in text/plain. Would you be kind enough to try changing this within def do_OPTIONS(self): In listener.py

**Comment by davidacarter1984** [comment]
I have actually found changed and tested a fix for this and would be great full if you could make the change in the master branch. the section of code is this

def getPlexHeaders(self):
        h = {
            "Content-type": "text/xml",
            "Access-Control-Allow-Origin": "*",
            "X-Plex-Version": self.settings['version'],
            "X-Plex-Client-Identifier": self.settings['uuid'],
            "X-Plex-Provides": "player",
            "X-Plex-Product": "PlexKodiConnect",
            "X-Plex-Device-Name": self.settings['client_name'],
            "X-Plex-Platform": "Kodi",
            "X-Plex-Model": self.settings['platform'],
            "X-Plex-Device": "PC",
        }

all I have done is changed the content type

**Comment by davidacarter1984** [comment]
Hi. Thanks for fixing the accented characters issue. Could you please look at this otherwise  every time the app gets updated on my 3 machines I  have to go and manually edit this file. Thanks very much.

**Comment by croneter** [comment]
Ah cool, thought I would have to construct new XML responses. That one's easy :-). Thanks a lot!
