### ISSUE TITLE
'Now Playing' Status not reported to Plex Media Server

### ISSUE THREAD

**Issue by meestark** [croneter/PlexKodiConnect#180]
Currently running 1.5.5 beta.

Started since update to 1.5.3 beta , now Playing status does not show up in the Plex Media Server status window.  It also does not update the watched status of an episode.

Log attached.

edit: Can confirm that manually "Mark as Watched" from within Kodi still seems to update back to PMS.

[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/703421/kodi.txt)

**Comment by croneter** [comment]
Fixed with 1a3728597b70dda3acc5b46da8062b274b0d75f0
