### ISSUE TITLE
Please allow to schedule sync, instead of syncing all the time.

### ISSUE THREAD

**Issue by TheGuyWhoo** [croneter/PlexKodiConnect#1805]
Having to sit through a sync every time I run kodi is very frustrating, especially since there's no way of canceling the sync. In this regard I would much prefer it to work as it does in TMDB helper.

**Comment by croneter** [comment]
Not likely that I'm gonna implement this. I.e. it's essential thst there IS a sync on startup.

Please open a feature request here: http://feathub.com/croneter/PlexKodiConnect
