### ISSUE TITLE
Add support for Kodi 20 Nexus VideoDatabase version 120

### ISSUE THREAD

**Issue by quietvoid** [croneter/PlexKodiConnect#1815]
## Describe the bug
The latest PKC version doesn't support VideoDatabase version 120, leading to syncs being saved to the previous database.
Or in the case of a fresh install, there's an error at initialization.

The database schema version was updated here: https://github.com/xbmc/xbmc/pull/19983

## To Reproduce
1. Install Kodi 20 Nexus nightly (at least newer than January 10 2022).
2. Install the PKC repository
3. Install the PKC addon
4. Wait for the configuration to start
5. It errors with `The current Kodi version is not supported by PKC. Please consult the Plex forum.`

## Expected behavior
The addon should work on latest Kodi 20 Nexus, with VideoDatabase 120.

The error comes from https://github.com/croneter/PlexKodiConnect/blob/27202d2ab2bfb7a32cd2d37eda869f0c6ebe2aac/resources/lib/service_entry.py#L44-L55

**Comment by quietvoid** [comment]
To make it work we simply need to add the version to the supported versions.
I don't know enough about the code to add the new HDR types from the DB.

**Comment by croneter** [comment]
Try the new BETA version 3.6.13 please

**Comment by quietvoid** [comment]
Beta version 3.6.13 seems to work for me.
I couldn't find it in the repository, though.

Thanks!

**Comment by Kravatak76** [comment]
@croneter Hi, can i ask why is last Nexus nightly unsupported in PKC? i instal this version and when i start PKC i have only information that this Kodi version is unsupported :( Thank you.

**Comment by croneter** [comment]
@Kravatak76 Solved with latest version 3.6.14. Please open a new issue next time

**Comment by Kravatak76** [comment]
> @Kravatak76 Solved with latest version 3.6.14. Please open a new issue next time

Thank you
