### ISSUE TITLE
Rediscover widget within hub marks seasons as watched

### ISSUE THREAD

**Issue by the-jeffski** [croneter/PlexKodiConnect#1821]
I have been trying to set up using the Hub elements in some widgets.  I chose the rediscover option to set up on a widget.
Thsi works and finds the relevant TV shows but when I navigate into the show I get
a) a season selection even if I have flatten enabled for the libraries (which I suspect is because it comes from the Plex API
b) some seasons will be marked as watched even when the episodes within are not. 

I'm trying to find a way to debug this to get what data is being received into Kodi to be able to provide some data response to analyse.  Enabled debuging on HTTP but nothing records.  Any tips to find the responses so I can give you more to analyse?

**Comment by croneter** [comment]
Hmmm, sounds to me like a skin issue. Try another skin. Or possibly an issue with the widget you're trying to use. 

Can't tell you more, sorry

**Comment by the-jeffski** [comment]
Tried with Estuary as the first thing. I just see the series as watched even navigating through the add on regardless of adding to a widget. Might have to proxy the requests then to see whats coming back from plex.
