### ISSUE TITLE
Plex New Function Watchlist

### ISSUE THREAD

**Issue by labdiynez** [croneter/PlexKodiConnect#1828]
Can you add it on PKC?

![image](https://user-images.githubusercontent.com/52117480/161870976-f9b5dcda-33a4-4436-8500-fa84206203ba.png)

**Comment by jamal2362** [comment]
I would welcome this.
I always have to open the Plex app to see what's in my watchlist.

**Comment by slydog3333** [comment]
Watchlist would be a great addition.

**Comment by croneter** [comment]
Implemented with PKC Beta version 3.9.1

**Comment by FrankieBBBB** [comment]
Hello, i got a watchlist with 40 movies. It shows with PKC not more then 19. Is this a PKC thing or Kodi?
