### ISSUE TITLE
Direct Paths does not show video playback information on the PMS Dashboard.

### ISSUE THREAD

**Issue by showkubii** [croneter/PlexKodiConnect#1830]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)
* I tried downgrading the version and the problem persists.

## Describe the bug
When I play a video via PKC 3.6.13 (Direct Paths) on the dashboard, the PMS shows nothing.

## Expected behavior
I want the dashboard to show information when playing video files on PKC 3.6.13.

## KODI LOG FILE!

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/8447655/kodi.log)

**Comment by croneter** [comment]
I need a DEBUG log file, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by showkubii** [comment]
> ฉันต้องการไฟล์บันทึก DEBUG ดูhttps://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

PKC & UPNEXT
Love and Destiny (2019) - S01E08 [DIYNEZ].mkv Show on PMS Dashboard
Love and Destiny (2019) - S01E09 [DIYNEZ].mkv Show on PMS Dashboard
Love and Destiny (2019) - S01E10 [DIYNEZ].mkv No Show on PMS Dashboard

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/8449489/kodi.log)

**Comment by showkubii** [comment]
Today PMS Dashboard shows nothing when playing with PKC.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/8458857/kodi.log)

**Comment by showkubii** [comment]
@croneter As PKC has problem with upnext, upnext works properly but PKC doesn't send data when playing next episodes on PMS server.

So I disabled upnext and everything was fine. Hope you can fix upnext problem or add auto play next chapter function on PKC. Thanks.

**Comment by showkubii** [comment]
I disabled upnext, problem persists, only tv shows. the movie works fine.

Sorry to confuse you but after I use it for a while the problem arises.

**Comment by showkubii** [comment]
> Please share another debug log, I guess your configuration changed.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/8468403/kodi.log)

**Comment by showkubii** [comment]
> Please share another debug log, I guess your configuration changed.

I have to go mark it as playing. and marked as not playing on PMS and everything works as expected including upnext as well.

I've tested it for hours and it's working fine so far.

Thanks for trying to follow up and help fix the problem.

**Comment by croneter** [comment]
Why did you close the issue?

**Comment by showkubii** [comment]
> Why did you close the issue?

I was able to fix the problem.

And now everything works fine.
