### ISSUE TITLE
Problem with Emby with different Sources?

### ISSUE THREAD

**Issue by SomeRandomDude870** [croneter/PlexKodiConnect#1835]
Hi,
There is a warning to only use Plex and not Kodi to manage content. And I believe there was something about Emby too.

I am using Kodi as Frontend and Emby as Backend.
Now I have an separate Software that can "add" it´s database to Plex, which I would like to do. No, I do not want to try Plex again for everything. It just didn´t work.

Can I use PKC together with "emby next gen" if the managed Files are different or would there still be problems?

**Comment by croneter** [comment]
You cannot use Plex and Eine next gen simultaneously as they both take over the Kodi database. 

Except if you set-up 2 Kodi profiles: one for Embed, one for PKC

**Comment by SomeRandomDude870** [comment]
Ohh that´s nice. Going to try that.
