### ISSUE TITLE
Kodi 19.4 crash when trying to setup widgets

### ISSUE THREAD

**Issue by dobbleg1000** [croneter/PlexKodiConnect#1845]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
Kodi is crashing when trying to execute the steps in 
https://github.com/croneter/PlexKodiConnect/issues/835#issuecomment-485118668

I am aware that I can delete Plex tokens that I accidentially posted by following the [instructions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server)
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/8800915/kodi.log)
[kodi_crashlog-20220530_172740.log](https://github.com/croneter/PlexKodiConnect/files/8800916/kodi_crashlog-20220530_172740.log)

**Comment by croneter** [comment]
No idea what's causing this. PlexKodiConnect as a Python add-on should never be able to crash Kodi. Sorry, this is some Kodi bug I cannot do anything about 😢

**Comment by dobbleg1000** [comment]
Sounds good. I'll do some digging. My whole Kodi instance has been a bit unstable since an os upgrade and this is the first reproducible crash.
