### ISSUE TITLE
Fanart.tv Art Requests Not Working / Use Direct API Instead?

### ISSUE THREAD

**Issue by DivinityCycle** [croneter/PlexKodiConnect#185]
Environment: 
OS: Windows 10 Enterprise 64-bit
Kodi: 17.0-RC2 Git:20161230-5c40b5c-dirty
PlexKodiConnect Version: 1.5.3

After turning on the fanart.tv-related options, I'm now not getting new art but am instead getting errors in my kodi.log.

The errors I get are things like:

18:38:42.856 T:4764  NOTICE: PLEX.downloadutils -> ERROR:: Unknown answer from PMS http://webservice.fanart.tv/v3/movies/tt0758730?api_key=[key redacted] with status code 502.
18:38:37.137 T:4764  NOTICE: PLEX.downloadutils -> ERROR:: Unknown answer from PMS http://webservice.fanart.tv/v3/movies/tt0120724?api_key=[key redacted] with status code 404.

18:38:36.048 T:4764  NOTICE: PLEX.downloadutils -> ERROR:: Unknown answer from PMS http://webservice.fanart.tv/v3/movies/tt0106697?api_key=[redacted] with status code 502.

18:38:29.687 T:4764  NOTICE: PLEX.downloadutils -> ERROR:: Unknown answer from PMS http://webservice.fanart.tv/v3/movies/135416?api_key=[key redacted] with status code 520.

Each of these log entries is followed by "Message: " and then a dump of I guess whatever the Plex server returned, as it's a bunch of raw HTML and JSON.

It looks to me like currently PlexKodiConnect is relying on the PMS to talk to Fanart.tv. This is not a bad idea but it seems like it'd be a smarter move to instead at least allow an option for having Kodi talk to Fanart.tv directly via something like the Artwork Downloader. That would facilitate better / more "native" functionality within Kodi, as the downloader can fetch and add art assets beyond the scope of what PMS is able to do, like clearart, clearlogos, disc art, etc.

As far as I know it is possible for skins and other add-ons to call the Artwork Downloader, although I'm not sure off the top of my head if you can do things like run it against a specific title.
Ideally it'd be great to run it against each new movie or show added, or at least run it at the end of a library sync session provided that sync added new movies, TV shows, music albums, or music artists.
IMO it would not make sense to run it only in the event of new individual music tracks or TV show episodes, as no new missing extra art assets will be introduced by this occurance.

Details on this add-on here: http://kodi.wiki/view/Add-on:Artwork_Downloader

**Comment by croneter** [comment]
PKC already directly downloads additional fanart (that Plex doesn't feature) from fanart.tv. Hence the URLs you posted. No PMS in the middle. I'm aware of some issues with the way these downloads are handled; it's on the list of stuff I'd like to improve

fanart.tv might've been down; try going to PKC Settings -> Artwork -> Download artwork from fanart.tv. See what happens. If it still does not work, I would need all the info that you redacted out of the log. 

You can still use Artwork Downloader in parallel if you want to.

**Comment by DivinityCycle** [comment]
I apologize for the low quality initial post, I didn't know that PKC was handling the extra stuff. Would that include the crazy extras like disc art, character art, clear logos, etc?

On the issue, I'll do some more testing and then punt you full logs ASAP (probably in about 12 to 18 hours, at work at the moment ;P). I'm guessing I have one or more elements in my media library which are causing some kind of issue, like they're not on fanart.tv (I have some obscure stuff in there). When these unusual items are encountered, one or more unhandled cases occurs and the PKC thread is crashed, which would account for why I didn't know PKC downloads extra stuff on it's own (never got that far for me).

**Comment by croneter** [comment]
Solved?

**Comment by croneter** [comment]
I take it this is solved? You will always have some library items that will throw errors on fanart.tv
