### ISSUE TITLE
Not enough RAM on Pi 3B+?

### ISSUE THREAD

**Issue by naddel91** [croneter/PlexKodiConnect#1858]
Hi at all,

I just installed PKC and wanted to use it on my Pi 3B+, but unfortunately it freezes when RAM is full. Why is it needed to "sync" in the first place? It does not on my Android devices or my iPad when I use Plex.

Best wishes!

**Comment by croneter** [comment]
Yes, nothing I can do about that. PKC works completely different than any other Plex client because it enables Kodi to use the Plex database. Synching is required for that to work

**Comment by naddel91** [comment]
shit, I have to get another device then :(
what is the advantage of syncing? the disadvantage just hit me in the face today :(

**Comment by croneter** [comment]
https://github.com/croneter/PlexKodiConnect/wiki
