### ISSUE TITLE
Video Nodes Limits. Feature request and small issue.

### ISSUE THREAD

**Issue by dettwild** [croneter/PlexKodiConnect#186]
The Video Nodes that PKC provides are a great help when one wants to set up widgets that mimic Plex. This is especially true for the "On Deck" category, as the Plex server contains a customizable lookback period (in weeks) that affects the content of 'On Deck'.
However, PKC currently has a hard-coded limit of 100 items for various categories. Given that the 'On Deck' node for TV Shows calls the PKC plugin which dynamically contacts the Plex server, this can slow down the process significantly - an example of this might be issue #182 . 
Since most users don't need to see a full 100 items in the Widget, I would propose to allow the user to specify the respective limit in the settings and build the nodes thereafter.
Note: The 'On Deck' category for Movies works significantly faster, as it uses built-in Kodi logic (inprogress flag) and therefore does not require the PKC Plugin to contact the Plex server. Threfore it may even make sense to allow the user to specify a separate limit for TV Shows and Movies.

Now to the small issue: 
I noticed that the nodes that use a path with PKC plugin and parameters in the path actually return 1 item less than the specified limit. This is not the case for movie nodes. I suspect that the PKC plugin code somewhere contains a `< limit` instead of `<= limit`. 
It's obviously no big deal, and I don't mean to be a PITA - just thought I mention it when I already noticed it.

In case you need further info or details, please feel free to ask.

**Comment by croneter** [comment]
The underlying issue here is that xbmc/Kodi `ListItems` are a PITA. For some reason, it can take ages to set one up (lot of CPU power needed). Good idea though to make the limit customizable. 

Kodi standard logic is much faster than using ListItems.

**Comment by dettwild** [comment]
Thanks for your prompt reply. 
I am not sure what you mean by `ListItems` though, is that the stuff that goes into the 'path' of some of the video nodes?  The video nodes themselves seem clear to me though.
The logic to obtain the next unwatched episode (what we call 'On Deck') per TV Show seems to be quite CPU intensive - even if done within Kodi, e.g. using the Widgets Skin Helper Script. In contrast, the 'Inprogress' Flag used for 'On Deck' Movies seems to be quite efficient, but I am not sure if that flag is persisted in the Kodi db or determined on-the-fly.

How about the following workaround idea though:

Since PKC already works extensively with Tags, could it not work to generate an 'On Deck' tag for all items (episodes mainly) that Plex lists as 'On Deck' when doing the periodic full Syncs? If Plex advertises a change of its 'On Deck' items, such updates could even be done/synchronized immediately in the background.
I would expect a significant performance increase of the corresponding 'On Deck' widgets, as the related Video Node could use the simple and fast logic of a Tag-filter.
The only 'tricky' thing would be to detect items that had the 'On Deck' Tag, but no longer need it - I suspect scanning the entire Kodi db for those tags is inefficient and it may be easier to keep a separate list of the 'prior On Deck' items to compare to at a subsequent run. However, I am happy to trust your judgement here.

What do you think about this? If I could help testing such a concept/feature, feel free to let me know.

Finally, I hope you don't mind me asking if you were able to confirm the mentioned 'issue' at the end of my first post?

**Comment by croneter** [comment]
`ListItem` is this: http://mirrors.xbmc.org/docs/python-docs/stable/xbmcgui.html#ListItem, basically Python objects by Kodi needed to list e.g. the On Deck movies. 

Good idea to use a Tag. Unfortunately a major code overhaul would need to be done. 

If you could list where there is one item missing, that would greatly help (e.g. movies on deck, but not tv show on deck. Not in movies recently added, etc.)

**Comment by dettwild** [comment]
The 1 missing item comes from those nodes that use the 'path' , i.e. TV Shows - On Deck or TV Show - Recently Added.
The items that use the limit filter as separate XML item (not in the path) like Movies - On Deck or Movies - Recently Added work fine.
That is why I think it must be something in the PKC code rather than in KODI.
I noticed this when manually editing the video nodes to 10 items (who want to count to 100? ;-)).

Thanks for the link, I'll have a look soon.
