### ISSUE TITLE
Support for local extras

### ISSUE THREAD

**Issue by 0x464e** [croneter/PlexKodiConnect#1860]
You can add local extras in Plex for [movies](https://support.plex.tv/articles/local-files-for-trailers-and-extras/) or [TV shows](https://support.plex.tv/articles/local-files-for-tv-show-trailers-and-extras/) and I believe PKC doesn't support this.  
I think this would be a very nice addition. Or if someone has an idea of how I could achieve this myself, that would be great.

**Comment by croneter** [comment]
PKC should support this - bring up the Kodi context menu on e.g. a movie, then Plex Options, then Extras.
