### ISSUE TITLE
Wrong transcoding quality

### ISSUE THREAD

**Issue by jlssmt** [croneter/PlexKodiConnect#1864]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
PKC always transcodes to 720x405 when transcode is necessary. No matter what quality I set in settings.
It's working fine on plex mobile app and plex web site.

## To Reproduce
Go to settings
Go to playback
Set playback method direct path (I also tried direct stream and direct play) 
Set video quality for transcoding to 1080p, 8Mbps (I also tried 720p, 4Mbps)
Disable auto adjust transcoding quality (I also tried this) 
Set always transcode if video Bitrate is above 8Mbps (or anything matching your files to get transcoding when playing)
Disable H265 transcoding
Leave rest default

Play video with video Bitrate over 8Mbps
Get a 720x405 video played... 

## Expected behavior
It will get transcoded to 1920x1080, 8Mbps in my example.

**Comment by jlssmt** [comment]
Is this addon dead?

**Comment by croneter** [comment]
Hopefully fixed with PKC beta version 3.10.5
