### ISSUE TITLE
Add PKC ON DECK (FASTER) for TV Shows

### ISSUE THREAD

**Issue by youhitgit** [croneter/PlexKodiConnect#1865]
Could you please add a PKC ON DECK (FASTER) for TV Shows like you did for movies please ?

On the kodi home screen in the TV Shows submenu I have "On Deck"
Clicking this takes me to "On Deck" TV Shows.
But when I press "back" to return to the kodi home screen, it instead takes me to the PKC menu.

With movie libraries I have "PKC ON DECK (FASTER)" in the sub menu. 
Clicking this takes me to "On Deck" Movies.
When I press back it takes me straight back to the kodi home screen. ( Works Perfectly )

I think it has to do with the target destination.

Movies PKC ON DECK (FASTER) target is ;

ACTIVATEWINDOW(VIDEOS,"LIBRARY://VIDEO/PLEX-1/1_RECENT.XML",RETURN)

TV Shows On Deck target is ;

ACTIVATEWINDOW(VIDEOS,"PLUGIN://PLUGIN.VIDEO.PLEXKODICONNECT?MODE=BROWSEPLEX&KEY=%2FLIBRARY%2FSECTIONS%2F2%FONDDECK&SECTION_ID=2",RETURN)

Thanks

**Comment by croneter** [comment]
Should now work with PKC beta version 3.7.0!

**Comment by thorindwarf** [comment]
I updated today to 3.7.0 but PKC On Deck (faster) is missing under any of my TV Shows library nodes.
Am I missing something?

**Comment by croneter** [comment]
@thorindwarf just use On Deck, there is only a PKC version of this video node!
