### ISSUE TITLE
Support for Multiple Editions

### ISSUE THREAD

**Issue by brolyxxx** [croneter/PlexKodiConnect#1867]
Hi,
as per title, does PKC support multiple editions of the same movie as explained [here](https://support.plex.tv/articles/multiple-editions/) ?

I added 2 different editions of the same movie, and while you can clearly see the difference in the web client or Plex HTPC, in PKC I can't find a way to show the edition.

The skin is Aero Nox Silvo

Please let me know if you need more details.

thanks for this great addon!

**Comment by croneter** [comment]
Yes PlexKodiConnect does support several editions. If you're using add-on paths, it will automatically prompt you to select a version. If you're using direct paths, use the Kodi context menu, then PlexKodiConnect settings, then "Play via the PMS" to choose a version
