### ISSUE TITLE
Question regarding video chapter thumbnails

### ISSUE THREAD

**Issue by thorindwarf** [croneter/PlexKodiConnect#1868]
Hey :)

Thanks for this amazing software! I'm using it more than a year and tried different access to media files.
Am I missing something important or the chapter (bookmark) thumbnails are only possible to show when using direct paths so Kodi can directly access the files and generate them itself?
Is there anything that can be done in order to get them from PMS as they are already generated there during library scans?

Thanks!

**Comment by croneter** [comment]
Sorry it took me a while to answer 😞. 

Yes, currently the only thing you can do is use PKC direct paths and let Kodi handle the video chapter thumbnails. Obviously, a Pull Request is always welcome if you want to implement a solution that would use Plex thumbnails 😉
