### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by JCalvi** [croneter/PlexKodiConnect#1873]
Your feature request link goes somewhere funky
[Feature Requests](https://feathub.com/croneter/PlexKodiConnect)

**Comment by JCalvi** [comment]
I mention it as I wanted to add my vote for tidal integration.

**Comment by croneter** [comment]
Darn, thanks for reaching out!

**Comment by JCalvi** [comment]
No problem.

**Comment by croneter** [comment]
Finally got around to removing this link. Thanks again, @JCalvi !
