### ISSUE TITLE
Help with maintaining

### ISSUE THREAD

**Issue by davidheitman** [croneter/PlexKodiConnect#1877]
So, this has always been one of my favorite addons, and arguably the most important one for the way I use my media center.  Noticed there haven't been any updates in quite some time, and while it's been working fine for me, no recent bugs or issues, I wanted to ask if you need help with maintenance.  I don't always get much time myself, work and life and all that, but I thought I'd offer my services for keeping this plugin alive if you want/need them.  Could use a good project, too.  I'm sure I'm not the only one, but I'm sure I could help if you're interested.  And I haven't tried Nexus yet, but no doubt there will be changes that need changes.  Just sayin'.

**Comment by croneter** [comment]
Nope, you're the first. Actually, I'd highly appreciate any help 😆. What could you help with exactly, what's your background/expertise and where would you like to invest some time..?

**Comment by davidheitman** [comment]
Delayed response, busy week! But I have a good amount of python experience, some db work, more mysql but some sqlite. I understand rest apis and the like. And, perhaps most helpful, I've been using plexkodiconnect for like 5 or 6 years, sometimes troubleshooting my own issues, so I'm familiar with the codebase (last time I opened an issue, you closed it because I didn't have a chance to provide a log file, I was in the middle of a big move to a new house in the mountains :D ).

So, I was thinking, I know specifically of some crusty bits of old code that could be cleaned up, for starters. Might dig up the issue I created before and submit some PRs now that I have a bit of time again, start there. And I can help troubleshoot issues that other people post, in addition to anything I come across myself. General cleanup and maintenance, basically.

**Comment by croneter** [comment]
Sound fabulous 😍. What can I do to help you with that, to make it easier for you to help with PlexKodiConnect?

I myself have been rather busy, unfortunately

**Comment by davidheitman** [comment]
I hear you! Busy is my middle name these days. I'm hoping to get some time to start contributing this month, `but things will slow down for me after the holidays, so I'll definitely be on it then.

**Comment by megaslx** [comment]
I update my coreelec from matrix 19.5rc3 to nexus 20.0rc2,then find out the addon doesn't work properly. It can loggin my account and shows it's syncing content.But it can't sync anything from plex server.New episode doesn't show up and deleted move still shows on kodi side.
I tried remove the addon then resintall and setup it and it still doesn't work.(I'm using matrix repo and I nonticed there is nexus repo now,but I compared the addon.xml it's just some dir tag fix)

**Comment by croneter** [comment]
@megaslx please open a NEW GitHub issue and share some DEBUG (!!) log files as explained here, otherwise no one can help you: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by cengbrecht** [comment]
I have 0 relevant experience to my knowledge, but would love to assist. I am working on C, C++, and am interested in Rust. I will need to learn SQL at some point for engineering, any parts I could look at? I am great at breaking down documentation and finding written errors.

**Comment by croneter** [comment]
@cengbrecht hello! 👋 😉 
Very nice of you!

Most of the code is Python. Kodi natively uses several SQLite databases in the background with the option of switching them out for eg MySQL. There is also a new 'plex.db' to store the sync results. I hacked some SQL code that is very specific for SQLite to increase sync speed. On the top of my head, this could be useful for PlexKodiConnect:
- increase sync speed further
- replace all MySQL specific code to allow for a different database backend while at least maintaining sync speed

Most of the SQL code can be found here to get you started:
- https://github.com/croneter/PlexKodiConnect/tree/python3-beta/resources/lib/kodi_db
- https://github.com/croneter/PlexKodiConnect/tree/python3-beta/resources/lib/plex_db
- along with https://github.com/croneter/PlexKodiConnect/tree/python3-beta/resources/lib/itemtypes


What do you think? Any other ideas?

**Comment by croneter** [comment]
@davidheitman If you're still interested: https://github.com/croneter/PlexKodiConnect/issues/1906 seems like an easy fix 😉

**Comment by davidheitman** [comment]
Definitely still interested, life's just been a bit mad lately. Just got my media center up and running and pkc working again, I'll try to take a look this weekend!

**Comment by cengbrecht** [comment]
> @cengbrecht hello! 👋 😉 Very nice of you!
> 
> Most of the code is Python. Kodi natively uses several SQLite databases in the background with the option of switching them out for eg MySQL. There is also a new 'plex.db' to store the sync results. I hacked some SQL code that is very specific for SQLite to increase sync speed. On the top of my head, this could be useful for PlexKodiConnect:
> 
> * increase sync speed further
> * replace all MySQL specific code to allow for a different database backend while at least maintaining sync speed
> 
> Most of the SQL code can be found here to get you started:
> 
> * https://github.com/croneter/PlexKodiConnect/tree/python3-beta/resources/lib/kodi_db
> * https://github.com/croneter/PlexKodiConnect/tree/python3-beta/resources/lib/plex_db
> * along with https://github.com/croneter/PlexKodiConnect/tree/python3-beta/resources/lib/itemtypes
> 
> What do you think? Any other ideas?

Hahaha I think most of that is still over my head right now, but as I learn I will keep on this. :)
