### ISSUE TITLE
Question/Watch Status

### ISSUE THREAD

**Issue by obsidiangroup** [croneter/PlexKodiConnect#1878]
I understand PKC takes over the Kodi database.  My question is this.

I assume PKC syncs watch status between Kodi and Plex.  If so, is there a way to disable this and just store watch status on the local Kodi installation?

Plex is annoying in that you have to create home users, and you are limited to 15 home users.  There's no way to support external authentication (saml, oidc, or even LDAP) so we are trying to come up with a better way around this versus having to deploy multiple Plex servers.  Since users will only be using Kodi to view anything, watch status do not need to be sync'd back to the Plex server.

**Comment by croneter** [comment]
Unfortunately, sync of watch state cannot be deactivated. Pull request welcome though 😉
