### ISSUE TITLE
Ftp not working

### ISSUE THREAD

**Issue by Shawn9347** [croneter/PlexKodiConnect#1879]
Hello,

I'm trying to make pkc work with ftp. My media folders are accessible in kodi via ftp. I can play the files. But when playing it in my library and having the paths setup correctly it gives me an error. 

![image](https://user-images.githubusercontent.com/48714886/205352146-2fce9951-649a-46ef-a1d5-f741177d2867.png)

![image](https://user-images.githubusercontent.com/48714886/205352272-a67a40d3-bf5f-420f-8113-3c03752f10a8.png)

Anyone an idea? 

I'm assuming it is possible to do this with other protocols than smb, like nfs or ftp. It shouldn't be any different from smb. 
And since smb is not the fastest I would like to try ftp. Someone suggested it on reddit.

**Comment by croneter** [comment]
Try to edit your `sources.xml` found in the [Kodi userdata directory](https://kodi.wiki/view/Userdata#Location). Add 2 (two!!) sources like this (important part is the `ftp://` entry for `<path>`):
```xml
    <source>
      <name>PlexKodiConnect Masterlock Hack</name>
      <path pathversion="1">ftp://</path>
      <allowsharing>true</allowsharing>
    </source>
    <source>
      <name>PlexKodiConnect Masterlock Hack</name>
      <path pathversion="1">ftp://</path>
      <allowsharing>true</allowsharing>
    </source>
```
Does that help?

**Comment by croneter** [comment]
Don't forget to reboot Kodi 😉

**Comment by Shawn9347** [comment]
Yeah I got it already. You have to put the credentials in the path you replace plex's with. Unlike with samba.
