### ISSUE TITLE
Split movies based on quality

### ISSUE THREAD

**Issue by BRTPOB** [croneter/PlexKodiConnect#1891]
I just setup PKC, and I have my Plex libraries split up by quality, such that HD/Full HD movies are in one category, 4K/HDR movies are in another, and Dolby Vision movies are on their own. When importing all of the movies, I see they all get jammed into one group.

I'd normally change the skin and do some advanced sorting, but considering you warn people not to do that, since the best usage is with the default skin I'm wondering if there's any way of doing this splitting?

I also have my TV shows sorted like that, but due to how Kodi works they all get merged together unless I export everything via NFO, change the name, then re-import them which I'm pretty sure isn't possible to do with PKC.

**Comment by croneter** [comment]
Here's the solution, you need to use a skin where you can customize your widgets to point to each movie category individually: https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins
