### ISSUE TITLE
PKC doesn't work with latest Kodi Nexus Nightly

### ISSUE THREAD

**Issue by bokkoman** [croneter/PlexKodiConnect#1892]
## Describe the bug
After installing latest Nexus nightly (12/27), PKC doesn't work. Tells me to look at the forums. 

## Expected behavior
To have a working PKC :-)

**Comment by croneter** [comment]
@bokkoman On principal, don't use the nightly, use the release candidate. Too much breaks still on the Kodi (and not PlexKodiConnect) side of things.

Having said that, share a DEBUG log file and I might be able to help you, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by bokkoman** [comment]
> @bokkoman On principal, don't use the nightly, use the release candidate. Too much breaks still on the Kodi (and not PlexKodiConnect) side of things.
> 
> Having said that, share a DEBUG log file and I might be able to help you, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Yeah, i just noticed that Kodi had messed up their nightlies. Soon after i updated they changed the folders/added folders to their nightly directory.
Apparently I downloaded the Omega alpha build (v21.0 Alpha).
So totally my fault (or maybe 50% my fault xD).
Now i have to uninstall Omega and install Nexus again. 

If you're still interested in a log for Omega, let me know, then I'll grab it, so you can perhaps make it compatible with Omega.

**Comment by bokkoman** [comment]
Just went through the logs.
It doesn't pass the version check, since it was 21.0.

**Comment by croneter** [comment]
No I am not interested in Omega - too early, too much stuff breaks.
