### ISSUE TITLE
PKC 3.7 not syncing Plex Server database on latest Kodi Nexus

### ISSUE THREAD

**Issue by krl691** [croneter/PlexKodiConnect#1902]
Installed PKC 3.7 beta on Kodi Nexus RC2. If there are changes like new episodes or deleted series etc in Plex Server, Kodi is not syncing with PKC from Plex server. Tested by deleting from Plex like episodes, series, movies etc. but they appear as "ghosts" in PKC. I¨m getting an error message in Kodi that e.g. the episode no longer exists and then asks if I want to delete it. I tried to uninstall the PKC, selected YES to delete all data from Kodi but it didn’t help. The problem dos not occur in Kodi Matrix 19.5

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/10338588/kodi.log)

**Comment by croneter** [comment]
I don't see anything of interest in the log file. Could you please replicate an issue - delete an item on the PMS or add one? Be sure to enable debug logging and have Kodi up and running when doing that.

**Comment by krl691** [comment]
> I don't see anything of interest in the log file. Could you please replicate an issue - delete an item on the PMS or add one? Be sure to enable debug logging and have Kodi up and running when doing that.

I did a clean install with the latest Nexus build and the PKC 3.7. Now everything is in order so I leave it there. Something with my config and update from Matrix, was messing with your addon. Just close this thread.
