### ISSUE TITLE
Plex Home Managed Users: background sync does not work

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#191]
Use case: Plex managed user (non-master user) in use leads to Plex websockets not working (Plex does not allow Managed Users to open websocket connections). 

This prevents the background sync mechanism from working

**Comment by croneter** [comment]
Feature request pending with Plex: http://forums.plex.tv/discussion/255727/open-plex-websockets-for-managed-users

**Comment by pannal** [comment]
What's the state of this?

**Comment by Borgcustom** [comment]
I'm looking for an update on this also.  This one issue prevents me from using PKC.

**Comment by croneter** [comment]
Please bring this up with the Plex team!

**Comment by croneter** [comment]
Please try **BETA** version 2.12.0, that should solve your issue. If not, please let me know here.
