### ISSUE TITLE
Movie Set sync issue

### ISSUE THREAD

**Issue by mash2k3** [croneter/PlexKodiConnect#1912]
If a movie is part of a set and 1 or more collections in Plex that movie wont show up in the Sets section of Kodi under its movie collection folder.
But it does show up in its collection folder of same name under Tags

**Comment by croneter** [comment]
Nothing I can do - on the Kodi side of things, a movie can be part of at most 1 set, sorry 😔

**Comment by mash2k3** [comment]
oh i get it, thanks atleast i know how to fix it. ill remove it from other set.

**Comment by mash2k3** [comment]
> Nothing I can do - on the Kodi side of things, a movie can be part of at most 1 set, sorry 😔

is there a way in plexkodiconnect where you can choose which collections to export and not?

**Comment by croneter** [comment]
No there is not
