### ISSUE TITLE
Movies won't start on Remote Connection

### ISSUE THREAD

**Issue by MadzDK** [croneter/PlexKodiConnect#192]
Hi 
Movies won't start when the connection is remote, Tv shows work fine !?!
IF it run on Local network it works flawless.

Tested: 
Freshly installed Libreelec 7.95.1. with PKC 1.5.8 Local network everything works
Freshly installed Libreelec 7.95.1. with PKC 1.5.8 Remote Tv show works but not Movies. 

i have attached the log from the remote test.

[01_KODI.zip](https://github.com/croneter/PlexKodiConnect/files/734654/01_KODI.zip)

**Comment by croneter** [comment]
The log says that you don't have access to that particular Plex video item

* Have you tried resetting the Kodi DB via PKC settings -> Advanced -> `Reset the Kodi DB...` (in red), then YES, YES, NO?
* Does your Plex user have access to that specific movie library?
* Have you tried switching the Plex user? (via Video -> Video Add-ons -> PlexKodiConnect -> `Log-out user XYZ`)
* You edited your Plex tokens (rightly so!!). If all above fails, could you check whether you have several different tokens in use or only one?

**Comment by croneter** [comment]
Also, your remote PMS was repeatedly not reachable
```
20:12:14.757 T:140101396293376   ERROR: CCurlFile::Exists - Failed: Couldn't connect to server(7) for https://0-0-0-0.6427f06286514fb5888b1c70e886ab30.plex.direct:32400/library/metadata/9621/thumb/1450966251?X-Plex-Token=XXXXXXXXXXXXXXXXX
```
Is the connection stable? Can you connect and play movies using e.g. Android or iOS?

**Comment by croneter** [comment]
Closing this issue as PKC needs a stable network connection to work

**Comment by MadzDK** [comment]
I will make a new log later today.
Yes the user have access to the movie folder, if i test with the "plex for kodi preview" plugin it works.
i edit 2 tokens "out" 
the connection failure you see is when i change network from a mobile hotsport to local lan to access the log file but a make a new one without the network shift. 
the new log i will start a tv show and try to start a movie.

**Comment by croneter** [comment]
Please also start a working TV show in the same log

**Comment by croneter** [comment]
Could you replace the tokens in a way that I can distinguish the 2 different tokens from each other? E.g. <TOKEN1> and <TOKEN2>

**Comment by MadzDK** [comment]
So Freshly installed Libreelec 7.95.1. with PKC 1.5.8 login and let it sync and wait 10 min. to let it settle.
Reboot and wait 1 min. first started 1 movie (not starting) and then 2 different tv shows (starting and working) and at last 2 different movies (not stating)

the 2 tokens is UserA and UserB


[01_KODI.txt](https://github.com/croneter/PlexKodiConnect/files/736796/01_KODI.txt)

**Comment by croneter** [comment]
Is this still an issue with latest beta 1.5.11?

**Comment by MadzDK** [comment]
Yes still not working :( 
tested with the new 7.95.2 and 1.5.11
[01_KODI.txt](https://github.com/croneter/PlexKodiConnect/files/750586/01_KODI.txt)

**Comment by croneter** [comment]
I cannot replicate your issue, which makes it really difficult to solve :-(
* Does it work if you change the Plex user?
* If you use another client, e.g. Plex for Android, does it work for movies if you're remotely connecting AND using the same user (for which it didn't work)?

**Comment by croneter** [comment]
There is no difference between movies and TV shows for PKC - so I'm really sceptic here... You can connect, everything works, but then if you try to play, the PMS tells you that you're not allowed:
```
13:11:32.327 T:139923236407424   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://0-0-0-0.6427f06286514fb5888b1c70e886ab30.plex.direct:32400/library/parts/101266/1485591847/file.mkv?X-Plex-Platform=Linux&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=Kodi+%28LibreELEC%29&X-Plex-Provides=client%2Ccontroller%2Cplayer&X-Plex-Token=UserB&X-Plex-Client-Identifier=2897d52e-ca7c-44be-91fc-d3a0961e2d42&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=1.5.11
13:11:32.354 T:139923236407424  NOTICE: VideoPlayer: Opening: https://0-0-0-0.6427f06286514fb5888b1c70e886ab30.plex.direct:32400/library/parts/101266/1485591847/file.mkv?X-Plex-Platform=Linux&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=Kodi+%28LibreELEC%29&X-Plex-Provides=client%2Ccontroller%2Cplayer&X-Plex-Token=UserB&X-Plex-Client-Identifier=2897d52e-ca7c-44be-91fc-d3a0961e2d42&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=1.5.11
13:11:32.354 T:139923236407424 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
13:11:33.043 T:139923236407424   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://0-0-0-0.6427f06286514fb5888b1c70e886ab30.plex.direct:32400/library/parts/101266/1485591847/file.mkv?X-Plex-Platform=Linux&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=Kodi+%28LibreELEC%29&X-Plex-Provides=client%2Ccontroller%2Cplayer&X-Plex-Token=UserB&X-Plex-Client-Identifier=2897d52e-ca7c-44be-91fc-d3a0961e2d42&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=1.5.11
13:11:33.553 T:139920706369280   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 400
13:11:33.553 T:139920706369280   ERROR: CCurlFile::Open failed with code 400 for https://0-0-0-0.6427f06286514fb5888b1c70e886ab30.plex.direct:32400/library/parts/101266/1485591847/file.mkv?X-Plex-Platform=Linux&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=Kodi+%28LibreELEC%29&X-Plex-Provides=client%2Ccontroller%2Cplayer&X-Plex-Token=UserB&X-Plex-Client-Identifier=2897d52e-ca7c-44be-91fc-d3a0961e2d42&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=1.5.11
```
Did you try the usual, e.g.:
* Restarted the PMS
* Update the movie library manually (the "wheel" if you are within the movie library using your browser to access the PMS), then restart the PMS

**Comment by MadzDK** [comment]
If i first try to start a movie on Remote connection it failed, if i then change the network to local and in the setting "Choose Plex Server from a list" and select the same PMS but now as a local and then start the same movie it works. i can upload a log of that if you would like to see it ?

**Comment by croneter** [comment]
Not no, thanks. 

Please answer the all the other questions

**Comment by MadzDK** [comment]
>Does it work if you change the Plex user?

The same not working

> If you use another client, e.g. Plex for Android, does it work for movies if you're remotely connecting AND using the same user (for which it didn't work)?

I have "Plex for iOS" and it works, "the web player" works and the "plex for kodi" works.

> Restarted the PMS

The PMS get restarted every day as it shutdown at night 

> Update the movie library manually (the "wheel" if you are within the movie library using your browser to access the PMS), then restart the PMS

Did that test but, didn't help.

took my mac now with the final kodi 17 and the new 1.5.12 but still the same :( 

[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/752293/kodi.txt)

**Comment by croneter** [comment]
What if you don't use the kodi widget, but navigate to your kodi movie view. Then use the context menu to queue a movie. Then queue another one. Then go to the kodi Playlist view (navigate "out of the screen in the movie view until an" option bar" pops up. Then choose Playlist. Can you start a movie there?

**Comment by MadzDK** [comment]
If i do that i get a Playback failed message and it remove the movie from the playlist

**Comment by croneter** [comment]
I'm still thinking it's a network issue. Your last log contains lines like this:
```
ERROR: CCurlFile::Exists - Failed: Timeout was reached(28) for https://0-0-0-0.6427f06286514fb5888b1c70e886ab30.plex.direct:32400/library/metadata/29085/art/1486192353?X-Plex-Token=UserA
CCurlFile::Stat - Failed: Couldn't resolve host name(6) for https://0-0-0-0.6427f06286514fb5888b1c70e886ab30.plex.direct:32400/library/metadata/5342/thumb/1486199029?X-Plex-Token=UserA
```
Do you have friends that try to access your PMS from outside your local LAN that could test this? Or could you add my user as a friend so I could test?

**Comment by croneter** [comment]
Any progress on this? Still an issue?

**Comment by MadzDK** [comment]
Hi 
tested / tried almost every combo also at my family that use this plug-in but it is the same.

Every other client i have tested, works with remote connection.  

the funny thing is that it have work flawless for a long time but suddenly it stoped. 

but i can now see a new PMS version is out with some network fixes, i will now test it again.

**Comment by croneter** [comment]
Any news on this issue?

**Comment by MadzDK** [comment]
Hi still the same :/ so i have told my family to use a chromecast, or another client.  Fill free to close it. i will let u know if it start working again. keep up the good job.

**Comment by croneter** [comment]
Alternatively, you could grant me access to your Plex home so I could test. Up to you ;-). 

This is really a mystery. 

Have you tried forcing transcoding in the PKC Settings under playback?

**Comment by MadzDK** [comment]
Hi tested a litte bit more, when selecting "force transcode" it works :) but not with direct play or direct stream !?  shift to local network and direct play and direct stream works again.

**Comment by croneter** [comment]
Then you were probably forcing kodi to play a high Bitrate file through a crappy Internet connection...

**Comment by croneter** [comment]
Or, and this is more likely, Plex streaming brain was active and kept you from streaming outside the house
