### ISSUE TITLE
Entering watched state crashes Kodi Matrix

### ISSUE THREAD

**Issue by InvisibleKnight** [croneter/PlexKodiConnect#1920]
I'm having a dual-path issue that leads to regular crashes.

The issue was described [HERE](https://github.com/croneter/PlexKodiConnect/discussions/1838) in the discussion section and somehow resolved by OP. I have no idea how.

I have the same issue on two completely different kodi boxes (one is ARM based and the other is x86, different OS as well) and strange enough the crash happens in Jellyfin as well so it might stem from how kodi itself handles multiple paths? Is my only option to assign just a single folder per library?

**Comment by croneter** [comment]
Pinged to original poster in the discussion https://github.com/croneter/PlexKodiConnect/discussions/1838 to kindly share his config.
