### ISSUE TITLE
Ratings keeps adding to the rating table in kodi on repair

### ISSUE THREAD

**Issue by JCalvi** [croneter/PlexKodiConnect#1928]
Running a repair on PKC adds all the ratings again to the kodi rating table db.

I will sort a fix for this and combine with closing #1911 at the same time.

**Comment by croneter** [comment]
Thanks! But please split this in 2 different pull requests

**Comment by JCalvi** [comment]
Will do.

**Comment by JCalvi** [comment]
Well I tried, the ratings adding changes wouldn't let me raise a separate pull request, they would only try and merge with #1927

All code is tested and verified working, hopefully you can sort it out from here.

**Comment by croneter** [comment]
Fixed in PKC beta version 3.7.3
