### ISSUE TITLE
Database locked

### ISSUE THREAD

**Issue by furrnace** [croneter/PlexKodiConnect#1929]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

I did all this. Is there something I can do to get it back in  working state?

## Describe the bug
Kodi display an error notification that the PlexKodi "Database is locked"

## To Reproduce
1. just wait for a while, or
2. go to Settings > Repair Kodi Database
3. the sync will run through Movies, TV Shows, Seasons and Episodes and then freeze at 78% (Kodi still responds, but not further progress on the sync)
4. at the point Kodi will display an error notification that the PlexKodi "Database is locked"

## Expected behavior
I never had this error notification before. After updating to PKC 3.7.1 it happened several times.

## You need to attach a KODI LOG FILE!
cannot do right now, need to be back at the device for that.

**Comment by JCalvi** [comment]
Try moving your myvideosxxx.db file to a temp folder so a new one is made.
Where xxx = 119 or 121 depending on what version of kodi you are running.
If you are plexing music do the same for that as well.
Also move the plex.db and plex-copy.db files as well.

Do all this with kodi shutdown, then start kodi again.

**Comment by croneter** [comment]
Otherwise, there's no help possible without a log file, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by furrnace** [comment]
Thanks I will give it a shot.

**Comment by croneter** [comment]
Closing this until we get your logs, @furrnace. No logs, no help possible.
