### ISSUE TITLE
Pictures are not syncing

### ISSUE THREAD

**Issue by Borgcustom** [croneter/PlexKodiConnect#193]
I am not seeing any pictures in my pictures library.  PKC does not appear to even attempt to sync my photos from Plex into Kodi.  I know there is a RAW photo issue, but my photos are a mixed bag of RAW and jpg, I figured I should see at least some of them sync.

**Comment by croneter** [comment]
Pictures do not get synced. Do you see your pictures library and its items?

**Comment by Borgcustom** [comment]
No, I don't see the library or items. If I go into the pictures section, it's empty.

**Comment by croneter** [comment]
Navigate to Video - Add-ons - PlexKodiConnect. Then the name of your
picture library

Am 28.01.2017 16:20 schrieb "Borgcustom" <notifications@github.com>:

> No, I don't see the library or items. If I go into the pictures section,
> it's empty.
>
> Sent from my iPhone.
>
