### ISSUE TITLE
New Feature:  Skip Ads

### ISSUE THREAD

**Issue by waltonbruce** [croneter/PlexKodiConnect#1938]
On other Plex players (e.g. android or web-based), when a video is played which has been recorded by the Plex DVR with commercial detection enabled, a "Skip Ads" button is presented at the appropriate time.   The user may then select to have the player jump to the next commercial marker.

Is there a way for PKC to detect this scenario and mimic the behavior?

Thank you for your consideration.

**Comment by croneter** [comment]
As I don't use Plex DVR, I need your help here. Using Plex Web, could you please navigate to a recording that you know contains ads that can be skipped. Then grab its XML metadata, see section `XML Information / XML File` [the official Plex help](https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/). Thanks!

**Comment by waltonbruce** [comment]
Here is such an example!    Thanks for looking.

[showmetadata.txt](https://github.com/croneter/PlexKodiConnect/files/10952735/showmetadata.txt)

**Comment by croneter** [comment]
Implemented in PKC beta version 3.7.6

**Comment by waltonbruce** [comment]
Good morning,  tried out the BETA repo,  getting this error on playback.
thx

------

<2023-03-20 02:18:58.489 T:127992   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the 

following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'commercial'
                                                   Traceback (most recent call last):
                                                     File "/home/bruce/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 8,
 in <module>
                                                       service_entry.start()
                                                     File "/home/bruce/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/servic
e_entry.py", line 592, in start
                                                       Service().ServiceEntryPoint()
                                                     File "/home/bruce/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/servic
e_entry.py", line 564, in ServiceEntryPoint
                                                       skip_plex_markers.check()
                                                     File "/home/bruce/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/skip_p
lex_markers.py", line 54, in check
                                                       skip_markers(markers)
                                                     File "/home/bruce/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/skip_p
lex_markers.py", line 35, in skip_markers
                                                       marker_message=MARKERS[typus],
                                                   KeyError: 'commercial'
                                                   -->End of Python script error report<--
>

**Comment by waltonbruce** [comment]
Ah, just a typo  in skip_plex_markers.py on line 12. 
Should be "commercial" to match the XML token.

Please could you fix it, my git skill is a little rusty these days.

thx again

**Comment by waltonbruce** [comment]
Tested working.   Thank you!
