### ISSUE TITLE
Need Guidance - Direct Paths

### ISSUE THREAD

**Issue by FlyWheel998** [croneter/PlexKodiConnect#1945]
Goal: Setting up Direct Paths for External Audio Tracks
Tech: plexkodiconnect on my Nvidia Shield, Plex server is from my Windows PC (I have installed SMB)

Current State: plexkodiconnect on my Nvidia Shield and the Kodi file browser can pick up my files, I can play anything, except its not picking up external audio tracks (video + external audio file in the same folder, same filename)

When I click on “Set network credentials for Direct Paths and direct play”, it asks me what my IP is, so I go to Plex → Remote Access → write in “Private IP” except port, then I type in “smb”, then my Windows Username + Password, I click Ok, nothing happens, no change, doesnt pick up any external audio tracks.

Where do I enter in the direct paths for all my videos?

I saw this comment, but where do I actually enter in all my paths for my content - (also is it nfs or smb) https://www.reddit.com/r/kodi/comments/11rkmg0/need_guidance_on_plexkodiconnect_direct_paths_for/jcdsrud/

Please assist, thank you! Please correct any steps if I am doing it wrong, thanks!

**Comment by croneter** [comment]
See https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths please. No help for configurations here otherwise, sorry, otherwise I wouldn't do anything else, unfortunately 😢
