### ISSUE TITLE
Didn't Play trailer on DialogVideoinfo

### ISSUE THREAD

**Issue by kmfly** [croneter/PlexKodiConnect#1948]
I think I remember you answered somewhere with a similar problem.For the record, I am a plexpass user and I have plexpass enabled in the PKC addon.Also, trailers play fine in plex.When I installed PKC, I left the path to plex as default (addon path).

Anyway, my problem is that when I don't use PKC and normally select a movie and go into info via the context menu and play the trailer, it plays fine.

But when I go through the same route with PKC, it won't play.

As I recall, the PKC add-on has some kind of logic to play the trailer supported by kodi if there is no trailer provided by plex, but it doesn't seem to work.

I'm currently using kodi 20.0/default skin, but it seems to be the same problem in previous versions.

I would like to fix this, is there any way to do it?

**Comment by croneter** [comment]
I don't understand your issue. What exactly is not working? Do you want to play a trailer (that exists on the Plex side of things!) But this does not work with Kodi and PKC?

Please be more specific

**Comment by kmfly** [comment]
Sorry for the confusion.

Without PKC - it plays the trailer correctly. No issue
With PKC - it can not play a trailer.

Use Kodi default skin - Estuary and play the trailer by entering info via the context menu and pressing the play trailer button.

**Comment by croneter** [comment]
That's still not enough information, sorry. 
- With PKC: if you use Plex Web to go to the movie in question: do you have a trailer or not?
- Without PKC: where does your trailer come from exactly?

**Comment by kmfly** [comment]
For your question

- With PKC: if you use Plex Web to go to the movie in question: do you have a trailer or not?
Yes, it has. Please see below my capture video(3).

- Without PKC: where does your trailer come from exactly?
It comes from youtube(1), I think it is the default in Kodi default skin. Please also see below my capture video.

I have created a captured video for each case.

https://drive.google.com/drive/folders/1ZTFGCOWytD9eOjKXY8yesAg3_MpBRvSY

you can find 3 video files in my google drive link. it is shared.
After a clean install Kodi 20.0
(1)kodi_native_trailer-ok.mp4 -> just add my library and play a trailer - it is okay
(2)pkc_trailer_ng.mp4 -> after plexkodiconnect install, it can not play a trailer
(3)plex_web_trailer_ok.mp4 -> above 2 case movie, it has a trailer in plex and can play.

**Comment by croneter** [comment]
Try resetting the Kodi database in the PKC settings, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by kmfly** [comment]
I tried "PKC Settings -> Advanced -> "Partial or Full Reset of Database and PKC" and set it again but it has the same.
I tried to get kodi.log (attached, also changed X-Plex-Token=THISISMYTOKEN in the log)
Would you please look at my log regarding plexkodiconnect?

My Suggestion:
If possible, if the trailer fails to play on PKC, as shown in my video capture "kodi_native_trailer-ok.mp4" above, could you please add a function to play it on youtube like it does on Kodi default skin?

The log file captures when I select a movie, choose info from the context menu, enter "DialogVideoInfo.xml" in kodi, and click the trailer button.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/11013005/kodi.log)

**Comment by croneter** [comment]
What happens if you use the context menu on a movie with a Plex trailer, then go to the PlexKodiConnect context menu, then hit "Extras"? Your trailers and potentially more stuff should be listed. Can you start a trailer from there?

**Comment by croneter** [comment]
Aha, found something in your log file:
```
...
info <general>: PLEX.playback_decision: The playurl for DirectPlay is: https://146-56-136-73.b6920615c43f4177b3096997f2dd3150.plex.direct:32400http://146.56.136.73:9999/metadata/normal/stream?mode=kakao&param=381667605&Accept=%2A%2F%2A&Content-Type=application%2Fx-www-form-urlencoded&Accept-Language=en&X-Plex-Device=Windows&X-Plex-Model=10&X-Plex-Device-Name=Kodi+LAPTOP-85AIV18V&X-Plex-Platform=Generic&X-Plex-Platform-Version=1.0.0&X-Plex-Product=PlexKodiConnect&X-Plex-Version=3.7.1&X-Plex-Client-Identifier=1759588d-b15b-4e4b-9ca2-7cb3aa8e4f33&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Protocol=1.0&Cache-Control=no-cache&X-Plex-Token=THISISMYTOKEN
...
info <general>: VideoPlayer::OpenFile: plugin://plugin.video.plexkodiconnect.movies/?plex_id=20439&plex_type=clip&mode=play
error <general>: CCurlFile::XFILE::CCurlFile::Stat - <https://146-56-136-73.b6920615c43f4177b3096997f2dd3150.plex.direct:32400http://146.56.136.73:9999/metadata/normal/stream?mode=kakao&param=381667605&Accept=%2A%2F%2A&Content-Type=application%2Fx-www-form-urlencoded&Accept-Language=en&X-Plex-Device=Windows&X-Plex-Model=10&X-Plex-Device-Name=Kodi+LAPTOP-85AIV18V&X-Plex-Platform=Generic&X-Plex-Platform-Version=1.0.0&X-Plex-Product=PlexKodiConnect&X-Plex-Version=3.7.1&X-Plex-Client-Identifier=1759588d-b15b-4e4b-9ca2-7cb3aa8e4f33&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Protocol=1.0&Cache-Control=no-cache&X-Plex-Token=THISISMYTOKEN> Failed: URL using bad/illegal format or missing URL(3)
...
```
Especially the part `Failed: URL using bad/illegal format or missing URL(3)` and the URL that PKC returns, which is completely wrong (2x "HTTPS://"): `https://146-56-136-73.b6920615c43f4177b3096997f2dd3150.plex.direct:32400http://146.56.136.73:9999/metadata/normal/stream?mode=kakao&param=381667605&Accept=%2A%2F%2A&Content-Type=application%2Fx-www-form-urlencoded&Accept-Language=en&X-Plex-Device=Windows&X-Plex-Model=10&X-Plex-Device-Name=Kodi+LAPTOP-85AIV18V&X-Plex-Platform=Generic&X-Plex-Platform-Version=1.0.0&X-Plex-Product=PlexKodiConnect&X-Plex-Version=3.7.1&X-Plex-Client-Identifier=1759588d-b15b-4e4b-9ca2-7cb3aa8e4f33&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Protocol=1.0&Cache-Control=no-cache&X-Plex-Token=THISISMYTOKEN
`

- Please enable Kodi DEBUG logging and try again to play a trailer, then share your log file again. See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug
- From the movie where you tried to play the trailer, kindly share the movie's XML metadata info. See "XML Information / XML File" here: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/

**Comment by croneter** [comment]
No logs, no help possible @kmfly, sorry. I'm still waiting for your answer
