### ISSUE TITLE
No external sub via direct path (webdav)

### ISSUE THREAD

**Issue by cvcodeminer** [croneter/PlexKodiConnect#1958]
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Basic info
PMS platform: Windows
Playback device: Android with Kodi v20.0 (Nexus)
Webdav info: located in Android device.
Direct path method: [Option 1: Substitute Paths using PKC](https://github.com/croneter/PlexKodiConnect/wiki/Option-1-Substitute-Paths-using-PKC)

Media file naming as below
Video.ext
Video.zh.ext

All files are asscessble via Kodi file manager, playback was fine via file manager or add-on playback mode, but for some reason, I'd swiched to direct path mode.

## Describe the bug
Even though PKC pulls metadata from Plex with external subtitle for the media, when I start to play the movie or any episode with direct path mode, it doesn't show any external sub for me to select.

### Kodi file manager view
![aaf4cea06da74b34cf2e774e07b5edb](https://user-images.githubusercontent.com/126143707/226998136-b1a71bbb-9151-487a-8529-e45625220165.jpg)

### Playback with Kodi file manager
![2d7140f324978aee066420f34f95a81](https://user-images.githubusercontent.com/126143707/226998479-7a670ec0-bf70-41eb-85af-ecd066c80fc7.jpg)

### PKC view
![image](https://user-images.githubusercontent.com/126143707/226998999-b9afa1cc-2109-4633-b9c3-9059ff887c16.png)

### Playback with PKC via direct path mode
![image](https://user-images.githubusercontent.com/126143707/226999243-05511e47-1e94-4d11-a5a7-bfc8d741f7c6.png)

## Kodi Log file

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/11043206/kodi.log)

Main error info: GetDirectory - Unable to process dav directory (dav://USERNAME:PASSWORD@127.0.0.1:5244/)

**Comment by cvcodeminer** [comment]
Hi,  I was wondering if you have look into this, and by the way, I noticed external sub are being well recognized by plex also sync via PKC to KODI database but when I play the video, external sub shows as unknown sub. (add-on mode)

**Comment by croneter** [comment]
I need the entire DEBUG log file for starters. Please enable Debug logging. Then playback using the Kodi file manager. Then playback using PKC.

**Comment by croneter** [comment]
Your [Direct Paths](https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths-Explained) need to be set-up and working correctly, otherwise external subs won't work.

**Comment by cvcodeminer** [comment]
it's escaping the special charater cause this problem, I leave only few special charater after test and everything works fine, I would close this issue, many thanks
