### ISSUE TITLE
Kodi (17) crashing if Artwork settings are activated

### ISSUE THREAD

**Issue by nexusle** [croneter/PlexKodiConnect#196]
Kodi is crashing, if artwork settings are activated. I think it's since 1.5.9. Have deactivated both sliders and Kodi doesn't crash. CPU usage is very high with activated settings. Tested in Intel Atom with Libreelec beta.

**Comment by croneter** [comment]
PKC had a version hickup yesterday if you were unlucky. Did you try to reset PKC via PKC settings -> Advanced -> Full or partial reset of Database (in red), then Yes, Yes, No?

If that does not help: Log? See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by nexusle** [comment]
Had only reset Kodi's database as dialog was displayed on startup. Will have a look as I use 1.5.9 or 1.5.10. 

Thanks for the answer.

**Comment by croneter** [comment]
1.5.11 as of rrrright now :-)

**Comment by croneter** [comment]
Still an issue?

**Comment by nexusle** [comment]
Sorry for the delay. No issue so far with latest version. Thanks

**Comment by croneter** [comment]
OK, thanks. Just reopen this issue otherwise
