### ISSUE TITLE
option to disable the new "skip credits"

### ISSUE THREAD

**Issue by kobeegh** [croneter/PlexKodiConnect#1961]
The "skip intro" function can be disabled in the PKC settings.
It would be nice if there was also an option for function "skip credits" to be deactivated if wanted by the user.

background: when credits are detected and the button for skipping credits is displayed, it's not possible anymore to skip forward or backwards within the credits (tried using keyboard with arrow an ,/.-keys)

**Comment by croneter** [comment]
That's not true, you can still skip. As soon as the "Skip Credits" button shows up, use the "back" button and the button will disappear
