### ISSUE TITLE
Playing plexkodiconnect library through Seren

### ISSUE THREAD

**Issue by MrMeatballSub** [croneter/PlexKodiConnect#1962]
Sorry, this isn't really a bug but more of a question.  I was hoping you could answer as I'm not sure where else to post to get in touch with the dev.

Is it possible to use pkc with seren to play local content before seren scrapes providers?

I tried doing this with TMDB Helper, but that addon asks me to set the path for the local library, and I'm not sure where to point to for my plex library.

Plex Composite is having issues for me so I am looking for a different way for seren to scrape for my plex content.

Any help is appreciated.

**Comment by croneter** [comment]
I have no idea. Just try? 😉
