### ISSUE TITLE
Some episodes now showing up on the tv show section? 

### ISSUE THREAD

**Issue by Fma15** [croneter/PlexKodiConnect#1963]
I have 3 unwatched episodes of a show. When I go to the show those 3 episode don't show up. One of the episodes shows up in the on deck section. Normally in the on deck section I can click and hold on an episode and it'll bring up a list of options including an option to see all of the episodes of the tv show season. This show doesn't have that option though.

The show works in the official plex app and in composite, so it's not a problem with plex itself.

**Comment by Fma15** [comment]
Incase anyone is wondering, I fixed this by downgrading from kodi 20.1 to kodi 19.3

**Comment by croneter** [comment]
Should be fixed in [3.8.1 for Kodi Matrix and beyond](https://github.com/croneter/PlexKodiConnect/releases/tag/3.8.1). You might need to reset the Kodi database in the PKC settings under Advanced.
