### ISSUE TITLE
HDR/DV/HLG tags not available in Plex Hubs of plexkodiconnect

### ISSUE THREAD

**Issue by thorindwarf** [croneter/PlexKodiConnect#1965]
Hi,
I'm using Arctic Horizon 2 and the skin reads the new tags and based on them displays codec icons in the Furniture section.
Browsing Plex hubs through plexkodiconnect they are not showed in any of the hubs e.g. Continue watching.

**Comment by croneter** [comment]
Can you please elaborate? How are you navigating exactly when this occurs? What is NOT showing? Are tags showing otherwise?

**Comment by thorindwarf** [comment]
Yes, they are showing when browsing in Kodi's library but not through Add-ons->Video addons->plexkodiconnect->Plex Hub->Continue Watching (e.g.).
As far as I remember fron Arctic Horizon 2's forum thread, this skin uses the new HDR tags (sorry if terminology is wrong) introduced in Nexus and not relying on filename to determine if it's HDR based on existence of e.g. 'HDR' string inside it.

Kodi's library -> Movies:
![2023-04-06 19_29_18-Kodi](https://user-images.githubusercontent.com/9911154/230440338-eb922ad8-22fc-4ac2-894b-30c67083639a.png)

plexkodiconnect's Continue Watching hub:
![2023-04-06 19_23_24-Kodi](https://user-images.githubusercontent.com/9911154/230440451-e1a7d550-b794-462a-8e23-9f74de0c60cc.png)

**Comment by thorindwarf** [comment]
I hope this helps somehow:
https://forum.kodi.tv/showthread.php?tid=367352&pid=3147994#pid3147994
