### ISSUE TITLE
Neverending intial sync - NAS being "stucked"

### ISSUE THREAD

**Issue by D4rkCrew** [croneter/PlexKodiConnect#1967]
## Help yourself
* I did try to restart Kodi :-)
My setup Synology NAS - Plex Media Server - PlexKodiConnect - Kodi - Nvidia shield was working without problems for several years, till I decided to update NAS OS and Kodi
Clean install and I also to did the same on my PC to replicate the issue

* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
Yes

* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
Yes, clean install

* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)
Yes

## Describe the bug
After initial sync my NAS keeps running at 100% even after Kodi is shut down
Not able to stop it as it is busy at 100%, so I am not able to open any NAS folders or get to the menu to restart NAS or Plex Media App
The only way how to stop NAS is via a power cable

## To Reproduce

Everything was working fine for years till I decided to do a clean install
Updated NAS OS
Installed Plex Media Server on my Synology NAS
Set new Permissions for PlexMediaServer (System internal user) to custom (Full Control)
Run Plex Media Server and let it sync (a few minutes)
Tested Plex via web browser and everything is working fine
Updated Kodi from 19.1 to 19.5
Installed PlexKodiConnect via wiki
Set IP and credentials to my NAS during PlexKodiConnect setup (SMB)
Set direct paths (NFS)
Restart Kodi
Run Kodi
Link Plex and set sync to all my folders (around 700 episodes and maybe 150 films)
Sync started
Sync finished fine
Till now everything is w/o problems
After Sync my NAS is still 100% busy (the hard drive running at 100%)
Kept it synced for 8 hours (overnight) did not help still running
It never ends

I am trying to solve it for almost 10 hours, no idea what is happening.
I also tried those steps on my PC instead of Nvidia Shield (primary device), same issue.

## Expected behavior
Finish sync and NAS remain idle

## You need to attach a KODI LOG FILE!
A Kodi debug log file is needed that you recorded while you reproduced the bug. **Do clean your log of all Plex tokens (="Plex passwords")!!!** .
1. Activate Kodi's debug logging by going to the Kodi `Settings` -> `System` -> `Logging`. Then toggle the `Enable debug logging` setting.
2. Restart Kodi to start with a "fresh" log file.
3. Reproduce the bug.
4. Follow the [Kodi instructions](http://kodi.wiki/view/Log_file/Easy) to grab/share the Kodi log file. Usually only `kodi.log` is needed
    * You can [find the log file here](http://kodi.wiki/view/Log_file/Advanced#Location)
5. **Delete all references to any of your Plex tokens** by searching for `X-Plex-Token` and `accesstoken` and replacing the strings just after that!
    * It's easiest if you copy your token, then use Search&Replace for the entire log file
    * You don't want others to have access to your Plex installation....
6. Drop your log file here in this issue. Or use a free pasting-service like https://pastebin.com and include the link to it here
    
I am aware that I can delete Plex tokens that I accidentially posted by following the [instructions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server)

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/11148496/kodi.log)

**Comment by croneter** [comment]
Sorry @D4rkCrew, your Plex token leaked. Please immediately follow [I published my Plex token to some forum or Github. Anyone can now access my Plex Server!](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server)

**Comment by croneter** [comment]
You got many of these errors in your log file:
```
...
WARNING <general>: PLEX.download: Server unreachable at: https://192-168-1-210.979120cab9d84e1fbc9f5b44f877ef92.plex.direct:32400/library/metadata/2313?checkFiles=0&includeExtras=1&includeReviews=1&includeRelated=0&skipRefresh=1&includeMarkers=1
WARNING <general>: PLEX.download: HTTPSConnectionPool(host='192-168-1-210.979120cab9d84e1fbc9f5b44f877ef92.plex.direct', port=32400): Max retries exceeded with url: /library/metadata/2313?checkFiles=0&includeExtras=1&includeReviews=1&includeRelated=0&skipRefresh=1&includeMarkers=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='192-168-1-210.979120cab9d84e1fbc9f5b44f877ef92.plex.direct', port=32400): Read timed out. (read timeout=30.0)"))
...
```
This means that some kind of firewall is in between your PlexKodiConnect and the Plex Media Server. PKC scrapes all the PMS' metadata during its initial sync - the firewall thinks (mistakenly) that PKC should not do that. 

Nothing I could do from the PKC side, sorry... 😞
