### ISSUE TITLE
Bug: Screensaver not toggling back on after library sync

### ISSUE THREAD

**Issue by axsys** [croneter/PlexKodiConnect#197]
Hello,

I have been having an issue with Kodi for a while and I believe I have narrowed it down to PlexKodiConnect. It seems that when PKC is syncing, it will disable the screensaver while running it's sync and then re-enable it when done. My issue is that sometimes it does not turn it back on. Unfortunately I don't have the log file of this exact moment (with Kodi running 24x7 you can imagine it is hard to track every PKC sync), but I have attached a log file nonetheless (that contains the toggling of the screensaver as well as it activating).

I have tried resetting PKC as well as using one of the standard screensavers. The issue happens about once a week.

If a bug cannot be determined, it is possible to disable the toggling of the screensaver during sync?

Other info: Kodi 17RC2 (I've had this issue since 16), W10 x64, PKC 1.5.1, 24x7 uptime with daily restarts

[kodi.log.txt](https://github.com/croneter/PlexKodiConnect/files/749032/kodi.log.txt)

**Comment by jordanade** [comment]
I continue to have this problem in version 1.8.0. Every once in a while I discover that my screensaver has been disabled.

**Comment by jordanade** [comment]
If PKC is unsetting the screensaver during sync, it might just be a matter of Kodi crashing or my machine restarting for some other reason during a sync.

**Comment by croneter** [comment]
Could you try and get a log of this issue actually happening? I'm always interested in any crashes 😉

**Comment by xenophobentx** [comment]
Actually i'm having the same one. Most likely it is connected to the emby roots:
https://emby.media/community/index.php?/topic/40992-emby-disables-kodi-screensaver/

https://forum.kodi.tv/showthread.php?tid=295124

**Comment by Damme** [comment]
Im annoyed by this too, but the typo in emby is not found in plexkodiconnect.
https://github.com/MediaBrowser/plugin.video.emby/commit/fd3c21d6c8eaf0b14cb1913087613e83950042ef

any ideas why screensaver gets disabled?

**Comment by croneter** [comment]
Should hopefully be fixed with the next PKC beta version and https://github.com/croneter/PlexKodiConnect/commit/74bed60c32577b5c296e372740c0ea2b674d195e

**Comment by croneter** [comment]
Should be fixed with new PKC version 2.0.4. Let me know here if this should not be the case.
