### ISSUE TITLE
Anyway to make pkc start when kodi opens? 

### ISSUE THREAD

**Issue by Fma15** [croneter/PlexKodiConnect#1971]
I only use pkc in kodi. I was using party mode auto start to automatically take me to the on deck section of pkc whenever I open kodi. I'm not sure why, but now party mode auto start takes 35 seconds to open the on deck section, which is really annoying. So is it possible to have a feature in the settings of pkc that can take you automatically to a section of pkc right when you open up kodi?

**Comment by croneter** [comment]
You need to use a "better" Kodi skin and customize its widgets - choose PKC On Deck as a widget. See https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins
