### ISSUE TITLE
Feature:Get filepath or filename of multiple version video from PMS for Direct path

### ISSUE THREAD

**Issue by cvcodeminer** [croneter/PlexKodiConnect#1974]
I'm currently using direct path, it works fine except it can't deal with multiple version movie/episode.

I need to split dulipcated video with Plex Meta Manager also marks the diffrences between them (it does not take much time but 2 or more same video lies in my library are not cool, check below pic), and it only display one version if you don't split it.

![image](https://user-images.githubusercontent.com/126143707/235421923-76658309-d017-48f8-b9aa-3be2d74cb98a.png)

here's scenario and what I expected when this feature implemented (hopefully you would take this suggest?)

Pops up a multiple version selection windows just like add-on mode and play under direct path mode (perhaps you could get the filepath and replace your own path which replace feature already implemented)

And in case not everyone need this feature, could provide a setting option to enable, because need go through PMS everytime you play the video for getting those info you need.

thanks for paying your attention to this issue and let me know whether this could join your to-do list or not. many thanks.

**Comment by croneter** [comment]
Here's how to deal with multiple versions on the Plex side of things (as Kodi does NOT support multiple versions of a video natively!):
- Do it "normally" on the Plex side - so make sure you have only 1 movie with several version
- In Kodi: use the context menu ("c"), then Plex Settings, then "Play via PMS". PlexKodiConnect will notice that several versions are present and present you with a menu to pick one.

**Comment by cvcodeminer** [comment]
Ah, it did play from my webdav, I thought I saw it play from PMS the other day, my bad. thanks for the instructions.

By the way, would you consider add one extra setting option for direct path? Always check with PMS are much more convenience.

**Comment by croneter** [comment]
That's impossible, unfortunately, due to the way Kodi works

**Comment by cvcodeminer** [comment]
That's a bummer, but you're doing great! thanks again!

**Comment by cvcodeminer** [comment]
Hey, it's me again! Turns out, PKC does support always check with PMS when using Direct paths.

All I do is keep the addon playback mode instead of switch it to direct paths as [Option 1: Substitute Paths using PKC](https://github.com/croneter/PlexKodiConnect/wiki/Option-1-Substitute-Paths-using-PKC) told me to

~~5. In the PKC Settings under Sync Options, switch Playback Mode to the setting Native (Direct Paths)~~

Reset the Kodi database after that and now everything works perfectly, mulitple version would pops up a window for me to select, external audio/subtitles are also tested. and most important thing is it still play via direct paths!

**Comment by croneter** [comment]
In other words: you're using Addon Paths 😆. Nice that this works out for you.

Btw
- PKC will indeed still use "direct paths" for playback if you set the Path Replacements correctly. (playing file will have a path like NFS://server/video.mkv
- Some Kodi addons might not work as expected (rare), because for add-ons, the video paths will look funny (Addon://plugin.video.plexkodiconnect...)
