### ISSUE TITLE
Repository not working?

### ISSUE THREAD

**Issue by ac3nl** [croneter/PlexKodiConnect#1975]
I can’t connect to the repo any more.
Also my version went back to 3.7.0 when i was on 3.8.1

managed to update to 3.8.1 manually, but through repo would be easier.

**Comment by croneter** [comment]
Nope, should be fine. Try again please.

**Comment by ac3nl** [comment]
Could not connect to rep….. kodi saysOp 8 mei 2023 om 10:17 heeft croneter ***@***.***> het volgende geschreven:﻿
Nope, should be fine. Try again please.

**Comment by croneter** [comment]
Are you starting with a fresh Kodi install?

Did you follow https://github.com/croneter/PlexKodiConnect/wiki/Install-PKC-Repository?

**Comment by ac3nl** [comment]
No, i used the 1.0.2 link from the github pageOp 9 mei 2023 om 11:31 heeft croneter ***@***.***> het volgende geschreven:﻿
Are you starting with a fresh Kodi install?
Did you follow https://github.com/croneter/PlexKodiConnect/wiki/Install-PKC-Repository?

**Comment by croneter** [comment]
Please remove the repo (so remove the Kodi-Addon for the PKC repo). Then follow these steps exactly:  https://github.com/croneter/PlexKodiConnect/wiki/Install-PKC-Repository

**Comment by ac3nl** [comment]
FixedPlease not thatcroneter/PlexKodiConnect: Plex integration in Kodi done rightgithub.comUnder downloads is an old repo-link  that doesn’t work anymoreThat was the one i was usingOp 9 mei 2023 om 17:45 heeft croneter ***@***.***> het volgende geschreven:﻿
Please remove the repo (so remove the Kodi-Addon for the PKC repo). Then follow these steps exactly:  https://github.com/croneter/PlexKodiConnect/wiki/Install-PKC-Repository
