### ISSUE TITLE
TV show artwork doesn't update as expected

### ISSUE THREAD

**Issue by Rocknol** [croneter/PlexKodiConnect#1980]
## Describe the bug
Hello, first of all thanks for the hard work.
So I've had this issue for as long as I can remember. I'm using the PlexKodiConnect add-on path, with basically two Plex libraries: movies and TV shows. When I change movie artwork from Plex(poster or fanart), the same movie is updated on Kodi with the artwork I chose on Plex, within a few seconds. Perfect then. However when I try to do the same thing with TV shows, it's not updated before the scheduled sync, or when I manually sync from PKC options.

## To Reproduce
1. Change some tv show artwork on Plex
2. Wait for Kodi to show the update

## Expected behavior
TV show artwork on Kodi should update right away just like movie artwork does.

I was surprised that I didn't find this issue posted anywhere. Is it known or only on my end?
I'll include a log file if needed.

**Comment by Rocknol** [comment]
I'm still experiencing this issue. It's the only little problem I have with PKC, otherwise everything is great.
Having to go into PKC settings and manually sync the library every time I want to change a TV artwork is a bit annoying.
Thanks.
[kodi.log](https://github.com/user-attachments/files/16648340/kodi.log)

**Comment by croneter** [comment]
Unfortunately, there's literally nothing PKC could do as Plex does not mark items as "changed" - hence there's no way for PKC to pick up this change except re-building the database entirely from scratch :disappointed:

**Comment by Eagle1337** [comment]
> I'm still experiencing this issue. It's the only little problem I have with PKC, otherwise everything is great. Having to go into PKC settings and manually sync the library every time I want to change a TV artwork is a bit annoying. Thanks. [kodi.log](https://github.com/user-attachments/files/16648340/kodi.log)


Hey croneter I know that you closed this but. 
Rock, I find that mine do typically update their artwork. I'm not sure if it's due to me analysing the episodes/series or when kometa does certain runs, but it may be worth trying analysing the episodes, seasons, and series in plex and see if that helps.

**Comment by croneter** [comment]
@Eagle1337 you or Plex do something else that marks the show as changed. Voilà, PKC Updates the show. There's nothing I can do, unfortunately

**Comment by Eagle1337** [comment]
> @Eagle1337 you or Plex do something else that marks the show as changed. Voilà, PKC Updates the show. There's nothing I can do, unfortunately

Yeah, I just wanted to tell the dude above a way to update things without doing a db refresh
