### ISSUE TITLE
Manual Library Sync crashes Shield

### ISSUE THREAD

**Issue by somerandomuser1** [croneter/PlexKodiConnect#1982]
When trying to do a "Manual Library Sync" it does a "sync" in the top right corner like its supposed to, shows 0%, then instantly crashes and does nothing. After that I have to unplug my ShieldPro (2019) and plug it back in as it is now completely locked up. The only time the Library sync functioned correctly was on the first setup. This is a brand new Kodi install (20.1) using Nexus Stable PKC, no other addons or changes have been made at all. I accidently hit "clean library" not realizing what it would do and now I need to resync but it wont do it.

**Comment by somerandomuser1** [comment]
I solved my library issue by setting the Timing for Auto Sync to 1 minute, this seems to be the only way to sync the library....Manual Sync does not work.

Also just tried Manually forcing the Image Cache...it does nothing...a quick check at the bottom of the Artwork section in settings shows that neither Fanart nor PMS caching has been completed. Several Restarts and re-attempts.

**Comment by croneter** [comment]
I need your Kodi DEBUG (!!) log file to be able to do anything, please see here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
No log file, no help possible
