### ISSUE TITLE
Kodi Crashes when trying to run Artwork Beef Script on PKC items

### ISSUE THREAD

**Issue by stereotypeuk** [croneter/PlexKodiConnect#1983]
## Describe the bug
As the title says. I had been using Artwork Beef to supplement PKC for clearlogos that don't pull from Fanart correctly.

This was working under Kodi 19.5 with AuraMod skin using latest PKC and a [Python 3 compatible fork of Artwork Beef ](https://github.com/henryjfry/repository.thenewdiamond/blob/main/zips/script.artwork.beef/script.artwork.beef-0.28.7.zip)(RMRector has since abandoned active development in favour of artwork dump, and using native Kodi Artwork scraping; however this doesn't give you the option to add missing or incorrect art entries)

Now using Kodi 20.2 and latest PKC with Arctic Horizon 2 skin, any time I try to action any kind of scrape by Artwork Beef, Kodi outright crashes.
 
I'm using PKC with direct smb paths, which is why I assume this was working for me previously. The changed variables here are the Kodi (& presumably Python) version and the skin.

I would get it if it was simply a Python error; however, if i set up an smb share in Kodi to the same folder on my network that PKC references, then Artwork Beef still runs just fine.

All things considered, it seems to be something about the communication between Artwork Beef & PKC?

## To Reproduce
1. Go to any title handled by PKC
2. Open Context Menu
3. Click Manage -> AB: Select Artwork

## Expected behavior
Kodi crash.

## You need to attach a KODI LOG FILE!
https://paste.kodi.tv/atozapibud.kodi

**Comment by croneter** [comment]
I think Artwork Beef is not really maintained anymore..? I found https://github.com/rmrector/script.artwork.beef with last update 4 years ago. Thus closing
