### ISSUE TITLE
Ability to disable skip credit function

### ISSUE THREAD

**Issue by joeio** [croneter/PlexKodiConnect#1985]
The new "skip credit" function is interfering with the Up Next add-on in my setup.

Could we please have it as an on/off option in settings like we do for "skip intro"?

Thanks!

**Comment by S1llyG1t** [comment]
Definitely think there should be option for both in the settings.

I'd like to tack on also perhaps the ability to cancel/clear the prompt when it shows up. Sometimes it seems that it is not synced correctly for some content. e.g. Skip button either doesn't show up right away or shows up later or not at all. There are those times that when especially if it shows up later after the opening credits have already shown, I just want the skip button to go away, but there's no way to clear it. Selecting it will advance you, skipping over parts of the show you're watching.

**Comment by croneter** [comment]
@S1llyG1t you CAN already cancel/clear the prompt: simply hit return on the remote and the skip credits stuff should go away

**Comment by croneter** [comment]
Implemented by @Spacetech with PKC version 3.8.7 (beta only)
