### ISSUE TITLE
PKC forced a reset and then wiped my library

### ISSUE THREAD

**Issue by djl0327** [croneter/PlexKodiConnect#1991]
Not sure if anybody else is having this issue but I have noticed that every so often I would get a notification in Kodi that PKC needed a reset.  I would typically click ok and be done with it since nothing would happen.  However, this time I got the notification and it forced a relink prompt where I would have to go to the Plex link page to enter the special code, after which the PKC add-on behaves as if I'm in the initial setup procedure.  That's fine I guess but when it comes time to get into the settings window all I get is a blank screen where I can't do anything, and if I back out it just resets my entire Kodi library back to 0.  I've tried exiting Kodi and going back in but it just brings me back to the beginning of the reset process where I have to relink again.  PKC was working normal until Sunday night, is there something being worked on with the add-on?

**Comment by jfeldhamer** [comment]
i have the same issue i have to uninstall the plugin and reinstall and redo all settings again
getting frustrating as it keeps happening

**Comment by djl0327** [comment]
I was able to get it working again by doing a full uninstall of PKC and delete of the settings, and then reinstalling.  Kind of a pain though since I had to start from scratch again but whatever it just takes a while to redownload all of the fanart.
This issue is now closed.
