### ISSUE TITLE
Http instead of smb direct paths

### ISSUE THREAD

**Issue by doomwithdon** [croneter/PlexKodiConnect#1993]
Is there a way I can use webdav/http links instead of smb paths for direct path mappings?

**Comment by KyleSanderson** [comment]
yes

**Comment by doomwithdon** [comment]
I tried just placing the http url in the direct path settings but that didn't work. Is there anything specific to be done?

**Comment by KyleSanderson** [comment]
customize paths:
- replace UNC
- replace Plex paths /vol or \\myserver
- make sure original and "replace" match correctly.
- escape special characters.

playback:
- Try Direct Path

all of this needs to be done before you import the data, otherwise you need to start fresh.

**Comment by doomwithdon** [comment]
Tried exactly that. Ended up with a blank library. Path mappings are as follows:
Plex mount: /mnt/cloud
Replaced by : http://abcxyz.com:1234
Both paths point to same directory listings and yet it ends up with a blank library

**Comment by doomwithdon** [comment]
Bump..Anyone have any suggestions? from the looks of it only smb protocol is supported by direct paths

**Comment by geropan** [comment]
@doomwithdon have a look at this:
https://github.com/croneter/PlexKodiConnect/pull/1184
I think the colon (:) to indicate the port is not being escaped.

**Comment by doomwithdon** [comment]
So i played around with escaping special characters and now my TV Shows get synced correctly with http direct paths but my Movies section turns out blank. The mappings for both sections are exactly the same so I am just tearing my hair out at the moment.

**Comment by doomwithdon** [comment]
Got it working by playing around with the escape characters option and changing my domain. Not sure what exactly fixed it but now I dont have any issues. Thanks!

**Comment by doomwithdon** [comment]
Got it working by playing around with the escape characters option and changing my domain. Not sure what exactly fixed it but now I dont have any issues. Thanks!
