### ISSUE TITLE
Spinning wheel/Screen Refeshing every 5 seconds

### ISSUE THREAD

**Issue by slydog3333** [croneter/PlexKodiConnect#1997]
So I've started having an issue where the screen is either refreshing or I get a spinning wheel every 5 seconds depending on what screen I'm on. 
It happens on two different devices. 
I've tried resetting the database.
I also just uninstalled pkc and deleted all kodi video and tv show databases then reinstalled but the problem shows up again.
Disabling backround sync fixes the issue.
I can attach the kodi log if needed but I think I found the important lines where it's getting hung up trying to update a show every 5 seconds on the background sync:

2023-10-07 13:59:58.490 T:25853   debug <general>: PLEX.sync.websocket: Processing new/updated PMS item: 88647
2023-10-07 13:59:58.506 T:25853    info <general>: PLEX.tvshows: UPDATE episode plex_id: 88647 - Episode 8

Is there something to be done to fix this with PKC?

If not is there a way to decode plex_id: 88647 to know what show it is so I can maybe delete it?

**Comment by loadamasta** [comment]
I can confirm the issue on Apple TV 4K on Kodi 19 as well as on 21 Beta 1. Disabling background sync solves the issue. Any solution or update to fix the issue?

**Comment by slydog3333** [comment]
@loadamasta It seems there hasn't been any development on this addon since April. There is another Plex addon I found that is actively being redeveloped : https://github.com/pannal/plex-for-kodi

It doesn't work the same though. Instead of taking over the Kodi database, instead it opens a plexlike addon in Kodi. I find it useful for opening other Plex servers I use but still prefer the Kodi navigation this addon provides for my main server

**Comment by loadamasta** [comment]
> @loadamasta It seems there hasn't been any development on this addon since April. There is another Plex addon I found that is actively being redeveloped : https://github.com/pannal/plex-for-kodi
> 
> It doesn't work the same though. Instead of taking over the Kodi database, instead it opens a plexlike addon in Kodi. I find it useful for opening other Plex servers I use but still prefer the Kodi navigation this addon provides for my main server

Thank you for the tip. I will give it a try.

**Comment by croneter** [comment]
Back in the business guys. But I need a complete DEBUG log file to fix this, please follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by slydog3333** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/13998944/kodi.log)

Luckily I saved the log from back then since I just enabled background sync and it's not doing it now. Maybe that episode has been deleted since then. Speaking of which is there a way to decode what episode the plex id is pointing to?

**Comment by croneter** [comment]
Thanks for the log file!

So you haven't experienced this issue the last couple of weeks or so, @slydog3333 ?

Yes, there's a way to get to the episode from the plex id. I guess the easiest is to use Plex: follow https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/ to "view XML". Then simply replace the "plex_id" in the URL and you get the episode's XML

**Comment by slydog3333** [comment]
Thanks for the plex id info. I figured out what episode it is and it is still in my library.

So I disabled background sync back in October and haven't had the issue since. I just re-enabled background sync today and so far no issues. I even tried stopping that episode halfway so it would have to update and it seems its good for now.  Not sure what caused it back then but I'll keep an eye out and get a new log if it happens again.

There is one other issue I've run into which I should probably start a new issue for. If I start browsing file manager before the initial startup sync starts and if I get a spinning circle while a folder is being opened and at the same time the sync starts Kodi locks up with the spinning circle. I've learned to just wait till the sync is done before I go into file manager. I'm not sure if a log would help on that since its more like an IRQ conflict it seems, but if I get that consistent enough again I'll try and get a log to open up an issue on that.

**Comment by croneter** [comment]
Ok thanks!

**Comment by slydog3333** [comment]
So last week I had to uninstall and reinstall PKC due to a database issue and after the initial scan the problem came back, but after restarting Kodi it went away until today. It's now back and relentless without turning off background sync.

It appears to be that same problem episode as before.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/14074524/kodi.log)

@croneter

**Comment by Spacetech** [comment]
I'm seeing similar behavior after changing to a different skin - screen flashing due to library updates every so often.

I debugged it a bit.

Whenever users click through shows, episodes, movies, etc, on your server in Plex Web, Plex sends activity events to a WebSocket. Plex attempts to refresh some data for the item when viewing them. Here is an example of the websocket event that fires after clicking a movie:

![2024-02-27_17-48-28](https://github.com/croneter/PlexKodiConnect/assets/824323/e7597b06-4283-4680-8cb8-ce18508f89ce)

PKC is triggering Kodi library updates when that happens. The logic for processing the websocket message is [here](https://github.com/croneter/PlexKodiConnect/blob/cd3bf2ce0d7524c3d359f8e7254e8bcd9266ce84/resources/lib/library_sync/websocket.py#L205). 

The interesting thing about the message is that it says `refreshed: false` at the bottom. Should PKC ignore the message when Plex indicates that nothing was refreshed?
