### ISSUE TITLE
Kodi Omega Android TV - everything is broken

### ISSUE THREAD

**Issue by waltonbruce** [croneter/PlexKodiConnect#2000]
Kodi Omega is hitting the Android TVs now.  Suddenly breaks all things PKC.   Spouse annoyed.

A.  library fails to update new items
B. nothing plays, all playback fails
C.  clearing and rebuilding DB does not help, (in fact pulls in Music lib!)
D.  does not work to uninstall/reinstall over new clean Kodi Omega

Will there be an Omega PKC repo released soon?

thx

**Comment by Fma15** [comment]
It seems to work fine for me on a Nvidia Shield?

**Comment by waltonbruce** [comment]
For my Shield, it started with not getting newly added content to the video libs after updating to Kodi 21.  (android just does this without your permission and with no way to back out)

In trying to fix this, got it more broken.   Tried a fresh install, new everything, tear kodi down and install new from scratch.   The message is:

"The current Kodi version is not supported by PKC.  Please consult the Plex Forum."

**Comment by Fma15** [comment]
To fix that error you need to edit the variables.py file. It's pretty easy to do. This will show you how to do it

[https://github.com/croneter/PlexKodiConnect/issues/1988](url)

Also, you should be able to get back to Kodi 20. You can only get Kodi 21 on the shield if you joined the beta for Kodi on the play store. If you want to continue to use Kodi 20 just leave the beta program. Then you can uninstall Kodi and reinstall Kodi 20.

**Comment by waltonbruce** [comment]
Ah, thank you for the hints.    Easy to edit a file on a linux/windows/mac host but the easiest way on a shield is what, now?   Where's emacs?  LOL

Honestly I had forgotten that I was on that beta program...  I will go bail out and wait for proper release channels.

thanks again
