### ISSUE TITLE
Why do trailers do this?

### ISSUE THREAD

**Issue by gregeeh** [croneter/PlexKodiConnect#2009]
Hello Everyone,

I have CE 20.2 (Nexus) on an Odroid N2 along with PKC.

When I watch trailers via PKC they look like this, with the rectangle:

https://i.imgur.com/vL11bOn.png

Viewing YT normally there is no rectangle.

Any idea why PKC is different?

TIA

**Comment by croneter** [comment]
No idea. PlexKodiConnect is NOT responsible for doing anything at all with video, it's all Kodi (or - very unlikely - Plex). PKC only tells Kodi what video to play, that's it. Sorry, can't help you....

**Comment by gregeeh** [comment]
> No idea. PlexKodiConnect is NOT responsible for doing anything at all with video, it's all Kodi (or - very unlikely - Plex). PKC only tells Kodi what video to play, that's it. Sorry, can't help you....

This does not happen with PM4K (plex4kodi fork) with the same versions of Kodi and YT.  Also tried with the Kodi Plex Client and it did not happen.  Seems odd that it's only PKC.
