### ISSUE TITLE
Błąd w Omega (MyVideos129)

### ISSUE THREAD

**Issue by Romik2505** [croneter/PlexKodiConnect#2023]
Since the January 4 kodi omega v21 release and the MyVideos128 database, everything was still fine, but in the next nightly release with the MyVideos129 database, everything went wrong. The Plex update is only going well in series, but no longer movies are appearing. Is there a chance to improve this problem. It's good to test the nightly release, but if there's no library, it's poor.

**Comment by croneter** [comment]
Absolutely no support for any Kodi nightly releases, sorry. More often then not, something breaks on the Kodi side of things. Use official beta releases please.

**Comment by Romik2505** [comment]
In Omega beta 3, movies are also not displayed. TV shows, on the other hand, work.
