### ISSUE TITLE
[Feature Request] Plex Labels to Kodi Tags

### ISSUE THREAD

**Issue by kingkearney** [croneter/PlexKodiConnect#2042]
Importing Plex Labels to Kodi Tags.

I'm a heavy user of Plex Labels and it would work well with kodi tags, I use just over 200 Netflix style genres as plex labels and if they were to be imported into Kodi as tags then my plex media would fit in nicely with my custom viewing experience created by 'Library Node Editor'.

My version of Netflix.....

MyFlix

😁

**Comment by cj0r** [comment]
Second this; I heavily rely on Plex-Meta-Manager for my  Plex organizing which utilizes labels to build Collections. Some of my Collections cleanly come over via PlexKodiConnect, but most do not.

Would be nice if PlexKodiConnect could interpret Plex's labels as Kodi tags or sets
