### ISSUE TITLE
files from different libraries shown under movies library

### ISSUE THREAD

**Issue by Sunset-1982** [croneter/PlexKodiConnect#2043]
Hey!

I have an issue or maybe I am just missing something...

I have several libraries (movies, series, demo videos, private videos, aso...) within the plex webinterface those libraries are separated. Within kodi (with pkc addon) all video files from the demo videos and private videos libraries are also shown under movies. Is there a setting where I can impede this? I don't want the demos and private videos to be shown under my movie collection...

same problem with the continue watching widget. The private videos are also shown under this tab. 

Is this a missing plex feature or just a pkc issue?

**Comment by croneter** [comment]
PKC supports this, but you need to make sure that you're using a Kodi skin that will enable you to split different movie libraries as well. See here for more info: https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins

**Comment by Sunset-1982** [comment]
ok thanks! That was very helpful! works good.

one last question: Is it possible to create more of those plex widgets? I would like to have one for 4k movies or Dolby vision movies.

**Comment by croneter** [comment]
Naturally, but you need to check with the Kodi skin you're using whether that's possible and how to do it. Not PKC 😉
