### ISSUE TITLE
PlexKodiconnect plex video nodes arent showing on kodi

### ISSUE THREAD

**Issue by crosshuntr74** [croneter/PlexKodiConnect#2064]
i just finished installing plexkodiconnect today on kodi 20.5 (nexus) so i have a problem with it that i have been troubleshooting all day long sadly with no solution.
now pkc synced correctly all my library from plex but it didnt feed into the kodi library if i see the movies tab for example in kodi its empty and tells me i need to add a source , same thing for tv shows library.
but i go into the PKC addon i can see the plex hub and everything is neatly organized.
If i understood correctly plexkodiconnect should feed those plex data into kodi library which now it didnt and i dont know why .
i tried destroying the database and rebuilding it , resetting everything from the settings but even that didnt work i would 
to be more specific Plex media nodes didnt get created inside kodi as per the screenshot attached.

appreciate the help !

i have attached pictures of the issue (forgive the bad pictures :D ) and a log file with debugging enabled.

![435625182_736777811969730_6788084940438695697_n](https://github.com/croneter/PlexKodiConnect/assets/50407185/8519a2de-714c-47c1-80f3-0407cda03fa4)
![435432237_880376337111529_7684057837276506371_n](https://github.com/croneter/PlexKodiConnect/assets/50407185/e5e2be53-34f0-46ce-ba51-9a648dde89ef)
![422118622_1104082477541698_8151143662426534877_n](https://github.com/croneter/PlexKodiConnect/assets/50407185/18e79dbd-5355-4176-a0b4-02e2ae5a5830)

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/14934884/kodi.log)

**Comment by croneter** [comment]
Hmmm, seems to me like you did something wrong setting up PKC. Go into the PKC settings, Advanced, then reset the Kodi DB and optionally PKC (in red). Reset EVERYTHING even the addon settings. When setting PKC up again, make sure to "not deselect" your libraries when asked which libraries you want to sync. Default is all of them. Do not setup direct paths either, just use default add-on paths. 

If it still doesn't work, share a DEBUG log file of the initial sync, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Jupp: you deselected every library when asked whether to sync :wink:

**Comment by crosshuntr74** [comment]
> Jupp: you deselected every library when asked whether to sync 😉

you were right and now it works ! thanks croneter much appreciated !
