### ISSUE TITLE
[Feature] Add Direct Mode similar to Infuse 7.7.

### ISSUE THREAD

**Issue by vegedb** [croneter/PlexKodiConnect#2079]
For context, https://firecore.com/blog/infuse-77-direct-mode ,

PlexKodiConnect currently only loads/sync between server>local database, this is incredibly slow compared to Plex Native App.
There should be a "direct mode" which mimics (Plex Native App/web browser interface) that infuse had introduced in their 7.7 update.

Do take a look and see if its possible.

**Comment by croneter** [comment]
There are upsides to the synching, e.g. "Kodi-native" speeds when browsing a large movie library. I'm never going to implement this. 

Plus: you can have a similar experience by deactivating the synching of every single Plex library. Then navigate to Video Add-ons -> PlexKodiConnect -> Name of your library. It'll still work even though you haven't synched.

**Comment by vegedb** [comment]
> There are upsides to the synching, e.g. "Kodi-native" speeds when browsing a large movie library. I'm never going to implement this.

It only syncs what's needed on "direct mode" using infuse. 
Its **exactly** like using plex on the Web Browser. 
Native Plex Apps also does not cache everything like PlexKodiConnect which bogs down everything, not seemless like the native app.

> Plus: you can have a similar experience by deactivating the synching of every single Plex library. Then navigate to Video Add-ons -> PlexKodiConnect -> Name of your library. It'll still work even though you haven't synched.

This is NOT the solution as newly added stuff will not be refreshed at all.
