### ISSUE TITLE
AttributeError: 'str' object has no attribute 'double_urldecode' my background sync breaks

### ISSUE THREAD

**Issue by freemind96** [croneter/PlexKodiConnect#2088]
my background sync breaks after 2 min or under 12 hours .... why??

error: 'str' object has no attribute 'double_urldecode'

have a rpi5 with libreelec on it. 
it doesn't matter which I use stable or beta. same error again and again. 3.10.1 for Kodi Matrix and beyond.

last time I remember it worked without errors was with libreelec 9.2.8 
[plexkodiconnect.txt](https://github.com/user-attachments/files/15743056/plexkodiconnect.txt)

**Comment by croneter** [comment]
Thanks for the report, should be an easy fix

**Comment by freemind96** [comment]
I'm really happy to hear that :D

**Comment by croneter** [comment]
Fixed in PKC version 3.10.2

**Comment by freemind96** [comment]
I thank you
