### ISSUE TITLE
Libreelec 13, Kodi 21.0 RC and PKC

### ISSUE THREAD

**Issue by jassi0001** [croneter/PlexKodiConnect#2098]
Hi, 
i just compiled my own Libreelec 13 Beta. Whenever i install PKC 3.10.3 i get the info, that my Version of Kodi is not Supported. I understood that the Version 3.10.3 should work with that version. Am i wrong?

Thanks Stefan

**Comment by croneter** [comment]
Seems like something is off with your build. Kodi Omega is supported by PKC. Please share your DEBUG log file: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by jassi0001** [comment]
[kodi.log](https://github.com/user-attachments/files/16319140/kodi.log)

here you are... seems the Version is coming with Kodi 22.0-Alpha1.

**Comment by croneter** [comment]
No official Alpha support yet for PKC - this breaks SO many things from the Kodi side. 

If you're willing to hack: https://github.com/croneter/PlexKodiConnect/pull/1940/files add a "22" there in the list.

**Comment by croneter** [comment]
No support for Alpha-versions
