### ISSUE TITLE
Any chance to get ComSkip feature?

### ISSUE THREAD

**Issue by nexusle** [croneter/PlexKodiConnect#210]
Hi croneter,

I doesn't know how to make this possible. In Kodi there is a ComSkip feature for TV commercials in video files from TV recordings. Could you please have a look how to enable it in relationship with PKC?

**Comment by croneter** [comment]
A "ComSkip" feature is far, far off of what PKC is actually doing. This needs to be either solved on the Plex or on the Kodi side. Sorry...

**Comment by nexusle** [comment]
Kodi can handle ComSkip. As I understand it, a text file is placed in the movie folder with time indicies. This timers will be skipped at playback of the video file. Just wanted to know, if this works with PKC.

**Comment by nexusle** [comment]
example text file contents for 'The Matrix' (The Matrix.txt):

FILE PROCESSING COMPLETE
-------------------------------
12645     17792
28578     34549
43114     48222

Kodi now display's "Comercial" and skips the frame index listed in the file. 
Had tested this with a movie folder not handled by PKC. The skipping works. Than had tested this with the same movie now handled by PKC. The comercial dialog appears, but it doesn't skip. 

Thats why I asked.

**Comment by nexusle** [comment]
Source: http://kodi.wiki/view/Edit_decision_list

**Comment by croneter** [comment]
Did you setup [PKC direct paths](https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths)? That way, Kodi/this ComSkip addon (??) might be able to find the file you left next to the movie file

**Comment by nexusle** [comment]
Yes. Because I use Plex Music. It seems the file is found. Get the Commercial dialog with the duration of the commercial, but skipping doesn't work as with native video source in Kodi.

**Comment by nexusle** [comment]
There is no ComSkip addon. Kodi itself can handle this (see link above)

**Comment by nexusle** [comment]
Hi croneter,

could you had a look at this thing? Such a comskip file is fast created. Just input some frame steps and look, what happen. In my case, only if I add the movie network shares manually the skipping works right after the Commercial message is displayed. With PKC I only get the Commercial message displayed.
