### ISSUE TITLE
Feature request: add additional remote plexmediaserver

### ISSUE THREAD

**Issue by iz3man** [croneter/PlexKodiConnect#2107]
I use plexkodiconnect for several years now, and it's been running great. 2 coreelec clients access my plex server in the basement. Now I want to watch movies from a friend's plex server, which is easily possible in plex directly, or from the webapp.
But there is no way to add a second library through plexmediaserver with plexkodiconnect.
Is there any way to acchive that?

Thanks in advance

**Comment by croneter** [comment]
Sorry, there will never be a "tight" integration of several Plex Media Servers with Kodi. There are workarounds, however. See e.g. https://github.com/croneter/PlexKodiConnect/discussions/1280

**Comment by iz3man** [comment]
Sorry. My fault. Seems like a workable solution. Thank you. 😊
