### ISSUE TITLE
Video state not set to watched in Plex after playback

### ISSUE THREAD

**Issue by hugues999** [croneter/PlexKodiConnect#2110]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
After watching a complete video, playback status is not set to Watched in Plex, despite having stopped it beyond 90%. It even reset to unplayed instead of having some progress.

## To Reproduce
1. Start any video
2. Skip ahead with up or right arrow until you reach the credits (> 90% progress), but not so far as to stop the video automatically
3. Don't skip the credits
4. Stop the video (press x)
5. Go to the Plex web app. Playback status of the episode/movie is unplayed, and there is no playback progress either.

I can reproduce with these steps almost every time, and it happens naturally while watching full episodes most of the time.
I also tried with play mode set to Addon instead of DirectPath just in case, and same behavior.

## Expected behavior
Video should be marked as watched if you stop at over 90% of the timeline, or at the very least have its progress saved.

## You need to attach a KODI LOG FILE!
https://pastebin.com/hTCRA452
    
I am aware that I can delete Plex tokens that I accidentially posted by following the [instructions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server)

**Comment by croneter** [comment]
Sorry that it took so long to get back to you @hugues999  😞 . The log is not around anymore on pastebin.com. Can you please upload a new one directly here on GitHub?

I'll close the issue as long as the log file is missing. Otherwise I have no chance of fixing this

**Comment by hugues999** [comment]
> Sorry that it took so long to get back to you @hugues999 😞 . The log is not around anymore on pastebin.com. Can you please upload a new one directly here on GitHub?
> 
> I'll close the issue as long as the log file is missing. Otherwise I have no chance of fixing this

Thanks for the followup. Unfortunately I don't have it anymore and I've been using Jellyfin recently instead. I'll re-open an issue if I encounter it in the future.
