### ISSUE TITLE
can't play anything from PKC Music

### ISSUE THREAD

**Issue by TimFH** [croneter/PlexKodiConnect#2117]
As described briefly on my replys on PKC's "Discussions" posting #2116, after a first-time installation under OSMC, PKC can't play any music using either the PAPlayer or the VideoPlayer (only the latter reports an error; the former just fails silently). I presume PKC also wouldn't be able to play any videos either, but I'm holding off setting up those libraries until I know PKC is working. At first I thought the problem might be that I hadn't installed Samba on PKC, but fixing that doesn't seem to have changed anything.

[kodi.log](https://github.com/user-attachments/files/17266763/kodi.log)

**Comment by TimFH** [comment]
And now it seems (manual) syncing isn't working any more either; I don't know why, but the log file indicates PKC is trying to treat `media' (as in /media, where osmc automounts volumes) as a host rather than a path component (?). Here's the log file: 
[kodi.log](https://github.com/user-attachments/files/17267623/kodi.log)
At this point I don't know what to do but try a full reset of the PKC and the Kodi database, but hopefully someone else has a better idea.

**Comment by TimFH** [comment]
Perhaps this has something to do with it: when I try to follow the instructions in https://kodi.wiki/view/SMB by going to Settings -> Services -> SMB Client, I see no option (under Kodi Omega) to "Browse for new share." So I haven't been able to do that.

**Comment by croneter** [comment]
Sorry, but get our PKC set-up correctly: do NOT use any "Customize Path" settings in the PKC settings if Kodi is on the same machine as your Plex Media Server. 

Also PKC's focus is clearly on VIDEOS, not music...
