### ISSUE TITLE
Limited storage for syncing

### ISSUE THREAD

**Issue by mccabedd** [croneter/PlexKodiConnect#2120]
I have limited storage on my Android TV box, and have a lot of media on my NAS.

After an hour of adding PKC to Kodi, it had scraped over 1GB of data to local storage, causing low memory alerts.

Is there any way to prevent PKC from copying all thumbnails, backgrounds artwork etc.. locally, whilst retaining functions like 'Watched Status'? or is there anything I can do to prevent the local storage from filling up?

**Comment by croneter** [comment]
Yes: go into the PKC settings, then Artwork, then deactivate `Cache all artwork for a smooth Kodi experience`

Be warned though that Kodi itself will be caching stuff. Your 1 GB seems excessively low 😉
