### ISSUE TITLE
Indicate several versions of a media file visually 

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#218]
Is there the possibility to display an indicator on the poster art to let you know that there is more than one version available? Native Plex apps show a badge with a number in it.

**Comment by croneter** [comment]
@im85288, this is really not my domain, maybe you know more? :-)

**Comment by croneter** [comment]
Now on feathub.com: http://feathub.com/croneter/PlexKodiConnect/+5
