### ISSUE TITLE
Fresh install - worked once, times out after that

### ISSUE THREAD

**Issue by Xaelias** [croneter/PlexKodiConnect#219]
Hey!

So I just setup a new NAS (Synology) and installed Plex on it.
Tonight, I tried to setup PKC and it worked the first time. But then I stopped to install subtitles addons, and PKC cannot connect to my PMS since then.

I tried with and without signing in to plex.tv, I did a clean install 3 times (removed the Kodi folder in AppData/Roaming/), but still...

I tried to restart the NAS, restart the plex server... Nothing changed.

Thanks for the help!

[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/762609/kodi.txt)

[EDIT] I can connect to the server via windows, my browser, or the plex app on my phone. So I don't think the issue is the PMS itself.

[EDIT2] Using Kodi 17

**Comment by croneter** [comment]
* Do other Plex clients work? 
* can you see your PMS if you go to the PKC settings, Connection then hit choose your PMS from a list?

**Comment by croneter** [comment]
Can you find the server if you go to Videos, Add source? (do NOT add a source ;-)

**Comment by Xaelias** [comment]
Hey!

Well what do you know, without doing anything it worked again this morning... I hope it stays that way and I only lost 3 hours of my life yesterday XD

Otherwise to answer your questions anyway (just in case it happens again):
- Yes like I said I can use the official plex client on my phone (although not really because I don't have the premium pass but I can see the file and I streamed a couple seconds of a video).
- Yes it shows up in the list (as local) whether I try to use plex.tv or not.

Anywho... Thanks for the help. Let's hope I don't have to come back. Sorry to have bothered you!
