### ISSUE TITLE
Little issue sending music stream from iPhone App to PlexKodiConnect

### ISSUE THREAD

**Issue by xefil** [croneter/PlexKodiConnect#22]
Hi again ;)

I'm testing to send from the Plex Iphone App a music stream from the App to the PlexKodiConnect player. KODI takes correctly the stream/command and in plays the music.
The only difference is that if I choose to play the music directly from KODI, then during the play on the home it shows the artist background and the album image.
If I choose to send the command via iPhone App, the background stay black, no album image. The title is shown correctly. Seems it doesn't take any image from the artist, even if present (and locally cached AFAYK).

Bug or normal?

Thanks!!

Simon

**Comment by croneter** [comment]
Should be solved in PKC beta (install from a dedicated PKC beta repository). Let me know if this is not the case

**Comment by xefil** [comment]
Could you point me to the beta repo?
