### ISSUE TITLE
Movies and Episodes start/resume where I left off, NOT from the beginning

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#220]
Issue:
> When i try to start a movie or show episode from the beginning instead of resuming where I left off, my video still resumes where I left off even tr

Solution:
> This **only** happens when you use Kodi widgets. There is no known fix to this on the PKC side. As a workaround, do not use widgets to start a movie from the beginning

**Comment by syoz** [comment]
Movies are not resuming from where they are left off. I think it may of happen since the last PlexPass update of PMS.  Movies don't seem to register with PMS in the 'Now Playing' section, nor do they appear to register 'On Deck'.  I've tried the beta release of PKC.

**Comment by croneter** [comment]
Please elaborate and follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
How do you start movies? From the kodi homescreen or from somewhere else?

**Comment by syoz** [comment]
From 'On Deck' and the 'All Movies' sections. Not just widgets if that's what you're asking.

**Comment by croneter** [comment]
Capture the bug in the Kodi log file as described above

**Comment by croneter** [comment]
Also, please open a new issue as this probably has nothing to do with this issue here

**Comment by syoz** [comment]
Apologies, after much investigation this was a PMS issue caused by a corrupt database.
