### ISSUE TITLE
Direct play from gdrive addon paths. For Plex Cloud users with gdrive.

### ISSUE THREAD

**Issue by Rick7C2** [croneter/PlexKodiConnect#221]
I would like to request a new feature for people using plex cloud with google drive.

It will work the same as Direct play from network paths feature But instead it will direct play using the gdrive addon instead of plex cloud server.

The google drive addon being used is located here...

http://forum.kodi.tv/showthread.php?tid=177557

I use the testing version. For the most part it is stable enough for daily use but also features the latest features.

I have done some looking in to the logs to see what url is played when using PlexKodiConnect with a gdrive plex cloud server.

This is the url I got...

`https://serverid.ric.plex.services:443/services/clouddrive/google/media/google:0B5myDjLOM51Xd0Y3cFpza3I3M1U?X-Plex-Platform=Windows&X-Plex-Client-Platform=Windows&Connection=keep-alive&X-Plex-Device-Name=Kodi+%28HTPC%29&X-Plex-Provides=client%2Ccontroller%2Cplayer&X-Plex-Token=****-Plex-Client-Identifier=****&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=1.5.12 itemid: 13736`

And here is a sample .strm file created by the gdrive addon for the same file...

For gdrive addon testing version
`plugin://plugin.video.gdrive-testing/?mode=video&username=Rick7C2&filename=0B5myDjLOM51Xd0Y3cFpza3I3M1U`

For gdrive addon stable version
`plugin://plugin.video.gdrive/?mode=video&username=Rick7C2&filename=0B5myDjLOM51Xd0Y3cFpza3I3M1U`

Where Rick7C2 is the username setup in my gdrive addon and "0B5myDjLOM51Xd0Y3cFpza3I3M1U" is the id number for the file located on google drive.

Would it be possible to to a new option in the settings to direct play for the gdrive addon instead of going through the plex server?

The options needed would be...

GDrive addon username? With textbox.

Gdrive addon testing version? Tick box to work with testing version.

The dev of the gdrive addon also has addons for OneDrive might work the same as his gdrive addon here..

http://forum.kodi.tv/showthread.php?tid=208131

I know the gdrive addon by itself lets you choose what transcode by google drive you want to use. But I have been running into issues with video files that have multiple audio tracks like commentary tracks that sometimes google drives transcodeing uses and there is no option to change it.

Using this with Plex Cloud will allow me to direct play from google drive with the abiity to change audio track in kodi. Or use a transcode from plex cloud that will allow me to change audio track aswell.

Thanks for this great addon!

**Comment by croneter** [comment]
Now on feathub: http://feathub.com/croneter/PlexKodiConnect/+4
