### ISSUE TITLE
Problems connecting to Plex.tv

### ISSUE THREAD

**Issue by KingKapalone** [croneter/PlexKodiConnect#223]
I posted about this in the forum thread on Plex's site and croneter told me to post my log here. I get this error saying "Problems connecting to Plex.tv. Network or internet issue?" I tried a full reset of the add-on and hitting the toggle plex.tv sign-in over and over. This has all worked for months before, but this started happening randomly after no changes AFAIK. Here's the logfile: http://paste.ubuntu.com/23993093/ I searched for X-Plex-Token and didn't find anything, but please let me know if I posted some info I wasn't supposed to.

I noticed that it might be confusing in the log that there are two Plex servers on the network, FRONTROW and FRONTROW-dave. The first one is mine.

**Comment by croneter** [comment]
Seems like your Python SSL installation is faulty:
```
23:00:07 T:140351521621760  NOTICE: PLEX.downloadutils -> DEBUG:: Server unreachable at: https://plex.tv/api/home/users
23:00:07 T:140351521621760  NOTICE: PLEX.downloadutils -> DEBUG:: ('bad handshake: SysCallError(0, None)',)
```
This certainly is **not** a PKC issue. Does this help?
* https://github.com/kennethreitz/requests/issues/2022

**Comment by croneter** [comment]
By the way - you're fine with the tokens. Nothing leaked ;-)

**Comment by KingKapalone** [comment]
I don't really know anything about linux but I scrolled through the stuff at the link and tried some of the commands they posted. When I tried this suggestion: 

`sudo apt-get install libffi-dev

pip install pyOpenSSL ndg-httpsclient pyasn1`

I got this exception:
`Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/ndg_httpsclient-0.4.2-py2.7-nspkg.pth'
`

After that suggestion there's a lot of talk about things I don't know about. Someone did mention pip being out of date, so I updated mine (before trying all this actually). Later on there's another suggestion to try:

`sudo pip install ndg-httpsclient pyasn1 --upgrade`

Which gives me this error (I copied from where it started to look relevant):

` x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:434:30: fatal error: openssl/opensslv.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of cryptography
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ungx_L/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-cGv6L4-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ungx_L/cryptography/
`

Why would something like Python get messed up without me doing anything to it and why wouldn't there be just an easy uninstall/reinstall fix? Linux seems unnecessarily complicated anytime I'm trying to do anything in it.

**Comment by croneter** [comment]
Sorry to hear that. Maybe it's enough to update Kodi to 17.0?

**Comment by croneter** [comment]
Any news for this issue?

**Comment by KingKapalone** [comment]
You think updating Kodi would fix the SSL issue? I thought it be more of just a pure ubuntu fix. I haven't gotten around to trying it yet.

**Comment by croneter** [comment]
Updating Kodi is certainly easier. So try that first - if you're lucky it's sufficient. I'll close this ticket now as this is not PKC issue but a problem with your Kodi/python installation

**Comment by KingKapalone** [comment]
Updated Kodi to 17.0 and the problem went away. Thanks for the help.
