### ISSUE TITLE
PlexKodiConnect's Plex Companion not recognized by Plex Media Player and Plex Web

### ISSUE THREAD

**Issue by mvanbaak** [croneter/PlexKodiConnect#224]
This is a feature request ;-)

Yesterday I was all excited and hopefull when I connected an Amazon Echo dot (I'm in .nl, it's not available here. got my boss to pickup one while he was in NewYork)
While plex server was found and alexa found 2 players, plexkodiconnect was not one. It only found my PS4 plex app and my web client.

While looking a bit more, I also noticed that the plex web client does not show plexkodiconnect as a player to cast to.
My iPhone client does.

So I installed Plex Media Player on my macbook, and this one also does not see plexkodiconnect as player to fling playback to.

I think the Companion is missing some items...

If there's anything I can do more to help in this issue, please let me know.

Kodi version: 17.0
PKC version: 1.5.13
PMS version: 1.4.1

Both PMS and PKC (and alexa and PlexMediaPlayer as well) are logged in with the same plex.tv user (no Home users, just one main account on both)

**Comment by croneter** [comment]
Plex needs to specify, what a developer needs to do in order for Alexa to work. Could be tricky to get them to do that. 

See https://forums.plex.tv/discussion/257193/how-to-implement-alexa-for-other-plex-clients

**Comment by croneter** [comment]
My Plex Web **does** show PlexKodiConnect. You might want to change the name PKC uses - go to the PKC settings, Plex, then `Use alternate device name`. Reboot Kodi after that!

Do let me know if PKC still won't show up

**Comment by mvanbaak** [comment]
It shows up right after a reboot of kodi. But only for 2 minutes. After that it's gone from the plex web list.
I'll enable debug logging and see what it tells me there.

**Comment by mvanbaak** [comment]
[kodi.log.txt](https://github.com/croneter/PlexKodiConnect/files/785211/kodi.log.txt)

See attached log.
My best bet (without knowing exactly how it works) is this line in the logs:

```
18:38:56.479 T:123145402478592  NOTICE: PLEX.PlexCompanion -> DEBUG:: Client is no longer registered. Plex Companion still running on port 3005
```

If you need more info let me know.

**Comment by mvanbaak** [comment]
https://github.com/croneter/PlexKodiConnect/blob/68e1e6facdae0d4ae01821f7c958bae1b902effc/resources/lib/plexbmchelper/plexgdm.py#L180

It looks like the is_discovery_complete is never set to True in the code. right?

**Comment by croneter** [comment]
Reload the Plex web page. Does that help? Other clients see PKC 24/7

**Comment by mvanbaak** [comment]
No, doesn't help.

Yes, my iPhone sees PKC (all of them, 3 raspberries and my notebook)
But alexa does not.

Later I'll try alexa right after a reboot while PKC shows up in plex web. Maybe it's the same problem?

**Comment by croneter** [comment]
Alexa is NOT plex companion!

Am 18.02.2017 19:37 schrieb "Michiel van Baak" <notifications@github.com>:

**Comment by mvanbaak** [comment]
Let's forget about alexa here.

I still have the same issue with plex web.
If I look at the url that is loaded with ajax as soon as you click the 'cast' icon in plex web, I do see PKC there right after a reboot, but it goes away after a couple of minutes.

https://77-160-35-62.724fa552acc2453bb301e81a797d7ef9.plex.direct:32400/clients?X-Plex-Token=SUPER-SECRET-TOKEN

The PS4 client is always listed there as long as the PS4 app is running.
I'm pretty sure it disappears from that list when I see this logline in kodi:
`21:11:27.698 T:123145562333184  NOTICE: PLEX.PlexCompanion -> DEBUG:: Client is no longer registered. Plex Companion still running on port 3005`

**Comment by croneter** [comment]
I cannot reproduce your issue. 
* browser? Do try another one
* how long do you need to wait until PKC is gone as casting target?

**Comment by mvanbaak** [comment]
I tried with both chrome and firefox on OSX.
It takes between 2 and 4 minutes for PKC to disappear as casting target.

PKC does stay visible as casting target on my iphone app though.

The url I pasted before is the same for all browsers when I click the cast icon to get the list (https://my-external-ip.somerandomstring.plex.direct:32400/clients?X-Plex-Token=my-token)

I see this behaviour with all PKC clients (libreelec latest beta 7.95.3 with latest PKC beta 1.5.14) on raspberry pi 3 and with kodi 17 running PKC beta 1.5.14 on osx

**Comment by croneter** [comment]
Which lets me believe it's a plex web issue, maybe even for a certain browser

**Comment by croneter** [comment]
Changed some stuff for the next PKC beta release. If Plex Companion still does not work, please share your entire log again

**Comment by mvanbaak** [comment]
I think you fixed it. I updated the plugin on my macbook to test. For now it still shows up after 10 minutes which was never the case.
I'll keep it running some hours and see what happens. If it does not stay visible, I'll reopen with a complete log, but I think it will be ok. See the log I have now:

```
17:30:16.373 T:123145421316096  NOTICE: PLEX.plexbmchelper.plexgdm -> DEBUG: Client has not been marked as registered
17:30:16.373 T:123145421316096  NOTICE: PLEX.PlexCompanion -> DEBUG: Client is no longer registered. Plex Companion still running on port 3005
17:30:16.373 T:123145421316096  NOTICE: PLEX.plexbmchelper.plexgdm -> DEBUG: Sending registration data: HELLO * HTTP/1.0
                                            Content-Type: plex/media-player
                                            Resource-Identifier: 817a5dbb-49cf-494a-b0a5-b587c60ad6d8
                                            Name: notebook
                                            Port: 3005
                                            Product: PlexKodiConnect
                                            Version: 1.5.15
                                            Protocol: plex
                                            Protocol-Version: 1
                                            Protocol-Capabilities: timeline,playback,navigation,playqueues
                                            Device-Class: HTPC
17:30:16.373 T:123145421316096  NOTICE: PLEX.plexbmchelper.plexgdm -> DEBUG: (Re-)registering PKC Plex Companion successful
```

**Comment by mvanbaak** [comment]
up until now the PKC players are still visible and usable from the plex web interface. Just to get back and confirm it's really fixed :) thanks 👍

**Comment by croneter** [comment]
Thanks for the info! ;-)
