### ISSUE TITLE
"Sync had to skip some items because they could not be processed." 

### ISSUE THREAD

**Issue by Karyudo** [croneter/PlexKodiConnect#225]
For the past month or so, I've been getting an error message every time I sit down to watch something: "Sync had to skip some items because they could not be processed. Kodi may be instable now!! Please post your Kodi logs to the Plex forum." This is accompanied by tons of lag in navigating and selecting items for a minute or more.

I've finally found time to tackle fixing this, but I need more info... such as:
• What Kodi logs are required? (Is it just 'kodi.log'?)
• Where are they located in LibreELEC? (If it's 'kodi.log' then it's /storage/.kodi/temp)
• Where should they be posted? (If it's here, then 'kodi.log' is attached.)
[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/784722/kodi.zip)

Has this issue already been addressed? I couldn't find anything using the search here. Where's the biggest PKC discussion forum?

**Comment by croneter** [comment]
You're Kodi database is locked:
```
02:06:44.866 T:140452508735232  NOTICE: PLEX.utils -> ERROR:: add_update has crashed. Error: database is locked
02:06:46.758 T:140452508735232  NOTICE: PLEX.utils -> ERROR:: Traceback:
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 838, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/itemtypes.py", line 529, in add_update
                                                artwork.addArtwork(API.getAllArtwork(), movieid, "movie", kodicursor)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/artwork.py", line 355, in addArtwork
                                                cursor=cursor)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/artwork.py", line 401, in addOrUpdateArt
                                                self.deleteCachedArtwork(url)
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/artwork.py", line 434, in deleteCachedArtwork
                                                (url,))
                                            OperationalError: database is locked
```
Try PKC beta, this should already be fixed. See here: https://github.com/croneter/PlexKodiConnect/wiki/Installation

**Comment by Karyudo** [comment]
Cool. Thanks for diagnosing! I'll give the beta a try.

Is there something I should do on the Kodi end to ensure the database isn't locked? Or is this the new normal, and PKC (beta) works around it from now on?

**Comment by croneter** [comment]
By the way, posting your log here was perfect, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

The forum is here: https://forums.plex.tv/discussion/210023/plexkodiconnect-let-kodi-talk-to-your-plex#latest

**Comment by croneter** [comment]
> Is there something I should do on the Kodi end to ensure the database isn't locked? Or is this the new normal, and PKC (beta) works around it from now on?

It's not normal. Maybe you're machine is extremely slow and that's causing it. Try the beta and do come back here if that does not work ;-)
