### ISSUE TITLE
Alexa / Amazon echo support

### ISSUE THREAD

**Issue by mvanbaak** [croneter/PlexKodiConnect#226]
The alexa plex skill is unable to find PKC players. When you ask her: 'Alexa, ask plex to change my player' she does not list PKC as an available player.

The plex developers have already been asked what's needed to support this:
https://forums.plex.tv/discussion/257193/how-to-implement-alexa-for-other-plex-clients

**Comment by croneter** [comment]
My hands are tied until plex tells what we would need to do in order to support Alexa 
Do support this request:https://forums.plex.tv/discussion/257193/how-to-implement-alexa-for-other-plex-clients

**Comment by mvanbaak** [comment]
Already supported. Let's wait for their information

**Comment by croneter** [comment]
Now on feathub: http://feathub.com/croneter/PlexKodiConnect/+3
