### ISSUE TITLE
new tv shows not being added to kodi library

### ISSUE THREAD

**Issue by Deihmos** [croneter/PlexKodiConnect#23]
Newly added TV shows are not being added automatically to Kodi. I tried this on multiple computers with different Plex server installs. It seems to work with Movies but does not work for TV Shows. Can you confirm if this works or not?

**Comment by croneter** [comment]
Just checked this. Worked flawlessly. 

Are we talking about a completely new show that did not exist on Plex before? Please share your extensive logs, otherwise I can't help. See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug.

**Do enable ```Debug``` logging in the PKC Settings under Advanced**

**Comment by Deihmos** [comment]
I am going to try it with the new build you posted and see what happens. No it isn't for a new show but a new episode. It worked with movies but not episodes.

**Comment by Deihmos** [comment]
Still not working. A new episode The 100.s2.e07 was added to Plex but after 10 minutes still nothing on Kodi. 

[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/253429/kodi.txt)

**Comment by croneter** [comment]
Hmm, there is nothing in the log. I will increase logging info in the next release. Hopefully something will get caught on camera then...

Again - you DID let Plex scan for new items? Meaning you used your browser to access ```http(s)://<pms-ip>:<pms-port>```, went to ```TV Shows``` library and hit the circular arrow at the top right to hit ```Update Library```?

**Comment by croneter** [comment]
Or differently put - if you use another Plex client like Android or iOS, do you see the new episode?

**Comment by Deihmos** [comment]
Yes I see the episodes on my iOS device. I did scan for the new episodes. The Kodi library just never seems to update. I installed a new plex setup on my laptop and it is the same behavior. The sync just doesn't seem to be working.

**Comment by Deihmos** [comment]
Would I need to forward any ports to get it to work?

**Comment by croneter** [comment]
No

**Comment by croneter** [comment]
Could you please try to log again with version 1.1.8? Do enable debug logging in the PKC settings

**Comment by Deihmos** [comment]
Ok I left it a while and none of the 3 episodes I added to the Plex library appeared in Kodi. They appear on the web and ios client fine. The only way I can get it to update is if I restart Kodi.

[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/253909/kodi.txt)

**Comment by Deihmos** [comment]
Here is an update. If a new movie is added to plex it updates on Kodi then the TV show is updated also. If I just add a TV show episode nothing is updated. I left it running for a while and nothing was updated until a new movie was added.
[kodi (2).txt](https://github.com/croneter/PlexKodiConnect/files/253982/kodi.2.txt)

**Comment by croneter** [comment]
Just experienced something similar. Do you not see the new episode in the On Deck view or recently added? What if you go to your series view - Does it show up? 

Kodi annoyingly slow updating the On Deck view. It works fine if I go to the TV series folder directly

**Comment by Deihmos** [comment]
I tried all of that and the new episodes aren't there.

**Comment by hstamas** [comment]
I looked in my regular library view as well and new TV episodes are not there unless I do a full refresh.

**Comment by croneter** [comment]
Naturally :-). Thanks guys. We'll find this bugger
