### ISSUE TITLE
Real time updating not working

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#232]
This started with my stable Kodi 16 / PKC 1.5.0 install. Notice release notes for 1.6.0 saying that Plex PMS changed web socket method and this problem might be a result so I updated to 1.6.0.
Still having the same issue. Added a new show at 9:12pm. As of 9:20pm still no refresh. I have my wait setting set to 60s. 

Logs:
http://pastebin.com/q5w1uk4u

**Comment by croneter** [comment]
Enable PKC debug logging and try to repeat the bug again. Nothing I can see
in there

Am 25.02.2017 03:39 schrieb "hstamas" <notifications@github.com>:

**Comment by croneter** [comment]
Also make sure that you are using the latest PMS version

Am 25.02.2017 07:20 schrieb "Thomas Kathriner" <kathriner.thomas@gmail.com>:

**Comment by hstamas** [comment]
Logs with debug enabled:

http://pastebin.com/0nrSfsSZ

I am using the latest public release of the PMS (1.3.4.3285). Is that sufficient? I've had unrelated issues with the Plexpass version so Id rather not use that unless necessary

**Comment by croneter** [comment]
Very weird behavior indeed. Could you please test again with 1.6.1?

**Comment by hstamas** [comment]
1.6.1 same behavior. 

Bit the bullet and updated PMS to Plexpass version and its updating almost instantly again but now the a good portion of shows I watch, once finished are not being marked 100% watched again. This is also tying with a different skin.

**Comment by croneter** [comment]
So the initial issue is solved for an up to date Media Server.
