### ISSUE TITLE
Kodi Library Export

### ISSUE THREAD

**Issue by levander051** [croneter/PlexKodiConnect#234]
Couple of months ago I was able to export library in seperate nfo files, today I reinstalled Kodi and PKC with latest updates and it doesn't export anything. There is a progress bar as it is working but when it finishes there are no exported files. I tried exporting without PKC and it works. What happened? Am I missing something or it is not possible anymore?
P.S.
Fanarts and posters are exported, but there are no nfo files.

**Comment by croneter** [comment]
Very low priority since all your data is on the plex media server

**Comment by levander051** [comment]
Fair enough, but I am 99% sure I was able to do it in some of the previous releases. Could you confirm that possibility in some of previous versions of PKC, please?

**Comment by levander051** [comment]
By the way, it would be very useful since all manually entered metadata (as Collections/Tags) could be saved into nfo files and imported back to Plex Media Server in case of corrupted/lost database and to be able to easier reorganize libraries in PMS. I can't see better way of maintaining and reorganizing PMS collections in sight at the moment...

**Comment by croneter** [comment]
PKC is NOT the tool to do this, sorry

**Comment by levander051** [comment]
me too

**Comment by croneter** [comment]
Now on feathub.com: http://feathub.com/croneter/PlexKodiConnect/+1
