### ISSUE TITLE
Compressing Database

### ISSUE THREAD

**Issue by almostserious** [croneter/PlexKodiConnect#238]
Hi since 1.6 update my SPMC always shows compressinf database every 5 seconds. And there is a very short freeze assoctiated with it. Any settings that i can change?

**Comment by croneter** [comment]
Have you disabled under settings > videos > hide library update?

**Comment by almostserious** [comment]
I did now. But thats just cosmetics isnt it?

**Comment by croneter** [comment]
True. Did you start of with PKC with an empty Kodi database? Try resetting the database by going to the PKC Settings, advanced, Reset the Kodi database (in red), then Yes, Yes, No

**Comment by almostserious** [comment]
I did the reset once i updated to 1.6. But can try it again.

**Comment by croneter** [comment]
Did it work?

**Comment by almostserious** [comment]
Sorry didn't try it yet. Will do it tonight.

**Comment by croneter** [comment]
Solved?

**Comment by almostserious** [comment]
Seems fine now :) Thx 👍
