### ISSUE TITLE
Slowdowns, or infinite loading when playing a file, failure to play or occasional hard crash

### ISSUE THREAD

**Issue by OmNomNomagon** [croneter/PlexKodiConnect#239]
Windows PMS 1.4.2.3400 and 1.4.2.3285
Kodi 17 windows on local machine and external windows machine.
PKC 1.6.0 - 1.6.1

Starting up Kodi and attempting to play files has been causing severe slowdowns and failure to play on the most recent PKC versions. 1.5.1 is working without issue, but subsequent versions have issues.

Playing a file will show the spinning loading disc for 30seconds to 2mins. The file may fail to play or eventually load. Once a file begins playing, generally subsequent plays also work without issue. CPU usage is abnormally high throughout startup of kodi.

I've completely reset settings and the database multiple times. It happens on a local install and a remote windows machine, however it seems to occur more readily on the local machine. Also not sure if it is related butPKC will not let me assign a manual ip address of 127.0.0.1 on the local machine. I've tried various combinations of directplay and direct stream, native and default, music library on and off.

I've included a log of the issue. The timestamps below indicate a time approximate to when a PKC file was attempted to be played.

23:05:18
23:06:00
23:06:57
23:09:03
23:10:50

[kodi-lotsoffails.log.txt](https://github.com/croneter/PlexKodiConnect/files/803606/kodi-lotsoffails.log.txt)

**Comment by OmNomNomagon** [comment]
The same slowdowns can occur when accessing the deck or recently added and when trying to open settings.

[kodi-failuretoloaddeck.log.txt](https://github.com/croneter/PlexKodiConnect/files/803701/kodi-failuretoloaddeck.log.txt)

**Comment by croneter** [comment]
Thanks for the log, sorry for the issue :-(. 

I've scanned both log files. With the new PKC version >1.6.1 you'll be able to enter a manual IP and port again :-) (version coming up soon)

I can't really find anything that could cause this issue. 
* Does this happen on 2 different Windows machines independently?
* Did you try to really wipe the Kodi settings entirely by deleting the entire `userdata` folder? (see here: http://kodi.wiki/view/userdata)

If that does not help, I see some local Python installations under the following paths:
```
23:48:38.806 T:5112   DEBUG: CPythonInvoker(12, C:\Users\HTPC\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py): setting the Python path to C:\Users\HTPC\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect;C:\Users\HTPC\AppData\Roaming\Kodi\addons\script.module.requests\lib;C:\Program Files (x86)\Kodi\system\python\DLLs;C:\Program Files (x86)\Kodi\system\python\Lib;C:\Program Files (x86)\Kodi\python27.zip;C:\Program Files (x86)\Kodi\system\python\lib\plat-win;C:\Program Files (x86)\Kodi\system\python\lib\lib-tk;C:\Program Files (x86)\Kodi;C:\Program Files (x86)\Kodi\system\python;C:\Program Files (x86)\Kodi\system\python\lib\site-packages
```
This sums up to:
```
C:\Program Files (x86)\Kodi\system\python
C:\Program Files (x86)\Kodi\python27.zip (???)
```
These get loaded and Kodi might be using it.

**Comment by croneter** [comment]
Solved?

**Comment by OmNomNomagon** [comment]
Hi Cron thanks for the suggestions.

I had already completely deleted the kodi userdata folder and reset from scratch a number of times between 1.5.2 and 1.6.0 without any luck. It seemed to persist between full resets. 

I followed your advise and installed the newest version of python 2.7.1.3 as well as the newest PKC. 1.6.1 - 1.6.2. Everything is working perfectly again. I'm not sure if it was related to the manual ip issue or python version or possibly complications with the skin helper packaged within the beta titan skin. However everything is working great now.

Some further information for you. It was occurring on 2 separate machines. a low power with the PMS server, as well as an external i7. The issues were more pronounced on the i3 machine with around 80% of files failing to play compared to 20%.

Thanks for this amazing addon. I'll close off the issue.
