### ISSUE TITLE
Photos doesn't work in Kodi v17

### ISSUE THREAD

**Issue by nexusle** [croneter/PlexKodiConnect#243]
Hi croneter. 

On a client using Kodi v16 I can see my Photos. With my other clients running Kodi v17 not. The version number is the only different between this clients.

**Comment by croneter** [comment]
Please quickly share a log: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by mbr1975** [comment]
Same issue here, when I try opening them from "pictures add-on / plexkodiconnect / Photos ", the icon on screen shows something is in progress, but nothing happens, pressing "DOWN" on remote control is uneffective, I had to press multiple times the "MENU" button to let it exit.

This is the log of first test:
[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/845261/kodi.txt)


Using directly Kodi 17 (through LibreELEC linux distribution), I can browse pictures, but can't see previews and selection is uneffective.

This is the log of second test:
[kodi2.txt](https://github.com/croneter/PlexKodiConnect/files/845291/kodi2.txt)

**Comment by intrawebltd** [comment]
I can get to photos via a favorite pointing to Videos/PlexKodiConnect/photoLibName BUT the Pictures menu on the Kodi home screen doesn't go there.

I didn't see any options to play a slideshow, so I tried play from here on a folder of photos and it just flashed repeatedly, pressing back it just hung. I force-closed Kodi, upon re-run I clicked my photos favorite and got the blue spinning circle for 15 minutes (not sure what PKC is doing on startup but it seems to be very busy). Once back in I clicked on a photo, the screen flickered but nothing happened.

I will probably just add photo sources direct to Kodi and see if that works.

**Comment by croneter** [comment]
Patience guys...

**Comment by croneter** [comment]
Should be solved with version 1.7.4.

# Warning 
If you want to show pictures, you need to navigate via Pictures -> Picture Add-ons -> PlexKodiConnect. If you want to watch a video, navigate through Videos -> Video Add-ons -> PlexKodiConnect. This is a Kodi limitation, unfortunately
