### ISSUE TITLE
High CPU on Fire Stick

### ISSUE THREAD

**Issue by broyuken** [croneter/PlexKodiConnect#248]
Hello,

I use PKC on an Amazon Fire TV Stick 2nd gen. As soon as I enable PKC, the CPU jumps from idling at ~8%-12% to ~50%-70%. I tried disabling constant background sync as well as limiting the download sync threads to 1, but this made the CPU go even higher. 

This is an issue for me because whenever I try to play live TV through Kodi with my hdhomerun, the CPU is around 95%-100% which causes very choppy playback and freezes which makes the wifey less than pleased that I got rid of our cable boxes.

As soon as I disable the PKC addon, my CPU idles back around 10%.

Am I missing a configuration item, or there something wrong with my setup that's causing the high CPU? I've reinstalled many times, and waited for days to see if the initial sync was just causing the high CPU and it would go down when it finished.

If I can get the CPU to a point where it doesn't freeze my live tv playback with PKC enabled this will be the perfect setup, because I absolutely LOVE this addon and the customization I can have with my skin (Titan).

**Comment by croneter** [comment]
That's really weird. Please enable debug logging for PKC AND Kodi, then grab a log: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Using a Raspberry Pi, CPU is never an issue...

**Comment by broyuken** [comment]
How long should I let it run with debug on?

**Comment by croneter** [comment]
1 hour? Be sure to enable debugging 2x, both in PKC and in Kodi

**Comment by broyuken** [comment]
Here is my kodi.log. I let it run for just about an hour. Most of the time it was just sitting on the home menu. Towards the end I did test by watching live tv and the CPU spiked to 90-100%. After disabling PKC and going back to TV the CPU is now at 50-65%. Idle CPU was around 30-60% with PKC enabled, but a couple times it did settle down. 

Please let me know if I can provide any more info to help figure out this issue.

[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/827678/kodi.txt)

**Comment by croneter** [comment]
Nothing unusual on first glance. Is the Fire Stick so much worse than a Raspberry Pi 2 or 3?

I'd suspect that you're installation is somehow faulty. Can you reset your fire stick completely? Then make sure you have the latest version of everything installed?

**Comment by broyuken** [comment]
This was on a fresh install, and it had the same issues prior to me resetting everything. I reinstalled Kodi, and reset the fire stick to factory defaults. I am running Kodi v17 stable release and the latest version of everything from the kodi repo and your repo. All I have installed is 

Kodi, 
HDHomerun PVR enabled
Titan skin
Backup addon
Official Plex addon
PKC

No other addons, no other programs installed. This is a fairly bare bones install. I will reset the fire stick and install Kodi and ONLY PKC to see what happens and report back. 

The RPI 3 has CPU: 4× ARM Cortex-A53, 1.2GHz for a CPU

The Fire Stick 2 has Quad-core ARM 1.3 GHz. 32-bit for a CPU

so they look fairly similar to me.

**Comment by croneter** [comment]
I would NOT mix PKC with the official Plex addon. Could you try to only run PKC?

**Comment by broyuken** [comment]
I formatted a second Fire TV Stick, put Kodi v17 on there, and only added PKC from your repo. When watching live TV CPU went from 60% to 90%. As soon as I disable PKC it goes back to 60%.

**Comment by broyuken** [comment]
Any ideas on anything I could try, or anything I can provide you to help look into this?

**Comment by croneter** [comment]
Not really :-(. The high loads are quite the mistery for me. I can't replicate the issue since I don't have a Fire TV Stick. 

Anyone else out there owning a Fire TV Stick where PKC works or does not work?

**Comment by broyuken** [comment]
Looks like this might be an issue with PKC and either Titan or the skinshortcut addon. If I use he default estuary the CPU is nice and low

**Comment by croneter** [comment]
I had issues with the Titan skin I  the past, too. It's rather CPU intensive... You proved that this issue isn't due to PKC ;-)
