### ISSUE TITLE
On Deck Behaviour

### ISSUE THREAD

**Issue by richardap1** [croneter/PlexKodiConnect#25]
Hi. I think there are a couple of issues with on-deck.  
1) Plex server doesn't seem to be notified if TV Shows are played from on deck.  Movies seem ok.  I checked with both Plexpy and main plex server.  

2) This might be a skin issue, however in Aeon Nox Silvo, On deck posters are a actually fanart.  If on deck is enabled as a widget and posters are selected, then you get thumbs. Movies again are fine.

Thanks

**Comment by croneter** [comment]
1. Playbak report works for me if started from On Deck. Please share your logs where it does not work
2. I cannot reproduce that either. How is the On Deck view different from e.g. Recently Added? Could you e.g. share some screenshots?

**Comment by richardap1** [comment]
[KodiPlaylog.txt](https://github.com/croneter/PlexKodiConnect/files/253505/KodiPlaylog.txt)

Hi.  Here is the play log from Kodi.  I played the same show twice. The first was from an OnDeck widget and not registed with plex, or plexpy. the other was played from TV-Shows -> 30 rock -> season 1 and was shown in both plex and plexply. I'll upload screen shot late, had to fight the family for the TV to get these logs :) Thanks

**Comment by richardap1** [comment]
Looking at the logs on line 721 and 1262 PlexKodiConnect is missing the Plex ID for the ondeck one, but not the library version.  Could that be it?

Thanks

**Comment by croneter** [comment]
Ahhhh, yes! This is a Kodi issue. For some reason, Kodi sometimes does not pass the unique Database ID. I've set up some mechanism to try and deduce the Plex item nevertheless. However, in your case, this is not possible as there seem to be several Plex items. So PKC will rather not report...

Sorry, I can't do anything about this as it's a Kodi bug

**Comment by croneter** [comment]
For the record:
```
18:09:35 T:17648  NOTICE: PlexKodiConnect KodiMonitor -> No kodi id passed. Playing itemtype is: episode
18:09:35 T:17648  NOTICE: PlexKodiConnect KodiMonitor -> Skip playstate update. No unique Kodi title found for <.......>
```

**Comment by richardap1** [comment]
Reinstalled isengard, seems OK.  Perhaps a Jarvis thing. Thanks for looking though
