### ISSUE TITLE
Video playback stuttering (skipping frames)

### ISSUE THREAD

**Issue by DEKL1NE** [croneter/PlexKodiConnect#252]
Hi,

For the last few months playback of videos has been stuttering for me (playing on Nvidia Shield).

**Description of the problem:**

Videos have been skipping frames/freezing while audio continues as normal, after a few seconds the video catches up to the audio and continues playing.
This happens with all my videos (movies and TV shows) and only when I play them through PlexKodiConnect. 

**Steps I've taken to determine the problem:**

Played the same file with: 
- Plex (direct play no transcoding), 
- SPMC (Kodi jarvis) with and without PlexKodiConnect 
- Kodi Krypton with and without PlexKodiConnect. 

The stuttering only happens when I play the files through PlexKodiConnect and happens on both Jarvis and Krypton.

At first I was using addon mode, I've since switched to Direct Paths but this did not fix the stuttering.

Can you think of anything else I can test?

Thanks in advance!

**Comment by croneter** [comment]
I do NOT think that the issue is directly related to PKC. PKC only hands over the video's path to Kodi, Kodi does the rest. Unfortunately, a bazillion things can go wrong there on the Kodi side... 

Log of you playing something that stutters would surely help, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug. Make sure to enable PKC debug logging

**Comment by DEKL1NE** [comment]
This is exactly what I was thinking, but I don't have the stuttering if I delete PlexKodiConnect and play it from within SPMC or Kodi, which is why I posted it here.

I've uploaded a logfile: http://paste.ubuntu.com/24151448/
The stuttering occured just before the end of the logfile.

**Comment by croneter** [comment]
Do you have the Plex Streaming Brain enabled? https://support.plex.tv/hc/en-us/articles/227715247-Server-Settings-Bandwidth-and-Transcoding-Limits

**Comment by croneter** [comment]
Your Kodi installation might be screwed up, looking at your log file (unrelated to PKC):
```
ERROR: Error loading Settings /mnt/expand/0ac39c36-6f6e-42fe-884a-1eaa8247732d/user/0/com.semperpax.spmc16/cache/apk/assets/addons/metadata.local/resources/settings.xml
ERROR: Previous line repeats 251 times.

ERROR: Error loading Settings /mnt/expand/0ac39c36-6f6e-42fe-884a-1eaa8247732d/user/0/com.semperpax.spmc16/cache/apk/assets/addons/metadata.local/resources/settings.xml
ERROR: Previous line repeats 251 times.

WARNING: Skin Helper Simplecache --> Database ERROR ! -- database disk image is malformed
```
The last one is not looking good and appears towards the end of the log. Any chance that you could exchange your HD/memory card?

**Comment by DEKL1NE** [comment]
I've already deleted both SPMC and Kodi several times, as well as installing on the internal storage and the micro SD card. 

I'll try removing the micro SD card and reinstalling everything on the internal memory and see if that helps.

**Comment by croneter** [comment]
Some memory issue seems like the likely cause, sorry. Be sure you're installing a fresh Kodi from scratch without any other addons or any settings preset!

**Comment by DEKL1NE** [comment]
I've removed the memory card and installed a fresh kodi, so far I haven't had any stuttering issues. 

So it seems that my memory card is (almost) defective, thanks for the help!!

**Comment by croneter** [comment]
Cool that it works. Reopen the issue if your problems reappear
