### ISSUE TITLE
PKC doesn't show track artist for compilation album tracks

### ISSUE THREAD

**Issue by intrawebltd** [croneter/PlexKodiConnect#254]
Drilling down into a compilation album's tracks, it displays the artist incorrectly:-
 
PKC shows compilation album tracks as TrackNum.AlbumArtist - TrackName 
eg: 01.Various Artists - Shape Of You 

Native Kodi v17.0 scan on same folders shows them as TrackNum.SongArtist - TrackName 
eg: 01.Ed Sheeran - Shape Of You 

I have 2 profiles, one using PKC and the other a normal scan on the same folders, all data originates from the same .nfo files.

=> On PKC you cannot see any of the 'track artist' names on compilation albums. I tried workarounds like using %F in Track Name Template, but when ordered by track number the track name then becomes a 5 digit number. All metadata is 100% and they appear correctly in Plex itself.

**Comment by intrawebltd** [comment]
I wanted to test this, so I changed to the beta repository, but I noticed it is at same version as stable (1.75) which doesn't include this fix? (so beta doesn't track the dev branch)

I then tried using the github develop branch zip file (with subfolder renamed) but kodi wouldn't install it?

Any clues?

**Comment by croneter** [comment]
Be patient, simply not published yet

**Comment by intrawebltd** [comment]
OK. 

In case you may be interested I experimented a bit more today and noticed that if following the manual install instructions at https://github.com/croneter/PlexKodiConnect/wiki/Installation 
specifically 
2. Open the ZIP file you downloaded and make sure that the folder it contains is renamed to plugin.video.plexkodiconnect
the install fails. If however I leave the zip fie intact without renaming this sub-folder it does install.

That said I didn't notice any difference re this issue, dunno if it needs a full rescan or?

**Comment by croneter** [comment]
You cannot "normally" install an unfinished version! 
You would need to overwrite everything in the add-ons folder in the folder video.plugin.plexkodiconnect

**Comment by intrawebltd** [comment]
OK, I did a file compare between the original zip files and the ones installed on kodi and they are the same, so it appears to install correctly by disregarding the sub-folder rename. 

I fully understand you don't want people experimenting with unfinished dev branches but I was curious, so won't bug-report on it or anything.

Cheers

**Comment by intrawebltd** [comment]
It works - thx

I wiped database+thumbnails folders on my PKC kodi profile, re-ran kodi, re-enabled pkc (as deleting database folder disables all non team-kodi plugins) , ran pkc which triggered re-scan and I can confirm that the compilation albums do now show the correct track artist. Brilliant!
PKC also did a full scan without crashing that was always a problem before.

**Comment by croneter** [comment]
Please do share your log files should the scan crash again! ;-)

**Comment by intrawebltd** [comment]
I did investigate the logs before and there was no indication as to what the problem was. I thought it was a certain (audio) file at first, but then realised on re-scans it would crash at different places. Only by re-adding the plex libraries one by one would it make it through.

**Comment by croneter** [comment]
Nevertheless: share-your-logs, otherwise I literally have a zero chance to improve PKC further
