### ISSUE TITLE
Hide connection notification on startup

### ISSUE THREAD

**Issue by ismay** [croneter/PlexKodiConnect#256]
I was wondering if it's possible to allow the user to hide the successful plex connection confirmation at kodi startup. I personally don't have to see it every time at startup, and would prefer it to only log errors instead of success messages. Is that already possible?

**Comment by croneter** [comment]
No. Please open a feature request here, since this is not a bug (you can use your github credentials to login): https://github.com/croneter/PlexKodiConnect

**Comment by ismay** [comment]
Ok. But that's the repo we're in now. Could you not label this as a feature request? Or do you want me to open a new issue? Let me know what you prefer.

**Comment by croneter** [comment]
No, here on github.com are bugs only. The link I sent is for features. So please just quickly copy paste your feature request ;-)

**Comment by ismay** [comment]
Ok, I think you sent me the wrong link then, because the link you gave me points to this repo.

**Comment by croneter** [comment]
Silly me, here you go 
http://feathub.com/croneter/PlexKodiConnect

**Comment by ismay** [comment]
Ok cool, done.
