### ISSUE TITLE
Playing movie takes ~3 minutes then video loading only takes about ~10 seconds.

### ISSUE THREAD

**Issue by iStatiK** [croneter/PlexKodiConnect#257]
PKC 1.7.2
Kodi 17.1
Selecting via the Movie Hub.

I am not sure if this is a PKC issue, Kodi issue, or other.  Here is the log from the minute before i selected movie to be played until it started playing.  Let me know if you need full log.

> 21:32:00.874 T:2784  NOTICE: PLEX.librarysync -> TVShows sync is finished.
> 21:32:00.884 T:2784  NOTICE: PLEX.utils -> It took 0:00:10.173000 to run the function PlexTVShows
> 21:32:00.889 T:2784  NOTICE: PLEX.librarysync -> Path hack successful
> 21:32:00.904 T:2784  NOTICE: PLEX.utils -> It took 0:00:31.399000 to run the function fullSync
> 21:32:00.904 T:2784  NOTICE: PLEX.librarysync -> Initial start-up full sync successful
> 21:32:00.953 T:1780  NOTICE: VideoInfoScanner: Starting scan ..
> 21:32:00.975 T:1780  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
> 21:33:24.720 T:6188  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting GUI proc (6.0.15)
> 21:33:30.099 T:3468   ERROR: XFILE::CDirectory::GetDirectory - Error getting \
> 21:33:32.535 T:5380  NOTICE: PLEX.default -> plugin.video.plexkodiconnect started
> 21:33:32.561 T:1096  NOTICE: PLEX.playback_starter -> Process_play called with plex_id 346, kodi_id 560
> 21:33:57.871 T:2784  NOTICE: PLEX.librarysync -> Session key 94 still unknown! Skip item
> 21:36:48.336 T:1096  NOTICE: PLEX.playbackutils -> Playbackutils called
> 21:36:48.339 T:1096  NOTICE: PLEX.playutils -> videoCodec: {'videocodec': 'mpeg4', 'container': 'avi', 'bitrate': '1039', 'height': '320', 'width': '592', 'bitDepth': '8', 'aspectratio': None, 'resolution': 'sd'}
> 21:36:48.344 T:1096  NOTICE: PLEX.playutils -> No video resolution from PMS, not transcoding.
> 21:36:48.347 T:1096  NOTICE: PLEX.playutils -> videoCodec: {'videocodec': 'mpeg4', 'container': 'avi', 'bitrate': '1039', 'height': '320', 'width': '592', 'bitDepth': '8', 'aspectratio': None, 'resolution': 'sd'}
> 21:36:48.354 T:1096  NOTICE: PLEX.playutils -> No video resolution from PMS, not transcoding.
> 21:36:48.354 T:1096  NOTICE: PLEX.playutils -> File is direct streaming.
> 21:36:48.355 T:1096  NOTICE: PLEX.playutils -> The playurl is: https://LANIPREMOVED:32400/library/parts/345/1447281142/file.avi?X-Plex-Platform=Windows&X-Plex-Client-Platform=Windows&Connection=keep-alive&X-Plex-Device-Name=Kodi&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=TOKENREMOVED-Plex-Client-Identifier=CLIENTIDREMOVED&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=1.7.2

As you can see, the movie was started at 21:33:32 and started playing at 21:36:48.  Nothing happens in between.

**Comment by croneter** [comment]
Need the full log please

**Comment by croneter** [comment]
Please do NOT delete issues! Other users might have learned from your
solution

Am 18.03.2017 16:54 schrieb "iStatiK" <notifications@github.com>:
