### ISSUE TITLE
Refresh video item makes item disappear

### ISSUE THREAD

**Issue by intrawebltd** [croneter/PlexKodiConnect#259]
If you show information for a video then click refresh, the file seems to vanish and can never be re-added, even by removing file from Plex and re-adding with PKC "Perform manual library Sync" after each operation.

**Comment by croneter** [comment]
Not good, but unfortunately I cannot prevent you from pushing that Kodi button. To fix your Kodi database, go to the PKC settings, Advanced, then the red `Reset the Kodi database ...`. Hit YES, YES, then NO.

**Comment by intrawebltd** [comment]
I assumed it would refresh the data for just that single item as it does in Kodi. I suspect others may as well.

**Comment by croneter** [comment]
Recorded this as a feature request: http://feathub.com/croneter/PlexKodiConnect/+22

**Comment by intrawebltd** [comment]
I'll leave the 'nuke' red button option running overnight. It's not too important TBH once we know not to press it, Personally I only use it occasionally when fixing metadata and want to reload it to check it's OK.

**Comment by intrawebltd** [comment]
Hmmm, unfortunately it is crashing on the re-import (music section) back out to amazon fire home screen (twice so far), so I can't get the library back at all now. I could try threads at 1 (currently is at 5) . I'll have to use the non-plex profile with regular kodi scan until I have the time to work out what is going on.

**Comment by croneter** [comment]
PKC Settings, advanced, Reset the Kodi database (in red). Then yes, yes, no

**Comment by intrawebltd** [comment]
Yes, I did that, and it is after that, that it is crashing on the re-import. Trying again now with threads=1

**Comment by intrawebltd** [comment]
Nope still crashes somewhere in the third (music) library, so I can't now rescan my library! I'll look at the logs at some point, but for now I guess I'm stuffed! I notice plugin updated to 1.2 recently I dunno if that could have affected it as it was all scanned in before. Oh well I'll get back when I've had a chance to investigate.

**Comment by intrawebltd** [comment]
OK I know from log files the music  folder that it is in when it bomb.

09:57:43.547 T:18446744072598763304  NOTICE: PLEX.itemtypes -> ADD song itemid: 116369 - Title: Connection

is implying this was the last file to succeed or is the one causing the problems. I note they are scanned in in track order so I've removed both files and rescanning.
