### ISSUE TITLE
Not retrieving all available artwork from Plex

### ISSUE THREAD

**Issue by RickDB** [croneter/PlexKodiConnect#261]
Hi,

Noticed that PKC only gets the active fanart and 1 extra when there are more available on Plex, checked to see if there was some sort of resolution limit but they are all in 1080P in Plex.

Ran a full image cache refresh a few times already but the result is the same, is there any hard limit for artwork in PKC?
Example of Plex vs Kodi Fanart:

![Plex - Timeless](http://i.imgur.com/qJCttjd.png)

![Kodi- Timeless](http://i.imgur.com/u5zJvO4.jpg)

**Comment by croneter** [comment]
PKC does sync all the ACTIVE artwork. Your first Screenshot shows POSSIBLE artwork. So no, this is not a bug

**Comment by RickDB** [comment]
Alright so it only imports fanart that is active in Plex which makes sense as it would otherwise increase artwork cache significantly.

Would be nice to have it import all artwork even if not active as an option though, in Plex you can select different ones as they look already available there.
Not a big deal either way as most people just stick with the default anyway :)

**Comment by croneter** [comment]
That doesn't make much sense as you can do exactly that using your Plex Web interface

**Comment by RickDB** [comment]
It depends on how you use it I guess because rarely use the Plex Web Interface here, only for the occasional update and what not.
This way you can just let PKC import all artwork and manage it in Kodi like when it's a local library.

**Comment by WoLpH** [comment]
Just putting ideas out there... isn't it possible to make it load them on-demand when you're actually trying to change the fanart? Not sure if Kodi offers a hook for that but it would be useful.
