### ISSUE TITLE
Dutch translation - some lines reverted to English

### ISSUE THREAD

**Issue by RickDB** [croneter/PlexKodiConnect#265]
Hi,

Seems in the recent commit for the Dutch translation a couple of lines got overwritten with their English counterparts:

**Line 239 - 241**
https://github.com/croneter/PlexKodiConnect/commit/6ae7e77ab1185b2d94252261b24bba202e4ae012#diff-0ddf42e2185032e2b24cc120ef070abdL239-L241

For example:

**Before commit**
```<string id="30253">Favoriete Thuis-Video's</string><!-- Verified -->```

**After commit**
```<string id="30253">Favorite Home Videos</string><!-- Verified -->```

Also noticed a typo in the previous translation for:

```<string id="30254">Favoriete foto 's</string><!-- Verified -->```

The word ```foto 's``` should be without an extra space like so ```foto's``` :) , can supply a new Dutch.xml with corrections if you want.

**Comment by croneter** [comment]
Thanks for the hint. Would you be kind enough to quickly change these strings yourself? Translations are done using crowdin.com, see https://crowdin.com/project/plexkodiconnect

**Comment by RickDB** [comment]
Fixed errors and applied some other corrections as well, should be good to go 👍 

Also noticed some old Emby for Kodi strings in there, here are the ID's:

33022
33023
39021

**Comment by croneter** [comment]
Many thanks!!
