### ISSUE TITLE
Choppy playback of some video files in kodi v17

### ISSUE THREAD

**Issue by kendalja** [croneter/PlexKodiConnect#266]
Since having to upgrade to kodi v17 almost all of my videos playback slow/choppy. In the log file I play three videos, the 1st is Aladdin the second Angry Birds and the third Alice in Wonderland. Alice in Wonderland is the only one of the three that played successfully. The other two are very choppy and slow. I have 0 issues with the same plex server running in plexkodiconnect on kodi v16.1. Any help is greatly appreciated. Below you will find the link to my logfile.

https://paste.ubuntu.com/24308329/

**Comment by croneter** [comment]
The conclusion is obvious that this is NOT a PKC issue. Nothing special about your log either 

Try to reset Kodi completely, see http://kodi.wiki/view/settings#Resetting_Kodi_settings_to_default

If that doesn't help, your kodi device might be too slow (not enough CPU) for you to watch certain videos, especially if they are in h265. Try using Plex transcoding by activating it in the PKC Settings under playback

Ultimately, PKC is not the problem. It simply hands the video files over to Kodi. It's then up to Kodi and Plex to do the actual playback

**Comment by kendalja** [comment]
What I don't understand then is why do the same videos play just fine under pkc in Kodi v16 on the SAME device. If it were a device playback issue they would play choppy and slow in v16 as well.

**Comment by croneter** [comment]
That points to a Kodi issue, hopefully related to some settings - because then you can revert them (my first solution proposal)

**Comment by kendalja** [comment]
All settings are default. This is with a brand new install of v17. I guess I'll have to post somewhere else for support but it's good to know this is not a pkc issue and thank you for the help!

**Comment by croneter** [comment]
Sorry buddy that I couldn't help you more here...

**Comment by croneter** [comment]
You DID try the new 17.1 though, right? ;-)

**Comment by kendalja** [comment]
Yeah sorry I have fresh out the box v17.1 with only pkc installed. I'll guess I'll just have to play with Kodi settings? But this is safe to say it's not a pkc issue? If I play the videos through my plex media server running on the same machine and through VLC they play fine. Kodi is installed on the same machine as the plex server and all the content is local. Nothing is remote

**Comment by croneter** [comment]
Very safe to say that it is not a PKC issue

**Comment by kendalja** [comment]
Thank you sir for looking into it for me I'll push on!!

**Comment by hstamas** [comment]
@kendalja I too am getting very choppy video playback on certain files in 17.1 and this is on a system that is not even using PKC so there is something going on on the Kodi side of things for sure.

**Comment by kendalja** [comment]
I found the issue! Go into settings, player settings, videos and disable "Allow hardware acceleration - VTBDecoder :-)
