### ISSUE TITLE
Plex direct paths

### ISSUE THREAD

**Issue by mihu15** [croneter/PlexKodiConnect#268]
Hi,
When I setup PKC with direct paths there should all kodi add-ons been sync yes? not for me. For example: I using add-on Exodus and when I finish a show or film after I see PKC is popup with message all sync finish successfully and I go to another device and after kodi starts up and PKC finish the sync I go to the same movie or film to see if is ticked as watched but is not why? please help.

**Comment by croneter** [comment]
I'm sorry, but I am really struggling with your English... Could you please share your Kodi log files following https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
If you watch something using Exodus (and not PKC/Plex), this will NOT change your Plex playstates

**Comment by mihu15** [comment]
Ok so I maybe wrong understand is section Advantages and Disadvantages where is wrote about compatibility direct paths: Maximum compatibility:hopefully all Kodi addons work.

**Comment by croneter** [comment]
Yes, Exodus did work for you! But if you watch a movie in Exodus, it will not get marked as watched in Plex, obviously
