### ISSUE TITLE
Slow loading on startup

### ISSUE THREAD

**Issue by qazero** [croneter/PlexKodiConnect#269]
I have a fairly large remote plex library. Each time I open Kodi it takes approximately 10 minutes to finish loading during which I can navigate through Kodi but nothing will play until 10 minutes or so once everything is done loading. After about 10 minutes everything loads fast and smooth. Any ideas what is causing the slow startup times?

**Comment by croneter** [comment]
Not with zero information from you - please share your logs, https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by intrawebltd** [comment]
I also had this every time Kodi+pkc  runs. But it is now cured for me.

I wiped database+thumbnails folders on my PKC kodi profile, re-ran kodi, re-enabled pkc (as deleting database folder disables all non team-kodi plugins) , ran pkc which triggered re-scan, when done I closed Kodi, re-ran Kodi, then ran PKC add-on (which is how I test the issue), the usual 12 minutes spinning blue circle was gone, it came up in a few seconds and I was able to play something. I was running the dev branch of pkc + no other non team-kodi add-ons running + clean scan.

**Comment by croneter** [comment]
So this seems solved for now. 

If anyone encounters this issue again, PLEASE share the log files here so I can have a good look

**Comment by intrawebltd** [comment]
Hmmm issue seems to be back now this morning. preventing shutdown etc. I'll upload some logs in a bit

**Comment by OmNomNomagon** [comment]
I also seem to have this issue again recently, I believe the previous issue I raised (#239) was basically this. Navigation is no issue but playing back any videos will give you a spinny wheel for 5 mins until everything eventually loads. I'll uploads logs as soon as it reappears for me. 

Not sure if more info will help. I also have a fairly large library. Aprox 4.5k movies, and 400 tv series. PKC 1.75, Kodi 17, Titan Skin. Trying to open PKC setting via the video addons node at startup will also freeze, but interestingly, going to settings directly via the settings - addon menu will work. it seems to affect all playback as other addons also give the spinny ring during this time. After disabling or uninstalling PKC there are no issues with playback on other addons. There is also a 10 second window on startup where playback will work if you are quick enough to start a video. It seems more pronounced on some skins.

**Comment by intrawebltd** [comment]
11:36 start kodi
go to add-ons + run pkc
get blue spinning circle
11:58 = force close
The Logs below show nothing after 11:38! (all other non team-kodi plugs are disabled, used on large library with lots of musicvideos stored as movies + live bootleg albums)

https://pastebin.com/ATS8S6Cf

**Comment by intrawebltd** [comment]
I have a snippet from another log file from yesterday that does show some pkc errors (memory leak warnings) which might be helpful, but I'm not sure what I was doing when these occured, so I haven't pasted whole log.

https://pastebin.com/BiPQgSVz

**Comment by intrawebltd** [comment]
Log3 = I ran Kodi, waited for 1 minute then did Power->Exit whereupon it hung. After approx 20 minutes Kodi did exit. Here's the log:-
https://pastebin.com/SfRBdN3j

**Comment by croneter** [comment]
Many thanks for the logs ;-)

**Comment by croneter** [comment]
@OmNomNomagon 
So you are NOT using Plex Music and still experiencing these hangs?

**Comment by croneter** [comment]
@intrawebltd 
Your first log seems the most interesting. Very mysterious, especially since the last PKC log line reads
```
NOTICE: PLEX.librarysync -> Time offset Koditime - Plextime in seconds: 59
```
Something after that must have crashed PKC, but I've no idea what :-(. Log number 2 and 3 are related to Kodi shutdown and are not important to solve the issue at hand

Could you please try the following?

1. **Deactive** `Force artwork caching` in the PKC settings, then restart. See if the issue pops up again? 
2. If this doesn't help, revert the former setting and set `Download extra artwork van FanArtTV` to False in the PKC, see if the issue pops up again?

**Comment by croneter** [comment]
Any more logs from you guys, @intrawebltd, @qazero, @OmNomNomagon and other users out there will help to shed light on this bug!

**Comment by intrawebltd** [comment]
I did another test whereby I ran kodi, waited 40 minutes then exited. This time it took about 20 seconds to close Kodi rather than the usual 20 minutes. The log file showed PKC rescanning all the music libraries in that 40 minutes (log too big for pastebin, zip+email?). 

It seems that whenever Kodi is run PKC goes through an initialisation that takes 20+ minutes (big library), so if you try to run PKC plugin or exit Kodi or swap profile you have to wait for PKC to finish what it's doing before you regain control. This does not prevent movies from playing though. The 3rd log is the only one that wasn't forcibly closed.

I will try your other tests (FanArtTV was already false afaik) when kids movie has finished.

Cheers

**Comment by croneter** [comment]
Please turn off Plex music entirely in the PKC Settings under Sync. Do the issues persist?

**Comment by croneter** [comment]
You can attach files to this thread, by the way ;-)

**Comment by intrawebltd** [comment]
I am wiping the database + thumbnails folder, then will re-run pkc overnight with:-
Force artwork caching = off (I presume this just means they get cached when first requested not all in advance)
Enable constant background sync = off

When I initially wiped the folders it seemed to have cured the issue, only for it to return the next day, so will need to try it for a while. I can try disabling music on a later test. Just waiting for Plex to finish re-scanning a  lot of audio files I changed genre on, so don't hold your breath.

**Comment by croneter** [comment]
I think I found the bugger. Let me know ;-)

**Comment by intrawebltd** [comment]
Gret news! and sorry my system is still not yet ready for a re-scan. 
I decided to merge all multi-cd's into single folders with disk# set and change a genre name. I will get your hotfix and retry as soon as it's done, but that's probably not going to be until tomorrow now as Plex rescan will take ages.

**Comment by intrawebltd** [comment]
Hi, I finally had to rebuild Plex lib from scratch, but have been running latest Kodi+PKC again for a few days now and haven't noticed the issue. It does sometimes take up to 30 seconds to close (which it doesn't do without PKC) but that's not too much of a problem. I have got PKC settings = images + instant plex off. I will monitor it and see if it reappears, but for now thanks.
