### ISSUE TITLE
hang and crash while streaming from server

### ISSUE THREAD

**Issue by richln** [croneter/PlexKodiConnect#27]
Hello,
Having a problem with streaming video from local server hanging and crashing Kodi. Consistently reproducible and occurs between 5-30 minutes after starting a stream. Video buffers a few times at beginning of play, but then is fine until the hang occurs and Kodi becomes unresponsive.
Knowns:
No known Kodi problems as other addons stream flawlessly from the Internet.
Wired network, no known network problems. Other programs on same machine have no issues streaming from server. Other machines on network have no issues streaming from server. Kodi and plexbmc on other machines on network have no issues.
No known hardware/driver issues on this machine.
Previously installed plexbmc on this machine did not have any issues.

Thanks! 

[kodi_hang_and_crash_verbose_debug.zip](https://github.com/croneter/PlexKodiConnect/files/253512/kodi_hang_and_crash_verbose_debug.zip)

**Comment by croneter** [comment]
Can't find anything related to PKC. Skin Helper service seems to have issues:
```
13:00:05 T:1140   ERROR: Skin Helper Service --> Error in plugin.py --> name 'ALPHABET' is not defined
13:00:05 T:1140   ERROR: Traceback (most recent call last):
13:00:05 T:1140   ERROR:   File "C:\Users\Rich\AppData\Roaming\Kodi\addons\script.skin.helper.service\plugin.py", line 119, in <module>
13:00:05 T:1140   ERROR:     Main()
13:00:05 T:1140   ERROR:   File "C:\Users\Rich\AppData\Roaming\Kodi\addons\script.skin.helper.service\plugin.py", line 95, in __init__
13:00:05 T:6232  NOTICE: PlexKodiConnect PlexAPI -> Checking connection successfull. Answer: 200
13:00:05 T:1140   ERROR:     plugincontent.getPluginListing(action,limit,refresh,optionalParam,randomize)
13:00:05 T:1140   ERROR:   File "C:\Users\Rich\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\PluginContent.py", line 69, in getPluginListing
13:00:05 T:6232  NOTICE: PlexKodiConnect InitialSetup -> plex.tv connection with token successful
13:00:05 T:7072   DEBUG: Testing Existence (multipath://special%3a%2f%2fprofile%2fplaylists%2fmusic/special%3a%2f%2fprofile%2fplaylists%2fmixed/)
13:00:05 T:7072   DEBUG: Testing Existence (special://profile/playlists/music)
13:00:05 T:7072   DEBUG: CMultiPathDirectory::GetDirectory(multipath://special%3a%2f%2fprofile%2fplaylists%2fmusic/special%3a%2f%2fprofile%2fplaylists%2fmixed/)
13:00:05 T:7072   DEBUG: Getting Directory (special://profile/playlists/music)
13:00:05 T:1140   ERROR:     allItems = eval(action)(limit)
13:00:05 T:1140   ERROR:   File "<string>", line 1, in <module>
13:00:05 T:1140   ERROR: NameError: name 'ALPHABET' is not defined
```
Have to tried installing Kodi from scratch, then installing PKC addon as the very first one?

**Comment by croneter** [comment]
You're using direct paths. Do native paths work?

**Comment by richln** [comment]
Direct paths seem to be the problem. Addon (default) playback works fine. I thought my plexbmc installs were using direct path but I looked up the settings and they are on default playback (HTTP). Is this the same as PKC addon default playback? Looks like my issue may be server-side or a networking issue.
Thanks!

**Comment by croneter** [comment]
Yes default PKC playback is addon, which is http direct streaming. You could try to directly play a video without using PKC - same issues?

**Comment by richln** [comment]
Playing from the network location using the Kodi file browser works well (I think this is direct play without PKC?) Playing from the network location using Windows Media Player is also fine. I am guessing this may be related to Plex Media Server then. Anyway, the default PKC playback seems to be OK. Thanks again for this great addon!
