### ISSUE TITLE
QUESTION - Playback of strm files

### ISSUE THREAD

**Issue by qazero** [croneter/PlexKodiConnect#272]
Was just wondering (since PKC is based off of PleXBMC), did you add anything to PKC to allow playback of strm files using the default Kodi DVDPlayer? The reason I ask is because I noticed I am unable to play any strm files through PleXBMC using the gdrive kodi addon (which I am able to do using PKC). Any ideas?

**Comment by croneter** [comment]
Not intentionally no

**Comment by qazero** [comment]
Any idea how I can achieve the same functionality in PleXBMC?

**Comment by croneter** [comment]
No. Please use the Plex or Kodi forum for these questions. Github focuses on issues
