### ISSUE TITLE
issue playing videos (Error: 'Playlist cant find a next item to play')

### ISSUE THREAD

**Issue by lukas15110168** [croneter/PlexKodiConnect#274]
Hello,

I'm having an issue with PlexKodiConnect ("PKC"), where I cannot get it to properly sync and play files with the account associated with it. I had it working successfully in Kodi 16, and now I've upgraded to Krypton, 17.1 and it will won't let me play any videos. It usually has the error, 'Playlist cant find a next item to play', but it sometimes also has error of file could not be found.

This is for an friend account that has ~3 libraries shared from a master user. The master user has multiple iterations of PKC running correctly on their various machines, but the friend account cannot get the PKC to work correctly.

I have tried repairing the local database, doing a partial/full reset of the database and PKC, and relogging and logging back in. It still seems to have the same issue.

Any ideas of how I could potentially fix this?

**Comment by croneter** [comment]
Are you using direct paths or addon paths? Check the PKC Settings under Sync

**Comment by lukaskt** [comment]
I believe I'm using addon paths

On Apr 10, 2017, at 3:57 AM, croneter <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you using direct paths or addon paths? Check the PKC Settings under Sync

**Comment by croneter** [comment]
Need logs then as always, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by lukas15110168** [comment]
Hmm, so I just was playing around with settings. It looks like on any Kodi that is remotely accessing the server, if the bitrate of the file is too high it results in this issue because I have a setting enabled in my server to disable streaming above a certain quality level (3-4mbps). 

If I play a low bitrate item, it works fine, but any item with higher bit rate (which is typically my whole library as its mostly 1080p files), then it spits out an error. Is there any way to get past this issue, without forcing transcoding into that quality level?

**Comment by croneter** [comment]
You have plex streaming brain enabled, so this behavior is by design! See https://support.plex.tv/hc/en-us/articles/227715247

If you don't want to deactivate the streaming brain, you could change the PKC settings to force transcode in a low bitrate

**Comment by lukas15110168** [comment]
So would I go to the playback section of PKC settings and change it to "force transcode" and then have it set to the exact same mbps as what the Plex Media Server limitation is set to?

Is there a way to have a setting where say, if I disable the Plex Media Server bandwidth limitation, I don't have to keep changing the settings in PKC to accomodate increases/decreases in quality?

**Comment by croneter** [comment]
Yes to your first question, anything below your PMS threshold is obviously fine, too 

No to your second question
