### ISSUE TITLE
Krypton Database Format Issues

### ISSUE THREAD

**Issue by maforshaw** [croneter/PlexKodiConnect#277]
I've been trying to track down why some addins don't work with a PlexKodiConnect created database (direct paths). While comparing a Kodi 17 created database with a PlexKodiConnect created database I noticed the movie and TV scraper IDs in the movie/tvshow tables are very different (fields c09/c12).

It looks like Kodi 17 changed the meaning of these fields to be a lookup to a new table called uniqueid.

I found more information here detailing the changes:

http://forum.kodi.tv/showthread.php?tid=306517&pid=2521761#pid2521761

Please can this new format be applied when PlexKodiConnect updates the database in Kodi 17 and later.

**Comment by croneter** [comment]
Can you elaborate on the differences you found between the 2 databases?

**Comment by maforshaw** [comment]
The PlexKodiConnect values in fields c09/c12 are the actual IDs from IMDb/TVDB. I assume it just reads them from Plex and puts them in directly in those fields?

However, in a Kodi 17 created database, those fields are no longer supposed to be the IMDb/TVDB ids. Instead, they are just pointers to another table, called uniqueid. It is this new table that holds the IMDb/TVDB ids.

**Comment by croneter** [comment]
OK, thanks for the info. I will take a look 

(I take it that you did a PKC database reset - just in case ;-))

**Comment by maforshaw** [comment]
No, but the last "forced" one was done after I upgraded to Kodi 17. To be sure, let me try. I'll report back.

**Comment by croneter** [comment]
Thanks if you could do the PKC dance then:in the PKC settings under Advanced, Reset the Kodi database (in red)

**Comment by maforshaw** [comment]
I have reset the database and the problem remains. A good way to test it is to run this command:

`curl --data-binary '{"jsonrpc": "2.0", "method": "VideoLibrary.GetMovieDetails", "params": {"properties": ["file", "imdbnumber", "year"], "movieid": 1 }, "id": 1}' -H 'content-type: application/json;' http://localhost/jsonrpc`

When using a PlexKodiConnect database, "imdbnumber" is null in the return data. That is why add-ins that use this will fail.

However, on a native Kodi 17 database, the above command returns the correct number.

Interestingly, the PlexKodiConnect database DOES appear to populate the uniqueid table. It just doesn't set the pointers to it in fields c09/c12 of the movie and tvshow tables.

**Comment by maforshaw** [comment]
Thank you for making this change. Please could you apply the same fix to the TVShows class, which also has the same issue but this time where it updates uniqueid for types KODI_TYPE_SHOW and KODI_TYPE_EPISODE. Thanks.

**Comment by croneter** [comment]
Plex does not use IMDB but TheTVDB. It should now work flawlessly for TV Shows. 

Unfortunatley, Plex does NOT easily provide TheTVDB IDs for episodes :-(. Plex gives you IDs like `com.plexapp.agents.thetvdb://289590/1/1?lang=en` meaning season 1, episode 1 of show 289590 - instead of giving the episode id. So this needs more work

**Comment by maforshaw** [comment]
I downloaded the development branch to test the movie and tvshow changes and it seems to work great, thank you. The JSON calls now seem to be returning the correct IDs for movies and TV Shows. Also, plugins that failed to fall back to a manual title search, such as ExtendedInfo and ArtworkDownloader, now seem to work fine.

Thanks again.

**Comment by dazedcrazy** [comment]
Just want to add that script.skin.helper.service (i.e. returns "similar movies" and such) now works correctly with the recent changes for movies just waiting on the tvshows to to be pushed, thank you.
