### ISSUE TITLE
Impossible to choose audio stream and subtitles ?

### ISSUE THREAD

**Issue by dagobertstyle** [croneter/PlexKodiConnect#278]
Hi, 
When I launch a plex movie, I can select the audio stream and the subtitles just before the movie start. But it doesn't work: whatever I choose, it's always the same audio and subtitle, and I cannot change that ?
Is there an option I forgot to set ?

PKC 1.7.7
Kodi 17.1
Ubuntu 14.04.3

**Comment by croneter** [comment]
Logs!! https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by dagobertstyle** [comment]
Oh, sorry.
Here it is : 
https://pastebin.com/qRRJGWMy

**Comment by croneter** [comment]
Please enable debug logging in the PKC settings under Advanced, too ;-)

**Comment by croneter** [comment]
And by the way - can you choose audio streams once the movie is playing?

**Comment by dagobertstyle** [comment]
Hi, 
sorry, but a new problem came just now: PKC is not able to play my plex movies. They are in the library, but when I want to play one of these, it says that the movie is no more in the library (and it ask me if I what to remove it from the library).
I tried a full reset, but nothing changed.
What could I do now ?

**Comment by dagobertstyle** [comment]
Ok, I found how to solve that. I had just to reset completely PKC, with a full reset of the PKC settings.
Now PKC can play my plex movies.

**Comment by dagobertstyle** [comment]
Ok, so I can see that when I **deactivate** the transcoding option (Settings -> Playback -> Always transcode if the video bitrate is above), then I can choose subtitles and audio streams during the playback.
But the problem is that I **need** to transcode, because my speed is too slow...
So how could I do ?

**Comment by dagobertstyle** [comment]
So here is the log: 

https://pastebin.com/1VcWXLZq

During that, I launch a plex movie, than I had the windows asking me to select audio stream and subtitle. I selected the audio and the subtitle, then the movie started, BUT the audio and the subtitle were not the ones I selected. So I tried to change them during the playback, but I can't. (option is in "grey").

**Comment by dagobertstyle** [comment]
No idea ?

**Comment by jozsy92** [comment]
Hello,

Same problem for me. when I'm in force transcode mode, then the plugin doesn't start the movie with the selected audio and subtitle. Most of my films has hungarian and english audio and some subtitles with the same two languages, but the PKC always play the movie with english audio without subtitle regardless of what I chose.
When I use direct play, there is no problem.

**Comment by dagobertstyle** [comment]
No news for this problem ?
