### ISSUE TITLE
PlexKodiConnect Install Problem

### ISSUE THREAD

**Issue by Mediaoase** [croneter/PlexKodiConnect#281]
The installation from the repository fails.

I have installed the repository from the zip file. When installing from the repository I get a error message. "Could not connect to the repository"

Data:
Android TV ver. 5.1.1
Kodi ver. 17.1

Logfile: https://pastebin.com/sanfg7Cb

**Comment by croneter** [comment]
I changed the PKC deployment process to have all MD5 files include an empty line at the end. That might help. 

Could you please try to install PKC from the **BETA** PKC repository?

**Comment by Mediaoase** [comment]
it doesn't work. :( but I'm not sure if it has anything to do with your plugin, because another third party repository doesn't work too. Only installations by the "original" Team Kodi Repository works.

**Comment by croneter** [comment]
Well then sorry, but I can't help you. Just installed successfully from the repo again...

**Comment by croneter** [comment]
I did enable installation from other repositories, right? http://kodi.wiki/view/Add-on_manager

**Comment by janitom** [comment]
Hi, is there a solution for that problem? I have the same problem on Android TV with Kodi 17.4.

I have tried the same things with beta and URL as Source in the FileManager. But in the FileManager the Source is Empty, but the connection is ok.

On my Other Kodi Devises there is no Problem with the Addon, only on the Android TV.

**Comment by Mediaoase** [comment]
I have unfortunately found no solution.

**Comment by croneter** [comment]
Could you please share some kodi debug logs of you trying to use the PKC
repo? See the wiki for how to report bugs

Am 01.10.2017 10:02 vorm. schrieb "Mediaoase" <notifications@github.com>:

**Comment by janitom** [comment]
I tried to install the videoplugin directly. Thats work for me, but i like automaticle updates.

**Comment by janitom** [comment]
log files are the same like Mediaoase. The Connection to Repository is ok, but there is no content

**Comment by croneter** [comment]
Working again?

**Comment by croneter** [comment]
Let me know if this is still an issue...

**Comment by alphareg92** [comment]
Hi,
Unfortunately this seems still broken for some of us. My case : fresh install of OSMC 2017.10-1, Kodi 17.5 on a rasp pi3.
Direct install of PKC 1.8.18 worked perfect. No luck with the repo : "Could not connect to the repository"

It did work fine on a previous OSMC/pi install, beginning of this year I think. So the problem must be in Kodi?

Thanks for the fantastic add-on, cheers.

**Comment by croneter** [comment]
@alphareg92
Debug logs please as always

**Comment by alphareg92** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1567566/kodi.log)

oops sorry. See attached kodi.log

**Comment by croneter** [comment]
See https://github.com/croneter/PlexKodiConnect/issues/374. 

Or simply follow https://github.com/croneter/PlexKodiConnect/wiki/Update-PKC-Repository

**Comment by alphareg92** [comment]
Oh great, thanks alot!! I could have found this issue #374 myself... well, it will serve other people ending up here.

**Comment by darouwan** [comment]
It happens again today: "Could not connect to the repository". 
Any way to solve it permanently?
