### ISSUE TITLE
Settings --> Connection --> Choose Plex Server from list  fails

### ISSUE THREAD

**Issue by Blindfreddy** [croneter/PlexKodiConnect#282]
When choosing another server from the list of plex servers in Settings --> Connection --> Choose  Plex Server from list, PKC gives error message 'Problems connection to "plex server name", choose another server ? <Yes/No>.

The other server is remote, not sure if this makes any difference because I only have one local server.  

Connecting to, and choosing between, the servers works fine in the plex.tv web interface.

**Comment by croneter** [comment]
https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
I'm sorry but I can't help you until you provide logs as explained in the link above

**Comment by Blindfreddy** [comment]
Will provide logs shortly.

**Comment by Blindfreddy** [comment]
Here is the log as requested. Seems in row 629 is the log entry when I selected the second entry in the Choose Plex Server from list dialog, which is a remote server.
[kodi.log.txt](https://github.com/croneter/PlexKodiConnect/files/969715/kodi.log.txt)

**Comment by croneter** [comment]
Could you please activate PKC (not Kodi!) debug logging by going into the PKC settings -> Advanced and adjust to "debug" logging? Then recapture the bug again - thanks

**Comment by Blindfreddy** [comment]
Yes sure but currently traveling, will be Friday before I get to it.

**Comment by Blindfreddy** [comment]
Please find enclosed the log as requested. If you search for the remote server's name 'cassandra-one' it'll take you straight to the lines giving more details at 7:16 today.  To me it seems as though PKC tries to connect to the host at an endpoint /library/onDeck:   https://cassandra-one.skyseract.com:32400/library/onDeck
If I enter that into a browser I get a 401 Unauthorised, whereas removing the /library/onDeck redirects to /web/index.html and displays login prompt.  Not sure where the /library/onDeck comes from but I certainly didn't configure it anywhere....

**Comment by Stanymanman** [comment]
Hi,
I have the same issue with a Plex Server on a Shield TV.
But the plexkodiconnect beta 1.7.9 seems to work better.
This error was not present with plexkodiconnect 1.7.9.

**Comment by croneter** [comment]
OK, got it:
```
07:17:08.969 T:1320154016  NOTICE: PLEX.PlexAPI -> DEBUG: Checking connection to server https://<SERVER>:32400/library/onDeck with verifySSL=None
07:17:09.211 T:1320154016  NOTICE: PLEX.downloadutils -> DEBUG: Server unreachable at: https://<SERVER>:32400/library/onDeck
07:17:09.212 T:1320154016  NOTICE: PLEX.downloadutils -> DEBUG: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
07:17:09.213 T:1320154016  NOTICE: PLEX.PlexAPI -> DEBUG: Could not connect to https://<SERVER>:32400/library/onDeck
07:17:09.714 T:1320154016  NOTICE: PLEX.PlexAPI -> DEBUG: Failed to connect to https://<SERVER>:32400/library/onDeck too many times. PMS is dead
```
In the PKC settings under _Connection_, disable SSL certificate check. Then all should be well.

**Comment by hexum1** [comment]
commit 6ff20b7 has fixed the issue for me, but it only works over local access (not remote)

**Comment by croneter** [comment]
Thanks for letting me know. Can you please share logs for you trying to access remote PMS?

**Comment by hexum1** [comment]
Here you are:


[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/1013201/kodi.txt)

**Comment by croneter** [comment]
```
DEBUG: Checking connection to server https://192.168.1.103:32400/library/onDeck with verifySSL=None
DEBUG: Server unreachable at: https://192.168.1.103:32400/library/onDeck
DEBUG: hostname '192.168.1.103' doesn't match '*.xxxxxxx.plex.direct'
```
Try deactivating SSL check

**Comment by hexum1** [comment]
I'm assuming you mean "Verify Host SSL certificate", which was already off.

**Comment by hexum1** [comment]
Fixed! Thanks a lot
