### ISSUE TITLE
Picture crash Kodi

### ISSUE THREAD

**Issue by richln** [croneter/PlexKodiConnect#288]
Hi Croneter, thanks for the awesome app. 
Every time I open a picture, it crashes Kodi. They were working fine before Krypton 17.1. I saw github issue #243, and I was able to follow those instructions to find my pictures again. But now, I can navigate my pictures, see the thumbnails, but if I try to click on a picture it crashes Kodi. I have done a full database reset and rescanned my files, but still the same problems. Any idea what is going on?
Thanks!

[kodi_picture_crash.txt](https://github.com/croneter/PlexKodiConnect/files/977913/kodi_picture_crash.txt)

**Comment by croneter** [comment]
* How many pictures are there in the view you called when Kodi crashed? 
* Can you try and deactive Plex Companion in the PKC settings, then restart, then see if Kodi crashes again?

Ultimately these errors seem related to Kodi crashing (but maybe unrelated to PKC?):
```
ERROR: CCurlFile::FillBuffer - Failed: Transferred a partial file
```
* Can you update your graphics drivers? See e.g. http://forum.kodi.tv/showthread.php?tid=303275

**Comment by richln** [comment]
I was in file view with maybe 300 pictures in that folder, but it was only showing the thumbnail of one at a time. It is fine with scrolling through the list and showing the thumbnails, it just crashes when I display the full picture or start a slideshow.

Thanks for the ideas, I will try them out and report back tonight or tomorrow. I have an Nvidia GPU, but deeper in that link you provided, someone reported it may also be related to h265 and dxva2. I will also clone to a new machine and see if it happens there as well. Thank you!

**Comment by richln** [comment]
No crashes when Plex Companion is turned off. Thanks!

**Comment by croneter** [comment]
Not good though....

**Comment by richln** [comment]
Let me know if there is something I can test out for you.

**Comment by sebastiaanluca** [comment]
I can't even get that far to disable it :( New Raspberry Pi and fresh Kodi installation on Raspbian. After a few seconds of navigating, Kodi starts flipping out and overlaying one section over another, glitching all around. It's still responsive and I can still navigate, just the image stays the same. Have to SSH in from another device to kill the process.

**Comment by croneter** [comment]
Could you please share your Kodi debug logs as always? Nothing I can do otherwise

**Comment by croneter** [comment]
Though honestly that sounds like a Kodi issue. Try LibreElec instead of raspian, works perfectly
