### ISSUE TITLE
[Feature Request] Ability to set buffer when transcoding.

### ISSUE THREAD

**Issue by ryanwalder** [croneter/PlexKodiConnect#29]
I end up in places with quite variable internet fluctuating from 500kbps to 8mbps from minute to minute (yay hotel WiFi) so it would be really handy to have a "buffer X minutes" during playback.

As I understand it when Plex is transcoding it will do X amount at 100% cpu then back off and encode at a lower percentage once it has enough, this is controllable via the server options.

However it is up to the client to make the requests for chunks of the transcoded files from the server which from my estimates are somewhere around 30-60 seconds worth so even if I tell the server to encode 10mins full tilt this doesn't relate to 10 minutes client side. As you can imagine watching a 2 or 3 mbps stream with variable bandwidth involves a lot of stopping and starting which could be avoided (mostly) with a decent buffer, unfortunately the speeds aren't quite enough for reliable direct play as that would sort this out!

Ideally I would like to set this via the Kodi cache setting (in advancedsettings.xml), or from an option within PKC where I can set a value for how many seconds/minutes to cache.

**Comment by CookieMonger** [comment]
I would also like this feature as my parents internet fluctuates often and they get heavy buffering in the middle of episodes using kodi when rasplex has no issue.

**Comment by croneter** [comment]
So guys, question - why don't you try changing your advancedsettings.xml on the Kodi side? See e.g. http://androidpcreview.com/fix-kodi-buffering-problems-heres-how-to-modify-the-kodi-cache/2611/

Try playing e.g. with the <cachemembuffersize>157286400</cachemembuffersize> setting. 

If you could tell me that messing with <cachemembuffersize> is enough, I could see whether I can implement a PKC setting that easier to use ;-)

**Comment by ryanwalder** [comment]
advancedsettings.xml does not change the current behaviour and still only buffers the next section from the server.

**Comment by croneter** [comment]
Darn, ok thanks!

**Comment by CookieMonger** [comment]
I also tried using advancedsettings.xml with no perceptible change in behavior.

**Comment by mikeau** [comment]
Try this one https://lubel.com.au/collections/android-tv-box

**Comment by Shaunoi** [comment]
If have problem with android Tv box then come here https://tvlocker.com/collections/android-tv-boxes

**Comment by croneter** [comment]
Deleted SPAM :-(

**Comment by croneter** [comment]
Now on feathub.com: http://feathub.com/croneter/PlexKodiConnect/+14
