### ISSUE TITLE
Any Kodi crash will nullify all sync progress

### ISSUE THREAD

**Issue by Tomalak** [croneter/PlexKodiConnect#291]
I have a music library of many albums, it takes a very long time (hours) to sync initially.

It looks as if the background task that does the syncing opens a database transaction when it starts working and does not commit the transaction until *everything* is done.

When a very large music library is being synced, Kodi becomes crash-happy. This becomes a vicious circle: The sync starts from zero, after an hour or so Kodi crashes for some reason, it comes back up again, the sync starts from zero, after an hour or so Kodi crashes for some reason, ad nauseam.

It would be useful to commit database changes every once in a while to save the progress. This way the whole process would at least finish at some point instead of running all night with nothing to show for it. :)

**Comment by croneter** [comment]
Actually, that should NOT be the case - every item synced should stay synced. 

As usual - please provide logs! Especially of Kodi crashing

**Comment by Tomalak** [comment]
That's the point, there are no logs. It just crashes and comes back up again. I'm running LibreELEC. There's nothing in the logs - at least not in the `kodi.log`. The log simply ends. The system then restarts the Kodi service when it goes down and the sync starts all over again.

In my despair I have resorted to `while true; do sleep 600; systemctl restart kodi.service; done`, that way I get at least 10 minutes worth of progress every time.

**Comment by Tomalak** [comment]
@croneter I don't really suspect PKC to be responsible for the crash. Maybe it's only a set of unfortunate circumstances. Maybe it's hardware-related, who knows.

That the sync starts from scratch every time is the puzzling thing here. Only a graceful shutdown of Kodi (either through a service restart or through `SIGTERM`) seems to write the changes to the database.

**Comment by croneter** [comment]
Nevertheless - could you please share 2 consecutive logs, the second one right after the crash of the first one? I could then have a look

**Comment by croneter** [comment]
Could you also enable debug logging on the Kodi side, please? Might help... 

Does your free memory go down while the sync is on progress?

**Comment by Tomalak** [comment]
I could set up a new Kodi profile and initiate a new sync on a freshly set-up PKC instance, but that would take a while. Currently the repeated restarting of the Kodi service prevents crashes and interrupted syncs. I've done too much other stuff in parallel today so that the current logs may contain red herrings.

Suffice it to say, there are crash logs that are filled with thousands of lines of `UPDATE artist:` and `ADD song` notices with no errors in-between that abruptly end with no hint towards any problem whatsoever. 

I believe you can reproduce the whole thing by killing Kodi forcefully (`kill -9` or equivalent) during a running sync. 

The RAM does not go down with plenty of RAM free and the flash memory has plenty of space available as well. The sync was successful once before as well, so I am positive that it works in principle. It just doesn't finish successfully in a single go.

**Comment by croneter** [comment]
I just checked again - partial sync progress here on my machines stays; syncing music does not start at 0 should I forcefully restart Kodi. 

Since you're not sharing any logs, I can't help you. Please reopen the tickets once you can share logs, thx

**Comment by Tomalak** [comment]
I'm rather busy at the moment, sorry. Closing is fine, I will report back when I figure out the steps to reproduce. Will post a log then as well.
