### ISSUE TITLE
ERROR: Unable to start PlexCompanion after Kodi profile log off/log on

### ISSUE THREAD

**Issue by Tomalak** [croneter/PlexKodiConnect#293]
Plex companion throws an `Address already in use` socket error when the current Kodi profile is logged out and and logged in again:

```
07:43:11.790 T:1566765984  NOTICE: PLEX.PlexCompanion -> ERROR: Unable to start PlexCompanion. Traceback:
07:43:11.791 T:1566765984   ERROR: Traceback (most recent call last):
07:43:11.791 T:1566765984   ERROR:   File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/PlexCompanion.py", line 174, in run
07:43:11.791 T:1566765984   ERROR:     listener.MyHandler)
07:43:11.791 T:1566765984   ERROR:   File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/plexbmchelper/listener.py", line 190, in __init__
07:43:11.791 T:1566765984   ERROR:     HTTPServer.__init__(self, *args, **kwargs)
07:43:11.791 T:1566765984   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
07:43:11.791 T:1566765984   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
07:43:11.792 T:1566765984   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
07:43:11.792 T:1566765984   ERROR:   File "/usr/lib/python2.7/socket.py", line 228, in meth
07:43:11.792 T:1566765984   ERROR: error: [Errno 98] Address already in use
```

Steps to reproduce:

- Create separate Kodi profile and load it
- Enable KPC and log into a PMS (the rest of the default configuration is fine)
- Optionally increase KPC log level
- Log out current user
- Log back in the same user
- The error about Plex companion appears

Expected behavior:
- The life-cycle of Plex companion should be symmetric. It obviously starts when a user logs in, so it should stop when a user logs out.

**Comment by Tomalak** [comment]
Hold on, apparently there are more factors involved. When the error shows up again I'll post an update.

**Comment by Tomalak** [comment]
In any case, Plex Companion stays running even after a Kodi profile switch. I believe it should shut down when the profile its configuration is associated to is unloaded.

**Comment by croneter** [comment]
Please share a log. I'd expect to see/not see a line saying `----===## Plex Companion stopped ##===----`

**Comment by Tomalak** [comment]
Yup, there seems to be a hang of the Plex Companion thread involved which I need to provoke first.

**Comment by Tomalak** [comment]
@croneter Could have been it. I'll update to the next beta and if that crops up again I'll say something.
