### ISSUE TITLE
Missing collections for certain languages

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#294]
Kodi collections are missing, e.g. for French

**Comment by croneter** [comment]
Cannot reproduce this, even with full DB reset while language is set to French

**Comment by onlyyou** [comment]
what can i do to help you (log ?)

**Comment by croneter** [comment]
Thanks :-). For getting a log, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

* Find a Kodi movie set with Plex web: you're looking for a "Plex Collection" (https://support.plex.tv/hc/en-us/articles/201273953-Collections). If you don't have one, quickly create one with 2 movies in it
* Enable PKC debug logging as explained in the link above
* Make sure that Kodi sets are shown: http://kodi.wiki/view/Movie_sets
* Make sure that your Kodi language is set to French (I hope you speak French ;-))
* Reset the Kodi DB by going to the PKC settings, Advanced, `Reset the Kodi database...` (in red)
* Let Kodi resync completely, capturing everything in the log
* Immediately (without restarting) check whether you can discover the movie set from above in Kodi, capturing everything in the log
* Share the log ;-)

**Comment by croneter** [comment]
I cannot reproduce this. Anyone out there experiencing this issue? Otherwise I'll close this issue

**Comment by croneter** [comment]
No, I still need logs as explained above

**Comment by onlyyou** [comment]
ok, i will today,
2 questions :
- reset DB is necessary ?
- where is located the log (shield TV)
thx

2017-05-16 10:37 GMT+02:00 croneter <notifications@github.com>:

**Comment by croneter** [comment]
* Yes, reset DB necessary. Please follow my step-by-step-guide in the comment above
* As always https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by onlyyou** [comment]
hey, after some tests and trying to make the log, i realized it was so my bad. In fact, i was tr to find "collection" (the word also exists and means the same in french) but now that PKC is in french, i should look inside "sagas" and didn't find my "collections" menus anymore. Plex itself also call them "collection" even in french settings. And not "sagas". So I was lost, but it was there. Sorry again... it is a bit confusing
I just have to re configure my widgets and sub menu shortcuts and now all is good.

**Comment by croneter** [comment]
You could help with these miss-leading translations 😉 
https://www.transifex.com/croneter/pkc

**Comment by onlyyou** [comment]
just joined the team
my english is not perfect, but think i can help with some french words ;)

2017-05-17 9:57 GMT+02:00 croneter <notifications@github.com>:
