### ISSUE TITLE
PKC syncing progress to wrong account

### ISSUE THREAD

**Issue by vmirage** [croneter/PlexKodiConnect#297]
Here's the scenario
Plex Android : Account A
PKC : Account B
Plex Server : Owned by Account A, Shared to Account B

Plex Android fling video to PKC. Video progress is somehow synced to Account B instead of Account A

**Comment by croneter** [comment]
What happens if you substitute PKC with e.g. Plex Web? Would Account A or Account B get synced?

**Comment by vmirage** [comment]
It syncs to Account A

**Comment by croneter** [comment]
This is a tough one. I fathom that it still doesn't work for you with the new Beta?

**Comment by vmirage** [comment]
Nope doesn't work. I'm using beta.
