### ISSUE TITLE
PKC Saying File doesn't exist, yet Plex plays it fine

### ISSUE THREAD

**Issue by TheHeroBilly** [croneter/PlexKodiConnect#299]
Occasionally I'll have a movie say that it isn't available or can't be found in Kodi, yet Plex plays it just fine, any ideas as to why?

I have the Native set up, and everything else is stock settings.

**Comment by croneter** [comment]
As always - no help without log files possible 
https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by TheHeroBilly** [comment]
I think I cleaned out the right tokens/passwords.
[kodi.old.log.txt](https://github.com/croneter/PlexKodiConnect/files/1016123/kodi.old.log.txt)

**Comment by croneter** [comment]
Enable DEBUG logging in the PKC settings from now on please.

Your Direct Paths setup seems a bit off:
```
NOTICE: VideoPlayer: Opening: smb://D/Movies/10,000 BC/10,000 BC.MP4
ERROR: XFILE::CDirectory::GetDirectory - Error getting smb://D/Movies/10,000 BC/
ERROR: CVideoPlayer::OpenInputStream - error opening [smb://D/Movies/10,000 BC/10,000 BC.MP4]
```
Your media server is probably not called "D", is it? Please revisit https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths

**Comment by croneter** [comment]
Closing this issue as it's a configuration failure on your side

**Comment by TheHeroBilly** [comment]
For whatever reason, something on my network doesn't like the Direct Paths root. Had to set up as addon.
