### ISSUE TITLE
PKC - TV Shows play fine, Movies suddenly dont

### ISSUE THREAD

**Issue by MrDownstream** [croneter/PlexKodiConnect#301]
Hey guys,
suddenly i cant play anymore movies on my android tv box with pkc installed. Strangely enough i didnt make any changes to the settings what so ever. Last week movies would still run on the setup (Kodi 17.1, PKC latest build).
Another strange thing is that tv shows still play fine.
What i notice on playing a movie: The movie loads up correctly, it shows title and length of the film. Still the tv stays black, whilst the movie seems to be playing in the background (the position counter of the movie is increasing). Also when i jump to a certain time of the movie, it shows the image of the movie to that second and nothing more.
Here is my Debug Log https://paste.ubuntu.com/24633260/
Right now im trying to reset my pkc db because it was mentioned in some of croneters answers on a thread where someone had a similar problem.
Someone of you knows whats going on here?

**Comment by croneter** [comment]
Your did not delete your Plex token from the log file! Please immediately reset your Plex tokens, otherwise anyone can log in to your Plex account!

**Comment by MrDownstream** [comment]
Jah forget to delete them. Ok thanks for the advice...

**Comment by MrDownstream** [comment]
Btw. i fixed the problem. The problem seemed to be that when audio passthrough was enabled with dts-hd, it led to the problem i had. When i deactivated dts-hd everything played fine again.
