### ISSUE TITLE
PKC unable to create Kodi advancedsettings.xml 

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#302]
> Going back to the "misconfigured" advancedsettings.xml. It seems to be PKC creating it at every Kodi start when I choose to include my music library causing the synchronisation to crash. When I disable music in the PKC settings everything works fine and the advancedsettings.xml is not created. Also any present advancedsettings.xml is overwritten by this incomplete file.I attached the advancedsettings.xml as it is created automatically. I also checked my paths, they are all as they should be. No clue why this is entered.And up to version 1.7.11 everything worked fine.

**Comment by croneter** [comment]
Could you share all your music paths here? Such as 'smb://ReadyNAS312/Audio/Audiobooks'

**Comment by Bab72de** [comment]
The music paths at the moment are smb://ReadyNAS312/Audio/Audiobooks and smb://ReadyNAS312/Audio/Musik
Audiobooks obviously is the first entry to be scanned.

**Comment by croneter** [comment]
Could you please share your entire log? 
https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by Bab72de** [comment]
I have a few busy days ahead of me, but I will get back to you as soon as possible with the log.
When I try to include my Plex music libraries the advancedsettings.xml is created on every reboot and PKC crashes.
When I deactivate the music library in PKC no advancedsettings.xml is created at all.
The only special characters I have in a few subfolders are German umlauts, which never has been a problem before.
The Plex server is version 1.5.5.3634 on a Netgear ReadyNAS and Kodi is version 17.1 on a FireTV 2.

**Comment by Bab72de** [comment]
Here is the log with Debug enabled.
[kodi.log.txt](https://github.com/croneter/PlexKodiConnect/files/1035179/kodi.log.txt)

**Comment by croneter** [comment]
I'm afraid that PKC killed your advancedsettings. If the new PKC version 1.8.1 is still complaining, simply delete advancedsettings.xml again and everything should be fine

**Comment by Bab72de** [comment]
With the new version everything works again as it should be, even the film collections got their covers back.
Thank you for your hard work.
