### ISSUE TITLE
"On Deck" widget doesn't always display content

### ISSUE THREAD

**Issue by mrsilver76** [croneter/PlexKodiConnect#306]
I'm running Kodi 17.3 with the Estuary Mod and the latest version of PlexKodiConnect.

I've added a "Television" option to the main menu, linked it to Plex (which works great) and I've added two widgets ("Recently Added" and "On Deck") to mirror that of Plex.

However the "On Deck" widget seems to not work consistently. Often it won't show at all, but when you go into the television shows and then come back out again it'll display. After a random amount of time elsewhere in Kodi, you'll go back to the main menu and it'll stop displaying again.

Throughout the entire time "Recently Added" shows all the time.

I've attached my logfile but there isn't anything in there which would immediately pop out at me as to why it's sometimes unable to display the results of "On Deck".

Many thanks in advance.

[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/1050641/kodi.zip)

**Comment by mrsilver76** [comment]
Turns out that I can view "On Deck", navigate down one menu item, move back up again 30 seconds later and "On Deck" will have disappeared. This isn't consistent, sometimes it will show.

What I do know is that as soon as "On Deck" disappears, the only way to get it back seems to be to go into the full Television list and then back out again.

I have three other Movie folders which also exhibit the same behaviour.

**Comment by croneter** [comment]
```
20:17:13.079 T:3520 WARNING: Skin Helper Service --> Traceback (most recent call last):
                                              File "C:\Users\Media\AppData\Roaming\Kodi\addons\script.skin.helper.service\resources\lib\listitem_monitor.py", line 314, in set_listitem_details
                                                details["year"], details["imdbnumber"], details["tvshowtitle"])
                                              File "C:\Users\Media\AppData\Roaming\Kodi\addons\script.module.simplecache\lib\simplecache.py", line 284, in decorated
                                                result = func(*args, **kwargs)
                                              File "C:\Users\Media\AppData\Roaming\Kodi\addons\script.module.metadatautils\lib\metadatautils.py", line 277, in get_imdbtvdb_id
                                                "", title, year, content_type).get("imdbnumber", "")
                                            AttributeError: 'NoneType' object has no attribute 'get'
20:17:13.079 T:3520   ERROR: Skin Helper Service --> Exception in resources.lib.listitem_monitor ! --> 'NoneType' object has no attribute 'get'
```
This is to 99.9% related to the skin you're using. Try another one that is more stable. As a check, navigate to Videos -> Addons -> Plexkodiconnect -> some movie folder -> On Deck a couple of times and see whether you get any content

Closing issue since this is most likely skin-related. Re-open if you disagree
