### ISSUE TITLE
Direct play from another player because Nvidia Shield TV is plex server

### ISSUE THREAD

**Issue by destriktion** [croneter/PlexKodiConnect#307]
My Shield TV is in function as plex Server. On the shield, direct play is in function without problems.
But on NO other players does direct play (Fire TV Stick or Galaxy Tab A). The dirct path on  plex server (shield tv) is "/storage/film or /storage/series. Fire TV or Galaxy Tab didn't find the path. They need normaly SMB path, but plex server on shield makes the smb path as storage like an sd kard or external hdd. I hope you know what i mean.

Many thanks for the search for a solution.

Sorry for my bad english.

**Comment by croneter** [comment]
Sorry, this is a configuration challenge, NOT a PKC issue. Please try the Plex forum

**Comment by croneter** [comment]
"Workaround": use addon paths

**Comment by hstamas** [comment]
@destriktion just so you don't go crazy trying to get things figured out, SMB access to the Shield is well known to be very difficult to get working. I believe its a known bug.
