### ISSUE TITLE
First Music artist is <missing>

### ISSUE THREAD

**Issue by ddanielww** [croneter/PlexKodiConnect#308]
All artist have a name apart from the first in the list , has this already been reported ? And is there a way to fix ?

**Comment by croneter** [comment]
I have no idea what you mean. Could you be more specific?

**Comment by ddanielww** [comment]
When I go into the music library and select artists, the first entry is missing the artist name, however , all other artist's names display correctly. I've done a full refresh and it's always the first artist that has a name of (missing).

**Comment by croneter** [comment]
Emby for Kodi has the same issue: https://emby.media/community/index.php?/topic/44809-artist-name-missing-in-kodi/

**Comment by ddanielww** [comment]
I read they implementation a fix to skip the first ID and its resolved the issue,can this be done with this ?

**Comment by croneter** [comment]
Don't know, try it

**Comment by ddanielww** [comment]
The developers of emby integration implemented a fix. I was hoping the developers here could fix it for a future update as I don't know where to start.

**Comment by AzraelDD** [comment]
Kodi 17.6, Git:20171114-a9a7a20

Hi everyone,
for me this issue still exists with ".wma" music files. The first artist of a list of several artists is not displayed. Files with a single artist work fine. ".mp3" music files do not show this issue.
