### ISSUE TITLE
Options are invisible

### ISSUE THREAD

**Issue by raidersan** [croneter/PlexKodiConnect#309]
When I try to set PKC up in options, the lines are blank, but I can see radio buttons on some lines and I can scroll down and select and de-select those, but I have no text shown so I dont know how to set it up.
I am running on a box midnight, with Gotham.

**Comment by croneter** [comment]
* log of you entering the settings: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug
* what language is your Kodi set to? 
* any other Kodi add ons that do work or do not work?

**Comment by croneter** [comment]
Also, try another skin

**Comment by raidersan** [comment]
Thanks for your prompt answer. Default language, English. I have changed to skin back to default and tried a few more, no difference. All other add-ons working fine.

**Comment by croneter** [comment]
Logs please!

Have you tried reinstalling PKC?

Am 17.06.2017 21:58 schrieb "raidersan" <notifications@github.com>:

**Comment by raidersan** [comment]
I have tried re-installing to no avail. I cannot think of a way to get at the logs as I do not see an option to enable SSH and the system is pretty much frozen booting kodi, so no option to install SSHD, unless you know?

**Comment by croneter** [comment]
Dude, that sound like your Kodi is pretty screwed up anyway. PKC is probably not the problem here...

You can use an addon to get the log file: http://kodi.wiki/view/Log_file/Easy

Other than that, I **do** need a log file otherwise I can't help you

**Comment by raidersan** [comment]
Apologies I expressed myself poorly there. I dont mean to say Kodi is frozen on boot up, I mean that it is a locked down system, to load anything you need to flash an iso image that has been encrypted, basically impossible to modify the filesystem itself. But Kodi works very well on it, I have never had an issue with addons, I am puzzled by what I am seeing with PDC. I will install the log addon as soon as I am back home. Thanks for your help!

**Comment by croneter** [comment]
Any update?

**Comment by croneter** [comment]
Closing as there is no more feedback
