### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by ddanielww** [croneter/PlexKodiConnect#310]
I watch an episode of a show but when I go to the on deck view it doesn't update to the next episode untill I perform a manually library update. Should I not update automatically or does it require 5 items to change before it gets updated ?

**Comment by ddanielww** [comment]
I have constant background sync already enabled ?

**Comment by ddanielww** [comment]
And I'm logged in as the master user, it's my own server.

**Comment by croneter** [comment]
Try another skin; the skin sometimes doesn't do well with updating. 

Other than that: share a log file of this issue actually happening: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Any update?

**Comment by croneter** [comment]
Closing as there is no more feedback nor a log
