### ISSUE TITLE
Extremely slow installation through repository 

### ISSUE THREAD

**Issue by kabeza** [croneter/PlexKodiConnect#312]
Hi
Using RBP3 with osmc/kodi (latest stable) I decided to give plexkodiconnect a chance and to replace plexbmc
I moved the repository zip file downloaded here into RBP3 then installed, but when I went to install from repository, it just took soooooo long
It looks like it connects to TOR through China and keeps waiting til it shows menu, etc. 
Tested speed, installing other addons, and all went fine

Just that. Thanks

**Comment by croneter** [comment]
There is no TOR involved - it'll download directly from bintray.com. No idea how sketchy your other add-ons or osmc are... 

What exactly is slow? PKC itself is only a couple of kilobytes big. The initial sync?

**Comment by kabeza** [comment]
I know, i was mocking about "TOR" @croneter 
I put the zip file (repository) and installed it through Kodi. This went ok
Then, I went to install from Repository "Plexkodiconnect addons"

The process of connecting to repository, listing its folders, going to video addons, and downloading/installing plexkodiconnect was the one that lasted very loooong time. the screen sometimes dimmed so i had to move the mouse...

Once I could download it, it installed correctly, the wizzard started with the questions, etc. and all went incredibly great. It is working great.

Thanks

**Comment by croneter** [comment]
Mocking is hard to understand in issues 😉 

Very weird. Did you install the stable or beta repository?

**Comment by kabeza** [comment]
stable

**Comment by croneter** [comment]
Just double checked - absolutely no issue on my side. Maybe bintray.com was just slow. 

Still experiencing the issue? If so: Could you please share a debug log with KODI debug logging also enabled? See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Additionally enable Kodi debug logging: http://kodi.wiki/view/Log_file/Advanced

**Comment by kabeza** [comment]
Hey
No, didn't experience issue again because i hadn't installed PKC again
I'm almost sure bintray.com was slow at the time I installed last week

**Comment by croneter** [comment]
OK thanks. 

Closing as there's nothing we can do on the PKC (except switching away from bintray.com ;-))
