### ISSUE TITLE
When logging off of Kodi with addon enabled, system locks up.

### ISSUE THREAD

**Issue by vampyrex13** [croneter/PlexKodiConnect#313]
It doesn't matter if I log right into Kodi, or wait several minutes, but when I log off (to switch to another profile), my system freezes. Sometimes for minutes, sometimes it completely crashes Kodi (Plex will still be running fine in the background as I can access it from my tablet). It does this 85% of the time. My Plex database exists on the same server as Kodi.

**Comment by croneter** [comment]
I cannot help you without log files - https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by vampyrex13** [comment]
I will post a log today.

**Comment by vampyrex13** [comment]
Go figure. I enable debugging days ago, and now it refuses to crash. When it does, I will post the log.

**Comment by croneter** [comment]
Please reopen this issue if it appears again
