### ISSUE TITLE
New requests

### ISSUE THREAD

**Issue by jmulvaney1** [croneter/PlexKodiConnect#315]
Unable to log a new request from http://feathub.com/croneter/PlexKodiConnect (I cannot load page  - site cannot be reached)

The request I would ask if I could, is for a feature add to delete watched TV and Movies (different options for each) during\before\after sync.

TV Options - Delete parent folder and all content (incl subdir) if no other video files remain (yes\no)
Movie Options - Delete parent folder and all content (yes\no)

Perhaps an other option if watched more than X days ago.  And watched status full or partial.

**Comment by croneter** [comment]
Feathub.com is online again and I opened a new request: http://feathub.com/croneter/PlexKodiConnect/+32

You still need to vote there, though
