### ISSUE TITLE
View per Library

### ISSUE THREAD

**Issue by arnold-maderthaner** [croneter/PlexKodiConnect#316]
I have several different libraries (like movies, private movies,...) but when I use PKC within KODI I see all movies from the different libraries in "Movies" in Kodi. Is there a way to configure PKC to show the different libraries instead of a "mixed" Movies section in Kodi ?

**Comment by croneter** [comment]
Of course there is, as stated e.g. in the FAQs: https://github.com/croneter/PlexKodiConnect/wiki/faq

See here for a detailed manual: https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins
