### ISSUE TITLE
Wrong audio language selection

### ISSUE THREAD

**Issue by arnold-maderthaner** [croneter/PlexKodiConnect#317]
I have setuped PKC but whenever I start an episode from a shared plex library it switches to english (but my default setting for my plex user is set to german). How can I force PKC to use german ?

**Comment by croneter** [comment]
Googling the Kodi-side-of-things should help you with these questions. Does this help? https://forum.kodi.tv/showthread.php?tid=163314

**Comment by RickDB** [comment]
Also you can use the Language Preference manager addon to allow better selection:

https://forum.kodi.tv/showthread.php?tid=153783
