### ISSUE TITLE
PlexKodiConnect causes Kodi LiveTV (PVR) Failures

### ISSUE THREAD

**Issue by pahrohfit** [croneter/PlexKodiConnect#318]
When enabled, the plex helper is trying to snatch all of the PVR video stream calls, and sends them to plex to find media information.  This happens for Addon and Direct setup methods.

Need a way to tell it to ignore certain player calls, or only listen for certain calls.

The same happens for the 'Arials' screensaver (snippet):

`00:19:02.420 T:1158607776  NOTICE: PLEX.playlist_func -> ERROR: Could not get new playlist Version for playlist <Playqueue_Object: ID: 9565, items: [<Playlist_Item: kodi_id: None, uri: library://whatever/item/http%3A%2F%2Fa1.phobos.apple.com%2Fus%2Fr1000%2F000%2FFeatures%2Fatv%2FAutumnResources%2Fvideos%2Fcomp_DB_D011_C010_v10_6Mbps.mov, kodi_type: unknown, file: http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_DB_D011_C010_v10_6Mbps.mov, plex_type: None, plex_id: None>, <Playlist_Item: kodi_id: None, uri: library://whatever/item/http%3A%2F%2Fa1.phobos.apple.com%2Fus%2Fr1000%2F000%2FFeatures%2Fatv%2FAutumnResources%2Fvideos%2Fb4-1.mov, kodi_type: unknown, file: http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b4-1.mov, plex_type: None, plex_id: None>, <Playlist_Item: kodi_id: None, uri: library://whatever/item/http%3A%2F%2Fa1.phobos.apple.com%2Fus%2Fr1000%2F000%2FFeatures%2Fatv%2FAutumnResources%2Fvideos%2Fcomp_DB_D001_C005_t9_6M_HB_tag0.mov, kodi_type: unknown, file: http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_DB_D001_C005_t9_6M_HB_tag0.mov, plex_type: None, plex_id: None>, <Playlist_Item: kodi_id: None, uri: library://whatever/item/http%3A%2F%2Fa1.phobos.apple.com%2Fus%2Fr1000%2F000%2FFeatures%2Fatv%2FAutumnResources%2Fvideos%2Fb5-3.mov, kodi_type: unknown, file: http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b5-3.mov, plex_type: None, plex_id: None>, <Playlist_Item: kodi_id: None, uri: library://whatever/item/http%3A%2F%2Fa1.phobos.apple.com%2Fus%2Fr1000%2F000%2FFeatures%2Fatv%2FAutumnResources%2Fvideos%2Fb9-3.mov, kodi_type: unknown, file: http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b9-3.mov, plex_type: None, plex_id: None>, <Playlist_Item: kodi_id: None, uri: library://whatever/item/http%3A%2F%2Fa1.phobos.apple.com%2Fus%2Fr1000%2F000%2FFeatures%2Fatv%2FAutumnResources%2Fvideos%2Fb6-3.mov, kodi_type: unknown, file: http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b6-3.mov, plex_type: None, plex_id: None>, <Playlist_Item: kodi_id: None, uri: library://whatever/item/http%3A%2F%2Fa1.phobos.apple.com%2Fus%2Fr1000%2F000%2FFeatures%2Fatv%2FAutumnResources%2Fvideos%2Fb3-1.mov, kodi_type: unknown, file: http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b3-1.mov, plex_type: None, plex_id: None>], shuffled: 0, playlistid: 1, version: 1, old_kodi_pl: [{u'title': u'Dubai by night', u'type': u'unknown', u'file': u'http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_DB_D011_C010_v10_6Mbps.mov', u'label': u'Dubai by night'}, {u'title': u'Hawaii by day', u'type': u'unknown', u'file': u'http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b4-1.mov', u'label': u'Hawaii by day'}, {u'title': u'Dubai by day', u'type': u'unknown', u'file': u'http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_DB_D001_C005_t9_6M_HB_tag0.mov', u'label': u'Dubai by day'}, {u'title': u'San Francisco by night', u'type': u'unknown', u'file': u'http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b5-3.mov', u'label': u'San Francisco by night'}, {u'title': u'San Francisco by day', u'type': u'unknown', u'file': u'http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b9-3.mov', u'label': u'San Francisco by day'}, {u'title': u'London by day', u'type': u'unknown', u'file': u'http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b6-3.mov', u'label': u'London by day'}, {u'title': u'London by night', u'type': u'unknown', u'file': u'http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b3-1.mov', u'label': u'London by night'}, {u'title': u'San Francisco by day', u'type': u'unknown', u'file': u'http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b8-2.mov', u'label': u'San Francisco`

**Comment by tbrasser** [comment]
I'm having the exact same problems since a full pkc reset (needed for direct play and music library changes on my side). Trying to watch PVR (TVHeadend in my case) and every channel plays for 1 sec then hangs. ( latest stable LibreElec on Raspberry Pi 3)

**Comment by croneter** [comment]
@pahrohfit 
What are your issues besides errors in the log? Lags or hang ups as well?

**Comment by pahrohfit** [comment]
The screensaver was just easier to point to -- it tries to load, then bails, then stutters, then loads.

The PVR, figured it'd be harder for you if you don't have a unit, has fundamental failures.  Channels won't load, sometimes hitting pause then play works or change channel then change back, others not.  If I click around too much (changing channels down/up), I often end up with a "stuck" system, needing a reboot to recover.  The looks like pretty similar to the above.

**Comment by tbrasser** [comment]
@croneter , any updates? In Addon playback mode I get the notification that sync had to skip some items. So I'd prefer to use the Direct/Native option.

**Comment by croneter** [comment]
Please DO share the debug logs of PKC having to skip some items in Addon mode! There shouldn't be any issues anymore. See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug and don't forget to enable PKC debug logging

**Comment by croneter** [comment]
Open a new issue, obviously ;-)

**Comment by croneter** [comment]
Sorry guys, need more info here, the snippet is not enough. Please share your entire logs as described here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

@tbrasser 
I'd really appreciate you also sharing logs of PKC having sync issues!

**Comment by tbrasser** [comment]
I'm going back to Kodi v17 now, I was testing some v18 builds the past few weeks so I couldn't provide any useful info.

**Comment by croneter** [comment]
Guys, I need some logs here as I don't have pvr set-up

**Comment by croneter** [comment]
Closing since I got no further feedback. 

If this still an issue, please [share debug logs](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug) as I cannot read minds!
