### ISSUE TITLE
Paused PKC keeps overwriting watched status

### ISSUE THREAD

**Issue by WoLpH** [croneter/PlexKodiConnect#319]
This bug is very easy to reproduce luckily so it shouldn't be too hard to debug :)

1. Start playing an episode for some series
2. Pause it halfway (or wherever)
3. Play the same episode through Plex in a different location until finished (for example, your phone)
4. Notice that PKC resets the resume point to where it was paused even though the other client marked it as watched by now.

Perhaps this can be fixed by keeping track of the last sent state? If it hasn't changed internally, don't send it again?

**Comment by croneter** [comment]
What happens if you substitute PKC with e.g. Plex for Android? Does that work like you desire?

My guess is No ;-)

**Comment by croneter** [comment]
Thing is that this is really, really hard to fix

**Comment by WoLpH** [comment]
I switched to PKC a few months ago and I didn't have that problem before so I'm certain it's related to PKC. Before I used the "regular" Plex (Kodi based) player and/or OpenPHT which didn't have this issue.

So far I I haven't had the problem with the Plex for Android app either but I haven't done extensive testing there.

Generally the situation looks like this:
1. Start watching an episode on my workstation
2. Continue watching the episode on my mediacenter

Sometimes the other way around, but that's about it.


I'm aware of how difficult conflict resolution can be and I'm not sure if Plex allows for a perfect solution. Ideally you would simply use the "newest" state in all cases but I'm not sure if that information is available with Plex.

Can I assume that this is the function call I should be looking at? https://github.com/croneter/PlexKodiConnect/blob/develop/resources/lib/PlexFunctions.py#L450-L466
I can try to find a working solution for the sync problems if I know which endpoints are used :)

**Comment by croneter** [comment]
I see the issue. Problem is, of course, that you're **pausing** and not **stopping** playback on the Kodi side. 

Fixing this is way more complex than just the function you cited, unfortunately...

**Comment by jmulvaney1** [comment]
What about if you used Trakt integration? On 6 Jul. 2017 17:12, croneter <notifications@github.com> wrote:I see the issue. Problem is, of course, that you're pausing and not stopping playback on the Kodi side.
Fixing this is way more complex than just the function you cited, unfortunately...

**Comment by croneter** [comment]
No -  I do not want to introduce any dependencies

**Comment by WoLpH** [comment]
I suppos I could stop playback instead of pausing it but I don't really understand why they're handled differently. 

Is it not possible to only send updates if something changed on your end? Or is it difficult to maintain and compare the previous state?

**Comment by croneter** [comment]
* If you only pause playback, I'd assume that you will soon resume playback. The movie's progress is thus focused on that particular device (no matter what you're doing on other devices) 
* If you stop playback, that's an entirely different matter

The playstate updates from PKC to the PMS would need additional logic

**Comment by WoLpH** [comment]
I've done a bit of checking with OpenPHT and it seems that it's continuously (live) updating the play state on both instances. While OpenPHT is playing on my laptop it's sending the state to Plex every few seconds and when I press play on OpenPHT on my workstation it's resume state is correct with perhaps a few seconds offset.

@croneter: Can you give me any explanation as to how it currently functions so I know where I can start debugging the issue and possibly improve upon the current sync system?

Unfortunately it seems the connection to plex is either binary or encrypted because I couldn't get anywhere with wireshark yet.

**Comment by croneter** [comment]
Sorry, been really busy. 

If you find the time, this issue is caused by https://github.com/croneter/PlexKodiConnect/blob/master/resources/lib/plexbmchelper/subscribers.py (or somewhere close to it). The XMLs being sent there would need to be checked for changes before being sent (no change=don't send). 

If you want to get Wireshark fired up, simply deactivate secure connections on your PMS

**Comment by WoLpH** [comment]
No worries, I know the problem... I have pull requests and issues open on some of my projects which have been there for months (some, years). It's hard to balance everything :)

Anyway, thanks for the info, I'll take a look. Right now I'm bouncing between OpenPHT en PKC which is less than ideal, OpenPHT does a lot right but has a few annoying bugs and isn't maintained anymore so that's an end of line thing. PKC is obviously the right direction but needs a few small tweaks to function for me :)

**Comment by croneter** [comment]
Good to hear! 

What tweaks are you thinking of?

**Comment by WoLpH** [comment]
Sync issues have been bugging me the most, whereas OpenPHT appears to sync as soon as you enter a TV series, with PKC it appears to be scheduled which means it's often out of date for me.

**Comment by croneter** [comment]
That should definitely NOT be the case! Please share logs, you know the drill :wink:

We're only talking watched status here, not actual new Plex items, correct?

**Comment by WoLpH** [comment]
Well, let me clarify. It's not out of date for that long, it always syncs soon after but there's an obvious (and visible) sync step which I've never seen with (Open)PHT. No need to worry about it, but I think it can be streamlined somehow, perhaps keep a connection open to PMS or something... I'll figure something out :)
