### ISSUE TITLE
After playback is finished, screen switches to black (not off)

### ISSUE THREAD

**Issue by hanzoh** [croneter/PlexKodiConnect#32]
Hello,

I'm on 1.1.8 on LibreELEC 7.0.0 (Kodi 16.1) and in some cases, the screen goes to black after playback of a video file is finished. This means I don't hit stop but let it run till the end.

I have refresh rate switching enabled, so in most cases it switches to 24Hz during playback and then back to 50Hz for the Kodi menu.

The funny thing is that Kodi has no crashed, if I hit DOWN and OK on the remote, it starts the playback of the next episode, switches to 24Hz and shows the video. When I then hit stop, it switches to 50Hz and shows me the Kodi menu again.

Do you see anything related to PKC or is this a Kodi/driver issue?

Kind regards
hanzoh
[kodi.log.txt](https://github.com/croneter/PlexKodiConnect/files/261727/kodi.log.txt)

**Comment by croneter** [comment]
I don't see anything suspicious from PKC in the logs. PKC only gives Kodi the "handle" to start playing a Plex file anyway - everything else is handled by Kodi.
