### ISSUE TITLE
A channel does not work

### ISSUE THREAD

**Issue by MineProjectZ** [croneter/PlexKodiConnect#321]
when i try to start a video from a channel it fails.

**Comment by croneter** [comment]
How about sharing some specifics? 
* What channel are you talking about?
* Do other channels work?
* Please share your PKC debug logs with PKC debug logging enabled for the video failing to play: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Any news here? Otherwise I'll close the issue

**Comment by MineProjectZ** [comment]
the youtube channel dont work

**Comment by croneter** [comment]
That's because the Plex channel `YouTube` is broken. This has nothing to do with PlexKodiConnect, sorry
