### ISSUE TITLE
PKC also listed as photo addon, way to set this up?

### ISSUE THREAD

**Issue by tbrasser** [croneter/PlexKodiConnect#325]
In the settings of PKC and in the addons section, there is mention of photo library functionality. However I can't find anything about it on the wiki.

Since I use direct play / native paths / etc, is there anything more that I can do with Kodi + PKC than just browsing the folder (and the pictures within) via navigating through kodi?

It would be cool to have a few of Plex's photo library tags show up in Kodi (like they do for TV Shows and Movies; recently added, etc)

I kinda want to use the standard kodi 17 skin (it's getting even better in kodi 18) (When kodi 18 is out I think Estuary MODV2 + Kodi 18 + PKC is an awesome combination that would make media consumption and management for once a pleasure to use) 

I guess basically my questions are: 1, does PKC offer this, and 2, is there a (preffered) (actively maintained) skin to use for full PKC integration into kodi / the home screen. (Since all I have tried are either really elaborate and make kodi far less intuitive to use or are looking good but are broken in some way.)

**Comment by croneter** [comment]
Sorry, this is not an issue. Please either use [the Plex forums](http://forums.plex.tv/discussion/210023/plexkodiconnect-let-kodi-talk-to-your-plex/p1) for your questions, or make a very specific [feature request on feathub.com](http://feathub.com/croneter/PlexKodiConnect)

**Comment by tbrasser** [comment]
Oh man, how have I never seen that thread before. Thanks for the link (maybe add it to the Readme?)! I'll scan through there for answers on my questions (and if I can't find any I'll add a comment).
