### ISSUE TITLE
'Sync Completed' banner/notification not disappearing

### ISSUE THREAD

**Issue by pheare** [croneter/PlexKodiConnect#326]
I use pkc on a shield. I have an issue where if I keep kodi running and minimize it (or whatever the android equivalent is) and the hourly sync occurs while in that minimized state, when I maximize kodi, the 'sync completed' banner/notification displays and will not go away. 

The only way I can get rid of it is by quitting kodi and restarting. Notification disappears on its own if the sync happens while kodi is maximized.

**Comment by croneter** [comment]
Just FYI: this is actually a Kodi bug 😉 . But I'll implement an option to completely disable these PKC notifications as a workaround

**Comment by pheare** [comment]
I actually kind of thought it may be a kodi issue...

Thanks for the workaround!
