### ISSUE TITLE
Video sounds plays but no video or controls show

### ISSUE THREAD

**Issue by 8bitgentleman** [croneter/PlexKodiConnect#327]
Recently I've had an issue with PKC where certain movies/shows in my Plex library will play audio not video when I try to play them. There's nothing wrong with the media, it plays just fine on other devices and from Plex directly. What could be going on here?

**Comment by croneter** [comment]
I'm 99% sure that this is a Kodi issue, not a PKC issue. PKC hands over the file for Kodi to play. Have you tried the numerous suggestions to fix this? See e.g.
* https://www.google.ch/search?q=kodi+plays+audio+no+video
* Windows: https://forum.kodi.tv/showthread.php?tid=138652&pid=1456627#pid1456627

Seems mostly dependent on your Kodi box/OS...

Other than that: since I'm no prophet, [logs would be in order ](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug)

**Comment by 8bitgentleman** [comment]
Thanks for the quick response and the links. I tried most of those suggestions before posting here and none worked. The strange thing is that the "official" plex plugin plays the file. Could this have to do with transcoding? I have Kodi running on a RP3

Here is a copy of my logs if that helps
https://gist.github.com/8bitgentleman/004d896d12038c0f98a249bd6063a949

**Comment by croneter** [comment]
Very sorry, but there seems nothing wrong with PKC. It must be a Kodi setting or Kodi issue; or your PMS. 
```
12:34:02.351 T:1330902000  NOTICE: PLEX.playutils -> File is direct streaming.
12:34:02.354 T:1330902000  NOTICE: PLEX.playutils -> The playurl is: https://192.168.1.179:32400/library/parts/5273/1466184104/file.mkv?X-Plex-Platform=Linux&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=PlexKodiConnect&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=PLEXTOKENREMOVED&X-Plex-Client-Identifier=f03ac32f-ec5f-4368-9d96-92253587fd4f&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=1.8.5
12:34:03.039 T:1958429616  NOTICE: VideoPlayer: Opening: https://192.168.1.179:32400/library/parts/5273/1466184104/file.mkv?X-Plex-Platform=Linux&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=PlexKodiConnect&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=PLEXTOKENREMOVED&X-Plex-Client-Identifier=f03ac32f-ec5f-4368-9d96-92253587fd4f&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=1.8.5
```
You could try to force-transcode and see if it works. But again: it's not PKC causing this

**Comment by 8bitgentleman** [comment]
Thanks for looking through those logs.
