### ISSUE TITLE
When transcoding, videos fail to play (no error message at all)

### ISSUE THREAD

**Issue by Jay2645** [croneter/PlexKodiConnect#329]
I have a low-power PC which I use to run Kodi. This PC is so low-power that it physically can't run 1080p videos; they all have to be transcoded down to 720p. I got sick of selecting the 720p version manually each time, so I went into the settings for PlexKodiConnect and told it to "Always transcode if video bitrate is above 720kbps". I'm assuming the transcoding happening on the server's end, not on the client's end. The server is a Raspberry Pi 3; my client is an HP Mini with a 1.66 GHz dual-core processor and 1 GB of RAM.

[Here's my full Kodi log](https://pastebin.com/WcHWLsHD). You can see me try to play a video a few times with transcoding enabled, and it doesn't work. I turn off the transcoding and it uses direct streaming, which works fine (although since the video is 1080p it starts dropping frames and lagging behind immediately). I turn on "Force Transcode" to double-check that it's a transcoding issue and the player refuses to play it one more time.

Whenever transcoding is enabled, I can see Kodi "thinking" for a few moments. It tells me to select a subtitle stream to use -- I've tried it both with and without subtitles. After I select a subtitle stream, it goes back to "thinking" and then once it's done "thinking" nothing happens. It just goes away and nothing plays.

Here's an excerpt from the logs, showing me playing an item when "Force Transcode" was on:

`18:19:25.267 T:140377755940608  NOTICE: PLEX.default -> plugin.video.plexkodiconnect started
18:19:25.292 T:140377806296832  NOTICE: PLEX.playback_starter -> Process_play called with plex_id 5343, kodi_id 14
18:19:25.578 T:140377806296832  NOTICE: PLEX.playbackutils -> Playbackutils called
18:19:25.584 T:140377806296832  NOTICE: PLEX.playutils -> Plex item optimized for direct streaming
18:19:25.597 T:140377806296832  NOTICE: PLEX.playutils -> User chose to transcode
18:19:25.597 T:140377806296832  NOTICE: PLEX.playutils -> File is transcoding.
18:19:25.648 T:140377806296832  NOTICE: PLEX.playutils -> The playurl is: https://192.168.1.220:32400/video/:/transcode/universal/start.m3u8?X-Plex-Platform=Android&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=Bedroom+Kodi+Player&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=TOKEN&X-Plex-Platform-Version=7.0&X-Plex-Client-Identifier=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=Plex+for+Android&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=5.8.0.475&maxVideoBitrate=4000&hasMDE=1&protocol=hls&partIndex=0&autoAdjustQuality=0&session=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&path=%2Flibrary%2Fmetadata%2F5343&videoResolution=1280x720&directStream=1&videoQuality=100&directPlay=0&audioBoost=0&fastSeek=1&subtitleSize=100&location=lan&mediaIndex=0&mediaBufferSize=20480
18:19:25.693 T:140377806296832  NOTICE: PLEX.playbackutils -> Playing from contextmenu: False
18:19:25.694 T:140377806296832  NOTICE: PLEX.playbackutils -> Playlist start position: 0
18:19:25.694 T:140377806296832  NOTICE: PLEX.playbackutils -> Playlist plugin position: 0
18:19:25.695 T:140377806296832  NOTICE: PLEX.playbackutils -> Playlist size: 0
18:19:25.695 T:140377806296832  NOTICE: PLEX.playbackutils -> Setting up properties in playlist.
18:19:28.867 T:140377806296832  NOTICE: PLEX.playbackutils -> Play as a widget item
18:19:28.871 T:140377806296832  NOTICE: PLEX.playback_starter -> Done process_play, playqueues: [<Playqueue_Object: ID: None, items: [], playlistid: 0, type: audio, kodi_pl: <xbmc.PlayList object at 0x7fac4ea4bfd0>>, <Playqueue_Object: ID: 35, items: [], shuffled: 0, playlistid: 1, version: 1, selectedItemID: 1943, type: video, kodi_pl: <xbmc.PlayList object at 0x7fac4f09d7d8>, selectedItemOffset: 0>, <Playqueue_Object: ID: None, items: [], playlistid: 2, type: photo, kodi_pl: <xbmc.PlayList object at 0x7fac4f09d800>>]
18:19:28.942 T:140377755940608  NOTICE: PLEX.default -> plugin.video.plexkodiconnect stopped
18:19:29.558 T:140379345336448  NOTICE: VideoPlayer: Opening: https://192.168.1.220:32400/video/:/transcode/universal/start.m3u8?X-Plex-Platform=Android&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=Bedroom+Kodi+Player&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=TOKEN&X-Plex-Platform-Version=7.0&X-Plex-Client-Identifier=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=Plex+for+Android&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=5.8.0.475&maxVideoBitrate=4000&hasMDE=1&protocol=hls&partIndex=0&autoAdjustQuality=0&session=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&path=%2Flibrary%2Fmetadata%2F5343&videoResolution=1280x720&directStream=1&videoQuality=100&directPlay=0&audioBoost=0&fastSeek=1&subtitleSize=100&location=lan&mediaIndex=0&mediaBufferSize=20480
18:19:29.559 T:140379345336448 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:19:29.794 T:140377635464960  NOTICE: Creating InputStream
18:19:30.038 T:140377635464960  NOTICE: Creating Demuxer
18:19:50.771 T:140377635464960  NOTICE: Opening stream: 0 source: 256
18:19:50.771 T:140377635464960  NOTICE: Creating video codec with codec id: 28
18:19:50.771 T:140377635464960  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
18:19:50.772 T:140377635464960  NOTICE: Creating video thread
18:19:50.772 T:140377635464960  NOTICE: Opening stream: 1 source: 256
18:19:50.772 T:140377876956928  NOTICE: running thread: video_thread
18:19:50.772 T:140377635464960  NOTICE: Finding audio codec for: 86018
18:19:50.775 T:140377635464960  NOTICE: Creating audio thread
18:19:50.775 T:140377635464960  NOTICE: Opening stream: 0 source: 1024
18:19:50.775 T:140377747547904  NOTICE: running thread: CVideoPlayerAudio::Process()
18:19:51.071 T:140378590148352  NOTICE: PLEX.kodimonitor -> Finish playback startup
18:19:51.231 T:140378590148352  NOTICE: PLEX.player -> ONPLAYBACK_STARTED: https://192.168.1.220:32400/video/:/transcode/universal/start.m3u8?X-Plex-Platform=Android&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=Bedroom+Kodi+Player&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=TOKEN&X-Plex-Platform-Version=7.0&X-Plex-Client-Identifier=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=Plex+for+Android&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=5.8.0.475&maxVideoBitrate=4000&hasMDE=1&protocol=hls&partIndex=0&autoAdjustQuality=0&session=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&path=%2Flibrary%2Fmetadata%2F5343&videoResolution=1280x720&directStream=1&videoQuality=100&directPlay=0&audioBoost=0&fastSeek=1&subtitleSize=100&location=lan&mediaIndex=0&mediaBufferSize=20480 itemid: 5343
18:19:51.236 T:140378590148352  NOTICE: PLEX.player -> ADDING_FILE: {'itemType': u'movie', 'currentfile': u'https://192.168.1.220:32400/video/:/transcode/universal/start.m3u8?X-Plex-Platform=Android&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=Bedroom+Kodi+Player&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=TOKEN&X-Plex-Platform-Version=7.0&X-Plex-Client-Identifier=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=Plex+for+Android&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=5.8.0.475&maxVideoBitrate=4000&hasMDE=1&protocol=hls&partIndex=0&autoAdjustQuality=0&session=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&path=%2Flibrary%2Fmetadata%2F5343&videoResolution=1280x720&directStream=1&videoQuality=100&directPlay=0&audioBoost=0&fastSeek=1&subtitleSize=100&location=lan&mediaIndex=0&mediaBufferSize=20480', 'SubtitleStreamIndex': u'', 'AudioStreamIndex': u'', 'item_id': u'5343', 'Type': u'movie', 'playmethod': u'Transcode', 'refresh_id': u'5343', 'currentPosition': 140, 'playcount': 0, 'runtime': 6526, 'fileid': 1450}
18:20:11.000 T:140377635464960  NOTICE: CVideoPlayer::OnExit()
18:20:11.000 T:140377635464960  NOTICE: VideoPlayer: eof, waiting for queues to empty
18:20:11.000 T:140377635464960  NOTICE: Closing stream player 1
18:20:11.000 T:140377635464960  NOTICE: Waiting for audio thread to exit
18:20:11.002 T:140377747547904  NOTICE: thread end: CVideoPlayerAudio::OnExit()
18:20:11.002 T:140377635464960  NOTICE: Closing audio device
18:20:11.002 T:140377635464960  NOTICE: Deleting audio codec
18:20:11.003 T:140377635464960  NOTICE: Closing stream player 2
18:20:11.003 T:140377635464960  NOTICE: waiting for video thread to exit
18:20:11.003 T:140377876956928   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
18:20:11.003 T:140377876956928  NOTICE: thread end: video_thread
18:20:11.003 T:140377635464960  NOTICE: deleting video codec
18:20:11.003 T:140377635464960  NOTICE: Closing stream player 3
18:20:11.016 T:140378590148352  NOTICE: PLEX.player -> ONPLAYBACK_ENDED
18:20:11.017 T:140378590148352  NOTICE: PLEX.player -> ONPLAYBACK_STOPPED
18:20:11.018 T:140378590148352  NOTICE: PLEX.player -> Played_information: {u'https://192.168.1.220:32400/video/:/transcode/universal/start.m3u8?X-Plex-Platform=Android&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=Bedroom+Kodi+Player&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=TOKEN&X-Plex-Platform-Version=7.0&X-Plex-Client-Identifier=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=Plex+for+Android&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=5.8.0.475&maxVideoBitrate=4000&hasMDE=1&protocol=hls&partIndex=0&autoAdjustQuality=0&session=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&path=%2Flibrary%2Fmetadata%2F5343&videoResolution=1280x720&directStream=1&videoQuality=100&directPlay=0&audioBoost=0&fastSeek=1&subtitleSize=100&location=lan&mediaIndex=0&mediaBufferSize=20480': {'itemType': u'movie', 'currentfile': u'https://192.168.1.220:32400/video/:/transcode/universal/start.m3u8?X-Plex-Platform=Android&X-Plex-Client-Platform=Linux&Connection=keep-alive&X-Plex-Device-Name=Bedroom+Kodi+Player&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=TOKEN&X-Plex-Platform-Version=7.0&X-Plex-Client-Identifier=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&Accept=%2A%2F%2A&X-Plex-Device=PlexKodiConnect&X-Plex-Product=Plex+for+Android&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=5.8.0.475&maxVideoBitrate=4000&hasMDE=1&protocol=hls&partIndex=0&autoAdjustQuality=0&session=fb3b90dd-3ee2-4fac-9198-8f9c3d53fc6e&path=%2Flibrary%2Fmetadata%2F5343&videoResolution=1280x720&directStream=1&videoQuality=100&directPlay=0&audioBoost=0&fastSeek=1&subtitleSize=100&location=lan&mediaIndex=0&mediaBufferSize=20480', 'SubtitleStreamIndex': u'', 'AudioStreamIndex': u'', 'item_id': u'5343', 'Type': u'movie', 'playmethod': u'Transcode', 'refresh_id': u'5343', 'currentPosition': 140, 'playcount': 0, 'runtime': 6526, 'fileid': 1450}}
18:20:11.020 T:140378590148352  NOTICE: PLEX.player -> Percent complete: 0.0214526509347 Mark played at: 0.9
18:20:11.022 T:140378590148352  NOTICE: PLEX.player -> Transcoding for 5343 terminating
18:20:11.056 T:140379345336448  NOTICE: CVideoPlayer::CloseFile()
18:20:11.056 T:140379345336448  NOTICE: VideoPlayer: waiting for threads to exit
18:20:11.056 T:140379345336448  NOTICE: VideoPlayer: finished waiting
18:20:11.071 T:140379345336448  NOTICE: CVideoPlayer::CloseFile()
18:20:11.071 T:140379345336448  NOTICE: VideoPlayer: waiting for threads to exit
18:20:11.071 T:140379345336448  NOTICE: VideoPlayer: finished waiting
18:20:11.845 T:140378590148352  NOTICE: PLEX.kodimonitor -> Item is invalid for playstate update.`

It looks to me like it's making an empty playlist, then playing the empty playlist, which (of course) immediately finishes and throws me back to the menu. But I haven't poked around the actual code to see if my hunch is correct.

If it's unfixable or an issue with my low-power hardware, perhaps at least an error message here would be nice? But if there's a solution, I'd love to hear one.

**Comment by croneter** [comment]
Sorry, but Transcoding is NOT going to work with the PMS on a Raspi 3, there is more power needed than that

**Comment by croneter** [comment]
And error handling is really difficult if not impossible because Kodi handles the playback (which fails in your case)
