### ISSUE TITLE
Play Error when playing transcoded media

### ISSUE THREAD

**Issue by littlespeed** [croneter/PlexKodiConnect#330]
Hey,
Since last week I stopped being able to use transcoding when playing media. I suspect it started with a Plex server update. Not sure.
**I always get a "Play Error" when I try to play using transcoding.**
**Direct Play/ Direct Stream work fine.**
Transcoding to other Plex apps (official) works fine, only Kodi fails.
I tried reinstalling Plex server (Windows), reinstalling Kodi (Openelec), even tried latest Beta PKC, reset my router settings, nothing helped.

I will provide a full log if necessary but I'd prefer sending it privately. I'm not sure whether any tokens are present, but I don't use any Plex account, remote, only local streaming.

Thanks for your awesome work, hope we'll get a solution for this.
LS

**Comment by croneter** [comment]
Full PKC debug log is absolutely necessary.

**Comment by armin-owen** [comment]
Hello, I have probably the same problem. In the log I tested with HEVC movie. First without transcoding, second with transcoding. Behavior is the same with h264 video. Btw this addon is very good and I like it. Thanks
[log.txt](https://github.com/croneter/PlexKodiConnect/files/1205193/log.txt)

**Comment by croneter** [comment]
I need the entire Kodi log. Could you please also share the pms log when you have tried to transcode?

**Comment by armin-owen** [comment]
[kodi_log.zip](https://github.com/croneter/PlexKodiConnect/files/1205897/kodi_log.zip)

[Plex Media Server Logs_2017-08-07_21-19-55.zip](https://github.com/croneter/PlexKodiConnect/files/1205894/Plex.Media.Server.Logs_2017-08-07_21-19-55.zip)

**Comment by littlespeed** [comment]
[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/1206562/kodi.zip)

Hope this helps. Also please delete the link if any sensitive information left undeleted in the log.
Much appreciated

**Comment by armin-owen** [comment]
[kodi_log.zip](https://github.com/croneter/PlexKodiConnect/files/1206574/kodi_log.zip)
[Plex.Media.Server.Logs_2017-08-07_21-19-55.zip](https://github.com/croneter/PlexKodiConnect/files/1206575/Plex.Media.Server.Logs_2017-08-07_21-19-55.zip)

**Comment by armin-owen** [comment]
Hello, I have already updated to version 1.8.8 but problem still exists. It cannot decode character "č".

[log.txt](https://github.com/croneter/PlexKodiConnect/files/1209604/log.txt)

**Comment by littlespeed** [comment]
Same here, same error

**Comment by croneter** [comment]
This is really weird, can't reproduce the issue you're having. 

Could you please share EVERY external subtitle files (*.srt) of a single movie where you have this issue? Thx!

**Comment by croneter** [comment]
Ah, never mind, I got it 😆

**Comment by littlespeed** [comment]
Fixed and working, thanx Croneter.

**Comment by armin-owen** [comment]
Good job, thank you.
