### ISSUE TITLE
NOTICE: PLEX.websocket_client -> timeout while connecting, trying again

### ISSUE THREAD

**Issue by stevezau** [croneter/PlexKodiConnect#332]
Hi,

On a fresh install of PKC and Kodi 17.3 i'm getting a bunch of timeout errors in the log every few seconds. The below is with debug turned on.

PMS is local and it plays videos fine. I'm trying to figure out what is causing it. Any idea where I can t-shoot?

Thanks

```15:20:12.770 T:139759390271232  NOTICE: PLEX.websocket_client -> timeout while connecting, trying again
15:20:13.771 T:139759390271232  NOTICE: PLEX.websocket_client -> Connection closed, (re)connecting
15:20:15.170 T:139759390271232  NOTICE: PLEX.websocket_client -> timeout while connecting, trying again
15:20:16.171 T:139759390271232  NOTICE: PLEX.websocket_client -> Connection closed, (re)connecting
15:20:17.575 T:139759390271232  NOTICE: PLEX.websocket_client -> timeout while connecting, trying again
15:20:18.584 T:139759390271232  NOTICE: PLEX.websocket_client -> Connection closed, (re)connecting
15:20:19.996 T:139759390271232  NOTICE: PLEX.websocket_client -> timeout while connecting, trying again```

**Comment by croneter** [comment]
Could you please enable PKC debug logging in the PKC settings, reboot Kodi, then share your entire log? Thx

**Comment by croneter** [comment]
https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by stevezau** [comment]
Ah, sorry. Should of followed the instructions.

full log is here - https://pastebin.com/SX34xyaq

**Comment by croneter** [comment]
That is PKC trying to open a connection to Amazon Alexa. However, the connection times out. 

Should you have a connection pubsub.plex.tv in principle? If yes, could you run a tracert to see how long a reply takes?

Workaround: deactive Alexa in the PKC settings :wink:

**Comment by stevezau** [comment]
Ah, that is what it was. I don't use alexa, it was on by default.

I'm using the Titian skin, when it displays the recently added shows etc it's very slow and seems to continue to 'refresh'. I thought it was related to PKC but it seems more related to the skin. I'll open a ticket there..

Thanks
