### ISSUE TITLE
Starting trailers does not always work (Kodi widgets)

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#334]
Thanks to @pheare

Start discussion: http://forums.plex.tv/post/quote/210023/Comment_1492644

* If I play a movie from a home screen widget based on a plex item, for example 'recently added' movies or a collection, the trailers do not play. However, even though the movie started playing without trailers or pre-roll, stopping the movie and looking at the current playlist shows two trailers, my pre-roll and then the selected movie.
* If I go into 'all movies' and select a movie from there, the trailers do play.
* If I play the movie right from the widget (without going into the information page first), the trailer will play. However, if from the widget I enter the info page and then play from there, the trailers do not play.

**Comment by croneter** [comment]
Unfortunately, this needs a major rewrite of how PKC starts up playback on Kodi

**Comment by pheare** [comment]
okay.  I understand if this is not something feasible to address.  Work around is easy enough - do not play from info page if in a widget.

**Comment by croneter** [comment]
Should be solved with beta version 2.0.0
