### ISSUE TITLE
Cant mark episode as watched from widget

### ISSUE THREAD

**Issue by gb160** [croneter/PlexKodiConnect#338]
Not sure if this is a known issue or if there is a setting somewhere that addresses this.
Pretty much as per title really, i can toggle the watched status through the library, which works instantly, but nothing happens when using the 'marked as watched' option from the context menu on the on deck widget.

Im very new to PlexKodiConnect, so apologies if this is already explained or known but i couldn't see a mention of this through searching the issues or the wiki.
Im using the latest stable version but this behaviour is the same on the latest beta v1.8.10 on Kodi 17.4.
Cheers.

**Comment by croneter** [comment]
thanks for the report. It's one of many widget issues - widgets are no fun, unfortunately...

**Comment by gb160** [comment]
No worries, I just didn't wanna be missing something if there was an easy way to fix this.

**Comment by gb160** [comment]
@croneter 
Hi sorry but i thought id inform you of my findings, I'm now not sure its even a widget issue afterall.
If i just go into the addon, into TV programmes, and then into the on deck section from there, i can toggle the watched status and the tick appears/disappears when toggling back as expected, but it just doesn't update the PMS of the change(checked via the web interface)...so thinking about it this issue is probably not even related to the widget.

To verify if this was related to the widget or not, if i toggle the watched status from the widget, it successfully changes the watched status in the 'on deck' section of the addon, but also doesn't update the PMS of this change(checked via the web interface)...which to me concludes that the widget function appears to be functioning as expected.

Ive tried manually syncing, and refreshing the nodes, and even after restarting Kodi the 'on deck' section still shows the same shows with the watched flag but the PMS status remains unwatched.

I hope this makes sense, just thought id clarify as the issue title is a bit misleading.
Cheers.

**Comment by croneter** [comment]
Should be fixed with PKC beta version 2.0.4. Let me know if this is not the case
