### ISSUE TITLE
Appearance Tweaks settings causing multiple issues

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#34]
Noticing some odd behaviors since 1.1.9 update. One consistent and one somewhat random. 
Consistently:
Unless "Extend Plex TV Series "On Deck" View to all shows" is selected in Appearance Tweaks, Kodi still reports the On Deck node as using the plugin path.
Randomly:
On Deck does not report a show as being watched after its finished playing if any combination of Appearance Tweaks is selected. I haven't been able to nail down what or if any particular combination consistently triggers this action but last night I had everything selected and noticed that after watching a show and being returned to my home screen, said show was still showing the episode that I just watched. Going into the library view also has the show indicated as unwatched. Doing a manual refresh corrects the problem so PMS is recognizing that the show was in fact watched. Turning off all Appearance Tweaks does seem to fix the problem every time.

**Comment by croneter** [comment]
To Consistently:
What does the kodi log say - are you indeed using plugin paths or file paths?

To Randomly: 
Please check with the Plex server - is the episode correctly reported as having been watched there? I've been having issues with Kodi simply not updating the video node view

**Comment by hstamas** [comment]
Can you give me an idea where in the log the path info might be or wording I can search for?

**Comment by hstamas** [comment]
And here is the log with the option CHECKED in Appearance Tweaks.

[kodi2.txt](https://github.com/croneter/PlexKodiConnect/files/263687/kodi2.txt)

**Comment by croneter** [comment]
Regarding Kodi displaying plugin paths instead of direct paths for On Deck: should hopefully be fixed. If not, try resetting the Kodi DB. If that does not help, kindly open a new issue ;-)
