### ISSUE TITLE
Library sync crashes upon resume from sleep

### ISSUE THREAD

**Issue by RickDB** [croneter/PlexKodiConnect#340]
Hi,

Noticed a new bug after 'long' sleeps and overview below.

**Issue**

Library sync crashes on long sleeps, only solution is to restart Kodi.
Short sleeps (10-15mins) are fine, used to work fine with long sleeps so most likely change in Kodi or PKC is causing this.

**How to reproduce**

- Put machine to sleep
- Wait a few hours and resume machine
- PKC will report library sync crashed and dialog requests you to restart Kodi, tested without restart and indeed sync no longer worked.

**Log snippet**

Can post full log via Plex forums PM if you need it, here's the sleep and resume and it will report library sync almost instantly upon resume (no noticeable delay / wait).
What might help is if it waited 15-30s to allow network to fully recover or a setting to configure that manually.

PKC debug logging was turned on in below log:
''''
06:46:40.586 T:21236  NOTICE: Additional mode: 1920x1080@ 50.00 - Full Screen
06:46:40.586 T:21236  NOTICE: Additional mode: 1920x1080@ 60.00 - Full Screen
06:46:40.586 T:21236  NOTICE: Additional mode: 1920x1080@ 25.00i - Full Screen
06:46:40.586 T:21236  NOTICE: Additional mode: 1920x1080@ 29.97i - Full Screen
06:46:40.587 T:21236  NOTICE: Additional mode: 1920x1080@ 30.00i - Full Screen
06:46:40.587 T:21236  NOTICE: Additional mode: 1920x1080@ 23.98 - Full Screen
06:46:40.587 T:21236  NOTICE: Additional mode: 1920x1080@ 24.00 - Full Screen
06:46:40.587 T:21236  NOTICE: Additional mode: 1920x1080@ 29.97 - Full Screen
06:46:40.587 T:21236  NOTICE: Additional mode: 1920x1080@ 30.00 - Full Screen
06:46:40.694 T:6416  NOTICE: PLEX.plexbmchelper.plexgdm -> DEBUG: Recieved UDP packet from [('10.1.2.50', 54048)] containing [M-SEARCH * HTTP/1.1]
06:46:40.694 T:6416  NOTICE: PLEX.plexbmchelper.plexgdm -> DEBUG: Detected client discovery request from ('10.1.2.50', 54048).  Replying
06:46:40.695 T:6416  NOTICE: PLEX.plexbmchelper.plexgdm -> DEBUG: Sending registration data HTTP/1.0 200 OK
12:54:26.994 T:7176  NOTICE: PLEX.librarysync -> Doing scheduled full library scan
12:54:26.995 T:7176  NOTICE: PLEX.librarysync -> Running fullsync for NEW PMS items with repair=False
12:54:26.995 T:7176  NOTICE: PLEX.utils -> DEBUG: Toggling screensaver to "": {u'jsonrpc': u'2.0', u'id': 1, u'result': True}
12:54:27.012 T:7176  NOTICE: PLEX.downloadutils -> DEBUG: Server unreachable at: https://10.1.2.50:32400/library/sections
12:54:27.012 T:7176  NOTICE: PLEX.downloadutils -> DEBUG: HTTPSConnectionPool(host='10.1.2.50', port=32400): Max retries exceeded with url: /library/sections (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2B8C5C30>: Failed to establish a new connection: [Errno 10065] A socket operation was attempted to an unreachable host',))
12:54:27.012 T:7176  NOTICE: PLEX.music -> ERROR: Could not get Plex sections
12:54:27.014 T:7176  NOTICE: PLEX.downloadutils -> DEBUG: Server unreachable at: https://10.1.2.50:32400/library/sections
12:54:27.014 T:7176  NOTICE: PLEX.downloadutils -> DEBUG: HTTPSConnectionPool(host='10.1.2.50', port=32400): Max retries exceeded with url: /library/sections (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x213F6370>: Failed to establish a new connection: [Errno 10065] A socket operation was attempted to an unreachable host',))
12:54:27.014 T:7176  NOTICE: PLEX.downloadutils -> Failed to connect to https://10.1.2.50:32400/library/sections too many times. Declare PMS dead
12:54:27.015 T:7176  NOTICE: PLEX.librarysync -> ERROR: Error download PMS views, abort maintainViews
12:54:27.015 T:7176  NOTICE: PLEX.utils -> DEBUG: Toggling screensaver to "": {u'jsonrpc': u'2.0', u'id': 1, u'result': True}
12:54:27.015 T:7176  NOTICE: PLEX.utils -> It took 0:00:00.020000 to run the function fullSync
12:54:27.015 T:7176  NOTICE: PLEX.librarysync -> ERROR: Could not finish scheduled full sync
12:54:27.015 T:7176  NOTICE: PLEX.librarysync -> ERROR: LibrarySync thread crashed. Error message: '{error}'
12:54:27.017 T:7176  NOTICE: PLEX.librarysync -> ERROR: Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\Rick\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1396, in run
                                                self.run_internal()
                                              File "C:\Users\Rick\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1592, in run_internal
                                                icon='error')
                                              File "C:\Users\Rick\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 111, in showKodiNote
                                                type='{error}')
                                              File "C:\Users\Rick\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\utils.py", line 186, in dialog
                                                kwargs['type'] = types[kwargs['type']]
                                            KeyError: '{error}'
12:54:28.732 T:21236  NOTICE: CPowerManager::OnWake: Running resume jobs
12:54:28.733 T:21236  NOTICE: CPowerManager::OnWake: Restarting lirc
12:54:29.214 T:4280  NOTICE: PLEX.downloadutils -> DEBUG: Server timeout at: https://10.1.2.50:32400/library/onDeck
12:54:29.215 T:4280  NOTICE: PLEX.downloadutils -> DEBUG: HTTPSConnectionPool(host='10.1.2.50', port=32400): Read timed out. (read timeout=10)
12:54:29.215 T:4280  NOTICE: PLEX.PlexAPI -> DEBUG: Could not connect to https://10.1.2.50:32400/library/onDeck
12:54:29.716 T:4280  NOTICE: PLEX.PlexAPI -> DEBUG: Failed to connect to https://10.1.2.50:32400/library/onDeck too many times. PMS is dead
12:54:29.716 T:4280  NOTICE: PLEX.service -> ERROR: Plex Media Server went offline
12:54:32.728 T:4280  NOTICE: PLEX.userclient -> DEBUG: Returning active server: https://10.1.2.50:32400
12:54:32.729 T:4280  NOTICE: PLEX.PlexAPI -> DEBUG: Checking connection to server https://10.1.2.50:32400/library/onDeck with verifySSL=False
12:54:33.733 T:21236   ERROR: ActiveAE::ActiveAE::CActiveAE::Resume - failed to init
12:54:33.911 T:21236  NOTICE: Found screen: Dummy Monitor on NVIDIA GeForce GTX 1080, adapter 0.
''''

**System information**

**Kodi**: 17.4
**PKC**: 1.8.11
**PMS**: 1.8.3.4235
**OS**: Windows 10 x64 (build 1703)

**Comment by croneter** [comment]
Ups, my bad. Thanks for this perfect bug report!
