### ISSUE TITLE
Library sync crashes every time with UnicodeDecodeError

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#344]
```
Traceback (most recent call last):

File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1499, in run self.run_internal()
File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1609, in run_internal
deletePlaylists()
File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 920, in deletePlaylists
for root, _, files in walk(path):
File "/usr/lib/python2.7/os.py", line 286, in walk
File "/usr/lib/python2.7/posixpath.py", line 71, in join
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)
```

**Comment by croneter** [comment]
Bad luck: https://stackoverflow.com/questions/21772271/unicodedecodeerror-when-performing-os-walk

**Comment by croneter** [comment]
Hmm, not so simple. Could you please try to navigate to your [Kodi userdata folder](http://kodi.wiki/view/Userdata), then `playlists\video`. Could you please make a screenshot or copy paste what folders and files you have in there?

**Comment by croneter** [comment]
Also, try updating your Python installation (outside Kodi) to the very latest 2.7!

**Comment by agasi34** [comment]
well i have nothing in playlists\video and my Python installation is already the lastest 2.7.13 !

**Comment by croneter** [comment]
What is your exact, full path to your playlists folder?

**Comment by agasi34** [comment]
Hi Croneter, i don't understand... I updated your plugin today and now i don't have synchro issue anymore ...
I don't understand what you have change but for me it's very good change !!!

**Comment by croneter** [comment]
It's magic! 😉  Thanks for reporting back

**Comment by croneter** [comment]
Many, many thanks for the coffee! ☕️

**Comment by agasi34** [comment]
Hi Croneter, unfortunately, the error come back ...

When Kodi start, i have the PKC library sync error message.

In the logs it's the same error ...
ERROR: PLEX.librarysync: Traceback:
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1503, in run
                                                self.run_internal()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1613, in run_internal
                                                deletePlaylists()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 920, in deletePlaylists
                                                for root, _, files in walk(path):
 File "/usr/lib/python2.7/os.py", line 286, in walk
                                              File "/usr/lib/python2.7/posixpath.py", line 71, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 12: ordinal not in range(128)

Now, in my playlist folder (/storage/.kodi/userdata/playlists/video) i have 4 files Plex 1 -2 -4 -5.xsp and 1 file Dessins animés .xsp (smart playlist).

It's curious because, since i have create this playlist (Dessins animés), other plex playlist does'nt update ... Do you think it's linked ?

**Comment by croneter** [comment]
The problem is the `é`. I think your Python setup (the module "os" of python 2.7.??) is throwing an error if you name your playlists with a non-ASCII character like `é`, `è`, `ê`, etc

**Comment by agasi34** [comment]
you are perfectly right Croneter ! i try to delete my playlist and now library sync worked like a charm... i'm going to try to re-create my playlist with a standard name.

Thx very much for your help, you can re-closed ticket ...

**Comment by croneter** [comment]
Cool! But I'd like to get to the bottom of this. Could you be so kind and:
* open a Windows/Linux command prompt. Type `python -V`
* Share your entire Kodi debug log when you reproduce this issue with an `é` in a playlist name. See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

You **really** should be able to use `é`!

**Comment by croneter** [comment]
Closing without having gotten to the bottom of this issue :-(

**Comment by vdias** [comment]
facing the same problem...

21:26:52.278 T:3152  NOTICE: PLEX.librarysync: ---===### Starting LibrarySync ###===---
21:26:52.281 T:8388 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: cannot reference separator setting in old setting condition "eq(-1,true)" for "skipContextMenu"
21:26:52.281 T:8388 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: failed to parse visible condition "eq(-1,true)" of old setting definition for "skipContextMenu"
21:26:52.291 T:9964 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: cannot reference separator setting in old setting condition "eq(-1,true)" for "skipContextMenu"
21:26:52.291 T:9964 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: failed to parse visible condition "eq(-1,true)" of old setting definition for "skipContextMenu"
21:26:52.296 T:3100  NOTICE: PLEX.playback_starter: ----===## Starting Playback_Starter ##===----
21:26:52.299 T:3152 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: cannot reference separator setting in old setting condition "eq(-1,true)" for "skipContextMenu"
21:26:52.299 T:3152 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: failed to parse visible condition "eq(-1,true)" of old setting definition for "skipContextMenu"
21:26:52.481 T:9596  NOTICE: PLEX.userclient: Successfully authenticated!
21:26:52.481 T:9596  NOTICE: PLEX.userclient: Current user: vitordias
21:26:52.481 T:9596  NOTICE: PLEX.userclient: Current userId: 3084589
21:26:53.222 T:8388  NOTICE: PLEX.plexbmchelper.plexgdm: Discovery starting up
21:26:53.225 T:8388 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: cannot reference separator setting in old setting condition "eq(-1,true)" for "skipContextMenu"
21:26:53.225 T:8388 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: failed to parse visible condition "eq(-1,true)" of old setting definition for "skipContextMenu"
21:26:53.229 T:8388  NOTICE: PLEX.plexbmchelper.plexgdm: Registration starting up
21:26:53.274 T:9340  NOTICE: PLEX.websocket_client: PMS_Websocket: connection closed, (re)connecting
21:26:53.276 T:9340 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: cannot reference separator setting in old setting condition "eq(-1,true)" for "skipContextMenu"
21:26:53.276 T:9340 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: failed to parse visible condition "eq(-1,true)" of old setting definition for "skipContextMenu"
21:26:53.303 T:3152 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: cannot reference separator setting in old setting condition "eq(-1,true)" for "skipContextMenu"
21:26:53.303 T:3152 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: failed to parse visible condition "eq(-1,true)" of old setting definition for "skipContextMenu"
21:26:53.307 T:3152  NOTICE: PLEX.librarysync: Db version:
21:26:53.307 T:3152  NOTICE: PLEX.librarysync: Synching time with PMS server
21:26:53.889 T:3152  NOTICE: PLEX.librarysync: Found an item to sync with: 1
21:26:54.157 T:3152  NOTICE: PLEX.PlexFunctions: Toggled watched state for Plex item 1
21:26:55.491 T:3152  NOTICE: Previous line repeats 1 times.
21:26:55.491 T:3152  NOTICE: PLEX.librarysync: Time offset Koditime - Plextime in seconds: -2.0
21:26:55.493 T:3152 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: cannot reference separator setting in old setting condition "eq(-1,true)" for "skipContextMenu"
21:26:55.493 T:3152 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: failed to parse visible condition "eq(-1,true)" of old setting definition for "skipContextMenu"
21:26:55.497 T:3152  NOTICE: PLEX.librarysync: Refreshing video nodes and playlists now
21:26:55.497 T:3152  NOTICE: PLEX.librarysync: Initial start-up full sync starting
21:26:55.497 T:3152  NOTICE: PLEX.librarysync: Running fullsync for NEW PMS items with repair=False
21:26:55.512 T:3152  NOTICE: PLEX.videonodes: Clearing nodes properties.
21:26:55.514 T:3152  NOTICE: PLEX.librarysync: Creating viewid: 1 in Plex database.
21:26:55.515 T:3152   ERROR: PLEX.librarysync: LibrarySync thread crashed. Error message: no such table: tag
21:26:55.519 T:3152   ERROR: PLEX.librarysync: Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\VDIAS\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1503, in run
                                                self.run_internal()
                                              File "C:\Users\VDIAS\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 1616, in run_internal
                                                librarySync = fullSync()
                                              File "C:\Users\VDIAS\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\utils.py", line 970, in wrapper
                                                result = func(*args, **kwargs)
                                              File "C:\Users\VDIAS\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 255, in fullSync
                                                if self._fullSync() is False:
                                              File "C:\Users\VDIAS\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 276, in _fullSync
                                                if not self.maintainViews():
                                              File "C:\Users\VDIAS\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 518, in maintainViews
                                                totalnodes)
                                              File "C:\Users\VDIAS\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\librarysync.py", line 353, in processView
                                                tagid = kodi_db.createTag(foldername)
                                              File "C:\Users\VDIAS\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\kodidb_functions.py", line 1058, in createTag
                                                self.cursor.execute(query, (name,))
                                            OperationalError: no such table: tag

**Comment by croneter** [comment]
Use Kodi 17, not kodi 18 in a yet very unstable alpha version

**Comment by vdias** [comment]
Thanks. everything ok with kodi 17.6.
