### ISSUE TITLE
Change Transcode Quality mid video

### ISSUE THREAD

**Issue by stevezau** [croneter/PlexKodiConnect#346]
Hi,

I'm trying to work out how to change the transcoding quality mid transcode. My internet can get congested at peak times, sometimes at random. It's a pain to change it via the settings each time.

Is it possible to add it to the context/menu popup??

It was asked here but not sure what the outcome was - https://github.com/croneter/PlexKodiConnect/issues/31

**Comment by croneter** [comment]
Hi there

This is a feature request and not a issue/bug. Please be so kind and open a new feature request here: https://feathub.com/croneter/PlexKodiConnect

**Comment by stevezau** [comment]
Interesting, had no idea about feathub. will open there!

**Comment by stevezau** [comment]
Thanks, done

https://feathub.com/croneter/PlexKodiConnect/+35
