### ISSUE TITLE
"Sync had to skip some items because they could not be processed." error

### ISSUE THREAD

**Issue by julian-phillips** [croneter/PlexKodiConnect#350]
Getting this message during playback.  Usually right at the beginning once or twice in row and then not at all for the rest of playback.  Playback continues while dialog box is open. 

"Sync had to skip some items because they could not be processed. Kodi may be instable now!! Please post your Kodi logs to the Plex forum."

https://pastebin.com/Dx0b7pwi

**Comment by croneter** [comment]
Do you have enough disk space?!?
```
OperationalError: database or disk is full
```
Workaround: 
1. In the PKC settings, deactivate `Force artwork caching`
2. In the [Kodi userdata folder](http://kodi.wiki/view/Userdata), delete the entire folder named `Thumbnails`

**Comment by julian-phillips** [comment]
So I think I have enough disk space.  PMS is installed on a docker on a server with 10 TB free.  And I believe that the size of those dockers is dynamic, so if it needs more it can get more.  

The kodi box itself also has over 3 GB free.

I have not tried to reset the entire database yet because I thought you might want to see the log beforehand.  Should I do that before the workaround above?

**Comment by croneter** [comment]
According to the Kodi error message, Kodi does NOT have enough disk space, sorry. This has nothing to do with a database reset. So if you cannot increase Kodi's disk space, you need to follow the workaround above directly...

Background: PKC caches artwork so your browsing experience is faster/better. This can quickly take a couple of gigabytes

Closing this as thus issue is solved :wink:
