### ISSUE TITLE
Disable overlay image in the corner

### ISSUE THREAD

**Issue by shogunreaper** [croneter/PlexKodiConnect#351]
How can i disable the image that pops up when the overlay is on?

heres what i'm talking about
https://i.imgur.com/NqysKrC.jpg

**Comment by croneter** [comment]
This is called "clearart" and additionally downloaded (among other stuff) by PKC. If you don't want that, you can deactivate this entirely in the PKC settings under Artwork, `Download additional artwork`. You would need to do a full Database reset afterwards: go to the PKC Settings, Advanced, `Reset the Kodi database ...` (in red), then hit YES, YES, NO

Alternatively, choose a Kodi skin where you can just turn off clearart. Might be easier 😉

**Comment by shogunreaper** [comment]
is that the only artwork that is downloaded under that?

**Comment by croneter** [comment]
No. PKC will also get (see http://kodi.wiki/view/Movie_artwork):
* Banner
* Clearart
* Clearlogo
* Landscape
* Disk
* Movie set/collection artwork

**Comment by shogunreaper** [comment]
i only want to disable that one image type.

**Comment by croneter** [comment]
Then choose a skin where you can deactivate "Clearart"

**Comment by shogunreaper** [comment]
but doesnt that still waste bandwidth on an image i never see?

**Comment by croneter** [comment]
Very very little - artwork is usually cached and only downloaded once

**Comment by croneter** [comment]
Or use [the Kodi add-on Artwork Downloader](http://kodi.wiki/view/Add-on:Artwork_Downloader) where you can specify what you want

**Comment by shogunreaper** [comment]
alright i'll use that, thanks for the help
