### ISSUE TITLE
Android TV No Connection to Repository

### ISSUE THREAD

**Issue by janitom** [croneter/PlexKodiConnect#352]
Mediaoase commented on 24 apr
The installation from the repository fails.

I have installed the repository from the zip file. When installing from the repository I get a error message. "Could not connect to the repository"

Data:
Android TV ver. 5.1.1

Hi, is there a solution for that problem? I have the same problem on Android TV with Kodi 17.4.

I have tried the same things with beta and URL as Source in the FileManager. But in the FileManager the Source is Empty, but the connection is ok.

On my Other Kodi Devises there is no Problem with the Addon, only on the Android TV.

**Comment by janitom** [comment]
I tried to install the videoplugin directly. Thats work for me, but i like automaticle updates.

**Comment by croneter** [comment]
Please share your Kodi debug log when you try to install from the PKC repository, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Please try again, there's a new version out. Does it work now?

**Comment by croneter** [comment]
Closing this issue as it should be resolved. Please let me know if that is not the case
