### ISSUE TITLE
OpenStream: unable to create subtitle parser

### ISSUE THREAD

**Issue by Cyriltra** [croneter/PlexKodiConnect#353]
Hello,

I have a lot of Chinese subtitles files for my movies (.srt or .ssa/.ass) which are working fine with PMP but doesn't work in Kodi.
Each time I select them in OSD, i got the following error:
`OpenStream: unable to create subtitle parser`

If I use a subtitle in another language than Chinese (english, german, french etc.) there is no issue and the subtitle is displayed correctly.

I suspect this issue to be linked with the font / unicode

Thank you

**Comment by Cyriltra** [comment]
Hello Croneter,

here is attached the log and the subtitles.
It seems the issue is linked with chinese characters encoding as it's replaced with dots in the subtitle file. Also there is no language name in the subtitle file itself.

in PMS, the code for Chinese is zh, so all my original subtitles are named like: moviename.zh.srt or .ssa
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1350955/kodi.log)
[subtitle01..ssa.txt](https://github.com/croneter/PlexKodiConnect/files/1350956/subtitle01.ssa.txt)
(i renamed the subtitle in .txt to upload it on github)

(limit size exceeded on pastebin)

Thank you

**Comment by croneter** [comment]
Have you tried with the new 1.8.17 PKC version?

Am 03.10.2017 04:25 schrieb "Cyriltra" <notifications@github.com>:

**Comment by Cyriltra** [comment]
well, how do i know which version am i using ? I cannot find the version number in settings.
I have kodi set to install updates automatically for addons and I installed the PKC repository, so the update should be automatic also if my understanding is correct ?
Thank you

**Comment by croneter** [comment]
Definitely an encoding issue. Could you please share an original subtitle file that gets converted to dots?

**Comment by Cyriltra** [comment]
Here it is, but if it's encoding issue, I assume it's more on Kodi's side than on PKC
[The Martian (2015).zh.ass.txt](https://github.com/croneter/PlexKodiConnect/files/1354371/The.Martian.2015.zh.ass.txt)
[The Martian (2015).zh.ssa.txt](https://github.com/croneter/PlexKodiConnect/files/1354370/The.Martian.2015.zh.ssa.txt)

**Comment by Cyriltra** [comment]
Ok, problem solved, not linked with PKC.
Here is the solution:

1) download Arial Unicode MS font (22mb)
2) place the font in /storage/.kodi/media/Fonts/ (the folder didn't exist so I created it
_I named the font ArialUnicodeMS.ttf (so I can be sure to select it in kodi's settings)_
3) In kodi: settings / Player / Language / :
- font use for subtitles: ArialUnicodeMS.ttf
- Character set: Chinese Simplified (GBK)
- enable: override ASS/SSA subtitles fonts (to be sure to always use the font I downloaded)

**Comment by croneter** [comment]
Thanks for reporting back!
