### ISSUE TITLE
Support for strm files

### ISSUE THREAD

**Issue by im85288** [croneter/PlexKodiConnect#354]
Would it be possible to add support for strm files (it works with the Emby addon) but for me failed with this addon. With kodi 18 addons such as Netflix now work and allow adding to the library so it will become a more popular option. I also recently pulled in a change to my next up addon that allows it to work properly with strm files in the local db.

**Comment by croneter** [comment]
What did you try to do exactly? Add a strm files to your Plex library? I can have a look if you give me some pointers

**Comment by im85288** [comment]
Yes, if you have the new netflix addon (or maybe the amazon one) installed https://github.com/asciidisco/plugin.video.netflix it allows you to export a tv show to your library (I set the location to be one that plex can see and scrape the details from)...basically you end up with a folder full of .strm files. I'm at work currently but if you need any more info I can get that to you, in Emby if you look at PlayUtils.py it has code such as:

` # Strm
        if playurl.endswith('.strm'):
            playurl = urllib.urlencode(playurl)
`

To handle these, but when I had a look at the playback in this addon I could not get my head around how it works now.

**Comment by croneter** [comment]
The netflix add-on is a Kodi add-on which will just fill a folder with strm files. Then Plex kicks in and scrapes these strm files into a movie/tv shows library. Then you want to be using PKC to watch a strm, NOT the netflix add-on itself. 
And PKC won't let you play any strm files currently. 
Did I understand that correctly? 😉 

Sorry for asking stupid questions, but I do not have netflix nor amazon

**Comment by im85288** [comment]
No problem at all, you are almost there with your understanding. So yes we use Plex to scrape the strm files into the movie/tvshows library and yes from there using PKC it should be able to launch the strm file but that in turn simply uses the netflix addon for playback.

I will get a proper example for you to see later today/tomorrow but the strm file simply contains a link to the netflix addon in a format similar to:

`plugin://netflix.addon/twobrokegirls/blah/blah/episode1`

And that is what is actually called when playing back a strm file.

So to clarify there would be strm files such as
No problem at all, you are almost there with your understanding. So yes we use Plex to scrape the strm files into the movie/tvshows library and yes from there using PKC it should be able to launch the strm file but that in turn simply uses the netflix addon for playback.

I will get a proper example for you to see later today/tomorrow but the strm file simply contains a link to the netflix addon in a format similar to:

`plugin://netflix.addon/twobrokegirls/blah/blah/episode1`

And that is what is actually called when playing back a strm file.

Does that make more sense? I think the problem is that it is attempting to transcode the contents of what it finds in the strm file but I'm not 100% on that. Hopefully that is more clear :)

**Comment by im85288** [comment]
Although not specific to the netflix one here is a better explanation of the format and contents of a strm file: https://github.com/MediaBrowser/Wiki/wiki/Strm-files

**Comment by im85288** [comment]
Here is the sample strm file I mentioned earlier on: https://www.dropbox.com/s/h99j96snk2udncl/S02E07.strm?dl=0 if there is anything else I can do to help just let me know. Thanks

**Comment by croneter** [comment]
Could you please try the hotfixes branch manually? https://github.com/croneter/PlexKodiConnect/tree/hotfixes

Test setup is kinda impossible for me as I don't use Amazon nor Netflix and back-referring to PKC is a bad idea ;-)

**Comment by im85288** [comment]
Thanks, I gave it a shot and got the following error in my logs:

`13:40:08.657 T:139446936656   ERROR: PLEX.playback_starter: Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playback_starter.py", line 137, in triage
                                                params.get('dbid'))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playback_starter.py", line 69, in process_play
                                                xml.attrib.get('librarySectionUUID'))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playbackutils.py", line 53, in play
                                                playurl = playutils.getPlayUrl()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playutils.py", line 35, in getPlayUrl
                                                playurl = self.isDirectPlay()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playutils.py", line 81, in isDirectPlay
                                                return tryEncode(playurl)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 193, in tryEncode
                                                uniString = uniString.encode(encoding, "ignore")
                                            AttributeError: 'NoneType' object has no attribute 'encode'`

It did detect it as a .strm file but looks like somehow the playurl was None?

There was also this in the log showing the filename:

`PLEX.playback_starter: Error encountered for mode play, params {u'dbid': u'2408', u'filename': u'S01E01.strm', u'mode': u'play', u'id': u'3766'}`

**Comment by im85288** [comment]
After further investigation I think this error is coming up as it is trying to direct play but cannot find the file, other things fallback to direct streaming but this seems to fail. I'll reconfigure to get direct paths working and see if that resolves things

**Comment by im85288** [comment]
@croneter - this works great once I set up direct paths. Thanks again

**Comment by croneter** [comment]
Obviously, you would need to have Direct Paths working, otherwise strm files are bound to fail. Right? :-) So I can check this off my list?

**Comment by im85288** [comment]
Yeah fine to close this one cheers.

**Comment by daveftw84** [comment]
any way to have plex kodi connect create strm files of the library being shared? im trying to get it to work like direct path but with transcoding

**Comment by croneter** [comment]
@daveftw84 
No, sorry, not currently and probably not in the near future.
