### ISSUE TITLE
Library synch crash - Kodi 18

### ISSUE THREAD

**Issue by petreee** [croneter/PlexKodiConnect#355]
I'm using kodi 18 on a raspberry pi 3 (Milhouse build) and when I try to cache all images to kodi the library thread crashes. Same thing on odroid c2. It does however work on my mac and kodi 17 on all devices.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1366383/kodi.log)

**Comment by croneter** [comment]
Currently (might change again), Kodi 18 does not have a database table called `art`:
```
OperationalError: no such table: art
```
Unfortunately, a lot of code references this table. I'm not going to adapt the PKC code until it's clear that this change is permanent - so until Kodi 18 is at least beta

**Comment by croneter** [comment]
Merged with issue #339
