### ISSUE TITLE
all movies in my library dissapear after few minutes

### ISSUE THREAD

**Issue by ezdakit** [croneter/PlexKodiConnect#356]
After the first configuration of the plugin on kodi 17.4 and the first synch I see my plex movies in the kodi library, but after few minutes they magically dissapear. Not sure but it seems that they dissapear after the library compression.

I tried it several times starting from scratch and always the same issue.

**Comment by croneter** [comment]
Debug logs are needed: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by ezdakit** [comment]
I'm uploading kodi.log
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1370121/kodi.log)

**Comment by croneter** [comment]
You have this piece in your `advancedsettings.xml` (see here for more infos on how to edit it: http://kodi.wiki/view/Advancedsettings.xml):
```
<cleanonupdate>true</cleanonupdate>
```
Set `cleanonupdate` to false:
```
<cleanonupdate>false</cleanonupdate>
```
Then reset the Kodi database in the PKC settings under Advanced (hit YES, YES, NO).
