### ISSUE TITLE
Plex Theme Music

### ISSUE THREAD

**Issue by kat953162** [croneter/PlexKodiConnect#358]
I think it would be nice if there were an option to start playing music when a user clicks a show in the library. 

It would be understandable if this wasn't possible because of how Kodi works. Its just a thought because OpenPHT (and probably PHT) can do it. 

Another feature that PHT does is change the wallpaper every few seconds, and when a show/movie is selected, it changes the wallpaper to fanart for that content. Just thought that would be cool to have as an option because I prefer PlexKodiConnect by far.

**Comment by croneter** [comment]
Thanks for the input. The theme music is a feature request, not a bug. Please open a new feature request here: https://feathub.com/croneter/PlexKodiConnect

Kodi or the respective Kodi does EVERYTHING related to presenting the media. Some skins already do what you're looking for. Check e.g. here: http://kodi.wiki/view/how-to:change_skins

Thanks!

**Comment by kat953162** [comment]
Interesting, I've always seen Feature Requests under Issues but giving it an upvote option is good for large projects.
