### ISSUE TITLE
Connection information for companion (via the plex API) is missing for PlexKodiConnect devices

### ISSUE THREAD

**Issue by abrenoch** [croneter/PlexKodiConnect#363]
I am trying to get this plugin to interface with another application that utilizes the plex API, but I believe something may be preventing PKC from relaying the connection information to the plex servers.

If I access `https://plex.tv/api/resources?includeHttps=1&X-Plex-Token=XXX` (with my token provided obviously), I get a list of different plex devices associated with my account.

Correct Example (just one of the listed devices):
```
<Device name="Plex for LG" product="Plex for LG" productVersion="3.13.1" platform="webOS" platformVersion="05.30.01" device="" clientIdentifier="xxx" createdAt="1510802081" lastSeenAt="1510802092" provides="client,player,pubsub-player" owned="1" publicAddress="xxx" publicAddressMatches="1" presence="0" accessToken="xxx">
    <Connection protocol="https" address="xxx" port="32400" uri="https://xxx:32400" local="1"/>
    <Connection protocol="https" address="xxx" port="32400" uri="https://xxx:32400" local="0"/>
</Device>
```

However, for my PKC devices, the `Connection` tag is missing:
```
<Device name="TV Room Kodi" product="PlexKodiConnect" productVersion="1.8.18" platform="Linux" platformVersion="" device="PlexKodiConnect" clientIdentifier="xxx" createdAt="1510443367" lastSeenAt="1510920967" provides="client,controller,player,pubsub-player" owned="1" publicAddress="xxx" publicAddressMatches="1" presence="1"></Device>
```

Everything else seems to work as expected, and the companion player does work if I use plex in chrome to fling the media... I just found it odd that I could not find my PKC devices through the other app I'm trying to use (Phlex), and looking over the source code for that it appears these missing `Connection` tags are the root of the issue.

Any help would be greatly appreciated!

https://pastebin.com/5CR6NjLw

**Comment by croneter** [comment]
Interesting. As this is completely undocumented, have you tried to Wireshark and figure out how other clients get their connection entry?

**Comment by abrenoch** [comment]
I haven't gone as far as to use wireshark, but I think I may have found a little info on it:

https://github.com/plexinc/plex-media-player/wiki/Remote-control-API
```
If the resources endpoint is exposing resources that are not local (e.g. myPlex, or the media server talking about non-proxied players), then each resouce element has a list of connections.
```

The thing is, having accessed the `/resources` path for both PKC and the android version of plex, I really couldn't find much of a difference:

PKC:
```
<MediaContainer>
    <Player title="PlexKodiConnect" protocol="plex" protocolVersion="1" protocolCapabilities="timeline,playback,navigation,playqueues" machineIdentifier="3e2cc1f7-fcbf-4c9d-8987-b737b6b484a4" product="PlexKodiConnect" platform="Windows" platformVersion="1.8.18" deviceClass="pc"/>
</MediaContainer>
```

Android:
```
<MediaContainer size="1">
   <Player product="Plex for Android" machineIdentifier="4121000283b8b396-com-plexapp-android" platformVersion="8.1.0" deviceClass="mobile" protocolVersion="1" title="Pixel XL" platform="Android" protocolCapabilities="timeline,playback,navigation,mirror,playqueues"/>
</MediaContainer>
```

The android one does list available connections, but I'm not seeing where in this XML that would be established.

I think I did find a work-around in phlex for this, but regardless I figures you would probably like to know about it... I've spent the last few hours trying to dig up info on this and this is the best I found!

**Comment by croneter** [comment]
Moved to Feathub, where Feature Requests belong: https://feathub.com/croneter/PlexKodiConnect/+49

Do vote there if you think this feature important
