### ISSUE TITLE
PlexKodiConnect: Library sync thread has crashed.

### ISSUE THREAD

**Issue by jarvey14** [croneter/PlexKodiConnect#366]
Good day. I initially had PKC running perfectly on my computer before a power outage. Upon restarting my computer, multiple instances of "Sync had to skip some items because they could not be processed..." occurred. So I tried resetting my PKC database. When Kodi restarted, PKC would connect to my PMS followed by library sync crashing. Even a fresh install of Kodi and PKC resulted to library sync crashing. Any help would be appreciated! Thank you.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1516292/kodi.log)

**Comment by croneter** [comment]
I see that you're running Kodi 18 Leia, an alpha version. PKC doesn't "officially" support Kodi 18 yet as it might be instable... 
Did you install EXACTLY the same Kodi 18 version that used to work before? Seems like you picked a newer version where a database table got changed. Hence: yet unsupported. 

Please either install an earlier Kodi 18 version or revert back to Kodi 17.

**Comment by jarvey14** [comment]
I updated my Kodi 17 setup to Kodi 18 (build released on Nov. 29), which worked for several hours. Problems occurred only after the aforementioned power outage. I then tried a fresh install using the exact same build, which didn't end up working. Anyway, thanks for helping.
