### ISSUE TITLE
Video setting "auto play next item"

### ISSUE THREAD

**Issue by Zriel88** [croneter/PlexKodiConnect#368]
I haven been watching an Anime with over 400 episodes, and I have seen the playback of the first item is done severely slow (the delay between you pless play, and the item is then reproduced, was arround a minute or so)
I have narrowed it to a setting in kodi which lets you queue all the files in a directory. This lead to kodi asking the PMS server for all the files and queue them before starting the first item.

I would like to know if it could be possible to have PlexKodiConnect limit this somehow, like to only ask for 25 items at most, for example, in order to aliviate this issue.

**Comment by croneter** [comment]
No so, that does not make sense if PKC intervenes here. Try putting your 400 Anime in e.g. different season folders.
