### ISSUE TITLE
Plex Kodi Connect Play Item Issue

### ISSUE THREAD

**Issue by ChayBrandon** [croneter/PlexKodiConnect#369]
Hi,

I am unable to play any items through PlexKodiConnect. Please note: This is a fresh Kodi install so no plugins or settings should be affecting playback.

When I click on the item to play nothing happens on screen it just doesn't play. I have run a full reset reset of PlexKodiConnect and set it back up but still no joy.

I have activated Kodi debug logging, reset the PKC database, set up PKC again, and tried to play an item. The log for which can be found in the attachment: here:
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1527132/kodi.log)

When Kodi restarts after setting up PKC I get the following message (One for each media item) 
![image](https://user-images.githubusercontent.com/16900328/33553746-d0812fd4-d8f1-11e7-9ed1-76cc625c1fe2.png)
Note: I have entered network details manually. (IP, Username and Password)

Any ideas on how to fix?

Thank you!

**Comment by croneter** [comment]
You did not configure [Direct Paths](https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths-Explained) correctly. Please either [configure them correctly](https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths) or switch to Addon Paths: 
1. In the PKC Settings under Sync Options, set the `Playback Mode` to `Addon (Default)`
2. In the PKC Settings under Advanced, hit `Partial or full reset of Database and PKC`. Then hit Yes, Yes, No

**Comment by ChayBrandon** [comment]
Hi,

Thank you for the fast response. This was working previously using Direct Path and I have  my plex media server setup so the folders point to SMB like below:
![image](https://user-images.githubusercontent.com/16900328/33555538-aa5eb662-d8f8-11e7-9ef8-d3730a6b93df.png)

I have also just changed the playback mode to Addon and this unfortunately hasn't fixed the issue.

Thanks,
Chay

**Comment by ChayBrandon** [comment]
Hi,

Thank you for the fast reply! I was previously using the direct paths option and it was working with no issues. My Plex server uses SMB paths in the media listing like in the image below:

![image](https://user-images.githubusercontent.com/16900328/33555972-4713e882-d8fa-11e7-971e-5c65c00540ed.png)

I can confirm I can also access the shares when using Kodi's file browser.

Thanks

**Comment by croneter** [comment]
There's a million reasons why SMB could have stopped working. If you're using LibreElec, see here: https://libreelec.tv/2017/11/libreelec-krypton-v8-2-1-mr/ (samba / smb changes)

**Comment by ChayBrandon** [comment]
Hi

I can confirm SMB on the server side is working fine. I can access the SMB share from another windows machine and raspberry pi on my network, I can also access the SMB shares using the Kodi File manager.

![image](https://user-images.githubusercontent.com/16900328/33560983-3879a4e2-d909-11e7-9155-e0a9b5729b1f.png)
SMBv1 is switched on for my Windows box but that shouldn't matter as I believe Kodi now connects using SMBv3 right? 

It's odd that I can access the share via the file manager but PlexKodiConnect doesn't seem to work anymore. **Note: This was previously working! No changes have been made on the Plex/server side**

**Comment by croneter** [comment]
I can confirm that you're having a configuration issue. 

In the image you just posted, you're using IP addresses, not the hostname `NAS`. In the PKC settings, use the same IP address.

**Comment by ChayBrandon** [comment]
Hi,

Apologies that has only recently been changed so I could get the screenshot. I can confirm in PKC settings I have used both the IP address and hostname of the server for testing. Both unfortunately harbour the same result. 

Same with the file browser, tried both NAS and 192.168.100.9 and can access the shares on both.

![image](https://user-images.githubusercontent.com/16900328/33562141-628b244c-d90c-11e7-92ec-7b999efca888.png)

Note: I clicked on "Manually enter Plex Media Server address" and manually entered the details.

**Comment by croneter** [comment]
I usually really don't give configuration advice here - otherwise I'd not be doing anything else. 

The paths are probably case sensitive. Use EXACTLY the paths you see in the Kodi file explorer screenshot above.

**Comment by ChayBrandon** [comment]
That's completely understandable, fixing every configuration issue would take forever, 

However I don't believe this to be a config issue with SMB or the like as I was able to connect to Plex using these settings before without any issues and had been using this setup for a long while now. 
No changes have been made to the SMB config or plex config on my side so I'm not sure how it could be a config issue with Plex or SMB as these settings where working fine before.

**Comment by croneter** [comment]
Again, there's a million things that can go wrong with Direct Paths. And since there hasn't been a PKC for a while, probably none of them are caused by PKC. 

Try resetting Kodi completely and starting from scratch. 
* Close Kodi
* Delete everything in the [Kodi userdata folder](http://kodi.wiki/view/userdata).
* Follow https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths

**Comment by croneter** [comment]
But I would really tripple check all the file paths, especially their respective cases.

**Comment by ChayBrandon** [comment]
Okay no problem thank you for all the tips! Like you said it is most likely an issue with my configuration. I will check the path letter by letter to ensure it's not that.

Thank you for your assistance and by the way cheers for the Kodi addon! Great Work!

**Comment by croneter** [comment]
Thx very much and good luck! 😉

**Comment by ChayBrandon** [comment]
Can confirm this is now working! 

To get working I had to change the SMB share being used in my Plex Libraries from \\NAS\Share to \\192.168.100.9\Share

![image](https://user-images.githubusercontent.com/16900328/33564931-aeaf3f3c-d913-11e7-93ba-a7d0ad8701cf.png)

After doing PKC is now connecting using direct paths. I wonder why that stopped working as previously it was working fine using \\NAS

**Comment by croneter** [comment]
I'm glad it works again. Thanks for reporting back!

Your DNS is broken. Or you changed the host name of your NAS to something else.

**Comment by ChayBrandon** [comment]
NAS is still the hostname of my PlexMediaServer and completing an NSLookup for NAS on my LAN brings back the DNS entry so the DNS seems to be functioning.

Only thing I can think of is maybe because one part of Kodi had 192.168.100.9 and PKC had NAS entered it didn't like it. Now they are both the IP they seem to be pulling through, 

Cheers either way mate, was a big help!
