### ISSUE TITLE
PKC on OSMC does find Plex on my PC, but unable to log into account

### ISSUE THREAD

**Issue by Loewkie** [croneter/PlexKodiConnect#372]
Installed PKC on OSMC. I manually entered my IP address: 192.168.1.78:32400
And it correctly registers this as my PC: DEKSTOP-NP8JOD5.

However, when I try to log into my account I get:
"Problems trying to contact plex.tv. Try again later."

Here is the log:
https://paste.osmc.tv/avijopivil

I'm pretty sure I'm doing something wrong here, since PKC worked fine on Windows. I just don't know what...

**Comment by Loewkie** [comment]
Shit sorry, I forgot:

http://paste.osmc.tv/naturuzafu

**Comment by croneter** [comment]
Seems like you're having network issues:
```
CCurlFile::Open failed with code 404 for https://github.com/dandy0850/dandymedia/raw/master/addons.xml.md5
Open - failed to open source <https://github.com/dandy0850/dandymedia/raw/master/addons.xml.md5>
ERROR: CCurlFile::Open failed with code 404 for https://raw.githubusercontent.com/ares-fortress/repo/master/addons.xml.md5
ERROR: Open - failed to open source <https://raw.githubusercontent.com/ares-fortress/repo/master/addons.xml.md5>
ERROR: CCurlFile::Open failed with code 0 for http://mediarepos.net/Repos/smashrepo/addons.xml.md5
```
And many more. PKC fails with many
```
ERROR: PLEX.userclient: Token is no longer valid
```
Try to completely reset PKC in the PKC settings, Advanced, then the red `Reset the Kodi database...`. Hit YES, YES, YES. 

That might help. If not, have a look at your network. 

You could also try www.libreelec.tv instead of OSMC, it's what I'm using

**Comment by Loewkie** [comment]
I updated my web scraping modules like requests (and with it urllib) and also urlresolver and now it works. Maybe that has something to do with it?

**Comment by croneter** [comment]
Requests definitely. Thanks for reporting back!
