### ISSUE TITLE
Choose source in KODI in the case of multiple sources

### ISSUE THREAD

**Issue by entr** [croneter/PlexKodiConnect#373]
I found that PKC can replace user rating placeholder with the number of sources as Plex reports them but how to choose which source to play? Can't really find it in 17.6 on WIN10 x64.

**Comment by croneter** [comment]
If you're using Addon Paths, you will automatically be prompted to select a version.

In your case, you're probably using Direct Paths. Use the Kodi context menu, then PKC, then "Start playback via PMS"

**Comment by entr** [comment]
Thanks for the quick reply!
