### ISSUE TITLE
No PKC updates. Could not connect to repository.

### ISSUE THREAD

**Issue by rekeds** [croneter/PlexKodiConnect#374]
Hi,

 I can wget the URLs from the box. 
Any help?

Same with BETA.

openelec 8.0.4

> wget https://dl.bintray.com/croneter/PlexKodiConnect/bin/addons.xml.md5
> Connecting to dl.bintray.com (5.153.35.248:443) addons.xml.md5       100% |*********************************************************************************************|    33   0:00:00 ETA`

>00:01:25.729 T:1405088672   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 405
>00:01:25.729 T:1405088672   ERROR: CCurlFile::Open failed with code 405 for https://dl.bintray.com/croneter/PlexKodiConnect/bin/addons.xml.md5
>00:01:25.729 T:1405088672   ERROR: Open - failed to open source <https://dl.bintray.com/croneter/PlexKodiConnect/bin/addons.xml.md5>
>00:01:25.729 T:1405088672   ERROR: CRepository: failed read 'https://dl.bintray.com/croneter/PlexKodiConnect/bin/addons.xml.md5'`

>00:01:33.654 T:1405088672   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 405
>00:01:33.654 T:1405088672   ERROR: CCurlFile::Open failed with code 405 for https://dl.bintray.com/croneter/PlexKodiConnect_BETA/bin-BETA/addons.xml.md5
>00:01:33.654 T:1405088672   ERROR: Open - failed to open source <https://dl.bintray.com/croneter/PlexKodiConnect_BETA/bin-BETA/addons.xml.md5>
>00:01:33.654 T:1405088672   ERROR: CRepository: failed read 'https://dl.bintray.com/croneter/PlexKodiConnect_BETA/bin-BETA/addons.xml.md5'
>00:02:17.884 T:1947377680   ERROR: GetDirectory - Error getting addons://repository.plexkodiconnectbeta/
>00:02:17.884 T:1947377680   ERROR: CGUIMediaWindow::GetDirectory(addons://repository.plexkodiconnectbeta/) failed

**Comment by croneter** [comment]
Probably a Python requests package connectivity issue. Try updating your Python installation, especially requests

**Comment by rcambrj** [comment]
I'm getting this same error today but on Kodi

```
19:37:05.329 T:3026096128   DEBUG: CGUIMediaWindow::GetDirectory (addons://repository.plexkodiconnect/)
19:37:05.330 T:3026096128   DEBUG:   ParentPath = [addons://repos/]
19:37:05.351 T:2806322160   DEBUG: CAddonDatabase: SELECT repo.id FROM repo .. took 2 ms
19:37:05.352 T:2806322160   DEBUG: CAddonDatabase: no valid repository matching 'repository.plexkodiconnect'
19:37:05.355 T:2651579376   DEBUG: Thread JobWorker start, auto delete: true
19:37:05.356 T:2651579376   DEBUG: CRepositoryUpdateJob[repository.plexkodiconnect] checking for updates.
19:37:05.371 T:2651579376   DEBUG: CFileCache::Open - opening <croneter/PlexKodiConnect/bin/addons.xml.md5> using cache
19:37:05.373 T:2651579376   DEBUG: CurlFile::Open(0x9ca99a90) https://dl.bintray.com/croneter/PlexKodiConnect/bin/addons.xml.md5
19:37:05.377 T:2651579376    INFO: easy_aquire - Created session to https://dl.bintray.com
19:37:05.639 T:2651579376   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 405
19:37:05.641 T:2651579376   ERROR: CCurlFile::Open failed with code 405 for https://dl.bintray.com/croneter/PlexKodiConnect/bin/addons.xml.md5
19:37:05.642 T:2651579376   ERROR: Open - failed to open source <https://dl.bintray.com/croneter/PlexKodiConnect/bin/addons.xml.md5>
19:37:05.644 T:2651579376   ERROR: CRepository: failed read 'https://dl.bintray.com/croneter/PlexKodiConnect/bin/addons.xml.md5'
19:37:05.755 T:2651579376   DEBUG: CRepositoryUpdater: done.
19:37:05.760 T:2806322160   DEBUG: CAddonDatabase: SELECT repo.id FROM repo .. took 3 ms
19:37:05.762 T:2806322160   DEBUG: CAddonDatabase: no valid repository matching 'repository.plexkodiconnect'
```

Unsure what to upgrade: ran `apt-get update && apt-get dist-upgrade`, `python-requests` is already the latest version (2.4.3-6)

**Comment by croneter** [comment]
Try updating the Kodi addon requests itself, http://kodi.wiki/view/Add-on:Requests

Or even uninstalling and reinstalling it

**Comment by rcambrj** [comment]
@croneter thanks for the quick reply. any idea how I might achieve that?

**Comment by rcambrj** [comment]
Found it!

System => Settings => System => Addons => Manage Dependencies => requests => update

But it seems to be missing on this particular Kodi box. Stand by...

**Comment by rcambrj** [comment]
Yep, I'm not going crazy, Add-on:requests isn't present on the box showing the error. My other box is fine (can browse the repository) and it lists this package. Seems to have a couple of other extra packages too, like certifi, urllib3 and xmltodict.

**Comment by croneter** [comment]
Well is everything fine now that you installed the requests addon?

**Comment by rcambrj** [comment]
@croneter I'm unable to install the requests addon - it's not listed in the default Kodi repository for installation, for some reason.

However, the discovery I just made is that the requests addon becomes installed once I install PKC manually (from ZIP file). Unfortunately, even though the requests addon is now available, the repository still doesn't work :( 

Without the repository link, it won't update automatically, is that right?

**Comment by kendo3664** [comment]
I have the exact same problem. Installed the repo but get the message rcambrj mentioned. Tried it on a Macbook as well as Nvidia Shield. Any ideas what's going on?

**Comment by kendo3664** [comment]
Also, tried the beta version and still got the same error.

**Comment by bleomycin** [comment]
Just wanted to chime in, same issue on fresh install of ubuntu 17.10. debug log shows same output as @rcambrj

Happy to provide more logs if helpful.

**Comment by croneter** [comment]
These idiots at https://bintray.com where I host the Kodi PKC repository changed something - no idea what. I am also unable to access the repo with Kodi, but direct downloads work. 

On it

**Comment by croneter** [comment]
Had to move the entire PKC repository 😞 . You need to **MANUALLY** intervene once, sorry for that: https://github.com/croneter/PlexKodiConnect/wiki/Update-PKC-Repository

**Comment by rcambrj** [comment]
Great work @croneter! Don't apologise, you've made something awesome here.

**Comment by croneter** [comment]
No news = good news guys?

**Comment by ericdepotter** [comment]
Your solution worked like a charm, thx.

**Comment by kendo3664** [comment]
Thanks. It's working now :)
