### ISSUE TITLE
Removed shows reappear

### ISSUE THREAD

**Issue by hofwing** [croneter/PlexKodiConnect#375]
So, sometimes I delete a show from my Plex library. It's all gone - I've checked, even the files and folders are deleted from my server and from Plex

When browsing in Plex Web App, there´s no trace of the show, BUT when browsing through shows in Kodi it still appears in the library with 0 episodes, if I refresh the library through Kodi it disappears but next time I open my shows, it's back. 

I've tried a complete refresh from PKC and the previously deleted show vanished from Kodi, but a couple of days later I deleted another show and that show still appears in my library

Currently on version 1.8.16 (which is the latest I could update to through OSMC on RPI 3)

Any ideas?

**Comment by croneter** [comment]
Is this still an issue with PKC versio 2.0.4?

**Comment by robotaur** [comment]
This is still an issue for me as well, yes. The only way to fix it is by manually deleting the TV show from the list on PKC or by deleting the whole library from Kodi and refetching all the show episodes.
