### ISSUE TITLE
Add API support to start media playback via API (or missing documentation?)

### ISSUE THREAD

**Issue by C-Duv** [croneter/PlexKodiConnect#377]
I couldn't find any evidence that _Kodi_ with _PlexKodiConnect_ supports playing "Plex" media when asked to do so via the _Kodi_ API.
Is it possible? If yes I think the documentation lacks API on how to do so.

This [forum thread](https://forum.kodi.tv/showthread.php?tid=157996) gives the API URL for single/native playback of a video file:

    http://192.168.15.117/jsonrpc?request={"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"file":"Media/Big_Buck_Bunny_1080p.mov"}}}

I get that playing a media that resides on a _Plex Media Server_ server requires some sort of path prefix or specific scheme?

I would like to use native _Kodi_ API to start/stop/seek/... movies and TV shows.

**Comment by croneter** [comment]
I don't understand what you're trying to do. 

What you're trying to do is probably completely unrelated to PKC and the PMS. PKC links Kodi database entries with filepaths (if using direct paths) or with `addon:` callbacks to Kodi (if using Addon paths). You can write your own addon to do whatever to the Kodi playback. PKC should pickup on anything you're doing, e.g. starting playback of a specific item, then relay that back to the PMS. 

PKC already uses the JSON Kodi interface, e.g. for Plex Companion. See the source code here on Github. 

See http://kodi.wiki/view/JSON-RPC_API/v8 for the Kodi JSON API. 

Also, this is not a PKC issue, hence closing this.
