### ISSUE TITLE
Selecting Appearance Tweak causes issues 

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#38]
Updated to v1.1.11. Completely resynced database. Same issues as closed problem.

Un-selecting the Extend option make On Deck note report plugin path.

Selecting some combination of the other Apperance tweaks causes home screen On Deck to not update to the next unplayed episode.

**Comment by croneter** [comment]
Darn. Exactly the same? Can you elaborate?

**Comment by hstamas** [comment]
Yeah I was as surprised as you are :(

Running Windows 10 / Jarvis / Titan beta. 

I have a home screen widget that points to the On Deck node. If I leave EVERYTHING in Appearance Tweaks UNCHECKED, all works properly. After a show finishes playing, I am returned to my home screen and the widget instantly updates as does my PMS. Navigating to the On Deck library node, file path shows a smb:// path.

If I check the Extend... option and then go back to the On Deck library node the path changes to plugin://

I still have to test a little more but it also appears that checking any combination of items in the Appearance Tweaks section causes the home screen widget to stop updating after a show is finished playing. PMS still reports the show as being played correctly.

**Comment by croneter** [comment]
Could you please make a screenshot of an episode showing plugin:// path? 

Also, on Isengard using Titan, I have 2 simultaneous home screen widgets to show both On Deck and Recently Added. No matter my settings, I cannot replicate your issues... Another thing though - when navigating to the Recently Added video node, episodes are correctly marked as watched with this blue eye thingy. Not on the home screen though :-). It does work for movies. 

Seems like a skin issue to me. Have you tried another skin? You won't lose your skin settings if you switch around with the skins.

**Comment by hstamas** [comment]
Screen shots attached with Extend on and off. Sorry for the quality but I am not at home right now so I had to do a remote screen grab. I think you can see the path difference well enough? Notice that with Extend on there is a lot more metadata being displayed along with a different series poster strangely enough.

I will try installing a different skin when I get home tonight.

Is there a way of telling what mode I'm actually using when playing a show through On Deck
![extend on](https://cloud.githubusercontent.com/assets/4341070/15334413/128d8464-1c3c-11e6-84b2-55935a7a9da3.png)
![extend off](https://cloud.githubusercontent.com/assets/4341070/15334415/129deeda-1c3c-11e6-8e61-79140db73947.png)

? I didnt understand what the logs were showing.

**Comment by croneter** [comment]
Thanks! 

After having played something, search your log for either smb://<PMS address > or plugin://PlexKodiConnect

Or post ;-)

**Comment by hstamas** [comment]
Just tried the Confluence skin. If Extend is unchecked path is plugin://. If checked, path is smb:// so I would guess that is definitely PKC related. Maybe its just reporting wrong? I Just tried playing an episode in Confluence with various Appearance Tweaks setting checked and uncheck. The first play it did not update. All other plays it did so it very inconsistent and pretty hard to tell what combination is causing it.

**Comment by hstamas** [comment]
It is just reporting it wrong. I played and episode twice. Once with Extended UNCHECKED (plugin://) and once CHECKED (smb://).

I deleted the logs in-between plays. Both logs report that playback is via smb:

15:35:47 T:6032  NOTICE: DVDPlayer: Opening: smb://192.168.0.4/Media/TV/Grandfathered/Season 1/Grandfathered - S01E07 - Sexy Guardian Angel - WEBDL-720p.mkv

**Comment by croneter** [comment]
Do you have these issues only for home screen widgets or also if you navigate to the corresponding video nodes?

**Comment by hstamas** [comment]
Happens on both the home screen widget and if I monitor from within the On Deck node. I was thinking it was a widget issue too but with this last round of tests with Confluence which as far as I can figure out doesn't support home screen widgets I was doing all of it from within the library node and getting the same results.

**Comment by croneter** [comment]
@im85288, any ideas?

**Comment by hstamas** [comment]
Just a quick update. Have watched maybe 10 episodes of various shows with "Extened..." unchecked but everything else checked in Apperance Tweaks and On Deck has consistently updated every time.
