### ISSUE TITLE
binary_repo wrong version numbers

### ISSUE THREAD

**Issue by dazedcrazy** [croneter/PlexKodiConnect#380]
![screenshot000](https://user-images.githubusercontent.com/9027988/34417643-81eac5b6-ebf1-11e7-8be4-91d47901a8af.png)
Both the new beta and normal repos show the wrong version numbers, your old bintray account still have the current correct version https://dl.bintray.com/croneter/PlexKodiConnect/bin/plugin.video.plexkodiconnect/

**Comment by croneter** [comment]
Argh, thanks for that! Should be fixed now
