### ISSUE TITLE
Movie Set Artwork Not Loading

### ISSUE THREAD

**Issue by sirreef** [croneter/PlexKodiConnect#381]
While my "Collections" are pulling over properly to "Sets", none of the Sets have artwork. The individual movies within the Set do - but not the Sets themselves.

1) I have set Plex to automatically create Collections. (Working - sets are created)
2) I set Kodi to do Sets. (Working - Sets show up.)
3) I set PKC to rescan. (Working - All sets, except sets with 1 item show up)
4) I set PKC to download additional artwork. (Working - All additional artwork types are showing)

After all that I did a "Download Additional Artwork Now" thing - and hours later ... nothing. The artwork for everything else is working from the CD Art to ClearArt ... but nothing for the Sets.

Am I missing something?

**Comment by dazedcrazy** [comment]
Both Kodi and Plex don't support movie set art (sets/collections yes but not the artwork) but with Kodi you can at least manually add it 
http://kodi.wiki/view/Movie_artwork#Movieset_Fanart

**Comment by sirreef** [comment]
@dazedcrazy - This much I know, but based on the thread on Plex, it would seem that Movie Set artwork SHOULD be downloaded and that we shouldn't manually edit it.  

Per @croneter :

> Never manually set anything in the Kodi library - manual changes will be lost if PKC updates the library
> Make sure that Download additional artwork is enabled in the PKC Settings under Artwork
> Also in the PKC Settings under Artwork, hit the yellow Download additional artwork now (or something like that). This will happen in the background - be sure to let PKC do its job for at least 60min
> Remember that there are sets without artwork (the not so popular ones)

Am I misunderstanding this issue?

https://forums.plex.tv/discussion/265288/plexkodiconnect-movie-sets

**Comment by croneter** [comment]
No, @dazedcrazy is wrong. Kodi does support artwork for "sets" (the Plex "collections"). The question is mostly, whether artwork actually exists for a specific set of movies!

@sirreef 
Please check with https://www.themoviedb.org/, whether set/collection artwork exists. For example, search for a **movie** like "Skyfall" (https://www.themoviedb.org/movie/37724-skyfall), then see whether a corresponding collection with art exists (https://www.themoviedb.org/collection/645-james-bond-collection).

**Comment by dazedcrazy** [comment]
PKC has never set collection art for me i just assumed it wasn't suppose to, this is what it looks like 
![7fg5nys](https://user-images.githubusercontent.com/9027988/34454535-3c989568-ed65-11e7-87c2-547c72b5c722.png)
Until i run [Movie Set Artwork Automator](https://forum.kodi.tv/showthread.php?tid=153502) or [Artwork Beef](https://forum.kodi.tv/showthread.php?tid=258886) then it looks like
![p807yjn](https://user-images.githubusercontent.com/9027988/34454560-d95845f6-ed65-11e7-8009-29c1f2ceb4a5.jpg)
But maybe that will change with Plex doing a better job with collections now 
https://www.plex.tv/blog/beginning-look-lot-like-collections/

**Comment by sirreef** [comment]
@croneter - The set artwork does exist (Fast & Furious and Star Wars autogrouped by Plex).  Do I need an add on like Artwork Beef per @dazedcrazy? 

Is there a magic setting or thing I am maybe missing?

**Comment by sirreef** [comment]
I completely uninstalled Kodi and reinstalled it fresh.  No library artifacts or add-ons to muck with.  

Installed PKC and sets work like a charm.

**Comment by croneter** [comment]
Thanks for reporting back @sirreef !
