### ISSUE TITLE
Other movies folder mixes with Movies

### ISSUE THREAD

**Issue by LenryNmQ** [croneter/PlexKodiConnect#382]
In PMS I created a new library, called "Other videos", and it's fully separated from Movies and TV shows everywhere in Plex.
But in Kodi with PKC the contains of this library ends up in the Movies folder.

How can I remove them from there?

**Comment by croneter** [comment]
https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins

**Comment by vin047** [comment]
> https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins

Whilst it does mention here that the default skin Estuary doesn't allow you to customise the top level menu, I feel it should be mentioned on the page that Estuary doesn't allow you to edit any of the nodes at all - I could create parent nodes/rules/etc but could never select a node to use. Changing to a different skin like Titan worked. 

Confusing as even the wiki mentions
> e.g. the Movies shortcut highlighted in blue in the top left of the screenshot above
 
referencing a screenshot which is running Estuary! Spent a good while trying to figure this out...

**Comment by croneter** [comment]
@vin047 
You are very welcome to update the wiki - anybody may contribute 😉

**Comment by vin047** [comment]
@croneter added to the wiki :)

https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins/63a8652925a7ad28ba4477bedf9ca337139c564d

**Comment by croneter** [comment]
Nice @vin047 , that's the first time someone added something to the PKC wiki 😆 . Many thanks!
