### ISSUE TITLE
when using other addons, 

### ISSUE THREAD

**Issue by daveftw84** [croneter/PlexKodiConnect#385]
when using other addons, they seem to find movies everytime but refuse to find tv shows
using addon path

**Comment by croneter** [comment]
You need to be wayyyy more specific!

What addon does not work? Also, share your DEBUG log of the addon trying to
access without success, see here:
https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug



Am 03.01.2018 16:13 schrieb "daveftw84" <notifications@github.com>:

**Comment by croneter** [comment]
Actually, scrap that. You need to use **direct paths** as explained e.g. Here: https://github.com/croneter/PlexKodiConnect/wiki/faq

**Comment by daveftw84** [comment]
any way to use direct paths over an internet connection.
the addon im using is Extended info mod. it supports .strm
but most of all it has no issues finding movies and playing. 
tv shows it see's i have show in library but doesnt even try to play them. like it cant see episodes

**Comment by croneter** [comment]
Yes, set up a VPN connection to your PMS.

Sorry but you need direct paths for this to work

Am 03.01.2018 16:30 schrieb "daveftw84" <notifications@github.com>:

**Comment by daveftw84** [comment]
what if i setup a smb share over the internet? do i have to  mount it? or can i mount with kodi?

**Comment by daveftw84** [comment]
sorry for the 100 questions

**Comment by croneter** [comment]
No need to mount it. But I would rather set up a VPN than directly opening
an SMB path - much more secure. You don't want your movie files out there
in the wild

Am 03.01.2018 16:34 schrieb "daveftw84" <notifications@github.com>:

**Comment by daveftw84** [comment]
ok thank you. 
is live tv channels supported, like iptv.simple?
i have it cloned a few times with different sources and all dont seem to work in pkc

**Comment by daveftw84** [comment]
i mean iptv.bundle

**Comment by croneter** [comment]
I don't know. Again - if some addon doesn't work, try it with **direct
paths** :wink:


2018-01-03 16:39 GMT+01:00 daveftw84 <notifications@github.com>:
