### ISSUE TITLE
PKC adds weird video sources

### ISSUE THREAD

**Issue by arabesc** [croneter/PlexKodiConnect#386]
I'm trying to configure PKC for DirectPlay, and I'm partially succeeded - it plays videos every other time. But I'm curious about the following video sources that have appeared after installing PKC and syncing a media library:
![screenshot 2018-01-04 21 30 33](https://user-images.githubusercontent.com/2709027/34579203-114b7e24-f199-11e7-9a10-ab0fdfa8e9e0.png)
![screenshot 2018-01-04 21 30 49](https://user-images.githubusercontent.com/2709027/34579226-264ebd2c-f199-11e7-950d-93ac6203a782.png)
![screenshot 2018-01-04 22 00 58](https://user-images.githubusercontent.com/2709027/34579638-d807e470-f19a-11e7-83ed-6625cc133bbd.png)
Why are they there and what they for?

Windows 10 Fall Creators Update / Kodi  v17.6 / PKC v1.8.18

**Comment by croneter** [comment]
The sources.xml file with the following entries
```
<sources>
  <video>
    <default pathversion="1" />
    <source>
      <name>Plex</name>
      <path pathversion="1">smb://</path>
      <allowsharing>true</allowsharing>
    </source>
    <source>
      <name>Plex</name>
      <path pathversion="1">smb://</path>
      <allowsharing>true</allowsharing>
    </source>
  </video>
</sources>
```
Is a hack to make PlexKodiConnect compatible to the Kodi master lock. Otherwise, there wouldn't be any videos/library elements showing up.
