### ISSUE TITLE
How to exclude items that client can't play

### ISSUE THREAD

**Issue by delta-heavy** [croneter/PlexKodiConnect#388]
First of all, I'm aware this is most likely not PKC territory but couldn't find much info on the subject and I'm looking for suggestions.

My setup:

Plex Server - cheap ARM based NAS
Various clients  - armv7 board running LibreELEC, armv8 board running LibreELEC, amd64 laptop running Win10

In my collection there're quite a lot of HEVC encoded videos, most of which are MAIN (8bit) but there are also some which are MAIN 10 (10bit). My x64 clients don't have problems to directly playback main10, even only in SW mode, but my armv7 board simply doesn't support it and of course transcoding is not supported on my ARM server as well. That's why I wish those videos to be simply ignored by the client.

Any ideas?

**Comment by croneter** [comment]
Sorry, no, and definitely not a PKC issue
