### ISSUE TITLE
PKC does not sync anything, synced categories are empty

### ISSUE THREAD

**Issue by arabesc** [croneter/PlexKodiConnect#389]
Either I don't get an idea behind PKC, or it still doesn't work properly for me.
I've synced a Plex library and here is how it looks in Kodi:
![screenshot 2018-01-06 21 27 53](https://user-images.githubusercontent.com/2709027/34642945-c29a6750-f32c-11e7-9db7-3a62cb3314fd.png)
All of the categories there except the _Browse by folder_ are empty. They are not empty in Plex. So, the only way to access movies is to make link to the _Browse by folder_ item. Is that behaviour expected?

Windows 10 Fall Creators Update / Kodi v17.6 / PKC v1.8.18

**Comment by croneter** [comment]
Not at all expected and I have also no idea what you're doing differently
than literally everybody else. Did you try rebooting Kodi again?

Also please share some debug  logs here, see the wiki

Am 06.01.2018 20:11 schrieb "Igor" <notifications@github.com>:

**Comment by arabesc** [comment]
> Also please share some debug logs here

I see there should be [a special setting](https://github.com/croneter/PlexKodiConnect/wiki/PKC-settings#advanced) to enable PKC debug logging, but there is no such setting in my version:
![screenshot 2018-01-06 22 24 51](https://user-images.githubusercontent.com/2709027/34643157-83ef408a-f330-11e7-9017-3ef913889626.png)

**Comment by croneter** [comment]
No need to do that, enable the kodi debug logging though in the kodi
settings


Am 06.01.2018 20:26 schrieb "Igor" <notifications@github.com>:

**Comment by arabesc** [comment]
Ok, I enabled debug logging, did a partial (yes/yes/no) PKC reset, PKC closed Kodi, I started Kodi again and caught an attached log.
[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/1609144/kodi.zip)

**Comment by arabesc** [comment]
And here is the second log where I tried to access a few categories after restart. It seems they were created on demand.
[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/1609162/kodi.zip)

**Comment by croneter** [comment]
Did you navigate to these empty PKC categories? THAT needs to be caught in
the log :wink:

Am 06.01.2018 20:55 schrieb "Igor" <notifications@github.com>:

**Comment by arabesc** [comment]
Yes, I did. It should be caught in the second log.

**Comment by arabesc** [comment]
Here are a couple of Kodi/PKC bases:
[plex.db](https://www.dropbox.com/s/6njyopiwhhcrc1l/plex.db?dl=0)
[MyVideos107.db](https://www.dropbox.com/s/ja023dnnt2t7pa3/MyVideos107.db?dl=0)
I see there are some empty tables.

**Comment by arabesc** [comment]
/offtopic
Does PKC use localized movie names for search? E.g.:
```
23:33:16.250 T:42852  NOTICE: PLEX.PlexAPI: Start movie set/collection lookup on themoviedb using Звездные войны: Эпизод 6 - Возвращение Джедая
23:33:17.404 T:42852  NOTICE: PLEX.PlexAPI: No themoviedb match found using year 1983
23:33:17.404 T:42852  NOTICE: PLEX.PlexAPI: Still no themoviedb match for type: movie, title: Звездные войны: Эпизод 6 - Возвращение Джедая, year: 1983
```
I think there should be original name: _Star Wars: Episode VI - Return of the Jedi_. themoviedb search for localized names is worse, it works for _[Star Wars: Episode VI - Return of the Jedi](https://www.themoviedb.org/search?query=Star+Wars%3A+Episode+VI+-+Return+of+the+Jedi)_, and it doesn't work for _[Звездные войны: Эпизод 6 - Возвращение Джедая](https://www.themoviedb.org/search?query=%D0%97%D0%B2%D0%B5%D0%B7%D0%B4%D0%BD%D1%8B%D0%B5+%D0%B2%D0%BE%D0%B9%D0%BD%D1%8B%3A+%D0%AD%D0%BF%D0%B8%D0%B7%D0%BE%D0%B4+6+-+%D0%92%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D0%B5+%D0%94%D0%B6%D0%B5%D0%B4%D0%B0%D1%8F)_, but it works again for a shorter request _[Возвращение Джедая](https://www.themoviedb.org/search?query=%D0%92%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D0%B5+%D0%94%D0%B6%D0%B5%D0%B4%D0%B0%D1%8F)_.

**Comment by arabesc** [comment]
As far as I understood logs, the movie_view table should not be empty but it is.

**Comment by arabesc** [comment]
I've just noticed that there is more information available in the TV shows section:
![screenshot 2018-01-07 04 02 51](https://user-images.githubusercontent.com/2709027/34645492-f9ea859a-f35f-11e7-9f39-a919093c8688.png)
![screenshot 2018-01-07 04 03 03](https://user-images.githubusercontent.com/2709027/34645493-fdaefb98-f35f-11e7-9bdd-de2d6d06f0aa.png)
![screenshot 2018-01-07 04 03 12](https://user-images.githubusercontent.com/2709027/34645495-0062c95a-f360-11e7-94a3-ed2b3670e337.png)
![screenshot 2018-01-07 04 03 22](https://user-images.githubusercontent.com/2709027/34645496-0257470e-f360-11e7-883a-893283b5572b.png)
All that data was extracted from Plex, at the same time all of those subcategories are empty.
I don't know how PKC works, but it seems that something disturbs database access.

**Comment by croneter** [comment]
Check out these log entries after the PKC initial sync (which basically copies the Plex DB into Kodi):
```
22:38:05.778 T:17440  NOTICE: CVideoDatabase::CleanDatabase: Starting videodatabase cleanup ..

22:38:06.470 T:17440 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.plexkodiconnect/movies/?dbid=1&mode=play&id=29879&filename=%2Flibrary%2Fmetadata%2F29879
22:38:06.470 T:17440 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.plexkodiconnect/movies/?dbid=10&mode=play&id=26150&filename=%2Flibrary%2Fmetadata%2F26150
22:38:06.470 T:17440 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.plexkodiconnect/movies/?dbid=100&mode=play&id=100042&filename=%2Flibrary%2Fmetadata%2F100042
22:38:06.470 T:17440 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.plexkodiconnect/movies/?dbid=1000&mode=play&id=89042&filename=%2Flibrary%2Fmetadata%2F89042

22:38:09.570 T:17440   DEBUG: CVideoDatabase::CleanDatabase: Cleaning files table
22:38:09.583 T:17440   DEBUG: CVideoDatabase::CleanDatabase: Cleaning movie table
22:38:09.712 T:17440   DEBUG: CVideoDatabase::CleanDatabase: Cleaning episode table
22:38:09.717 T:17440   DEBUG: CVideoDatabase::CleanDatabase: Cleaning paths that don't exist and have content set...
22:38:09.718 T:17440   DEBUG: CVideoDatabase::CleanDatabase: Cleaning tvshow table
22:38:09.718 T:17440   DEBUG: CVideoDatabase::CleanDatabase: Cleaning path table
22:38:09.718 T:17440   DEBUG: CVideoDatabase::CleanDatabase: Cleaning genre table
22:38:09.718 T:17440   DEBUG: CVideoDatabase::CleanDatabase: Cleaning country table
22:38:09.718 T:17440   DEBUG: CVideoDatabase::CleanDatabase: Cleaning actor table of actors, directors and writers
22:38:09.757 T:17440   DEBUG: CVideoDatabase::CleanDatabase: Cleaning studio table
22:38:09.757 T:17440   DEBUG: CVideoDatabase::CleanDatabase: Cleaning set table
22:38:09.767 T:17440  NOTICE: CVideoDatabase::CleanDatabase: Cleaning videodatabase done. Operation took 00:03
```
Change your [Kodi advancedsettings.xml](http://kodi.wiki/view/Advancedsettings.xml#videolibrary) to reflect the following (the `false` is important, you should have a `true` there now:
```
 <videolibrary>
    <cleanonupdate>false</cleanonupdate>  <!-- default set to false to prevent Kodi from removing items from the database while updating.  -->
</videolibrary>
```
Then do the following:
1) Reboot Kodi!
2) Reset PKC: go to the PKC settings, Advanced, `Reset the Kodi database ...` (in red). Hit Yes, Yes, No
3) Reboot Kodi and let PKC do its magic

**Comment by croneter** [comment]
I will force this Kodi setting in the next PKC update!

**Comment by arabesc** [comment]
Here is my advanced.xml:
```
<advancedsettings>
	<video>
		<dxvaallowhqscaling>true</dxvaallowhqscaling>
	</video>
	<imagescalingalgorithm>bicubic_spline</imagescalingalgorithm>
	<pictureexcludes>  <!-- Regular expressions that if evaluated to true won't be displayed in My Pictures -->
		<regexp>_raw</regexp>
		<regexp>_private</regexp>
		<regexp>_bad</regexp>
	</pictureexcludes>
	<cache>
	<memorysize>335544320</memorysize>  <!-- number of bytes used for buffering streams in memory
                                                 When set to 0 the cache will be written to disk instead of RAM -->
	<buffermode>1</buffermode>  <!-- Choose what to buffer:
                                           0) Buffer all internet filesystems (like "2" but additionally also ftp, webdav, etc.) (default)
                                           1) Buffer all filesystems (including local)
                                           2) Only buffer true internet filesystems (streams) (http, etc.)
                                           3) No buffer -->
	<readfactor>10.0</readfactor> <!-- this factor determines the max readrate in terms of readfactor * avg bitrate of a video file.
                                           This can help on bad connections to keep the cache filled. It will also greatly speed up buffering. Default value 4.0. -->
	</cache>
	<fullscreen>true</fullscreen>
</advancedsettings>
```
It's reflected in the logs also:
`22:37:41.567 T:17440  NOTICE: Contents of special://profile/advancedsettings.xml are...`

There is no such record as:
```
 <videolibrary>
    <cleanonupdate>true</cleanonupdate>
</videolibrary>
```

I've done what you suggested but it doesn't help.

I've attached a new log.
There are records:
```
19:18:12.381 T:4984  NOTICE: Contents of special://profile/advancedsettings.xml are...
                                              <videolibrary>
                                                <cleanonupdate>false</cleanonupdate>
                                              </videolibrary>

```
and:
`19:18:35.960 T:4984  NOTICE: CVideoDatabase::CleanDatabase: Starting videodatabase cleanup ..`

It seems that something forces db cleanup after a sync.

[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/1609948/kodi.zip)

**Comment by croneter** [comment]
Yes you still got this entry in the log, the cause for all this evil:
```
NOTICE: CVideoDatabase::CleanDatabase: Starting videodatabase cleanup ..
```
I guess one of your other Kodi/SPMC add-ons is triggering these. Kodi/SPMC should not just clean/refresh the database.

Could you try deactivating all other add-ons, then reboot, then reset PKC again?

**Comment by arabesc** [comment]
Caught it! It was due to [Library Auto Update](http://kodi.wiki/view/Add-on:XBMC_Library_Auto_Update) add-on, there is an option to cleanup library after a sync.
Thanks!
