### ISSUE TITLE
Resetting texture cache doesn't work properly

### ISSUE THREAD

**Issue by Pavuucek** [croneter/PlexKodiConnect#392]
How to reproduce:
Open PKC settings -> Artwork -> Cache all images to kodi texture cache -> Yes -> Yes

What should happen (or at least how I understand it):
1) contents of Textures13.db should be deleted
    - this works
2) userdata/thumbnails folder should be deleted
    - this also happens
3) userdata/thumbnails folder AND it's sub-folders should be recreated (and images cached there)
   - this doesn't happen and kodi starts flooding log with messages like following, because it assumes all folders are still there.

`20:49:55.517 T:1199428512  NOTICE: PLEX.artwork: Image cache sync about to process 0 music images
20:49:57.773 T:1080030112  NOTICE: CreateThumbnailFromSurface: unable to create thumbnail special://masterprofile/Thumbnails/3/38feec11.jpg 360x540
20:50:00.594 T:1080030112  NOTICE: Previous line repeats 1 times.
20:50:00.594 T:1080030112  NOTICE: CreateThumbnailFromSurface: unable to create thumbnail special://masterprofile/Thumbnails/7/7bc715f9.jpg 1280x720
20:50:01.917 T:969929632  NOTICE: CreateThumbnailFromSurface: unable to create thumbnail special://masterprofile/Thumbnails/2/2c40d222.jpg 360x540
20:50:04.539 T:969929632  NOTICE: Previous line repeats 1 times.
20:50:04.539 T:969929632  NOTICE: CreateThumbnailFromSurface: unable to create thumbnail special://masterprofile/Thumbnails/a/a38cd63b.jpg 1280x720
20:50:06.975 T:995095456  NOTICE: CreateThumbnailFromSurface: unable to create thumbnail special://masterprofile/Thumbnails/a/af976e35.jpg 383x540`

I'll provide full log if necessary

**Comment by croneter** [comment]
So how does this affect your Kodi experience exactly? Seems a bit academic
to me

Am 22.01.2018 8:09 nachm. schrieb "Michal Kuncl" <notifications@github.com>:

**Comment by Pavuucek** [comment]
Never mind. I'll try to fix this myself
