### ISSUE TITLE
Sync had to skip some items because they could not be processed

### ISSUE THREAD

**Issue by tomatosoupcan** [croneter/PlexKodiConnect#395]
Been getting this every hour or so for a few days now. No idea what is going on. Tried a full database reset from the settings of PKC with no luck, tried upgrading PKC with no luck. kodi.log attached: [kodi.log](https://github.com/croneter/PlexKodiConnect/files/1690693/kodi.log)

**Comment by croneter** [comment]
Thanks for sharing your log. The cause is this:
```
PLEX.itemtypes: ADD song itemid: 58045 - Title: 東京シナリオ
NOTICE: PLEX.itemtypes: Album database entry missing.
NOTICE: PLEX.itemtypes: ADD album itemid: 58042 - Name: シュガーソングとビターステップ
NOTICE: PLEX.itemtypes: UPDATE artist: strArtist: UNISON SQUARE GARDEN, idArtist: 57640
NOTICE: PLEX.itemtypes: ADD song itemid: 58045 - Title: 東京シナリオ
ERROR: PLEX.utils: add_updateSong has crashed. Error: UNIQUE constraint failed: song.idSong
ERROR: PLEX.utils: Traceback:
                                            Traceback (most recent call last):
                                              File "C:\Users\Benjamin\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\utils.py", line 951, in wrapper
                                                return func(*args, **kwargs)
                                              File "C:\Users\Benjamin\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\resources\lib\itemtypes.py", line 1784, in add_updateSong
                                                dateplayed, rating, 0, 0, mood))
                                            IntegrityError: UNIQUE constraint failed: song.idSong
```
Looks like you found a bug that only occurs if there is no album first, then PKC tries to sync a song without the respective album, then tries to add the missing album. 

I will look into it!

**Comment by tomatosoupcan** [comment]
Interesting given that all of my synced songs should have proper album metadata. Anything I can do metadata wise on my end to patch it up in the meantime?

**Comment by croneter** [comment]
No I don't think so, sorry

**Comment by croneter** [comment]
@tomatosoupcan 
Could you please share the PMS xml info for this song? Use Plex Web, navigate to any movie or episode, hit  the three dots ... at the top right, choose `Show information`, then `Show xml`. A new window pops up. In the URL bar, leave everything exactly like it is, but replace the item's ID. So you start with e.g. 
```
https://192.168.0.2:32400/library/metadata/458160?checkFiles=1&includeExtras=1&X-Plex-Token=<TOKEN>
```
Replace the number after metadata with `58045` so you end up with
```
https://192.168.0.2:32400/library/metadata/58045?checkFiles=1&includeExtras=1&X-Plex-Token=<TOKEN>
```
Please share the entire xml here

**Comment by tomatosoupcan** [comment]
Here's 58045:
`<MediaContainer size="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1510642226"></MediaContainer>`

But I think that's not right. Looks like the ID for the song may have changed, so I grabbed that as well which is now 58152:
`<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="3" librarySectionTitle="Music" librarySectionUUID="50768ea7-a25f-49ae-9ba8-719047f353b1" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1510642226">
<Track ratingKey="58152" key="/library/metadata/58152" parentRatingKey="58149" grandparentRatingKey="57640" guid="local://58152" librarySectionID="3" librarySectionKey="/library/sections/3" type="track" title="東京シナリオ" grandparentKey="/library/metadata/57640" parentKey="/library/metadata/58149" grandparentTitle="UNISON SQUARE GARDEN" parentTitle="シュガーソングとビターステップ" summary="" index="3" parentIndex="1" thumb="/library/metadata/58149/thumb/1517766200" parentThumb="/library/metadata/58149/thumb/1517766200" grandparentThumb="/library/metadata/57640/thumb/1517213835" duration="279249" addedAt="1517766190" updatedAt="1517766200">
<Media id="63703" duration="279249" bitrate="323" audioChannels="2" audioCodec="mp3" container="mp3">
<Part accessible="1" exists="1" id="64127" key="/library/parts/64127/1517213408/file.mp3" duration="279249" file="\\?\D:\Libraries\Music\New\[ì–¼í‹°ë©”ì´íŠ¸] [150520] TVã‚¢ãƒ‹ãƒ¡ã€Œè¡€ç•Œæˆ¦ç·šã€EDãƒ†ãƒ¼ãƒžã€Œã‚·ãƒ¥ã‚¬ãƒ¼ã‚½ãƒ³ã‚°ã¨ãƒ“ã‚¿ãƒ¼ã‚¹ãƒ†ãƒƒãƒ—ã€ï¼UNISON SQUARE GARDEN (320K)\MP3\03. æ±äº¬ã‚·ãƒŠãƒªã‚ª.mp3" size="11285483" container="mp3" hasThumbnail="1">
<Stream id="98850" streamType="2" selected="1" codec="mp3" index="0" channels="2" bitrate="320" audioChannelLayout="stereo" samplingRate="44100"/>
</Part>
</Media>
<Extras size="0"></Extras>
</Track>
</MediaContainer>`

**Comment by croneter** [comment]
Did 58152 fail as well? I need the PMS metadata for an item that caused PKC to crash. They are: 58031, 58035, 58039, 58045

**Comment by tomatosoupcan** [comment]
58031:
`<MediaContainer size="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1510642226"></MediaContainer>`
58035:
`<MediaContainer size="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1510642226"></MediaContainer>`
58039:
`<MediaContainer size="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1510642226"></MediaContainer>`
58045:
`<MediaContainer size="0" identifier="com.plexapp.plugins.library" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1510642226"></MediaContainer>`

I have one line in my log file regarding 58152:
`13:43:14.171 T:104148  NOTICE: PLEX.itemtypes: Deleted song: 58152 from kodi database`

**Comment by croneter** [comment]
You should get much more info than that (compared to the xml you get for a video as described above). XML for one of my songs:
```
<MediaContainer size="1" allowSync="1" identifier="com.plexapp.plugins.library" librarySectionID="3" librarySectionTitle="Musik" librarySectionUUID="bea191fd-1eae-45c0-8ad8-96657bdbafd3" mediaTagPrefix="/system/bundle/media/flags/" mediaTagVersion="1517321106">
<Track ratingKey="9" key="/library/metadata/9" parentRatingKey="8" grandparentRatingKey="7" guid="com.plexapp.agents.plexmusic://gracenote/track/158662880-1743362967C0FF88063290277AC654DB/158662881-2A743E83C2CB6A2626C28AC6F9E710D7?lang=en" librarySectionTitle="Musik" librarySectionID="3" librarySectionKey="/library/sections/3" type="track" title="Train" grandparentKey="/library/metadata/7" parentKey="/library/metadata/8" grandparentTitle="3 Doors Down" parentTitle="3 Doors Down" summary="" index="1" parentIndex="1" ratingCount="632587" year="2008" thumb="/library/metadata/8/thumb/1514963464" art="/library/metadata/7/art/1514963445" parentThumb="/library/metadata/8/thumb/1514963464" grandparentThumb="/library/metadata/7/thumb/1514963445" grandparentArt="/library/metadata/7/art/1514963445" duration="190642" addedAt="1396692904" updatedAt="1514963464">
<Media id="5" duration="190642" bitrate="213" audioChannels="2" audioCodec="mp3" container="mp3">
<Part accessible="1" exists="1" id="5" key="/library/parts/5/1396692904/file.mp3" duration="190642" file="C:\Temp\Test-Music\01 Train.mp3" size="5081616" container="mp3" hasThumbnail="1">
<Stream id="13" streamType="2" selected="1" codec="mp3" index="0" channels="2" bitrate="211" audioChannelLayout="stereo" samplingRate="44100"/>
</Part>
</Media>
<Mood id="282" filter="mood=282" tag="Heavy Brooding"/>
<Extras size="0"></Extras>
</Track>
</MediaContainer>
```

**Comment by croneter** [comment]
Seems like the Plex library is a bit off. Try the [Plex Dance](https://forums.plex.tv/discussion/257246/what-is-the-correct-way-to-plex-dance) once just for your music library. See if PKC still crashes on sync

**Comment by croneter** [comment]
Anyway, think I found the bugger. Let me know if the new PKC beta version (to be released very soon :-)) shouldn't help

**Comment by tomatosoupcan** [comment]
Can't connect to the beta repo, so hopefully the plex dance helps out

**Comment by croneter** [comment]
See here for that problem: https://github.com/croneter/PlexKodiConnect/issues/374

But again: new PKC version needs to be pushed first from my side 😉
