### ISSUE TITLE
Possible issue with multiple clients. 

### ISSUE THREAD

**Issue by richardap1** [croneter/PlexKodiConnect#40]
I noticed today that if I start watching something (tv show) in the Plex web interface and stop it after several minutes, for example 6, the web interface shows it as in progress but kodi shows it as competed. Anyone else see this. Will try to get logs when I get back.

PKC 1.1.11
Kodi 15.2

**Comment by croneter** [comment]
Interesting. PKC should mark something as done once you have passed 95% of the total play time

**Comment by croneter** [comment]
I got the same behavior. This is a Kodi/skin issue, in my case the Titan skin. It will show the element as having been completely played, but actually Kodi knows that this is not the case. If you immediately try to resume/play the item again, it WILL give you the option to resume e.g. at 6 minutes. 

So it ain't PKC's fault :-). Nothing I can do about this
