### ISSUE TITLE
Enabling music (direct paths) causes a restart loop

### ISSUE THREAD

**Issue by dazedcrazy** [croneter/PlexKodiConnect#402]
Kodi v17.6
PKC 2.0.2
My first time trying to add music from Plex to Kodi so it's probably an already known problem but i keep getting this everytime i start Kodi
![jec4fnm](https://user-images.githubusercontent.com/9027988/36109654-ee2bb1d2-1017-11e8-8cd7-ba9730ad56a8.png)

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1717150/kodi.log)
I have to go into kodi\userdata\addon_data\plugin.video.plexkodiconnect\settings.xml and disable music from there to get Kodi to start as normal again

**Comment by dazedcrazy** [comment]
Tested https://github.com/croneter/PlexKodiConnect/commit/754432f5bc2cbf554b49ebb5b369e854631ddd98 works great, thanks 👍

**Comment by dazedcrazy** [comment]
Did notice something while adding music to a different device (libreelec one) today, the audio setting added by PKC in advancedsettings.xml
```
  <audio>
    <excludefromscan />
  </audio>
```
Was getting library sync errors until i removed it, it gets replaced with
```
  <audio>
    <excludefromscan>
      <regexp>^smb://media-pc/audiobook/</regexp>
      <regexp>^smb://media-pc/music/</regexp>
    </excludefromscan>
  </audio>
```
Not sure if that actually was causing it i just know that when i removed it it synced fine

**Comment by croneter** [comment]
This was extremely helpful, @dazedcrazy , many thanks!!
