### ISSUE TITLE
Issue with playback on Nvidia Shield TV

### ISSUE THREAD

**Issue by Homaxz** [croneter/PlexKodiConnect#403]
I have a Nvidia Shield TV 2017 running Kodi 17.6 and PlexKodiConnect 1.8.18.

I'm trying to play a video file which is in a library of 900 files, it loads for 1-2 minutes and then fails to play. 
It works flawlessly on my Host PC running the same Kodi configuration.

Using PMP to play the file on the Nvidia Shield TV works as well, but I need the Kodi player for subtitles etc.

**Comment by croneter** [comment]
Please follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

My guess is that you're trying to play play all 900 files at once

**Comment by Homaxz** [comment]
Hi, sry about that. I logged it now but the file is too huge to upload here and pastebin as well. Can I send to your email or is there another way?

**Comment by croneter** [comment]
Email won't work then, unfortunately. You could put it on your Dropbox and make it public. Or open a new project here on github und just put the log on there 😆

**Comment by Homaxz** [comment]
Here is the Dropbox link: https://www.dropbox.com/s/yxe5s05q5ovr45v/kodi.zip?dl=0

**Comment by croneter** [comment]
Does 2.0.3 help?

**Comment by croneter** [comment]
By the way - you officially crashed my computer because you log is so big 😆 

So if you still have this issue, please restart Kodi. Then replicate the issue while debug logging is turned on. Then share the much smaller log here again

**Comment by Homaxz** [comment]
Sorry about that. 2.0.3 didn't work for me, it failes to load plex after I open Kodi.

The log is from a fresh instance of Kodi and it's still so big.

**Comment by croneter** [comment]
Should be fixed with new PKC version 2.0.4. Let me know here if this should not be the case.
