### ISSUE TITLE
PKC unstable after database error

### ISSUE THREAD

**Issue by CrankyCraig** [croneter/PlexKodiConnect#404]
Hi Croneter,

Only a week or so into a fresh Kodi installation and I received an error message. I paid little attention to the message at the time unfortunately, not believing that the error would have any long term adverse effect. It did,  and though I can't recite the exact message, the essence of it was that PlexKodiConnect expirienced a database error and may now be unstable, requesting me to report my logs. 

Now, every 6-7 seconds a message appears which says 'Compressing Database', as if it's attempting it but failing to do so. As I type this it's happening on 3 clients simultaneously, so I don't know whether that suggests a problem server side or with the clients.

The message was there to greet me in the morning on 2 separate Kodi clients (also each running separate Plex Media Servers) that run 24/7. I've changed and updated so much lately in an effort to address some niggles with the old Kodi installations that I can't begin to suggest what may have been the cause, though in the few days before the message I hadn't made any changes to anything at all. Automatic updates were enabled for both the server and Kodi. 

I've tried a full PKC reset twice, but I haven't tried a fresh installation yet. I can of course, but I figured I'd await your instruction first.

Other info that may or may not be useful:
Both instances of PMS are running server version 1.10.1.4602. All PKC clients are set up to connect to only one server.
Both servers are owned by me with the same Plex User and are on the same local network.
Only a single user is used in each Kodi client.

All clients are using an identical Kodi install, consisting of the Titan skin with only a few additional add-ons installed:
Picture Slideshow Screensaver
PlexKodiConnect
LazyTV
Trakt
CU LRC Lyrics
A couple of Skin related add-ons required by Titan.

If the error wasn't caused by something I did wrong setting it up, I'd be surprised. Here's the Log:

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1718260/kodi.log)

If you need any additional info just let me know.

Kind regards.

Craig.

**Comment by croneter** [comment]
There is nothing in the log except a couple of these: 
```
XFILE::CFile::Delete - Error deleting file C:\Users\Tablet PC\AppData\Roaming\Kodi\userdata\Thumbnails\b\bad65335.jpg
```
Are you possibly using a crappy SD card as your C drive? Kodi is allergic to that...

Other than that, please do a complete reset of PKC (PKC Settings -> Adanced -> Reset the Kodi database..., then YES, YES; NO). Let PKC rescan everything. Then share that log.

**Comment by CrankyCraig** [comment]
No, the C drive is an SSD, but there are flash drives attached to the machine I took these logs from which contain media used for the second server.

That log was immediately after a complete reset of PKC. Does the problem lie elsewhere?

**Comment by CrankyCraig** [comment]
Just another small observation. Just requested a library update, which triggered the same flashing screen behaviour again (I believe it stops after 200 attempts?), but the watched status' in Kodi aren't reflecting that of the server. I disbaled Trakt in both the server and client and tried again. Still not updating.

**Comment by croneter** [comment]
So there's 3 issues here really: 
1. A PKC pop-up that PKC might be unstable because of ...
2. "Flashing screen" when you request a library update using **Plex Web** (and not PKC)
3. The Kodi watch status does not reflect the Plex watch status

Number 2 is to be expected as the PMS will (re-)scan potentially thousands of files. It doesn't do that usually except you request it. Don't worry about it. If something's off, a PKC full sync will take care of it (happening ~60 minutes automatically in the background). 

Number 3 can happen if you use the PKC widgets, mostly. They don't automatically update when they should. I hope to solve this sometime. 

Number 1 worries me. Please do a PKC reset: in the PKC settings under Advanced, choose Reset the Kodi library (in red), then YES, YES, NO. Let Kodi restart and PKC do the initial sync. Then grab the log BEFORE restarting Kodi

**Comment by CrankyCraig** [comment]
The points you made were correct, but hopefully all are solved now. 

No. 2 was solved by removing a video file that appears to be corrupt. PMS was really unhappy with it, constantly processing it, which is a behaviour I've never seen before. I deleted the file, rescanned the library (in PMS) and PMS is no longer fixated on it. Restarted Kodi/PKC and it too now seemed happy, with no more flashing screen and no more 'Compressing Database' message. I hoped it was fixed, but shortly after I get what I believe is the message from a few days ago appearing on 2 of the clients:
 
PlexKodiConnect:
Sync had to skip some items because they could not be processed. Kodi may be unstable now. Please post your Kodi Logs to the Plex forum.

I rechecked PMS and noticed a new message in the Server Settings beside the PMS version which said 'something went wrong. Please install manually'.

I reinstalled Plex and, although it's only been a few hours since, all seems well. Kodi logs are showing no errors and there's no strange behaviour from PMS or Kodi. My hope is that was also the issue that Kodi/PKC was warning me of in No.1. Fingers crossed.

After wrestling Kodi, PKC and Plex for a bit I still couldn't get the correct watched status' to return. They were right on the server, but not on the Kodi clients. I had to Google widgets to find out what they are, and whether I use them, but I'm still none the wiser which suggest I probably don't. Perhaps, if I'd allowed the systems time to settle back down they would have corrected themselves, but I tried running Trakt (which I'd disabled) and that appears to have done the trick.

Thanks for all your help Croneter, it does seem the problems were stemming from the server. If anything changes I'll let you know.

Kind regards.

Craig

**Comment by croneter** [comment]
OK, thanks for letting me know. 

Please reopen or open a new issue :wink:
