### ISSUE TITLE
PKC companion on windows and bonjour dependency

### ISSUE THREAD

**Issue by Draic** [croneter/PlexKodiConnect#405]
I have installed PKC on a windows platform today and had the issue that the companion could not connect to plex. The error message was to change the ports. After some tinkering I saw that the real culprit was lacking bonjour on the machine. After I installed bonjour, but left the service DISABLED in windows, companion is working. So even without bonjour actually running, companion works (while zeroconf won't, as bonjour is not actually running). Seems to be there is some dependency on it somewhere? Not really a big problem, but I thought maybe you could add some info in the doc for people, or update/expand the error message in kodi

**Comment by croneter** [comment]
Bonjour is only needed for AirPlay and has nothing to do with PKC. I think it was rather a Kodi webserver issue. I added this to the Kodi wiki here: https://github.com/croneter/PlexKodiConnect/wiki/faq
