### ISSUE TITLE
Invalid root path for some shows (plugin path instead of samba)

### ISSUE THREAD

**Issue by RickDB** [croneter/PlexKodiConnect#406]
**Issue**

Show root paths for some shows not pointing to smb:// path but instead links to plugin://plugin.video.plexkodiconnect/tvshows/'id'/, they do work but mess up smart playlists which filter by path for instance.
Files themselves have the correct SMB path so it's just the show root path that is inconsistent.

Some examples from Kodi interface:

root path correctly set to samba path
<img width="1920" alt="correctpath" src="https://user-images.githubusercontent.com/347084/36177642-af5d866a-1116-11e8-86a1-50741b67a3ad.PNG">

root path incorrectly set to plugin path
<img width="1920" alt="invalidpath" src="https://user-images.githubusercontent.com/347084/36177647-b1415718-1116-11e8-88ea-78fd271c5373.PNG">

Doubled checked the Kodi video DB and see a few there:

show with samba root path
<img width="1333" alt="correctpath2" src="https://user-images.githubusercontent.com/347084/36177894-70bed066-1117-11e8-9bb1-6e2c55186145.PNG">

shows with plugin path as root
<img width="1349" alt="invalidpath2" src="https://user-images.githubusercontent.com/347084/36177749-00b8666a-1117-11e8-95a2-6817d930a0f3.PNG">

Checked the linking of the example show "The Seven Deadly Sins" and indeed see it linked to a tv show plugin path with root path plugin://plugin.video.plexkodiconnect/ :

<img width="395" alt="invalidpath3" src="https://user-images.githubusercontent.com/347084/36193140-f56445ba-1164-11e8-86bb-1eb6bba799c4.PNG">
<img width="180" alt="invalidpath4" src="https://user-images.githubusercontent.com/347084/36193142-f65a3592-1164-11e8-9d2c-ebe2d5749be0.PNG">
<img width="1316" alt="invalidpath4_5" src="https://user-images.githubusercontent.com/347084/36193278-94811902-1165-11e8-9a67-565929ab74f2.PNG">
<img width="1314" alt="invalidpath5" src="https://user-images.githubusercontent.com/347084/36193192-2d7e59e0-1165-11e8-8816-9b6ae5927458.PNG">

That show has the same root directory as all my anime so should have been able to translate correctly.

**Steps to reproduce**

No idea at this point as it seems random, ranges from new shows but also older without any pattern and paths are normal without any special characters.
Can PM the logs but they are just showing the navigation and no import errors whatsoever.
Already tried a complete PKC reset and Kodi DB wipe but same result each time.

**PKC settings**
Native paths with translate unc to smb active, pretty much default and just using direct paths

**System information**

Kodi 17.4
PlexKodiConnect 2.0.2 (latest beta)
PMS 1.11.3.4793
Windows 10 x64

**Comment by RickDB** [comment]
Added a a completely new show and it got a root path point to plugin path as well, seems that new shows coming from Plex Media Server get handled differently than existing entries.

**Comment by RickDB** [comment]
Looks to be scanner related as path is missing completely from the Plex API results so reported to Absolute Series Scanner instead, if it turns out to be a PlexKodiConnect bug will re-open :)

**Comment by croneter** [comment]
Awesome, thanks for letting me know @RickDB 😆

**Comment by croneter** [comment]
Looks to me like PKC was exceptionally stable and did what it could to let you watch these videos 😆

**Comment by RickDB** [comment]
Yeah, fallback works perfectly and loving 2.0 so far :D
Seems related to season folders but hopefully developer there can sort it out:

https://github.com/ZeroQI/Absolute-Series-Scanner/issues/131
