### ISSUE TITLE
Kodi collection/set poster is not the Plex collection poster

### ISSUE THREAD

**Issue by ghost** [croneter/PlexKodiConnect#408]
Kodi will not load the right collection posters from my Plex Media Server.
Can you please look at this issue? I want to have the posters I've selected by myself.
This collection feature at Plex Media Server is new since the release of version 1.11.1.4760. 

## **Plex - American Pie Collection Poster**
![american pie collection plex printscreen](https://user-images.githubusercontent.com/16412293/36230538-01b1fdbe-11db-11e8-80b9-02b5e7691547.JPG)

## **Kodi - American Pie Collection Poster**
![american pie collection kodi printscreen](https://user-images.githubusercontent.com/16412293/36230537-018b5eac-11db-11e8-9bdb-d74ed4a3e975.JPG)

**Comment by Hollander1908** [comment]
Please?🙊

**Comment by dazedcrazy** [comment]
There is no API call to get the poster or collection summary from plex so PKC goes to TMDb to get it's poster [(the one you linked is the first one)](https://www.themoviedb.org/collection/2806-american-pie-collection/images/posters). If you want to use your own artwork you can use [Movie Set Artwork Automator](https://forum.kodi.tv/showthread.php?tid=153502) or [Artwork Beef](https://forum.kodi.tv/showthread.php?tid=258886)

**Comment by croneter** [comment]
As @dazedcrazy explained, the collection feature is new to Plex. PKC does not yet use it to grab the Plex artwork but rather gets its own. 

Low priority to implement since it's just cosmetic :wink:

**Comment by Hollander1908** [comment]
Okay. 
But it’s now looking at FanArtTV for missing artwork. 
Can you please change it back to TMDb?

**Comment by srk15372** [comment]
Hi, I hope this feature will arrive. It would be perfect

**Comment by andrewsris** [comment]
Hello, thank you very much for your hard work. I just wanted to ask if there are any updates in regards to this issue? It seems that PKC does not pull collection poster from the Plex collection poster.

**Comment by andrewsris** [comment]
> Hello, thank you very much for your hard work. I just wanted to ask if there are any updates in regards to this issue? It seems that PKC does not pull collection poster from the Plex collection poster.

Just to follow-up on my own comment. I'm not sure what combination of settings I changed, but it works now and this is not an issue anymore. Thank you again!
