### ISSUE TITLE
Wrong playing information on Plex APP using PlexCompanion

### ISSUE THREAD

**Issue by tomzini** [croneter/PlexKodiConnect#410]
step 1. I log into the Plex App with a user different from the one used on PKC.
step 2. From Plex App, I play something locally on the device (KODI). Then I stop it.
step 3. On kodi I play something else, then I connect the Plex App to PKC.

Sometimes I have no "now playing" information at all, some other times what I see in the "nowplaying" section is the "step 2" content information, but the track progress slider and time information are aligned to "step 3" content, and controls work.

**Comment by croneter** [comment]
You are not even giving me the PKC version number. 

Please follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by tomzini** [comment]
yes sorry!
PKC versione 2.0.2

**Comment by croneter** [comment]
Debug log as described in the link?

**Comment by tomzini** [comment]
Reproduced on version 2.0.3
in the attachment the logs

[bug-2_kodi.log](https://github.com/croneter/PlexKodiConnect/files/1733575/bug-2_kodi.log)

Following the action prefromed for this test:

- log into the plex app with a different user regarding the one used in pkc connect to PKC
- play something starting from the plex app
- stop it
- through kodi and pkc I started playing something else
- on android plex app I can see a correct track length, a working control and a working slider, but the cover is remained the one I played before, starting from the plex app. Moving to next track, same thing (frozen cover, working controls, working feedbacks for length and progress bar)

In addition I have try the same test accessing to the Plex APP with same user of PKC, and I see the same issue. I also found that the problem seem happen with playing in background (default for audio play)

BR

**Comment by croneter** [comment]
Should be fixed with new PKC version 2.0.4. Let me know here if this should not be the case.
