### ISSUE TITLE
 Nvidia Shield TV(android) slowness

### ISSUE THREAD

**Issue by aniel300** [croneter/PlexKodiConnect#413]
im having couples of issues/bugs
1) on the Nvidia Shield TV and android (i believe this issue does not apply for windows) in general where movies or tv show Widgets scrolling is really slow 
2)when scrolling inside movies category in wall mode, the poster will lag on show up, 
3)playback from x265 is laggy (cant confirm x264) 
any ideas

**Comment by croneter** [comment]
For the first 2 points, see https://github.com/croneter/PlexKodiConnect/wiki/faq#kodi-is-missing-backgrounds--fanart-and-black-screens-show-up-kodi-browsing-is-slow-images-take-a-while-to-load

For the last, there is nothing PKC can do. H265 playback is more demanding for your hardware. Check the Kodi forum for further help
