### ISSUE TITLE
Repeated warning about missing setting definitions during library scan

### ISSUE THREAD

**Issue by Lou-Cipher** [croneter/PlexKodiConnect#414]
I've noticed during some recent debugging that during library scans, my logs are being filled with the following, repeating seemingly for every media library item (so, big big logs).  This is on 2.0.3.

`19:08:29.316 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting definitions
19:08:29.316 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: trying to load setting definitions from old format...
19:08:29.316 T:139827827701504 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: cannot reference separator setting in old setting condition "eq(-1,true)" for "skipContextMenu"
19:08:29.316 T:139827827701504 WARNING: CAddonSettings[plugin.video.plexkodiconnect]: failed to parse visible condition "eq(-1,true)" of old setting definition for "skipContextMenu"
19:08:29.318 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: loading setting values
19:08:29.319 T:139827827701504   DEBUG: CSettingsManager: requested setting (InstallQuestionsAnswered) was not found.
19:08:29.319 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting InstallQuestionsAnswered. Creating a setting on-the-fly...
19:08:29.319 T:139827827701504   DEBUG: CSettingsManager: requested setting (SyncInstallRunDone) was not found.
19:08:29.319 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting SyncInstallRunDone. Creating a setting on-the-fly...
19:08:29.319 T:139827827701504   DEBUG: CSettingsManager: requested setting (dbCreatedWithVersion) was not found.
19:08:29.319 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting dbCreatedWithVersion. Creating a setting on-the-fly...
19:08:29.319 T:139827827701504   DEBUG: CSettingsManager: requested setting (last_migrated_PKC_version) was not found.
19:08:29.319 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting last_migrated_PKC_version. Creating a setting on-the-fly...
19:08:29.319 T:139827827701504   DEBUG: CSettingsManager: requested setting (plexAvatar) was not found.
19:08:29.319 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting plexAvatar. Creating a setting on-the-fly...
19:08:29.319 T:139827827701504   DEBUG: CSettingsManager: requested setting (plex_client_Id) was not found.
19:08:29.319 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting plex_client_Id. Creating a setting on-the-fly...
19:08:29.319 T:139827827701504   DEBUG: CSettingsManager: requested setting (plex_machineIdentifier) was not found.
19:08:29.319 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting plex_machineIdentifier. Creating a setting on-the-fly...
19:08:29.319 T:139827827701504   DEBUG: CSettingsManager: requested setting (plexid) was not found.
19:08:29.319 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting plexid. Creating a setting on-the-fly...
19:08:29.319 T:139827827701504   DEBUG: CSettingsManager: requested setting (userid) was not found.
19:08:29.319 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting userid. Creating a setting on-the-fly...
19:08:29.319 T:139827827701504   DEBUG: CSettingsManager: requested setting (username) was not found.
19:08:29.319 T:139827827701504   DEBUG: CAddonSettings[plugin.video.plexkodiconnect]: failed to find definition for setting username. Creating a setting on-the-fly...
19:08:30.415 T:139826720388864   DEBUG: Thread JobWorker 139826720388864 terminating (autodelete)
19:08:30.824 T:139827802523392   DEBUG: PLEX.websocket_client: PMS_Websocket: Received message from PMS server: {u'PlaySessionStateNotification': [{u'viewOffset': 30099, u'playQueueItemID': 41128, u'url': u'', u'ratingKey': u'8896', u'state': u'playing', u'sessionKey': u'66', u'key': u'/library/metadata/8896', u'guid': u''}], u'type': u'playing', u'size': 1}
19:08:30.829 T:139829270525696   DEBUG: PLEX.plexbmchelper.subscribers: Sent server notification with parameters: {'hasMDE': '1', 'X-Plex-Provider-Version': '2.0.3', 'X-Plex-Platform': 'Linux', 'playQueueItemID': '41128', 'ratingKey': '8896', 'key': '/library/metadata/8896', 'duration': 172666, 'X-Plex-Device-Name': u'PlexKodiConnect', 'X-Plex-Token': u'xxxxxxxxxxxxx', 'X-Plex-Model': 'unknown', 'X-Plex-Platform-Version': 'unknown', 'X-Plex-Client-Identifier': u'xxx-xxx-xxx-xxx', 'X-Plex-Device': 'Linux', 'state': 'playing', 'X-Plex-Product': 'PlexKodiConnect', 'time': 30099, 'X-Plex-Version': '2.0.3'} to https://xxx.xxx.xxx.xxx:32400/:/timeline
`
Tokens and IPs have been obfuscated to protect the guilty.  I'm wondering if these on-the-fly settings creations are supposed to be persistent, or if this is indicative of a larger problem?  This is on Kodi 18 alpha (built from my fork-of-a-fork at https://github.com/Lou-Cipher/xbmc, but happens on a vanilla Kodi 18 build, too.  In either case, this is after making the modifications I mention at the end of https://github.com/croneter/PlexKodiConnect/issues/339, otherwise you don't get far enough to see the errors).

**Comment by croneter** [comment]
PKC is not yet Kodi 18 compatible. Also, apparently the saving of settings changed from 17 to 18:
```
trying to load setting definitions from old format
cannot reference separator setting in old setting condition "eq(-1,true)" for ....
```
This will be a major pain in the a... to fix, because I don't see a way to make PKC both Kodi 17 and 18 compatible at the same time. For other Kodi 18 issues, see https://github.com/croneter/PlexKodiConnect/issues/339

On the other hand - are your PKC settings working for you using Kodi 18?

**Comment by Lou-Cipher** [comment]
Yeah, everything appears to be working, I was just concerned by the log output.
