### ISSUE TITLE
Own movie trailers are gone

### ISSUE THREAD

**Issue by Hollander1908** [croneter/PlexKodiConnect#416]
Movie trailers from my server are gone. Can only do a manually search for trailers. But it don’t give me the option to play the movie trailers I’ve selected. Example: Movie (2018)-trailer.mp4 Please fix that issue. This was a lot of work.😂

**Comment by Hollander1908** [comment]
At version 1.8.18 it was working well. Got the newest beta and now it’s not working anymore.

**Comment by croneter** [comment]
Should be fixed with new PKC version 2.0.4. Let me know here if this should not be the case.

**Comment by Hollander1908** [comment]
Yeah, it’s working again!
Everything is so much faster after updating tot 2.0.4. :-)

Thank you so much!
