### ISSUE TITLE
Version 2.04 installation problem

### ISSUE THREAD

**Issue by Sparh4wk** [croneter/PlexKodiConnect#417]
Hi,

I have a problem installing new beta version.. I reinstalled even kodi, but every single time that I want install it from zip file, it gives me this error: 

![uflz1bz](https://user-images.githubusercontent.com/7014826/36618577-efd563c0-18eb-11e8-956b-6be466bd5003.png)

any suggestions?

thanks

**Comment by croneter** [comment]
Yes, logs! https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by Sparh4wk** [comment]
sry I forget about it
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1753306/kodi.log)

**Comment by croneter** [comment]
Install the PKC repo first: https://github.com/croneter/PlexKodiConnect/wiki/Install-from-ZIP-file
Then install PKC from the repo. You might need to reboot kodi or manually install the two PKC helper add-ons that you'll find in the repo (because you tried to manually install PKC)

**Comment by croneter** [comment]
Hmm, the link above is not saying much. Simply follow the instructions here: https://github.com/croneter/PlexKodiConnect/wiki/Installation

**Comment by Hollander1908** [comment]
This was working for me. 
Install beta repo and after that install 2.0.4.
