### ISSUE TITLE
Nvidia shield tv pro (old and new model) laggy playback 

### ISSUE THREAD

**Issue by aniel300** [croneter/PlexKodiConnect#418]
so i have been trying to run kodi+plexkodiconnect+nvidia shield tv but im getting this issue where it will make the performance/playback really slow, it happens random, it was worse i managed to kind of fix by following suggestion [here](https://github.com/croneter/PlexKodiConnect/issues/182) but issue still happening randomly, i believed this is related specifically to the nvidia shield tv, i have no issue on my windows 10, oneplus 5 and a Chinese android tv box, i have tried kodi, 17.6, 18 and spmc but no luck. 

things i have tried

1) fresh install of kodi kodi, 17.6, 18 and spmc 17

2) posted an bug report on [github](https://github.com/croneter/PlexKodiConnect/issues/413) but i think he didn't understood me. 

3) bough 2017-2018 nvidia shield tv model

4) suggestion [here](https://github.com/croneter/PlexKodiConnect/issues/182)

5) disable plexkodiconnect and play same movie/tv show over ftp and performance and playback back to normal

6) few other ts

7) I might open a new bug report 

8) i can make a video or something if you want

thank you, any feedback or suggestion will be appreciated

original post [here](https://www.reddit.com/r/Addons4Kodi/comments/80j9if/plexkodiconnectnvidia_shield_tv_pro_old_and_new/), [here](https://www.reddit.com/r/PleX/comments/80ipk6/plexkodiconnectnvidia_shield_tv_pro_old_and_new/) and [here](https://www.reddit.com/r/kodi/comments/80ipdh/plexkodiconnectnvidia_shield_tv_pro_old_and_new/)

**Comment by croneter** [comment]
You need to be WAY more specific describing your issue! 
* What exactly is slow? Navigating Kodi libraries? Playback? Playback cannot possibly be "slow", but maybe stutter (which would have nothing to do with PKC). 
* Have you tried the new PKC beta version 2.0.4? If not, do so.
* Share a DEBUG log file [as described here](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug) of your issue occuring (using the newest PKC beta version 2.0.4)

**Comment by croneter** [comment]
Looking at your original post, did you do as proposed?
> PKC caches all artwork in the background, not during initial sync. Restart Kodi and let it sit for a while to let PKC do its magic. For ~500 movies and ~1000 episodes, 30-60 minutes should do it.
If that does not work, go to the PKC settings, then choose Cache all images to Kodi texture cache now under Artwork. Again, let PKC do its invisible magic in the background for at least 60 minutes.

**Comment by aniel300** [comment]
Yes sir i have tried 2.0.4, i did mention that if i disable pkc, playback and performance go back to normal, but yet i issue does not happen on my windows 10 machine, oneplus 5 or Chinese set top box, please tell me whatever i need to do to help u pinpoint the issue and hopefully fix it, thanks

**Comment by croneter** [comment]
You could start by answering all the questions above

**Comment by aniel300** [comment]
1-What exactly is slow?: when pkc is enable kodi performance is bad (moving around, hiccups/stuttering during play back. 
2-Navigating Kodi libraries? part of the performance issue, but not the major concern (playback is my main concern because i start playing a movie or something and out of the blue it start stuttering)
3-Playback? Playback cannot possibly be "slow", but maybe stutter (which would have nothing to do with PKC).: idk if it has something to do with pkc or not, im not a developer just yet andi really appreciate your project, i just wish it works, 
4-Have you tried the new PKC beta version 2.0.4? If not, do so.: yes i have tried it.
Share a DEBUG log file as described here of your issue occuring (using the newest PKC beta version 2.0.4): https://drive.google.com/file/d/1b1vePO0_-pc0umlvs5GB-OxZ-H5lqehb/view?usp=sharing  (could not use pastebin)

**Comment by croneter** [comment]
Thanks for the log. 

## 1) Playback issues
Seems like Kodi has issues with your video codec:
````
03:18:05.948 T:138185499728   ERROR: CDVDMediaCodecInfo::ReleaseOutputBuffer ExceptionCheck index(12), render(1)
03:18:06.289 T:138185499728   ERROR: CDVDMediaCodecInfo::ReleaseOutputBuffer ExceptionCheck index(5), render(1)
03:18:06.395 T:138185499728   ERROR: CDVDMediaCodecInfo::ReleaseOutputBuffer ExceptionCheck index(11), render(1)
03:18:06.573 T:138185499728 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
03:18:06.761 T:138185499728   ERROR: CDVDMediaCodecInfo::ReleaseOutputBuffer ExceptionCheck index(13), render(1)
03:18:07.140 T:138185499728   ERROR: CDVDMediaCodecInfo::ReleaseOutputBuffer ExceptionCheck index(7), render(1)
03:18:07.363 T:138185499728   ERROR: CDVDMediaCodecInfo::ReleaseOutputBuffer ExceptionCheck index(6), render(1)
03:18:07.491 T:138185499728   ERROR: CDVDMediaCodecInfo::ReleaseOutputBuffer ExceptionCheck index(1), render(1)
03:18:07.743 T:138505339984   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
```
This has nothing to do with PKC. PKC only servers up the video file. Additionally you're streaming h265 from Plex. This is very taxing on both Plex and Kodi. You could try the following:
* Restart Kodi. Then just let it sit for say 30 minutes. Seriously. The initial scan in your log did not seem finished. 
* Use [direct paths](https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths). Plex won't need to stream, that might help with the demanding h265 codec
* Use h264 instead of h265. 

## 2) Moving around
Nothing suspicious in the log there. But again, your initial sync was not finished. Restart Kodi and let it sit for 30 minutes. Artwork is cached by PKC (if you did not change the default PKC setting under artwork) - navigating Kodi should be a breeze, no slow loading of artwork. Follow the FAQs if navigating is not smooth: 
> PKC caches all artwork in the background, not during initial sync. Restart Kodi and let it sit for a while to let PKC do its magic. For ~500 movies and ~1000 episodes, 30-60 minutes should do it.
If that does not work, go to the PKC settings, then choose Cache all images to Kodi texture cache now under Artwork. Again, let PKC do its invisible magic in the background for at least 60 minutes.

**Comment by aniel300** [comment]
Edit: recorded video audio got de synced after hiccup from disabling pkc

**Comment by croneter** [comment]
Thanks for the video. Again you ignored my suggestions above, which still hold true in my opinion. 
* did you try to use direct paths? If not, do so now. 
* Is the Plex Media Server also on your shield?
* I noticed that Kodi navigation is STILL laggy even if you deactivate PKC. Hence this is NOT an issue with PKC but with your entire shield setup!

**Comment by croneter** [comment]
Edit - you even get a pop-up AFTER deactivating PKC saying "SPMC is not responding"

**Comment by aniel300** [comment]
Yeah that is what happens when i was disabling but that is beside the point, all im trying to demonstrate to u is that playback and performance is terrible when pkc is enabled, i did a comparison between using pkc and ftp for the stream. I don't understand why can't understand, i will a try to direct paths but then again i have same set up on my windows 10, one plus 5 and Chinese set top box and issue is not present, i think is has something to do with the shield or shield Android os version, idk because im not a dev, i might try installing a 8.1 Android tv( lineage os) available for the shield but i dont if i want go to the trouble just to confirm if pkc will work on that rom

**Comment by croneter** [comment]
Let me tell you again very clearly: PKC is NOT responsible for the laggy playback. It cannot be, because it hands over playback to Kodi entirely. Please also answer ALL questions above. Otherwise I'm getting the impression here that you're trolling me...

**Comment by croneter** [comment]
Any news?

**Comment by aniel300** [comment]
Thanks for the video. Again you ignored my suggestions above, which still hold true in my opinion.

did you try to use direct paths? If not, do so now: i did but it was giving lot of error related to files not being missing, so i gave up on that ( i dont think issue is related to this but i could be wrong)

Is the Plex Media Server also on your shield?: plex app come pre install and for one second i tough issue was related to the plex app being install and the server feature being on but i disable it and issue was still present ( i aslo disable the plex app and server app but issue still ) 

I noticed that Kodi navigation is STILL laggy even if you deactivate PKC. Hence this is NOT an issue with PKC but with your entire shield setup!: when pkc is disable in the contrary, performance is back to normal

note for croneter: i kinda was hesitating to answer to you because u seen to got upset, my intention was never meant for you to think that the issue im having was cause because of pkc but instead for you to hep me pin point the issue and if it an issue indeed to find a solution to it (i believe it is called debugging) anyways, right now i think is going to be either related to the shield hw or sw.

my next ts steps are: install android oreo from [here](https://forums.geforce.com/default/topic/1034999/android-8-1-shield-tv-linageos-15-1-based-oreo-preview-download/) and/or wait for android oreo from nvidia for further ts.

thank you for this project and keep up the good work

**Comment by croneter** [comment]
I think you need to try to use [direct paths](https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths) in order to play h265 videos without hiccups. h265 put a lot of strain on both Kodi and the Plex Media Server. If you manage to use direct paths, you can cirrcumvent the PMS entirely for playback - chances are that playback will be fine. 

Sanity check: do you have another Plex client (e.g. the official [Plex for Kodi](http://forums.plex.tv/categories/plex-for-kodi) that CAN direct play h265 without hiccups?

So **setting up direct paths** is your next steps if you want to use your hardware/software AND h265. Unfortunately that calibration is not easy...
