### ISSUE TITLE
The dependency on plugin.video.plexkodiconnect.movies version 2.0.0 could not be satisfied.

### ISSUE THREAD

**Issue by Cyriltra** [croneter/PlexKodiConnect#420]
Hi Croneter,

I got this error when trying to install beta 2.0.4 on librelec
Could you please let me know what to do ?

Thank you

**Comment by croneter** [comment]
Follow the installation guideline and install the Kodi REPOSITORY, not PKC itself, as described here: https://github.com/croneter/PlexKodiConnect/wiki/Installation

THEN install PKC using the PlexKodiConnect repository. Dependencies will be taken care of
