### ISSUE TITLE
Problems connecting to plex server

### ISSUE THREAD

**Issue by nhorvath** [croneter/PlexKodiConnect#422]
After selecting my server from the list kodi.log is spammed with this line repeating:

10:32:09.406 T:139637767948032 WARNING: PLEX.downloadutils: Server unreachable at: https://192.168.1.50:32400/library/onDeck
10:32:09.406 T:139637767948032 WARNING: PLEX.downloadutils: HTTPSConnectionPool(host='192.168.1.50', port=32400): Max retries exceeded with url: /library/onDeck (Caused by SSLError(CertificateError("hostname '192.168.1.50' doesn't match '*.5829d328c8c649caa1346d800e0a2bdd.plex.direct'",),))

I have verify client ssl unchecked in settings so I don't know why it's complaining about this at all.

**Comment by nhorvath** [comment]
Went back into settings and it somehow rechecked itself. I unchecked it again and it connected. So I guess the real issue is:
1. Why do I have to uncheck this?
2. Why does it recheck itself when plex reconnects?

**Comment by croneter** [comment]
* does only the log get "spammed" with a couple of entries? OR do you experience actual issues connecting?
* the verify ssl checkbox in the settings is meant to be used if you entered your pms IP manually 
* selecting a local pms will let PKC attempt to directly connect to it, circumventing plex.tv. Hence the ssl log entry,

**Comment by nhorvath** [comment]
I mean the logs are constant as it tries to request everything. I didn't
enter anything manually but if I go to the url it is trying to get then I
do see an invalid https certificate because it is trying to go to IP
addresses but the hostname is in the certificate.

**Comment by croneter** [comment]
So I understand that you have no issue using PKC/Kodi at all after you uncheck "Verify SSL Certificate" in the PKC settings. 

Closing issue
