### ISSUE TITLE
Kodi not marking as watched straight away.

### ISSUE THREAD

**Issue by JonathanGorbutt** [croneter/PlexKodiConnect#423]
Hi,

So for some reason when I have finished watching something Kodi will tick the episode to say its has been watched, I will then click back a few times to see my shows and the show I just watched will show 1 episode still to watch (the one I just watched) so I go back into the season of that show and Kodi shows the episode as in-progress (but resuming the episode will send me right to the very end of the episode basicly 1 second before the episode ends)

after a little bit Kodi will update and the episode will be marked as watched, I just don't understand whats causing this?

Trust you understand my problem, haha :) 

Many Thanks

**Comment by Draic** [comment]
Not sure if related, but 2.0.5 broke watch states again for me aswell. For now I would recommend sticking to 2.0.4 until a new version comes out

**Comment by croneter** [comment]
Does the new 2.0.6 help?

**Comment by Draic** [comment]
for me it does not. Same as with 2.0.5. Finished playback will not mark as watched. Not in kodi and not on the Plex server either.

**Comment by hstamas** [comment]
2.0.6 was not working at all for me in Add-on mode. All shows watched would eventually revert back to an in progress state. Switching back to Direct Paths fixed the problem.

**Comment by CrankyCraig** [comment]
I'm experiencing some similarly odd problems with watched status' too. Hard to find a pattern in the behaviour at the moment. I'll respond when I better understand what's going on.
