### ISSUE TITLE
Failed: HTTP response code said error(22)

### ISSUE THREAD

**Issue by Cyriltra** [croneter/PlexKodiConnect#424]
Hello

After a fresh sync with beta 2.0.5 I got a lot of following errors in kodi.log

> 20:14:37.459 T:545938993376  NOTICE: PLEX.PlexAPI: Start movie set/collection lookup on themoviedb with 300: Rise of an Empire
20:14:37.480 T:545603449056   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://192.168.50.10:32400/library/parts/991/1452004802/
20:14:37.480 T:545603449056 WARNING: Process directory 'https://192.168.50.10:32400/library/parts/991/1452004802/' does not exist - skipping scan.
20:14:37.701 T:545603449056   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://192.168.50.10:32400/library/parts/992/1452004851/
20:14:37.701 T:545603449056 WARNING: Process directory 'https://192.168.50.10:32400/library/parts/992/1452004851/' does not exist - skipping scan.
20:14:37.881 T:545603449056   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://192.168.50.10:32400/library/parts/993/1452004901/
20:14:37.881 T:545603449056 WARNING: Process directory 'https://192.168.50.10:32400/library/parts/993/1452004901/' does not exist - skipping scan.
20:14:38.068 T:545603449056   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://192.168.50.10:32400/library/parts/994/1452004860/
20:14:38.068 T:545603449056 WARNING: Process directory 'https://192.168.50.10:32400/library/parts/994/1452004860/' does not exist - skipping scan.
20:14:38.256 T:545603449056   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for https://192.168.50.10:32400/library/parts/995/1452004868/
20:14:38.256 T:545603449056 WARNING: Process directory 'https://192.168.50.10:32400/library/parts/995/1452004868/' does not exist - skipping scan.

**Comment by croneter** [comment]
Known issue: https://github.com/croneter/PlexKodiConnect/issues/14

Only spams your Kodi log file but should not be noticable otherwise
