### ISSUE TITLE
issue with accessing plex over cdn

### ISSUE THREAD

**Issue by bbourdet** [croneter/PlexKodiConnect#425]
i use a plex server that is behind a cdn. i tried to use the main plex addon for kodi, but it has problems. i am getting constant disconnect errors. i read the faq and have disabled constant background sync. here are my logs, any help would be greatly appreciated.
[pkc.log](https://github.com/croneter/PlexKodiConnect/files/1787779/pkc.log)

**Comment by croneter** [comment]
Please enable Kodi debug logging and share the log file again, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by bbourdet** [comment]
Here is the debug log. Please let me know if i didnt strip out all the sensitive info.
[pkc-debug.log](https://github.com/croneter/PlexKodiConnect/files/1789310/pkc-debug.log)

**Comment by bbourdet** [comment]
Tried with a bunch of settings changes but could not get it to work last night. Hard to believe I would be the only one seeing this, must be something with my setup. Is there an older version that might work better?

**Comment by bbourdet** [comment]
Do you see anything in the logs?

**Comment by croneter** [comment]
So the connection seems to be working fine, except websockets on port 443. Any chance you could open that port? 

Otherwise, disabling constant background sync should lead to websockets not even being started. Did you restart kodi after disabling the setting?

**Comment by bbourdet** [comment]
I don’t have control over the server I can ask. I believe I did restart Kodi after that setting but I will try again. Would that prevent me from being able to play anything? Currently I don’t believe anything will play.

**Comment by croneter** [comment]
No it doesn't prevent you from playing anything. The error message is just annoying

**Comment by bbourdet** [comment]
Ok. Well I am unable to play anything and even with the background sync disabled I am still seeing the web socket messages.

**Comment by bbourdet** [comment]
Moved it from direct play to force transcode. Now it is working! If we disable background sync, when will pkc get new content from the plex server?

**Comment by croneter** [comment]
I fixed the deactivation of the constant background sync (websocket shutdown wasn't working). With the next PKC beta version, you shouldn't be bothered with these popup messages anymore. 

A full sync will take place by default every 60min. You can change that under the sync settings. If you don't have other Plex clients using the same Plex username and don't want to share playstates across clients (say you stopped watching James Bond at 20% using Plex for Android and want to immediately resume on PlexKodiConnect), you shouldn't really notice a difference
