### ISSUE TITLE
Trailers play the wrong file

### ISSUE THREAD

**Issue by zonly1** [croneter/PlexKodiConnect#426]
Playing a trailer (from information window) for a movie does not play the trailer, instead plays the last played regular movie (a different movie completely and not a trailer).
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1790940/kodi.log)

Movie trailers are PlexPass's Plex Movie Agent and not local in the movie folders.

PKC 2.0.7 but has been happening with previous 2.0 beta releases.

**Comment by zonly1** [comment]
I went back to 1.8.18 to test and trailers played normally so it's related to 2.0 only. I also tested on multiple machines, same result.

**Comment by croneter** [comment]
Thanks for reporting. I think I already found a cure! No need for further research from your side

**Comment by zonly1** [comment]
Thanks croneter for the quick fix, will stay on 1.8.18 for now till you release a new beta cause I don't like reseting the database very often. I was also having an issue with 2.0 where a played movie would not show in now playing on the server status page (not sure if it's a related bug).
