### ISSUE TITLE
Xbox one - library sync crash

### ISSUE THREAD

**Issue by ivlovric** [croneter/PlexKodiConnect#427]
After installing and configuration of latest beta on Xbox ONE Kodi 18 alpha build, but tried with older stable versions also, plugin can not start and there is an error "Library sync thread has crashed".
I know kodi 18 is still alpha and things will get better, but since Xbox one is new platform maybe there is more that needs to be done on plugin side.
Thanks.

**Comment by croneter** [comment]
PKC does not yet support Kodi 18. See here for possible workarounds you could do yourself in the meantime: https://github.com/croneter/PlexKodiConnect/issues/339
