### ISSUE TITLE
Plex Now Playing shows a previously played movie, and not the current one sometimes

### ISSUE THREAD

**Issue by zonly1** [croneter/PlexKodiConnect#428]
Plex Server shows now playing the previously played movie if it was started from a widget like In progress or recently added movies and even playing an IPTV channel using Simple IPTV add-on.

So if I start Pacific Rim for example from a widget, it'll show correctly in now playing. If I stop the movie and play The Avengers also from a widget, Plex will show Pacific Rim instead in Now playing although on Kodi, The Avengers is playing (or even a TV channel).

Also the playing position timing gets messed up.

It reports back normally if I play a file from the Movies list normally (not from a widget from the home screen).

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1808548/kodi.log)

hope this helps cause it's an annoying bug.

Thanks croneter.

**Comment by croneter** [comment]
Thanks for the log! Let me know if update 2.0.9 does not fix your issue. Please enable DEBUG logging then 😉

**Comment by croneter** [comment]
Ahhh, just saw that you enabled debug logging after the issue happening. Good call, 'cause I couldn't reproduce it 😆 . Thx again!

**Comment by zonly1** [comment]
Ok, updated to 2.0.9. Same issues.
Only happening to my LibreELEC setup. On my Desktop computer it does NOT happen at all, not sure why. Here is another full log (sorry about the previous one).

Steps done:
-Restarted and enabled debug logging
-Played 300 , then Zootopia, from library - All reporting correctly.
-Played Jumanji from recently added - still good.
-Played Downsizing from recently added, and it reported as  Jumanji from previously played (still plays Downsizing correctly though)
-Played Star Wars from recently added also reported as Jumanji.
-Played Zootopia from Library - Shows Correctly in Now Playing again
-Played Star Wars from Widget again - Shows Correctly
-Played Jumanji from Widget - Reports as Star Wars.

If I play an IPTV channel after playing a movie from a widget, Plex reports as if i'm playing that file again (Clearly I'm not). 

When the widget bug happens, it messes up my playback position for In Progress movies.

Haven't tested TV Shows.

Hope this helps further.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1811113/kodi.log)

**Comment by zonly1** [comment]
The only difference I can think of is that the Desktop computer (Windows 10) does not use Custom Paths (both options disabled) because it's on the same machine as my media. LibreELEC uses custom paths with both options enabled.

Not sure if it helps.

**Comment by croneter** [comment]
Could you please try resetting the Kodi database, that REALLY might help. (PKC settings, Advanced, then reset the Kodi database (in red)). Thx!

**Comment by croneter** [comment]
I cannot make much sense of your log: there are no entries of PKC playback startups. It looks like Kodi still DIRECTLY starts playback. So I'd really guess that you had direct paths in your Kodi database. Please try resetting as described above and see if the problem disappears.

**Comment by croneter** [comment]
Ah, found it - playback report for Direct Paths is buggy. Thx for the report, can fix it now!

**Comment by zonly1** [comment]
Thanks a lot croneter, I already reset the database, will I need to reset it again to apply the fix when the next beta is out?
Also, I found another bug where if the In progress movies widget is empty (not visible) and you start a movie and not finish it, the In progress movies widget does not show up unless you restart Kodi, can you reproduce that? Should I open a new Issue for it?

**Comment by croneter** [comment]
Already fixed 😆

**Comment by zonly1** [comment]
This fix works great with the exception of a certain scenario. If you play a file with Kodi, then play another in Plex for Kodi addon (I don't think many people will have this issue) The Plex server reports the file being played by the Plex for Kodi addon AND the previously played file in PKC (it's not playing obviously). I like to use the addon sometimes for it's music interface.

A very minor bug and I can kind of understand why it happens from the code but I thought I'd report it anyway.

If you need a log I'll be happy to provide.

Thanks for all your great work croneter.
