### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by channelup69** [croneter/PlexKodiConnect#429]
I have an Apple tv and I wanted to know if you can provide a repository instead of downloading a zip file. Its easier to download via adding a new source  in code.  I also wanted to know how hard would it be to fork https://github.com/plexinc/plex-for-kodi and add the channels option.

**Comment by croneter** [comment]
There has been a repository for ages. It's linked all over the place. Check here: https://github.com/croneter/PlexKodiConnect/wiki/Installation and simply hit either the stable or beta BUTTON 

Channels are already supported. Main problem is that plex doesn't give a damn anymore about channels

**Comment by channelup69** [comment]
Ok thanks.....I was referring to the plex addon in the kodi official
repository that launches in kiosk mode...it doesn't offer support for
channels.
