### ISSUE TITLE
PKC constantly wakes up the server for no reason

### ISSUE THREAD

**Issue by Draic** [croneter/PlexKodiConnect#43]
Even with all sync and login stuff disabled in the settings (which seem to not do anything at all; yes I restarted), PKC still constantly nags my server and keeps it awake. I want PKC to only sync when I tell it to and not connect to the server in anyway unless I tell him. This currently is not the case or is broken.

Using a RPI3 with a fresh install of XBian running Kodi16.1

**Comment by croneter** [comment]
Detailed logs please.

**Comment by Draic** [comment]
Will do. First I also want to state that I have disabled logging me into plex.tv automaticly on startup. It still logs me in every time.

**Comment by Draic** [comment]
Will attach the full log but the culprit seems this: 
```
07:43:39  89.819931 T:1611097008  NOTICE: PlexKodiConnect plexgdm -> discover : Sending discovery messages: M-SEARCH * HTTP/1.0
07:43:40  90.420822 T:1611097008  NOTICE: PlexKodiConnect plexgdm -> discover : Number of servers Discovered: 1
07:43:40  90.421143 T:1611097008  NOTICE: PlexKodiConnect plexgdm -> discover : Server Discovered: {'updated': 1464068620, 'protocol': u'https', 'class': None, 'owned': '1', 'port': u'32400', 'uuid': u'6cf5cd84117ff35722ebfddc0f760437641e6613', 'serverName': u'Fringe', 'server': u'192.168.2.13', 'version': 'irrelevant', 'master': 1, 'role': 'master', 'content-type': 'plex/media-server', 'discovery': 'auto'}
```

PKC does this constantly and will never let my server sleep. No idea how to turn it off.
Also the logs states that PKC does a sync on startup which I do not want to happen but unable to disable aswell.

[kodi.log.txt](https://github.com/croneter/PlexKodiConnect/files/278849/kodi.log.txt)
