### ISSUE TITLE
Remote Server not working

### ISSUE THREAD

**Issue by Hollander1908** [croneter/PlexKodiConnect#430]
When I want to play a movie or tv-show from a friend his PMS it won't play..
When I play files from my own PMS it's working fine.

I have two profiles on Kodi: 1. Master User - 2. PMS from a friend

**Comment by croneter** [comment]
I cannot possibly help you without a log, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by Hollander1908** [comment]
I don't know how to export kodi.log from a Nvidia Shield TV.
Can you help me?

**Comment by croneter** [comment]
Try this: https://kodi.wiki/view/Log_file/Easy

**Comment by Hollander1908** [comment]
Thanks!
Here is my kodi.log

[Kodi.log](https://github.com/croneter/PlexKodiConnect/files/1822675/Kodi.log)

**Comment by croneter** [comment]
You did NOT read the link above and posted your Plex token (=Plex password, more or less) for everyone to see. Please immediately follow the advice `I published my Plex token to some forum or Github. Anyone can now access my Plex Server!` here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by Hollander1908** [comment]
Ok, how can I delete this log file?

**Comment by croneter** [comment]
You did not install PlexKodiConnect correctly, no idea how you managed to make it run in the first place:
```
ERROR: Unable to find plugin plugin.video.plexkodiconnect.tvshows\
```
Please uninstall PlexKodiConnect completely. Then uinstall the PlexKodiConnect REPOSITORY as described in detail here: https://github.com/croneter/PlexKodiConnect/wiki/Installation

Download the ZIP file by clicking either the button `stable version: latest` or `beta version: latest`. And NOT by downloading anything else from Github.

**Comment by croneter** [comment]
Your password is out in the wild - no matter whether you delete the log file here now or not. So please follow the advice at the very bottom of https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
And please let me know if installing PKC correctly doesn't solve your problem 😉

**Comment by Hollander1908** [comment]
Yeah, changed password. Thanks for the advice!
I will uninstall PlexKodiConnect. If it’s not working I will come back to you!
