### ISSUE TITLE
In progress TV shows widget broken

### ISSUE THREAD

**Issue by zonly1** [croneter/PlexKodiConnect#432]
Hi croneter, 2.0 is becoming solid for me but I found another bug with the TV shows In progress widget on the home screen.

It simply does not work nothing happens when you play an item from the "In progress" widget. If I open information window, it takes me to the show information window but the play button also does not work there. Works fine if played from a the Plex video node or other places.

I tried to play a Star Wars Clone Wars episode and nothing happens, then I tried an episode of The Flash but gave me a playback error this time and finally an episode of legends of tomorrow and again nothings happens (no error). 

Here's the log
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1823350/kodi.log)

**Comment by croneter** [comment]
Should be solved with the new beta version 2.0.11. Please let me know here if this should not be the case!

**Comment by zonly1** [comment]
It works fine if I have Default select action in media settings set to "Play". If it's set to "Information", it doesn't work.
