### ISSUE TITLE
Trailers not Working

### ISSUE THREAD

**Issue by FreeSoftwareServers** [croneter/PlexKodiConnect#433]
I just seutp KodiPlexConnect and I am loving it so far. The direct play is exactly what I wanted! But, I can't get trailers to work. I even re-setup everything to confirm it was this addon that caused the issue. I first installed Kodi 17.6, added a local movie, installed youtube, watched a trailer. Yay!, Installed KodiConnectPlex and added Plex Movie library and switched to Aeon skin and "Trailer" is greyed out :(..

PS: I also re-setup Plex! I am now using the latest version.

Full Setup Details:

Kodi 17.6 w/ AEON Skin (Tested w/ Estuary as well, no luck)
KodiPlexConnect setup via Repo w/ Latest & AutoUpdate
Plex 1.12.0.4829 
DirectPlay w/ ReWrite SMB Paths configured and working
Windows 10 x64 is my "client"

![trailer grey](https://user-images.githubusercontent.com/16218200/37593400-10a7e9ec-2b2f-11e8-95a6-69dfa0793ba9.png)

**Comment by croneter** [comment]
Try the newest beta version, should be working fine... Otherwise, I need DEBUG log files, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by FreeSoftwareServers** [comment]
It tested new beta, same thing. Option is "greyed out". I doubt anything would be in logs, but I can pass you kodi.log which is what I gathered you want based on reading that URL. I skipped all the "delete/refresh" etc by just re-installing fresh each time. I did want to clarify something from that URL, do I need to worry about Plex Token if I didn't sign into my account? I just use local PMS server that is unclaimed, I dont even sign in on my PMS. (I really dislike how much they are pushing you to sign in).

**Comment by croneter** [comment]
Ah, now I get it!

Trailers are a [Plex Pass feature](https://support.plex.tv/articles/200288566-what-is-plex-pass/). PKC only adds plex trailers to the Kodi database, nothing from third parties. If what you are describing were possible, you would circumvent Plex pass. I love Plex and they just need a way to make some money.... Sorry, that's not gonna get "fixed"

**Comment by FreeSoftwareServers** [comment]
But Kodi itself can play trailers via YouTube. I don't understand how PKC would break that function.

**Comment by croneter** [comment]
PKC DOES support trailers for movies like you described above - simply buy a Plex Pass :wink:

**Comment by FreeSoftwareServers** [comment]
Well, I don't necessarily see the benefit of this over plexbmc, it also allows rewrite and smb direct play, but its less maintained and polished, yet has more functionally. I may switch back since there is a working PlexBMC for Kodi Krypton. Until my PMS is public i see no need for a plex pass. 

I really don't like the new forced sign in feature in PMS. I see the direction they are going and it makes me appreciate open source software.

**Comment by croneter** [comment]
You may switch back
