### ISSUE TITLE
In progress movies widget

### ISSUE THREAD

**Issue by zonly1** [croneter/PlexKodiConnect#434]
Is it possible to reload the skin after a library update (like Kodi does after running it's library update) so In progress movies widget shows up if it was invisible before because it was empty?

**Comment by croneter** [comment]
Problem is that this behavior renders e.g. the Titan skin pretty much unusable. I take it you're using the standard Kodi skin Confluence?

I could re-introduce the skin-reload but would have to set the PKC standard to NOT reload

**Comment by zonly1** [comment]
If you mean like a setting that I can switch, that can work. I use Kodi 17 default skin Estuary.
