### ISSUE TITLE
Feature-Request: Plex-Channels: Expose/use summary attribute

### ISSUE THREAD

**Issue by pannal** [croneter/PlexKodiConnect#439]
Hey,

I'm the author of the [Sub-Zero subtitle plugin](https://github.com/pannal/Sub-Zero.bundle) for the Plex Media Server and I was very pleased to see that PKC supports Plex plugin channels. Thank you for all the hard work you've put into PKC!

There is one thing missing from the implementation, that would make it even more complete:
Sub-Zero heavily relies on the `summary` attribute of the `MediaContainer.Directory` entries, to present crucial information to the user, like information about the current subtitle, subtitle provider metadata, score breakdowns and information about the current menu item.

Is it possible to expose the contents of that attribute and map it to an equal Kodi attribute so that the channel views of PKC can relay that information to the user?

Thank you!

PS: Sorry about the amount of tickets; I'm currently trying to replace my Plex4Samsung setup with PKC on a Vero 4K and everything Kodi and PKC related is very new to me.

**Comment by croneter** [comment]
Would you be so kind and use feathub.com for any and all feature requests like everyone else? Bugs only here...
See http://feathub.com/croneter/PlexKodiConnect
