### ISSUE TITLE
TV shows on deck focus not on in progress item

### ISSUE THREAD

**Issue by pannal** [croneter/PlexKodiConnect#441]
I'm using the current beta version of PKC, with the (fuse) neue skin. 

When on deck TV shows is used as a widget, the first focused item is the first on deck item, not the currently in progress item (so not the first item in the list). 

The extend option is enabled for on deck TV shows.

**Comment by pannal** [comment]
Ok, thus might be skin related. It seems to always focus the second  (or even the "middle" one in the viewport?) item in a widget, when nothing was focused before. 

This happens right after a reboot of kodi. If that's not PKC related, I'll file an issue with (fuse) neue.

**Comment by croneter** [comment]
PKC doesn't put the focus anywhere, that's the skin

**Comment by pannal** [comment]
Fair enough, I wasn't sure whether you could indicate which item was first, besides putting it first.
