### ISSUE TITLE
Appearance tweaks: support for recently added episode combining

### ISSUE THREAD

**Issue by pannal** [croneter/PlexKodiConnect#443]
The PMS recentlyAdded API endpoint (and the official clients for that matter) support merging multiple recently added episodes of the same TV show, so they don't clutter up the recently added view.

This would be nice to have for PKC, as well.

![](https://i.imgur.com/hpnZOF3.png)

**Comment by croneter** [comment]
Could you please elaborate - merged how?

**Comment by pannal** [comment]
In the recently added widgets, multiple recently added episodes of the same season get merged to one instance so it doesn't visually clutter up the view.

I think that's a PMS API feature with the recentlyAdded endpoints.

With the mentioned appearance tweak to also show already watched episodes in recently added, this functionality is broken.

**Comment by pannal** [comment]
I've just realized: You don't directly use the recentlyAdded endpoint, do you?

As I've said in my last comment, it merges multiple episodes of one TV show into a series (or season?). The implementation can be seen by looking at recently added for TV shows in PlexWeb.

The recentlyAdded endpoint doesn't necessarily only return Video nodes, but also Directory nodes in that case.

Could this be implemented into PKC as well, so that we have that functionality and when an item that's not a Video node is selected in a recently added view, it opens the specific season or TV show?

**Comment by dazedcrazy** [comment]
Doesn't skinhelper do this for you
![nzyixbf](https://user-images.githubusercontent.com/9027988/37929046-beed0e3a-3136-11e8-8e52-43730dc74b38.png)

**Comment by pannal** [comment]
@dazedcrazy yes, for the normal Recent Episodes widget, but not for the PKC Recently Added one.

**Comment by pannal** [comment]
Updated the ticket to a feature request, not a bug report.

**Comment by croneter** [comment]
Would you be so kind and use feathub.com for any and all feature requests like everyone else? Bugs only here...
See http://feathub.com/croneter/PlexKodiConnect

**Comment by reconman** [comment]
Searched for this feature and only found this issue.

Was the merging of recently added episodes of the same series ever implemented?

**Comment by Nicba1010** [comment]
Anything on this?

**Comment by prism2001** [comment]
yet another blatant oversight of decent UX design that never got addressed

**Comment by prism2001** [comment]
+1 

would really love this, is the main gripe holding me back from using Kodi more often
