### ISSUE TITLE
Add option to prefer external subtitles

### ISSUE THREAD

**Issue by pannal** [croneter/PlexKodiConnect#444]
Hey,

Sorry for the recent onslaught of partially invalid/first-use-error-prone tickets.

As i've stated in #439 I'm the author of Sub-Zero. PKC does a great job of auto-selecting subtitles so far. What I'd like to see is an option to prefer external subtitles over embedded ones. 
They have the `format` attribute set in comparison to embedded ones, also they have no `index` attribute, in the API responses of the PMS.

As Sub-Zero actually (tries to) improve(s) subtitles significantly, even if they're extracted from the embedded subtitle streams, it makes sense to prefer them over the "first-language-match-subtitle-stream".

Thank you!

**Comment by pannal** [comment]
Example of embedded vs. external subtitle streams:
```
<Stream id="685304" streamType="3" codec="srt" index="2" bitrate="0" language="English" languageCode="eng" title="English"/>
<Stream id="685305" streamType="3" codec="srt" index="3" bitrate="0" language="Español" languageCode="spa" title="Spanish"/>
<Stream id="685306" streamType="3" codec="srt" index="4" bitrate="0" language="Français" languageCode="fre" title="French"/>
<Stream id="685307" streamType="3" codec="srt" index="5" bitrate="0" language="Deutsch" languageCode="ger" title="German"/>
<Stream id="685308" streamType="3" codec="srt" index="6" bitrate="0" language="Italiano" languageCode="ita" title="Italian"/>
<Stream id="724967" key="/library/streams/724967" streamType="3" codec="srt" language="English" languageCode="eng" format="srt"/>
```

**Comment by pannal** [comment]
Another option would be to present the user with the available subtitle streams upon playback. I'm actually not sure who decides this currently - PKC, or Kodi itself.

**Comment by croneter** [comment]
Would you be so kind and use feathub.com for any and all feature requests like everyone else? Bugs only here... 
See http://feathub.com/croneter/PlexKodiConnect
