### ISSUE TITLE
PKC issue when playing from Kodi "Movies" from home menu

### ISSUE THREAD

**Issue by zonly1** [croneter/PlexKodiConnect#446]
Another bug with PKC 2.0.13. Playing a movie from a menu widget or from PKC video nodes, plays back fine and reports in "Now Playing" in Plex server correctly.

If I attempt to play from Movies menu item (from Home window), it will take a long time to start the movie and eventually when it plays, Plex server reports nothing although the movie is playing. Any subsequent movies played (even from widgets or nodes) will not report to Plex server. A restart is required for PKC to behave normally until I attempt to play a movie from the Movies menu item.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1861680/kodi.log)

Also noticed that if I rearrange my Plex nodes using the nodes editor they get reset after a restart, is that behaviour normal?

**Comment by zonly1** [comment]
UPDATE: Issue only happens if I have the setting (Settings -> Player -> Videos -> Play next video automatically).
When disabled, it works fine.

**Comment by croneter** [comment]
Will push a new beta in a couple of minutes. Let me know if PKC manages to crash the PMS - it'll build a Plex playqueue for ALL your movies if this setting is enabled :grimacing:

**Comment by zonly1** [comment]
I know, right? checked the logs and was baffled too. Took me some time to figure it out too.

I updated to 2.0.14 but the issue still exists (the other issues got fixed though, thanks), if I enable this setting. (It also occurs on 1.8.18 stable too).
I disabled the setting for now as there are alternative options for TV Shows and I do not need it for movies.
With it disabled, PKC and Kodi are pretty stable with 2.0.14.

I'll keep testing and post issues as I find them.

**Comment by croneter** [comment]
Guess your library is too large. My 400+ movies work now... How many movies are we talking about?

**Comment by zonly1** [comment]
4500+ movies. I guess it is.

**Comment by croneter** [comment]
Added a new warning with commit https://github.com/croneter/PlexKodiConnect/commit/5facbddfc7ebba58436231e8cca66f7c729836c8

It's actually possible that everything works fine, if the initial setup of the (in your case 4500+) playqueue does not take too long. Don't see any way to fix this currently, due to the way Kodi works
