### ISSUE TITLE
Disable during playback

### ISSUE THREAD

**Issue by farfromrefug** [croneter/PlexKodiConnect#451]
Could it be possible to have an option for Pkc not to do anything during playback. I have looked at my log and I clearly can see stuttering issues when Pkc is doing something.
This especially happens when I start a movie right on startup. Doing so I am sure Pkc will connect, communicate and sync during pkayback
Just so you know this is not only due to Pkc because I am on a fire stick and it's quite struggling sometimes. But without plug-ins doing stuffs in the background this is enough.
Thanks

**Comment by croneter** [comment]
That is already the case - when you start playback, sync activities are stopped. There are a bazillion reasons why playback stutters **immediately** after kodi startup

**Comment by croneter** [comment]
Nope, you're right, PKC doesn't stop syncing on playback start, that changed a while ago. How bad is the stuttering? Does it only happen if you start playback after starting up Kodi just a couple of seconds ago?

**Comment by farfromrefug** [comment]
I happens quite often to be honest. The worst is clearly on startup. But i still see stutters like 1h after. And looking at the log i do see plex activity
