### ISSUE TITLE
No playback at all on latest beta 2.0.18

### ISSUE THREAD

**Issue by CraftyClown** [croneter/PlexKodiConnect#452]
Hello mate,

as requested I'm attaching a log to help track the issue

I can't play anything on the latest build. 2.0.18.  

I click on anything and it hangs for about 60 seconds but nothing plays.

I'm on Kodi 17.6 and using addon mode rather than direst paths.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/1913287/kodi.log)

**Comment by Pavuucek** [comment]
I've been having similar issue. The "infinite waiting screen". I tried to play some tv shows. First episode (after start of the device) plays fine, trying to play the next one results in wait screen to pop and disappear after a second or so. Then trying to play anything results in waiting screen that after few minutes crashes the player device.

[kodi.old.log](https://github.com/croneter/PlexKodiConnect/files/1913316/kodi.old.log)

**Comment by Pavuucek** [comment]
It's still happening after updating PKC addons. However I found that this "infinite waiting screen" bug only affects files that are played via smb. Files streamed via https play just fine and I can play as many as I like. Until trying to play a file via smb, that is. 
[kodi.old.log.zip](https://github.com/croneter/PlexKodiConnect/files/1917391/kodi.old.log.zip) (sorry, a big one)

Also: why do mp4 files always prefer to be played via https? Just curious.

**Comment by since85** [comment]
same problem with kodi 18, with build 2.0.17 no problems

**Comment by croneter** [comment]
Thanks for the logs guys. I think I found the issue, just takes a while to fix. Thanks for beta-testing anyway 😉

**Comment by since85** [comment]
https://Ko-fi.com/home/coffeeshop?txid=41f80e03-e0ea-4818-a198-1ff729de5d68&mode=public&img=ogiboughtsomeone

**Comment by croneter** [comment]
:lol: many thanks!

**Comment by croneter** [comment]
Please be so kind and try beta version 2.0.19 - should be fixed. Thanks for letting me know!

**Comment by Pavuucek** [comment]
Thank you very much, that was a veeery annoying bug. You sir, deserve a coffee. Or 5 :-)
