### ISSUE TITLE
Since beta 2.0.17 my TV show episodes show a screen grab thumbnail rather than a banner or poster

### ISSUE THREAD

**Issue by CraftyClown** [croneter/PlexKodiConnect#453]
Hello mate, 

as the title reads; since beta 2.0.17 my TV show episodes show a screen grab thumbnail rather than a banner or poster.

rolling back to 2.0.16 fixes the issue.

I've attached a screengrab

I'm on Kodi 17.6 using addon mode

Cheers

![screenshot 85](https://user-images.githubusercontent.com/19290757/38782955-85bdaf80-40f3-11e8-9d4f-626654a20eb6.png)

**Comment by croneter** [comment]
What skin is this?

**Comment by CraftyClown** [comment]
It's Titan
