### ISSUE TITLE
Error message when opening IPTV catagories

### ISSUE THREAD

**Issue by AllviewTV** [croneter/PlexKodiConnect#454]
I have PKC installed but when I go to channels - IPTV it all opens but as soon as I click a catagory it comes up with an error messsge. Any ideas whats wrong?

**Comment by AllviewTV** [comment]
IndexError: list index out of range
                                            -->End of Python script error report<--
21:26:46.170 T:521866867952   ERROR: GetDirectory - Error getting plugin://plugin.video.plexkodiconnect/?id=None&key=%2fvideo%2fMultiPLEX%2flistitems%2fSPORTS&mode=browseplex
21:26:46.171 T:521866867952   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.plexkodiconnect/?id=None&key=%2fvideo%2fMultiPLEX%2flistitems%2fSPORTS&mode=browseplex) failed
21:26:57.192 T:522507667912 WARNING: CPeripheralBusAndroid: failed to update input device with ID 4 because it couldn't be found
21:26:57.193 T:522507667912 WARNING: CPeripheralBusAndroid: failed to update input device with ID 5 because it couldn't be found
21:26:58.724 T:521866867952  NOTICE: Storing total System Uptime
21:26:58.725 T:521866867952  NOTICE: Saving settings

**Comment by croneter** [comment]
Seems like you were unauthorized for the Plex Media Server at the time: 
````
WARNING: PLEX.downloadutils: HTTP error 401 from PMS https://<IP>.plex.direct:11478/channels/all
NOTICE: PLEX.downloadutils: <html><head><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>
ERROR: PLEX.entrypoint: Could not download Plex Channels
```
* Can you try to reconnect correctly?
* Are you able to navigate your channels using another Plex client, e.g. Plex for Android?

**Comment by croneter** [comment]
By the way, I do NOT see the error in your second post in the log! Could you please try to reproduce that one and share the entire log here if you find the time?

**Comment by AllviewTV** [comment]
I uninstalled the latest beta version and installed the latest stable version on my device thats why you wont see it in the second log. I keep getting 'play error' why trying to watch anything. That should be present in the second log

**Comment by AllviewTV** [comment]
I will do it when I get home for you. It was the beta I was having I was having the original issue with

**Comment by AllviewTV** [comment]
These are the new logs. They are for kodi 18 I've tried 17.6 and its the exact same error when tryong to open IPTV catagories. The plugin opens comes up will all my catagories like Entertainment, sports etc but as soon as I click one it comes up with the error

https://pastebin.com/ZKJZwZiu
