### ISSUE TITLE
Not aligned information on iOS Plex APP during audio playback

### ISSUE THREAD

**Issue by tomzini** [croneter/PlexKodiConnect#456]
Scenarios:
- last available iOS Plex APP 
- PKC v2.0.19
- KODI 17.5

Tests:
1) if starts playing video (or TV series) from Kodi, the feedback on Plex APP is ok (cover ok, title ok, time ok)
2) if starts playing audio track often the feedback on the Plex is not synced (no cover, no title and no time)
3) if starts playing audio from Plex APP, on Kodi side the media is correctly played but also in this case the feedback is incomplete (no cover, no title and no time)

**Comment by croneter** [comment]
PKC does not have anything to do with the iOS Plex app. What do you mean with point 3?

**Comment by tano46** [comment]
Hi, Croneter
sorry, probably we was not clear in our previous description.

The main issue we was describing is that when we play an audio content from PKC, on the original Plex app you have no feedback: no timeline, no cover, no title.

We tried also new version 2.0.21, all is ok for videos and TV shows but no info from audio play.

Do you need for other logs?

Let me know, thanks
