### ISSUE TITLE
Trailer quality

### ISSUE THREAD

**Issue by maforshaw** [croneter/PlexKodiConnect#46]
I'm using direct paths with the Titan skin and if I select Info for a movie and then the Trailer button the video quality is not good.

I've looked at the Kodi database and the trailer has a value that looks like this:

`plugin://plugin.video.plexkodiconnect/trailer/?id=/library/metadata/5974&mode=play`

If I look at metadata item 5974 in Plex, it has 3 video parts with resolutions 1080, 720, 480. Which one does PlexKodiConnect choose and is there a way to tell it to always pick the 1080 part?

**Comment by maforshaw** [comment]
My mistake - I didn't realise it transcoded trailers (or perhaps Plex uses the setting to pick the best stream). I changed PlexKodiConnect's transcode settings to 12Mbps and it now plays with good quality.

**Comment by croneter** [comment]
Thanks for this - I did not know that transcoding was enabled in the defaul/standard settings :-)

**Comment by maforshaw** [comment]
Yes, the PlexKodiConnect default was on the lowest setting which caused Plex to transcode it. When I upped it to 12 (or 20) Mbps and checked the Plex logs, it didn't transcode it, just streamed it. Perhaps it would be useful to add an "Original" option to the selection list like the Plex Web Player options do.
