### ISSUE TITLE
Failed Consecutive Playback

### ISSUE THREAD

**Issue by siputturbo** [croneter/PlexKodiConnect#463]
hi,

i managed to installed PKC and successfully play a media content there. However upon pausing the media and return to resume, the playback failed and straight jump to main kodi menu. tried the same media and different media few times to no available.

i try to install it on my mac, aftv and android box all having the same issue. first time is success then consecutive playback will failed.

worth noted that i'm one of the shared user (non-master), if that related to the issue im facing.

my kodi log is here https://pastebin.com/zwGJyt0F

kindly advise.

**Comment by croneter** [comment]
Please try the newest beta version and report back

**Comment by siputturbo** [comment]
hi, after numerous troubleshooting i can confirm that the issue was caused by gdrive quota limitation, using plexcloud. changed the cloud provider to another and issue solved!

thanks for the feedback!

**Comment by croneter** [comment]
Cool, thanks for reporting back
