### ISSUE TITLE
Episode title numbering off

### ISSUE THREAD

**Issue by jamos316** [croneter/PlexKodiConnect#464]
this is my situation:
on my laptop i have my plex media server and also kodi, i have installed pkc and all sycns well.
i install it on my android box (same version of kodi, and same network), when i try to setup pkc it shows error; 'could not find any plex server in the network. aborting...'.
on the same android box i have installed the plex apk and this works fine.

im guessing the reply ill get is to upload log but i cant find how do do this.

thanks

**Comment by croneter** [comment]
Yes, log is needed. See here https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Obviously, do enable kodi debug logging and then try to search for Plex media servers in your network...

**Comment by jamos316** [comment]
sorry i done a bit of experimenting in router settings and the issue was blocking tcp connections.

i now have a minor issue about episode titles.
i have pkc tv shows as a shortcut link on my kodi home. when i go into it a click into a season the episodes are named 1.2.3.4....and so on. now if i go into information for 1 (for example) it shows as episode 3.
whats weird is if i go into tv shows via video addons > pkc > tv shows > tv shows the episodes titles show up as they should. episode 1. episode 2 ...and so on.

is there an issue here that you know of?

**Comment by croneter** [comment]
Aha...

Never heard of that. What skin are you using? Please make some Screenshots.

**Comment by jamos316** [comment]
sorted issue, sorry to bother you

**Comment by croneter** [comment]
OK, no problem, thanks for reporting back :wink:
