### ISSUE TITLE
Playing an Extra crashes Kodi

### ISSUE THREAD

**Issue by dazedcrazy** [croneter/PlexKodiConnect#466]
PKC Version 2.0.23
Kodi is latest nightly
I don't use Extras but I seen the update and thought I'd try it out, it just crashes Kodi on Leia when I try.
**Leia logs**
Debug: [kodi.log](https://github.com/croneter/PlexKodiConnect/files/2001679/kodi.log)
[kodi_stacktrace-18.0-ALPHA2 Git_20180513-9815b13305-20180514-171538.txt](https://github.com/croneter/PlexKodiConnect/files/2001671/kodi_stacktrace-18.0-ALPHA2.Git_20180513-9815b13305-20180514-171538.txt)
[kodi_crashlog-18.0-ALPHA2 Git_20180513-9815b13305-20180514-171538.dmp.txt (just remove the .txt)](https://github.com/croneter/PlexKodiConnect/files/2001681/kodi_crashlog-18.0-ALPHA2.Git_20180513-9815b13305-20180514-171538.dmp.txt)
Krypton doesn't crash just looks like it's going to play it but never does
**Krypton log:** [kodi.log](https://github.com/croneter/PlexKodiConnect/files/2001749/kodi.log)

**Comment by croneter** [comment]
A word of advice: Kodi latest nightly is NOT a good idea - stick to the "official" Alpha releases if you're using PKC. I tried to use the nightly versions but there is just too much breaking...

https://kodi.tv/download

![image](https://user-images.githubusercontent.com/4637940/40015507-e0732dd4-57b3-11e8-815d-db5af361dfe7.png)

**Comment by croneter** [comment]
Having a look now though, nevertheless 😉

**Comment by croneter** [comment]
You have `Play next video automatically` enabled in the Kodi player settings. This is generally a bad idea if using PKC, unfortunately. PKC should have warned you at some point...

![image](https://user-images.githubusercontent.com/4637940/40016148-a8792850-57b5-11e8-8bba-414489198962.png)

**Comment by croneter** [comment]
This leads to the issue: PKC tries to initiate this same playlist (a playlist of all extras) on the PMS side. This is currently not possible for trailers and the like and leads to an error

**Comment by dazedcrazy** [comment]
I don't use Leia as a daily player just for testing every few updates to see what's changed or netflix while at my desktop. `Play next video automatically` is this the reason for it not playing on both Krypton and Leia?

**Comment by dazedcrazy** [comment]
Just to let you know this still happens in Alpha2 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2132962/kodi.log)
Also the "Play next video automatically" has been changed from a one button does all to
![kiimxi3](https://user-images.githubusercontent.com/9027988/41849044-85d7cf6c-7877-11e8-8edf-dc569aad6997.png)

**Comment by croneter** [comment]
Implemented in PKC 2.5.9
