### ISSUE TITLE
Image Caching Disk Space Usage

### ISSUE THREAD

**Issue by kantlivelong** [croneter/PlexKodiConnect#468]
Hello,

Every few months I run out of disk due to image caching. Recently I ran [texturecache.py](https://github.com/MilhouseVH/texturecache.py) with the **p** and **r** arguments and it tells me that many cached files have been orphaned. Even after clearing the cache and running the script an hour later a few files are orphaned. Is it possible that the URL changes over time which results in files being re-cached whilst orphaning the original?

**Comment by croneter** [comment]
URLs to artwork should not really change. 

Try to use the latest PKC beta (next version being published in about an hour or so 😉 ). This will reset the Kodi DB entirely and also remove all cached artwork (version demands a DB reset). If you've been using PKC stable till now, it's possible that some orphaned artwork accumulated over time. Beta should take better care of that.

**Comment by kantlivelong** [comment]
Thanks! I'll keep an eye out for the beta release and continue running texturecache.py to monitor usage. Hoping it's just a bug that's been corrected.

**Comment by croneter** [comment]
Me too 😉 . Thanks for letting me know how it goes!
