### ISSUE TITLE
Beta version update issue

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#469]
Sorry folks, beta is beta, I botched a much more complicated update process than usual to beta version 2.0.24.

If you're affected and pkc does not seem to connect, go to the Kodi plug-ins section, then Video Add-ons, then plexkodiconnect. Open the pkc settings and manually initiate a Kodi database reset in the Advanced section.

**Comment by croneter** [comment]
I thought that was fixed, too! 
* Could you please share your debug log of having these 2 pms to choose from?
* did you have to manually reset the Kodi DB on pkc update?

**Comment by dazedcrazy** [comment]
It's not doing it now after resetting the db to get a debug log for you but if I go into the settings and click `Choose Plex Server from list` it still gives me the double server but now either one signs in ok.  [kodi.log](https://github.com/croneter/PlexKodiConnect/files/2003674/kodi.log)
