### ISSUE TITLE
Artwork not downloading on SPMC

### ISSUE THREAD

**Issue by cculpepp** [croneter/PlexKodiConnect#47]
Just installed v.1.2.0 on SPMC on Shield TV.  Artwork such as clear logos, disc art, etc, is not downloading.  Artwork supplied by PMS is fine, just the artwork supplied by PKC is absent.  All was working fine with the previous version of PKC.

**Comment by croneter** [comment]
Nothing changed there. Try this: go to PKC settings, Sync options, **disable** `Download additional art from FanArtTV`, exit the PKC settings. Then toggle the same setting on again. Then do a complete reset with PKC settings, Advanced, `Partial or full reset of Database and PKC`, then 2x Yes and 1x No. 

If it still did not download, please **immediately** grab the Kodi logs and post them (because you will have captured the sync process). See https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
I guess this is solved. Please come back to this issue if you are still having troubles

**Comment by cculpepp** [comment]
Hi!  Sorry...didn't get a chance to work with it until just now because of the long weekend.  I followed your instructions and could not get the issue solved.  I went as far as uninstalling SPMC completely and doing a fresh install....still no Fanart.tv art is downloading.  The next problem is that the log uploader doesn't want to work with SPMC....keeps returning an error message when trying to upload the logs.

I then tried to reproduce the bug on my Win7 machine...did a fresh install of Kodi and PKC and everything worked fine....all artwork is downloading.  BTW, I used Titan skin on both SPMC and Kodi.  I'm thinking the bug has to be with SPMC or Android (Shield TV) since everything worked fine on Kodi Win7.  Sorry I can't upload logs.  Maybe someone else running SPMC on Shield TV can reproduce the same issue.

**Comment by croneter** [comment]
Unfortunately, I cannot help you at all without kodi / spmc logs. 

Try getting them without the plugin by manually grabing the kodi/spmc log file; try this: http://kodi.wiki/view/Log_file/Advanced

**Comment by cculpepp** [comment]
Will do.  It will be tomorrow before I can get to this.  Thanks.

**Comment by cculpepp** [comment]
Ok...here are the logs.  Hope this helps.

http://pastebin.com/PQ1RZnAK

**Comment by croneter** [comment]
Well, **some few** movies (or their IMDB ids) were not found on fanart.tv - that is normal. I do see the majority of additional fanart appearing to download correctly, e.g. for "The Good Dinosaur". 

Is no additional artwork at all being downloaded? Or are just some pieces missing? It's easiest to check if you go into your movies and choose a view showing banners - Plex does not have banner art.

**Comment by cculpepp** [comment]
I'm not getting any of the artwork from Fanart for any of my tv shows or movies.  No banners, logos, disc art...nothing, nada, zip.

**Comment by croneter** [comment]
Your log is saying that Kodi (and **not** PKC) downloaded art from fanart.tv mostly successfully. 

@im85288 do you experience the same issues? What is your log saying?

**Comment by im85288** [comment]
I need to look in detail, I annoy using SPMC and in fact the machine where it lost the artwork I had not touched at all. The only change was the update in PKC version..which eventually made the artwork go away. Once I find more time I'll check the logs.

**Comment by cculpepp** [comment]
That's odd.  I don't even have artwork downloader installed, so I don't know why it says Kodi is downloading from fanart.tv.

**Comment by croneter** [comment]
Well, that is PKC :-P.

**Comment by cculpepp** [comment]
I've been out of town and haven't even turned on Kodi in the last ten days or so.  Looks like you have had several updates to PKC since then, and whatever you did seems to have fixed the artwork problem.  Everything appears to be downloading and displaying normally.  I''l have to buy you another coffee.  Thanks!

**Comment by croneter** [comment]
Good to hear :-)
