### ISSUE TITLE
not yet authorized for plex server

### ISSUE THREAD

**Issue by metzger2309** [croneter/PlexKodiConnect#472]
Hey !

since 2.0.24 I am not able to sign in to the server. I installed Kodi 18 alpha complete new. no chance...

![grafik](https://user-images.githubusercontent.com/39235719/40079005-a66303c0-5886-11e8-8130-379c152e12eb.png)

I signed in on plex.tv, entered the pin... restarted the server, deleted all devices... no chance.
always the same message.

Am I doing something wrong?

Peter

**Comment by Lou-Cipher** [comment]
I can verify this, latest 2.0.25 has the same issue.  If I downgrade (I went back to 2.0.22 for testing), I'm able to reset the plugin and authenticate.  I remain authenticated if I update to 2.0.25, but if I reset and attempt to reauthenticate while already on 2.0.25, I get the failure.  Entering the pin on plex.tx/pin (which, side note, redirects to plex.tv/link, probably should update the link in the plugin), and it accepts it and registers with the server.  On my PMS, I see the newly registered device.

**Comment by croneter** [comment]
@metzger2309 @Lou-Cipher Please share your DEBUG log files, otherwise I cannot help you

**Comment by croneter** [comment]
Jupp, unfortunately I cannot replicate your issue

**Comment by metzger2309** [comment]
Thank you croneter for help, I will try to share these files this evening :)

**Comment by Lou-Cipher** [comment]
Two things.  One, regarding log files, as with my other open issue, I can't upload my logs to github, it fails parsing them and says it can't upload, try again.  And, due to the massive amounts of logs about ssl errors from my other issues, my logs are several MB, and can't fit on pastebin.  Any preference as to where I upload them?

Two, regarding this issue, it appears to only happen when connecting to my own server.  If I connect to one of my friends' servers, no problem.  All their servers are remote, mine is local.

**Comment by croneter** [comment]
Same thing - reboot Kodi, reproduce the issue, share the log :wink: . 

My PMS here is local, too, and I cannot reproduce the issue

**Comment by Lou-Cipher** [comment]
OK, you'll love this.  I reproduced the issue like 5 times while I was troubleshooting.  I just followed my own exact steps again, so I could get you a fresh log.  This time, naturally, I'm unable to reproduce the issue.  On 2.0.25, with PKC settings and DB freshly reset, this time I was able to connect to my own server without issue.  So, unfortunately, I don't have any logs, and can no longer reproduce.  Swear it was real, though.

**Comment by Lou-Cipher** [comment]
Oh, I forgot, I did do one thing I forgot to mention, that may have been relevant.  @metzger2309 what router are you running?  I had to update my pfsense router's dns config as per: https://support.plex.tv/articles/206225077-how-to-use-secure-server-connections/

That may be your issue, too.  Totally spaced that I made that change.

**Comment by metzger2309** [comment]
cracy... now it works.
@Lou-Cipher - i have a FritzBox Router. This has a DNS-Rebinding tool. I made this exclusion:
![grafik](https://user-images.githubusercontent.com/39235719/40197471-d2a1f1ba-5a13-11e8-8084-c0f85d6aa358.png)
now it is working perfect.

freaky which details you have to consider...

@croneter - thank you for great work!

Cheers!

**Comment by croneter** [comment]
Thanks @Lou-Cipher , added to https://github.com/croneter/PlexKodiConnect/wiki/FAQ

**Comment by croneter** [comment]
Literally EVERY other Plex client should have issues though with a network setup like that, even if it's just not having the "green secure connections lock" when choosing a PMS to connect to...
