### ISSUE TITLE
Emby branding

### ISSUE THREAD

**Issue by dazedcrazy** [croneter/PlexKodiConnect#474]
I use the Embuary skin for Kodi but PKC is still using Emby images. If you have a look [here](https://forum.kodi.tv/showthread.php?tid=320137&pid=2734890#pid2734890) the skin dev said below that the file naming and logo need changing. I done a quick image that could be used to replace the Emby one if you want.
![plex](https://user-images.githubusercontent.com/9027988/40124249-0bd433f2-5920-11e8-85db-0d750ac8c0c0.png)

**Comment by croneter** [comment]
Nice! I'm lazy - could you make a github pull request?

**Comment by dazedcrazy** [comment]
https://github.com/croneter/PlexKodiConnect/pull/475 man i tired to do that PR about 5 times and kept messing it up lol
