### ISSUE TITLE
plugin.video.plexkodiconnect/resources/settings.xml loaded about 83 times every 2-3 seconds

### ISSUE THREAD

**Issue by viulian** [croneter/PlexKodiConnect#477]
Hello,

I'm running the latest 2.0.25 plugin on LibreELEC / Raspberry Pi 3b+ and I'm trying to debug high load even when things are idling.

Attaching to the thread that occupies the most CPU, strace reports about 83 lines (about 2-3 seconds) that look like:

`open("/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/settings.xml", O_RDONLY|O_LARGEFILE) = 68`
`open("/storage/.kodi/userdata/addon_data/plugin.video.plexkodiconnect/settings.xml", O_RDONLY|O_LARGEFILE) = 68`
`open("/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/settings.xml", O_RDONLY|O_LARGEFILE) = 68`
`open("/storage/.kodi/userdata/addon_data/plugin.video.plexkodiconnect/settings.xml", O_RDONLY|O_LARGEFILE) = 68`

After a reboot, it looks like the Music library is being refreshed, few popups that sync had to skip some items appear. After dismissing them, one thread starts reading the plexkodiconnect settings.xml very often, driving the CPU load high. There are no kodi.logs as this is happening ...

I understand from the popup that Kodi may be unstable, BUT why is kodi interested only in the settings.xml of plexkodiconnect and not on the other plugins :) ?

PS: CPU load (longterm) is about 0.80, and CPU usage hovers around 50% ...

Thank you,

**Comment by croneter** [comment]
Please share your entire debug log as explained in the wiki here on Github - this will allow me to understand the context

**Comment by viulian** [comment]
The log file is huge, 12Mb and increasing ... so I started digging.

For now, there is a problem with this file as it is constantly written to:

`/storage/.kodi/userdata/addon_data/plugin.video.plexkodiconnect/settings.xml`

The value updated very often is:

`    <setting id="caching_artwork_count" value="XXXXX" />`

Which means onSettingsChanged(self) will constantly get called by Kodi, loading the system even more.

I guess I have to tolerate a very high load until everything finishes - thank you for the hint with the debug, there it was obvious the line:

`19:25:46.050 T:1759507360   DEBUG: PLEX.kodimonitor: PKC settings change detected`

It feels like a bug, but I don't see an immediate solution to it - except moving this status counter in a separate status file - instead of a setting (which would imply the user could change it, but he can't, is just a status).
