### ISSUE TITLE
IPTV: Play error

### ISSUE THREAD

**Issue by AllviewTV** [croneter/PlexKodiConnect#479]
I raised an issue a while ago with 'play error' when trying to watch IPTV through PKC. I seem to still be getting the same error

**Comment by croneter** [comment]
As I cannot read minds, I still need your DEBUG log files as explained here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
@AllviewTV 
Still need your log file...

**Comment by croneter** [comment]
Closing as the debug log file is still missing. @AllviewTV please reopen if you decide to share your log

**Comment by Vansmak** [comment]
Since I have a question about this topic hopefully it's a good place to ask. To use pex connect and an iptv service is it better to add the iptv on plex server or the kodi simple client?
