### ISSUE TITLE
Plex Companion not available on iOS devices

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#48]
Just noticing that I don't see PKC companion on any of my iOS devices. It is available within the web interface though.

**Comment by croneter** [comment]
Works here, no problem. All OS should work similarly... Have tried the usual, restarting iOS, kodi, PMS...?

**Comment by hstamas** [comment]
Working now after a Kodi restart. I believe this is connected to issue #41 as last night I again noticed that PMS did not know that I was playing a video AND compion was not available on my phone. Restarting Kodi fixed that problem and now the companion is available on my iPhone.
