### ISSUE TITLE
Specific Items won’t sync

### ISSUE THREAD

**Issue by ziggy73701** [croneter/PlexKodiConnect#480]
Not sure where to start looking for logs on this, I have PlexConnect in latest beta. Had to rebuild Kodi and since the PlexConnect wont sync certain items. I use DirectPaths everything is visible and I can play the file direct but it won’t sync.
10 things I hate about you refuses 
Airwolf entire series refuses
The random episodes.
All of which can be played directly if I browse to the file
Any ideas?

**Comment by croneter** [comment]
Yes, share your log files: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by ziggy73701** [comment]
My bad, somehow.. and for no reason I understand.. the kids had been using SPMC. Gone back to latest Kodi and all good!!
