### ISSUE TITLE
17.6 Krypton with v2.1.1 database sync keeps crashing

### ISSUE THREAD

**Issue by mbze430** [croneter/PlexKodiConnect#487]
ever since PKC upgraded to 2.1.1 my KODI 17.6 keeps crashing when trying to sync with "DETECTED KODI DATABASE NEEDS TO BE RECREATED FOR THIS VERSION. THIS MIGHT TAKE A WHILE. PROCEED?"

**Comment by croneter** [comment]
As usual, I cannot just do some magic and thus need your DEBUG log file https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Any news here?

**Comment by croneter** [comment]
Still need a log file...

**Comment by croneter** [comment]
Closing, because I cannot help without a log file
