### ISSUE TITLE
Continous "library sync thread has crashed" message

### ISSUE THREAD

**Issue by theprob** [croneter/PlexKodiConnect#490]
Hello,

I repeatedly getting the "library sync thread has crashed" message. I restarted many times LE as requested but don't seems to be solving. I tried to clear the library, reset PKC, reinstall, etc.

Here is my log file: http://paste.kodi.tv/afedegowal.sql

Thanks in advance!

**Comment by Pavuucek** [comment]
`14:36:41.991 T:4006601632   ERROR: SQL: [MyVideos107.db] The database disk image is malformed
...
14:36:41.991 T:4006601632   ERROR: Connect failed with 'SQL: [MyVideos107.db] The database disk image is malformed
...
14:36:42.006 T:4006601632   ERROR: SQL: [MyVideos107.db] The database disk image is malformed
...
14:36:42.006 T:4006601632   ERROR: Connect failed with 'SQL: [MyVideos107.db] The database disk image is malformed
...
`
Please check your sd card. It looks like it's corrupted and might need replacing.

**Comment by theprob** [comment]
Yes, there was other signs of a possible card corruption...

However, after I issues the following commands, the mentioned message is disappeared.:
```
cd ~/.kodi/userdata/Database
sqlite3 AddonsXX.db #replace XX with the actually existing file; can also be several files
sqlite> .mode insert
sqlite> .output dump.sql
sqlite> .dump
sqlite> .exit
 
# edit dump.sql
echo -n '' > AddonsXX.db #replace XX like above
sqlite3 AddonsXX.db #same here
sqlite> .read dump.sql
sqlite> .exit
rm dump.sql
```
Unfortunatelly now I only the see the TV Shows, the movies not. I tried to resync library or reset PKC, but didn't helped... :S

**Comment by croneter** [comment]
Delete all the Kodi databases in the user directory to start from scratch

Also, either reformatting the SD card or even getting a new one might be a very good idea

**Comment by croneter** [comment]
Closing as this has nothing to do with PKC but the way you're treating both the SD card and your databases :wink:
