### ISSUE TITLE
2.1.x Breaks CinemaVision Addon

### ISSUE THREAD

**Issue by leejk421** [croneter/PlexKodiConnect#492]
Hello,

Before the last stable update PKC worked together with the Cinemavision addon with no issues. Now, when playing the CV sequence, at the point in the sequence where movie trailers start to play, KODI locks up. I'm guessing that when the CV addon tells KODI which trailer video to play, somehow PKC is intercepting and causing a conflict. Attached is the debug log.
[kodi.log.zip](https://github.com/croneter/PlexKodiConnect/files/2096328/kodi.log.zip)

**Comment by croneter** [comment]
Looks to me like you need to somehow completely reset the CinemaVision add-on. It uses old calls like
```
NOTICE: [- CinemaVision -]: Experience: Playing next item: VIDEO: u'plugin://plugin.video.plexkodiconnect/trailer/?id=/library/metadata/147377&mode=play'
```
The paths have changed and should read something like this:
```
plugin://plugin.video.plexkodiconnect.movies/?plex_id=147377&plex_type=clip&mode=play
```

**Comment by croneter** [comment]
Thanks for reporting back whether it worked and what you did exactly 😉

**Comment by leejk421** [comment]
OK, deleted the CV folder and tried again a couple of times. The difference this time was that KODI did not crash or lockup, but exited out of the CV sequence when it started to play a trailer from the KODI database. Trailers that are not in the KODI DB still work fine.

[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/2107711/kodi.zip)

**Comment by croneter** [comment]
Tough one. Could you please try the newest PKC beta version, that might help. If not, please make sure that debug logging is enabled, restart Kodi and capture  the issue again. 

Since this add-on is very complex, you might also want to post on their forums to get help... (Revering back to this issue's URL here)

**Comment by croneter** [comment]
Any news?

**Comment by leejk421** [comment]
Sorry, been away from home for the last couple of weeks. Hope to try the beta build tomorrow.

**Comment by leejk421** [comment]
Ok I did not try the beta yet because I did some testing and thought this might be significant. CinemaVision is not the problem at all. If I try and play a trailer directly inside KODI, the same behavior happens. I opened up the KODI db file and looked at the movies table, and the path to trailers reads like this: plugin://plugin.video.plexkodiconnect.movies/?plex_id=153369&plex_type=clip&mode=play

KODI apparently does not like that path. Also I noticed something else. In the PMS settings for the Plex Movie agent, the option to download trailers and extras is on. Always has been. In Plex Web, it will display 2 trailers beside the movie, my local one and the one it'll stream from the internet. Could this be now causing a conflict?

Here is another log file too in case something new stands out.
[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/2152244/kodi.zip)

**Comment by croneter** [comment]
You need to be way more specific. What exactly happens if you play a trailer from directly inside Kodi?

The path you saw in the Kodi DB is exactly like its supposed to be. Works perfectly fine for anyone else as far as I can tell. PKC will pick one of the 2 trailers you have, as Kodi only supports one (but you could use the Plex context menu, then extras, to see all trailers). 

What did you do, how did Kodi react when you captured the log file?

**Comment by leejk421** [comment]
OK, so when I tried to play a trailer directly inside KODI from the movie info screen, it starts the play process. The screen goes black and a buffering please wait message is displayed. After about 2 minutes I assume it's not going to play and try to abort the playback by pressing the escape key. After a few seconds a playback failed message appears, and says to check the log. KODI is then again responsive. Note that I do not have the play Plex trailers option turned on in PKC because I use the CV addon to control trailer playback, and I have my own locally stored trailers. This all worked fine before.

This one is not a debug log but does show the path it tried to play. If there are some specific debugging steps you need me to perform, let me know please.

thx

[log.zip](https://github.com/croneter/PlexKodiConnect/files/2152931/log.zip)

**Comment by croneter** [comment]
Ouh nice catch there! Fix on the way. Many thanks!!

**Comment by leejk421** [comment]
Great! Which release should I test for?

**Comment by croneter** [comment]
Try the latest beta
