### ISSUE TITLE
"Library sync thread has crashed..." on PKC 2.2.0 

### ISSUE THREAD

**Issue by tano46** [croneter/PlexKodiConnect#493]
Hi, 
I had sync library issue on PKC 2.2.0. All is ok with stable versione 2.1.0.

Log attached
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2102127/kodi.log)

Regards

**Comment by croneter** [comment]
Should be fixed with beta version https://github.com/croneter/PlexKodiConnect/tree/2.2.1
