### ISSUE TITLE
syncing Plex playlists to Kodi

### ISSUE THREAD

**Issue by levander051** [croneter/PlexKodiConnect#494]
Hi, how syncing Plex playlists to Kodi and vice-versa actually works? How to sync the playlists?

**Comment by croneter** [comment]
Make sure that you have the latest beta 2.2.1 first 😉 . There is nothing you need to do - your Plex video playlists should show up in Kodi e.g. under Videos - Playlists. If you happened to have Kodi playlists (with Plex items, mind!), they should immediately be visible in Plex. 

Make sure you're using the same Plex home user though, as different Plex users have different playlists
