### ISSUE TITLE
Direct Paths: Kodi won't play anything from the OnDeck

### ISSUE THREAD

**Issue by charlie2alpha** [croneter/PlexKodiConnect#495]
In reference to https://forums.plex.tv/discussion/comment/1685207/#Comment_1685207 I have opened this issue. In short, I cannot play anything from the OnDeck nodes after upgrading from 1.x to 2.x stable branch.

Attaching a Kodi debug log, made several attempts to play items.

(Log deleted by Croneter)

**Comment by croneter** [comment]
I'm sorry to tell you that you posted your Plex tokens! Please follow [I published my Plex token to some forum or Github. Anyone can now access my Plex Server!](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server) immediately.

**Comment by croneter** [comment]
Apart from that - thanks for the log! 😉

**Comment by charlie2alpha** [comment]
Damn, I thought I had them removed. Ah crap, I know what happened, forgot to click save on Notepad++!!! I am an idiot!

**Comment by croneter** [comment]
I'm confused, thought you're using direct paths, not add-on paths! But add-on paths are enabled:
````
NOTICE: PLEX.service: PKC Direct Paths: False
```
Try the following:
1) Enter the PKC settings. Activate direct paths in the settings:
![2018-06-15_161632](https://user-images.githubusercontent.com/4637940/41472743-a53e1bee-70b7-11e8-967a-69799a030093.png)
2) Don't leave the settings, but reset the Kodi database:
![2018-06-15_162027](https://user-images.githubusercontent.com/4637940/41472957-30a5ff4e-70b8-11e8-8f3b-2f50f882eff7.png)
* First hit YES, then NO!
* Let Kodi restart and resync

**Comment by croneter** [comment]
If that were the case, I'd see that in the Logs. Please follow the steps above exactly - the resync is necessary as the database entry for both direct paths and add-on paths are very different. 

Playback probably does not work because PKC expects add-on paths but is served direct paths.

**Comment by charlie2alpha** [comment]
I did EXACTLY what you asked me, it just won't work! If I set it to Add-On mode and reset, it works. When I set it to Native and reset, OnDeck won't work. If I start playback anywhere EXCEPT OnDeck, it works fine too!

**Comment by croneter** [comment]
Please set paths to direct paths as explained. Reboot Kodi. Then try to play from the Widgets to capture that in the logs, then please start any video from the library, so I have that in the log as well. 

Mind the tokens before uploading the log 😉

**Comment by charlie2alpha** [comment]
Here it is: 2 attempts to play from a widget, and the final attempt from the normal library menu, which succeeds. 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2106431/kodi.log)

**Comment by croneter** [comment]
You settings for addon paths/direct paths don't stick. Again, you have add-on paths enabled. 

What happens if you enter the settings, choose DIRECT paths. Then OK to exit the settings. Go back in. Does it show add-on or direct paths in the settings?

**Comment by charlie2alpha** [comment]
It always says "Direct Paths" on the configuration menu. I do not know what happens internally, but visually it reports the right setting. But obviously something is messed up, otherwise I would not bother you here.

**Comment by croneter** [comment]
Maybe you're really, really fast in changing these settings upon a reboot (if the settings are changed internally by PKC, which happens 2-3 times on start-up, your changes will be lost). After the above, try rebooting Kodi. Then wait 5min. Then choose Direct Paths again and reset the library. Does it work then?

**Comment by croneter** [comment]
Let's pull the plug on the settings then: shut-down Kodi. In the [Kodi userdata folder](https://kodi.wiki/view/Userdata), in the subfolder `addon_data`, delete the entire folder called `plugin.video.plexkodiconnect`. Reboot Kodi and try again from scratch. 

This is Kodi's doing, I'm afraid, there's not much else I can do

**Comment by charlie2alpha** [comment]
That worked finally. Very annoying, at least I didn't have to reconfigure the widget nodes etc. Thank you for your time, something was stuck apparently.
