### ISSUE TITLE
Marking an item as watched or unwatched is not reflected in Kodi

### ISSUE THREAD

**Issue by d0ogie** [croneter/PlexKodiConnect#496]
From https://forums.plex.tv/discussion/210023/plexkodiconnect-let-kodi-talk-to-your-plex/p181 ..

Back on the stable branch 2.1.1 and Kodi 17.6 on Windows, I am hitting a small issue concerning watched state.

Mark as watched/unwatched WITHOUT partial progress works great, no issue there. However if an item is partially watched..

Repro:

* Partially watch a show or movie

    >11:27:19.831 T:828 NOTICE: Closing stream player 3
    >11:27:19.845 T:4796 NOTICE: VideoPlayer: finished waiting
    >11:27:19.937 T:4796 NOTICE: CVideoPlayer::CloseFile()
    >11:27:19.937 T:4796 NOTICE: VideoPlayer: waiting for threads to exit
    >11:27:19.937 T:4796 NOTICE: VideoPlayer: finished waiting
    >11:27:19.937 T:4796 NOTICE: CVideoPlayer::CloseFile()
    >11:27:19.937 T:4796 NOTICE: VideoPlayer: waiting for threads to exit
    >11:27:19.937 T:4796 NOTICE: VideoPlayer: finished waiting
    >11:27:20.069 T:3360 NOTICE: PLEX.librarysync: Session key 192 still unknown! Skip playstate update

* Kodi UI shows nn% watched, PMS matches this correctly, all good
* Attempt to mark as watched in same Kodi client, UI continues to show nn% watched, however PMS shows item watched correctly. Also, the Kodi context menu correctly flips between "Mark as Watched" and "Mark as Unwatched!"

    >11:29:09.225 T:224 NOTICE: PLEX.PlexFunctions: Toggled watched state for Plex item 208239

   

I can continue to mark watched/unwatched in Kodi as I please and PMS will honor my silly requests, but Kodi will continue to show partial watched state, until I either trigger a manual library sync, or wait out the regular sync interval. At that point the Kodi UI will match PMS.

Is Kodi caching this state? Admittedly I don't understand well enough how this works.
Trying to reproduce with Emby in place of PKC - it happens fast, but it appears that they do a mini refresh of the Kodi library of sorts, to potentially avoid this and refresh the local Kodi library. This is the only scenario (the partial watched scenario) that I can get this behavior to trigger under.

**Comment by croneter** [comment]
Just tested and had a look at the code. It works fine here, Kodi's watched status indication seems to be correct. 
* Try another skin; Arctic Zephyr worked fine for me
* Which "view" are you in when it does not work for you? E.g. Kodi's "home view" and you're looking at widgets? Or the library view (navigating to e.g. "movies")? Or does it not work in BOTH?

**Comment by d0ogie** [comment]
Thanks for investigating. Will chalk this up to a skin issue - Titan is, well, Titan.
