### ISSUE TITLE
Crashing Leia Alpha Windows X64

### ISSUE THREAD

**Issue by BinsonBuzz** [croneter/PlexKodiConnect#497]
Hi

I'm using this for the first time to see if I can simplify my setup.  I'm setting it up on a fresh Leia Alpha Windows X64 build i.e. before changing skins or addons, and it keeps crashing after a few mins.  Even when i think it's running, I come back to my PC and Kodi's gone.

Help please as I'd love to get this working

https://paste.ee/p/khUZR

Edit: updated paste

**Comment by croneter** [comment]
Nothing special regarding PlexKodiConnect in your log, sorry. Kodi 18 is still in ALPHA state (=not even a beta version) and thus inherently unstable. Your options:
* Use Kodi 17.6
* Try a newer Kodi 18 version and "hack" PKC as explained here: https://github.com/croneter/PlexKodiConnect/issues/486

Sorry, there's nothing more I can do
