### ISSUE TITLE
No Covers after Syncing

### ISSUE THREAD

**Issue by ultrax1887** [croneter/PlexKodiConnect#508]
hello, I have Kodi 18 alpha2 freshly installed. After syncing but no covers appear. My PKC version is 2.2.13.

**Comment by croneter** [comment]
Try STABLE Kodi 17.6. Working? You might've gotten a Kodi Alpha version that still has some flaws...

**Comment by ultrax1887** [comment]
225/5000
Yes, I know that it is an alpha. A Kodi 18er version of a few months ago ran perfectly. With 17.6 it runs wonderfully, but for that the HDR play does not run properly, therefore I wanted to change to 18er.

**Comment by croneter** [comment]
Then this is definitely not a PlexKodiConnect issue but a Kodi Alpha bug. Sorry...

**Comment by croneter** [comment]
Be patient, the Kodi team is working hard on making version 18 more stable

**Comment by ultrax1887** [comment]
in the pkc features but is the support for kodi 18 listed ... The HDR problem was due to wrong settings in Kodi (Mediacodec Surface).
Where is the error syncing now? I also noticed that the movie does not start at all.

**Comment by croneter** [comment]
Yes PKC supports Kodi 18 Alpha 2 (official download from Kodi.tv). BUT - there are still many bugs on the Kodi side of things that need to be sorted by the Kodi team

**Comment by ultrax1887** [comment]
Ok, if I understand correctly, does Kodi 18 not work with pkc 2.2.13 at the moment on Shield TV?

**Comment by croneter** [comment]
Cool that you could solve the issue.

Regarding Kodi 18: it means that PKC should work with the alpha version _in principle_, but there are still many bugs in the entire setup. Thus the developer won't invest much time in looking at issues with Kodi 18 - not until more stable versions are released
