### ISSUE TITLE
LibreELEC Kodi 17.6 crashes when opening a file that only has external subtitles using Direct Paths

### ISSUE THREAD

**Issue by crazygambit** [croneter/PlexKodiConnect#510]
Kodi immediately freezes when attempting to open external .srt subs in a file.

If the file also has embedded subs it won't crash and the external subs are selectable, but won't play. If I try to download a subtitle file, it downloads it to the correct folder on my NAS, correctly renames it and then crashes (see attached log)

Same PMS on the same network with the same files works perfectly on a Windows machine with 17.6 and PKC using Direct Paths as well. Those files and subtitles also work perfectly on other Plex players. So it might be a LibreELEC bug.  Also I had to enable SMBv1 as the minimum standard in the LibreELEC settings to be able to see the server over smb. I was using nfs before installing PKC.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2211520/kodi.log)

**Comment by croneter** [comment]
Nothing pointing to PlexKodiConnect. PKC only informs Kodi to use subtitles. Kodi will then handle everything else. In principle, PKC should not even be able to crash Kodi. 

Please take this up with the LibreElec team as it is not something I can fix. This bug might be related to the only error in the log I could find:
```
ERROR: GetDirectory - Error getting /storage/.kodi/media/Fonts/
ERROR: GetDirectory - Error getting special://home/media/Fonts/
```
I guess fonts are needed to display subtitles - not having fonts not being good 😉

**Comment by croneter** [comment]
There are other errors that point to missing fonts/folders and subtitles and a butched LibreElec installation: 
````
ERROR: GetDirectory - Error getting /storage/.kodi/userdata/addon_data/service.subtitles.subscene/temp/
```
and
```
ERROR: GetString: error reading /storage/.kodi/userdata/disp_cap
```
