### ISSUE TITLE
PKC - Server is unreachable

### ISSUE THREAD

**Issue by xefil** [croneter/PlexKodiConnect#511]
Hello,
I'm trying to use PlexKodiConnect (installed from BETA Repo as well on release, actually on version 2.2.15) on my Amazon Fire Stick (2.nd gen).
What happens is the following.:
When I install the plugin, on the first run it starts with the connection wizard. It asks for the Plex login (PIN) and then asks for disable Music library and some other questions.
Well, if I answer to all "NO", which involves NOT to restart Kodi, the scan starts and I can collect informations from my Plex Server. I can play movies correctly, all works PERFECT!
If I exit the app (kodi), or the first wizard asks me to restart KODI due some given answers on the startup, then I cannot connect to the PMS anymore.
A popup appears telling me it was not possible to connect to the PMS. Trying to play a movie or to browse the content via PKC wont work.
If I reset the settings of PKC, restart the wizard from the beginning, all starts over: I mean, if no KODI restart is required, I can see movies again.
Using a Amazon Fire Stick I have no idea how to send you log files.
Maybe it's a common issue and the solution is easy :-)
I'm using it on Kodi 17.6.
Any idea / help?
Thanks, Simon

**Comment by croneter** [comment]
Please share a DEBUG log: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by xefil** [comment]
Hello,
Actually I'm not able to collect the informations, I'm not at home.
Meanwhile yesterday I've found a workaround, maybe that can help you.
If I set up the Plex IP Address manually (so disable plex.tv login) AND set my home IP Address as trusted into my remote plex server, this works well and no issues at all.
Does it help a little bit?
Simon

**Comment by croneter** [comment]
Yes that does help - because it fixes your issue 😉 . Otherwise I would really need your DEBUG log to have a look at what's going on
