### ISSUE TITLE
Sync thread crashed due to having some Plex PHOTO playlists

### ISSUE THREAD

**Issue by coz2001** [croneter/PlexKodiConnect#517]
Got this error message after the new stable update to 2.3.0

Log: deleted

**Comment by croneter** [comment]
Workaround: delete the Plex playlists containing photos/images

**Comment by coz2001** [comment]
I deleted the photo album I had and haven't seen the error since.

I'm closing this issue now, thanks croneter for you support.

**Comment by croneter** [comment]
Reopening as this user manipulation should definitely NOT crash PKC 😉

**Comment by coz2001** [comment]
👌😉
