### ISSUE TITLE
Movies not appearing but all other media (TV shows, music) is

### ISSUE THREAD

**Issue by aagha** [croneter/PlexKodiConnect#518]
I've installed PKC on my Nvidia Shield TV (16GB) where I have a Plex Media Server (PMS) running alongside /w Kodi. I've successfully logged into Plex Pass.

All my media get scanned (I can see the 500+ movies being scanned), but when I go to Kodi's Movies menu, none of the movies are displaying.

In PKC I've also added the path to my NAS where the files are stored and accessed by PMS.

Why are TV shows and music appearing, but not Movies?

**Comment by croneter** [comment]
Did you restart Kodi?

Otherwise, debug logs of the entire sync process are in order: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Any news here? Otherwise I'll close this issue

**Comment by croneter** [comment]
Closing as without more info from @aagha , I cannot do anything
