### ISSUE TITLE
How can I see debug logs on an Nvidia Shield

### ISSUE THREAD

**Issue by aagha** [croneter/PlexKodiConnect#519]
I just instlled PKC, but want to debug any issues. Where can I go to see the (debug) logs?

**Comment by croneter** [comment]
https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Link above should give you a pointer. Google Kodi Nvidia shield log file.

Closing as this is definitely not a PlexKodiConnect issue
