### ISSUE TITLE
PKC sometimes just won't play titles

### ISSUE THREAD

**Issue by Rajaat** [croneter/PlexKodiConnect#520]
Hi there,

why does sometimes/regularly my raspberry pi (osmc/pkc) just won't play any titles?

the server runs on a synology nas 216play, web plex web client runs, just the three raspberry pi clients won't work as expected...

A reboot helps. I attached my kodi log, hoping someone can help me solving this issue?

This is my first forum post, so if you need further information i will gladly deliver.

Thank you!

**Comment by croneter** [comment]
Ouh thanks for that log! Error spotted, its a UnicodeDecodeError thingy.

**Comment by Rajaat** [comment]
Thank you for the incredible quick answer!
Is that a problem i can solve on my own with your advice?
What can i do?

P.S. awesome work!

**Comment by croneter** [comment]
Nope that's my bad. Will be fixed soon. Glad you like PKC

**Comment by croneter** [comment]
Could you please test the BETA PKC version 2.3.4? Quite a heavy change I had to do...

**Comment by Rajaat** [comment]
Sorry for the late answer,


how do i test 2.3.4.? in OSMC I only see 2.3.3. as latest version; how do i alter the update channel for pkc?


Plus, i altered all "ö ü ä" to "oe ue ae" in my database. The unicode error was gone.


________________________________
Von: croneter <notifications@github.com>
Gesendet: Sonntag, 5. August 2018 14:46:25
An: croneter/PlexKodiConnect
Cc: Rajaat; Author
Betreff: Re: [croneter/PlexKodiConnect] PKC sometimes just won't play titles (#520)


Could you please test the BETA PKC version 2.3.4? Quite a heavy change I had to do...

**Comment by croneter** [comment]
Install the beta pkc repository as well. You should not have removed the Umlaute, pkc supports them of course :see_no_evil:
