### ISSUE TITLE
multi part files not playing properly

### ISSUE THREAD

**Issue by JCYTang** [croneter/PlexKodiConnect#522]
I have some tv episodes that are multi part files. They are named correctly. ie in other plex clients they will play properly. But with plexkodiconnect only the first part file will play. Is there some setting I need to use so that these multi part files will play correctly?

**Comment by croneter** [comment]
Try using the Kodi context menu (e.g. hit "i"), then `Plex Options`, then `Start playback via PMS`. Does that help?

**Comment by JCYTang** [comment]
Thanks that did the trick.
