### ISSUE TITLE
Library sync thread crashes with UnicodeEncodeError

### ISSUE THREAD

**Issue by drt1** [croneter/PlexKodiConnect#523]
Hey folks,

Since I installed PKC a few days ago, every time I start kodi, I get the "Library sync thread crashed..." error message after 1-2 minutes.
I disabled addon completely, cleared library, did a PKC reset and clearance of kodi database - but it still happens every time.

After looking into the logfile, the error message is the following (I'm sorry, I don't know how to expand the quotation box, so that horizontal scrolling is possible):

>15:02:22.439 T:140175578240768  NOTICE: PLEX.librarysync: Initial start-up full sync starting
15:02:22.445 T:140175578240768  NOTICE: PLEX.videonodes: Clearing nodes properties.
15:02:22.445 T:140175578240768  NOTICE: PLEX.librarysync: Found viewid: 6 viewname: Dokus viewtype: movie tagid: 1
15:02:22.446 T:140175578240768  NOTICE: PLEX.utils: Writing playlist file to: /home/kodi/.kodi/userdata/playlists/video/Plex 6.xsp
15:02:22.446 T:140175578240768  NOTICE: PLEX.utils: Successfully added playlist: Dokus
15:02:22.449 T:140175578240768  NOTICE: PLEX.librarysync: Found viewid: 8 viewname: Filme viewtype: movie tagid: 2
15:02:22.449 T:140175578240768  NOTICE: PLEX.utils: Writing playlist file to: /home/kodi/.kodi/userdata/playlists/video/Plex 8.xsp
15:02:22.449 T:140175578240768  NOTICE: PLEX.utils: Successfully added playlist: Filme
15:02:22.452 T:140175578240768  NOTICE: PLEX.librarysync: Found viewid: 3 viewname: Musik viewtype: artist tagid: 3
15:02:22.486 T:140175578240768  NOTICE: PLEX.librarysync: Found viewid: 4 viewname: TV-Serien viewtype: show tagid: 4
15:02:22.486 T:140175578240768  NOTICE: PLEX.utils: Writing playlist file to: /home/kodi/.kodi/userdata/playlists/video/Plex 4.xsp
15:02:22.486 T:140175578240768  NOTICE: PLEX.utils: Successfully added playlist: TV-Serien
15:02:22.488 T:140175578240768  NOTICE: PLEX.librarysync: Found viewid: 10 viewname: XXX viewtype: movie tagid: 5
15:02:22.488 T:140175578240768  NOTICE: PLEX.utils: Writing playlist file to: /home/kodi/.kodi/userdata/playlists/video/Plex 10.xsp
15:02:22.488 T:140175578240768  NOTICE: PLEX.utils: Successfully added playlist: XXX
15:02:22.491 T:140175578240768  NOTICE: PLEX.librarysync: Finished processing views. Views saved: [{u'itemtype': u'movie', u'kodi_tagid': 1, u'id': u'6', u'sync_to_kodi': 1, u'name': u'Dokus'}, {u'itemtype': u'movie', u'kodi_tagid': 2, u'id': u'8', u'sync_to_kodi': 1, u'name': u'Filme'}, {u'itemtype': u'artist', u'kodi_tagid': 3, u'id': u'3', u'sync_to_kodi': 1, u'name': u'Musik'}, {u'itemtype': u'show', u'kodi_tagid': 4, u'id': u'4', u'sync_to_kodi': 1, u'name': u'TV-Serien'}, {u'itemtype': u'movie', u'kodi_tagid': 5, u'id': u'10', u'sync_to_kodi': 1, u'name': u'XXX'}]
15:02:22.491 T:140175578240768  NOTICE: PLEX.librarysync: Running fullsync for NEW PMS items with repair=False
15:02:22.491 T:140175578240768  NOTICE: PLEX.librarysync: Processing Plex Movies. Libraries: [{u'itemtype': u'movie', u'kodi_tagid': 1, u'id': u'6', u'sync_to_kodi': 1, u'name': u'Dokus'}, {u'itemtype': u'movie', u'kodi_tagid': 2, u'id': u'8', u'sync_to_kodi': 1, u'name': u'Filme'}, {u'itemtype': u'movie', u'kodi_tagid': 5, u'id': u'10', u'sync_to_kodi': 1, u'name': u'XXX'}]
15:02:25.154 T:140175578240768  NOTICE: PLEX.librarysync: Movies sync is finished.
15:02:25.155 T:140175578240768  NOTICE: PLEX.utils: It took 0:00:02.664477 to run the function plex_movies
15:02:25.156 T:140175578240768  NOTICE: PLEX.librarysync: Media folders for TVShows: [{u'itemtype': u'show', u'kodi_tagid': 4, u'id': u'4', u'sync_to_kodi': 1, u'name': u'TV-Serien'}]
15:02:40.356 T:140175578240768  NOTICE: PLEX.librarysync: TVShows sync is finished.
15:02:40.376 T:140175578240768  NOTICE: PLEX.utils: It took 0:00:15.220597 to run the function plex_tv_show
15:02:40.376 T:140175578240768  NOTICE: PLEX.librarysync: Running fullsync for CHANGED PMS items with repair=False
15:02:40.379 T:140175578240768  NOTICE: PLEX.librarysync: Processing Plex Movies. Libraries: [{u'itemtype': u'movie', u'kodi_tagid': 1, u'id': u'6', u'sync_to_kodi': 1, u'name': u'Dokus'}, {u'itemtype': u'movie', u'kodi_tagid': 2, u'id': u'8', u'sync_to_kodi': 1, u'name': u'Filme'}, {u'itemtype': u'movie', u'kodi_tagid': 5, u'id': u'10', u'sync_to_kodi': 1, u'name': u'XXX'}]
15:02:40.427 T:140176189814528  NOTICE: VideoInfoScanner: Starting scan ..
15:02:40.631 T:140176189814528  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
15:02:41.357 T:140175578240768  NOTICE: PLEX.librarysync: Movies sync is finished.
15:02:41.360 T:140175578240768  NOTICE: PLEX.utils: It took 0:00:00.983753 to run the function plex_movies
15:02:41.361 T:140175578240768  NOTICE: PLEX.librarysync: Media folders for TVShows: [{u'itemtype': u'show', u'kodi_tagid': 4, u'id': u'4', u'sync_to_kodi': 1, u'name': u'TV-Serien'}]
15:02:48.316 T:140175578240768  NOTICE: PLEX.librarysync: TVShows sync is finished.
15:02:48.327 T:140175578240768  NOTICE: PLEX.utils: It took 0:00:06.966724 to run the function plex_tv_show
15:02:48.327 T:140175578240768  NOTICE: PLEX.playlists: Starting playlist full sync
15:02:48.355 T:140177252116224  NOTICE: VideoInfoScanner: Starting scan ..
15:02:48.547 T:140177252116224  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
15:03:49.733 T:140175578240768   ERROR: PLEX.librarysync: LibrarySync thread crashed. Error message: 'latin-1' codec can't encode character u'\u2019' in position 75212: ordinal not in range(256)
15:03:49.869 T:140175578240768   ERROR: PLEX.librarysync: Traceback:
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1480, in run
                                                self._run_internal()
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 1554, in _run_internal
                                                elif self.full_sync():
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/utils.py", line 1073, in wrapper
                                                result = func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py", line 268, in full_sync
                                                if not playlists.full_sync():
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/__init__.py", line 121, in full_sync
                                                return _full_sync()
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/__init__.py", line 149, in _full_sync
                                                kodi_pl.create(api.plex_id())
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/kodi_pl.py", line 64, in create
                                                _write_playlist_to_file(playlist, xml_playlist)
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/playlists/kodi_pl.py", line 118, in _write_playlist_to_file
                                                text = text.encode(v.M3U_ENCODING, 'strict')
                                            UnicodeEncodeError: 'latin-1' codec can't encode character u'\u2019' in position 75212: ordinal not in range(256)

It seems that libraries are syncing fine, but when it comes to playlist syncing, the unicode character 2019 (right single quotation mark) is causing errors.
I think the supplied "normal" log file should do, if you still need the debug log I will paste it too, please let me know.

So what can I do to get rid of the error?

thanks in advance!

greets

**Comment by drt1** [comment]
alright, I noticed that I only used playlists for music - so I disabled the music library sync, so playlists aren't needed - and error message doesn't show up anymore.

**Comment by croneter** [comment]
Thanks for the bug report. Should be fixed in brand new BETA version 2.3.7. Please reopen the issue here should the bug persist!

**Comment by drt1** [comment]
thank you, great support!
