### ISSUE TITLE
Direct Paths: Video won't play if non-ASCII characters are in the file name (e.g. Umlaute, é, ù)

### ISSUE THREAD

**Issue by coz2001** [croneter/PlexKodiConnect#524]
I'm not sure if this is PKC or kodi, but couldn't get westworld episode "Virtù e Fortuna" & "Les Écorchés" to start/play, with Option 1 Substitute Paths using PKC & nfs://share.

**Comment by croneter** [comment]
https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
I cannot read minds nor your Kodi harddisk remotely 😉

**Comment by coz2001** [comment]
The sign above the letters é ù I believe is causing this issue.

**Comment by croneter** [comment]
Did you try the newest beta version 2.3.7?

**Comment by coz2001** [comment]
No not yet, will try and report back.

Here is a log trying to start the file.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2271633/kodi.log)

**Comment by coz2001** [comment]
Did you try the newest beta version 2.3.7?

Yes, it had updated so the log is with 2.3.7

**Comment by coz2001** [comment]
It has to be nfs that dosen't like those signs, cause when I rename them it will play fine.

**Comment by caphm** [comment]
This is an NFS issue. You need to setup your NFS share so it exports as UTF8, which requires at least NFS v4.0 (better yet 4.1) on both the client and server side.
Try browsing the NFS share outside of Kodi and check if the filenames show up correctly.

**Comment by croneter** [comment]
No PKC issue as far as I can see in the log. Thanks @caphm for the hint!

**Comment by croneter** [comment]
Workaround if you cannot get NFS to work: use add-on paths.
