### ISSUE TITLE
How to resume a episode like in Plex?

### ISSUE THREAD

**Issue by drt1** [croneter/PlexKodiConnect#526]
Hi guys,

I have one (probably dumb) question, but I don't get it...

How can I resume a already started video (on other machine with kodi and PKC) without again searching for it?

For example tvshows:
On the kodi home screen I see "In progress TV shows", but only with the complete show, not the episode.

If I hit one of the "in progress TV shows" I just get to the whole season list, and have to find the episode by hand...I think that's not the way it should work.
In plex web, there are episodes listed and I can resume them directly, I think this is called "On dock", but I cannot find the functionality in kodi via PKC.

Can someone please advise me?

thanks folks!

best regards

**Comment by croneter** [comment]
Kodi widgets are usually used for that, along with another skin than Kodis default Confluence. See here: https://kodi.wiki/view/Custom_home_items

You can use a pkc menu item as widget, e.g. the following that allows resuming: Video - Video Add-ons - PlexKodiConnect - (name of your Plex library) - 'On Deck' 

Also See here how to use skins and widgets with PKC https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins

**Comment by drt1** [comment]
ok, thank you!

best regards
