### ISSUE TITLE
Collections not showing up in TV Shows but are in Movies

### ISSUE THREAD

**Issue by ryryonline** [croneter/PlexKodiConnect#528]
I'm on the most recent stable version of PKC. I'm trying to add a menu item to Kodi (Aeon Nox skin) using collections. I am only seeing Collections available in Movies, but none in the TV Shows menu item.

Is this a bug or am I missing something?

Thanks.

**Comment by croneter** [comment]
There are no TV shows collections on the Kodi side, sorry
