### ISSUE TITLE
PKC: Kodi Beta 1 not supported?

### ISSUE THREAD

**Issue by aaronstc1** [croneter/PlexKodiConnect#532]
PKC updated to 2.3.10 and now I get a pop up that says, "Cancelling the database syncing process. Current Kodi version is unsupported. Please verify your logs for more info."

https://paste.kodi.tv/hayijowusi

**Comment by croneter** [comment]
You're probably still on an older nightly version, not the official beta 1. Try updating Kodi.

If that does not work, either downgrade pkc to 2.3.9 or manually adjust the pkc sourcecode as explained here: https://github.com/croneter/PlexKodiConnect/issues/486. You'd need to set 110 or 111 as video dB version

**Comment by aaronstc1** [comment]
Yeah, I'm not sure what's going on with bthe Xbox UWP branch. I do get the new versions a while before they are announced. I had Alpha 3 at least a week before the blog post announcing it's release. I've also been on Beta 1 since August 17th.

Currently no updates on the Xbox store. 

Anyway, I rolled back to 2.3.8 and that still works. I'll try updating PKC again after I get another Kodi update.

**Comment by aaronstc1** [comment]
FYI, 2.3.12 works on Xbox Kodi Beta 2.
