### ISSUE TITLE
PKC force trailers to start fullscreen instead of windowed, not sure...

### ISSUE THREAD

**Issue by coz2001** [croneter/PlexKodiConnect#533]
Hi,

I have started using a Titan MOD skin by cartman.dos with a Netflix look which has the option to start the trailer automatically when staying on the poster for a certain amount of time it is supposed to play it only at the top right corner like Netflix my issue here is it starts fullscreen always, all this is on the homescreen.

I have raised the issue in the skin thread and he could not find any issue related to the skin and didn't have this issue himself also on the same box as me Nvidia Shield and he might believe it's PKC.

So could this be PKC?

Thanks for all croneter

**Comment by croneter** [comment]
Sorry, this doesn't have anything to do with PlexKodiConnect. PKC only hands the play URL to Kodi. The rest is up to Kodi
