### ISSUE TITLE
Libraray sync thread crashed.

### ISSUE THREAD

**Issue by trenst** [croneter/PlexKodiConnect#534]
I'm running Kodi 18 Alpha 3.  PlexKodiConnect 2.3.9 was working well for me.  When it updated to 2.3.10, it stopped syncing and gives the error "Libraray sync thread crashed".  This error persists in 2.3.11
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2341372/kodi.log)

**Comment by croneter** [comment]
That's because Alpha is history - please update to Kodi Beta 1. If you don't want to do that, use an older PKC version smaller than 2.3.10
