### ISSUE TITLE
Kodi 18 Leia Beta1 on Xbox one s

### ISSUE THREAD

**Issue by eskimos2000** [croneter/PlexKodiConnect#535]
Hi,

Thank you for great work on this addon, it worked very well, however now on XB s Kodi got an update to mentioned version and I can't sync libraries anymore. Are you going to update your addon soon, please?
I bought you a coffee even ;-).

Cheers

**Comment by croneter** [comment]
Thanks for the coffee!!

See here for a solution: https://github.com/croneter/PlexKodiConnect/issues/532

**Comment by eskimos2000** [comment]
Yeah, I did downgrade to 2.3.8 and it's working again. Enjoy your coffee, Cheers mate.

**Comment by croneter** [comment]
I will :wink: For some reason, the Xbox builds are a step or two behind
