### ISSUE TITLE
Long Press On Media -> Plex Options -> Delete Option -> Does not remove thumbnails from kodi untill next restart

### ISSUE THREAD

**Issue by madusmacus** [croneter/PlexKodiConnect#537]
Been around for a long while now
I didnt report it as i was sure it was obvious :¬)
Prolly not that important but its a tad  anoying you dont know if you deleted something
thanks again for excellent addon

**Comment by croneter** [comment]
Does the PKC beta version 2.4.5 help here?

**Comment by madusmacus** [comment]
i tried 2.4.4 and it seemed to work better but then i tried 2.4.5 and it stopped playing anthing on my  remote plex server (just long rotating rings) so i went back to 2.4.4

last night i tried to get 2.4.5 usign the 1.0.2 repo and it was not available for me 
i assumed it was pulled?

I accidentaly updated to kodi beta 3 (oct 2) maybe i should clean install everything and go back to beta 2?

Also maybe i should remote login to my remote plex server and update it
In fact ill get of my a$$ and do that today :¬)

So many variables it must make your life a pain 
Many thanks for doign it all though i appreciate it

**Comment by croneter** [comment]
Eeeehm, 2.4.4 was the version that did not play anything. 2.4.5 should be available and stable. Please try again :wink:

**Comment by croneter** [comment]
A clean install of beta 3 might be a good idea - from a Kodi perspective (not PKC)

**Comment by madusmacus** [comment]
strange :¬) i will report back in a few hours ill do it all today
thanks for feedback

**Comment by madusmacus** [comment]
All is ok but here is my findings below...

I restarted nvidia tv and then kodi beta 3
checkjed for 2.4.5 PKC update on 1.0.2. repo and it was there.... so i installed it
I then got "Library sync thread has crashed please report to forum" twice
So I decided to reinstall Kodi Beta 3 from scratch and restart everything/databases
All worked fine from now on :¬) yaaaaaaaay

Tested my OP delete problem and its all fixed
One last big thanks croneter

I think all the betas and stuff kodi side did something and it needed a reinstall
Byeeee
