### ISSUE TITLE
GenreID bug

### ISSUE THREAD

**Issue by sualfred** [croneter/PlexKodiConnect#539]
Hey there,

I'm the creator of the official Emby skin "Embuary". Even if the the skin is targeted to Emby users, it also can be used for any other kind of Kodi setup. 

One of my users is using your PKC and was facing a problem that my genre widgets are creating KeyErrors.

After looking into his log and database I've noticed that you guys assigning the genre_id field wrong.
The IDs have to start with "1", but you guys are starting with "0". That will cause empty values for JSONRPC requests. 

Database screenshot:
https://i.imgur.com/3AHEx2e.png

Json result:
```
{u'jsonrpc': u'2.0', u'id': 1, u'result': {u'genres': [{u'label': u'Action'}, {u'genreid': 9, u'label': u'Adventure'},....
```

**Comment by croneter** [comment]
Thanks for the bug report @sualfred ,will be fixed in the next pkc version

**Comment by croneter** [comment]
Kodi database will have to be manually reset: go to the PlexKodiConnect settings, `Advanced`, then hit the red `Reset the Kodi database`. Hit YES, then NO
