### ISSUE TITLE
disable plex watch status, use kodi watch status instead

### ISSUE THREAD

**Issue by daveftw84** [croneter/PlexKodiConnect#542]
any way to disable plex watch status and only use local kodi watch status? 
so that plex server can house the metadata, pics, media, etc
and kodi can keep track of its own watch status, ondeck, etc

**Comment by croneter** [comment]
No, sorry, that is not PKC's intention.

**Comment by daveftw84** [comment]
then whats the point? why not just use the official plex addon and do what
you want it for? easier and faster...
why even sync?

**Comment by daveftw84** [comment]
not to be mean, but i thought this was  the whole point

**Comment by croneter** [comment]
Well, there's a HUGE difference between the official Plex-for-Kodi add-on and PlexKodiConnect. With PKC you can use all the native Kodi functionality as if Plex did not even exist in the background. With Plex-for-Kodi, you can only do what Plex intends you to do, "on-top" of Kodi. 
See https://github.com/croneter/PlexKodiConnect/wiki/faq

**Comment by croneter** [comment]
In a nutshell, you get the following benefits if you use PKC:
* Use virtually any other Kodi add-on
* Use any Kodi skin, completely customize Kodi's look
* Browse your media at full speed (cached artwork)
* Automatically get additional artwork (more than e.g. Plex offers)
* Enjoy Plex features using the Kodi interface

**Comment by MacQwerty** [comment]
I've to say that I highly agree with Croneter! 

Plex's watch status syncs across all devices which is great as you can continue to watch on another device from where you left. If you have several users you should get a Plex Pass or share your PMS to other Plex accounts. However, if you only want to use Kodi's watch status, you should skip PMS and setup everything through NFS/SMB as everyone else does...

**Comment by daveftw84** [comment]
I have everything on a virtual server. over 150 TB.
I don't want to have to use the android boxes memory to store metadata.
all im asking for is a switch to turn it off and on. not get rid of it for
everyone.
I would like to be able to use pseudo tv and use one account on all devices.
plex has a 100 user cap. so making accounts is out of picture for me

**Comment by daveftw84** [comment]
revisiting this idea. 
going to try to interrogate it myself, i dont want to boggle down my plex server s by constantly making writes to the db to do something the clients should be doing anyway.
just throw a track account on the devices you want to sync watch status with and call it a day

**Comment by daveftw84** [comment]
i want my server to be only a media-meta host. i dont need it to waste resources and also limit my selection of kodi addons. a simple switch to disable monitor play status can already be found in plexbmc and works very well. plex database are pain to deal with when your library starts to get big.  plex app also does a bad job with direct playing everything, it tends to transcode more then needed while kodi can transcode more audio formats client side. so its able to direct play correctly by letting the clent do the work.. see where im getting here? plex is great but baddly designed,  the cleints should be offering to do more of the work. not forcing everything on the server. the same devices running kodi can direct play almost anything thrown at it.  database locks and unnecessary trans codes is killing my server and this is very common with anyone with a few TBs

**Comment by daveftw84** [comment]
https://www.reddit.com/r/PleX/comments/9pleen/constant_plex_database_issues/

**Comment by croneter** [comment]
Moved to Feathub, where Feature Requests belong: https://feathub.com/croneter/PlexKodiConnect/+47

Do vote there if you think you need this feature
