### ISSUE TITLE
Music isn't show in Kodi 18 beta 3

### ISSUE THREAD

**Issue by nexusle** [croneter/PlexKodiConnect#548]
Hi croneter,

I've setup a music library on my PMS. PKC scans these library but MyMovies72.db is empty (zero bytes). Didn't know what I should do to see my music in Kodi again.

I did several things... deactivate/activate music library scan; killes MyMovies72.db but nothing happens.

**Comment by croneter** [comment]
Log file of your sync progress please - see the wiki here on github

**Comment by croneter** [comment]
Please share your log, see  https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Did you activate `Enable Music Library` in the PKC settings under `Sync Options` and then restart Kodi?

**Comment by nexusle** [comment]
Hey croneter,

Sorry for the late answer. I had several other problems with PKC the last days. I.e. I scanned Plex an rebuild the library. In this case, all entries disappeared when I goes into the addon itself and looked into the plex libraries. 

Now I resetted Kodi to defaults and all is working again. So I think it was another bug in Kodi settings somewhere.

**Comment by croneter** [comment]
Thanks for letting me know that everything is fine, @nexusle !
