### ISSUE TITLE
PlexPy - Last Watched not updating from PKC

### ISSUE THREAD

**Issue by llpr** [croneter/PlexKodiConnect#55]
It looks like the Last Watched tab in PlexPy is not updating from PKC. PlexPy detects what's playing from PKC and even logs it in the user history as a "Kodi" device play, but it never receives the final completed watch status. PlexPy is configured at a 85% watched percent. I've also notified the PlexPy team, but this used to work before with PKC. Thanks for your time.

**Comment by croneter** [comment]
Any idea when this issue started, which PKC version? Was there a new PlexPy version? Does everything look correct on the Plex Media Server side? (e.g. movies are indeed watched as completely played)

**Comment by llpr** [comment]
If I look at my user log in PlexPy it stopped registering as 90-99% viewed after the 17th of may. After that, PlexPy registers a 0% view status but logs to correct viewing duration. Hope this helps.

**Comment by PadelzZ** [comment]
Also been having this problem lately, for me it just started like 2 days ago when i first started noticing it.
Their is no problem with the watched status on the Plex Media Server side for me, Plexpy shows the duration i watched for the episode but the watched status keeps at 0%.
Im using the latest PMS server update(plex pass) also been using the latest update of plexkodiconnect from the repository. Last update of PlexPy was v1.4.5 (2016-05-25) but im having problems since a few days so the problem wouldn't be with PlexPy.

**Comment by croneter** [comment]
Please report this also to the PlexPy devs. PKC only interacts with the PMS. I have absolutely no idea how PlexPy works, but it must be listening in on the PMS....

**Comment by PadelzZ** [comment]
Yeah i was just thinking about it,couldn't be problem with plexkodiconnect because it is noticing the PMS server the episode has been watched and PMS has the watched status for the media file you have been watching

**Comment by llpr** [comment]
Oh I forgot to mention that I'm running SPMC if this is relevant.

**Comment by JonnyWong16** [comment]
PlexPy dev here.

PKC is reporting the `viewOffset` in seconds instead of milliseconds after this change c47fc7f25f231c33459cace7860ad3c0a691795c which is causing the watched percent in PlexPy to be off by a factor of 1000.

I would strongly suggest keeping the `viewOffset` in milliseconds as this is how every other Plex client reports it.

**Comment by croneter** [comment]
Hi PlexPy dev JonnyWong :-). Thanks for chiming in!

I don't think that commit is the issue. I think it could be this one, where I removed the "PMS"(/PlexPy?) discovery in the local LAN: https://github.com/croneter/PlexKodiConnect/commit/719956157306d54b510e97f1cbec2d099a7f1908

Would PKC need to broadcast what it's playing in the LAN? Or does PlexPy get this info from the PMS directly?

**Comment by JonnyWong16** [comment]
PlexPy gets all it's info from the Plex API. So as long as PKC is reporting the correct info back to Plex, then everything will be fine. There does not need to be any interaction between clients and PlexPy.

@llpr and @PadelzZ both sent me their PlexPy databases and PKC was reporting `viewOffset` in milliseconds before May 18th, and it changed to seconds afterwards.

**Comment by croneter** [comment]
So why would everything work on the PMS side just fine, but not on the PlexPy side?

**Comment by croneter** [comment]
I know that the plex websocket api usually tells time in seconds. Except sometimes in milliseconds, pretty randomly. Had to include a check for that, otherwise you'd have a few screwed up resume points in kodi

**Comment by JonnyWong16** [comment]
I don't use PKC so I can't check this.

If you access this API endpoint when something is streaming with PKC. Is the `viewOffset` in milliseconds or seconds?
```
http://<plex_ip>:32400/status/sessions?X-Plex-Token=<plex_token>
```

**Comment by croneter** [comment]
Just FYI - PKC only uses websocket to be informed on PMS changes and items being played off that PMS. Didn't find useful info on also telling what kodi and PKC is playing - for that, the timeline endpoint of the PMS is triggered

**Comment by llpr** [comment]
@JonnyWong16 Yes websockets is at on. I'll try to disable it and report back.

**Comment by PadelzZ** [comment]
@JonnyWong16 got it enabled, will try later to see if their is any difference

**Comment by llpr** [comment]
@JonnyWong16 @croneter It didn't work for me. Still  0% view status after.

**Comment by JonnyWong16** [comment]
Can some one check the url in my previous post?

**Comment by llpr** [comment]
@JonnyWong16  I've resumed a movie and this is what I'm getting: "viewOffset="5388016"

**Comment by JonnyWong16** [comment]
@llpr That's in milliseconds (90 min movie) so it should show up properly in PlexPy.

**Comment by PadelzZ** [comment]
@croneter and @JonnyWong16  disabling websockets in plexpy fixed the problem for me i both thank you for your help and support. Keep up the good work!

**Comment by llpr** [comment]
Same here, it's now working. Thanks for the help guys!
