### ISSUE TITLE
Movie never starts ...

### ISSUE THREAD

**Issue by scott451** [croneter/PlexKodiConnect#550]
Hello,

I am at wit's end. I have been using PlexKodiConnect on a Vero4k for some time with basically good results but now I have reached an impasse. When I launch a movie Kodi either,

a/ briefly shows the spinning circle that normally precedes a movie's start and then returns to menu, or
b/ show the spinning circle indefinitely until I exit.

I do not think that my server is the issue as I can play movies on my other TV with OpenPHT on a Raspberry Pi 3. I have also rebooted my system and reinitialized the database. I have also had this error with many movies.

I might also mention that I use the skin Aeon Nox Silver. Here is an excerpt of the log. Please help !

- Scott

**Comment by croneter** [comment]
Hmm, weird. Could you please share your entire log by **attaching** it here, not copy-pasting? Also, did you try a Kodi database reset? (Under Advanced in the PKC settings)

**Comment by scott451** [comment]
hello again,

here is the log. after putting kodi in debug mode i rebooted. log file starts with reboot. i navigated to moves and tried a movie on first page which worked (strangely enough). i then scrolled down to a different file and experienced the same 'infinite wait' behaviour.

yes i reset the kodi database. i also re-scannned the plex database and restarted the server. to no avail ...

thanks for your help,


- scott



[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2514986/kodi.log)

**Comment by croneter** [comment]
Thanks for the log! Where did you scroll? Did you navigate within your movie library instead of playing from the Kodi homescreen (like the first movie you played)?

**Comment by scott451** [comment]
hello,

both movies were played inside the movie library. the first movie was on the first page of the movie library. i was so surprised when in played that i scrolled (a long time) to find the movie that i knew would fail.

thanks again for your help !

- scott

**Comment by croneter** [comment]
Please try the new PKC **beta** version 2.5.0. Problem solved?

**Comment by scott451** [comment]
Hi,

I installed the beta. I got a blue screen with a sad face following install when reboot was initiated. I rebooted manually and it seems to work, however ... it only sync 1000 out of 1400 films. The status bar advances in a regular manner until around 1000 and then it goes instantly to 100%, but films are not synced.

I tried to force update the database. I received database locked error. PKC also said impossible to reset database in a dialog box when i attempted that.

After another reboot down to 200 movies. Logs attached.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2637337/kodi.log)

Is it possible to go back to stable version or is my KDC installation fried ?  Thanks again,


- Scott

**Comment by croneter** [comment]
You can go back, of course! Be sure to also manually downgrade the 2 helper Kodi addons plugin.video.plexkodiconnect.movies and plugin.video.plexkodiconnect.tvshows to 2.0.5

**Comment by scott451** [comment]
cool,

just realised that i could upgrade to a previous version. thanks for the up on the helpers.

is there a way for it to stop proposing upgrades to beta ?  do i need to uninstall the updater and reinstall from the stable zip or will that delete the pkc install as well ?

- scott

**Comment by croneter** [comment]
I don't know whether you can deactivate Kodi's update suggestions. Check the Kodi forum please. I would not uninstall the PKC repo, however ;-)
