### ISSUE TITLE
Issue connecting in 2.4.X

### ISSUE THREAD

**Issue by sthebemita** [croneter/PlexKodiConnect#551]
Hi, I experienced a bug in 2.4.X versions (at least 2.4.9 and 2.4.1). A few days ago the addon was logged out automatically, but I wouldn't be able to connect with the server again. The expected behavior after choosing the server would be getting a message ("not yet authorized...") and after clicking OK you would get a code to authorize PKC. However in this case after the ""not yet authorized..." message I didn't get anything. This happened on a Mi Box using Kodi 17.6, I also tried it on Kodi for PC and I had the same issue. I don't have a log, sorry. 

However, I know it's not a router problem like this: https://github.com/croneter/PlexKodiConnect/issues/472 because I uninstalled 2.4.9 and installed 2.3.0, which uses a different UI, and it did work, I got the pin and logged in successfully. So this isn't really a problem for me for now, I guess I can just keep running 2.3.0 as long as it works, but it might be a bug that affects other people too.

**Comment by croneter** [comment]
Install the latest version again, then navigate to the PKC add-on settings. Choose Pick my PMS from a list in the Connection section. Does that work?

**Comment by sthebemita** [comment]
That's what I did, it does find my plex server, but when I select it I get the "not yet authorized" message, and that's it. In 2.3 (and older probably) after clicking OK in that message I get the pin to enter in plex.tv, and it works properly. So I guess it's some kind of issue with the new UI (since it changed from 2.3 to 2.4), or maybe something about that version of Kodi.

**Comment by croneter** [comment]
In the Plex.tv section, toggle sign in to plex.tv. You might need to do that several times

**Comment by croneter** [comment]
Issue solved?
