### ISSUE TITLE
PKC not working on Kodi 18 Beta 3

### ISSUE THREAD

**Issue by larserich** [croneter/PlexKodiConnect#552]
Hi,

just installed the latest LibreElec Kodi 18 Beta 3 version on a Raspberry PI3. Then installed the PKC addon. All movies and TV shows were synced but no media is played. When I select a movie it is not played or Kodi crashes. Also the preview on the first page is not displayed correctly. Tried it with several different Kodi versions but it never works on Kodi 18. On Kodi 17 everything works without any problems. 

Can you help out here? No idea what I am doing wrong. In the past it always worked without any problems.

Thanks for your support,
Lars

**Comment by croneter** [comment]
Sorry no, because LibreElec with Kodi 18 is still an alpha version and thus has loads of bugs. Use 17 for now until LibreElec has stabilized
