### ISSUE TITLE
Delete items option missing

### ISSUE THREAD

**Issue by zombieagain** [croneter/PlexKodiConnect#553]
Hi, I know that an issue about this was opened a while back, but I still have the problems. I've been using PKC for a long time now and e few weeks back the delete option in the context menu disappeared. The only three options are start playback, force transcode and addon settings. 
my plex server is up to date (v 1.13.9.5439) restarted several times and I only have one user on plex. 
In plex I have "allow media deletion" checked in settings --> library
I even uninstalled and reinstalled PKC and reset all settings.
Do you have any suggestions? Is there anything else that I need to set in either PKC or Plex server. Again, this worked fine for months. Thanks!

**Comment by croneter** [comment]
What pkc version are you using? Could you make a screen shot of the context menu with the missing delete entry?

**Comment by zombieagain** [comment]
and sure enough, after several weeks, the option is back and working. The only thing that happened between yesterday and today was an osmc update... Sorry about this...
