### ISSUE TITLE
Playlist Sync Documentation

### ISSUE THREAD

**Issue by quixote23** [croneter/PlexKodiConnect#554]
I'm trying to get playlists to sync from Plex into Kodi and I've been unsuccessful so far. Poking around, I'm not seeing any kind of documentation or guide to setting this up (just that it's expected to just work automatically once enabled, which it isn't for me.) I wonder if anyone can answer the following:

1. Can I expect to see my music playlists imported or is this for video playlists only?

2. I don't use native Kodi playlists - once imported, where exactly are they supposed to show up? I've checked under every module called Playlists (both Kodi and PKC) and I'm not seeing either my music or my video test playlist showing up.

3. When I open the PKC addon, I see a list of options: Playlists, Plex Hub, Watch Later, etc. None of these have ever populated with anything except for Channels, which shows my Plex plugins.  What should I be seeing here? 

Additionally the last two options (Refresh Plex Playlists/Nodes and Perform Manual Library Sync) don't appear to do anything - if I want to do a manual sync, which I do quite often, I have to navigate into the add-on settings for PKC and run it from there. 

What am I doing wrong? Needless to say PKC itself works great and I've never had any problem syncing my Plex libraries. I don't really use video playlists but I'd love to be able to import my music playlists from Plex to Kodi if possible.

**Comment by croneter** [comment]
I will update the wiki here on Github if I find the time. 

For playlists to work:
* Make sure that you have `Sync Plex playlists` enabled in the PKC settings under `Sync Options`
* Make sure that you're NOT using Kodi on some kind of [Microsoft UWP](https://en.wikipedia.org/wiki/Universal_Windows_Platform) Operating System - playlists won't work then, unfortunately (Microsoft is too restrictive).

1. Music and video playlists, yes. Playlists are synced from Plex to Kodi and from Kodi to Plex. Mixed Kodi playlists are NOT synced (mixed does not exist on the Plex frontiert). 
2. See here: https://kodi.wiki/view/Basic_playlists. E.g. for videos, navigate into your e.g. Movie library in Kodi, then hit the three dots `...`, then hit the three dots again, , then choose `Playlists`
3. You should see EITHER all your Plex video playlists OR all your Plex music playlists. This depends whether you started navigating from the Kodi music library OR from some Kodi video library. It won't show if you start navigating from e.g. Kodi pictures!

**Comment by quixote23** [comment]
Thank you, this is extremely helpful. 

It turns out my problem may be related to how my Kodi skin handles playlists, as I can see both the music and video playlists have been imported to AppData\Roaming\Kodi\userdata\playlists\, but the option within Kodi to navigate directly to one or the other is not immediately apparent. Anyway, thanks again!

**Comment by quixote23** [comment]
FWIW, I addressed this by creating submenu shortcuts under Movies and Music with the following custom commands, respectively:

ActivateWindow(Videos,special://profile/playlists/video/,return)
ActivateWindow(Music,special://profile/playlists/music/,return)

I am now able to browse directly to my synced playlists in Kodi.
