### ISSUE TITLE
Using http source for direct paths

### ISSUE THREAD

**Issue by madknave** [croneter/PlexKodiConnect#555]
Hello,

I am wondering if it would be possible to utilize the internal HTTP source created by this plugin (https://github.com/cguZZman/plugin.googledrive) for direct paths. 

I was playing around with the path substitution that PKC does to try and point to the HTTP source of the googledrive addon, and indeed, it almost works. The only problem that I encountered is the way HTTP treats `spaces` in a path (it uses `%20` instead). 

Would it be possible to give the option of replacing those `spaces` with `%20` so we can use the googledrive source?

i.e.
`http://localhost:8587/source/USER/media/movie%20example/movie%20example.mkv`
instead of
`http://localhost:8587/source/USER/media/movie example/movie example.mkv`

**Comment by croneter** [comment]
Nice use case! Yes that's definitely possible. I'll look into it

**Comment by croneter** [comment]
Implemented in PKC 2.5.9

**Comment by madknave** [comment]
I tried the implementation quickly this weekend, it is currently escaping the whole path, meaning that the `:`'s from `http://localhost:8587/` are also escaped. Could you modify it to only escape the path substitution portion (`/movie example/movie example.mkv`) instead of the whole path?

**Comment by croneter** [comment]
Should work with 2.6.1
