### ISSUE TITLE
Plex Incorrectly Reporting Playback for DVR Files

### ISSUE THREAD

**Issue by incompetus** [croneter/PlexKodiConnect#557]
Hi

As detailed on the PKC plex thread, here's logs for when Kodi plays a DVR file, and Plex then starts reporting that media is being played incorrectly. 

Show being played on the DVR is 'Grand Designs' - I've seen it updating Plex status for a couple of different random shows in the Plex library...

Interestingly it will only report to Plex that incorrect media is being played if you start from the very beginning, if you resume playback it doesn't do it. Reset the watched status to start from the beginning again and it will report incorrect media again...

Thanks

Jon

[kodi.old.log](https://github.com/croneter/PlexKodiConnect/files/2543190/kodi.old.log)

**Comment by croneter** [comment]
As a sidenote: You have numerous errors like these in your log:
```
DEBUG: CWebServer[8080]: request received for /image/image://https%253A%252F%252F<IP>%253A32400%252Fphoto%252F%253A%252Ftranscode%253Fwidth%253D4000%2526height%253D4000%2526minSize%253D1%2526upscale%253D0%2526url%253D%252Flibrary%252Fmetadata%252F83874%252Fthumb%252F1514485895%2526X-Plex-Token%redacted
ERROR: CCurlFile::Exists - Failed: SSL peer certificate or SSH remote key was not OK(51) for https://<IP>:32400/photo/:/transcode?width=4000&height=4000&minSize=1&upscale=0&url=/library/metadata/83874/thumb/1514485895&X-Plex-Token=xxx
```
If you're using the "standard" Plex way of setting up your PMS (and don't use your own SSL certificates), then try to reconnect to your PMS:
- In the PKC Settings under Connection, Choose `Pick your PMS from a list`
- Wait for the PMS to be shown
- Simply reconnect to your PMS
- Reset the Database in the PKC Advanced section

**Comment by croneter** [comment]
Silly question: in the log you shared, is the DVR you played ('Grand Designs') something from your Plex library? OR is this not showing up on your Plex side of things and only Kodi?

**Comment by croneter** [comment]
So that means PKC should not be telling that the DVR recording is being played, at all... This could get a bit ugly as PKC needs some hacky workarounds for playback updates - one of them firing now too often when it should not

**Comment by incompetus** [comment]
Nope - there should be no need for PKC to report any playback status for that DVR recording, nope...

Could you not just check if the playback source is dvr:// and ignore updates back to plex if true?

**Comment by croneter** [comment]
Is this still an issue with the brand new 2.6.0?

**Comment by croneter** [comment]
Is this still an issue?
