### ISSUE TITLE
Latest Kodi Krypton not working, Library sync 

### ISSUE THREAD

**Issue by blablub121** [croneter/PlexKodiConnect#56]
Since a few days no more tv episodes are added to Kodi Library. New episodes are found in PMS but not pushed to Kodi with either manual sync nor scheduled sync. I have already reset Kodi library and also reinstalled Kodi with a new user profile.

My setup:

Ubuntu 16.04
PMS 0.9.16.6
Kodi  2:17.0~git20160609.0200-d432df0-0xenial

I can provide logs, you just need to tell which you like to have.

**Comment by croneter** [comment]
Please enable debug logging in the PKC settings, Advanced. Then restart Kodi and reset the database. Capture the logs after initial sync has finished and share them here. Do note which PMS items are missing

**Comment by croneter** [comment]
Kodi logs should suffice

**Comment by blablub121** [comment]
Some of the missing episodes:
23:17:49 T:140531858401024  NOTICE: PlexKodiConnect Items -> run_add_updateEpisode : ADD episode itemid: 16186 - Title: What Happened to You, Annalise?
23:17:37 T:140531858401024  NOTICE: PlexKodiConnect Items -> run_add_updateEpisode : ADD episode itemid: 16198 - Title: Eyes to Eyes
23:18:41 T:140531858401024  NOTICE: PlexKodiConnect Items -> run_add_updateEpisode : ADD episode itemid: 16193 - Title: Selbstjustiz

You can find the whole log here: https://dl.dropboxusercontent.com/content_link/vzPsiS8P3hRBJW5l05s1KbXUJDLGmb6n7XDOTJ1lOBwStiMruxkoLGw49gs6r2Il/file?dl=1

**Comment by blablub121** [comment]
Got it working again. Kodi 17 made a DB version bump to 105 with https://github.com/xbmc/xbmc/commit/600dc168f353ab30f59afdb4ec710f6794ad33fe
So I replaced 104 with 105 in https://github.com/croneter/PlexKodiConnect/blob/master/resources/lib/utils.py

**Comment by MartinAyla** [comment]
Thanks! This was driving me crazy.

Can I just go to my add-ons folder and make that change and restart Kodi?

Also, do I need to reset my DB afterwards?

**Comment by croneter** [comment]
Yes, go to your addons folder and change the source code in plugin.video.plexkodiconnect/resources/lib/utils.py. You do not need to reset the DB, as far as I can tell

You might want to disable automatic updates for PKC, or these changes will be undone on any next release ;-).

**Comment by croneter** [comment]
I won't be changing this soon in PKC. Otherwise, all older installations of Krypton will stop working... This is the danger of using Krypton Alpha versions ;-)
