### ISSUE TITLE
Disable Plex Image Caching Notifications?

### ISSUE THREAD

**Issue by drt1** [croneter/PlexKodiConnect#560]
Hi folks,

everytime I start kodi, I see the "Image caching" notification, and after a while another Notification, that image caching is done. This always interrupts me in the middle of some video, so I'd like to let do PKC the work silently.
Therefore I enabled the "Show sync progress"-setting, but unfortunately the messages still show up.
Is it possible to hide also these status messages?

I am also wondering, why PKC shows the exact same number of images to cache every time I start kodi...is it intended, that ALL images are synced to cache on every start?

thank you

best regards

**Comment by ellite** [comment]
Settings -> Artwork -> Enable Notifications for image caching

**Comment by drt1** [comment]
Erm...I must have been blind.
Thank you very much for answering, despite my obvious blindness.

best regards

**Comment by drt1** [comment]
Erm...I must have been blind.
Thank you very much for answering, despite my obvious blindness.

best regards
