### ISSUE TITLE
Latest Kodi 18 Beta 5 not working with PKC

### ISSUE THREAD

**Issue by kat953162** [croneter/PlexKodiConnect#562]
Latest Kodi beta 5 isn't compatible with latest PlexKodiConnect. I get  a Pin overlay every time I launch Kodi. After that, it never syncs my libraries, whether I choose native paths or through the addon. The PlexKodiConnect settings are blanked out with no text, thus useless. Relaunching Kodi just gives the Pin overlay again.

**Comment by croneter** [comment]
Please try the new PKC **beta** version 2.5.0. Problem solved?
