### ISSUE TITLE
HTTP/HTTPS in initial setup

### ISSUE THREAD

**Issue by nexusle** [croneter/PlexKodiConnect#569]
Hey croneter,

could you please implement a option in initial setup to choose HTTP or HTTPS. As default PXC is thinking, we use HTTPS, but some people doesn't. So if I forget to go to options after initial setup, I must do a database recovery next time...

**Comment by croneter** [comment]
No sorry. I want to keep the initial setup as easy and lean as possible. PKC usually detects whether HTTP or HTTPS is needed. Otherwise, you would have to fine tune the settings anyway

**Comment by nexusle** [comment]
No. It doesn't. My config ever used port 80, without SSL. Every initial setup think, I use SSL. 
Also, I just started a new setup today with 2.5.6. I went to go into the config after initial setup, but PKC is restarting Kodi soon. I'm unable to set HTTPS off until I make it with SSH to the box ...

**Comment by nexusle** [comment]
Not 80, Plex standard port, but without SSL ... my mistake

**Comment by croneter** [comment]
So going to the PKC settings while you install PKC works?

**Comment by nexusle** [comment]
Yes. In progress of initial setup I go to settings, but PKC is restarting Kodi itself. Is doesn't wait for me to take this change.

**Comment by croneter** [comment]
Closing this issue.

On installation, PKC presents the PMS to connect to. If that is not sufficient, you can choose to show the PKC settings to fine tune your settings - WITHOUT PKC restarting
