### ISSUE TITLE
increase timeout to play a movie/show

### ISSUE THREAD

**Issue by tunip** [croneter/PlexKodiConnect#57]
For powersaving, all 5 disks will spin down (sleeping) after certain time of idle on my NAS.

If i start watching a movie/show on my kodi-client with PKC, the disk needs -of course- to spin up, which needs mostly a few seconds (5-10). On every start watching a movie/show from a sleeping disk, I receive a message "could not play movie/show". After second try movie/show starts immediately.

Is there a value/setting which could be set to wait a little bit longer for starting a movie/show, before popup comes with "could not play movie/show".

Thx

**Comment by croneter** [comment]
Weird - my harddisks power down too, it takes around 5-10s for them to power up again. Might have more to do with Plex Media Server and the PMS host OS...

I'm using a Raspi 2 with Openelec as a Plex client, Windows as PMS host.

Could you please share a log when this happens? Please increase logging to "debug" in the PKC settings, advanced. Then capture when you try to play for the first time and fail as well as succeeding the second time. Thanks

Makes it easier to implement such a functionality ;-)

**Comment by croneter** [comment]
What happens if your change your advancedsettings.xml to have a client timeout of like 15 seconds? See here http://kodi.wiki/view/Advancedsettings.xml#samba

**Comment by tunip** [comment]
Tests with advancedsettings.xml and 15 seconds timeout was successful 👍

Many Thx

**Comment by kler** [comment]
I guess the entry you changed @tunip was `<clienttimeout>` in the `<samba>` section?
```xml
<samba>
  <clienttimeout>10</clienttimeout>  <!-- timeout (in seconds) -->
</samba>
```

I experience similar problem, but locally on attached USB disks.
Is anyone aware if there is a similar timeout option, but for locally mounted disks?
