### ISSUE TITLE
Not Issue - Suggestion

### ISSUE THREAD

**Issue by starman2908** [croneter/PlexKodiConnect#571]
I have no idea about coding but have seen similar implementations on other add-ons......I'm noticing some folk complaining about throttling issues downloading additional-art from source. To prevent possibility from the add-on being blacklisted, could you integrate an ability for people to use their own API keys for TMDB/Fanart.TV to save your access load on additional artwork? 

Also, disk space can be a commodity with some setups and depending on skin preference, a toggle to download additional artwork types. I.e an option to turn on/off downloads (for HDclearlogo/Clearlogo, Discart, additional fanart, season art, collection art ETC) would be very handy.... I reckon most folk like myself use plex to draw poster and fanart from their own servers and depending on the skin in use..... all downloads/missing artwork maybe surplus to requirement. It would save the load through your API, and also save users of the add-on from caching any more disk space than necessary depending on their skin preferences and utilization..

Ryan

**Comment by croneter** [comment]
You can change your API keys if you manually edit `settings.xml` in the PKC add-on folder `plugins.video.plexkodiconnect` in your Kodi userdata folder. Look for `FanArtTVAPIKey`, `themoviedbAPIKey`. By the way: PKC has never been baned. These services servers were just experiencing very high loads last weekend so they had to throttle. 

Deactivate getting additional fanart in the PKC settings. The use the Kodi add-on artwork beef. Problem solved 😉
