### ISSUE TITLE
Long Press On Media -> Plex Options -> Delete Option -> Does not remove thumbnails from kodi untill next restart - Reapeared

### ISSUE THREAD

**Issue by madusmacus** [croneter/PlexKodiConnect#572]
This issue was fixed back on October 7th 2018 - #537 - but it has reappeared again
Not the end of the world but i have to restart Kodi now to see deletions

Thanks for all your work on this :)

**Comment by croneter** [comment]
Beta version of pkc?

**Comment by madusmacus** [comment]
Sorry forgot to say version

The newest beta 2.5.5 and fresh install of Kodi RC2
I always test the newest beta versions

Thanks croneter

**Comment by croneter** [comment]
Hmm, works here. Can you please try again with the new 2.5.7 (coming in a couple of minutes) and share your DEBUG log-file if it still does not work? Thanks

**Comment by madusmacus** [comment]
I will do it next 30 mins :¬) 
Ill ahve to look where the debug logs are kept hehe

**Comment by madusmacus** [comment]
ok i got link to logs of 2 deletions
https://paste.kodi.tv/obuwazudib

the delete works but the refresh container nolonger works weird
it just flashes the file it deleted but does not remove it from the thumbnails

15:01:20.206 T:170605098224  NOTICE: PLEX.context: option selected: Delete item from server
15:01:23.145 T:170605098224  NOTICE: PLEX.context_entry: Deleting Plex item with id 3141
15:01:23.650 T:170605098224  NOTICE: PLEX.plex_functions: Successfully deleted Plex id 3141 from PMS
15:01:23.650 T:170605098224  NOTICE: PLEX.context_entry: refreshing container

give me a shout if you need anything i will do it immediately

many thanks for all this :-)

**Comment by madusmacus** [comment]
i just noticed 2.5.7 was not on repo
i think was just called 2.5.6 because i did get an auto update
:)

**Comment by danjames92** [comment]
@madusmacus Nope. 2.5.7 is a new update. If you don't see it, uninstall the repo and reinstall

**Comment by madusmacus** [comment]
i will do now

**Comment by madusmacus** [comment]
that got 2.5.7 to install thanks but this issue still persists as reported above
i turned debug on and got a full log with more info in it here

https://paste.kodi.tv/hopebisini

shout if anything else is needed
ty

**Comment by madusmacus** [comment]
did some more digging and the only thing i can do to refresh the thumbnails so the deleted ones are gone is todo a 

addons->plexkodiconnect->perform a manual sync
or
restart kodi

this exact same issue was fixed back in october for me 
this is nvidia shield tv running kodi newest stablish rc3 (not nightly)
weird :)

i will stfu now hehe

**Comment by madusmacus** [comment]
After many clean installs kodi/1.02repo/2.5.7 and data base resets...
This issue appears to be fixed
I do not have a clue why its fixed itself

I thought maybe local kodi media and plex media together but no

Seems it has automagicaly fixed itself    vvvv weird
maybee some generic kodi addon has updated and fixed thumbnail cache
who knows

might as well close this as i can no longer do anything to break it
ty for your patience
