### ISSUE TITLE
Error while instaling. script.module.defusedxml 0.5.0 could not be satisfied.

### ISSUE THREAD

**Issue by Pawliko** [croneter/PlexKodiConnect#573]
When i try to install from repo, i got this error.
"The dependency on script.module.defusedxml version 0.5.0 could not be satisfied"

Any tips what am I doing wrong?
Thx

**Comment by croneter** [comment]
For some reason, Kodi sometimes does not install dependency addons so you need to do it manually. This one in your case: https://kodi.wiki/view/Add-on:Defusedxml

**Comment by SuperBoss9** [comment]
Fresh installation of LebreELEC 10.0 (2021.11) with Kodi 19.3 and Linux Kernel 5.10.x on RPi 4 leads to "he dependency on script.module.requests version 2.22.0 could not be satisfied" error with unable of installation....

**Comment by croneter** [comment]
Then it's missing on the LibreElec side. Grab it here and then manually install from ZIP: https://kodi.wiki/view/Add-on:Defusedxml
