### ISSUE TITLE
Error message not going away

### ISSUE THREAD

**Issue by milnash** [croneter/PlexKodiConnect#574]
PlexKodiConnect error in library sync. With red cross. Not going away during playback...

**Comment by croneter** [comment]
https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
I need logs

**Comment by BlackMamba248** [comment]
Hi Croneter, I think the error in library sync might be related to an issue me and a few others have. We posted it under the other post titled Beta 2.5.x: not all Plex items synced #566 since it was related missing contents after sync. I posted my log there as well, wasn't sure to make a new issue post since similar to this one.

**Comment by starman2908** [comment]
Hi Matey, I'm running the latest beta (2.5.5) on Leia RC2 (Windows 10) with the same issue. 

Initial sync seems successful and generally is great to load up (congrats on your hard work!!), but when playing an item... i'm getting a library sync error message, which doesn't disappear and seems to cycle a continuous sync with same error... Here is the log and image for you to have a look through :) Cheers, Ryan.

Log - https://1drv.ms/u/s!AjLrauIo92yxmMcRxOY-uogRyV3nGQ
Image - https://1drv.ms/u/s!AjLrauIo92yxmMcQY9EEPi4TdhuSZw

**Comment by danjames92** [comment]
Here's my log

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2683464/kodi.log)

**Comment by croneter** [comment]
Is beta version 2.5.6 solving this issue?

**Comment by starman2908** [comment]
You are a god amongst men! The error has gone, done a fresh install (WIN 10 Leia RC3) and the initial sync was super fast... the error has gone initiating playback. However, on restarting kodi, sync seems to hang on a loop... one step closer :) kudos... attached a log.

Cheers,
Ryan

https://1drv.ms/u/s!AjLrauIo92yxmMdprUGTYizb3FSn4w

**Comment by starman2908** [comment]
Addition : Put a delay startup incase my pvr was affecting load. PlexConnect starts succesfully and sync finished with the delay. But when trying to play anything it shuts down kodi (WIN 10 Leia RC3)

Here is that log:

https://1drv.ms/u/s!AjLrauIo92yxmMdqy3MQYUGoHYFXcQ

Cheers, Ryan

**Comment by croneter** [comment]
Kodi crashing seems due to Kodi caching images in the background. Just let Kodi sit for a while after the initial sync. Nothing I can do there, really...

**Comment by starmanrf** [comment]
Cool, I'll leave it over night and see it how it goes.

**Comment by starmanrf** [comment]
Apologies, my server is doing a metadata refresh and is taking quite a while. I'm just letting it finish and hopefully will sort the issue I encountered. Sure it will be fine 👍
