### ISSUE TITLE
No shows or movies appearing: 2.5.6

### ISSUE THREAD

**Issue by greg4168** [croneter/PlexKodiConnect#577]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2705504/kodi.log)
Hi - starting I believe with 2.5.5 and Leia,scan appears to complete successfully but nothing appears in Movies or TV Shows.  Can only get to them via the Plex Hub option.  Have tried with Estuary and same issue. Uninstalled, reinstalled, rebuilt library, nothing.  Would like to try 2.5.7 but not seeing it in the beta repository yet.  Log attached.

Thanks!

**Comment by croneter** [comment]
Completely reset pkc: go to the PKC settings, Advanced, then Reset the Kodi database (in red). Hit Yes, then Yes again.

**Comment by croneter** [comment]
Also do get 2. 5.7 before doing that :wink:

**Comment by greg4168** [comment]
Did that multiple times. Even did a fresh Kodi install.


________________________________

**Comment by greg4168** [comment]
Ok have to wait til I can see it...


________________________________

**Comment by croneter** [comment]
Did you navigate into e. G. The movie section in Kodi? You need to navigate around after first sync for stuff to appear, or reboot Kodi

**Comment by croneter** [comment]
Reboot Kodi., then try to update PKC again

**Comment by greg4168** [comment]
Yes sir.  See any sign of a problem in the log?

Why wouldn't see2.5.7 yet?  Slow replication?


________________________________

**Comment by croneter** [comment]
Yes. Do NOT use Kodi nightly version. Get release candidate 3
