### ISSUE TITLE
if PKC enabled or installed it seems to overide a kodi system variable... see inside

### ISSUE THREAD

**Issue by madusmacus** [croneter/PlexKodiConnect#579]
At kodi startup PKC seems to SET system->media->library->hide progress of library updates to ON

This has been happening to me for years, only just realised it was PKC as i was testing alot of stuff 

Its not important at all but.... it is easy to check

**Comment by croneter** [comment]
Yes PKC needs to override some Kodi settings to work properly. What's your issue, exactly?

**Comment by madusmacus** [comment]
i just wondered why when ever i turned off the system option ...
system->media->library->hide progress of library updates
PKC turns it on again next startup of Kodi :¬)

I wanted to see my local media updates so i turn it off
Do my local media stuff and see the updates but 
The next time i start kodi PKC will turn on the hide again hehehe

This is not your PKC setting show updates that works well :¬)
its the system one and does not seem to effect your addon if i turn it off :¬)

Its not a problem to do this everytime i need to see whats its doing :¬)
I jsut have to remember to turn it off again 
I reported it incase you needed to know 
Reject this if its of no interest croneter

Bye thanks and happy thingy (nearly)
