### ISSUE TITLE
Plex Plugin Support

### ISSUE THREAD

**Issue by theCheek** [croneter/PlexKodiConnect#58]
Probably a moonshot due to interface issues, but is it possible to have Plex Plugins working in PKC?

**Comment by croneter** [comment]
What exactly are you trying to achieve?

**Comment by theCheek** [comment]
Basically my family use PKC with their RPIs to stream from Plex on my seedbox. I want them to be able to request new content via Sonarr and Couchpotato, using the plugins (channels) section of Plex. 

No biggy if not, they can use the Plex Web interace to interact with the channels, but would be great if it was all contained within PKC

**Comment by croneter** [comment]
OK. Sorry but that does not make sense to incorporate into PKC itself. Rather, I'd expect a Kodi plugin to have that functionality - one layer less of complexity ;-).

**Comment by theCheek** [comment]
You're absolutely right, don't know why i didn't think that first!
