### ISSUE TITLE
Beta 2.5.x: database is locked error

### ISSUE THREAD

**Issue by spamies1** [croneter/PlexKodiConnect#580]
When kodi/plex is left running in the background overnight the next day I see a database is locked error in kodi

Heres the old log I didn't have debug enabled. If needed I can get the debug log tomorrow since it takes awhile for the error to show up.

[kodi.old.log](https://github.com/croneter/PlexKodiConnect/files/2707654/kodi.old.log)

**Comment by croneter** [comment]
I need the entire log. Debug enabled if possible

**Comment by spamies1** [comment]
I got the same database locked error today. Didn't have debug enabled. I will try and get logs tomorrow.

**Comment by croneter** [comment]
@spamies1
Share the log anyway please, I might see something even if debug logging is not enabled

**Comment by spamies1** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2713392/kodi.log)

**Comment by croneter** [comment]
@spamies1 
Very weird error. Were you able to capture it with debug logging enabled? Did it occur again or just once? Did it occure on the official Kodi RC3 as well?

**Comment by spamies1** [comment]
I didn't have debug enabled since I thought the update fixed it. I can get a debug log but I only see the pop up error the next day. Kodi needs to be restarted and its good for another 12 hours or so. I haven't tried the rc3 release. The kodi DB did change to 113 so I updated that when I install PKC updates.
https://github.com/croneter/PlexKodiConnect/blob/master/resources/lib/variables.py#L95

**Comment by croneter** [comment]
Could you please try to get a debug log for this?

**Comment by spamies1** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2716566/kodi.log)

**Comment by milnash** [comment]
I have exactly same problem. Happened over night.

**Comment by croneter** [comment]
Does 2.5.9 help?

**Comment by spamies1** [comment]
unfortunately no it still has the same error. regular log attached. let me know if you need debug and I can get it tomorrow.

**Comment by spamies1** [comment]
Unfortunately no it still has the same error. Regular log attached, let me know if you need debug.

[kodi.old.log](https://github.com/croneter/PlexKodiConnect/files/2718695/kodi.old.log)

**Comment by croneter** [comment]
Darn

**Comment by croneter** [comment]
@spamies1 
Please try again with beta version 2.5.10

**Comment by spamies1** [comment]
Kodi wasn't running over night so I don't know if its fixed, I will check again tomorrow.

**Comment by spamies1** [comment]
Looks good, no errors
