### ISSUE TITLE
Feature Request: Support android TV play next. 

### ISSUE THREAD

**Issue by spamies1** [croneter/PlexKodiConnect#581]
Play next is a row in the new android TV UI for media that is related to what was recently played. Kodi and plex both support it but with PKC its not working. If possible can this be implemented, thanks.

https://shield.nvidia.com/blog/shield-android-update-May2018

**Comment by milnash** [comment]
It is only supported in Kodi 18. Nothing to do with PKC.

You could try with SPMC (Kodi 17) and it works.

**Comment by croneter** [comment]
Unfortunately, I don't own a device to test this. Could you please share a Screenshot where this is working as well as how it looks like with PKC?

**Comment by milnash** [comment]
It works with PKC because it has nothing to do with PKC. Kodi 17 does not have this feature. Kodi 18 has it. So PKC with Kodi 18 will have this feature. Or he could try with SPMC (which is a special Kodi 17 version for Android TV).

Are you interested in getting donations so you can buy Nvidia Shield? Will make testing easier :)

**Comment by croneter** [comment]
@milnash
Naturally :laughing:

**Comment by spamies1** [comment]
I'm using kodi 18 on shield. The default Plex app works with play next. Do you have it working with PKC and shield, please post screenshots? I figured it wouldn't work since the kodi DB is "hacked" with PKC and doesn't mesh with play next.

**Comment by milnash** [comment]
I had it enabled and it worked. Have you enabled Kodi in Shield channels? I removed Kodi 18 because of issues with PKC on playback start/stop. Would have given you screenshots. Nope, I don't use direct paths. 

Otherwise, take a look at SPMC.

**Comment by spamies1** [comment]
My mistake for requesting a feature that not even kodi supports. I checked with a kodi dev and kodi 18 does not support android play next feature. You have to use smart playlists.

https://forum.kodi.tv/showthread.php?tid=332589&pid=2803647#pid2803647
