### ISSUE TITLE
Unable to update PKC beta beyond 2.4.10

### ISSUE THREAD

**Issue by bretthabel** [croneter/PlexKodiConnect#582]
Any ideas as to why I can’t seem to update past 2.4.10? It’s the latest version that appears in the repository when using 1.0.2 of the beta.

I'm currrently running Kodi 18.0-RC5 on a OSMC Vero 4K.

kodi.log available here;
https://pastebin.com/6YjTvS4M

**Comment by croneter** [comment]
Seems like you somehow botched your Kodi install. Kodi seems to hang trying to update a single other addon:
```
18:33:28.891 T:3505124080   ERROR: AddonVersion: 9-g8b77776 is not a valid revision number
18:33:28.892 T:3505124080 WARNING: Repository add-on repository.aussieaddons-devel uses plain HTTP for add-on downloads in path http://aussieaddons.com/repository-devel/ - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
18:33:28.921 T:3505124080 WARNING: Repository add-on repository.xbmc.org uses plain HTTP for add-on downloads in path http://download.osmc.tv/kodi/addons/leia - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
18:33:28.930 T:3505124080   ERROR: AddonVersion: 9-g8b77776 is not a valid revision number
```

Try to delete the addon `script.module.drmhelper v1.1.0-9-g8b77776`

**Comment by croneter** [comment]
Also, PKC does usually NOT support nightly Kodi versions! Do try "stable" Kodi 18 RC 4

**Comment by croneter** [comment]
Then again, the Kodi database changed - to use Kodi 18 RC 4, you need to wait for PKC beta 2.5.8
