### ISSUE TITLE
Deleting Plex items does not work

### ISSUE THREAD

**Issue by loeffelpan** [croneter/PlexKodiConnect#587]
I tried to delete some of my watched movies with “Delete from Server” in “Plex Settings” of context menu.
Nothings happens.

In debug log there are errors while validating which option from menu is chosen:
`UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal`

Full debug log:
https://pastebin.com/dKn3sNgM

**Comment by croneter** [comment]
Very good bug-spotting skills you have! 😆

**Comment by loeffelpan** [comment]
Just trying to be helpful! 😢
In which version the commit will be published?
