### ISSUE TITLE
Beta 2.5.x: Error entering any plex hub menus.

### ISSUE THREAD

**Issue by coz2001** [croneter/PlexKodiConnect#588]
I get a PKC error when trying to enter "continue watching", "on deck" etc. in the plexhub menu.

**Comment by croneter** [comment]
Try beta version 2.5.11, out in a couple of minutes

**Comment by milnash** [comment]
For me, everything in Plex Hub works except "Recently added Movies". Just spins and spins :(

**Comment by croneter** [comment]
@milnash
Guess what - I need debug logs
