### ISSUE TITLE
Plugin incompatible with latest Kodi 17 Krypton builds?

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#59]
If installing on anything later than around the June 1st build of Kodi 17 the PKC repository will install but afterwards Throws an error stating that it can't connect when trying to enter the repository. If installing the plugins manually, when the initial scan starts an error comes up stating that the version of Kodi is not supported. 

Older builds of Krypton works fine.

**Comment by croneter** [comment]
See #56
