### ISSUE TITLE
Beta 2.5.x: PKC only reports the first played item to PMS

### ISSUE THREAD

**Issue by MCs88** [croneter/PlexKodiConnect#591]
Hi,

I'm using the 2.5.12 beta plugin with Kodi RC4 and direct path mode.
It seems that only the first item is reported to PMS when I start the playback of on item: I start playing an episode, it shows up it the PMS activity page. After it ends I start a next episode, but it doesn't show up, when it ends, it isn't marked as watched in PMS, also PMS doesn't scrobble it to trakt. It behaves like I play it from a simple share without PKC.

Kodi log attached. [kodi.log](https://github.com/croneter/PlexKodiConnect/files/2729468/kodi.log)

**Comment by spamies1** [comment]
I have the same issue. Also kodi wouldn't exit when I was reproducing the issue with debug logging enabled. Not sure if thats related or a separate kodi issue.

[kodi_debug.log](https://github.com/croneter/PlexKodiConnect/files/2730010/kodi_debug.log)

**Comment by zonly1** [comment]
Same issue. Tell me if you need logs from me too.

**Comment by dazedcrazy** [comment]
> 
> 
> I have the same issue. Also kodi wouldn't exit when I was reproducing the issue with debug logging enabled. Not sure if thats related or a separate kodi issue.
> 
> [kodi_debug.log](https://github.com/croneter/PlexKodiConnect/files/2730010/kodi_debug.log)

Your issue might be unrelated because you are using a nightly with RC5 which was complied from https://github.com/xbmc/xbmc/commit/087521b803628221fda45626a8cca9809663c66b which had a videodb version bump

**Comment by spamies1** [comment]
I noticed that if I go into pkc and do a manual sync it starts working again but loses connection to plex after stopping the next played item. I reverted back to x.11 and its working fine again.

**Comment by croneter** [comment]
Hopefully solved in 2.5.13, let me know otherwise

**Comment by spamies1** [comment]
Looks to be fixed. thanks
