### ISSUE TITLE
[2.5.12] Follow-up dialogs from Advanced settings not showing up

### ISSUE THREAD

**Issue by BrutuZ** [croneter/PlexKodiConnect#592]
Whenever I try to trigger an action in the Advanced Tab under Settings, the PKC dialog asking for confirmation fails to show up, leaving me unable to reset the database or force update all content.

Log only prints the following line upon activating either menu item:
`T:10312   ERROR: Control 9 in window 10140 has been asked to focus, but it can't`

Kodi v18 Leia RC4
PKC 2.5.12
Titan BETA for Kodi Leia 3.8.4

**Comment by BrutuZ** [comment]
Not really. Tested with Estuary, still no pop-up messages, and no error log message to boot.


-------- Original message --------

**Comment by croneter** [comment]
Do you have the "official" Kodi 18 RC4 installed or some nightly version? PKC **ONLY** supports the official releases as too much can break otherwise. 

Please share logs: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by BrutuZ** [comment]
Regular RC4, not a nightly.
Generated a fresh `kodi.log` only going into the settings and trying to trigger a Database reset first, and a Force Refresh right after, can be found on https://paste.kodi.tv/giqiricoja.kodi

**Comment by BrutuZ** [comment]
It might've been to do with the upgrade from 2.4.11 -> 2.5.12
Just completely uninstalled PKC wiping its settings and reinstalled 2.5.12 from scratch. Prompts are showing again as intended 👍
