### ISSUE TITLE
Beta 2.5.x: Database locked

### ISSUE THREAD

**Issue by coz2001** [croneter/PlexKodiConnect#593]
Since 2.5.12 I had database locked messages but with debug off, with this log I haven't seen the message but pretty sure its locked since adding content to PMS don't get synced to Kodi/PKC, only on a new session things will sync.

I also have the watched/unwatched bug as others already mention.

Fanart.tv and image caching seemed to took longer than what I'm used to, but that could be the database lock I don't know.

**Comment by croneter** [comment]
Sorry, I cannot track this error down. I need the log for it, even if debug logging is not enabled.

**Comment by croneter** [comment]
Looking good?

**Comment by coz2001** [comment]
No more database lock, but I noticed yesterday when adding a movie it synced but no poster/artwork showed up.

**Comment by coz2001** [comment]
I raised a new issue for the missing artwork, you can close this I haven't seen any database locked errors with 2.5.13, thanks....

**Comment by coz2001** [comment]
I still experience database lock error, here's a log but not with debug activated.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2752609/kodi.log)

**Comment by croneter** [comment]
OK, further improved the database interactions. How about 2.5.15?

**Comment by coz2001** [comment]
I haven't seen any database locked with the latest version, so I do believe this can be closed 👍

**Comment by craZy-C** [comment]
No logs yet i will test, experienced a database lock on v2.5.12 out of the blue, did the upgrade to 2.5.16 and sync performed well until a database lock occured, may have to keep open for now. The database lock error message only appears for a few seconds

**Comment by croneter** [comment]
@craZy-C 
I cannot do anything without logs in this case - you still got the one? Debug mode might not even be necessary

**Comment by craZy-C** [comment]
@croneter Still haven't had a chance to check logs but all seems fine, it is adding new shows and movies without  problem, automatically added 6 today while at work. Will check and add logs if i see it happen again.

**Comment by coz2001** [comment]
This issue is still ongoing, turned on the Kodi/shield after sleep and briefly saw the database lock error.
There are many other errors in the log are those some I should worry about?

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2762446/kodi.log)

**Comment by croneter** [comment]
2.5.18 better?

**Comment by craZy-C** [comment]
@croneter At present I am still running 2.5.16 and seems pretty stable, haven't seen any database locks for a while, all syncing is working okay, no missed shows. On rare occasions when starting a show it can take a moment to buffer.  I will keep monitoring and keep it on 2.5.16 for now

**Comment by croneter** [comment]
Thanks for the info, @craZy-C . Buffering on playback start is entirely up to the PMS (e.g. startup of streaming) or Kodi; nothing PKC can do. 

I did have another Locked DB last night 😢 . Still leaving this open for now.

**Comment by coz2001** [comment]
Me too sadly.
If it is any help here's the log

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2772678/kodi.log)

**Comment by Norien** [comment]
Database locked up on me this morning, Last night wife was unable to play anything at all

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2773589/kodi.log)

**Comment by croneter** [comment]
I hope the brand new version 2.5.20 will solve this - once and for all!

**Comment by coz2001** [comment]
Update and testing....

**Comment by craZy-C** [comment]
Hopes it does as well, 1 database lock up in 48hrs otherwise working fine. still sitting stable on 2.5.16, will wait to hear  reports on 2.5.20

**Comment by coz2001** [comment]
So far so good, crossing fingers.
@craZy-C I don't get the reason why you are staying on 2.5.16 when clearly there are issues and if you wan't to help croneter you should update to his latest so we can confirm if the issue is solved or not so new changes can be made if not.

**Comment by craZy-C** [comment]
@coz2001 only reason I was staying on that was for the better part it was stable only having two database locks since setup, i was waiting to see if any other issues arose before updating. Rule 101 in my book if it aint broke don't touch it. :P will do an update shortly and fingers crossed nothing new pops up

**Comment by croneter** [comment]
Thanks @craZy-C! Try and restart Kodi, then search for updates

**Comment by craZy-C** [comment]
@croneter . had only just turned it on, did a restart and still only 19. will try again in 10m

**Comment by craZy-C** [comment]
Okay v20 has shown up, strangely enough it did not request my to refresh to database, will do so anyway

**Comment by craZy-C** [comment]
Smooth Sailing so far, no DB lock Up, crashes or missing titles

**Comment by coz2001** [comment]
Me to...

**Comment by craZy-C** [comment]
@croneter . Just a quick query, With every patch release is it necessary to reset the database.

**Comment by coz2001** [comment]
Only if croneter says it in the release notes.

**Comment by craZy-C** [comment]
@coz2001 Having one of those blonde days, been reading over release notes and change logs and cannot see reset or not on any.  did you reset on applying 2.5.21

**Comment by croneter** [comment]
No need to reset for e.g. 2.5.19-21. Have you encountered any more locked databases?

**Comment by coz2001** [comment]
No I did not reset updating to 2.5.21.
If you look at release 2.5.12 you had to reset. https://github.com/croneter/PlexKodiConnect/releases

**Comment by coz2001** [comment]
Looking good so far no DB locks here, but only time will tell if it's completely solved.

**Comment by craZy-C** [comment]
Cheers, also still going strong here, even with the occasional blonde moment :P

**Comment by croneter** [comment]
How is it looking? Any locked databases?

**Comment by coz2001** [comment]
No, I haven't seen any 🤞😀
