### ISSUE TITLE
Beta 2.5.x: Playback not starting 

### ISSUE THREAD

**Issue by milnash** [croneter/PlexKodiConnect#595]
Device: Nvidia Shield
Kodi Krypton 17.6
PKC version: 2.5.12
Problem: Playback is not starting. Just busy spinner and no error message. Worked in 2.5.11. I have tried with both movies and tv shows - same error.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2730825/kodi.log)

**Comment by milnash** [comment]
In the settings of PKC, under show syncing progress, I enabled show progress and play user state or something like that and I saw it was still progressing ALL tv episodes really slow. Hopefully it got done over night and works now.

Will get back with report.

**Comment by croneter** [comment]
Should be solved in beta 2.5.13

**Comment by milnash** [comment]
Nope, same thing. Will let Kodi on over the night and try again tomorrow. Maybe it's doing something in the background.

**Comment by croneter** [comment]
You might have to reset the database
