### ISSUE TITLE
Kodi 18 RC4: TV Shows not synched anymore

### ISSUE THREAD

**Issue by herrwusel** [croneter/PlexKodiConnect#597]
Lately PKC doesn't sync shows anymore. Arrested Development has 3 episodes for example but they don't show up in Kodi. I can find them in PKC when I go to 'Browse by folder'. I tried a full reset of PKC already without success.
Here is my [kodi.log](https://privatebin.net/?2f9a834740570563#LpMfbOIwR8M2qwTa9uc3uo7ud+X5rlJjlp6JIQSmBz4=)

**Edit by croneter:**
# Workaround
Use PKC beta version >2.5.9

**Comment by kocane** [comment]
For the record, I am also experiencing this.

**Comment by kat953162** [comment]
#586  herrwusel kocane see the instructions croneter posted.

**Comment by kocane** [comment]
@kat953162 must be having another issue then, cause my TV shows library is and has always been set to "show" seasons. I'll see about producing some logs if possible.

**Comment by herrwusel** [comment]
@kat953162 Same here as @kocane. I had the option always like mentioned in the issue.

@croneter: what does the title change mean? Are you aware of this issue and it will be fixed in beta or should we try the beta already? Thanks!

**Comment by croneter** [comment]
I thought this was a bug of PKC **BETA** version 2.5.x only? Is this the case?

**Comment by herrwusel** [comment]
No, I experienced this with the stable version:
```repository.plexkodiconnect v1.0.2 installed```

Now I installed the beta and there it is back to normal. Btw newly added movies also didnt appear in PKC.

**Comment by MacQwerty** [comment]
I encountered the same problem with Kodi 18 RC4 while using the stable version and changing the channel to beta fixed it (as expected given v. 2.5.9 added compatibility with Kodi 18 RC4). There will probably be several more similar bug reports in the close future as people want to use KODI 18 RC, LibreELEC, CoreELEC etc while following the PKC stable release channel to prevent resetting Kodi DB for every beta update where it's needed.

So, I highly advice to update the stable version to add compatibility for Kodi 18 RC4 in the next days as some people might think PKC is not working while using the stable channel with KODI RC (y)

**Comment by milnash** [comment]
Why not use 2.5.11? The database change was made on 2.5.12?

**Comment by herrwusel** [comment]
@MacQwerty Thanks for clarifying! I close this for now since it's not PKC's fault.

**Comment by croneter** [comment]
I'm reopening this issue as other users are affected for sure, thinking it's PKC "fault" ;-)
