### ISSUE TITLE
Titan Skin: Playback Error

### ISSUE THREAD

**Issue by starman2908** [croneter/PlexKodiConnect#599]
Sorry that post's links didnt work on plex forums earlier. I have installed titan skin, and the PKC 2.5.13 addon is synching perfectly in startup, but I can’t initiate play playback. The interesting thing is that items play when I switch to estuary …wonder if you mind taking a look at the logs as I’m stumped.
[KODI KRYPTON STABLE PCK crash.log](https://github.com/croneter/PlexKodiConnect/files/2747649/KODI.KRYPTON.STABLE.PCK.crash.log)
[KODI KRYPTON STABLE PCK not loading media.log](https://github.com/croneter/PlexKodiConnect/files/2747650/KODI.KRYPTON.STABLE.PCK.not.loading.media.log)

UPDATE: May have found something, I disabled "image cache during playback" under the artwork section of settings, and its playing media now. Wonder if i managed playback before the artwork process had started in estuary.  

I also encountered this on Kodi 18RC4 on the spare machine i've been testing for PKC and other betas, and media wouldn't playback on Estuary or Titan MOD Skins... but disabling the same option resolved it. I can try and recreate tomorrow if you want a log for Leia as well.

**Comment by starman2908** [comment]
Here is the log for leia, unfortunately the problem has persisted even with that setting unchecked mentioned above on 5kodi 17.6 and 18 rc4 & Here is the log for 18: 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2749489/kodi.log)

**Comment by MacQwerty** [comment]
I highly advice you to NOT use the Titan skin until it's updated for the final version of Kodi 18 as it is outdated. So, use the default skin or some modifications of it as [Estuary MOD V2](https://forum.kodi.tv/showthread.php?tid=306757) which I use 👍

**Comment by croneter** [comment]
I don't see anything suspicious in the logs you uploaded, @starman2908 

Try resetting the Kodi database in the PKC settings under Advanced (answering Yes, No).

If it still does not work: Could you please share a debug log of your clean build, reproducing the issue?

**Comment by Norien** [comment]
i'm unable to start playback now, tried several files
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2753205/kodi.log)

**Comment by Norien** [comment]
Seems to be tied to titan skin for me as well, default skin plays right away

**Comment by starman2908** [comment]
@croneter Just did a fresh install on Leia RC5.2 (WIN10) with PKC 2.5.16 , good news is my local server is running great, very fast sync, artwork download and play back... Kudos!! 

I'm experiencing issues with a remote server still. After doing another clean install and selecting the remote server, the sync was super fast (like over 120, 000 items in about 15 mins). After sync, and on restarting kodi after sync, I get no success in playback, as in it just hangs until i cancel or kodi crashes - here is that log 
[kodi no playback.log](https://github.com/croneter/PlexKodiConnect/files/2753772/kodi.no.playback.log)

What's wierd is, if i catch PKC while still syncing on startup, i can playback a file before the sync process completes.. ... on stopping playback it just hangs and crashes kodi. Here is that log - 
[kodi playback before sync process ends.log](https://github.com/croneter/PlexKodiConnect/files/2753774/kodi.playback.before.sync.process.ends.log)

Both instances was the same media item (Film - 127 Hours)

Cheers, 

Ryan

**Comment by mow4cash** [comment]
I'm seeing this issue as well with titan mod leia skin, unable to play. No issues playing with Estuary.

**Comment by Norien** [comment]
I'm not sure why but rebooting the entire box seems to correct the issue temporarily. At least for me. I'm now getting database locked as well as no playback described above.

**Comment by croneter** [comment]
@starman2908 
Does 2.5.19 help?

**Comment by starman2908** [comment]
@croneter Bingo!! Reset the database, playback is only taking a couple of seconds to load media now. Great stuff and very well done!!! :) 

Stopping playback is still causing a hang which crashes kodi, here is the log:

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2772194/kodi.log)

I'm gonna let something play through to the end to see if the behaviour changes and I'll post another log...bout half an hour matey.

Cheers

**Comment by starman2908** [comment]
@croneter I've just let an item play through to see if it would stop naturally, no luck i'm afraid, similar behaviour as described above. I can't share the log as its 570MB, so hopefully the one above may shed some light. 

As for playback, all seems working and loading fine. Thanks for your hard work on this.

**Comment by croneter** [comment]
@starman2908 
Nothing suspicious in your logs regarding stopping playback - nothing I can do for now. Let's hope the Kodi team fixes this in Kodi 18 stable...
