### ISSUE TITLE
OSX+DSM, reporting stability

### ISSUE THREAD

**Issue by aglv** [croneter/PlexKodiConnect#6]
I've been running PlexKodiConnect in the last few weeks. I run the latest stable versions of Kodi and PMS. Hardware: Macmini4,1, Synology DS412+

When new versions of PKC come out I test them. If things don't work properly, I revert to the previous version that worked for me. I intend to report future versions success/failure to this issue, if you're not interested in this, just close it :)

~~Currently, the latest working version with my setup is v1.1.2.~~
* ~~v1.1.4: Worked for a few hours (after install and db refresh), then started firing "couldn't find next item to play" and other error messages.~~
* ~~v1.1.3: same as v1.1.4.~~

> UPDATE: My setup wasn't working because somehow I had Transcoding enabled in the PlexKodiConnect settings. Everything is working properly with the following settings:
> * Preferred playback method: Direct Play (default)
> * Video Quality for Transcoding: 1920x1080, 40 Mbps
> * Force transcode H265: Fisabled (default)
>
>So, **v1.1.4 works with my setup**, and even better after setting up SMB direct access to the NAS.

~~I haven't set up direct file access, in any version.~~

I realize this isn't a full bug report. I'm not sure how to access the Kodi/PKC logs you'd be interested in. If you want more detailed information, please point me to some documentation explaining how to obtain the logs.

**Comment by TimDowker** [comment]
I appreciate this. Good to know latest working versions for people.

**Comment by croneter** [comment]
Thanks for your time to test, really appreciated. You are right - I can't do anything without log files. Please see here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#report-using-a-log-file

Do post your log file here though, not in the plex forums ;-)

**Comment by aglv** [comment]
Log file: [pkc1.1.4.txt](https://github.com/croneter/PlexKodiConnect/files/234096/pkc1.1.4.txt)
* Installed PKC v1.1.4,
* Reset kodi DB (not settings, not artwork cache)
* Relaunched Kodi, database refresh (took a few mins)
* Reset kodi.log to empty file (manually), so the file you have attached here is shorter
* Relaunched Kodi, browsed to a movie, got the 'can't find next item to play' error message (in bottom popup box), tried again, same error, tried again, same error (but in alert box).
* Switched to a show, tried playing, stuck on 'Opening stream' alert/dialog box.

**Comment by croneter** [comment]
Thanks! 

You have transcoding enabled. Really quick fix for now: go to PKC settings, playback, "video quality". Choose 1920x1080, 40 Mbps. 

Does that solve your issues?

**Comment by aglv** [comment]
This seems to work :) Thank you! No idea why transcoding was on though, I'm aware my NAS couldn't handle transcoding, so I don't think I ever enabled that. I updated the initial issue with updated info 👍

**Comment by aglv** [comment]
I'm reopening this: playing stops after a few minutes using the corrected setup. Log file linked, look towards the end of it.
[stuck-v1.1.4.txt](https://github.com/croneter/PlexKodiConnect/files/234597/stuck-v1.1.4.txt)

**Comment by croneter** [comment]
Seems like your NAS really does not have a lot of CPU. There is a malformed message from PKC about where you're currently at in the movie (playstate update). This causes the PMS to stall: 
```
15:11:52 T:123145308819456  NOTICE: PlexKodiConnect WebSocket -> run : Connection closed, (re)connecting
15:11:52 T:123145308819456  NOTICE: PlexKodiConnect WebSocket -> run : Error connecting
...
15:12:12 T:123145303990272   ERROR: PlexKodiConnect DownloadUtils -> downloadUrl : Server unreachable at: http://192.168.178.26:32400/library/metadata/9339?includePopularLeaves=1&includeExtras=1&includeChapters=1&includeConcerts=1&checkFiles=1
15:12:12 T:123145303990272  NOTICE: PlexKodiConnect DownloadUtils -> downloadUrl : HTTPConnectionPool(host='192.168.178.26', port=32400): Max retries exceeded with url: /library/metadata/9339?includePopularLeaves=1&includeExtras=1&includeChapters=1&includeConcerts=1&checkFiles=1 (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fb0a8d22150>: Failed to establish a new connection: [Errno 61] Connection refused',))
15:12:12 T:123145303990272   ERROR: PlexKodiConnect DownloadUtils -> downloadUrl : Failed to connect to http://192.168.178.26:32400/library/metadata/9339?includePopularLeaves=1&includeExtras=1&includeChapters=1&includeConcerts=1&checkFiles=1 too many times. Declare PMS dead
15:12:12 T:123145303990272   ERROR: PlexKodiConnect PlexFunctions -> doPlayback : Error retrieving metadata for {server}/library/metadata/9339?includePopularLeaves=1&includeExtras=1&includeChapters=1&includeConcerts=1&checkFiles=1
```
Which kills the playback at some point. 

I hope to fix this in the next PKC release.

**Comment by aglv** [comment]
I fixed this by setting up direct SMB access
