### ISSUE TITLE
LibrarySync thread crashed. Error message: no such table: path

### ISSUE THREAD

**Issue by JingenChen** [croneter/PlexKodiConnect#601]
Library sync thread always crashed, restarting Kodi won't help.
https://pastebin.com/cG9kd6tq

**Comment by MacQwerty** [comment]
You are using PKC v.2.4.11 which is NOT compatible with Kodi 18 RC4... Use the beta release channel and update to the latest release (v.2.5.13)

**Comment by croneter** [comment]
Version 2.5.x REALLY changes a lot and I want to be sure that there are no major bugs left. I hope the current 2.5.13 is now pretty-much bug-free

**Comment by MacQwerty** [comment]
Yeah, I know :) And it has been several days now without issues related to the latest version, 2.5.13, so it's looking good 👍
