### ISSUE TITLE
Crash when browsing episodes

### ISSUE THREAD

**Issue by JingenChen** [croneter/PlexKodiConnect#603]
23:07:16.727 T:123145384480768   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'kodi_fileid'
                                            Traceback (most recent call last):
                                              File "/Users/jingen/Library/Application Support/Kodi/addons/plugin.video.plexkodiconnect/resources/lib/kodimonitor.py", line 89, in onNotification
                                                _playback_cleanup()
                                              File "/Users/jingen/Library/Application Support/Kodi/addons/plugin.video.plexkodiconnect/resources/lib/kodimonitor.py", line 436, in _playback_cleanup
                                                _record_playstate(status, ended)
                                              File "/Users/jingen/Library/Application Support/Kodi/addons/plugin.video.plexkodiconnect/resources/lib/kodimonitor.py", line 486, in _record_playstate
                                                kodidb.set_resume(db_item['kodi_fileid'],
                                            KeyError: u'kodi_fileid'
                                            -->End of Python script error report<--

https://pastebin.com/7S4YV8Ta

**Comment by croneter** [comment]
How exactly did you start your playback?!?

**Comment by croneter** [comment]
Please try updating to the latest "official" Kodi Release Candidate 5.2 for Kodi 18 first: https://kodi.tv/download

Still an issue?

**Comment by JingenChen** [comment]
Yes, issue still exists even after updating to RC 5.2. The crash happened when I click the "Browse" icon from information page of TV show.

<img width="648" alt="2019-01-15 09 11 14" src="https://user-images.githubusercontent.com/7324423/51151549-561eaf00-18a6-11e9-914e-b97abd3ca2fd.png">

**Comment by zonly1** [comment]
I get this issue with tv shows if I set Default Select Action > Show Information. If I set it to play, it works as it should. If that can be fixed, it would be great as I prefer it instead of play for browsing movies.

**Comment by croneter** [comment]
Does beta version 2.5.19 help?

**Comment by zonly1** [comment]
It did not fix it for me. It does not crash Kodi but if I click browse (from TV Shows widgets), it goes back to the main screen instead of going into the TV Show. It works as expected from the TV Shows menu itself but not  from the widgets.

**Comment by croneter** [comment]
Does beta version 2.5.20 help?

**Comment by zonly1** [comment]
Yes, helps a lot. It works fine now but when you back out to the main menu, it goes up to the video node which means two extra back presses but other than that, it’s working. Thanks croneter.
