### ISSUE TITLE
PKC Errors (check log & -1)

### ISSUE THREAD

**Issue by coz2001** [croneter/PlexKodiConnect#604]
RC5.2 and 12.5.15, I got these 2 errors after 1-2 mins of uptime.

Let me now if you need debug on.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2753243/kodi.log)

**Comment by coz2001** [comment]
Now that debug is on then of course -1 won't show it self.

Your right it did show simply as -1.

**Comment by coz2001** [comment]
2.5.16 fixed the errors, I will get back if -1 should return.

Thanks for the fast & sublime work you put into this, it's much appreciated😉

**Comment by croneter** [comment]
-1 (actually an invalid PMS message!) won't show up again, I made sure of that :wink:

You're very welcome!
