### ISSUE TITLE
Wrong episode or movie playing

### ISSUE THREAD

**Issue by imbaimbaimba** [croneter/PlexKodiConnect#607]
Hey guys,

Often having this issue where it will play the episode before the one I select. It is super annoying, as it often takes a while to realize you are rewatching the episode you just seen. 

Is this something known that I can fix?

**Comment by croneter** [comment]
Try to reset the Kodi database in the PKC settings under Advanced, then Reset the Kodi database, then Yes and No. 

If that does not work, share your DEBUG log of the issue happening, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by imbaimbaimba** [comment]
Hi @croneter
Thank you for answering. Actually, I forgot to mention, the issue only pretty recently started occurring. It was working fine before that. I did a complete network reinstall with new cables, router, switch, everything and in that process my media setup broke. Therefore I did just that, I did a reset on PKC completely, set everything back up and after that the issue has been there.

Could I have done something wrong in that process? And does that change what I need to try now? I’ll give it a go, just wanted to tell you I just realized when it started happening.

**Comment by Norien** [comment]
You're not alone. I'm seeing this issue as well which just started happening within the last couple versions

**Comment by croneter** [comment]
Logs?!

**Comment by croneter** [comment]
Please just enable debug logging and reproduce the issue, then share the log here (redact your Plex token!)

**Comment by croneter** [comment]
No log no help - I cannot read minds. Please try to reproduce the issue and capture that in a Kodi log file as described here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Is this still an issue? If so, I need logs. I cannot reproduce the issue currently myself...

**Comment by croneter** [comment]
OK, found the issue. Really, really obscure in the way Kodi & Python interact 🙄
