### ISSUE TITLE
Transcoding music doesn't work

### ISSUE THREAD

**Issue by kouinou** [croneter/PlexKodiConnect#609]
Hello everybody,

It seems that music transcoding doesn't work with Plex Kodi Connect. I am not sure whether this is a plex or a PKC issue, because it works fine when using official Android Plex app.

I first thought that this was due to the fact that there wasn't an existing profile for PKC so I created a client profile for PKC (that I called Linux.xml) that I placed in the right profile directory on Plex server side. I specified in this file that I wanted my musics to be transcoded in a lower bitrates (192kbps) but my flac files are still played without transcription which is an issue when using mobile data.

Has anyone managed to resolve this ? Maybe it is a configuration issue on my side I didn't do well...

kouinou

**Comment by croneter** [comment]
It's not an issue. It's a feature request 😉. PKC currently simply does not support transcoding of music - because it'd be a hack to figure out how it's done and because I guess not many people will use it. 

Please open a feature request here: http://feathub.com/croneter/PlexKodiConnect

**Comment by kouinou** [comment]
Hi,

Thank you for your quick answer, I will do as you said ans cross my fingers that some other people will ne interested by this évolution !

Thank you for all your work :)
