### ISSUE TITLE
Using Alexa to resume movie starts at beginning

### ISSUE THREAD

**Issue by spamies1** [croneter/PlexKodiConnect#610]
https://forums.plex.tv/t/alexa-resume-movie-doesnt-work/303152

Using the alexa skill for plex everything works except resuming movies. alexa asks me if I want to resume I say yes, alexa says ok resuming... but then the movie starts from the beginning. 

This has been an issue for a long time, finally got a debug log. 

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2771228/kodi.log)

**Comment by spamies1** [comment]
seems this is a common issue.

https://github.com/d8ahazard/Phlex/issues/87

**Comment by croneter** [comment]
Is this still an issue?

**Comment by croneter** [comment]
Let me know here if this is still an issue
