### ISSUE TITLE
Image caching fails over https - Kodi RC 5.2 Beta 2.5.19

### ISSUE THREAD

**Issue by JBeresford** [croneter/PlexKodiConnect#611]
I've recently tested upgrading to RC 5.2 from my existing Krypton instance. However on RC 5.2 image caching refuses to work over https and continuously throws the following error in the log:
`ERROR: CCurlFile::Stat - Failed: SSL peer certificate or SSH remote key was not OK(51)`

This happens for an upgraded DB (but I keep my images) see attached log
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2775451/kodi.log)

This also occurs for me on a fresh RC 5.2 install which beta 2.5.19 or if I run a full PKC DB reset.

If I turn of the requirement of https in the settings then everything caches as expected.

**Comment by croneter** [comment]
Try and reconnect to your PMS: 
* go to the PKC settings, then Connection. Let your PMS' be listed. Select **ANOTHER** PMS. Let PKC connect. 
* Then reconnect to your original PMS again
* After you've done that, you need to reset your Kodi database: in the PKC settings under Advanced, select Reset the Kodi database. Hit Yes, then No

**Comment by JBeresford** [comment]
The above steps have flushed everything through on my FireTV instances and everything is back up and running. So happy days  :)

However the Mac client which I provided the log from is still not playing ball at all. I suspect there's a Kodi bug in here somewhere. I've completely removed Kodi and the caches from the system and it happens on a completely blank install.
Additionally when I do a reset it, it empties the Database but Kodi doesn't restart it just sits there.

Happy to close this since my main devices are working, so it doesn't look like its PKC (unless you disagree). Thanks for you help

**Comment by JBeresford** [comment]
Just in case anyone looks at this in the future basis the error - I think I've finally got to the bottom of what was going on. I had an IP Address conflict on my subnets, the afore mentioned FireTVs were on a different one to my Macbook. I swapped my Plex Server over to DHCP and it's been smooth sailing since
