### ISSUE TITLE
Feature Request: Disable the syncing of certain libraries.

### ISSUE THREAD

**Issue by danjames92** [croneter/PlexKodiConnect#612]
Feature Request: the ability to disable the syncing of certain libraries.

I have a couple of trakt based libraries that update very regularly (think #trending tv, #trending movies)

They are just for my friends and not for myself. I have no use for them when using PKC myself.

Any chance of this being possible?

**Comment by croneter** [comment]
Already on the radar: https://feathub.com/croneter/PlexKodiConnect/+13

**Comment by danjames92** [comment]
@croneter does that mean it's coming?

the feature request is very old and I saw you closed another thread so I assumed it was out of scope.

**Comment by croneter** [comment]
The feature request is old because it needs a ton of work and even some skinning work - where I'm not really the expert 😢
