### ISSUE TITLE
AttributeError: 'KodiVideoDB' object has no attribute 'kodiconn'

### ISSUE THREAD

**Issue by spamies1** [croneter/PlexKodiConnect#614]
New DB error message after leaving kodi running overnight.

 ERROR: PLEX.utils:     AttributeError: 'KodiVideoDB' object has no attribute 'kodiconn'

Non-debug log attached.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2776883/kodi.log)

**Comment by croneter** [comment]
Should be solved with 2.5.21
