### ISSUE TITLE
Problem with NULL_VIDEO

### ISSUE THREAD

**Issue by SKrab91** [croneter/PlexKodiConnect#617]
Hi to all!

I had a problem with the NULL_VIDEO (the screen only went black and nothing happend until i canceled the playback - after that the right video file started).
I changed the "empty_video.mp4" filte to an black-video with less than a second lenght - now it seems to work.
But it is still annoying that first a black video file will be started and after that PKC returns to the menu and than it starts the correct video.

Is it possible to skip the "NULL_VIDEO" so that Kodi can start the correct video file directly?

**Comment by croneter** [comment]
Please use the beta version of PKC if you're in a hurry - the next PKC update won't involve an empty video file.

Or wait a couple of days for stable to update
