### ISSUE TITLE
Problem with Playback/Hang after Selecting Epsiode

### ISSUE THREAD

**Issue by BlackMamba248** [croneter/PlexKodiConnect#620]
Hello, I'm using the newest Beta 2.5.22 and have been having this issue since 2.5.18/19 I think. Usually whenever I click an episode for playback, there's a brief pause with the spinning circle to wait and then it disappears and nothing happens. If I select the episode again to play, it'll hang at the spinning circle for awhile and then will get the error saying cannot playback. Also sometimes after selecting an episode to play, it'll will start the episode and then automatically stop or start the episode with it playing as usual except the error no playback will pop up in the middle of the screen and once clicking to get rid of the error, the playback stops with it. I have this issue both in my current build with doing a full reset as well as doing a fresh start for kodi and installing Beta 2.5.22. Attached my logs at the bottom, hopefully was able to get the logs properly

[Log for playback error:hang.html.zip](https://github.com/croneter/PlexKodiConnect/files/2798901/Log.for.playback.error.hang.html.zip)

**Comment by croneter** [comment]
Do you have some kind of special Kodi build? Or are you using an "official" build from www.kodi.tv/download? 

I'm using Kodi 17.6 on a daily basis - no issues 🙄

**Comment by croneter** [comment]
Did you try to reset the database in the PKC under Advanced?

**Comment by BlackMamba248** [comment]
I'm using arctic zephyr plus as my build, it's been working fine earlier. I also did reset the database so i'm not sure if it's a problem on my end or not

**Comment by croneter** [comment]
Could it be that you've been messing with the PKC settings for direct paths and add-on paths?
```
NOTICE: PLEX.playutils: The playurl is: /storage/BRYANNAS251/BP-2/NVIDIA_SHIELD/Anime/Date A Live/Season 2/S02E10 - Inversion 1080p HD.mkv
```
PKC tries to direct play using the LOCAL path `/storage/BRYANNAS251/BP-2/NVIDIA_SHIELD/Anime/Date A Live/Season 2/S02E10 - Inversion 1080p HD.mkv`. 

Please try the following:
* Make sure that Kodi debug logging is enabled
* In the PKC settings under `Sync`, tripple check that Add-on Paths are set (not Direct Paths)
* Under `Advanced`, reset the Kodi database again (in red). Hit Yes, then No. 
* Reboot and resync
* Try to play a video again
* If it still does not work, please share the log file again

**Comment by croneter** [comment]
Does it work if you change the "Preferred playback method" to "Direct Stream" in the PKC settings under Playback?

**Comment by BlackMamba248** [comment]
I did try switching from direct play to direct stream in preferred playback method but it's about the same as before. What I now notice is that it does play, it just takes a long time for some reason to start. I click on an episode once, and it'll display the spinning circle with please wait for a sec and then disappear. After the spinning wheel initially disappears, I'm able to move the cursor and try to click and play the episode again (this leads to please wait spinning circle.  If I wait instead of trying to click to play the episode again, anywhere from a couple of seconds to maybe up over 60 seconds, it'll start showing the spinning circle and eventually plays or sometimes the playback error. I'm not entirely sure but I'm guessing the playback error sometime could be due to trying to play the episode again after the initial click?

**Comment by croneter** [comment]
If I did not know better, I'd say that you're using a really weak CPU for Kodi. 
```
14:59:22.469 T:192319247600  NOTICE: PLEX.playback: playback_triage called with plex_id 7264, plex_type episode, path None, resolve True
14:59:22.661 T:192319247600   DEBUG: PLEX.playback: Playing trailers: False
14:59:22.662 T:192319247600   DEBUG: PLEX.playlist_func: Playlist cleared: {'playlistid': 1, 'id': None, 'version': None, 'type': 'video', 'selectedItemID': None, 'selectedItemOffset': None, 'shuffled': 0, 'repeat': 0, 'kodi_playlist_playback': False, 'pkc_edit': False, 'items': []}
...
(Push playqueue to the PMS)
...
14:59:24.715 T:192319247600   DEBUG: PLEX.playlist_func: Updated playlist from xml: {'playlistid': 1, 'id': 2931, 'version': 1, 'type': 'video', 'selectedItemID': 13789, 'selectedItemOffset': 0, 'shuffled': 0, 'repeat': 0, 'kodi_playlist_playback': False, 'pkc_edit': False, 'items': []}
...
(Taking 13 seconds)
...
14:59:37.138 T:192319247600   DEBUG: PLEX.playlist_func: Insert listitem at position 1 for Kodi only for {'playlistid': 1, 'id': 2931, 'version': 1, 'type': 'video', 'selectedItemID': 13789, 'selectedItemOffset': 0, 'shuffled': 0, 'repeat': 0, 'kodi_playlist_playback': False, 'pkc_edit': False, 'items': []}
...
(Taking 12 seconds)
...
14:59:49.913 T:192319247600   DEBUG: PLEX.playlist_func: Created new playlist item from xml: {'id': 13789, 'plex_id': 7264, 'plex_type': 'episode', 'plex_uuid': 'None', 'kodi_id': 11106, 'kodi_type': 'episode', 'file': 'None', 'uri': 'None', 'guid': 'com.plexapp.agents.thetvdb://257765/2/19?lang=en', 'playmethod': 'None', 'playcount': 0, 'offset': 0.0, 'force_transcode': False, 'part': 0, 'xml': "<Element 'Video' at 0x2cb9367360>"}
```
This should be lightning fast!

Anything CPU-intensive you're doing with your shield at the same time?

**Comment by croneter** [comment]
In the PKC settings under `Sync`, what is `Number of simultaneous download threads` set to? Please set them to 10

**Comment by BlackMamba248** [comment]
Yup, it's been set at 10 for simultaneous downloads, constant background sync is also enabled if that has anything to do with the problem? 

Nothing I can think of, I usually close most of the other applications when I open up kodi to watch. Is there any way to determine the cpu usage at the time of playing something from PKC? I checked just know under system info and CPU usage is 0  atm.

**Comment by croneter** [comment]
I hope I found the problem - thanks for this really important bug report!!

Does the brand new version 2.5.23 help? Do restart after the PKC update, then immediately try to play something 😉

**Comment by Norien** [comment]
So far this seems to be fixed for me. Playback is much much faster and I haven't had one hang for 10 mins yet like I did before.

**Comment by BlackMamba248** [comment]
Just updated, reset, and tested real quick and the playback problem is gone! Thanks a lot croneter for the speedy fix. I wonder what the issue was, thought I was the only one being affected since didn't see any issue reports
