### ISSUE TITLE
Fire Stick 4K Library Sync Thread has Crashed

### ISSUE THREAD

**Issue by louisefindlay23** [croneter/PlexKodiConnect#629]
On my new Firestick 4K, when I install PlexKodiConnect on the inital sync it says the library sync thread has crashed. I've lowered the sync threads and items fetched to 1 and disable the artwork caching but it still happens.

Logs: https://paste.kodi.tv/usuhirikuf

Relevant log section, I think: `ERROR: PLEX.librarysync: LibrarySync thread crashed. Error message: no such table: path 21:41:34.285 T:2132957472 ERROR: PLEX.librarysync: Traceback: Traceback (most recent call last): File “/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py”, line 1500, in run self._run_internal() File “/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/librarysync.py”, line 1547, in _run_internal kodi_db.setup_path_table() File “/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/kodidb_functions.py”, line 63, in setup_path_table path_id = self.get_path(‘plugin://%s.movies/‘ % v.ADDON_ID) File “/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/kodidb_functions.py”, line 185, in get_path (path,)) OperationalError: no such table: path 21:41:34.306 T:18446744071901808928 DEBUG: —— Window Init (/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/skins/Main/1080i/script-plex-options_dialog.xml) —— 21:41:34.306 T:18446744071901808928 INFO: Loading skin file: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.plexkodiconnect/resources/skins/Main/1080i/script-plex-options_dialog.xml, load type: LOAD_ON_GUI_INIT 21:41:34.327 T:18446744071901808928 ERROR: Control 1001 in window 13000 has been asked to focus, but it can’t 21:41:34.361 T:2135046432 DEBUG: Thread Timer 2135046432 terminating`

**Comment by croneter** [comment]
You seem to have a funky Kodi version installed from https://android.googlesource.com/toolchain/clang. The Kodi database looks different than it should, an entire table is missing. 
```
NOTICE: Kodi compiled 2018-12-28 by Clang 7.0.2 (https://android.googlesource.com/toolchain/clang 003100370607242ddd5815e4a043907ea9004281) (https://android.googlesource.com/toolchain/llvm 1d739ffb0366421d383e04ff80ec2ee591315116) for Android ARM 32-bit API level 21 (API level 21)
```
Kodi Nightly versions are NOT support by PKC (likely your Kodi build is based on some nightly version) because stuff like this tends to happen and there's nothing PKC can do to fix it. 

Please get an "official" Kodi 18 Release Candidate (5.2 is current, not 4) or use Kodi 17.6 stable.

**Comment by louisefindlay23** [comment]
I installed the RC 5 from kodi.tv using the Downloader app and it still says Library sync thread has crashed.

**Comment by croneter** [comment]
I'm using RC 5.2 here - no issue. Can you please post the exact link you used?

**Comment by MacQwerty** [comment]
@louisefindlay23, don't bother using Kodi on Android as it is a nightmare! Use [LibreELEC](https://forum.libreelec.tv/c), [CoreELEC](https://discourse.coreelec.org) etc. instead! If you also want to use Android, setup dual boot so you can either boot to Android or LibreELEC/CoreELEC and switch between them 👍

**Comment by croneter** [comment]
Sorry @louisefindlay23 for the inconvenience, but there's not much PKC can do if the Kodi databases look entirely different 😞

**Comment by louisefindlay23** [comment]
@MacQwerty I don't think you can use Libreelec on Fire TV

@croneter Using 
http://mirrors.kodi.tv/releases/android/arm/kodi-18.0-Leia_rc5.2-armeabi-v7a.apk is there another source you can suggest?

**Comment by croneter** [comment]
Can you stick to Kodi 17.6? 🙂 That's what I'm testing with using my Android tablet. Kodi stable version 18 is scheduled to be finally released by the end of January - let's hope that the Android builds will improve by then as well...

**Comment by louisefindlay23** [comment]
Got it working with 17.6. Thanks a lot for your patience and help.

**Comment by erkston** [comment]
Just a heads up @croneter: 

Final 18.0 builds are out, and using the apk listed on the official download page (https://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-18.0-Leia-arm64-v8a.apk) with stable PKC gives the same "no such table: path" error described in this thread. The build also still shows "Kodi compiled 2019-01-28 by Clang 7.0.2", seems like they changed something.

Switching to beta PKC seems to be working just fine though :)
