### ISSUE TITLE
Errors in PMS Log: Unable to find client profile

### ISSUE THREAD

**Issue by Panja0** [croneter/PlexKodiConnect#634]
In my Plex logs I'm seeing constant errors when playing media though PlexKodiConnect.

`Unable to find client profile for device; platform=Linux, platformVersion=unknown, device=Linux, model=unknown`

I read I can fix it by adding a PlexKodiConnect.xml file in my Profile Directory.
I stopped the Plex server, copied Generic.xml and renamed it to PlexKodiConnect.xml
Started the Plex server but the problem remains.

PlexKodiConnect v2.4.11
Plex Server: v1.14.1.5488 (Windows)

**Comment by Panja0** [comment]
Ok, I created a debug log.
I don't have Pastbin Pro so I've created 3 links:

Kodi log - 1/3:
https://pastebin.com/7KM7VB3Y

Kodi log - 2/3:
https://pastebin.com/0vyft3Vy

Kodi log - 3/3:
https://pastebin.com/CJV9L7Zy

**Comment by Panja0** [comment]
FYI:
After upgrading to v2.6 the problem remains.

**Comment by Panja0** [comment]
FYI:
After upgrading to v2.6.1 the problem remains.

**Comment by ashleybone** [comment]
The filename you create needs to match the device name in the error message.Copying Generic.xml to Linux.xml should stop the error message.

**Comment by Panja0** [comment]
> The filename you create needs to match the device name in the error message.Copying Generic.xml to Linux.xml should stop the error message.

Cheers! This fixed my problem. Thx

**Comment by croneter** [comment]
Should be solved with PKC BETA version 2.6.6 - without the need to create a `generic.xml`. Let me know if that is not the case

**Comment by Panja0** [comment]
I'm running the stables. So I'll wait until the new stable is released. Thanks for fixing!

**Comment by Panja0** [comment]
Fixed for my now in v2.7.0 (stable).
