### ISSUE TITLE
Scan (1500+ movies) needs several reboots - memory not being freed correctly on new item scan?

### ISSUE THREAD

**Issue by spants** [croneter/PlexKodiConnect#64]
When scanning a movie collection, it consumes memory at an alarming rate for new items downloaded and never seems to free it up for that item once download. It eventually reboots.

I'm using Kodi 16.1 (LibreElec) on a clean system.

Looking at System Info when scanning.

I have set for low power pc (its an acer with 2gb ram)

**Comment by croneter** [comment]
That's a first. Please enable debug logging in the PKC settings -> Advanced. Also enable debug logging in the Kodi settings. Also see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Then try to reproduce the reboots. I think you'd have to get the "crash log" then.

**Comment by croneter** [comment]
Kindly add your logs. Otherwise I cannot help you...

**Comment by spants** [comment]
I will do - I have been away so I have been unable to do so. Thanks for keeping track...

**Comment by croneter** [comment]
Any progress on your logs? ;-)

**Comment by croneter** [comment]
Any update here? Otherwise I'll assume that this issue is solved ;-)

**Comment by spants** [comment]
Hi-have managed to get a log for today. My library scans about 100 new items then crashes.... so it takes about 15+ reboots to restore my library!.
How can I get the logs to you privately as it may contain sensitive info?

**Comment by croneter** [comment]
croneter at google . com ;-)

**Comment by spants** [comment]
sent...
