### ISSUE TITLE
Missing posters

### ISSUE THREAD

**Issue by FezVrasta** [croneter/PlexKodiConnect#656]
Hi, I'm using the most recent version of this plugin. But both on Kodi 17 and 18 I was never able to see the posters of movies and TV shows.

I see a transparent picture instead (blank).

Is there anything I have to do to fix it?

**Comment by croneter** [comment]
You will definitely need to reset the Kodi DB to "load" the poster info into the DB

**Comment by croneter** [comment]
Did that work?

**Comment by FezVrasta** [comment]
I tried what you suggested but I still see the empty posters.

**Comment by croneter** [comment]
Then please first enable Kodi debug logging, then Reset the Kodi database again. Then upload your log file here following https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug
