### ISSUE TITLE
Not able to add plex server

### ISSUE THREAD

**Issue by SuperTrembler** [croneter/PlexKodiConnect#657]
Installed the addon from the repo, but it never asked me to login in to plex.tv as in Krypton.
Also when I try to configre it with "Choose server from list" or "Manully enter..." it just closes the configre window.

Same in Plex pane if I select "Toggle plex.tv login.."

**Comment by croneter** [comment]
Guess what - I need a log: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

I take it that you DID try to reset PKC completely by going to the PKC settings, Advanced, then "Reset the Kodi database...", then YES and again YES.

**Comment by SuperTrembler** [comment]
yup, only thing that worked was going back to 2.4, then upgrading

**Comment by croneter** [comment]
I cannot help without a log file...

**Comment by croneter** [comment]
No log no help. If this is still an issue, please share your log file here. Otherwise I assume this issue has been solved
