### ISSUE TITLE
Transcoding and subtitles together don't work.

### ISSUE THREAD

**Issue by johnnygo1** [croneter/PlexKodiConnect#66]
I have a problem when i use transcoding and subtitles. My htpc isn't fast enough to play X265 files. So I have set in the settings to transcode them. When I try to play a X265 file, i first get a question for the available subtitles. When I select a subtitle, then nothing happends and i return back to kodi, or i got the same question again. When I select none, the file starts playing and transcoding is working fine.
I think this is a PKC issue, since this is only happening using the PKC addon. When i use one of the plex apps (ios/android/playstation), or the old plexbmc, this isn't happening.
Hope someone has a solution for this.
The logfile can be found here: http://paste.ubuntu.com/17552066/

**Comment by ianimacleod** [comment]
I concur, I have seen this on a Pi 3 also.

**Comment by Darkshift228** [comment]
Yeah I need this or i Cant use this app.

**Comment by Insighter2k** [comment]
I still have this problem.
My logfile: https://pastebin.com/W3Yq68mC

Do you need any further information?

**Comment by croneter** [comment]
@Insighter2k 
Please enable PKC debug logging and share the entire Kodi log, not just excerpts.

**Comment by Insighter2k** [comment]
Thanks for the tip. I forgot to enable it.

Hopefully it can help you to analyze the problem. => https://pastebin.com/5sWFtBD9

**Comment by croneter** [comment]
Should be solved by now - let me know if not.

**Comment by croneter** [comment]
At least - didn't find anything suspicious in your log file. If you're still having issues, share your ENTIRE log please, not just excerpts.
Also, in this case, sharing your PMS log with both debug and verbose logging enabled would greatly help (probably nothing showing up on the Kodi side of things)
