### ISSUE TITLE
Reset resume position

### ISSUE THREAD

**Issue by dazedcrazy** [croneter/PlexKodiConnect#661]
![image](https://user-images.githubusercontent.com/9027988/52081436-26ec8b00-2592-11e9-8ca8-d2d614452a8f.png)
I think this is new I don't remember seeing it on Kodi 17. If you reset the resume position using that option when you restart Kodi the resume position goes back to where is was. If it's not a bug can it be a feature request. When I hit ``Reset resume position`` it should mark it unplayed in Plex

**Comment by croneter** [comment]
So what exactly does this do in vanilla Kodi? :laughing:

**Comment by dazedcrazy** [comment]
Basically marks it was unwatched, removes the ``Resume from 00:21:08`` so it plays from the start the next time it plays
![image](https://user-images.githubusercontent.com/9027988/52083524-931dbd80-2597-11e9-92ff-dc2891ca3790.png)

**Comment by croneter** [comment]
Moved to Feathub, where Feature Requests belong: https://feathub.com/croneter/PlexKodiConnect/+48

Do vote there if you think this feature important

**Comment by cyberden** [comment]
The featurehub link does not seem to work. I'm also interested in this feature if it can be done in the future.
