### ISSUE TITLE
Can´t play videos and the covers are not displayed

### ISSUE THREAD

**Issue by AlexSjr** [croneter/PlexKodiConnect#666]
After upgrading to Kodi 18 Leia, I can no longer play any videos and the Plex server covers are not displayed.
This is the application log:
https://pastebin.com/mTbhwi30

**Comment by croneter** [comment]
This is the culprit:
```
ERROR: CCurlFile::Exists - Failed: SSL peer certificate or SSH remote key was not OK(51) for https://192.168.0.8:32400/photo/:/transcode?width=3840&height=3840&minSize=1&upscale=0&url=/library/metadata/1/thumb/1549002943
```
Your PMS' SSL certificate is not valid. The "easy" solution is to follow @tekwarfare 's advice and deactive `Check SSL certificate` in the PKC settings. The harder but much more securer solution is to find out **WHY** the PMS certificate is not valid. 

You did not mind [the instructions](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug) and shared your Plex tokens. Please **IMMEDIATELY** follow [I published my Plex token to some forum or Github. Anyone can now access my Plex Server!](https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug#i-published-my-plex-token-to-some-forum-or-github-anyone-can-now-access-my-plex-server).
