### ISSUE TITLE
Newest Kodi Krypton not reporting playstate update to PMS

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#67]
Log:
```
17:43:08 T:2180 NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnPlay Data: {"item":{"title":"","type":"movies"},"player":{"playerid":1,"speed":1}}
17:43:08 T:2180 NOTICE: PlexKodiConnect KodiMonitor -> Currently playing file is: smb://DISKSTATION/share/TV/Orange Is The New Black/Season 03/Orange Is the New Black - 03x07 - Tongue-Tied.mkv
17:43:08 T:2180 NOTICE: PlexKodiConnect KodiMonitor -> No kodi id passed. Playing itemtype is:
17:43:08 T:2180 NOTICE: PlexKodiConnect KodiMonitor -> Item is invalid for PMS playstate update.
17:43:12 T:2180 ERROR: PlexKodiConnect Player -> Could not find itemId, cancelling playback report!
So it seems it fails to located the itemId, however when you stop the episode it reports
17:44:49 T:2180 NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnStop Data: {"end":false,"item":{"id":3457,"type":"episode"}}
```
Workaround by @im85288 
```
playerid = data["player"]["playerid"]

        # Get details of the playing media
        self.logMsg("Getting details of playing media", 1)
        result = xbmc.executeJSONRPC(
            '{"jsonrpc": "2.0", "id": 1, "method": "Player.GetItem", "params": {"playerid": ' + str(
                playerid) + ', "properties": ["showtitle", "tvshowid", "episode", "season", "playcount"] } }')
        result = unicode(result, 'utf-8', errors='ignore')
        self.logMsg("Got details of playing media" + result, 2)
        kodiID = result["result"]["item"]["tvshowid"]
```

**Comment by croneter** [comment]
@im85288, unfortunately, using JSONRPC did not work if you use video nodes + widgets - Kodi doesn't tell you the id then. Put a hack in place now that uses the filename and path :-/

**Comment by im85288** [comment]
That's a shame but thanks for solving it with the filename hack :)

**Comment by hstamas** [comment]
Still not working for me :( I'm attempting a full database resync just to see if that helps. I wonder why there isn't more chatter about this since if PMS doesn't know that something has been played through PKC won't Kodi and PMS get out of sync?

**Comment by im85288** [comment]
Yes tested too and not working for me either after a full database resync.

The logs show:

`20:05:29 T:1392  NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnPlay Data: {"item":{"title":"","type":"movies"},"player":{"playerid":1,"speed":1}}
20:05:29 T:1392  NOTICE: PlexKodiConnect KodiMonitor -> Currently playing file is: smb://DISKSTATION/share/TV/Black Sails/Season 02/Black Sails - 02x10 - XVIII.mkv
20:05:29 T:1392  NOTICE: PlexKodiConnect KodiMonitor -> Playing itemtype is (or appears to be): movies
20:05:29 T:1392  NOTICE: PlexKodiConnect KodiMonitor -> Did not get Plex id from window properties
20:05:29 T:1392  NOTICE: PlexKodiConnect KodiMonitor -> Did not get a Kodi id from Kodi, darn
20:05:29 T:2480  NOTICE: D3D: rendering method forced to DXVA processor
20:05:29 T:2480  NOTICE: DXVA::CProcessorHD::InitProcessor - Supported deinterlace methods: Blend:yes, Bob:yes, Adaptive:yes, MoComp:yes.
20:05:29 T:1392  NOTICE: PlexKodiConnect KodiMonitor -> No Plex id returned for kodiid None
20:05:29 T:1392  NOTICE: PlexKodiConnect KodiMonitor -> Aborting playback report`

**Comment by croneter** [comment]
Nothing more to that log? Should have used filename and path to find the plex id. How did you initiate playback? Widget? Video node?

**Comment by im85288** [comment]
No that's all, to make sure I tried another one from a widget on the home screen and got a similar output in the log

`20:45:55 T:5716  NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnPlay Data: {"item":{"title":"","type":"movies"},"player":{"playerid":1,"speed":1}}
20:45:55 T:5716  NOTICE: PlexKodiConnect KodiMonitor -> Currently playing file is: smb://DISKSTATION/share/TV/Quantico/Season 1/Quantico - S01E18 - Soon HDTV-720p.mkv
20:45:55 T:5716  NOTICE: PlexKodiConnect KodiMonitor -> Playing itemtype is (or appears to be): movies
20:45:55 T:5716  NOTICE: PlexKodiConnect KodiMonitor -> Did not get Plex id from window properties
20:45:55 T:5716  NOTICE: PlexKodiConnect KodiMonitor -> Did not get a Kodi id from Kodi, darn
20:45:55 T:5716  NOTICE: PlexKodiConnect KodiMonitor -> No Plex id returned for kodiid None
20:45:55 T:5716  NOTICE: PlexKodiConnect KodiMonitor -> Aborting playback report`

**Comment by croneter** [comment]
Darn. Thanks for letting me know...Both of you using Krypton?

**Comment by im85288** [comment]
Yeah both Krypton, looking more closely it looks like the problem may be the type coming in is "movies" where it should be "episode"

**Comment by croneter** [comment]
Awww, found it. Ridiculously small thing, 'movies' instead of 'movie'

**Comment by im85288** [comment]
Will it make a difference on the lookup that the file I was playing is actually an episode in this case? Basically using the up next section of my skin

**Comment by croneter** [comment]
No. That's taken care of

**Comment by hstamas** [comment]
Man I wish I could look at a log and help you guys figure things out. For me it a fresh Krypton install. First using the native Estuary skin then im85288's mod. If initiated from a home screen widget, playback is never detected now. Going into the library sections (I assume that is what you mean by "node"), PMS does recognize that playback has started.
