### ISSUE TITLE
Sync options configuration screen text issue under Krypton

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#68]
In the configuration screen under Sync Options, the limit artwork cache has odd words where it should be numbers.

scrolling through the choices: May/20/Friday/10/Settings/Disabled

**Comment by croneter** [comment]
Not here. Did you try to restart Kodi?

**Comment by hstamas** [comment]
Yes, fresh install of latest Krypton nightly and PKC 1.2.6.  At least 3 restarts.
![image](https://cloud.githubusercontent.com/assets/4341070/16358494/f86626c6-3ae1-11e6-96db-6eb196d50910.jpg)

**Comment by croneter** [comment]
Just had a look at the PKC source code:
```
<setting id="imageCacheLimit" type="enum" label="30513" values="Disabled|5|10|15|20|25" default="5" visible="eq(-1,true)" subsetting="true" /> 
```
Looks perfectly fine. I'm guessing it's a Kodi Krypton issue - they're still heavily developing the alpha version
