### ISSUE TITLE
Kodi Crashes on start of movie

### ISSUE THREAD

**Issue by rush02112** [croneter/PlexKodiConnect#685]
When I click to start a movie, the loading notification comes up, hangs, then crashes to desktop.

## To Reproduce
1. Start Kodi
2. Click on any movie
3. Crash to desktop

Kodi.old log file:
https://pastebin.com/ffagZHV9

Kodi log file:
https://pastebin.com/5T6ASisc
    
I also have 13 kodi_crashlog-18.0 dump files if that matters

**Comment by croneter** [comment]
Nothing suspicious in the log concerning PKC, unfortunately. PKC passes the file to play to Kodi. Then it's up to Kodi what to do with it. 

Please bring this up with the Kodi team

**Comment by croneter** [comment]
Thread on Kodi forum: https://forum.kodi.tv/showthread.php?tid=340199

**Comment by croneter** [comment]
Nope, that did not help

**Comment by croneter** [comment]
How does 2.7.15 work for you?

**Comment by rush02112** [comment]
At first I thought you might have gotten it. Then when I tried resuming from a resume point it crashed.

https://www.dropbox.com/s/zza9n2txzowd8ow/kodi.old.log?dl=0

Then I tried to reboot and play another movie and another crash

https://paste.kodi.tv/situkacobu.kodi

Sorry about the dropbox link, pastebin didnt like it being that large of a file

**Comment by croneter** [comment]
How about 2.7.16?

**Comment by rush02112** [comment]
I do not see a 2.7.16 beta update on the beta repository

**Comment by croneter** [comment]
Hit "Search for updates"

**Comment by rush02112** [comment]
Another crash on resume point

https://www.dropbox.com/s/5xjhi33xkquhzdm/Kodi%20Log.txt?dl=0

**Comment by croneter** [comment]
Did you manage to play something? Or does Kodi crash immediately? How bad is it?

**Comment by croneter** [comment]
And 2.7.17?

**Comment by rush02112** [comment]
It crashed on the first attempt on 2.7.16. I am at work today so I will not be able to try 2.7.17 until I get home in about 9 hours.

**Comment by croneter** [comment]
PKC hasn't crashed yet?

**Comment by rush02112** [comment]
Sorry I actually forgot about it last night. I just tried multiple movies with fresh starts & resume points and no crashes, I will swap this install into my main kodi instance tonight to really test it.

You have me hopeful!

Not that I will understand it, what was/is causing this that you're chasing?

**Comment by croneter** [comment]
Nice!! Let me know how it is going please

Kodi is just a pain - there's a lot one can do wrong when programming a complex addon such as PKC ;-)

**Comment by rush02112** [comment]
All weekend of playing and no issues. I am willing to go out on a limb and say you got it.
