### ISSUE TITLE
No playstate update if transcoding 

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#69]
```
21:59:40 T:1372  NOTICE: PlexKodiConnect WebSocket -> process : Received message from PMS server: {u'_elementType': u'NotificationContainer', u'_children': [{u'context': u'static', u'videoCodec': u'h264', u'protocol': u'http', u'complete': False, u'audioChannels': 2, u'throttled': True, u'width': 1920, u'audioDecision': u'copy', u'_elementType': u'TranscodeSession', u'container': u'mp4', u'audioCodec': u'aac', u'key': u'a7496824-860d-42d5-ab1d-496b9eb3424e', u'progress': 45.400001525878906, u'height': 808, u'speed': 0, u'remaining': 34487, u'videoDecision': u'transcode'}], u'type': u'transcodeSession.update', u'size': 1}
```
So `u'type': u'transcodeSession.update'` is indeed sent.

The following messages are NOT sent by the PMS (could not be replicated); `u'type': u'playing'`
```
15:56:46 T:8152  NOTICE: PlexKodiConnect WebSocket -> process : Received message from PMS server: {u'_elementType': u'NotificationContainer', u'_children': [{u'viewOffset': 286396, u'transcodeSession': u'97ecddceb64da4f4-com-plexapp-android', u'url': u'', u'ratingKey': u'340448', u'_elementType': u'PlaySessionStateNotification', u'state': u'playing', u'sessionKey': u'145', u'key': u'/library/metadata/340448', u'guid': u'com.plexapp.agents.imdb://tt4172430?lang=en'}], u'type': u'playing', u'size': 1}
```

**Comment by c0m3r** [comment]
Will try the OS reboot as requested. Its an always on server so doesnt reboot often. Am using Windows 10 on both machines. Will report back after the reboot. Thanks

**Comment by c0m3r** [comment]
Rebooted and re-tried the same process. Marked 2 Guns as unwatched etc. but never updated in Kodi. Log attached.
[kodi.txt](https://github.com/croneter/PlexKodiConnect/files/342124/kodi.txt)

**Comment by croneter** [comment]
There is this missing message type from the PMS. Could you do me a favor and grab the PMS logs as well? https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files

Just need the Plex Media Server.log. Please enable debug logging in the PMS settings

**Comment by c0m3r** [comment]
Attached. Just to note, new items are added fine and marking watched or unwatched within kodi is properly transferred to PMS.
[Plex Media Server.txt](https://github.com/croneter/PlexKodiConnect/files/342208/Plex.Media.Server.txt)

**Comment by croneter** [comment]
Thanks! 

By the way, if you manually toggle watched state on the PMS, that is not transferred. PMS doesn't tell :-(

**Comment by c0m3r** [comment]
Ah that may be the problem then, that is what I was doing during the testing on my test machine before rolling out to the HTPC. For these I would need to do a manual sync then?

**Comment by croneter** [comment]
I understood that you were actually watching a movie/episode on another machine and this information was not synced to Kodi. 

Now I understand that you were logged into your PMS and changed the watched status there: so from "unwatched" to "watched" and/or vice-versa. 

The latter cannot be synced instantly to Kodi (as opposed to the first ;-)). This is because the PMS doesn't tell anyone that you just toggled the watched-status. Nothing I or anyone else can do. That's also the reason why there is a regular full/delta sync from PKC, to capture these watched state changes every x minutes. You should usually not be forced to do a manual sync ;-). Who toggles watched status manually anyway?!? ;-)

So we're good? Or were you watching something on another machine?

**Comment by c0m3r** [comment]
No was doing it manually. I'm currently running a dual plex and emby server as I previously used the emby kodi addon. Didnt like the plexbmc so have been looking for a replacement. With this addon doing the same thing with the kodi database I assumed it would do the same with manual watch status changes as I sometimes have to fix things between the two servers. Intention is to make to just plex and this was the final issue stopping me.

**Comment by croneter** [comment]
Closing - PMS issue PKC cannot solve
