### ISSUE TITLE
On-screen display of "Show syncing process"

### ISSUE THREAD

**Issue by Zixim** [croneter/PlexKodiConnect#702]
The info displayed in "Show syncing process" could be better organized.
2nd line displays : 
`current_item_nr / total_items  itemname`

Since `itemname` can have any length, it causes the preceding displayed info to jump across the screen, rendering it unreadable.

Wouldn't it be better to display `itemname current_item_nr / total_items`  ?

`itemname` will still jump across the screen, but at least `current_item_nr / total_items` will be readable ?

**Comment by croneter** [comment]
This depends on your skin - with Estuary, it's actually the other way around

**Comment by Zixim** [comment]
errr...no ?
![image](https://user-images.githubusercontent.com/7814664/52272359-d173fd80-2946-11e9-986d-77b9c39f46b5.png)

But, point taken that the skin is in charge of the display order.

**Comment by croneter** [comment]
I'm saying that e.g. with Estuary, the pop-up aligns to the left. Putting the item's name first would make everything worse 😉

**Comment by Zixim** [comment]
still, the different lengths of the name make the line jump around...
If the sync is going fast enough ofcourse 😛 
In this particular instance the name isn't even refreshing ... 🤦‍♂️ 
![image](https://user-images.githubusercontent.com/7814664/52272802-2e23e800-2948-11e9-9530-42f2509e0223.png)

**Comment by croneter** [comment]
What was I thinking - you're correct! 🙈  I'll place the item's name in front (I'd consider Estuary as the most important skin still)
