### ISSUE TITLE
No rating in Kodi 17 Krypton

### ISSUE THREAD

**Issue by onlyyou** [croneter/PlexKodiConnect#71]
Works fine under Kodi 16.1 but not in Kodi 17 alpha 2
thanks

**Comment by croneter** [comment]
As you said Kodi 17 is still in alpha state and thus under heavy development (this might actually be a Kodi, not a PKC issue). Anything might change at any time. I won't invest in this yet until Kodi 17 is more stable

**Comment by onlyyou** [comment]
no problem, will try the new nigthly builds and let know people here as soon as a version will works

**Comment by platj3** [comment]
Still no movie ratings in Kodi 17 Final.

**Comment by croneter** [comment]
Install PKC beta (at least PKC version 1.5.11 needed). Then resync by going to the PKC Settings, advanced, Reset the Kodi database (in red), then Yes, Yes, No

**Comment by platj3** [comment]
I already did this on multiple systems multiple times, still no ratings... I am using in plex the imdb rating.

**Comment by platj3** [comment]
Also TV Shows and Episodes are missing ratings...

**Comment by croneter** [comment]
There are "pulic" rating like IMDB. They appear in Estoury like this:
![screenshot000](https://cloud.githubusercontent.com/assets/4637940/22864047/28584a66-f14a-11e6-827c-16d178303d4e.png)

Then are are YOUR user ratings, taken from Plex. You need to manually set them for each and every video. They appear like this:
![screenshot001](https://cloud.githubusercontent.com/assets/4637940/22864049/40e90778-f14a-11e6-8794-2a3e8a5a181e.png)
![screenshot003](https://cloud.githubusercontent.com/assets/4637940/22864051/483a612a-f14a-11e6-9975-ef30bcb6fb50.png)

Still sure ratings are missing? Then share a screenshot

**Comment by platj3** [comment]
Hi Croneter, thanks for your explanation.
When I am using the skin Estuary I indeed see the Rating.
I am using the skin Arctic Zephyr, so probably the issue sits in this skin.

Thnx for your time.

**Comment by platj3** [comment]
Hi Croneter, in version 1.5.14 the ratings are working now for TV Shows. But for Movies the rating is still not visible in view list. See screenshot. If you do a Database Reset, do you then have ratings for movies in view list?

![image](https://cloud.githubusercontent.com/assets/25724146/23102596/2e7b5106-f6ac-11e6-9538-5b158c01e046.png)

**Comment by croneter** [comment]
It's visible in estuary, just checked. Do try a database reset. If that doesn't help, try switching the skin

**Comment by croneter** [comment]
Hold on - the code says something else :-D. There'll be an update tonite ;-)

**Comment by platj3** [comment]
Great! you found something thats looks like a bug? :)
