### ISSUE TITLE
Not writing network credentials to passwords.xml

### ISSUE THREAD

**Issue by briancl2** [croneter/PlexKodiConnect#72]
So I was having problems with the Kodi library playing movies via Direct Play.  My Direct Paths setup was correct, and the path showing on Kodi via the Info screen was a playable smb path (checked from another networked computer).

I turned on debug logs and found this in the kodi.log:

```
19:55:44 T:140111986067328   ERROR: SMBDirectory->GetDirectory: Unable to open directory : 'smb://USERNAME:PASSWORD@mynas/giant/share/videos/movies'
                                            unix_err:'d' error : 'Permission denied'
19:55:44 T:140111986067328   ERROR: GetDirectory - Error getting smb://mynas/giant/share/videos/movies/
```

I know that I had configured the password, so that is odd that it reflects that some default username and password is being used.  I then re-entered the creds via the PKC settings. No change.  I try to remove the credentials and still no change.  I look again at the log:

```
19:52:17 T:140110393165568  NOTICE: passwordsXML -> __init__ : Path to passwords.xml: /storage/.kodi/userdata/passwords.xml
19:52:21 T:140110393165568  NOTICE: passwordsXML -> __init__ : Successfully removed credentials for: mynas
19:52:21 T:140110393165568  NOTICE: Plex -> __init__ : Failed to find saved server: mynas in passwords.xml
```

This seems odd.  I look in the passwords.xml file, and sure enough, there is a conflicting SMB share setup with the same server name (I had earlier tried to add my nas as a Kodi fileshare).  I delete the passwords.xml file and then start over.  It works now.  I guess the PKC setting didn't know how to react to the conflicting passwords.xml entry.

One idea: when entering the SMB network credentials in PKC, have it validate the creds work right there on the spot.  Provide the user some feedback that what they entered is valid or invalid.  Had I known my creds never worked, I would have saved myself a couple days of troubleshooting.

**Comment by croneter** [comment]
Thanks for your issue report! I will look into this
