### ISSUE TITLE
Feature request: Downloading for offline viewing

### ISSUE THREAD

**Issue by loeffelpan** [croneter/PlexKodiConnect#725]
I would like to have the ability like in Plex app to download content from server (maybe trancoded) and store this locally on my Kodi device to watch offline.

I don't know if this is similar to #144 but my usecase is somewhat different.

**Comment by croneter** [comment]
Feature request is already here: https://feathub.com/croneter/PlexKodiConnect/+9

**Comment by loeffelpan** [comment]
Ok thanks.
Wasn‘t sure in this is exactly what is described in the feature request.
