### ISSUE TITLE
PKC pulling wrong or none actor thumbs

### ISSUE THREAD

**Issue by milesbenson** [croneter/PlexKodiConnect#727]
Hi there,

i dont know if this is an Kodi or an PKC issue, but let's give it a try:

I somestimes do get wrong actor thumbs and sometimes no actor thumb at all while Plex Media Player is showing them correctly.

Examples:
Sylvester Stallone - No thumb at all
Will Smith - well, there is a thumb, but not Will Smith

Both thumbs do show up fine in Plex itself.

What i tried so far:
Restarted Kodi, deleted Thumbnail folder and Textures13.db, recreated EVERYTHING, also did wipe out Cache/PhotoTranscoder within Plex.

I do have the same behaviour for three PKC instances. If a log would help, let me know.

**Comment by croneter** [comment]
PKC picks the thumbnail for an actor only for the FIRST Plex item it encounters. So this is definitely a Plex issue.
Can you somehow rescan your Plex library?

**Comment by milesbenson** [comment]
I did twice, but same error. No picture for Stallone, wrong picture for Will Smith. In Plex Media Player, they are correct.

**Comment by croneter** [comment]
I'm 100% sure that there is at least ONE movie/show where both pictures are incorrect also when you use PMP. 

Could you please have a look at the movies for these actors, then find the one where the metadata is incorrect. Then post the XML. See here for a similar issue with Plex: https://forums.plex.tv/t/cast-metadata-incorrect/198941/3

**Comment by milesbenson** [comment]
Well, i cross checked and they seem to be ok.

Also the false Will Smith picture IS Will Smith, but the comedian :D
https://thecomedystore.co.uk/london/wp-content/uploads/sites/4/2013/10/Will-Smith-205-x-205.jpg

Is there a way to change the picture manually within Kodi/PKC?

**Comment by croneter** [comment]
You Plex library needs to be looked at, I think. Any way you can share it with me? ("croneter") That would be easiest

**Comment by milesbenson** [comment]
You have been invited :)

**Comment by croneter** [comment]
Which movie is it? 😉

**Comment by milesbenson** [comment]
Well, all Sylvester Stallone movies show Sylvester Stallone in Plex Media Player but not in PKC/Kodi.
All movies with Will Smith show the correct Will Smith in PKC/Kodi, but the wrong one in PKC/Kodi.

I dont know if there are more, i am still testing with PKC :-)

**Comment by milesbenson** [comment]
Ok i guess i have found the issue for Will Smith:

I have 'Paddington' added to my movies, where the Comedian Will Smith (https://www.themoviedb.org/person/234120-will-smith?language=de-DE) was part of. Plex shows the wrong Will Smith here https://www.themoviedb.org/person/2888-will-smith?language=de-DE

All other movies with Will Smith show the correct one https://www.themoviedb.org/person/2888-will-smith?language=de-DE, but PKC seems to have pulled the Will Smith from Paddington. 

Whenever i update Metadata for 'Paddington', the correct Will is shown, but also updated for each other Will Smith' movies which are then incorrect. If i update 'Bad Boys' again, the Will for Paddingtion is also changed. So this is definitly a Plex issue, but i do not know how to describe that.

**Comment by croneter** [comment]
Please open a new thread in the Plex forum, PMS section. Share Paddingtons metadata (using Plex web, navigate to the movie. Then hit the three dots... At the top right, then show info, then show xml)
