### ISSUE TITLE
Will not connect to home user or sometimes the server at all

### ISSUE THREAD

**Issue by hermy65** [croneter/PlexKodiConnect#73]
I have multiple managed users in my pms instance and using PKC i can connect to any of them except one which happens to be the most important one. Everytime i select that user it prompts for the pin like its supposed to, i enter it and then a few seconds later the user popup happens again. Im using the same pin to log into the web interface and other devices without issue, even changed the pin and tried it but it still doesnt work. In the log it mentions its not what it was expecting but i literally have no idea what else to try.

Attached is the log

Also, secondary issue is that ive uninstalled/reinstalled Kodi a handful of times trying to get this working and half the time it fails to connect to the local server. 
[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/358625/kodi.zip)

**Comment by croneter** [comment]
Thanks for the issue report!

Looks like your PMS is rather weak; it does not reply within 4 seconds. I will think of something to counter this in the next release.

**Comment by hermy65** [comment]
Interesting, its running on an i7 with 32gb of ram and connected to a gigabit network. Anything on my end i should be looking at?

**Comment by croneter** [comment]
I could not think of anything... Do you have a large library?

PKC "pings" the server's On Deck view. Your server takes more than 4 seconds to respond for some reason

**Comment by hermy65** [comment]
So PKC pinging the server's On Deck view is whats causing me to connect to all users except one?

**Comment by croneter** [comment]
My guess is that the PIN for that user or the fact that it's the master user takes the PMS a bit longer to process the On Deck ping. So if you can, try removing the PIN

**Comment by hermy65** [comment]
Just a little more info for you, all four accounts on my PMS have pins, 3 of them work without issue in PKC the fourth does not. I removed the pin and tried it again and that account will still not connect.
