### ISSUE TITLE
Direct Path local (feature request?)

### ISSUE THREAD

**Issue by xcorp** [croneter/PlexKodiConnect#730]
Hi,

I'm trying to setup direct path and SMB isn't working for me, the thing is I don't need SMB.
Plex runs in a LXC container on the host where i run Kodi and all the files are stored. 
For both Plex and Kodi the path to my media is exactly the same (/files/Movies and /files/TV), is there any way I can use PKC and have Kodi play the media from the local path instead from SMB/NFS/Stream?

Thanks

**Comment by croneter** [comment]
Yes of course. Simply enable direct paths in the PKC settings and DO NOT replace any paths. Then reset the Kodi database in the Advanced section of the PKC settings. That's it.
