### ISSUE TITLE
dsplayer 17.6 kodi version not supported by pkc after 2.4.11

### ISSUE THREAD

**Issue by JCYTang** [croneter/PlexKodiConnect#742]
after updating to any pkc version past 2.4.11 I get the version not supported by pkc message

I am using dsplayer kodi 17.6 and attached my log file.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2896413/kodi.log)

**Comment by croneter** [comment]
Well, dsplayer probably never worked. It's got a DB version of 112 that I have never seen before for Kodi 17.6

If you manually install PKC from the zip file attached, does it work? If not, please share the debug log file again. 

[plugin.video.plexkodiconnect-2.7.2.zip](https://github.com/croneter/PlexKodiConnect/files/2896567/plugin.video.plexkodiconnect-2.7.2.zip)

**Comment by JCYTang** [comment]
it was working great for me using dsplayer up to 2.4.11

when i revert back to the old version it is fine.

tried installing manually from the zip file but no luck.

please see the log file below
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2896692/kodi.log)

**Comment by croneter** [comment]
dsplayer apparently is not Kodi at all - it uses completely different database versions. I can't guarantee that this is not going to blow into your face 🙈 

Please try again with this version:
[plugin.video.plexkodiconnect.zip](https://github.com/croneter/PlexKodiConnect/files/2896721/plugin.video.plexkodiconnect.zip)

**Comment by JCYTang** [comment]
thanks i tried, it seems to detect now but i get another error msg saying:
table album has no column name str artists

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2896806/kodi.log)

**Comment by croneter** [comment]
Ah I know what's causing this bug. Will be fixed shortly

**Comment by croneter** [comment]
Should be solved with stable and beta version 2.7.3. Let me know here if this is not the case

**Comment by JCYTang** [comment]
thanks heaps seems to be working now
