### ISSUE TITLE
PKC crashes plex server almost immediately

### ISSUE THREAD

**Issue by bleomycin** [croneter/PlexKodiConnect#75]
As the title says, I connect a fresh install of kodi + PKC to my plex server and within 2-3 minutes the entire server becomes unresponsive to all clients and PKC times out (plex server running on debian Jessie, also tried ubuntu server 16.04). The client (i7 5960X, 64GB ram) and server: E5-2680v3 with 128GB of ram are both under 0 load during this time. All plex library data is stored on SSD. I'm happy to send full debug logs for plex and kodi but i'm afraid to post them here for fear of personal info leaking. Is there some place I can send these? Thanks!

**Comment by croneter** [comment]
Croneter at Gmail com 

Kindly tell plex, too, that their server crashes ;-)

**Comment by croneter** [comment]
Still an issue or did the last PKC update help?  ;-)
