### ISSUE TITLE
Endlessly attempting to sync playlists, filling logs

### ISSUE THREAD

**Issue by Lou-Cipher** [croneter/PlexKodiConnect#753]
On newer versions (I don't know exactly when it started, pretty sure sometime after 2.7.0, and continuing through latest 2.7.3), PKC endlessly attempts and fails to sync the same playlists over and over, throwing the error "Detected spanning tree issue, abort sync for..."  It never succeeds in syncing, and never stops trying, causing the log file to grow without bound, and causing Kodi to hang when attempting to quit/shutdown/reboot/etc.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2906852/kodi.log)

**Comment by Lou-Cipher** [comment]
Worth noting these are all music playlists.  The actual music library appears to function properly.

**Comment by Lou-Cipher** [comment]
If I was a gamblin' man, I'd say this is related to 873c9e74f55a8afa897590cde7ac0c33136b0a0b

**Comment by Lou-Cipher** [comment]
And indeed, I remove that conditional and all is sunshine and rainbows.  Couple unicorns.

**Comment by Lou-Cipher** [comment]
Although perhaps not, the logs just started spamming the following several hundred thousand times (I'm guessing this was the edge case you were solving for with that commit):

2019-02-26 11:28:11.150 T:140575261050624   DEBUG: PLEX.plexgdm: Sending registration data HTTP/1.0 200 OK
2019-02-26 11:28:15.061 T:140577690609408   DEBUG: Testing path: [000] special://profile/playlists/music/fun.m3u
2019-02-26 11:28:15.061 T:140577690609408   DEBUG: Testing path: [001] special://profile/playlists/music/fun_01.m3u
2019-02-26 11:28:15.061 T:140577690609408   DEBUG: Testing path: [002] special://profile/playlists/music/fun_02.m3u
2019-02-26 11:28:15.061 T:140577690609408   DEBUG: Testing path: [003] special://profile/playlists/music/fun_03.m3u
2019-02-26 11:28:15.061 T:140577690609408   DEBUG: Testing path: [004] special://profile/playlists/music/fun_04.m3u
2019-02-26 11:28:15.061 T:140577690609408   DEBUG: Testing path: [005] special://profile/playlists/music/fun_05.m3u

**Comment by croneter** [comment]
Fixed with stable and beta 2.7.4

**Comment by croneter** [comment]
Please use Plex Web and have a look at your playlists. Are there thousands of them? If so, please see here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-automatically-delete-playlists

**Comment by Lou-Cipher** [comment]
So, there are 220k playlists.  My server crashes after deleting about 300 with this script each time...

**Comment by Lou-Cipher** [comment]
So, this really sucks.  There is no way I can/will babysit this script through a thousand iterations of run/hang/kill/restart.  I'm currently running a hackadoo script that waits for an exception (a timeout) and runs a kill -9 on the pms process then restarts it.  It's going to take days for this to work.  Do you have a better way to clean these up?

**Comment by croneter** [comment]
Ouh shoot, so sorry... 

Take the same script, reduce
```
NUMBER_OF_THREADS = 30
```
To something like 
```
NUMBER_OF_THREADS = 10
```

**Comment by croneter** [comment]
Try to reduce any other strain on the PMS, if you can. Don't have other scripts running

**Comment by Lou-Cipher** [comment]
Doesn't look like it's a threading issue.  With nothing else running or accessing Plex, I'm running the following (NOTE to anyone else reading this, the following will wipe ALL your Plex playlists, use with caution):


```
from plexapi.server import PlexServer
from plexapi.config import PlexConfig
from time import sleep
import os

kill_cmd = "kill -9 $(ps faux| grep 'Plex Media Server' | grep -v grep | awk '{print $2}'); service plexmediaserver restart"
baseurl = 'https://blah:port'
token = 'xxxxxx'
plex = PlexServer(baseurl, token)

playlists = plex.playlists()

for playlist in playlists:
    try:
        playlist.delete()
        print("hooray")
    except Exception as e:
        os.system(kill_cmd)
        sleep(5)
        print("trying again")
```

So, it's single threaded, calls the plex api delete function directly on every playlist.  Still hangs frequently, but it kills the plex process and starts it over, keeps going.  I'll have to run it again after it completes, to pick up all the playlists where it died.  I'm hoping that once it gets down below a couple hundred thousand playlists it will stop crashing so much.  I'll just leave it running overnight and see where I end up in the AM.

**Comment by croneter** [comment]
Ouch. That REALLY should not happen on the PMS side

**Comment by Lou-Cipher** [comment]
I'd guess the database is not sufficiently optimized to handle operations on a quarter million playlists.  After running overnight, I'm down to 190k.  Assuming the rate remains constant (I'm actually assuming that at some threshold it will improve), it's going to take almost exactly one week running 24x7 with no other server load to complete this operation.

**Comment by croneter** [comment]
Ouh I'm so sorry :-(((

**Comment by Lou-Cipher** [comment]
Lie down with the beta, get up with the bugs.  C'est la vie.

But it really picked up at some point, I'm guessing it dropped below a threshold where the DB could sanely handle the number of playlists it was dealing with, and it's already done.  I'll fire up latest PKC and validate that everything's fixed and close this issue out.  Bet this also fixes some general wonkiness I've been seeing with Plex in general lately (the Android app has been having major issues connecting to the music library).  Update to follow, thanks for helping figure this out.

**Comment by Lou-Cipher** [comment]
OK, looks like a fresh sync worked properly.  Strangely, my in-progress and recently added movies panels have no artwork, but the actual movie list does, as do the recently added and in progress TV Shows, but that's a whole different problem I'll investigate and open an issue for if necessary (could also be related to using my own fork of the titan skin with the xbmc.gui version updated to 5.14.0 with no other changes.  Poor titan hasn't received any love in a long time).  I've also deleted all my playlists, so I'll recreate one and see if there are any problems, and open a new issue if so.  For now, this one can be closed out.

**Comment by croneter** [comment]
Glad it worked out!
