### ISSUE TITLE
Sync crashes PKC

### ISSUE THREAD

**Issue by Joostzilla** [croneter/PlexKodiConnect#754]
Since my upgrading to Leia i have major problems with PKC. I tried to do a full reset but it fails and crashes during sync.
Here is my log file:
https://paste.kodi.tv/ocobuwopek.kodi

**Comment by croneter** [comment]
You're using a really-old version of PKC: 1.8.18. Please grab the latest from the repository, currently `2.7.4`, that hopefully solves all your problems.

Background: Your Kodi database looks different than expected:
```
OperationalError: no such table: tag
```

As a sidenote (I don't know whether this is applicable to you):
Please use an "official" stable Kodi version from www.kodi.tv/download. Nightly version are **not** supported

**Comment by Joostzilla** [comment]
Thanks for the help.
I now have installed repository 1.02 but PKC still goes not higher as 1.8.18
I am sure I am doing something wrong. 
Downloaded the stable release > install from zip file > install from repo > Plex Kodi Connect Addons > Video add-ons > PlexKodiConnect 1.8.18
Very strange. 

Furthermore, I did use the official download. But I upgraded from Kodi DSPlayer 17.6

**Comment by croneter** [comment]
Navigate to Addons - My Addons - Video Addons - PlexKodiConnect. Then hit update and get the latest version

**Comment by Joostzilla** [comment]
Installation issues solved :)
