### ISSUE TITLE
sync.py crashed - float() argument must be a string or a number

### ISSUE THREAD

**Issue by eversins** [croneter/PlexKodiConnect#755]
Hello,

On a fresh LibreElec 9 installation I install PKC from the repository. After selecting the user when the sync should start I get this error: "TypeError: float() argument must be a string or a number"

Plex server is remote.

I noticed this thread which might be connected, but restoring a backup is no option for me.
https://github.com/croneter/PlexKodiConnect/issues/615
I used the plex guild: https://support.plex.tv/articles/201154527-move-viewstate-ratings-from-one-install-to-another/ to transfer my watched status to a new server.

Thank you.

Here is the log:
`02:23:32.334 T:140708134569728  NOTICE: PLEX.plexgdm: Discovery starting up
02:23:32.337 T:140708134569728  NOTICE: PLEX.plexgdm: Registration starting up
02:23:32.342 T:140708144015104  NOTICE: PLEX.utils: Init DBs done
02:23:32.342 T:140708144015104  NOTICE: PLEX.sync.time: Synching time with PMS server
02:23:32.772 T:140708144015104  NOTICE: PLEX.sync.time: Found a movie item to sync with: 2
02:23:33.171 T:140708144015104  NOTICE: PLEX.plex_functions: Toggled watched state for Plex item 2
02:23:34.402 T:140708144015104  NOTICE: Previous line repeats 1 times.
02:23:34.402 T:140708144015104   ERROR: PLEX.utils: Error encountered: sync.py crashed - float() argument must be a string or a number
02:23:34.403 T:140708144015104   ERROR: PLEX.utils: _____________________________________________________________
02:23:34.403 T:140708144015104   ERROR: PLEX.utils:     Traceback (most recent call last):
02:23:34.403 T:140708144015104   ERROR: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 124, in run
02:23:34.403 T:140708144015104   ERROR: PLEX.utils:         self._run_internal()
02:23:34.403 T:140708144015104   ERROR: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 175, in _run_internal
02:23:34.403 T:140708144015104   ERROR: PLEX.utils:         library_sync.sync_pms_time()
02:23:34.403 T:140708144015104   ERROR: PLEX.utils:       File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/time.py", line 101, in sync_pms_time
02:23:34.403 T:140708144015104   ERROR: PLEX.utils:         timing.KODI_PLEX_TIME_OFFSET = float(koditime) - float(plextime)
02:23:34.403 T:140708144015104   ERROR: PLEX.utils:     TypeError: float() argument must be a string or a number
02:23:34.403 T:140708144015104   ERROR: PLEX.utils: _____________________________________________________________
02:23:34.404 T:140708144015104  NOTICE: PLEX.sync: ###===--- Sync Thread Stopped ---===###
02:23:34.404 T:140708144015104   ERROR: Exception in thread Thread-5:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 124, in run
                                                self._run_internal()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/sync.py", line 175, in _run_internal
                                                library_sync.sync_pms_time()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/library_sync/time.py", line 101, in sync_pms_time
                                                timing.KODI_PLEX_TIME_OFFSET = float(koditime) - float(plextime)
                                            TypeError: float() argument must be a string or a number
02:40:52.914 T:140708284221568   ERROR: Window Translator: Can't find window videolibrary
02:40:52.914 T:140708284221568 WARNING: Label Formating: $VAR[GlobalFanartVar] is not defined
02:40:52.923 T:140708284221568   ERROR: Control 1000 in window 13001 has been asked to focus, but it can't
02:40:59.011 T:140708284221568   ERROR: Control 1200 in window 13001 has been asked to focus, but it can't`

**Comment by croneter** [comment]
Should be solved with stable and beta version 2.7.7. Let me know here if this is not the case.
