### ISSUE TITLE
Rename to Plex for Kodi

### ISSUE THREAD

**Issue by StoneOffStones** [croneter/PlexKodiConnect#76]
Hey croneter,

sorry but I had no other way to get in contact with you.
Why has that great Addon such a complicated name?
For Emby Mediaserver the name for the Kodi Addon ist also only "Emby for Kodi".
It's a but much easier and more enjoyable, or not?!

I think other Third-Party Clients like the Client for the Samsung Smart Hub has also for long time a name like "Plex for SamsungTV's".
Or something like that.

For your Addon, I would much rather prefer such names like...

1. Plex for Kodi 
2. Plex Kodi-Client
3. Kodi-Client for Plex

Thanks at all and what do you think about or?

**Comment by croneter** [comment]
Hi there

Thank you for your input. Since this github issues page is indeed for issues and does not really allow for a lot of user/community involvement, could you please ask this question in the Plex.tv forums? http://forums.plex.tv/categories/other-third-party-clients

Thanks :-)
