### ISSUE TITLE
Problem with customize paths

### ISSUE THREAD

**Issue by angus2064** [croneter/PlexKodiConnect#762]
Hello ,

I have a little problem to configure the custom path ,I got the error message : "Kodi cannot locate ..." 

In fact ,PKC use a wrong path substitution ,my real smb path is "smb://IP_address/Server_Name/...." and PKC use "smb://IP_address/Volume1/Server_Name/....." .
I don't know how to force PCK to use the correct smb path .

Thank you in advance for your help .

**Comment by croneter** [comment]
Post screenshots of your path substitution settings please

**Comment by angus2064** [comment]
Thanks for your response ,here some screenshots :

Error message with wrong path : 
<img width="725" alt="Capture d’écran 2019-03-10 à 18 55 48" src="https://user-images.githubusercontent.com/46409598/54089198-c3126a80-4366-11e9-915a-922c438ccd9a.png">

Path substitution settings :
<img width="1369" alt="Capture d’écran 2019-03-10 à 18 56 36" src="https://user-images.githubusercontent.com/46409598/54089212-dd4c4880-4366-11e9-9247-6f4ecc201e30.png">

Real smb path in Kodi : 
<img width="955" alt="Capture d’écran 2019-03-10 à 18 58 06" src="https://user-images.githubusercontent.com/46409598/54089217-ea693780-4366-11e9-9d7e-1f49c6e002dd.png">

**Comment by croneter** [comment]
You need to set the "Original Plex Xxx" stuff in the PKC settings! See https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths

Try /volume1

**Comment by angus2064** [comment]
Thank you ! 
That's work perfectly :)
