### ISSUE TITLE
Tautulli receiving the same session_id for different playbacks

### ISSUE THREAD

**Issue by Panja0** [croneter/PlexKodiConnect#764]
## Describe the bug
I have 2 Kodi boxes running with PlexKodiConnect.
If I play a (different) file (movie, tv show etc) on both boxes at the same time they both have the same session_id.
This causes issues with the app Remote for Tautulli. 

## Expected behavior
Every new play should have a different session_id.

**Comment by croneter** [comment]
Try this: in the PKC settings under Advanced, choose "Generate a new unique Plex device ID" on one of the devices. Restart Kodi. Issue should be solved

**Comment by Panja0** [comment]
Not working...
I even did it on both machines (generating a new unique Plex Device ID) without luck.

Kodi/PKC one:
"session_id": "44cc7f30-3726-4fed-8913-919d61252743"

Kodi/PKC two:
"session_id": "44cc7f30-3726-4fed-8913-919d61252743"

**Comment by croneter** [comment]
Please share DEBUG log files of you playing something for both devices, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by Panja0** [comment]
Here ya go!

Kodi 01 machine:
[kodi01.log](https://github.com/croneter/PlexKodiConnect/files/2958594/kodi01.log)

Kodi 02 machine:
[kodi02.log](https://github.com/croneter/PlexKodiConnect/files/2958596/kodi02.log)

**Comment by croneter** [comment]
I'm pretty sure you already fixed the bug by following my steps above. Might be that either the PMS or Tautulli somehow took their time to pick up on the change. 

Reboot both devices again please. Then try again

**Comment by Panja0** [comment]
I’m sorry. It did not fix anything for me.
I have rebooted the boxes several times the past days without any luck.

Aan za, mrt. 16, 2019 om 17:38, croneter <notifications@github.com> schreef:

**Comment by croneter** [comment]
Does Plex web have any issues when you play 2 different items simultaneously? Or only Tautulli? My guess is that Tautulli is the culprit here

**Comment by Panja0** [comment]
The problem is with the app Remote for Tautulli.
I had contact with the developer and he told me the problem is with PKC.

The only thing I know and see is that PKC gives the same session_id to both streams...

Aan zo, mrt. 17, 2019 om 16:56, croneter <notifications@github.com> schreef:

**Comment by croneter** [comment]
With PKC, there is no `session_id`. Could the Tautulli dev be very specific here?

**Comment by tfonfara** [comment]
@croneter hi, I'm the developer of Remote for Tautulli app, maybe we can solve this together.

I've developed this app to work properly with any original Plex client. So far this is the first issue in that matter. After some analysis @croneter and me found that PKC is sharing the same session_id across multiple devices which should not be the case (a session should be unique). So at that point PCK behaves different to the official clients.
For my understanding this isn't a bug in my app, as this behavior is "not usual".

WDYT?

**Comment by tfonfara** [comment]
Maybe one additional note, I'm just accessing the api of Tautulli itself, maybe the issue could also be there.

**Comment by croneter** [comment]
Hell there @tfonfara :wave: . 

There is no `session_id` that is passed to the PMS. What is passed is a unique client id as . This id will be identical if a Kodi installation is cloned/copied. Choosing `Generate a new unique Plex device Id` in the PKC settings under Advanced will set a new unique id. A Kodi reboot is then mandatory. 
I have seen in the past that it took the PMS a while to pick up this change. 

Only exception is if PKC/Kodi should transcode - which was not the case here

I don't know what else besides `X-Plex-Client-Identifier` could be causing the behavior :disappointed:

**Comment by Panja0** [comment]
I have generated an unique Plex ID for both the Kodi boxes and rebooted numerous times.

**Comment by croneter** [comment]
That's why I'm thinking it might be a Tautulli issue.

**Comment by Panja0** [comment]
On the Tautulli website I’m see 2 different streams and I can click on both of them. Getting the individual information for the streams...

**Comment by tfonfara** [comment]
@Panja0 this only means that Tautulli web interface might use a different property for selecting the streams this does not mean that session_id isn't unique 🤔

**Comment by Panja0** [comment]
Hmm I see.
Well I don’t know.

Probably this will be something unresolvable...

**Comment by croneter** [comment]
Is this still an issue?

**Comment by Panja0** [comment]
The problem has been solved.
The creator/dev of Tautulli made a workaround which works for me.

Sorry for not getting back to you earlier.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bxprbadboy** [comment]
Can you share the work around with the community for those that use tautulli?

**Comment by Panja0** [comment]
There is no workaround on an user level.
It’s implemented in Tautulli so everyone can benefit from it.

Aan di, jun. 25, 2019 om 22:08, bxprbadboy <notifications@github.com> schreef:

**Comment by croneter** [comment]
So it's solved? Great

**Comment by Panja0** [comment]
Yes, it’s solved.

Aan wo, jun. 26, 2019 om 06:43, croneter <notifications@github.com> schreef:
