### ISSUE TITLE
PKC On Android Phone not playing

### ISSUE THREAD

**Issue by rcocchiararo** [croneter/PlexKodiConnect#767]
## Describe the bug

I have a Synology nas storing my media and my Plex server is the Nvidia shield TV (mounting the nas).

PKC works on the shield and on Windows computers on my network.

I just got an Android phone, installed Kodi and pic and can't play media (it tries for a while and gives up with no error).

Tried direct path (I use add-on on all other devices) with the same result.

## To Reproduce
1.buy OnePlus 6t
2. Install Kodi and pkc
3. Sync, try to play
4. Nothing plays (using Plex for Android does play)

## Expected behavior
I expect my media to play

##
LOG

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2973329/kodi.log)

**Comment by croneter** [comment]
Hmmm, sorry to tell you that this seems to be a Kodi issue. Everything looks just fine in the log. PKC did correctly tell Kodi what to play:
```
PLEX.playutils: The playurl is: https://192-168-88-229.0db4bf6e88014b48a2f1765534c20eb8.plex.direct:32400/library/parts/6600/1552091865/file.mkv?X-Plex-Platform=Konvergo&Connection=keep-alive&X-Plex-Device-Name=Kodi192.168.88.209&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=***&X-Plex-Model=4.9.106-perf%2B&X-Plex-Platform-Version=2.26.0.947-1e21fa2b&X-Plex-Client-Identifier=bc57825d-aa3f-4863-bb10-69feff9505c3&Accept=%2A%2F%2A&X-Plex-Device=Linux&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=2.7.4
CPlayerCoreFactory::GetPlayers(https://192-168-88-229.0db4bf6e88014b48a2f1765534c20eb8.plex.direct:32400/library/parts/6600/1552091865/file.mkv?X-Plex-Platform=Konvergo&Connection=keep-alive&X-Plex-Device-Name=Kodi192.168.88.209&X-Plex-Provides=client%2Ccontroller%2Cplayer%2Cpubsub-player&X-Plex-Token=***&X-Plex-Model=4.9.106-perf%2B&X-Plex-Platform-Version=2.26.0.947-1e21fa2b&X-Plex-Client-Identifier=bc57825d-aa3f-4863-bb10-69feff9505c3&Accept=%2A%2F%2A&X-Plex-Device=Linux&X-Plex-Product=PlexKodiConnect&Content-Type=application%2Fx-www-form-urlencoded&X-Plex-Version=2.7.4)
```
Just tested with my old Android tablet - all working fine. 

The Kodi teams still pushes many Android fixes to the Github source code. Let's hope that they'll fix this

**Comment by rcocchiararo** [comment]
booo

ON the shield tv (android 8.1) its working fine

ONte op 6t with android 9 its not.

Too bad for me i guess.

**Comment by rcocchiararo** [comment]
forgot to mention, today i tested direct stream with the same result, and then force transcoding, and that works.

No idea how well the transcoding part will work with my not so powerfull server (it has hardware support for some transcoding).

**Comment by croneter** [comment]
Is this still an issue for you? Or was it fixed on the Android/Kodi side?

**Comment by croneter** [comment]
Seems to be solved - no news is good news
