### ISSUE TITLE
playing wrong episode when using the plex android app as remote

### ISSUE THREAD

**Issue by kjellvanzon** [croneter/PlexKodiConnect#77]
First of all, sorry for my English in advance, I’m Dutch J. I have a problem when I’m trying to start a video on Kodi and PKC with my android Plex app on my mobile. (with the cast app, use the mobile as remote). I can find my tv box perfectly and connect to it. But when I start a tv show it plays a different episode from that same show. So for example, when I try to play GoT S06E07 it plays GoT S04E07. When I don’t use my mobile and use Kodi itself to navigate to the tv show and play GoT S06E07 it works perfectly. Then it plays the write episode.

I tried to reset the database a few times, reinstall Kodi and PKC a few times and tried it PKC on different devices (both android boxes as windows systems), they all have the same problem.

hopefully the log like this is good. i enclosud it as a docx and as a txt file. (http://xbmclogs.com/ didn't work)
[log kodi.docx](https://github.com/croneter/PlexKodiConnect/files/367179/log.kodi.docx)
[log kodi.txt](https://github.com/croneter/PlexKodiConnect/files/367181/log.kodi.txt)

**Comment by croneter** [comment]
Thanks for your issue report! 

Could you please go to your plex media server, navigate to these two episodes (S04E07 and S06E07), hit the three dots (...) on the left, choose "info", then show XML file? Please upload the two XML files here...

**Comment by kjellvanzon** [comment]
Hereby the two xml files. Thanks for looking in too it.
[S04E07.txt](https://github.com/croneter/PlexKodiConnect/files/367208/S04E07.txt)
[S06E07.txt](https://github.com/croneter/PlexKodiConnect/files/367209/S06E07.txt)

**Comment by kjellvanzon** [comment]
Not to rush you, but did you have the time to look at this and are the xml files that I send usable?

**Comment by croneter** [comment]
Yes, they are very usable, thanks again! Found the bug really quickly. The issue is rather trickier to solve though, need to rewrite a lot of code :-(

**Comment by kjellvanzon** [comment]
Nice that you found the bug! Unfortunately that solving it is trickier and cost you a lot of time. Good luck! :)

**Comment by kjellvanzon** [comment]
Just tried it with two devices and the problems still occurs. I used Kodi 16.1 PKC 1.2.11. I did a clean install on both devices. 
The same wrong video starts playing. Please let me know if you need another Log or something

**Comment by kjellvanzon** [comment]
I have some time this weekend to test with PKC, so if there is anything I can test to help, please let me know :)

**Comment by croneter** [comment]
Thanks :-). But unnecessary - I know exactly where the problem lies, but just need time to program ;-)

**Comment by kjellvanzon** [comment]
all right, good luck with programming!

**Comment by LasseSLambertsen** [comment]
Any news on this issue, it is kind of a dealbreaker :/

**Comment by croneter** [comment]
Be patient, worst is solved. Tidying up the code now

**Comment by croneter** [comment]
Should be solved in PKC beta (install from a dedicated PKC beta repository). Let me know if this is not the case
