### ISSUE TITLE
Adding a master lock PIN break Kodi's media library

### ISSUE THREAD

**Issue by nicolas707** [croneter/PlexKodiConnect#779]
## Before posting this issue 
I did all I could (fresh install, reset Kodi DB, search in existing issues, ...)

## Describe the bug
On a working configuration, enabling a PIN lock on Master Profil break the library. After that I cannot see any movie in the Kodi UI. 
Removing the PIN make Kodi working well again

## My conf
I did some test and even with a minimal config I can reproduce the bug.
- On a fresh install
- I have only 1 user in Kodi: the master user
- My Kodi master user is linked to the default Admin in Plex.
- Plex server version is Version 1.15.2.793  on a ubuntu LTS server 16.04
- Kodi Version 18.1 Git:20190217-8cfdc895f3. Platform: OS X x86 64-bit
- PlexKodiConnect Version: 2.7.7. No other plugins.
- Movie Library is on a Synology NAS (access via NFS)

## To Reproduce
1. Configure Kodi + PKC with a Movie Library
2. Check that movies are in sync. Opening the Movie library shows all movies
3. Add a PIN on the Master 
4. Restart
5. The movie library do not show any movie. They are all gone.

## Expected behavior
Adding a PIN to he master should not change anything in the library sync.

I am posting 2 log files, one without PIN and another one with it, to compare.
I quick diff showed me that an error occurs only with the PIN enabled: 
` CUtil::GetMatchingSource: no matching source found for [nfs://192.168.1.111/volume1/Tv1/Tv-Films/All/Infernal Affairs (2002)/]`

[kodi-sync-with-master-pin-ko.log](https://github.com/croneter/PlexKodiConnect/files/2985226/kodi-sync-with-master-pin-ko.log)
[kodi-sync-without-master-pin-ok.log](https://github.com/croneter/PlexKodiConnect/files/2985228/kodi-sync-without-master-pin-ok.log)

**Comment by croneter** [comment]
Works fine here. Is your `sources.xml` messed up (found in the [Kodi userdata folder](https://kodi.wiki/view/Userdata))? It needs the following 2 entries:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<sources>
  <video>
    <default pathversion="1" />
    <source>
      <name>PlexKodiConnect Masterlock Hack</name>
      <path pathversion="1">smb://</path>
      <allowsharing>true</allowsharing>
    </source>
    <source>
      <name>PlexKodiConnect Masterlock Hack</name>
      <path pathversion="1">smb://</path>
      <allowsharing>true</allowsharing>
    </source>
</sources>
```
PKC should automatically update your `sources.xml`

**Comment by nicolas707** [comment]
Ok thanks for your quick answer. Now it's working, but:
- with my setup, the 2 entries (PlexKodiConnect Masterlock Hack) are not automatically updated to my sources.xml files (I cleaned all and did a fresh install)
- I had to replace in the 2 entries `smb://` with `nfs://` because I am using direct path and all the video media files are stored in a Nas and accessed via Nfs. FWI I have a direct path rule that replace original `/mnt/` path (my local media are here) with `nfs://192.168.1.XXX/`

Thanks for your help and congrats for your plugin, with it I can  have a very nice HTPC setup. 
You can close the issue.
