### ISSUE TITLE
Direct Paths: Items with several versions or several files not given a choice as to which to play via PKC

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#78]
![combined title](https://cloud.githubusercontent.com/assets/4341070/16959527/8ad10bb4-4db3-11e6-93d9-bc3df6fb4fb7.png)
[Simpsons XML.txt](https://github.com/croneter/PlexKodiConnect/files/372037/Simpsons.XML.txt)

**Comment by croneter** [comment]
Are you using direct paths?

**Comment by hstamas** [comment]
I am.

**Comment by croneter** [comment]
Then PKC doesn't have a say anymore once your media is synced to kodi. Standard setting now is to sync the first item/file only. 

I hope I can think of something...

**Comment by hstamas** [comment]
It certainly isnt a big issue for me. The few movies I have like this I can definitely work around.

**Comment by timhansinger** [comment]
The same happens also to e.g. movies that are split to multiple files (so not different versions). Then only the first file is played.

![screencapture at mon oct 31 15 05 06 cet 2016](https://cloud.githubusercontent.com/assets/7524165/19856857/9b2f9592-9f7b-11e6-8ce9-840c47a12efa.png)

**Comment by RickDB** [comment]
Was wondering how this currently works as I have setup direct paths and if there are multiple files for the same movie it always starts the first item no matter what, does this need Direct Stream to allow for selection?

**Comment by croneter** [comment]
The issue is that Kodi always assumes that there is exactly one media file associated for each Kodi library item. Which isn't the case for Plex. 

Use the [Kodi context menu](http://kodi.wiki/view/Basic_controls#Contextual_menu) (might not always be available, depending on the Kodi screen you're in), then choose Plex options, then `Initiate playback from the PMS`. PKC will then ask you which version you want to play.

**Comment by RickDB** [comment]
Awesome, didn't get that option at first from the info view (Aeon Nox) but see it now 👍 
Any chance the select stream dialog can include more info like filename / audio+subtitle language?

**Comment by croneter** [comment]
Good idea. Your code needs some cleaning up though :-). Just make a PR and we'll see from there!

**Comment by RickDB** [comment]
Yeah thought as much :D , really new at Python and used to Visual Studio with ReSharper as that offers in-line suggestions and what not.
PR #264 created.
