### ISSUE TITLE
Custom Library and Direct Path

### ISSUE THREAD

**Issue by ghallford** [croneter/PlexKodiConnect#780]
I have a custom library on Plex that I sync with PKC to Kodi but I also use direct paths. There is nowhere in the config, where I can put in the conversion of /data/something to smb://blah/something for the custom library like I can do for TV shows and movies

**Comment by croneter** [comment]
Do you mean the Plex config? Or pkc?

**Comment by ghallford** [comment]
Plex has 3 libraries: Movies, TV Shows, Custom. In PKC config, I can customize to remap the to the direct path for Movies, TV Shows but not for Custom. So in Plex, the path to Movies is: /data/movies but Kodi needs to play it from smb://nas/movies. I can do that remap in PKC config for Movies and TV Shows but I can't do it for Custom, so I go and play something in Kodi from custom and it tries to play from /data/custom, not smb://nas/custom

**Comment by croneter** [comment]
Ah OK. "Custom" is actually a movie library as well. If you want to use direct paths, you should use option 2: https://github.com/croneter/PlexKodiConnect/wiki/Option-2-Substitute-Paths-on-the-PMS

**Comment by ghallford** [comment]
Thanks. I am having a hard time figuring it out because my Plex Server is running Linux in a Docker container under Unraid and my Kodi is a Windows 10 PC. Any thoughts on that? Seems like I would have to follow the Linux instructions for Plex but that would make me have to use the "replace paths" method in PKC, which is where I am having the trouble today

**Comment by ghallford** [comment]
I think I see why it might work because it's ALL libraries of that type under 1 mount, as opposed to different ones. Let me give it a try. Thanks.
