### ISSUE TITLE
PKC 2.7.7 produces errors, widgets don't work on Nvidia SHIELD

### ISSUE THREAD

**Issue by charlie2alpha** [croneter/PlexKodiConnect#781]
After upgrading to PKC on my Nvidia SHIELD I get error notifications from PKC "Plexkodiconnect: None" and the On Deck widgets do not work at all, navigating to On Deck from PKC directly produces an empty list. Reverting to 2.7.4 restores full functionality.

Attached a debug log.
[kodi.zip](https://github.com/croneter/PlexKodiConnect/files/2992021/kodi.zip)

**Comment by croneter** [comment]
Should be solved with 2.7.8. Let me know here if not

**Comment by charlie2alpha** [comment]
2.7.8 fixes it, thank you!
