### ISSUE TITLE
Racing condition after updating to 2.7.8

### ISSUE THREAD

**Issue by charlie2alpha** [croneter/PlexKodiConnect#786]
After updating yesterday to PKC 2.7.8 the issues I reported were fixed. Today though when I launched KODI I was greeted with a generic error notification from PKC which was followed by the normal "welcome user charlie2alpha" promt. After that everything worked normally but I got alarmed. I restarted KODI and the same thing happened, error and then the welcome notification.

I checked the log (attached below) and the reason is very obvious, PKC tried to access my PMS before authenticating itself to the PMS. The interesting thing is that PKC had selected on the initial setup the custom URL I have setup on the PMS and not the one that Plex creates itself. The IP address though points to a local LAN IP (I run a custom router setup so I can manipulate the DNS) but the PMS detects that the custom URL is in use anyway and will not allow unauthenticated access. I have whitelisted on the PMS my LAN subnet so any local client that uses the regular Plex URLs can access the PMS without authentication.

To confirm the problem I run the PKC setup to select a server. I selected the same server and everything proceed as normal but this time PKC selected the normal Plex URL ( part of the log, you can see for yourself). After the initial sync, I restarted KODI, the error did not appear likely because PMS detected local access and it allowed it with no authentication.

This is not a critical bug and most users that have more conventional setups will never encouter it but it happened to me!
[kodi.old.log](https://github.com/croneter/PlexKodiConnect/files/2995898/kodi.old.log)

**Comment by croneter** [comment]
Solved with 2.7.9. Let me know here if this is not the case
