### ISSUE TITLE
Error on start up.

### ISSUE THREAD

**Issue by danjames92** [croneter/PlexKodiConnect#787]
Kodi v18
Aura Skin
VPN connection enabled during boot.
30s delay on PKC.

I get to the UI and immediately see an error, then 30s later i get the welcome user pop up.

Also seeing the 2x0 format when I would love to see S02E01.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/2999658/kodi.log)

**Comment by croneter** [comment]
> Also seeing the 2x0 format when I would love to see S02E01
Up to the skin you're using! PKC already shows ``SxxExx`

**Comment by croneter** [comment]
Solved with 2.7.9. Let me know here if this is not the case

**Comment by danjames92** [comment]
Seems to be!
