### ISSUE TITLE
UnicodeDecodeError on launch

### ISSUE THREAD

**Issue by BrutuZ** [croneter/PlexKodiConnect#788]
## Describe the bug
I'm getting this notification at launch and sometimes during playback ever since updating to 2.7.5 and above (incl. 2.7.8)
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)`
Unicode 0xc3 is character `é`, part of my TV Shows path (Séries).
Seems slightly related to #772 except it does seem to be syncing (tested after DB reset).

## To Reproduce
1. Launch Kodi
2. Wait for message
3. Alt+F4 for minimum log size

## LOG
https://gist.github.com/BrutuZ/d5f6672af011489b225e8e25b6c2db82#file-kodi-log-L1622

**Comment by croneter** [comment]
Solved with 2.7.9. Let me know here if this is not the case
