### ISSUE TITLE
Movie node sorted by year not working

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#79]
This is using Krypton 17 so please ignore if it's too early to troubleshoot but when I sort by year I'm presented with one date (1601) only. Also no movies show the year info in any of the description fields either. 

Strang thing is, sorting by year works fine in the TV nodes.

![img_0025](https://cloud.githubusercontent.com/assets/4341070/17074890/aa3d52be-5051-11e6-9069-3cfb04d5862a.JPG)

**Comment by croneter** [comment]
Sorry, Kodi Krypton issue

**Comment by hstamas** [comment]
Tried a test and installed Kodi 17 beta 1 as a stand alone install (no PKC). Years work fine. Only when using PKC does this happen. Now that we are out of the alpha stage can this be revisited?

**Comment by croneter** [comment]
Definitely. I guess nothing changed; let me know otherwise.

**Comment by oscarchd** [comment]
same sorting by year not working, only showing 1601 as picture above.

running on krypton beta 2

**Comment by bartolomesoriano** [comment]
@croneter As I mentioned in the issue I created (sorry for creating a duplicate issue), the team over at Emby for Kodi already fixed this issue, perhaps it would be a good idea to ask them about it, since the code for this addon is based on the code for their addon.

**Comment by oscarchd** [comment]
anyone able to add it to the code?

**Comment by bartolomesoriano** [comment]
@croneter , the commit in the EMby for Kodi plugin to fix this is https://github.com/MediaBrowser/plugin.video.emby/commit/02dee885e8ea5509fdfb1b7e9c23efd99e9ca687, in case that can be useful to you in resolving this issue.

**Comment by oscarchd** [comment]
tried to add in these codes but could not make it work...

anyone with better understanding of the code can merge into the plexconnect py file?
