### ISSUE TITLE
Smartplaylist and Plex libraries

### ISSUE THREAD

**Issue by steve1977** [croneter/PlexKodiConnect#797]
I have different movie libraries in plex (movies and 3D movies, documentaries and TV shows, etc.).

I was trying to build a smart playlist leveraging just one of the libraries. This does not seem feasible. Any idea how this can be accomplished? Not sure whether this requires changes in Kodi or can be done by the addon?

**Comment by croneter** [comment]
Yes that's quite possible. PlexKodiConnect uses [Kodi tags](https://kodi.wiki/view/Video_library_tags) to replicate Plex libraries. Simply add the following snipped to your smart playlist xml:
```
<rule field="tag" operator="is">
    <value>YOUR PLEX LIBRARY NAME</value>
```
Obvisouly replacing `YOUR PLEX LIBRARY NAME` with the actual name of the Plex library. Watch out for case-sensitivity.
