### ISSUE TITLE
Krypton dbVerison bump (107)

### ISSUE THREAD

**Issue by csutcliff** [croneter/PlexKodiConnect#80]
Hi, the latest Krypton nightlies now have version 107 of the schema, PKC seems to work fine when the new version is set in utils.py

**Comment by croneter** [comment]
Thanks for reporting. I'll wait a bit before updating to 107 in order to not break the LibreElecs out there

See https://github.com/croneter/PlexKodiConnect/issues/56 for a solution on how to manually adjust the DB version to 107
