### ISSUE TITLE
TV Show artwork not displaying on playback (Clearlogo)

### ISSUE THREAD

**Issue by starman2908** [croneter/PlexKodiConnect#813]
Windows 10 Kodi 18.1 on Remote Plex Server
I did try to restart Kodi
I checked the [PKC Frequently Asked Questions on the PKC wiki]
I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
I did check the [existing issues on Github]

Hi Cronetor,

I mentioned this a little while ago on aplexforum as i wasn't sure if it was a PKC issue, but after posting the issue on Artwork Beef forums, and MrRector doesn't seem to think the issue lies there. https://forum.kodi.tv/showthread.php?tid=258886&page=55 
Comment# 820&823

The issue exists after any PKC update after 2.7.4 where TV Clearlogo no longer displays during playback. The clearlogo is definately downloaded to the library and displays correctly within library views, but no longer displays on the playback screen. I have ruled out any other addons that may cause the issue by doing a fresh install of kodi, and any all add-ons to the point of where the expected behaviour stops. I also tried several other skins to rule out an issue there. 

The following picks up from where i have got everything working as expected after installing all other addons (with PKC 2.7.4).  I thought this would help to have a baseline you could compare before and after logs. As you can see from this screen shot, the player displays the logo for the TV Show as expected. 

![screenshot000](https://user-images.githubusercontent.com/36766279/55288336-ecdf1000-53ad-11e9-98ca-2955c3fcd737.png) 

Here is the log from this instance : 
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3026522/kodi.log)

After updating PKC to the latest version (Although any version after 2.7.4 exhibits the same behaviour as I have tested all through to 2.7.11 and reset database after each), playback no longer shows artwork on the playback screen.

![screenshot002](https://user-images.githubusercontent.com/36766279/55288374-9920f680-53ae-11e9-97e5-d9f02f11ba65.png)

Here is the log for this instance:
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3026523/kodi.log)

Hope you can have look and see if you can notice any difference in the playback of the logs that might link to PKC somehow.

Thanks for your time,
Ryan

**Comment by goose2600** [comment]
Hi Croneter,
I am experiencing the same issue: clearlogos are showing during the playback untill PKC v.2.7.4, and not showing from v2.7.5.
If the log provided by @starman2908 is not enough, I can provide a log too.
Thanks

**Comment by croneter** [comment]
How about 2.8.0?

**Comment by starman2908** [comment]
No joy i'm afraid. Movies are showing fine, but not TV Shows. Tested on a couple of skins. Tried a PKC reset, and also a fresh kodi and PKC install on a different PC.

The artwork is definitely there and downloaded. I tried PKC artwork download, then reset and tried using artwork beef...same result. 

The same behaviour exists for both remote and local servers. mind boggled :-S

**Comment by croneter** [comment]
You're using addon paths and not direct paths, I take it?

**Comment by starman2908** [comment]
I am yeah

**Comment by goose2600** [comment]
I am using direct paths and clearlogos are showing fine on movies, but not on tv shows.

**Comment by croneter** [comment]
Does PKC beta version 2.8.1 help?

**Comment by starman2908** [comment]
You my friend are genius. TV shows now displaying clearlogo as normal...kudos!!

**Comment by starman2908** [comment]
Just realised....all my tv

**Comment by croneter** [comment]
Yes please

**Comment by starman2908** [comment]
Will do, I start work shortly so I'll do it later, I'll do a fresh install of 2.8.0, then update to 2.8.1 on my spare pc, in case this isn't a pkc issue .....as I updated all on kodi (urlib3) was updated.

**Comment by goose2600** [comment]
2.8.1 works! Thank you!
