### ISSUE TITLE
No Movies or TV

### ISSUE THREAD

**Issue by mccorkled** [croneter/PlexKodiConnect#814]
I recently just upgraded to the newest Kodi and reinstalled this plugin. From what I can see there is no way to view my movies or tv shows. All I can see are whats in the screenshot below.

Thanks 

![1](https://user-images.githubusercontent.com/13697804/55290413-17769c00-53a1-11e9-9b8e-6e09b834a3e2.png)

**Comment by croneter** [comment]
Try to restart Kodi. If that does not work, go to the PKC settings, Advanced, then "Reset the Kodi database". Hit Yes, then No

**Comment by mccorkled** [comment]
Restarting made the two items viewable. I also reset the database. My shows are coming up as the widget but not under the TV Show menu.

![2](https://user-images.githubusercontent.com/13697804/55290947-8fe05b80-53a7-11e9-867d-8c45eeaf21a5.png)

![1](https://user-images.githubusercontent.com/13697804/55290950-9242b580-53a7-11e9-9319-4ba0a3c18c41.png)
