### ISSUE TITLE
Sync Kodi Playlist to plex

### ISSUE THREAD

**Issue by bonatom** [croneter/PlexKodiConnect#815]
I can sync from Plex to Kodi.. but not the other way around. I have specific playlist checked in the setting and the playlist I want to sync has the appropriate prefix that I setup.

**Comment by croneter** [comment]
How about a debug log as described here?https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by bonatom** [comment]
https://paste.kodi.tv/evajozodop

**Comment by bonatom** [comment]
https://paste.kodi.tv/evajozodop

**Comment by croneter** [comment]
So you set the following for playlist sync:
```
PLEX.service: Synching only specific Kodi playlists: True
PLEX.service: Kodi playlist prefix: s_
PLEX.service: Synching only specific Plex playlists: False
...
```
The names of your Kodi **VIDEO** and **AUDIO** playlists thus must start with the prefix `_s`. 

I don't see PKC picking up anything. Are you sure you don't have a **mixed** playlist in Kodi with both video and audio? This is not supported by Plex and thus ignored by PKC...

**Comment by croneter** [comment]
I take it this is solved. Let me know here if this is not the case

**Comment by bonatom** [comment]
I actually gave up... I can not get Kodi Playlist to Sync back to Plex.

If I create a playlist in Kodi (with the right prefix) it should sync (and create) the same playlist in Plex correct? Unless I misunderstand the feature.

Kodi has many more Playlist automation options (I.e. IMDB 250, etc) than Plex and I looked at this as a way to import “Smarter” playlist into Plex

**Comment by croneter** [comment]
You can't import Kodi smart playlists to Plex. Only normal playlists
