### ISSUE TITLE
[Direct Path] Multi part files - only the 1st part is synced

### ISSUE THREAD

**Issue by Inervo** [croneter/PlexKodiConnect#817]
## Describe the bug
Kodi 18.1
PKC 2.7.10 Direct Path

I have some movies / tv show that are multi part (filename with .part1.mkv , part2.mkv, ...).
In Kodi, only the part1 is synced (and is played). The other parts are unavailable in kodi.
I have tried to play with "Start playback via PMS", it doesn't play anything.

Is there some setting I need to use so that these multi part files will play correctly?

**Comment by croneter** [comment]
Kodi cannot handle multi-part files. 

# Solution
Start playback via the Kodi context menu (e.g. hit the button C), choose "Plex Options", then "Start Playback via PMS"

**Comment by croneter** [comment]
Hah, one should read everything. Please share your DEBUG log file of trying to do the above, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by Inervo** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3047981/kodi.log)

Here is the debug log.
Trying to play directly in kodi. The movie part1 is the only one played.

Then trying "Start Playback via PMS" --> nothing happens.

**Comment by croneter** [comment]
Should be solved with PKC BETA version 2.7.12. Let me know here if this is not the case
