### ISSUE TITLE
Movies and Home Videos in one?

### ISSUE THREAD

**Issue by kenrick** [croneter/PlexKodiConnect#82]
Before is say anything else, I love this plugin good work!
However I noticed that my home videos are showing up under movies and I'm not sure why. Is there a was to separate them to even remove home videos all together. I have a ton of home videos in plex and it just looks like a mess in kodi. I big hard to scroll through my movies.

**Comment by croneter** [comment]
See here
https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins
