### ISSUE TITLE
Docker high CPU use

### ISSUE THREAD

**Issue by rbcolom** [croneter/PlexKodiConnect#822]
Hello,
I'm using kodi Leia with 2.7.12 plexkodiconnect on a raspbian - raspberry 3b+
As soon as I activate plexkodiconnect the CPU on my PMS jumps from an idling 10% to 100-150% and also ram usage steeply increases. Normally, with other clients, transcoding video usually uses 70-90% of my cpu.
On the Kodi/Plexkodiconnect I use the samba paths, and every works fine. The only problem I have is that with a cadence of a about every minute and a half kodi gives me an error "Failed to sync" and "PMS server found".
This is my log...    
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3051018/kodi.log)

**Comment by croneter** [comment]
```
WARNING: PLEX.download: Server unreachable at: https://192-168-1-3.f4558f20daa54ba28eec003ab00f6c11.plex.direct:32400/playlists
ERROR: PLEX.playlists.pms: Could not download a list of all playlists
```
Using Plex Web, do you have hundreds if not thousands of playlists? If so, I'm very sorry for that, and please follow https://github.com/croneter/PlexKodiConnect/wiki/How-to-automatically-delete-playlists

**Comment by rbcolom** [comment]
Sorry for the late response, it took me quite a while to remove 200k of playlists... (Never used them, and never noticed how many there were!). But now far so good now.

Just a quick notice for anybody with my same problem, the script provided by the awesome @croneter in python3 queue is queue.Queue() not queue.queue(). 
I actually had so many playlists that the script kept crashing, so I "manually" edited the plex db (Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db) removing in the metadata_item table all rows with metadata_type = 15

Again thank you for kindness in sharing your work and assisting me.

**Comment by croneter** [comment]
@rbcolom 
Thanks a lot for the hint with manipulating the Plex database. I updated the Wiki entry accordingly: https://github.com/croneter/PlexKodiConnect/wiki/How-to-automatically-delete-playlists
