### ISSUE TITLE
PlexKodiConnect not Transcoding from H265

### ISSUE THREAD

**Issue by Veda82** [croneter/PlexKodiConnect#825]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
I've set PlexKodiConnect in Direct Play mode, and I have enabled the option to transcode any H265 file that I play, however transcoding fails and falls back to direct stream.

Excerpt from the attached log file (lines 873-875):

2019-04-09 23:40:46.697 T:1217827696  NOTICE: PLEX.playutils: videoCodec: {u'videocodec': 'hevc', u'container': 'mkv', u'bitrate': '57843', u'height': '2160', u'width': '3840', u'bitDepth': '10', u'aspectratio': None, u'resolution': '4k'}
2019-04-09 23:40:46.763 T:1217827696  NOTICE: PLEX.playutils: No video resolution from PMS, not transcoding.
2019-04-09 23:40:46.764 T:1217827696  NOTICE: PLEX.playutils: File is direct streaming..

Log reports the resolution as '4k'. Is it correct?

Looking at https://github.com/croneter/PlexKodiConnect/blob/master/resources/lib/playutils.py I see (lines 124-128):

        try:
            resolution = int(videoCodec['resolution'])
        except (TypeError, ValueError):
            LOG.info('No video resolution from PMS, not transcoding.')
            return False

Could it be that it's not working because '4k' is not converted to an integer?

Maybe Plex guys changed something in how Plex reports the resolution in the latest Plex Media Server version?

If instead of choosing Direct Play I set Force Transcode, every file (including H265 ones) are transcoded and play fine.

I'm using Plex Media Server latest version (1.15.3.876-ad6e39743), Kodi 18.1 on a Raspberry Pi 2, PlexKodiConnect latest stable version.

## To Reproduce
1. Set PlexKodiConnect in Direct Play Mode
2. Enable Transcoding H265 Files
3. Play any 4K H265 file in my library

## Expected behavior
Playing the transcoded file instead of direct streaming

## Kodi Log:
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3066109/kodi.log)

**Comment by croneter** [comment]
Should be solved in PKC **BETA** version 2.7.13. Please try and let me know here whether it worked!

**Comment by Veda82** [comment]
Just tried, works like a charm!

Thanks for the quick fix!

**Comment by idealitystarts** [comment]
Another method is to use iDealshare VideoGo to convert H.265 or other video files to Kodi more supported video format with this easy guide https://www.idealshare.net/ipad-ipod-iphone/kodi-h265.html
It also helps to convert video files to H.265
