### ISSUE TITLE
Web server constantly try to start

### ISSUE THREAD

**Issue by C-Duv** [croneter/PlexKodiConnect#83]
On my Kodi v17 setup (an _Android TV_ device) it seems the Web server is not working (it's the case since _Kodi_ v15) and I never needed it.
Since I installed _PlexKodiConnect_, it always tries to start even if it is disabled in _Settings > Services > Web server_.
Is that server required for _PlexKodiConnect_?

**Comment by croneter** [comment]
Yes it is required!

**Comment by croneter** [comment]
So what's the issue, exactly?

**Comment by croneter** [comment]
Closing this as it's probably solved - do activate the webserver :-)

Let me know if it's still an issue

**Comment by C-Duv** [comment]
> Yes it is required!
OK, it explains the repeated attempts to start it.

> So what's the issue, exactly?
No, technically, as long as Web server is really required, there is no issue for PKC constantly trying to start it.
A side-effect issue would be the annoying "failed to start" message that pops every 30s: PKC could try to run the server once, find out it failed, warn the user (id. that Web server is required but cannot start in current configuration and invite the user to configure and run the Web server manually for PKC to work) and stop trying.

In my case, the _Android TV_ device I am using has some limitations (device is provided as-is by my ISP) and Web server always refused to start using various port (8080, 8000, 8090, etc.) so I always assumed it was somehow not available on my device because of internal OS limitations (and since I never needed that Web server, never gave it much time).

That being said, by taking more time to play with port setting, I apparently managed to find an open port I could run the Web server on and PKC seems to works just fine.

**Comment by croneter** [comment]
Thanks for clarifying. Good idea, will have a look at the error handling if I get the time

**Comment by paour** [comment]
Trying to change the port in the main Kodi settings, they are reverted to 8080 as soon as the add-on tries to start the web server.
