### ISSUE TITLE
Help with Playlist Replication Issue

### ISSUE THREAD

**Issue by bdpna** [croneter/PlexKodiConnect#836]
Croneter - Saw your post on the playlist replication problem.  I have now 170,000 playlists.  This is a problem.  My server is to its knees.

First off, is this problem fixed or will they just replicate again once I fix it?

I need to use the tough method and am building the python script.

Your help post instructed me to get an ID from the first URL of the first playlist, however, the URL format looks different on my server. 

I see the format like yours in XML view but not in regular playlist view.  Help?

Yours:
https://82-123-96-251.7923ljfse892382.plex.direct:34698/playlists/682194?<potentially-more-stuff>

Mine:
https://app.plex.tv/desktop#!/server/a51fad0d2307e36a751cc3ec9a682b09c21e8e17/playlist?key=%2Fplaylists%2F148681

**Comment by croneter** [comment]
Sorry for the hassle 😞 . The issue should be fixed!

I updated the Wiki article with an option to run a Python script that simply manipulates the Plex database. Should be easier then the third method that you already tried. 
Link to the wiki: https://github.com/croneter/PlexKodiConnect/wiki/How-to-automatically-delete-playlists

Please let me know here if this does not solve your issue.

**Comment by bdpna** [comment]
Thanks so much for the response, and it's all ok!  I appreciate all the work you have put into this plugin.

Here's what I get when I try the new script on my Debian box.  Any thoughts?

_```
root@mediawall:/export/TV4# python3 plexfix2.py
Making a backup of the Plex database:
/sharedfolders/AppData/Plex/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db.BACKUP
Traceback (most recent call last):
  File "plexfix2.py", line 55, in <module>
    main()
  File "plexfix2.py", line 34, in main
    shutil.copyfile(original, backup)
  File "/usr/lib/python3.5/shutil.py", line 103, in copyfile
    if _samefile(src, dst):
  File "/usr/lib/python3.5/shutil.py", line 88, in _samefile
    return os.path.samefile(src, dst)
  File "/usr/lib/python3.5/genericpath.py", line 90, in samefile
    s1 = os.stat(f1)
TypeError: argument should be string, bytes or integer, not PosixPath
```_

**Comment by croneter** [comment]
Seems like you are not using the latest Python 3.7 version. Can you try and upgrade?

**Comment by bdpna** [comment]
Hmmm, I will keep at it.  My openmediavault server running plex (where I need to run the script locally) is on Debian and is telling me 3.5.3-1 is the latest...I will figure out a way to get 3.7.


root@mediawall:/export/TV4# apt-get install python3
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3 is already the newest version (3.5.3-1).

**Comment by bdpna** [comment]
Got 3.7 installed.  Script worked!  Thanks so much for helping me get this resolved.  Now I just need to restart my Kodi instances and re-sync the database (assume they have the latest version of PKC that doesn't have the playlist replication bug).  Thanks again for all the work you do on this.

**Comment by bdpna** [comment]
Sorry to make you open the issue again, but here's what I did.

- Shut down plex server.  
- Emptied / initialized PKC databases and shut down all Kodi instances.
- Ran script.
- Started plex media server back up and verified playlists were gone.  Let sit overnight and still no playlists in the morning.
- Started one Kodi Leia instance on on Pi, started sync on movies and tv and walked away.  Latest PKC is installed on this Pi.
- 4 hours later, I have 13,000+ playlists cyned on my Plex server again.
- Was there a step I missed on Kodi that is causing the playlists to hang around even though I initialized the PKC database?
- Can I grab a log from the Kodi instance that was running that would help you see what happened?

**Comment by croneter** [comment]
Yes, a log might help.

For EACH Kodi instance, did you stop Kodi and follow exactly the steps described in the manual https://github.com/croneter/PlexKodiConnect/wiki/How-to-automatically-delete-playlists, step `Delete all playlists on the Kodi side`? Otherwise, playlists will spawn again!

**Comment by bdpna** [comment]
This is probably user error, I will report back.  I missed deleting the playlists folder.  Now I can't get my dang libreelec ssh to work so I can't delete the folder easily.  Working on a fix.  But that has to be it.  I have no idea why I thought that folder would auto delete when I deleted the PKC database and I did indeed miss that step in your excellent instructions.  Thank you for the reply.

**Comment by croneter** [comment]
The folder won't auto delete, unfortunately

**Comment by croneter** [comment]
Issue solved?

**Comment by bdpna** [comment]
Yes user error thank you! Please close.
