### ISSUE TITLE
Resume playback doesn´t work

### ISSUE THREAD

**Issue by MikeDeltaHH** [croneter/PlexKodiConnect#840]
Hi!
I´ve installed the latest pkc build on my Vero4k with Kodi 18.2 RC and resuming playback won´t work on every media - test it serveral times and with several sources without luck - select resuming but it starts from the beginning every time! The PMS runs on a Synology DS and resuming works with the native Plex Apps perfect. Found some threads here with the same problem but all are old and closed... sorry for my bad english, i´m from germany! 

Regards!
Mike

**Comment by croneter** [comment]
Bitte lade dein DEBUG Kodi log file hoch wie hier beschrieben, nachdem du den Bug "aufgezeichnet" hast. https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by MikeDeltaHH** [comment]
Moin!
Seit gestern Abend funktioniert das plötzlich, eingeatellt hatte ich nichts... strange aber egal! Vielen Dank für das klasse Plugin!
