### ISSUE TITLE
Unable to reinstall PKC

### ISSUE THREAD

**Issue by RotorJoe** [croneter/PlexKodiConnect#842]
My first install of PKC and kodi were all done at the same time as I was brand new to the raspberrypi. Everything seemed to go well and I followed the instructions but I was having issues with videos taking a long time to load, so I found an article and decided to follow instructions for enabling direct paths which stated I'd also need to reset the DB.  This is where things went wrong initially. After resetting the database, I kept getting an error saying that "The file is encrypted or is not a database" on startup of kodi.  So then I decided to completely uninstall PKC and reinstall, but it kept failing to install from zip.  So then I uninstall/reinstall kodi.  Updated and upgraded Raspian and reinstalled kodi.  PKC still failing to install from zip.  

http://paste.debian.net/1080262/

**Comment by RotorJoe** [comment]
Looking at the logs myself I see it referencing the older version of PKC.  Maybe I didn't completely remove or uninstall something?
2019-04-27 10:40:01.523 T:1900059920   DEBUG: ------ Window Deinit (FileBrowser.xml) ------
2019-04-27 10:40:01.544 T:1900059920   DEBUG: CAddonInstaller: installing from zip '/boot/PlexKodiConnect-2.7.10.zip'
2019-04-27 10:40:01.791 T:1754448608   DEBUG: CAddonInstallJob[plugin.video.plexkodiconnect]: requires plugin.video.plexkodiconnect.movies version 2.0.9 which is not available
2019-04-27 10:40:01.791 T:1754448608   ERROR: CAddonInstallJob[plugin.video.plexkodiconnect]: The dependency on plugin.video.plexkodiconnect.movies version 2.0.9 could not be satisfied

**Comment by croneter** [comment]
Did you install the PKC repository from github? Its linked all over the place, e.g. Here: https://github.com/croneter/PlexKodiConnect/wiki/Install-from-ZIP-file

Then try to install PKC itself from the PlexKodiConnect repo - NOT from zip as that won't install 2 dependency addons.

**Comment by croneter** [comment]
Yes, simply follow https://github.com/croneter/PlexKodiConnect/wiki/Install-from-ZIP-file first to install the pkc repo, then follow https://github.com/croneter/PlexKodiConnect/wiki/Install-PKC-from-PKC-Repo to install PKC itself

**Comment by RotorJoe** [comment]
That seemed to do the trick! Thank you, always something simple.  My initial install of this was back in December so I'd forgotten everything I'd done before. Hopefully no more database issue going forward.  Thanks again
