### ISSUE TITLE
Can not find plex server on network

### ISSUE THREAD

**Issue by jsuttinger** [croneter/PlexKodiConnect#843]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO
* I did check the [existing issues on Github](https://github.com/croneter/PlexKodiConnect/issues)

## Describe the bug
PKC "could not find any Plex Server on the network"

Choosing Plex Server from a list results in "could not find any Plex Server on the network"
Manually entering IP results in a failure as well.

This issue is on an existing install. One that has been working without changes, other than updates.
I have since reset the database and PKC settings with the same issue.

## To Reproduce
Settings > Connection > Choose server / manually enter server 

## Expected behavior
I am expecting PKC to find my server and connect.

## You need to attach a KODI LOG FILE!
http://paste.kodi.tv/uzozifokiy
    
Connection failures occur line around 340

**Comment by croneter** [comment]
Well, all servers cannot be reached by PKC - you can see their IPs around line 340. Do you manage to connect to them using just Kodi?

**Comment by jsuttinger** [comment]
It's solved. No PKC issue. User / Firewall issue. 
Couple days ago I enabled the firewall on Linux Mint. Forgot about it. 
Once disabled, PKC found Plex Server. 
Sorry about that. I had a feeling it was a network issue, but pfSense showed me nothing useful.
