### ISSUE TITLE
Force transcoding not work when Direct Path enabled

### ISSUE THREAD

**Issue by rosystain** [croneter/PlexKodiConnect#846]
Some videos encoded by H264 10bit have trouble with playback on my Kodi since I set up Direct Path.
![screenshot000](https://user-images.githubusercontent.com/27495128/57207871-d4908f80-7002-11e9-8c65-dbae89363b71.png)

<img width="223" alt="Snipaste_2019-05-06_13-04-37" src="https://user-images.githubusercontent.com/27495128/57207636-84fd9400-7001-11e9-87e2-baa1bb2e4406.png">

They can be transcoded if I use Plex Web.
<img width="249" alt="Snipaste_2019-05-06_13-03-13" src="https://user-images.githubusercontent.com/27495128/57207633-8464fd80-7001-11e9-8dd1-770482399cc0.png">

And  If I switch to Addon Path on PKC , they can be transcoded well too.
<img width="227" alt="Snipaste_2019-05-06_13-12-21" src="https://user-images.githubusercontent.com/27495128/57207634-8464fd80-7001-11e9-8eb7-e4e13043980c.png">

**Comment by croneter** [comment]
Sorry, I don't speak Chinese. Could you please walk me through your issue? What exactly does not work? When does it not work?

**Comment by rosystain** [comment]
> Sorry, I don't speak Chinese. Could you please walk me through your issue? What exactly does not work? When does it not work?

Sorry, I mean PKC(set to Direct Paths) dosen't tell PLEX to transcode my video when I start playback with Force Transcode.
When I choose 'Addon paths' it works well.
There is no trouble with Direct Play but some videos I need them transcoded from h264 10bit to 8bit because my device cannot handle with them. 
Should I upload any logs?

**Comment by rosystain** [comment]
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3147710/kodi.log)

**Comment by woble** [comment]
You are asking kodi to play files directly from thier paths bypassing plex yet you expect plex to transcode as well? I don't believe that's possible.

**Comment by croneter** [comment]
Does 2.8.0 work?

**Comment by rosystain** [comment]
> Does 2.8.0 work?

Yes, 2.8.0 works.
Thank you!
