### ISSUE TITLE
Multiple Plex Media Servers: Logical solution

### ISSUE THREAD

**Issue by paegus** [croneter/PlexKodiConnect#847]
I think your approach to multiple Plex Media Servers is a bit shortsighted. Having to switch between servers is a very cumbersome approach.

> PKC can only connect to one Plex Media Server (PMS) at any point of time. Due to the way PKC works, it does not make sense to be connected to several simultaneously. How should PKC decide whether **How I Met Your Mother S02E03** should be marked as played on your PMS number 1 or your PMS number 2, or even your friend's PMS?

Using a settings option you could toggle between either list...

- each separate instance of a file separately. Kodi has no problem displaying multiple copies of the same episode/movie etc. Media tags can be used to choose the version they want to watch.
- a single instance that picks whichever source meets the user's transcoding settings with the minimum amount of work needed by the providing server. Then mark them all watched or sync the watch progress.

**Comment by croneter** [comment]
I'm very aware that the current "solution" is not ideal (using several different Kodi profiles with a dedicated PMS set per profile). 

However, implementing another soution requires a BIG overhaul no matter how it'll look like in the end. 

This is not an issue but a feature request. Please open a new feature request here: https://feathub.com/croneter/PlexKodiConnect
