### ISSUE TITLE
Dynamically create direct path mappings

### ISSUE THREAD

**Issue by thedwillis** [croneter/PlexKodiConnect#848]
Currently when using 'Direct Paths' and choosing to 'Replace plex paths' the user is only given the option to replace MOVIE, TV SHOWS, MUSIC, and PICTURES path's; would it be possible to dynamically populate this list of paths to remap from the list of libraries the person opts to sync from Plex?

**Comment by croneter** [comment]
This is not an issue but a feature request. Please vote here: https://feathub.com/croneter/PlexKodiConnect
