### ISSUE TITLE
Kodi won't sync library and crashes right after

### ISSUE THREAD

**Issue by Fischle** [croneter/PlexKodiConnect#849]
So after finishing the Installation of PKC it crashes (right after it asks you if you want to change any setting). It just closes after a huge FPS drop without any message. After re-starting my PC it doesn't crash but it won't sync the library at all, so far I've tried re-installing Kodi and addon but neither seem to work and I've tried to reset the DB but it is crashing again.

Latest log:[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3170268/kodi.log)

**Comment by croneter** [comment]
Try to reconnect to your PMS - looks like PKC can't connect

**Comment by Fischle** [comment]
> 
> 
> Try to reconnect to your PMS - looks like PKC can't connect

I did reconnect and it didn't change much either , it is still crashing moments after I get logged into Plex

Latest log : [kodi.log](https://github.com/croneter/PlexKodiConnect/files/3173122/kodi.log)

**Comment by croneter** [comment]
Try to completely reset PKC by selecting "Reset the Kodi database" in the PKC settings under Advanced. Hit Yes, then Yes again. Let Kodi reboot, and PKC redo its thing. Please share the log file after this reboot when you'll be setting up PKC again
