### ISSUE TITLE
Having Problems with Local Paths

### ISSUE THREAD

**Issue by WindfallProphet** [croneter/PlexKodiConnect#85]
I am having problems trying to get PKC working with local drives. I am probably making an error somewhere in the settings but wasn't sure where to go for help.

**Comment by WindfallProphet** [comment]
I think I fixed my problem. Currently refreshing the library and will update if the following didn't work.

Plex was setup using local drives. P:\ath\To\Media. Going over the instructions with a clearer head, thanks to coffee, I have set it up via '\\hostname\media' ('\\localhost' or '\\127.0.0.1' should theoretically work).

**Comment by croneter** [comment]
So it worked? Can we close the issue?
