### ISSUE TITLE
[Question] How could I migrate Kodi's watchlist to a new install of Kodi using PKC?

### ISSUE THREAD

**Issue by UntouchedWagons** [croneter/PlexKodiConnect#852]
My dad's current HTPC runs Xbian and it is being an incredible pain in the ass. So I want to try reinstalling Xbian and use your addon to pull content from my Plex server. What would you guys recommend I use to migrate Kodi's watch list to the plex account I made for my dad?

**Comment by croneter** [comment]
Your issue/challenge has nothing to do with PlexKodiConnect. You want to migrate your Kodi watch status to the Plex Media Server. I guess this is best asked in the official Plex forum and/or Kodi forum
