### ISSUE TITLE
Custom genres not passed to kodi

### ISSUE THREAD

**Issue by Norien** [croneter/PlexKodiConnect#853]
I set a custom genre for some tv series via Plex web with the intent of creating a smart playlist containing that genre, however the custom added genre was not added in kodi. It was expected to edit custom genre on Plex web and see it in kodi

**Comment by croneter** [comment]
Genres are all passed, but probably not instantly after you changed it, because Plex does not tell that something DID change.

Try a repair sync or Kodi database reset through the PKC settings, Advanced

**Comment by Norien** [comment]
A database repair did work, totally sucks It rescans my rather large library each time I want to add a show to that grene but it did work. Thanks!
