### ISSUE TITLE
OSMC Beta: "Wiedergabe nicht möglich" Fehlermeldung

### ISSUE THREAD

**Issue by MikeDeltaHH** [croneter/PlexKodiConnect#854]
Moin!
Ich habe einen Vero 4k mit Kodi 18.3 RC1 und eine Synology mit der aktuellsten Kodi Server Version. Wenn ich per Plex Addon abspiele ist alles ok aber wenn ich Dein Addon nutze habe ich immer wieder das Problem dass bei Auswahl einer Mediendatei es sehr lange dauert bis diese gestartet wird, bzw. dann die Meldung kommt "Wiedergabe nicht möglich. Mindestens eine Datei konnte nicht abgespielt werden..." --> die Datei wird dann zwar gestartet aber mit der Meldung im Vordergrund und wenn ich diese dann bestätige wird die Wiedergabe beendet und ich muss diese erneut starten, dann ist der Start auch sehr schnell. Wenn ich eine andere Datei auswähle geht dies dann meistens von vorne los. Das Problem tritt nicht immer auf, nach Aktivierung des Debug Logs sind die ersten drei Medien die ich ausgewählt habe auch ohne Fehler gestartet (wobei dies immer recht lange dauert), danach wieder Fehler. 
Anfangs funktionierte es problemlos, irgendwann trat dann dieser Fehler auf, ich hatte zuerst gedacht dies liegt vieleicht an irgendeinem Plugin oder Skin auf dem Vero bzw. dieser ist zugemüllt und habe dann das offizielle Plex Addon genutzt. Nun habe ich mir aber einen weiteren Vero zugelegt und mit diesem tritt das gleiche auf obwohl dieser frisch installiert ist und würde Deine Hilfe benötigen da ich Dein Addon wesentlich besser finde als das offizielle Plex Addon...

Viele Grüße!
Michael

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3221951/kodi.log)

**Comment by croneter** [comment]
Bitte installiere Kodi 18.2 und schau, ob das Problem immer noch existiert. Ich unterstütze keine RCs (=instabile Beta Versionen)

**Comment by MikeDeltaHH** [comment]
Nabend!
Eine manuelle Installation ist auf dem Vero nicht möglich, das sind auf das Gerät hin optimierte Kodi Versionen und die neuen Builds kommen immer per Firmware-Update. Mit Kodi18.2 welches auf dem anderen Vero vorher lief bestand das Problem aber auch, nur dachte ich eben dass die Kodi Installation durch Plugins oder einen Skin verhunzt wäre...

**Comment by croneter** [comment]
Hilft die neue Beta 2.7.15? Eventuell hilft's, wenn du die Kodi Datenbank noch zurücksetzt

**Comment by MikeDeltaHH** [comment]
Teste ich heute Abend mal! :)

**Comment by MikeDeltaHH** [comment]
Also die Beta 15 & 16 hat es nur verschlimmert... ich habe dann mal das Gerät auf Werkseinstellungen zurüvkgesetzt und nur mit dem OSMC Standardskin eingerichtet, jetzt tritt das Problem aktuell bei diversen Tests nur ganz selten auf.  Mir ist die Ursache aber echt schleierhaft...
Ich habe zwei Kodi-Profile angelegt für mich und meine FRau und wir haben auch verschiedene Benutzer in Plex. Jeder Kodi-Benutzer muss in Plex die Verlinkung zu plex.tv durchführen und das Addon soweit konfigurieren... wäre es eigntlich auch möglich in Kodi nur mit einem Profil, also ohne Anmeldung zu arbeiten und dann in Deinem Addon die Anmeldung so zu setzen dass beim Start des Addons man immer wählen muss welchen Plex Benutzer man anmelden will? Dann könnte man sich in Kodi zwei vrschiedene Profile mit doppelter Einrichtung hinsichtlich Skin, Menü, etc. ersparen... evtl. ist das auch eine Fehlerquelle weniger... ich weiss nur nicht wie sich das dann mit der lokalen Kodi Datenbank verhält, dass diese dann jedesmal vom Addon neu synchronisiert wird da ja zwei verschiedene Plex-Benutzer wechselseitig darauf zugreifen...

**Comment by croneter** [comment]
Bitte nutze zB auf deinem PC die stabile Kodi Version 18.2. PKC unterstützt halt leider keine instabilen Betas, weil ich dann mit Bugs fixen gar nicht mehr nachkommen würde.

Kurze Antwort zum 2.: nein, geht nicht

**Comment by MikeDeltaHH** [comment]
Alles klar, danke für Deine Mühe... ich nutze dann erstmal das offizielle Plex Addon bis die 18.3 final kommt mit dem nächsten Update im Juni und teste dann erneut...
