### ISSUE TITLE
PKC doesn't load content on Latest Kodi Beta

### ISSUE THREAD

**Issue by xinseo** [croneter/PlexKodiConnect#858]
Any release of Kodi Beta on Shield TV  after 21-05-19 results in the screen getting stuck at the message "Please wait". The videos never load. Everything syncs fine but when I press on play, it just doesn't load it. I've tried resetting PKC and setting it up again to no avail.

Netflix etc on Kodi beta works fine. Only PKC content isn't loaded.

**Comment by croneter** [comment]
Kodi Beta version are NOT supported. Please stick to stable official releases, currently 18.2.
