### ISSUE TITLE
UnicodeDecodeError on sync

### ISSUE THREAD

**Issue by DonTomate24** [croneter/PlexKodiConnect#863]
### **Describe the bug**
I receive the following notification while the initial content scan is performed:

`UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 116: invalid continuation byte`

It appears in stable version and current beta, same error. The library is the same as a few months ago, there is no change in the name of the libraries. Current version of python: Python 2.7.15 and Python 3.7.1.

I have tested in Kodi 18.2, both Android and CoreElec and I have had the same error.

### **To Reproduce**
1. Launch Kodi
2. Wait for the error while synchronizing

Once the error is given, the synchronization is canceled. However, the items already synchronized can be perfectly reproduced.

### **LOG**

https://pastebin.com/GhmkRGSp

Thank you friend ;)

**Comment by croneter** [comment]
Weird. Can you please share the Plex metadata XML for the Plex id `10957` that's causing this crash? See `XML information` here: https://support.plex.tv/articles/201998867-investigate-media-information-and-formats/

**Comment by DonTomate24** [comment]
This is the metadata XML. Checking it I see that the name of the chapter is badly written ... Could that be the reason for the error? It's strange, because I have this content a long time ago in that location and I never had an error in scanning.

Github will not let me upload this type of file, I leave it to download in Google Drive [here](https://drive.google.com/file/d/1Af3DSalke5A56zccQtVJJ89FhwIYLEll/view?usp=sharing)

**Comment by croneter** [comment]
Ouh good spotting, I think I caught the bugger. Thanks for the report!

**Comment by croneter** [comment]
Does PKC BETA version 2.8.1 help?

**Comment by DonTomate24** [comment]
Hi friend!  The error is effectively fixed, no longer generates an error when scanning.  But now the scan remains stopped at the same point where it gave the error, without giving any error, so it never completes the scan.

**Comment by croneter** [comment]
Log please. I take it that you're still sharing your library with me?

**Comment by DonTomate24** [comment]
Sorry friend, it seems that it was my kodi's fault for some kind of mistake.  Once reinstalled everything in clean works perfectly, synchronizes to 100% without any type of error.  Thank you very much for the support, we can mark as solved, you are a genius!
