### ISSUE TITLE
I can't delete files

### ISSUE THREAD

**Issue by brassica77** [croneter/PlexKodiConnect#869]
## Describe the bug
I can't delete files

## Steps to reproduce the behavior:
1. Go to any TV or movie directory
2. Right click on a video file
3. No delete option appears

## Expected behavior
A delete option should appear to be able to delete a file

No log can be given : a feature is missing somewhere, and no error message appears.
Issue happpens with Kodi 18, on a Windows 10 pc, a Windows 7 pc and an Android phone.
PKC version used is 2.8.0 .
I am the only user of the Plex server, and I activated in Plex Server the "Allow media deletion" option.
I can delete files in Plex Web Player.
If I install Kodi's Plex addon, I am able to delete files in it.
I can also delete files in the same Kodi using the Embycon addon, which means I correctly set thing in Kodi's own settings.

Any idea what I am missing?

**Comment by croneter** [comment]
Not every Plex user can delete files! Check with another Plex client like Plex for Android whether the Plex user you're using with PKC is even allowed to delete files.

**Comment by brassica77** [comment]
There are no other accounts, only this one, the admin one, and I am the only user.
I installed Plex for Android and I can delete files.
If it might help I connect with a Gmail account.

**Comment by croneter** [comment]
Try to reconnect to your PMS: choose `Choose PMS from a list` in the PKC settings. Does that help?

**Comment by brassica77** [comment]
Still the same.
I am using Plex Server on a Synology NAS by the way, if this can help.

**Comment by croneter** [comment]
If you have access to a friend's PMS, connect to that. Let PKC do its job. Then reconnect to your PMS. Does that help?

If you don't have access to a friend's PMS, try completely resetting PKC: in the PKC settings under Advanced, choose `Reset the Kodi database ...`. Then hit Yes and YES. Does that help?

**Comment by brassica77** [comment]
I don't have access to another PMS.
Resetting did not resolve the problem : tested on my home desktop, on my job's laptop, and on my mobile phone, each time using latest Kodi.

**Comment by croneter** [comment]
In the PKC settings under Connection, is 'I own this Plex Media Server' enabled? You will probably need to reboot if you change that setting

**Comment by brassica77** [comment]
This option is already enabled.

**Comment by croneter** [comment]
Please check your file`settings.xml` located in the [Kodi userdata folder](https://kodi.wiki/view/Userdata) under `addon_data\plugin.video.plexkodiconnect`.
- What does the entry `plex_allows_mediaDeletion` say?
- What does the entry `plex_restricteduser` say?

**Comment by brassica77** [comment]
I installed Plex on my desktop (so far it was installed on my Synology DS116 NAS), and it works there, using the same Plex server and Kodi settings.
So the issue occurs only on Synology.

**Comment by croneter** [comment]
Please answer my question above for Kodi on Synology

**Comment by brassica77** [comment]
Sorry, I deleted everything regarding Plex on my Synology.
I will close the issue.

**Comment by brassica77** [comment]
Hi.
I installed Plex on my PC during July and got no errors at all, I could see the Plex menu and delete files fine.
I reverted back to my Synology (the PC is causing a huge rise in the electircity bill), and the issue is still here.
But I got it narrowed down I think.

Here is what I do : 
- install the addon in Kodi and launch it,
- connect to my plex using the plex.tv/link code,
- leave by default the libraries selected in green (see capture1),
- Kodi will show a list of files and folders being scanned at the upper right with a percentage),
- browse to the video files : they are empty (see capture2 and capture3), but if I right click on  folders  I do see the Plex menu and can delete.
- looking at the options in the folders, everything looks ok (capture4).

Now, if at the beginning where the folders are in green, I click on those and unselect them, I end up being able to see and launch the files, but the Plex menu by right clicking on a folder does not show.

To reply to your comment above, first one is false, second one is true.

![Capture4](https://user-images.githubusercontent.com/33419011/62369470-01840e00-b530-11e9-8b4f-c5c286ffed62.PNG)
![Capture](https://user-images.githubusercontent.com/33419011/62369471-01840e00-b530-11e9-9265-bbb37756c1b9.PNG)
![Capture2](https://user-images.githubusercontent.com/33419011/62369472-01840e00-b530-11e9-8d96-d9efeb57f180.PNG)
![Capture3](https://user-images.githubusercontent.com/33419011/62369473-021ca480-b530-11e9-9412-07ce0c12f7f9.PNG)

**Comment by croneter** [comment]
> To reply to your comment above, first one is false, second one is true
This means that `plex_allows_mediaDeletion` is `false` - you **cannot** delete files according to your PMS settings. Additionally, you're using a [Plex managed user](https://support.plex.tv/articles/203948776-managed-users/) if `plex_restricteduser` is set to `true` - but **only** an admin user may delete files. 

Get your settings in order please!

**Comment by croneter** [comment]
> browse to the video files : they are empty (see capture2 and capture3)    

This is an entirely different issue than the one before, but yet another PMS setting that you need to change. Please see here for the solution: https://github.com/croneter/PlexKodiConnect/issues/586

**Comment by brassica77** [comment]
Sorry, I reversed : both were as you said.

Thanks for the workaround : it worked!
