### ISSUE TITLE
Problem selecting audio and subtitle stream

### ISSUE THREAD

**Issue by CooLajz** [croneter/PlexKodiConnect#87]
Using PMS: 1.0.3 with Kodi: 16.1, PKC: 1.2.11
Using plugin for playing from remote OMS server.

When streaming from PMS use transcode, i can select audio and subtitle stream, but when i select audio and subtitle stream different from default in MKV, video play always with default stream and subtitles.
When PMS use direct stream, option for selecting audio and subtitles dont even appear and PSM streaming with default track in MKV.

**Comment by croneter** [comment]
Thanks for your issue report. Related to #66 

Working on it...
