### ISSUE TITLE
Trakt Add-On: sync not working for non-english tv shows

### ISSUE THREAD

**Issue by UncleStark** [croneter/PlexKodiConnect#870]
In kodi 18.2 there were problems with the trakt script. The developer of trakt says that the "structure id" has changed. You can read the discussion https://github.com/trakt/script.trakt/issues/458

**Comment by croneter** [comment]
Thanks for your help translating! ;-)

There is no easy fix for this issue, unfortunately. Trakt needs unique ids for TV shows. Plex does not deliver them in a way I could use. Let me think about possible solutions...

**Comment by UncleStark** [comment]
but it worked in Kodi up to 18

**Comment by croneter** [comment]
Ask Trakt

**Comment by croneter** [comment]
Should be fixed with PKC version 2.8.5

You will need to manually reset the Kodi database in the PKC settings under `Advanced`. Then hit Yes, then No. Let me know here if this issue fares...

**Comment by UncleStark** [comment]
all worked, u r the best, man =) tnx
