### ISSUE TITLE
Slow Fast Forward

### ISSUE THREAD

**Issue by thecat18** [croneter/PlexKodiConnect#872]
I use plexkodiconnect on a Nvidia Shield & stream from my pc to tv & using just kodi fast forward plays fine but through plexkodiconnect even on 8x it's lagging & freezes up.  I wanted to be able resume files from my plex from another TV also it does it using plex addon in kodi-17.6.

**Comment by croneter** [comment]
Same answer as on the Plex forums: playback is entirely controlled by Kodi. As long as your PMS and the network connection are fast enough, you need to tinker with Kodi. Please ask on the Kodi forums

**Comment by thecat18** [comment]
Ok sorry to bug u.  I think it is my router I got this to work on my firetv.

**Comment by croneter** [comment]
No problem :wink:
