### ISSUE TITLE
Aura Theme's TV Show not working on 2.8.1

### ISSUE THREAD

**Issue by xinseo** [croneter/PlexKodiConnect#885]
Aura theme’s “Recently Added TV Shows” and"Recently Added Movies" widgets stopped working after the latest update of PKC. Had to revert back to 2.8.0

Movie widgets kept working, however.

**Comment by croneter** [comment]
https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Debug log file? Did you try to re-set the widgets after updating to 2.8.1? Does everything work if you navigate to the widget manually: Addons - Video Addons - PlexKodiConnect - Your Plex library name - widget in question?

**Comment by starman2908** [comment]
Hi, see someone started a thread. here is a log from 2.8.0 and 2.8.1. All TV shows/seasons are marked as watched in kodi DB, click into them and the episode status is displaying correct watch status.


[280.log](https://github.com/croneter/PlexKodiConnect/files/3289506/280.log)

[281.log](https://github.com/croneter/PlexKodiConnect/files/3289507/281.log)


![screenshot](https://user-images.githubusercontent.com/36766279/59491640-1244cb80-8e7f-11e9-94d1-9f460d8b11fb.jpg)

Cheers, 

Ryan

**Comment by xinseo** [comment]
> Hi, see someone started a thread. here is a log from 2.8.0 and 2.8.1. All TV shows/seasons are marked as watched in kodi DB, click into them and the episode status is displaying correct watch status.
> 
> [280.log](https://github.com/croneter/PlexKodiConnect/files/3289506/280.log)
> 
> [281.log](https://github.com/croneter/PlexKodiConnect/files/3289507/281.log)
> 
> ![screenshot](https://user-images.githubusercontent.com/36766279/59491640-1244cb80-8e7f-11e9-94d1-9f460d8b11fb.jpg)
> 
> Cheers,
> 
> Ryan

You might want to remove your Plex username and Tokens from those logs.

**Comment by starman2908** [comment]
whoops, cheers ;)

**Comment by croneter** [comment]
@starman2908 please start a new issue - yours does not necessarily have anything to do with this one here

**Comment by xinseo** [comment]
I enabled debug logging while on 2.8.0
After that I updated to 2.8.1 and went to the 'TV Shows' section where all the widgets were gone. Log file:
https://paste.kodi.tv/axeladokab

On 2.8.01
![IMG_20190614_150959](https://user-images.githubusercontent.com/6553354/59502503-5a7fe000-8eb7-11e9-91d8-e3a86102b766.jpg)


On 2.8.1
![IMG_20190614_151147](https://user-images.githubusercontent.com/6553354/59502516-64a1de80-8eb7-11e9-975f-ea8029580e51.jpg)

**Comment by croneter** [comment]
Should be solved in beta version 2.8.2. Please let me know

**Comment by xinseo** [comment]
Working fine so far on 2.8.2.
Now if you could just find the time to fix the issues on latest Leia builds ;)

**Comment by starman2908** [comment]
All is working pretty good on Leia for me. Have a bit of a lag going into TV show to view seasons/episodes but that's probably due to my library size... What other issues xinseo?

**Comment by xinseo** [comment]
Whenever i try to play something, It gets stuck on loading. (on Nvidia Shield)

**Comment by croneter** [comment]
@xinseo sorry, no support for nightly builds! Use Kodi 18.2.
