### ISSUE TITLE
All TV Shows Are Marked as Watched (2.8.1)

### ISSUE THREAD

**Issue by starman2908** [croneter/PlexKodiConnect#887]
Hi, 

I did a fresh install of PKC 2.8.0 on a spare PC (windows 10, kodi 18.2). Database behaviour is as expected. When updating and testing beta 2.8.1, all tv shows and seasons are marked as watched, affecting kodi db 'in progress/on deck' widgets. Oddly, when clicking in any TV Show>Season> the episodes do display correctly depending on my watched status.

Tested a few skins (default estuary, aura, bello, embuary,amber) with the same result. Here are the logs from a fresh install on a default Kodi setup fully updated before installing PKC.

[280.log](https://github.com/croneter/PlexKodiConnect/files/3289839/280.log)

[281.log](https://github.com/croneter/PlexKodiConnect/files/3289844/281.log)

![screenshot](https://user-images.githubusercontent.com/36766279/59497046-951f5380-8e8a-11e9-91da-8557b1ab2877.jpg)

Cheers,

Ryan

**Comment by croneter** [comment]
Do these episodes appear as unwatched again if you downgrade to 2.8.0?

**Comment by starman2908** [comment]
they do indeed, when downgrading all shows appear as they should.

[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3290237/kodi.log)
....here is the log of the downgrade.

**Comment by croneter** [comment]
Found the bugger, will be fixed with the next PKC beta version 2.8.2

**Comment by starman2908** [comment]
Looking in further, lots of unwatched shows appeared in progress...but just did a database reset in PKC and all is displayed back to normal.

**Comment by croneter** [comment]
Should be solved in beta version 2.8.2. Please let me know

**Comment by starman2908** [comment]
Awesome, it's working great!
