### ISSUE TITLE
TV Series and recorded TV

### ISSUE THREAD

**Issue by TheBigTalker** [croneter/PlexKodiConnect#89]
Hi there,
I am using Plex only for recording live TV (DVR) and then I have whole series saved as seasons in separate locations.  The PlexKodiConnect plugin mixes all of these shows in the same TV Shows folder on Kodi.  Is there a way to keep them separate?

**Comment by croneter** [comment]
Does this help? https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins

**Comment by croneter** [comment]
I guess it did help

**Comment by TheBigTalker** [comment]
Hi there,
Sorry for the delayed response, I was traveling.  Unfortunately, it didn't help.  I am only pulling the Season TV shows from Kodi itself, not from Plex.  For some reason, the Kodi system is combining the Plex Tv shows with the TV shows I am pulling from Plex.  Any suggestions?

**Comment by croneter** [comment]
Well that's to be expected! PKC integrates the Plex items into the Kodi database, as if these Plex items were "normal". If your TV show has e.g. the exact same show name ("The Simpsons"), they will get mixed up. 

You could separate Plex and non-Plex items with video nodes, see https://github.com/croneter/PlexKodiConnect/wiki/Video-Nodes-and-Skins. You could manually add a new label, e.g. `Non-Plex` to all Kodi items, then use your own custom made video node or smart playlist to filter for `Non-Plex`.
