### ISSUE TITLE
Python error since 2.8.3

### ISSUE THREAD

**Issue by Katsu626** [croneter/PlexKodiConnect#897]
Hi, I can't play media anymore from PKC on my Debian system.

I have the following log :

`09:07:09.828 T:139806487082752  NOTICE: PLEX.TVSHOWS: PKC add-on for tv shows started
09:07:09.863 T:139806461904640  NOTICE: PLEX.playback: playback_triage called with plex_id 1563, plex_type episode, path None, resolve True
09:07:10.007 T:139806461904640  NOTICE: PLEX.playback: Concluding playback for playqueue position 1
09:07:10.012 T:139806461904640  NOTICE: PLEX.playutils: videoCodec: {u'videocodec': u'h264', u'container': u'mkv', u'bitrate': u'2599', u'height': u'720', u'width': u'1280', u'bitDepth': u'8', u'aspectratio': None, u'resolution': u'720'}
09:07:10.014 T:139806461904640  NOTICE: PLEX.playutils: File is direct playing.
09:07:10.014 T:139806461904640  NOTICE: PLEX.playutils: The playurl is: /stockage/medias/Vidéos/Séries/Français/Diesel Brothers/Diesel Brothers 5x02.mkv
09:07:10.014 T:139806461904640  NOTICE: PLEX.playback: Done concluding playback
09:07:10.029 T:139806487082752   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'offscreen' is an invalid keyword argument for this function
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect.tvshows/default.py", line 61, in <module>
                                                play()
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect.tvshows/default.py", line 50, in play
                                                result = transfer.wait_for_transfer(source='main')
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/transfer.py", line 139, in wait_for_transfer
                                                return de_serialize(result)
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/transfer.py", line 100, in de_serialize
                                                return convert_pkc_to_listitem(result)
                                              File "/home/kodi/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/transfer.py", line 151, in convert_pkc_to_listitem
                                                offscreen=True)
                                            TypeError: 'offscreen' is an invalid keyword argument for this function
                                            -->End of Python script error report<--
09:07:10.068 T:139809836686144   ERROR: Playlist Player: skipping unplayable item: 1, path [plugin://plugin.video.plexkodiconnect.tvshows/553/?plex_id=1563&plex_type=episode&mode=play&filename=Diesel Brothers 5x02.mkv]`

So I tried to downgrade to 2.8.0 and it works again. Could you investigate on what can brake my play system since the new version ?

Good work :)

**Comment by croneter** [comment]
I need the entire debug log, see https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
Solved with 2.8.4. Let me know how it went, please

**Comment by Katsu626** [comment]
Perfect !
