### ISSUE TITLE
Kodi crashes on LibreElec on Wetek Hub 

### ISSUE THREAD

**Issue by croneter** [croneter/PlexKodiConnect#91]
I've installed LibreElec on a fresh Wetek Hub and I installed PlexKodiConnect, which works on the Android system, but I need to switch to LibreElec, as I find Android too iffy and the CEC implementation really bad.

About 2 minutes in after PKC starts scanning the Plex server, the box freezes completely.

I have saved this first log after a freeze.
For the second log I have activated debug mode in LE, so on the info overlay the MEM parameter starts going down quite fast, and when it reaches around 70mb, the box freezes. I tried this several times, it's the same behaviour each time.

If anyone would be so kind to look at the logs and tell me what the problem is, that would be awesome as I have no idea what to do next... I will tell again that under Android, the addon seems to work fine.

thanks a lot in advance...

**Comment by croneter** [comment]
I don't see any specific PKC errors, but many of these: 
```
23:25:33 T:547694690528   ERROR: CecLogMessage - Write: write failed !
```
Do you have the possibility of testing with another SD card? (Wetek Hub uses one?!? ;-)) Could be caused by a faulty memory card.

**Comment by ermethic** [comment]
I have installed LE on the internal memory, but the behavior is exactly the same.

**Comment by croneter** [comment]
Also with the CecLogMessage Error above?

**Comment by ermethic** [comment]
Yes, exactly the same...

**Comment by ermethic** [comment]
There is a LibreELEC 8.0 (alpha) image freshly made available for the Hub, I will try to install that too, with the latest PKC Krypton compatible beta, and will get back with the results...

**Comment by ermethic** [comment]
Same thing with LE 8. Memory goes down FAST and in about 30s the box freezes. 
Got two logs from here too: [log1 ](https://www.dropbox.com/s/nfc2tc6mkby5n7q/kodi17.freeze01.log) and [log2](https://www.dropbox.com/s/v5zvxxsvgcz7tf0/kodi17.freeze02.log).

**Comment by croneter** [comment]
Please try lowering the setting `Number of PMS responses to cache` to 10 in the PKC settings and report back

**Comment by ermethic** [comment]
Seems to have the same behaviour as before... Lowering the 'PMS responses to cache'  doesn't have any effect.

**Comment by croneter** [comment]
OK, next attempt. What if you deactivate Force artwork caching in the PKC Settings under sync options?

**Comment by ermethic** [comment]
That seems to do it. It finally scanned the whole library. Free mem still goes down, but a lot slower, so it manages to finish the library scan without running out.

**Comment by croneter** [comment]
Then this is a memory management issue of kodi in your particular case, nothing PKC can do about. Kodi is asked by PKC to download media art in the background, this causes memory leaks. 

Does your memory still go down once the initial scan finished and you restarted kodi?

**Comment by ermethic** [comment]
Sorry for the late response, but i needed time to test it... especially since the behaviour is really erratic.
At initial scan, if I deactivate artwork caching, everything finishes, and I can play the files.
If I leave the box idling, after a few hours I find it frozen. Every time.
[Here ](https://www.dropbox.com/s/r5x2w8n7w8mq7ee/kodi.freeze03.log?dl=0)is a log after such a freeze.
There seem to be a lot of errors like this, don't know if it has anything to do with it:
`07:55:50 T:545732727008 WARNING: Create - unsupported protocol(image) in image://https%3a%2f%2fxx-xx-xx-xxx.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.plex.direct%3a32400%2flibrary%2fmetadata%2f635%2fart%2f1465489318%3fX-Plex-Token%3dxxxxxxxxxxxxxxxxxxxx/`

**Comment by croneter** [comment]
Is this still an issue?

**Comment by ermethic** [comment]
yes it is, unfortunately, i have tried all the LE releases in the last month, they all exhibit the same behaviour...

**Comment by croneter** [comment]
I think it's a LibreElec issue. Memory leak when kodi downloads and caches art (PKC only triggers this download and caching). 

Have you opened an issue with the LibreElec team?

**Comment by tomsimmons78** [comment]
I think I've got the same problem as described here, I was using LibreElec (latest version download on 26 October).  If I performed a manual sync after a short while of alternating "working" and "compressing library" messages and a apparently constant message of "Full library sync finished" it would then freeze with just a "working" message - the whole Pi frozen.

Having found this thread I scrapped LibreElec and installed latest version of OSMC (downloaded 27 October).  Everything appeared fine, I chose manual sync, it sat there with an active animation "working" message and the mouse worked, clock progressed.  I left it running all night, following morning it was still going, then shortly afterwards I was back to the Kodi standard front end, but no albums.  I think it probably restarted?

Starting another manual sync, and it was back to freezing as it had on LibreElec.

I have cleared the artwork caching, and it has been running the sync for longer with the compressing and working message, and it's not frozen yet.

I'll report back later.


Regards

Tom

**Comment by croneter** [comment]
Be sure to use the newest PKC Beta (!!) version (install the provided beta repository), might cure some off the issues you're seeing, especially manual sync stuff. Also make sure that you restart Kodi once you've installed PKC ;-).

**Comment by tomsimmons78** [comment]
OK, I've moved to the Beta, reset the database and now when I do a manual refresh it's near instant.

The problem is it doesn't find any music, but there is no shortage believe me!

I've set logging to debug, so if anyone can tell me where to find the logs I can upload those.


Regards

Tom

**Comment by croneter** [comment]
In the PKC settings under sync options, activate music. You're done ;-)

**Comment by tomsimmons78** [comment]
Ahh, OK!

Well initially it didn’t work, but it seems that I think is because after I set it, but before I had a chance to restart Kofi, Kodi installed updates and wanted a restart, during which time it seemed to forget the setting change.

The change has been made again, a further restart initiated, and it is now sync’ing.

Not sure what the first sync was for 1900 and something entries, then it started again with 3609, which is the number of albums (according to Plex), now it’s started again with 33822 items, which I can only assume is the number of tracks in those albums?

I assume it is pulling the meta data about all the albums, track and artists from Plex for it’s own use?


Tom

**Comment by croneter** [comment]
Correct. Please stop hijacking this thread now - this thread is all about `Kodi crashes on LibreElec on Wetek Hub`. For question, please visit http://forums.plex.tv/discussion/210023/plexkodiconnect-let-kodi-talk-to-your-plex/p1

**Comment by tomsimmons78** [comment]
Sorry.

I was on LibreElec when I first had the same problem listed here, and as the same problem also existed on OSMC, and we now have a resolution I didn't consider this a hijack, more further input on the same issue.

**Comment by croneter** [comment]
@tomsimmons78 
No worries ;-)

@ermethic 
Still crashing?

**Comment by tomsimmons78** [comment]
Nope, seems to be working now.

It's retrieved everything and it's busy building the final catalogue having retrieved everything.

Tom

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ermethic** [comment]
It passes the initial scan with "force caching" set to off, but it crashes while browsing the library. I think it caches the art and doesn't release the memory.
I can browse for about an hour at max, before RAM drops to freezing levels.
Didn't try OSMC on the hub though... if tomsimmons78 says it's fine there, I will give it a go.

**Comment by tomsimmons78** [comment]
My library should be finished compiling by the time I get home, so I'll update on whether ager a period it crashes.

Tom

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by croneter** [comment]
> but it crashes while browsing the library

That is a Kodi bug. Probably related to Kodi downloading the not-yet-cached artwork. Nothing I can do, sorry

> I can browse for about an hour at max, before RAM drops to freezing levels.

Again, Kodi bug

**Comment by ermethic** [comment]
Apparently it's a LibreElec memory leak on amlogic S905 devices... still being worked on, although slowly... until then I'm back to my raspberry pi, as it seems the Wetek Hub, even if it's a nice toy, is useless if you try to use it for plex purposes (unless on android).
The issue can be followed on the [LibreElec Amlogic forums](https://forum.libreelec.tv/forum-38.html), where kszaq seems to be the main developer.
[Here](https://forum.libreelec.tv/thread-1924-post-17067.html#pid17067) and [here](https://forum.libreelec.tv/thread-1924-post-17212.html#pid17212) are the posts where kszaq mentions the leak, apparently it's there on the Krypton builds too.

This can be closed as far as I'm concerned.

**Comment by croneter** [comment]
Thanks for verifying this!
