### ISSUE TITLE
Not authorized

### ISSUE THREAD

**Issue by kiaengima27** [croneter/PlexKodiConnect#914]
Just tried Plex connect on a default version of Kodi using version 2.8.6 and keep getting a message that I'm not authorised through Plex. Keep entering my code on Plex website and it keeps going in a loop asking me to authorize.

Didn't have s problem trying it in my phone using version 2.8.5

**Comment by croneter** [comment]
It's called PlexKodiConnect...

Try resetting: in the PKC settings under Advanced, hit Reset the Kodi database. Then choose Yes and Yes again. 

If that does not help, share your log file: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by croneter** [comment]
What is the status here?

**Comment by kiaengima27** [comment]
Hi sorry forgot to reply. Seems to working fine now after I set the sever address to the IP of my server rather than trying to find it manually

**Comment by croneter** [comment]
Awesome!
