### ISSUE TITLE
Cannot use CastagnaIT/plugin.video.netflix and Sandmann79/plugin.video.amazon-test along with PlexKodiConnect

### ISSUE THREAD

**Issue by padok** [croneter/PlexKodiConnect#920]
## My current setup
Hey!
I'm currently running running Kodi 18.3 with CastagnaIT/plugin.video.netflix and Sandmann79/plugin.video.amazon-test add-ons.
The setup currently enables both of these add-ons to create placeholder directory trees in there add-on data directories, which can easily be integrated using Kodis internal scrapers.

```
plugin.video.amazon-test
├── Movies
│    └── _Movie_name_
│           └── _Movie_name_.strm
└── TV
    └── _Show_name_
            └── _Show_name_ - S00E00 - _Episode_name_.strm
plugin.video.netflix
├── movies
│    └── _Movie_name_
│           └── _Movie_name_.strm
└── shows
    └── _Show_name_
            └── _Show_name_ - S00E00 - _Episode_name_.strm
```

The strm files itself contains internal add-on links, that can start every add-on process needed for proxying or playback.
That way it's easily possible to merge my netflix, amazon and offline librarys and keep them up to date, since the add-ons keep there directory trees in sync and Kodis scraper do there thing.
The Amazon add-on even provides additional information through *.nfo files.

## Describe the bug
Since I'm tryng to integrate PKC in my current setup I installed the add-on after the setup explained above and went through the setup process with **Addon Paths**. Because my server is not located on the same network as my streaming devices and does not have a static permanent IP or host name I need **PMS**'s functionality.

Afterwards the library gets synchronized and it resets my current setup, all content definition of my sources are set to None now.
Kodi integrates only the Plex content now.
When I attempt to reconfigure my setup (setting up content types of sources) I always end up missing either the movie or show categories of my plex share.

## Suggestion
I would love to get an option for PKS, that also create a placeholder directory trees using strm files. Since the only important information to know that I got from your wiki is the URL "https://192.168.1.2:32400/library/metadata/1234" strm files could look like this:
```
plugin://plugin.video.plexkodiconnect/?mode=PlayVideo&url=https%3A%2F%2F192.168.1.2%3A32400%2Flibrary%2Fmetadata%2F1234
```
That way the PMS can be provided with all needed information.

It could also be a great alternative to writing directly to Kodis database, that I would consider as risky.

**Comment by croneter** [comment]
This is not a bug but 2 different feature requests 😉 . As such, please open a corresponding ticket here: https://feathub.com/croneter/PlexKodiConnect

**Feature Request 1: use PKC alongside `plugin.video.netflix` and `plugin.video.amazon-test`**
The setup you want is indeed impossible right now. 
As a workaround, you could use PKC with a dedicated Kodi profile. You'd need to switch Kodi profiles when switching from PKC to either of the other add-ons. 

**Feature Request 2: use PKC with a PMS/IP addresses that potentially change**
Really not on the roadmap of PKC right now. Either use the standard plex.tv redirect or set-up your own static dns redirect (I think that's the technique) using e.g. duckdns.org

**Comment by padok** [comment]
I went ahead and created Feature Request 1.
https://feathub.com/croneter/PlexKodiConnect/+55

Thanks for your help!

**Comment by alazabe** [comment]
@croneter Hi sorry to ping you ,but is there any chance we see strm support this year ? 
this will be amazing to see
