### ISSUE TITLE
Unplayed movie getting marked played

### ISSUE THREAD

**Issue by dazedcrazy** [croneter/PlexKodiConnect#924]
## Describe the bug
Unplayed movie being marked as played

## To Reproduce
1. Stop Kodi
2. Mark movie as unplayed in Plex Web
3. Restart Kodi
4. Movie gets marked as played

## Expected behavior
Movie stays unplayed

Log: [kodi.old.log](https://github.com/croneter/PlexKodiConnect/files/3387763/kodi.old.log)
``plex_id: 89537 - Hellboy`` is what keeps getting marked as played in the log. There is another it is also happening with but i just ran the log with one to make it easier.

**Comment by croneter** [comment]
I cannot reproduce what you're describing. Does this work for every single movie? Do you start out with a movie that has been WATCHED, then shut down Kodi, then mark unwatched?

Make sure you wait for a while as all playstates get synced a bit later...

**Comment by dazedcrazy** [comment]
It's something got to do with trakt addon becaue if i remove Hellyboy (2004) for my history on trakt it stops marking Hellboy (2019) as watched. The other movie this happens with is Dumbo (1941) and Dumbo (2019)

**Comment by croneter** [comment]
So it's a Trakt bug :stuck_out_tongue_closed_eyes:
