### ISSUE TITLE
PKC "On Deck" and "Newly Added" missing

### ISSUE THREAD

**Issue by stackguard** [croneter/PlexKodiConnect#938]
## Help yourself
* I did try to restart Kodi :-)
* I checked the [PKC Frequently Asked Questions on the PKC wiki](https://github.com/croneter/PlexKodiConnect/wiki/faq)
* I did try to reset the Kodi database by going to `PKC Settings -> Advanced -> "Reset the database and optionally reset PlexKodiConnect"` and then hitting YES, NO

## Describe the bug
I installed CoreElec on a new device in my living room with Kodi 18.3.
After the first install, and PKC configured, I went into tweaking the skin, and the PKC "On Deck" and "Newly Added" widgets are not there.
I used to have it on a Kodi 18.1 and 17.3 with previous versions of PKC, either on a full Linux Box, on a MacOS computer and on a LibreElec mini-pc.
Any Ideas why the widgets are missing? Something to do with the latest PKC? or kodi 18.3? I am really missing the usability of the widgets on the Aura Skin.

## To reproduce.
Install CoreElec (latest 9.0.3)
Install and configure PKC
Add a customizable skin
Widgets aren't there

**Comment by stackguard** [comment]
Just something I noticed - "PKC on deck (fast)" exists for movies, but only that one

**Comment by croneter** [comment]
Here is the solution: https://github.com/croneter/PlexKodiConnect/issues/835
