### ISSUE TITLE
PKC use https Kodi v18 (Libreelec)

### ISSUE THREAD

**Issue by gurabli** [croneter/PlexKodiConnect#939]
Hi,
I have Plex server running in VPS and using Traefic for https and reverse proxy. 
I also use direct paths, working perfectly fine.
However, I would like to make sure my connection to PMS from PKC is encrypted. How can I check if encrypted connection is used or not? And how to configure PMS and PKC to make it use https?

BTW, if not using SSL, but using Direct Paths, what kind of inforation is going between PKC and PMS? No video stream since it is played locally, but any sensitive data I should be worried about?

Thanks

**Comment by croneter** [comment]
* Use Plex Web to change your PMS settings, https://support.plex.tv/articles/206225077-how-to-use-secure-server-connections/. Choose "required" 
* in the PKC Kodi settings under "Connection", check that "Enable https" is indeed enabled 
Check your Kodi

**Comment by croneter** [comment]
Nope, no sensitive data - just your play states - the movie you're playing and stuff...
