### ISSUE TITLE
PKC not doing background sync

### ISSUE THREAD

**Issue by gurabli** [croneter/PlexKodiConnect#940]
Hi,
I have PKC configured on Coreelec latest 9.0.3, and added latest stable PKC. I configured direct paths (SMB), everything works very nice. Initial sync performed nicely, everything plays. 
The problem is that there is no background sync happening. I need to restart Coreelec box, than an initial sync is performed and everything shows up correctly. Any idea what could I try? I am the admin and owner of PMS. I deleted all the databases in Kodi, did a full recreation of db in PKC. 
Using skin Aeon Nox: Silvo.

Any ideas what to try and if it is a know problem?

BTW: if I share my library with my brother, he connects to my PMS with his email/pass, will he be able to have backround sync? It works for him now, and new episodes are added fine, just as playing.

**Comment by croneter** [comment]
In the Kodi PKC settings, is `Enable constant background sync` enabled? If you toggle this setting, be sure to restart Kodi. 

Please share your DEBUG Kodi log file while Kodi is running and you're adding a new movie or episode to Plex - that is then NOT showing up in Plex: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by gurabli** [comment]
> In the Kodi PKC settings, is `Enable constant background sync` enabled? If you toggle this setting, be sure to restart Kodi.
> 
> Please share your DEBUG Kodi log file while Kodi is running and you're adding a new movie or episode to Plex - that is then NOT showing up in Plex: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Yes, Constant background sync is enabled (it was never disabled).
Here is the Kodi Log: [Pastebin](http://pasted.co/dbd68c5e)
I see some websocket errors, not sure if that is related in any way. 
I did a restart of PKC add-on, there you could see it was working perfectly fine, and the downloaded new episode of CM was added perfectly. 
Thanks!

**Comment by croneter** [comment]
Yes, pkc background sync needs websockets to work, sorry. Please configure your Cloudflare and network set-up accordingly

**Comment by croneter** [comment]
Alternatively, you can decrease the number of minutes between full library syncs in the PKC settings

**Comment by gurabli** [comment]
Yes, it turned out it was CF. Disabling CF for plex subdomain made it work. But I don't get it, as CF supports websocket? Any idea?
It is so good in terms of security to use CF. 

Is full library sync putting heavy load on anything? Is it safe to set it to 5 or 10 minutes?

**Comment by croneter** [comment]
It's safe

You might need to open another websockets port on CF

**Comment by gurabli** [comment]
> It's safe
> 
> You might need to open another websockets port on CF

CF does allow webscockets, but on a free plan (even on a paid, but not Enterprise plan) it limits the number of calls. They don't state a limit, but it is enforced on use case. I had a high limit since adding two times the new library. Now I enabled CF again for PMS and it is working. Will see and check if they ban again. If yes, I will lower full scan or disable CF routing. 

Thanks for your help!
