### ISSUE TITLE
ERROR: CCurlFile::Open failed with code 404

### ISSUE THREAD

**Issue by davboc** [croneter/PlexKodiConnect#944]
Hi,

I installed this addon on my raspberry PI2 with KODI 18. 

I can see all videos of my library but I can't open no one of them. 
The error is always the 404, indeed if I try to copy-past the address reported in kodi log on a browser it shows me 404 error. 

This is the complete debug log

Thanks in advance!

**Comment by croneter** [comment]
Please share the entire DEBUG log file as explained here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

**Comment by davboc** [comment]
> Please share the entire DEBUG log file as explained here: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Sorry mate, 

this is the full log
https://pastebin.com/zrqhnHeb

**Comment by croneter** [comment]
You still have pieces ox PlexBMC installed
'''
2019-07-29 00:31:58.463 T:1776677600   ERROR: GetDirectory - Error getting plugin://plugin.video.plexbmc/?
'''
Please wipe you're Kodi installation and try again from scratch

**Comment by davboc** [comment]
Thanks @croneter. There is a way to do this without lose all kodi settings?

**Comment by croneter** [comment]
I'd suggest you make a complete Kodi backup. Then reset Kodi entirely - that's the point :wink:. I guess some setting or old add-on is interfering with PlexKodiConnect

**Comment by davboc** [comment]
no mate @croneter ... I tried to completely remove .kodi folder, reinstall PKC from the beginning but the behavior is the same, I can't open any file :(

**Comment by davboc** [comment]
Sorry, my bad. There was a problem on nas permissions linked to the last version of Plex. I'm so sorry for bother you :(
