### ISSUE TITLE
Newly added episodes not in Kodi

### ISSUE THREAD

**Issue by hstamas** [croneter/PlexKodiConnect#95]
Unfortunately I don't have a log file for this but all of the sudden newly added episodes are not appearing in Kodi. 

They appear in Plex but a manual sync does nothing. If I use plex companion to fling the "missing" show to Kodi, a different show and episode plays. The correct episode plays fine in Plex though. 

The next time I get a new episode of something and if this happens again I will upload logs.

**Comment by croneter** [comment]
Logs!! ;-)
