### ISSUE TITLE
Playing from widgets does not work 

### ISSUE THREAD

**Issue by richardap1** [croneter/PlexKodiConnect#96]
I have done a reset of the kodi database and moved to directpaths, however using Video addons -> TV shows -> On deck as a widget in the Titan skin i get a stange issue where some items play from the widget fine, others don't.  Looking at the logs, some jst go straight to the direct path and play others try to use the plugin (log section below).  Both items will play fine if not using a widget.
Thanks
Rich

15:37:37 T:12788  NOTICE: Using Image Cache Thread Count: 25 -> 1
15:37:37 T:12788  NOTICE: PlexKodiConnect Playlist -> Initiated video playlist
15:37:37 T:12788  NOTICE: PlexKodiConnect PlaybackUtils -> Play called.
15:37:37 T:12788  NOTICE: PlexKodiConnect PlayUtils -> File is direct playing.
15:37:37 T:12788  NOTICE: PlexKodiConnect PlayUtils -> The playurl is: D:\HDTV 4\Bad Education\Season 1\Bad Education - S01E04.mkv
15:37:37 T:12788  NOTICE: PlexKodiConnect API -> Found external subs: []
15:37:37 T:12788  NOTICE: PlexKodiConnect PlaybackUtils -> Play playlist.
15:37:37 T:12788 WARNING: CPythonInvoker(176, C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect.tvshows-1.0.1\default.py): the python script "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect.tvshows-1.0.1\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::Player,class XBMCAddon::xbmc::PlayList
15:37:37 T:12556   ERROR: PlayMedia could not play media: plugin://plugin.video.plexkodiconnect.tvshows/?dbid=1126&mode=play&id=808378
15:37:48 T:8412  NOTICE: PlexKodiConnect PlexCompanion -> Client is no longer registered
15:37:48 T:8412  NOTICE: PlexKodiConnect PlexCompanion -> Plex Companion still running on port 3005
15:38:17 T:11720  NOTICE: Using Image Cache Thread Count: 25 -> 1
15:38:17 T:11720  NOTICE: PlexKodiConnect Parameter string: ?dbid=1706&mode=play&id=4924
15:38:17 T:11720  NOTICE: PlexKodiConnect DownloadUtils -> Request session does not exist: start one
15:38:17 T:11720  NOTICE: PlexKodiConnect DownloadUtils -> Verify SSL certificates set to: false
15:38:17 T:11720  NOTICE: PlexKodiConnect DownloadUtils -> SSL client side certificate set to: None
15:38:17 T:11720  NOTICE: PlexKodiConnect DownloadUtils -> Set server: https://192.168.0.2:32400
15:38:17 T:11720  NOTICE: PlexKodiConnect DownloadUtils -> Set token: xxxxxxx
15:38:17 T:11720  NOTICE: PlexKodiConnect DownloadUtils -> Set userId: XXXXXXX
15:38:17 T:11720  NOTICE: PlexKodiConnect DownloadUtils -> Set username: Rich
15:38:17 T:11720  NOTICE: PlexKodiConnect DownloadUtils -> Requests session started on: https://192.168.0.2:32400
15:38:17 T:11720  NOTICE: Using Image Cache Thread Count: 25 -> 1
15:38:17 T:11720  NOTICE: PlexKodiConnect Playlist -> Initiated video playlist
15:38:17 T:11720  NOTICE: PlexKodiConnect PlaybackUtils -> Play called.
15:38:24 T:11720  NOTICE: PlexKodiConnect PlayUtils -> File is direct playing.
15:38:24 T:11720  NOTICE: PlexKodiConnect PlayUtils -> The playurl is: G:\Media\HDTV\Black Sails\Season 2\Black Sails S02E05.mkv
15:38:24 T:11720  NOTICE: PlexKodiConnect PlaybackUtils -> Setting up properties in playlist.
15:38:24 T:11720  NOTICE: PlexKodiConnect API -> Found external subs: []
15:38:24 T:11720  NOTICE: PlexKodiConnect PlaybackUtils -> Play as a widget item.

**Comment by croneter** [comment]
Please post the entire log

**Comment by richardap1** [comment]
This only affect items On Deck that haven't been played. Once they have been played they will for fine.

Here is a log.  Tried to play Bad education (Unplayed next episode) from On Deck it fails. Go and play the same episode from the main TV shows view it works -> fast forward to 5 minutes (12%) and go back to the home screen, play same file from widget and it works fine.

15:55:20 T:3324  NOTICE: PlexKodiConnect Playlist -> Initiated video playlist
15:55:20 T:3324  NOTICE: PlexKodiConnect PlaybackUtils -> Play called.
15:55:20 T:3324  NOTICE: PlexKodiConnect PlayUtils -> File is direct playing.
15:55:20 T:3324  NOTICE: PlexKodiConnect PlayUtils -> The playurl is: D:\HDTV 4\Bad Education\Season 1\Bad Education - S01E04.mkv
15:55:20 T:3324  NOTICE: PlexKodiConnect PlaybackUtils -> Setting up properties in playlist.
15:55:20 T:3324  NOTICE: PlexKodiConnect PlaybackUtils -> Adding main item to playlist.
15:55:20 T:3324  NOTICE: PlexKodiConnect API -> Found external subs: []
15:55:20 T:3324  NOTICE: PlexKodiConnect PlaybackUtils -> Play playlist.
15:55:20 T:3324 WARNING: CPythonInvoker(44, C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect.tvshows-1.0.1\default.py): the python script "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect.tvshows-1.0.1\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::Player,class XBMCAddon::xbmc::PlayList
15:55:20 T:1304   ERROR: PlayMedia could not play media: plugin://plugin.video.plexkodiconnect.tvshows/?dbid=1126&mode=play&id=808378
15:55:27 T:9852  NOTICE: PlexKodiConnect PlexCompanion -> Client is no longer registered
15:55:27 T:9852  NOTICE: PlexKodiConnect PlexCompanion -> Plex Companion still running on port 3005
15:56:31 T:9852  NOTICE: PlexKodiConnect PlexCompanion -> Client is no longer registered
15:56:31 T:9852  NOTICE: PlexKodiConnect PlexCompanion -> Plex Companion still running on port 3005
15:57:34 T:9852  NOTICE: PlexKodiConnect PlexCompanion -> Client is no longer registered
15:57:34 T:9852  NOTICE: PlexKodiConnect PlexCompanion -> Plex Companion still running on port 3005
15:58:37 T:9852  NOTICE: PlexKodiConnect PlexCompanion -> Client is no longer registered
15:58:37 T:9852  NOTICE: PlexKodiConnect PlexCompanion -> Plex Companion still running on port 3005
15:59:41 T:9852  NOTICE: PlexKodiConnect PlexCompanion -> Client is no longer registered
15:59:41 T:9852  NOTICE: PlexKodiConnect PlexCompanion -> Plex Companion still running on port 3005
15:59:41 T:10236  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting GUI proc (6.0.15)
15:59:56 T:1304  NOTICE: DVDPlayer: Opening: D:\HDTV 4\Bad Education\Season 1\Bad Education - S01E04.mkv
15:59:56 T:1304 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
15:59:56 T:5476  NOTICE: Creating InputStream
15:59:56 T:5476  NOTICE: Creating Demuxer
15:59:56 T:5476  NOTICE: Opening stream: 0 source: 256
15:59:56 T:5476  NOTICE: Creating video codec with codec id: 28
15:59:56 T:5476  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
15:59:56 T:5476  NOTICE: Creating video thread
15:59:56 T:5476  NOTICE: Opening stream: 1 source: 256
15:59:56 T:5476  NOTICE: Finding audio codec for: 86019
15:59:56 T:7588  NOTICE: running thread: video_thread
15:59:56 T:5476  NOTICE: Creating audio thread
15:59:56 T:7588  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
15:59:56 T:10540  NOTICE: running thread: CDVDPlayerAudio::Process()
15:59:56 T:10540  NOTICE: Creating audio stream (codec id: 86019, channels: 2, sample rate: 48000, no pass-through)
15:59:56 T:7588  NOTICE:  fps: 25.000000, pwidth: 1280, pheight: 720, dwidth: 1280, dheight: 720
15:59:56 T:7588  NOTICE: Display resolution DESKTOP : 1920x1080@ 60.00 - Full Screen (16)
15:59:56 T:7588  NOTICE: D3D: rendering method forced to DXVA processor
15:59:56 T:7588  NOTICE: DXVA::CProcessorHD::InitProcessor - Supported deinterlace methods: Blend:yes, Bob:yes, Adaptive:yes, MoComp:no.
15:59:56 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: Playlist.OnAdd Data: {u'item': {u'type': u'episode', u'id': 1126}, u'playlistid': 1, u'position': 0}
15:59:56 T:1304 WARNING: CWinRenderer::UpdateVideoFilter - chosen scaling method 1 is not supported by renderer
15:59:56 T:10540  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 32
15:59:56 T:8524  NOTICE: Previous line repeats 1 times.
15:59:56 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnPlay Data: {u'item': {u'type': u'episode', u'id': 1126}, u'player': {u'playerid': 1, u'speed': 1}}
15:59:56 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Currently playing file is: D:\HDTV 4\Bad Education\Season 1\Bad Education - S01E04.mkv
15:59:56 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Playing itemtype is (or appears to be): episode
15:59:56 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Found Plex id 808378 for Kodi id None for type episode
15:59:56 T:10540  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 32
15:59:56 T:8524  NOTICE: Using Image Cache Thread Count: 25 -> 1
15:59:56 T:8524  NOTICE: PlexKodiConnect API -> Found external subs: []
15:59:56 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Window properties set for direct paths!
15:59:56 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Finish playback startup
15:59:56 T:8524  NOTICE: PlexKodiConnect Player -> ONPLAYBACK_STARTED: D:\HDTV 4\Bad Education\Season 1\Bad Education - S01E04.mkv itemid: 808378
15:59:56 T:8524  NOTICE: PlexKodiConnect Player -> Playing itemtype is: episode
15:59:56 T:8524  NOTICE: PlexKodiConnect Player -> ADDING_FILE: {'itemType': u'episode', 'currentfile': 'D:\\HDTV 4\\Bad Education\\Season 1\\Bad Education - S01E04.mkv', 'SubtitleStreamIndex': '', 'AudioStreamIndex': 1, 'item_id': u'808378', 'Type': u'episode', 'playmethod': u'DirectPlay', 'refresh_id': u'808376', 'currentPosition': 0, 'playcount': 0, 'runtime': 1689, 'fileid': 2248}
15:59:58 T:7588  NOTICE: DXVA::CDecoder::Close - closing decoder
15:59:58 T:7588  NOTICE: DXVA::Close - closing decoder context
15:59:58 T:7588  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
15:59:58 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnSeek Data: {u'item': {u'type': u'episode', u'id': 1126}, u'player': {u'playerid': 1, u'seekoffset': {u'hours': 0, u'seconds': 0, u'minutes': 3, u'milliseconds': 0}, u'speed': 1, u'time': {u'hours': 0, u'seconds': 2, u'minutes': 3, u'milliseconds': 399}}}
15:59:58 T:10540  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 32
16:00:01 T:7588  NOTICE: DXVA::CDecoder::Close - closing decoder
16:00:01 T:7588  NOTICE: DXVA::Close - closing decoder context
16:00:01 T:7588  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
16:00:01 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnSeek Data: {u'item': {u'type': u'episode', u'id': 1126}, u'player': {u'playerid': 1, u'seekoffset': {u'hours': 0, u'seconds': 30, u'minutes': 0, u'milliseconds': 0}, u'speed': 1, u'time': {u'hours': 0, u'seconds': 37, u'minutes': 3, u'milliseconds': 520}}}
16:00:01 T:10540  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 32
16:00:03 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnSeek Data: {u'item': {u'type': u'episode', u'id': 1126}, u'player': {u'playerid': 1, u'seekoffset': {u'hours': 0, u'seconds': 0, u'minutes': 1, u'milliseconds': 0}, u'speed': 1, u'time': {u'hours': 0, u'seconds': 40, u'minutes': 4, u'milliseconds': 40}}}
16:00:03 T:7588  NOTICE: DXVA::CDecoder::Close - closing decoder
16:00:03 T:7588  NOTICE: DXVA::Close - closing decoder context
16:00:03 T:7588  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
16:00:03 T:10540  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 32
16:00:05 T:7588  NOTICE: DXVA::CDecoder::Close - closing decoder
16:00:05 T:7588  NOTICE: DXVA::Close - closing decoder context
16:00:05 T:7588  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
16:00:05 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnSeek Data: {u'item': {u'type': u'episode', u'id': 1126}, u'player': {u'playerid': 1, u'seekoffset': {u'hours': 0, u'seconds': 30, u'minutes': 0, u'milliseconds': 0}, u'speed': 1, u'time': {u'hours': 0, u'seconds': 13, u'minutes': 5, u'milliseconds': 0}}}
16:00:05 T:10540  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 32
16:00:07 T:1304  NOTICE: CDVDPlayer::CloseFile()
16:00:07 T:1304  NOTICE: DVDPlayer: waiting for threads to exit
16:00:07 T:5476  NOTICE: CDVDPlayer::OnExit()
16:00:07 T:5476  NOTICE: Closing stream player 1
16:00:07 T:5476  NOTICE: Waiting for audio thread to exit
16:00:07 T:10540  NOTICE: thread end: CDVDPlayerAudio::OnExit()
16:00:07 T:5476  NOTICE: Closing audio device
16:00:07 T:5476  NOTICE: Deleting audio codec
16:00:07 T:5476  NOTICE: Closing stream player 2
16:00:07 T:5476  NOTICE: waiting for video thread to exit
16:00:07 T:7588  NOTICE: thread end: video_thread
16:00:07 T:5476  NOTICE: deleting video codec
16:00:07 T:5476  NOTICE: DXVA::CDecoder::Close - closing decoder
16:00:07 T:5476  NOTICE: DXVA::Close - closing decoder context
16:00:07 T:1304  NOTICE: DVDPlayer: finished waiting
16:00:07 T:1304  NOTICE: CDVDPlayer::CloseFile()
16:00:07 T:1304  NOTICE: DVDPlayer: waiting for threads to exit
16:00:07 T:1304  NOTICE: DVDPlayer: finished waiting
16:00:07 T:1304  NOTICE: CDVDPlayer::CloseFile()
16:00:07 T:1304  NOTICE: DVDPlayer: waiting for threads to exit
16:00:07 T:1304  NOTICE: DVDPlayer: finished waiting
16:00:07 T:8524  NOTICE: PlexKodiConnect Player -> ONPLAYBACK_STOPPED
16:00:07 T:8524  NOTICE: PlexKodiConnect Player -> Played_information: {'D:\\HDTV 4\\Bad Education\\Season 1\\Bad Education - S01E04.mkv': {'itemType': u'episode', 'currentfile': 'D:\\HDTV 4\\Bad Education\\Season 1\\Bad Education - S01E04.mkv', 'SubtitleStreamIndex': '', 'AudioStreamIndex': 1, 'item_id': u'808378', 'Type': u'episode', 'playmethod': u'DirectPlay', 'refresh_id': u'808376', 'currentPosition': 314.09600830078125, 'playcount': 0, 'runtime': 1689, 'fileid': 2248}}
16:00:07 T:8524  NOTICE: PlexKodiConnect Player -> Percent complete: 0.185965665069 Mark played at: 0.9
16:00:07 T:8524  NOTICE: PlexKodiConnect Player -> Clear playlist properties.
16:00:07 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnStop Data: {u'item': {u'type': u'episode', u'id': 1126}, u'end': False}
16:00:07 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: VideoLibrary.OnUpdate Data: {u'item': {u'type': u'episode', u'id': 1126}}
16:00:07 T:1168  NOTICE: script.tv.show.next.aired: ### TV Show - Next Aired starting GUI proc (6.0.15)
16:00:09 T:9180  NOTICE: Using Image Cache Thread Count: 25 -> 1
16:00:09 T:9180  NOTICE: plugin.video.plexkodiconnect started
16:00:09 T:9180  NOTICE: PlexKodiConnect - Full sys.argv received: ['plugin://plugin.video.plexkodiconnect/', '25', '?id=2&mode=ondeck&type=tvshows&tagname=TV Shows&limit=100']
16:00:09 T:9180  NOTICE: PlexKodiConnect DownloadUtils -> Request session does not exist: start one
16:00:09 T:9180  NOTICE: PlexKodiConnect DownloadUtils -> Verify SSL certificates set to: false
16:00:09 T:9180  NOTICE: PlexKodiConnect DownloadUtils -> SSL client side certificate set to: None
16:00:09 T:9180  NOTICE: PlexKodiConnect DownloadUtils -> Set server: https://192.168.0.2:32400
16:00:09 T:9180  NOTICE: PlexKodiConnect DownloadUtils -> Set token: xxxxxxx
16:00:09 T:9180  NOTICE: PlexKodiConnect DownloadUtils -> Set userId: xxxxxxx
16:00:09 T:9180  NOTICE: PlexKodiConnect DownloadUtils -> Set username: Rich
16:00:09 T:9180  NOTICE: PlexKodiConnect DownloadUtils -> Requests session started on: https://192.168.0.2:32400
16:00:09 T:9920  NOTICE: Using Image Cache Thread Count: 25 -> 1
16:00:09 T:9920  NOTICE: plugin.video.plexkodiconnect started
16:00:09 T:9920  NOTICE: PlexKodiConnect - Full sys.argv received: ['plugin://plugin.video.plexkodiconnect/', '26', '?id=2&mode=recentepisodes&type=tvshows&tagname=TV Shows&limit=100']
16:00:10 T:9180  NOTICE: Using Image Cache Thread Count: 25 -> 1
16:00:10 T:9180  NOTICE: PlexKodiConnect Playlist -> Initiated video playlist
16:00:10 T:9180  NOTICE: Using Image Cache Thread Count: 25 -> 1
16:00:10 T:9180  NOTICE: Previous line repeats 28 times.
16:00:10 T:9180  NOTICE: plugin.video.plexkodiconnect stopped
16:00:10 T:9180 WARNING: CPythonInvoker(47, C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py): the python script "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::Player,class XBMCAddon::xbmc::PlayList
16:00:10 T:9920  NOTICE: plugin.video.plexkodiconnect stopped
16:00:10 T:9920 WARNING: CPythonInvoker(49, C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py): the python script "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::Player
16:00:12 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: Playlist.OnClear Data: {u'playlistid': 1}
16:00:12 T:2176  NOTICE: Using Image Cache Thread Count: 25 -> 1
16:00:12 T:2176  NOTICE: PlexKodiConnect Parameter string: ?dbid=1126&mode=play&id=808378
16:00:12 T:2176  NOTICE: PlexKodiConnect DownloadUtils -> Request session does not exist: start one
16:00:12 T:2176  NOTICE: PlexKodiConnect DownloadUtils -> Verify SSL certificates set to: false
16:00:12 T:2176  NOTICE: PlexKodiConnect DownloadUtils -> SSL client side certificate set to: None
16:00:12 T:2176  NOTICE: PlexKodiConnect DownloadUtils -> Set server: https://192.168.0.2:32400
16:00:12 T:2176  NOTICE: PlexKodiConnect DownloadUtils -> Set token: xxxxxxx
16:00:12 T:2176  NOTICE: PlexKodiConnect DownloadUtils -> Set userId: xxxxxxx
16:00:12 T:2176  NOTICE: PlexKodiConnect DownloadUtils -> Set username: Rich
16:00:12 T:2176  NOTICE: PlexKodiConnect DownloadUtils -> Requests session started on: https://192.168.0.2:32400
16:00:12 T:2176  NOTICE: Using Image Cache Thread Count: 25 -> 1
16:00:12 T:2176  NOTICE: PlexKodiConnect Playlist -> Initiated video playlist
16:00:12 T:2176  NOTICE: PlexKodiConnect PlaybackUtils -> Play called.
16:00:12 T:2176  NOTICE: PlexKodiConnect PlayUtils -> File is direct playing.
16:00:12 T:2176  NOTICE: PlexKodiConnect PlayUtils -> The playurl is: D:\HDTV 4\Bad Education\Season 1\Bad Education - S01E04.mkv
16:00:12 T:2176  NOTICE: PlexKodiConnect API -> Found external subs: []
16:00:12 T:2176  NOTICE: PlexKodiConnect PlaybackUtils -> Play as a widget item.
16:00:12 T:1304  NOTICE: DVDPlayer: Opening: D:\HDTV 4\Bad Education\Season 1\Bad Education - S01E04.mkv
16:00:12 T:1304 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:00:12 T:832  NOTICE: Creating InputStream
16:00:12 T:832  NOTICE: Creating Demuxer
16:00:12 T:832  NOTICE: Opening stream: 0 source: 256
16:00:12 T:832  NOTICE: Creating video codec with codec id: 28
16:00:12 T:832  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
16:00:12 T:832  NOTICE: Creating video thread
16:00:12 T:832  NOTICE: Opening stream: 1 source: 256
16:00:12 T:832  NOTICE: Finding audio codec for: 86019
16:00:12 T:13288  NOTICE: running thread: video_thread
16:00:12 T:832  NOTICE: Creating audio thread
16:00:12 T:12768  NOTICE: running thread: CDVDPlayerAudio::Process()
16:00:12 T:13288  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
16:00:12 T:12768  NOTICE: Creating audio stream (codec id: 86019, channels: 2, sample rate: 48000, no pass-through)
16:00:12 T:12768  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 32
16:00:12 T:13288  NOTICE:  fps: 25.000000, pwidth: 1280, pheight: 720, dwidth: 1280, dheight: 720
16:00:12 T:13288  NOTICE: Display resolution DESKTOP : 1920x1080@ 60.00 - Full Screen (16)
16:00:12 T:13288  NOTICE: D3D: rendering method forced to DXVA processor
16:00:12 T:13288  NOTICE: DXVA::CProcessorHD::InitProcessor - Supported deinterlace methods: Blend:yes, Bob:yes, Adaptive:yes, MoComp:no.
16:00:12 T:2176 WARNING: CPythonInvoker(50, C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect.tvshows-1.0.1\default.py): the python script "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect.tvshows-1.0.1\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::Player,class XBMCAddon::xbmc::PlayList
16:00:12 T:1304 WARNING: CWinRenderer::UpdateVideoFilter - chosen scaling method 1 is not supported by renderer
16:00:12 T:12768  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 3 packets of duration 32
16:00:12 T:12768  NOTICE: Previous line repeats 2 times.
16:00:12 T:12768  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 1 packets of duration 32
16:00:12 T:12768  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 32
16:00:12 T:8524  NOTICE: Previous line repeats 1 times.
16:00:12 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnPlay Data: {u'item': {u'type': u'episode', u'id': 1126}, u'player': {u'playerid': 1, u'speed': 1}}
16:00:12 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Currently playing file is: D:\HDTV 4\Bad Education\Season 1\Bad Education - S01E04.mkv
16:00:12 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Playing itemtype is (or appears to be): episode
16:00:12 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Found Plex id 808378 for Kodi id None for type episode
16:00:12 T:8524  NOTICE: Using Image Cache Thread Count: 25 -> 1
16:00:12 T:8524  NOTICE: PlexKodiConnect API -> Found external subs: []
16:00:12 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Window properties set for direct paths!
16:00:12 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Finish playback startup
16:00:12 T:8524  NOTICE: PlexKodiConnect Player -> ONPLAYBACK_STARTED: D:\HDTV 4\Bad Education\Season 1\Bad Education - S01E04.mkv itemid: 808378
16:00:12 T:8524  NOTICE: PlexKodiConnect Player -> Playing itemtype is: episode
16:00:12 T:8524  NOTICE: PlexKodiConnect Player -> ADDING_FILE: {'itemType': u'episode', 'currentfile': 'D:\\HDTV 4\\Bad Education\\Season 1\\Bad Education - S01E04.mkv', 'SubtitleStreamIndex': '', 'AudioStreamIndex': 1, 'item_id': u'808378', 'Type': u'episode', 'playmethod': u'DirectPlay', 'refresh_id': u'808376', 'currentPosition': 315, 'playcount': 0, 'runtime': 1689, 'fileid': 2248}
16:00:15 T:1304  NOTICE: CDVDPlayer::CloseFile()
16:00:15 T:1304  NOTICE: DVDPlayer: waiting for threads to exit
16:00:15 T:832  NOTICE: CDVDPlayer::OnExit()
16:00:15 T:832  NOTICE: Closing stream player 1
16:00:15 T:832  NOTICE: Waiting for audio thread to exit
16:00:15 T:12768  NOTICE: thread end: CDVDPlayerAudio::OnExit()
16:00:15 T:832  NOTICE: Closing audio device
16:00:15 T:832  NOTICE: Deleting audio codec
16:00:15 T:832  NOTICE: Closing stream player 2
16:00:15 T:832  NOTICE: waiting for video thread to exit
16:00:15 T:13288  NOTICE: thread end: video_thread
16:00:15 T:832  NOTICE: deleting video codec
16:00:15 T:832  NOTICE: DXVA::CDecoder::Close - closing decoder
16:00:15 T:832  NOTICE: DXVA::Close - closing decoder context
16:00:15 T:1304  NOTICE: DVDPlayer: finished waiting
16:00:15 T:8524  NOTICE: PlexKodiConnect Player -> ONPLAYBACK_STOPPED
16:00:15 T:1304  NOTICE: CDVDPlayer::CloseFile()
16:00:15 T:1304  NOTICE: DVDPlayer: waiting for threads to exit
16:00:15 T:1304  NOTICE: DVDPlayer: finished waiting
16:00:15 T:1304  NOTICE: CDVDPlayer::CloseFile()
16:00:15 T:1304  NOTICE: DVDPlayer: waiting for threads to exit
16:00:15 T:1304  NOTICE: DVDPlayer: finished waiting
16:00:15 T:8524  NOTICE: PlexKodiConnect Player -> Played_information: {'D:\\HDTV 4\\Bad Education\\Season 1\\Bad Education - S01E04.mkv': {'itemType': u'episode', 'currentfile': 'D:\\HDTV 4\\Bad Education\\Season 1\\Bad Education - S01E04.mkv', 'SubtitleStreamIndex': '', 'AudioStreamIndex': 1, 'item_id': u'808378', 'Type': u'episode', 'playmethod': u'DirectPlay', 'refresh_id': u'808376', 'currentPosition': 315, 'playcount': 0, 'runtime': 1689, 'fileid': 2248}}
16:00:15 T:8524  NOTICE: PlexKodiConnect Player -> Percent complete: 0.186500888099 Mark played at: 0.9
16:00:15 T:8524  NOTICE: PlexKodiConnect Player -> Clear playlist properties.
16:00:15 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: Player.OnStop Data: {u'item': {u'type': u'episode', u'id': 1126}, u'end': False}
16:00:15 T:8524  NOTICE: PlexKodiConnect KodiMonitor -> Method: VideoLibrary.OnUpdate Data: {u'item': {u'type': u'episode', u'id': 1126}}
16:00:15 T:11688  NOTICE: Using Image Cache Thread Count: 25 -> 1
16:00:15 T:11688  NOTICE: plugin.video.plexkodiconnect started
16:00:15 T:11688  NOTICE: PlexKodiConnect - Full sys.argv received: ['plugin://plugin.video.plexkodiconnect/', '28', '?id=2&mode=ondeck&type=tvshows&tagname=TV Shows&limit=100']
16:00:15 T:11688  NOTICE: PlexKodiConnect DownloadUtils -> Request session does not exist: start one
16:00:15 T:11688  NOTICE: PlexKodiConnect DownloadUtils -> Verify SSL certificates set to: false
16:00:15 T:11688  NOTICE: PlexKodiConnect DownloadUtils -> SSL client side certificate set to: None
16:00:15 T:11688  NOTICE: PlexKodiConnect DownloadUtils -> Set server: https://192.168.0.2:32400
16:00:15 T:11688  NOTICE: PlexKodiConnect DownloadUtils -> Set token: xxxxxxx
16:00:15 T:11688  NOTICE: PlexKodiConnect DownloadUtils -> Set userId: xxxxxxxx
16:00:15 T:11688  NOTICE: PlexKodiConnect DownloadUtils -> Set username: Rich
16:00:15 T:11688  NOTICE: PlexKodiConnect DownloadUtils -> Requests session started on: https://192.168.0.2:32400
16:00:16 T:11688  NOTICE: Using Image Cache Thread Count: 25 -> 1
16:00:16 T:11688  NOTICE: PlexKodiConnect Playlist -> Initiated video playlist
16:00:16 T:11688  NOTICE: Using Image Cache Thread Count: 25 -> 1
16:00:16 T:11688  NOTICE: Previous line repeats 28 times.
16:00:16 T:11688  NOTICE: plugin.video.plexkodiconnect stopped
16:00:16 T:11688 WARNING: CPythonInvoker(52, C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py): the python script "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.plexkodiconnect\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::Player,class XBMCAddon::xbmc::PlayList

**Comment by croneter** [comment]
Please post the entire log, e.g. here: www.pastebin.com

**Comment by richardap1** [comment]
http://pastebin.com/QPtkHBsW

**Comment by roc16** [comment]
hi Guys,
I have the same issue except I use Addon(Default) with Direct play and customize unc paths enabled (smb shares are setup).

**Comment by Daywalker442000** [comment]
Cannot start anything over widgets (Titan Skin)

PlayMedia could not play media: plugin://plugin.video.plexkodiconnect.movies/?dbid=297&mode=play&id=28850&filename=%2Flibrary%2Fmetadata%2F28850

**Comment by roc16** [comment]
Happens in Titan and amber skin for me. Not tried another one.
