### ISSUE TITLE
Kodi add-on "Globalsearch" does not work with Add-on Paths

### ISSUE THREAD

**Issue by rmellid** [croneter/PlexKodiConnect#963]
The movie (or TV show) doesn't start when I use the search engine. I can  search the media without problem, select it, and when I play the movie, nothing happend.

[kodi_prob_search.log](https://github.com/croneter/PlexKodiConnect/files/3485425/kodi_prob_search.log)

**Comment by rmellid** [comment]
little more precision, it happen when I use this:
![pkc](https://user-images.githubusercontent.com/53934742/62795073-22bba000-bad6-11e9-8be3-f100abd0e75d.png)

**Comment by croneter** [comment]
This does not concern "vanilla" Kodi but the Kodi add-on `globalsearch`. 

Easiest way to fix this for now: use PlexKodiConnect [Direct Paths](https://github.com/croneter/PlexKodiConnect/wiki/Set-up-Direct-Paths). That should do it. 

I can't do anything else from the PKC side. Please take this up with the globalsearch developers e.g. in the Kodi forum. globalsearch somehow can't deal with add-on file paths in the Kodi database.

**Comment by rmellid** [comment]
Thanks for your answer. I ask the "Globalsearch" developer about my request....  waiting now...

**Comment by croneter** [comment]
Could you link the request here please?

**Comment by rmellid** [comment]
Of course:

https://forum.kodi.tv/showthread.php?tid=109301&page=37

**Comment by rmellid** [comment]
Hello,
FYI, I tried the last beta version 2.9.6, now it works with "add-on path" in synchronisation menu and "try direct play" in playback menu. It's really good. Works fine.

**Comment by croneter** [comment]
Great, thanks for reporting back this this issue is fixed!
