### ISSUE TITLE
Kodi Remote Apps (Kore, Yatse and Kodi Remote) crashes Kodi after moving to PKC

### ISSUE THREAD

**Issue by bricor1709** [croneter/PlexKodiConnect#966]
Recently moved to PKC to manage my Kodi DB as the various scapers in Kodi struggled to find/scrape my media libraries properly.
Love it and it works great. Using Addon path as opposed to direct path.
Only issue now seems that most Kodi Remote apps crash Kodi now when a media file gets selected to be played.
The Remote app connects fine, sync fine, works fine as an air mouse or touch pad and plays Music files fine(not managed bt PKC)
Any Movie, music video or TV file crashes (close kodi)
Funny thing though that 4Head Kodi Remote App works fine.

Please pardon my ignorance in the functional coding issues here. The only common denominator here according to my ignorant eyes is that PKC gets called and in the case of 4Head seem to find the path to the media file.

[Kodi log for 4Head.txt](https://github.com/croneter/PlexKodiConnect/files/3488579/Kodi.log.for.4Head.txt)
[Kodi log for Kore.txt](https://github.com/croneter/PlexKodiConnect/files/3488580/Kodi.log.for.Kore.txt)
[Kodi log for Kodi Remote.txt](https://github.com/croneter/PlexKodiConnect/files/3488584/Kodi.log.for.Kodi.Remote.txt)

A look at the Kodi Log files indicate that the 'play' function seems to call PKC sub routines or something before it crashes in all three the Apps that fails, same with 4Head but then 4Head continues where the others just close Kodi.
Is this a known issue?
Would changing to Direct paths as opposed to Addon paths help?

**Comment by croneter** [comment]
Works fine here with Yatse!

Please share the entire DEBUG log as explained here, not just excerpts, especially for Yatse as I consider that the best Kodi remote 😉 : https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

It would most probably help to use PlexKodiConnect Direct Paths.

**Comment by bricor1709** [comment]
Hi thanks for the reply.  Find attached two log files

Yatse crashing
[Kodi Yatze log.txt](https://github.com/croneter/PlexKodiConnect/files/3488837/Kodi.Yatze.log.txt)

Log file with 4Head starting and playing a video file then being stopped and then Kore crashing Kodi

[Kodi log 4Head then Kore.txt](https://github.com/croneter/PlexKodiConnect/files/3488838/Kodi.log.4Head.then.Kore.txt)

In all instances it was the same movie file, played from the same place
Drop down Menu>Movies>3 Nights in the Desert>Play

**Comment by croneter** [comment]
You got other add-ons causing problems, namely `plugin.video.FladnagSports`:
```
2019-08-10 14:06:53.863 T:17508   DEBUG: Service XML Parse Exception - Trakt API Token 
                                             Traceback (most recent call last):
                                              File "C:\Users\Brian\AppData\Roaming\Kodi\addons\plugin.video.FladnagSports\service.py", line 298, in get_my_settings
                                                TRAKT_ACCESS_TOKEN = re.findall('default="(.+?)"', TRAKT_ACCESS_TOKEN.group())[0]
```
as well as `plugin.video.limitless`
```
2019-08-10 14:34:47.322 T:9692   DEBUG: Service XML Parse Exception - Trakt API Token 
                                             Traceback (most recent call last):
                                              File "C:\Users\Brian\AppData\Roaming\Kodi\addons\plugin.video.limitless\service.py", line 298, in get_my_settings
                                                TRAKT_ACCESS_TOKEN = re.findall('default="(.+?)"', TRAKT_ACCESS_TOKEN.group())[0]
                                            IndexError: list index out of range
```
Both errors seem related to Trakt. 


There is nothing suspicious from the PlexKodiConnect side, nothing I could pinpoint. I suggest you start from scratch with a clean Kodi, install PKC and go from there... 

Closing this issue for now as I'm pretty sure PKC is not the culprit. Please reopen it if your crashes persist with a clean Kodi.

**Comment by bricor1709** [comment]
Tried with direct path and everything works. Could only do it with a small sample though as my library is spread over 6 drives and doing it for all drives is going to be impossible due to the way the drives are currently set up.   
  
One folder on Root>MOVIES>folders with single movie.   
  
6 drives set up exactly the same only alphabeticaly divided a-d, e-i, j-p etc.   
  
IN PLEX     
  
Libraries>movies>folders(x:\movies, z:\movies etc
  
Cannot see a way to do this through PKC settings in custom paths
  
  
  

  
  
  
  
  
>

**Comment by croneter** [comment]
Please try with a clean Kodi installation

**Comment by croneter** [comment]
To still use Direct Paths, you can use "Option 2" of setting them up: https://github.com/croneter/PlexKodiConnect/wiki/Option-2-Substitute-Paths-on-the-PMS

Please try with Add-on Paths and a clean Kodi installation first though, as I cannot replicate your issue

**Comment by parlarkin** [comment]
I have the same issue. And it is on a clean install.
Fresh installation of Kodi (kodi-18.3-Leia-x64) and installed PKC with Add-on paths.
I've since installed a couple of skins but nothing else.

Kodi application and Plex integration works brilliantly (OMG thank you!) and the remote works well. But selecting any TV show or movie (not tried with music because I don't have any) on my Android phone, always crashes Kodi. It has never worked.

I haven't tried the Direct paths method yet, because it seems like I've got to re-jig my filing system which I'm not ready to do. I'm not complaining cos its still really useful! I'm just reporting the same issue. Sorry I've not got much developer chops and I don't know much about getting log files etc. I'm not a complete noob so if you, bricor or anyone else wants to direct me, I'll happily upload if it would help.

**Comment by croneter** [comment]
@parlarkin please see here for instructions on how to get logs: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug
There should be an Android section in the links provided there.

**Comment by parlarkin** [comment]
Please find my log file attached from my desktop machine. I'm still looking into how I find it on Android. Thanks
[kodilog.txt](https://github.com/croneter/PlexKodiConnect/files/3512056/kodilog.txt)

**Comment by parlarkin** [comment]
Here's the Android Yatse log, and the Desktop Kodi log (from the same event)
[Desktop Kodi Log.txt](https://github.com/croneter/PlexKodiConnect/files/3525510/Desktop.Kodi.Log.txt)
[Yatse debug log.txt](https://github.com/croneter/PlexKodiConnect/files/3525511/Yatse.debug.log.txt)

**Comment by croneter** [comment]
Is this still an issue with PKC version 2.10.0?

**Comment by croneter** [comment]
I guess this issue has been solved

**Comment by parlarkin** [comment]
Sorry, upgraded my computer recently so only just reinstalled. All is working perfectly - cheers!
