### ISSUE TITLE
PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401

### ISSUE THREAD

**Issue by Goga777** [croneter/PlexKodiConnect#97]
witek play + librelec LibreELEC (Krypton) v7.90.005 ALPHA with internal flash

In the log I have strange messages like

14:29:15 T:2630591392  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
14:29:15 T:2895115168   ERROR: CecLogMessage - Write: write failed !
14:29:16 T:2630591392  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
14:29:16 T:2630591392  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
14:29:16 T:2895115168   ERROR: CecLogMessage - Write: write failed !
14:29:17 T:2630591392   ERROR: Previous line repeats 1 times.
14:29:17 T:2630591392  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
14:29:17 T:2895115168   ERROR: CecLogMessage - Write: write failed !
14:29:17 T:2630591392   ERROR: Previous line repeats 1 times.
14:29:17 T:2630591392  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
14:29:18 T:2630591392  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
14:29:18 T:2895115168   ERROR: CecLogMessage - Write: write failed !
14:29:19 T:2630591392  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
14:29:19 T:2895115168   ERROR: CecLogMessage - Write: write failed !
14:29:20 T:2630591392  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
14:29:20 T:2895115168   ERROR: CecLogMessage - Write: write failed !
14:29:20 T:2630591392  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
14:29:20 T:2895115168   ERROR: CecLogMessage - Write: write failed !
14:29:21 T:2630591392  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
14:29:21 T:2630591392  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
14:29:21 T:2895115168   ERROR: CecLogMessage - Write: write failed !

[kodi.log.gz](https://github.com/croneter/PlexKodiConnect/files/453426/kodi.log.gz)

**Comment by croneter** [comment]
Hmm, something with your storage seems off, these messages are not boding well (and have nothing to do with PKC):
```
14:31:14 T:2895115168   ERROR: CecLogMessage - Write: write failed !
14:31:14 T:2630591392   ERROR: Previous line repeats 1 times.
```
Apart from that, you might have revoked your Plex token. Try resetting the addon: PKC Settings -> Butten `Defaults`. Then restart Kodi

**Comment by Goga777** [comment]
it is CEC messages, which doesn't have any link with the storages. I disabled CEC in the kodi system settings and such messages disappeared.

**Comment by croneter** [comment]
And resetting the PKC addon?

**Comment by Goga777** [comment]
after full reseting I have the following error

[code]
22:11:19 T:3035910144  NOTICE:         m_channels        : FL,FR,BL,BR,FC,LFE,SL,SR
22:11:19 T:3035910144  NOTICE:         m_sampleRates     : 8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000
22:11:19 T:3035910144  NOTICE:         m_dataFormats     : AE_FMT_RAW,AE_FMT_S16NE,AE_FMT_S16LE
22:11:19 T:3035910144  NOTICE:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512
22:11:19 T:3035910144  NOTICE: Enumerated PULSE devices:
22:11:19 T:3035910144  NOTICE:     Device 1
22:11:19 T:3035910144  NOTICE:         m_deviceName      : Default
22:11:19 T:3035910144  NOTICE:         m_displayName     : Default
22:11:19 T:3035910144  NOTICE:         m_displayNameExtra: Bluetooth Audio (PULSEAUDIO)
22:11:19 T:3035910144  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
22:11:19 T:3035910144  NOTICE:         m_channels        : FL,FR
22:11:19 T:3035910144  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
22:11:19 T:3035910144  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
22:11:19 T:3035910144  NOTICE:         m_streamTypes     : No passthrough capabilities
22:11:19 T:3035910144  NOTICE: Loaded settings file from special://xbmc/system/advancedsettings.xml
22:11:19 T:3035910144  NOTICE: Contents of special://xbmc/system/advancedsettings.xml are...
                                            <?xml version="1.0" encoding="UTF-8" ?>
                                            <advancedsettings>
                                              <showexitbutton>false</showexitbutton>
                                              <samba>
                                                <clienttimeout>30</clienttimeout>
                                              </samba>
                                              <pvr>
                                                <minvideocachelevel>5</minvideocachelevel>
                                                <minaudiocachelevel>20</minaudiocachelevel>
                                              </pvr>
                                            </advancedsettings>
22:11:19 T:3035910144  NOTICE: Loaded settings file from special://profile/advancedsettings.xml
22:11:19 T:3035910144  NOTICE: Contents of special://profile/advancedsettings.xml are...
                                            <advancedsettings>
                                              <network>
                                                <cachemembuffersize>52428800</cachemembuffersize>
                                              </network>
                                              <musiclibrary>
                                                <backgroundupdate>true</backgroundupdate>
                                              </musiclibrary>
                                            </advancedsettings>
22:11:19 T:3035910144  NOTICE: Default Video Player: VideoPlayer
22:11:19 T:3035910144  NOTICE: Default Audio Player: paplayer
22:11:19 T:3035910144  NOTICE: Disabled debug logging due to GUI setting. Level 0.
22:11:19 T:3035910144  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
22:11:19 T:3035910144  NOTICE: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
22:11:19 T:3035910144  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
22:11:19 T:3035910144  NOTICE: Loaded playercorefactory configuration
22:11:19 T:3035910144  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
22:11:19 T:3035910144  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
22:11:19 T:3035910144  NOTICE: Running database version Addons26
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.1orgar
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.xbmc.org
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.xbmc-israel
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.plexkodiconnect
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.unofficial.addon.pro
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.kodi.game
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.plexbmc.addons
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.libreelec.tv
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.myshows.me
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.mnn
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.search.db
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.plexkodiconnectbeta
22:11:19 T:3035910144  NOTICE: ADDONS: Using repository repository.tdw1980
22:11:19 T:3035910144  NOTICE: InitWindowSystem: Using EGL Implementation: amlogic
22:11:19 T:3035910144  NOTICE: Found resolution 720 x 480 for display 0 with 720 x 480 @ 60.000000 Hz
22:11:19 T:3035910144  NOTICE: Found resolution 720 x 576 for display 0 with 720 x 576 @ 50.000000 Hz
22:11:19 T:3035910144  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 60.000000 Hz
22:11:19 T:3035910144  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080i @ 60.000000 Hz
22:11:19 T:3035910144  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 60.000000 Hz
22:11:19 T:3035910144  NOTICE: Found resolution 1280 x 720 for display 0 with 1280 x 720 @ 50.000000 Hz
22:11:19 T:3035910144  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080i @ 50.000000 Hz
22:11:19 T:3035910144  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 50.000000 Hz
22:11:19 T:3035910144  NOTICE: Found resolution 1920 x 1080 for display 0 with 1920 x 1080 @ 24.000000 Hz
22:11:19 T:3035910144  NOTICE: Found (1920x1080@50.000000) at 23, setting to RES_DESKTOP at 16
22:11:19 T:3035910144  NOTICE: Checking resolution 16
22:11:19 T:3035910144  NOTICE: GL_VENDOR = ARM
22:11:19 T:3035910144  NOTICE: GL_RENDERER = Mali-400 MP
22:11:19 T:3035910144  NOTICE: GL_VERSION = OpenGL ES 2.0
22:11:19 T:3035910144  NOTICE: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 1.00
22:11:19 T:3035910144  NOTICE: GL_EXTENSIONS = GL_OES_texture_npot GL_OES_vertex_array_object GL_OES_compressed_ETC1_RGB8_texture GL_EXT_compressed_ETC1_RGB8_sub_texture GL_OES_standard_derivatives GL_OES_EGL_image GL_OES_depth24 GL_ARM_rgba8 GL_ARM_mali_shader_binary GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_format_BGRA8888 GL_OES_vertex_half_float GL_EXT_blend_minmax GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_rgb8_rgba8 GL_EXT_multisampled_render_to_texture GL_EXT_discard_framebuffer GL_OES_get_program_binary GL_ARM_mali_program_binary GL_EXT_shader_texture_lod GL_EXT_robustness GL_OES_depth_texture_cube_map GL_KHR_debug GL_ARM_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_mapbuffer
22:11:20 T:3035910144  NOTICE: Running database version Addons26
22:11:20 T:3035910144  NOTICE: Running database version ViewModes6
22:11:20 T:3035910144  NOTICE: Running database version Textures13
22:11:20 T:3035910144  NOTICE: Running database version MyMusic60
22:11:20 T:3035910144  NOTICE: Running database version MyVideos107
22:11:20 T:3035910144  NOTICE: Running database version TV29
22:11:20 T:3035910144  NOTICE: Running database version Epg11
22:11:20 T:3035910144  NOTICE: start dvd mediatype detection
22:11:20 T:2923422624  NOTICE: Register - new cec device registered on cec->Amlogic: CEC Adapter (0000:0000)
22:11:20 T:2931811232  NOTICE: Register - new hid device registered on usb->/sys/devices/lm1/usb1/1-1/1-1.1: WETEK Play remote (2252:0106)
22:11:21 T:3035910144 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
22:11:21 T:3035910144   ERROR: JSONRPC: Unable to parse JSON Schema definition for ""
22:11:21 T:3035910144   ERROR: JSONRPC: Invalid JSON Schema definition for method ""
22:11:21 T:3035910144   ERROR: Window Translator: Can't find window videolibrary
22:11:21 T:3035910144   ERROR: Previous line repeats 1 times.
22:11:21 T:3035910144   ERROR: Window Translator: Can't find window musiclibrary
22:11:21 T:3035910144   ERROR: Window Translator: Can't find window musicfiles
22:11:21 T:3035910144  NOTICE: initialize done
22:11:21 T:3035910144  NOTICE: Running the application...
22:11:21 T:3035910144  NOTICE: CWebServer[8080]: Started
22:11:21 T:3035910144  NOTICE: starting upnp client
22:11:21 T:2898256800  NOTICE: [script.torrent-tv.ru.pp::STARTUP] script.torrent-tv.ru.pp v.1.3.4
22:11:23 T:2863674272 WARNING: CSkinInfo: failed to load skin settings
22:11:23 T:2889868192  NOTICE: PlexKodiConnect Service -> ======== START PlexKodiConnect ========
22:11:23 T:2889868192  NOTICE: PlexKodiConnect Service -> Platform: Linux
22:11:23 T:2889868192  NOTICE: PlexKodiConnect Service -> KODI Version: 17.0-BETA1 Git:81d5d26
22:11:23 T:2889868192  NOTICE: PlexKodiConnect Service -> PlexKodiConnect Version: 1.3.0
22:11:23 T:2889868192  NOTICE: PlexKodiConnect Service -> Using plugin paths: True
22:11:23 T:2889868192  NOTICE: PlexKodiConnect Service -> Log Level: 1
22:11:23 T:2889868192  NOTICE: PlexKodiConnect VideoNodes -> Clearing nodes properties.
22:11:23 T:2889868192  NOTICE: PlexKodiConnect InitialSetup -> Entering initialsetup class
22:11:23 T:2889868192  NOTICE: PlexKodiConnect InitialSetup -> Initial setup called.
22:11:23 T:2889868192  NOTICE: PlexKodiConnect ClientInfo -> Generating a new deviceid.
22:11:23 T:2889868192  NOTICE: PlexKodiConnect ClientInfo -> Unique device Id plex_client_Id loaded: 2690a720-b9f9-4a89-aab9-1ed6893d3d4e
22:11:24 T:2889868192  NOTICE: PlexKodiConnect PlexAPI -> Successfully retrieved code and id from plex.tv
22:12:05 T:2889868192  NOTICE: PlexKodiConnect PlexAPI -> Checking with plex.tv for more PMS to connect to
22:12:08 T:2948588448   ERROR: PlexKodiConnect DownloadUtils -> Server unreachable at: https://192.168.1.10:32400/identity
22:12:08 T:2948588448  NOTICE: PlexKodiConnect DownloadUtils -> HTTPSConnectionPool(host='192.168.1.10', port=32400): Max retries exceeded with url: /identity (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xa3881490>, 'Connection to 192.168.1.10 timed out. (connect timeout=3)'))
22:12:11 T:2889868192  NOTICE: PlexKodiConnect PlexAPI -> Checking connection to server https://46-188-53-29.2de44db2da8c47128aaf52c61b822697.plex.direct:32400/library/onDeck with verifySSL=None
22:12:12 T:2889868192  NOTICE: PlexKodiConnect PlexAPI -> Checking connection successfull. Answer: 200
22:12:12 T:2889868192  NOTICE: PlexKodiConnect InitialSetup -> Setting SSL verify to true, because server is not local
22:12:12 T:2889868192  NOTICE: PlexKodiConnect InitialSetup -> Writing to Kodi user settings file
22:12:12 T:2889868192  NOTICE: PlexKodiConnect InitialSetup -> PMS machineIdentifier: f16bdbf006ba200403435048c99b2de8098154d2, ip: 46-188-53-29.2de44db2da8c47128aaf52c61b822697.plex.direct, port: 32400, https: https
22:12:25 T:2889868192  NOTICE: PlexKodiConnect InitialSetup -> User opted to disable Plex music library.
22:12:37 T:2889868192  NOTICE: PlexKodiConnect InitialSetup -> User thinks that PKC runs on a raspi or similar
22:12:37 T:2889868192   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'goToSettings' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 322, in <module>
                                                Service().ServiceEntryPoint()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/service.py", line 129, in ServiceEntryPoint
                                                initialsetup.InitialSetup().setup()
                                              File "/storage/.kodi/addons/plugin.video.plexkodiconnect/resources/lib/initialsetup.py", line 482, in setup
                                                if goToSettings is False:
                                            UnboundLocalError: local variable 'goToSettings' referenced before assignment
                                            -->End of Python script error report<--
22:12:37 T:2889868192 WARNING: CPythonInvoker(1, /storage/.kodi/addons/plugin.video.plexkodiconnect/service.py): the python script "/storage/.kodi/addons/plugin.video.plexkodiconnect/service.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon4xbmc6PlayerE,N9XBMCAddon9xbmcaddon5AddonE
[/code]

**Comment by croneter** [comment]
That bug will be fixed in next release. 

Try to restart Kodi. Working then?

**Comment by Goga777** [comment]
after kodi restart I still have in the lof that message

**Comment by croneter** [comment]
Please be as specific as possible and post the entire log again after the PKC reset you did. What message?

**Comment by Goga777** [comment]
I mean this old annoing message 

I attached log


23:43:34 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:35 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:35 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:36 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:36 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:37 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:38 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:39 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:39 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:40 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:40 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:41 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:42 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:43 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:43 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:44 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:44 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:45 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:46 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:47 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:47 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:48 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:48 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:49 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:50 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:51 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:51 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:52 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:52 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:53 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:53 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:54 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:54 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:55 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:56 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:57 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:57 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:43:58 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:43:59 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:44:00 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting
23:44:00 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Unknown exception encountered in connecting: Handshake Status 401
23:44:01 T:2682712992  NOTICE: PlexKodiConnect WebSocket -> Connection closed, (re)connecting


[log.zip](https://github.com/croneter/PlexKodiConnect/files/454108/log.zip)

**Comment by Goga777** [comment]
BTW - how to watch the channels on PLex in kodi ?

**Comment by croneter** [comment]
Does this issue still exist with the new PKC version?

Channels are not yet supported by PKC

**Comment by Goga777** [comment]
with new PKG the behavior has changed little bit. After the first restart of the PKG sometime I didn't see such annoying messages in the log  But after second restart I still see them. I can't say when they disappeared.

About the channels - when do you intend to implement the channels support ?

**Comment by Twit123** [comment]
Hi,

I can confirm this issue as well, the below is repeating about every second indefinitely, I have gone so far as to format the PC and reinstall Windows 10 and Kodi but the problem remains.

11:32:55 T:1352  NOTICE: PLEX.websocket_client -> ERROR:: Unknown exception encountered in connecting: Handshake Status 401
11:32:56 T:1352  NOTICE: PLEX.websocket_client -> Connection closed, (re)connecting

Kodi - 16.1 Jarvis
PKC - 1.4.5
PMS: 1.2.3 - On same local network as Kodi and I am signing in as a normal user (not admin)

On the PMS logs the corresponding repeating entries are:

Nov 04, 2016 11:32:55.072 [0x7f2e2cffe700] DEBUG - Request: [192.168.80.40:56154 (Subnet)] GET /:/websockets/notifications (5 live) TLS Signed-in Token ()
Nov 04, 2016 11:32:55.072 [0x7f2e2cffe700] DEBUG - Completed: [192.168.80.40:56154] 401 GET /:/websockets/notifications (5 live) TLS 0ms 285 bytes
Nov 04, 2016 11:32:56.141 [0x7f2e2d7ff700] DEBUG - Auth: We found auth token (xxxxxxxxxxxxxxxxxxxx), enabling token-based authentication.
Nov 04, 2016 11:32:56.141 [0x7f2e2d7ff700] DEBUG - Auth: authenticating user as guest

Any ideas?

Thanks

Simon
