### ISSUE TITLE
PKC is using account of server owner

### ISSUE THREAD

**Issue by SKrab91** [croneter/PlexKodiConnect#980]
Hello !

Since a few days I have problems with my PLEX home users in PKC. 
I created an user which can access all libraries except of one which should only be visible for the owner. After some days I can see the entire content (I guess PKC also snyc the watch-status of the owner account).
On kodi startup and in the PKC settings I see the correct account (which is obviously wrong). After logging out an in again the snyc status is correct and the wrong content is invisible. 
Is it possible to automate this process on startup so that the additional library will stay invisible ?
I am currently using Kodi 18.
Hope you have an solution for that.

**Comment by croneter** [comment]
This hopefully should be fixed shortly with #977

**Comment by croneter** [comment]
Does **BETA** version 2.9.6 help? Please let me know. 

If it does not help: Thanks for sharing your full DEBUG log according to https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug after first resetting the Kodi library, then waiting a couple of days until you notice the issue again.

**Comment by croneter** [comment]
I guess this issue is fixed. Let me know here otherwise...
