### ISSUE TITLE
Yatse crashes Kodi when playing Movie

### ISSUE THREAD

**Issue by abedo2015** [croneter/PlexKodiConnect#981]
Hi, I saw that someone has uploaded a similar question and I'm sorry that I'm asking a bit of a repeat, but I am having issues with starting a file on PKC with Yatse. Kodi will attempt to load the file and then immediately crash. I have provided the log file and any help would be greatly appreciated! Thank you.
[kodi.log](https://github.com/croneter/PlexKodiConnect/files/3567144/kodi.log)

**Comment by croneter** [comment]
Duplicate of #966
