### ISSUE TITLE
Kodi 18 - Absturz sobald PKC (aktuellster Build) startet

### ISSUE THREAD

**Issue by MikeDeltaHH** [croneter/PlexKodiConnect#996]
Guten Morgen!
Ich habe seit gestern Abend das Problem dass Kodi abstürzt und mein Vero 4K einen Reboot hinlegt sobald PKC startet - das betrifft alle eingerichteten Benutzer auf dem Vero 4K und ich habe keine Chance das Plugin abzuschalten oder sonstwie zu reagieren da dies zu schnell passiert... kannst Du mir helfen?

Viele Grüße!
Michael

**Comment by croneter** [comment]
Debug Logs bitte: https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug

Hast du etwas an deiner Kodi installation geändert?

**Comment by MikeDeltaHH** [comment]
Nein, nichts - es kam auch keinerlei Update! Ich habe am Abend vorher nur einen Film geschaut und dann den Vero heruntergefahren! Logs kann ich auch keine ziehen da ich überhaupt nicht bis in die Optinen komme, vorher ist Kodi schon abgeschmiert...

**Comment by croneter** [comment]
Theoretisch sollte PKC gar nicht in der Lage sein, Kodi zu crashen. Bitte setze Kodi komplett zurück, das sollte helfen: https://discourse.osmc.tv/t/factory-reset-vero-4k/72963

Ohne logs kann ich sonst überhaupt nicht helfen, sorry. Du kannst sonst logs via SSH holen.  **ACHTUNG** Dein log file enthält dein Plex Token, welches du vor dem Upload des logs löschen respektive ersetzen musst (siehe https://github.com/croneter/PlexKodiConnect/wiki/How-to-Report-A-Bug)

**Comment by MikeDeltaHH** [comment]
Moin! Ich hab Kodi komplett zurückgesetzt, so´n Problem ist mir auch noch nicht untergekommen... danke für deine Hilfe!

**Comment by croneter** [comment]
Cool hat's funktioniert! 😆 Danke für die Rückmeldung
