### ISSUE TITLE
PKC Play error

### ISSUE THREAD

**Issue by drt1** [croneter/PlexKodiConnect#999]
## Describe the bug
PKC on RasPi stopped working a few days ago without any prior update or change to the system.

## To Reproduce
1. Start kodi
2. Select any movie or tvshow and press play
3. See error popup "PlexKodiConnect Play Error"

Sometimes it only shows the popup error, sometimes a loading circle of death is added.

## Expected behavior
file should be played. ;)

## Log file
--removed log--
    
I noticed several lines with PMS_Websocket: WebSocketException: Handshake Status 401, can this be the reason? I have several other clients using PKC with the same plex-server and they are all working.
If I go to plex app on mobile phone, start playback from there and transfer it to the Pi, playback works as expected.

thanks for you help!
br

**Comment by croneter** [comment]
Did you try resetting the Kodi database (in the PKC settings under Advanced)?

**Comment by drt1** [comment]
yes, i did a complete reset of the kodi db but did NOT reset PKC settings.
didn't help either.

**Comment by croneter** [comment]
Try deleting the PlexKodiConnect addon as well as the 2 helper addons for movies and TV shows. Then reinstall only the PlexKodiConnect addon

**Comment by croneter** [comment]
Well, before that, try resetting PlexKodiConnect completely

**Comment by drt1** [comment]
hmm, ok, i deleted the PKC addon as well as the addons for movies and tvshows. didnt help. after that I processed a librelec and kodi update, reinstalled PKC.
syncing works, but now I get message on every file in the library "is not available, do you like to remove it".
hm... what can I try next?
i wanted to avoid a complete wipe of the pi, but now it looks like I have no choice.

**Comment by croneter** [comment]
Your setup for pkc direct paths is wrong:
```
Cannot access file: /mnt/auto/WD15EADS/dokus/Abgefuellt.2009.DVDRip.XviD-DOMiNO/domino-tapped.avi
```
Please choose addon paths in the PKC settings under Sync. Then reset the Kodi database under Advanced. 

I do not provide help for setting up direct paths as that would take too much time and is very dependent on your specific setup

**Comment by croneter** [comment]
See here for more info: https://github.com/croneter/PlexKodiConnect/wiki/Direct-Paths-Explained

**Comment by drt1** [comment]
after switching to "Addon" under sync I am stuck at the inital "Play Error" again

**Comment by croneter** [comment]
Did you reset the Kodi database again AFTER switching to addon paths? If yes, share your debug log again please

**Comment by drt1** [comment]
yes I did the reset after switching paths.
here u are: https://pastebin.com/MhuipMqF

**Comment by croneter** [comment]
PKC cannot get a play queue from the PMS. Could you please enable debug
logging for your PMS, then try to play something with Kodi, then share both
PMS and Kodi log? Sorry for all the log sharing....


drt1 <notifications@github.com> schrieb am So., 29. Sep. 2019, 13:40:

**Comment by drt1** [comment]
kodi.log: https://pastebin.com/fUUeN5NJ

PMS log: [Plex Media Server.log](https://github.com/croneter/PlexKodiConnect/files/3667375/Plex.Media.Server.log)

**Comment by croneter** [comment]
Really weird! Your get these errors in the PMS log: 
```
[0x7f1f3b7ff700] DEBUG - Request: [::ffff:192.168.0.100:33650 (Subnet)] POST /playQueues?shuffle=0&repeat=0&type=movie&uri=server%3A%2F%2F2ef6587b8ec66ef6ff250ec343feff6658da65f2%2Fcom.plexapp.plugins.library%2Flibrary%2Fmetadata%2F58235&includeChapters=1 (12 live) TLS Signed-in Token (<censored>@Home)
[0x7f1f3b7ff700] DEBUG - PlayQueue: 0 generated IDs compressed down to a 2 byte blob.
[0x7f1f3b7ff700] ERROR - LPE: only library URIs are allowed right now.
[0x7f1f3b7ff700] DEBUG - PlayQueue: Start index: 0 End index: -1 Count: 0
[0x7f1f3b7ff700] DEBUG - PlayQueue: 0 generated IDs compressed down to a 2 byte blob.
```
Can you please try and install the current beta version 2.9.7 of PKC and see if that helps? Simply install the beta PKC repository and "install" PKC again from there

**Comment by drt1** [comment]
ok i uninstalled pkc and movie and tvshow addon, installed 2.9.7 from beta repo - but no change, still says "play error". I will wait until the sync is finished to take new logs and see if something changed in there.

**Comment by croneter** [comment]
I think I found the bugger! 😆 I'll push another beta version very soon. Thanks very much for your patience!

**Comment by drt1** [comment]
nice, thanks for your quick and nice support!
you're welcome

**Comment by croneter** [comment]
Does the brand new beta version 2.9.8 help?

**Comment by drt1** [comment]
hmm, i dont see a new 2.9.8, no direct update, no new version in beta repo. hmm...

**Comment by croneter** [comment]
Go to Addons - my addons - options - check for updates

**Comment by drt1** [comment]
works great, you're awesome man, thanks!!! :)

for the update: auto-update didn't work, and then I tried to update the addon itself.
"check for updates" did the trick, tx.
